-- Câu hỏi trắc nghiệm Kinh Thánh chất lượng cao
-- Tạo bởi chuyên gia Kinh Thánh và sáng tạo nội dung học tập

-- Câu hỏi về Sáng Thế Ký (Genesis) - 20 câu
INSERT IGNORE INTO questions (id, book, chapter, verse_start, verse_end, difficulty, type, content, options, correct_answer, explanation, tags, source, language, is_active, created_at, updated_at) VALUES

-- Câu hỏi dễ (6 câu)
('q-gen-001', 'Genesis', 1, 1, 1, 'easy', 'multiple_choice_single',
'Trong câu đầu tiên của Kinh Thánh, "Ban đầu Đức Chúa Trời dựng nên trời đất" (Sáng 1:1), từ "ban đầu" trong tiếng Hê-bơ-rơ có nghĩa gì?',
'["Beresheet - Khởi nguyên tuyệt đối", "Rishon - Thứ nhất", "Tachlit - Mục đích", "Techilah - Bắt đầu"]',
'[0]',
'Beresheet (בראשית) có nghĩa là "khởi nguyên tuyệt đối", không chỉ là thời gian mà còn là nguyên lý cơ bản của vũ trụ.',
'["Cựu Ước", "Ngôn ngữ", "Khởi nguyên"]',
'Genesis 1:1',
'vi',
true,
NOW(),
NOW()),

('q-gen-002', 'Genesis', 2, 7, 7, 'easy', 'multiple_choice_single',
'Đức Chúa Trời đã tạo nên con người từ gì?',
'["Bụi đất", "Nước", "Không khí", "Lửa"]',
'[0]',
'Kinh Thánh ghi: "Giê-hô-va Đức Chúa Trời lấy bụi đất nắn nên hình người" (Sáng 2:7).',
'["Cựu Ước", "Sáng tạo", "Con người"]',
'Genesis 2:7',
'vi',
true,
NOW(),
NOW()),

('q-gen-003', 'Genesis', 3, 6, 6, 'easy', 'multiple_choice_single',
'Eva đã ăn trái cấm từ cây nào?',
'["Cây sự sống", "Cây biết điều thiện và điều ác", "Cây tri thức", "Cây khôn ngoan"]',
'[1]',
'Kinh Thánh ghi: "Người nữ thấy trái của cây đó... bèn hái ăn" - cây biết điều thiện và điều ác (Sáng 3:6).',
'["Cựu Ước", "Sa ngã", "Eva"]',
'Genesis 3:6',
'vi',
true,
NOW(),
NOW()),

('q-gen-004', 'Genesis', 4, 1, 1, 'easy', 'multiple_choice_single',
'Ai là con trai đầu lòng của Adam và Eva?',
'["Abel", "Cain", "Seth", "Enosh"]',
'[1]',
'Kinh Thánh ghi: "A-đam ăn ở với Ê-va, vợ mình; nàng thọ thai và sanh Ca-in" (Sáng 4:1).',
'["Cựu Ước", "Gia đình", "Cain"]',
'Genesis 4:1',
'vi',
true,
NOW(),
NOW()),

('q-gen-005', 'Genesis', 6, 9, 9, 'easy', 'multiple_choice_single',
'Noah được mô tả là người như thế nào?',
'["Công bình và trọn vẹn", "Khôn ngoan và giàu có", "Mạnh mẽ và dũng cảm", "Tốt lành và nhân từ"]',
'[0]',
'Kinh Thánh ghi: "Nô-ê là người công bình và trọn vẹn trong đời mình" (Sáng 6:9).',
'["Cựu Ước", "Nhân vật", "Noah"]',
'Genesis 6:9',
'vi',
true,
NOW(),
NOW()),

('q-gen-006', 'Genesis', 12, 1, 1, 'easy', 'multiple_choice_single',
'Đức Chúa Trời đã gọi Abraham ra khỏi đâu?',
'["Ur của người Canh-đê", "Babylon", "Ai Cập", "Damascus"]',
'[0]',
'Kinh Thánh ghi: "Hãy ra khỏi quê hương, khỏi gia tộc và khỏi nhà cha ngươi" - từ Ur của người Canh-đê (Sáng 12:1).',
'["Cựu Ước", "Gọi", "Abraham"]',
'Genesis 12:1',
'vi',
true,
NOW(),
NOW()),

-- Câu hỏi trung bình (10 câu)
('q-gen-007', 'Genesis', 1, 26, 26, 'medium', 'multiple_choice_single',
'Đức Chúa Trời đã tạo nên con người theo hình ảnh của ai?',
'["Thiên sứ", "Chính Ngài", "Các vì sao", "Các loài thú"]',
'[1]',
'Kinh Thánh ghi: "Chúng ta hãy làm nên loài người như hình ta và theo tượng ta" (Sáng 1:26).',
'["Cựu Ước", "Hình ảnh", "Sáng tạo"]',
'Genesis 1:26',
'vi',
true,
NOW(),
NOW()),

('q-gen-008', 'Genesis', 3, 15, 15, 'medium', 'multiple_choice_single',
'Trong lời tiên tri về Đấng Cứu Thế, ai sẽ "đạp đầu" của con rắn?',
'["Dòng dõi của người nữ", "Các thiên sứ", "Con trai của Adam", "Dân Y-sơ-ra-ên"]',
'[0]',
'Kinh Thánh ghi: "Dòng dõi người sẽ đạp đầu ngươi" - ám chỉ Đấng Mê-si-a sẽ đến từ dòng dõi của người nữ (Sáng 3:15).',
'["Cựu Ước", "Tiên tri", "Mê-si-a"]',
'Genesis 3:15',
'vi',
true,
NOW(),
NOW()),

('q-gen-009', 'Genesis', 4, 4, 4, 'medium', 'multiple_choice_single',
'Abel đã dâng lên Đức Chúa Trời vật gì?',
'["Con chiên đầu lòng", "Hoa quả đầu mùa", "Bánh mì", "Rượu nho"]',
'[0]',
'Kinh Thánh ghi: "A-bên cũng dâng chiên đầu lòng trong bầy chiên cùng mỡ nó" (Sáng 4:4).',
'["Cựu Ước", "Dâng hiến", "Abel"]',
'Genesis 4:4',
'vi',
true,
NOW(),
NOW()),

('q-gen-010', 'Genesis', 6, 14, 14, 'medium', 'multiple_choice_single',
'Noah được Đức Chúa Trời chỉ dẫn làm tàu bằng gỗ gì?',
'["Gỗ bá hương", "Gỗ ô-liu", "Gỗ bách", "Gỗ thông"]',
'[2]',
'Kinh Thánh ghi: "Hãy làm lấy một chiếc tàu bằng cây bách" (Sáng 6:14).',
'["Cựu Ước", "Tàu", "Noah"]',
'Genesis 6:14',
'vi',
true,
NOW(),
NOW()),

('q-gen-011', 'Genesis', 8, 11, 11, 'medium', 'multiple_choice_single',
'Con chim nào Noah thả ra cuối cùng và không quay về?',
'["Con quạ", "Con chim bồ câu", "Con chim én", "Con chim sẻ"]',
'[1]',
'Kinh Thánh ghi: "Con bồ câu bay về cùng người một cành ô-liu tươi" và không quay về nữa (Sáng 8:11).',
'["Cựu Ước", "Lũ lụt", "Chim bồ câu"]',
'Genesis 8:11',
'vi',
true,
NOW(),
NOW()),

('q-gen-012', 'Genesis', 11, 4, 4, 'medium', 'multiple_choice_single',
'Dân chúng xây tháp Babel với mục đích gì?',
'["Để lên trời", "Để làm danh cho mình", "Để tránh lũ lụt", "Để thờ phượng"]',
'[1]',
'Kinh Thánh ghi: "Chúng ta hãy xây một cái thành và dựng lên một cái tháp, chót cao đến tận trời; ta hãy làm rạng danh cho ta" (Sáng 11:4).',
'["Cựu Ước", "Tháp Babel", "Kiêu ngạo"]',
'Genesis 11:4',
'vi',
true,
NOW(),
NOW()),

('q-gen-013', 'Genesis', 12, 2, 2, 'medium', 'multiple_choice_single',
'Đức Chúa Trời hứa với Abraham sẽ làm cho ông thành gì?',
'["Một dân tộc lớn", "Một vương quốc", "Một đế chế", "Một thành phố"]',
'[0]',
'Kinh Thánh ghi: "Ta sẽ làm cho ngươi nên một dân lớn" (Sáng 12:2).',
'["Cựu Ước", "Lời hứa", "Abraham"]',
'Genesis 12:2',
'vi',
true,
NOW(),
NOW()),

('q-gen-014', 'Genesis', 15, 5, 5, 'medium', 'multiple_choice_single',
'Đức Chúa Trời dùng hình ảnh gì để mô tả dòng dõi của Abraham sẽ đông như?',
'["Cát biển", "Sao trên trời", "Lá cây", "Hạt cát"]',
'[1]',
'Kinh Thánh ghi: "Hãy ngước mắt lên trời và đếm các ngôi sao... dòng dõi ngươi cũng sẽ như vậy" (Sáng 15:5).',
'["Cựu Ước", "Lời hứa", "Dòng dõi"]',
'Genesis 15:5',
'vi',
true,
NOW(),
NOW()),

('q-gen-015', 'Genesis', 17, 5, 5, 'medium', 'multiple_choice_single',
'Tên "Abraham" có nghĩa gì?',
'["Cha của nhiều dân tộc", "Người được chọn", "Bạn của Đức Chúa Trời", "Người tin"]',
'[0]',
'Kinh Thánh ghi: "Tên ngươi sẽ là Áp-ra-ham, vì ta đặt ngươi làm cha nhiều dân tộc" (Sáng 17:5).',
'["Cựu Ước", "Tên", "Abraham"]',
'Genesis 17:5',
'vi',
true,
NOW(),
NOW()),

('q-gen-016', 'Genesis', 18, 12, 12, 'medium', 'multiple_choice_single',
'Sarah đã cười khi nghe tin gì?',
'["Sẽ có con trai", "Abraham sẽ sống lâu", "Dòng dõi sẽ đông", "Đất hứa sẽ thuộc về họ"]',
'[0]',
'Kinh Thánh ghi: "Sa-ra cười thầm mà rằng: Già như tôi, còn có sự vui thích nào được nữa?" (Sáng 18:12).',
'["Cựu Ước", "Sarah", "Cười"]',
'Genesis 18:12',
'vi',
true,
NOW(),
NOW()),

-- Câu hỏi khó (4 câu)
('q-gen-017', 'Genesis', 1, 2, 2, 'hard', 'multiple_choice_single',
'Trong câu "Thần của Đức Chúa Trời vận hành trên mặt nước", từ "vận hành" trong tiếng Hê-bơ-rơ có nghĩa gì?',
'["Ruach - Thổi", "Merachefet - Bay lượn như chim", "Shachav - Nằm", "Halach - Đi"]',
'[1]',
'Merachefet (מרחפת) có nghĩa là "bay lượn như chim", thể hiện sự chăm sóc và bảo vệ của Thần Đức Chúa Trời.',
'["Cựu Ước", "Ngôn ngữ", "Thần"]',
'Genesis 1:2',
'vi',
true,
NOW(),
NOW()),

('q-gen-018', 'Genesis', 14, 18, 18, 'hard', 'multiple_choice_single',
'Melchizedek là vua của thành nào và đồng thời là thầy tế lễ của Đức Chúa Trời nào?',
'["Salem - Đức Chúa Trời Tối Cao", "Jerusalem - Đức Chúa Trời của Abraham", "Zion - Đức Chúa Trời của Isaac", "Canaan - Đức Chúa Trời của Jacob"]',
'[0]',
'Kinh Thánh ghi: "Mên-chi-xê-đéc, vua Sa-lem, thầy tế lễ của Đức Chúa Trời Tối Cao" (Sáng 14:18).',
'["Cựu Ước", "Melchizedek", "Tế lễ"]',
'Genesis 14:18',
'vi',
true,
NOW(),
NOW()),

('q-gen-019', 'Genesis', 22, 2, 2, 'hard', 'multiple_choice_single',
'Đức Chúa Trời yêu cầu Abraham dâng Isaac làm của lễ thiêu trên núi nào?',
'["Núi Moriah", "Núi Sinai", "Núi Carmel", "Núi Zion"]',
'[0]',
'Kinh Thánh ghi: "Hãy đi đến xứ Mô-ri-a, nơi đó dâng đứa con trai ngươi làm của lễ thiêu" (Sáng 22:2).',
'["Cựu Ước", "Dâng hiến", "Isaac"]',
'Genesis 22:2',
'vi',
true,
NOW(),
NOW()),

('q-gen-020', 'Genesis', 32, 28, 28, 'hard', 'multiple_choice_single',
'Tên "Israel" có nghĩa gì và được đặt cho ai?',
'["Người chiến đấu với Đức Chúa Trời - Jacob", "Người được Đức Chúa Trời chọn - Abraham", "Người thấy Đức Chúa Trời - Isaac", "Người phục vụ Đức Chúa Trời - Joseph"]',
'[0]',
'Kinh Thánh ghi: "Tên ngươi sẽ chẳng phải là Gia-cốp nữa, nhưng là Y-sơ-ra-ên; vì ngươi đã đấu tranh với Đức Chúa Trời và với người ta, và đã thắng" (Sáng 32:28).',
'["Cựu Ước", "Tên", "Israel"]',
'Genesis 32:28',
'vi',
true,
'system',
NOW(),
NOW());

-- Câu hỏi về Xuất Ê-díp-tô Ký (Exodus) - 20 câu
INSERT IGNORE INTO questions (id, book, chapter, verse_start, verse_end, difficulty, type, content, options, correct_answer, explanation, tags, source, language, is_active, created_by, created_at, updated_at) VALUES

-- Câu hỏi dễ (6 câu)
('q-exo-001', 'Exodus', 2, 10, 10, 'easy', 'multiple_choice_single',
'Moses được nuôi dưỡng bởi ai?',
'["Con gái của Pharaoh", "Mẹ ruột", "Chị gái", "Bà ngoại"]',
'[0]',
'Kinh Thánh ghi: "Con gái Pha-ra-ôn nói: Hãy đem đứa trẻ này đi cho ta bú mớm" (Xuất 2:10).',
'["Cựu Ước", "Moses", "Pharaoh"]',
'Exodus 2:10',
'vi',
true,
NOW(),
NOW()),

('q-exo-002', 'Exodus', 3, 2, 2, 'easy', 'multiple_choice_single',
'Moses thấy gì trong bụi gai?',
'["Một ngọn lửa", "Một thiên sứ", "Một con rắn", "Một cây cột lửa"]',
'[0]',
'Kinh Thánh ghi: "Thiên sứ của Đức Giê-hô-va hiện ra cùng người trong ngọn lửa, giữa bụi gai" (Xuất 3:2).',
'["Cựu Ước", "Moses", "Bụi gai"]',
'Exodus 3:2',
'vi',
true,
NOW(),
NOW()),

('q-exo-003', 'Exodus', 4, 2, 2, 'easy', 'multiple_choice_single',
'Đức Chúa Trời đã biến cây gậy của Moses thành gì?',
'["Con rắn", "Con chim", "Cây cột", "Ngọn lửa"]',
'[0]',
'Kinh Thánh ghi: "Môi-se ném gậy xuống đất, gậy hóa ra một con rắn" (Xuất 4:3).',
'["Cựu Ước", "Phép lạ", "Moses"]',
'Exodus 4:3',
'vi',
true,
NOW(),
NOW()),

('q-exo-004', 'Exodus', 7, 20, 20, 'easy', 'multiple_choice_single',
'Phép lạ đầu tiên Moses làm trước Pharaoh là gì?',
'["Biến nước thành máu", "Gọi ếch nhái", "Tạo mưa đá", "Gây bóng tối"]',
'[0]',
'Kinh Thánh ghi: "Môi-se và A-rôn làm y như lời Đức Giê-hô-va đã phán... nước sông hóa ra máu" (Xuất 7:20).',
'["Cựu Ước", "Phép lạ", "Máu"]',
'Exodus 7:20',
'vi',
true,
NOW(),
NOW()),

('q-exo-005', 'Exodus', 12, 3, 3, 'easy', 'multiple_choice_single',
'Lễ Vượt Qua được cử hành vào tháng nào?',
'["Tháng Giêng", "Tháng Hai", "Tháng Ba", "Tháng Tư"]',
'[0]',
'Kinh Thánh ghi: "Trong ngày mồng mười tháng này, mỗi gia trưởng phải bắt một con chiên" (Xuất 12:3).',
'["Cựu Ước", "Lễ Vượt Qua", "Tháng"]',
'Exodus 12:3',
'vi',
true,
NOW(),
NOW()),

('q-exo-006', 'Exodus', 14, 21, 21, 'easy', 'multiple_choice_single',
'Moses đã làm gì để chia Biển Đỏ?',
'["Giơ tay lên", "Đập gậy xuống", "Cầu nguyện", "Hát thánh ca"]',
'[0]',
'Kinh Thánh ghi: "Môi-se giơ tay lên trên biển... Đức Giê-hô-va dẫn nước lui" (Xuất 14:21).',
'["Cựu Ước", "Biển Đỏ", "Moses"]',
'Exodus 14:21',
'vi',
true,
NOW(),
NOW()),

-- Câu hỏi trung bình (10 câu)
('q-exo-007', 'Exodus', 3, 14, 14, 'medium', 'multiple_choice_single',
'Đức Chúa Trời tự xưng mình là gì với Moses?',
'["Ta là Đấng Tự Hữu", "Ta là Đấng Toàn Năng", "Ta là Đấng Thánh", "Ta là Đấng Chân Thật"]',
'[0]',
'Kinh Thánh ghi: "Đức Chúa Trời phán rằng: Ta là Đấng Tự Hữu Hằng Hữu" (Xuất 3:14).',
'["Cựu Ước", "Danh", "Đức Chúa Trời"]',
'Exodus 3:14',
'vi',
true,
NOW(),
NOW()),

('q-exo-008', 'Exodus', 5, 2, 2, 'medium', 'multiple_choice_single',
'Pharaoh đã trả lời Moses như thế nào khi được yêu cầu thả dân Y-sơ-ra-ên đi?',
'["Đức Giê-hô-va là ai?", "Ta không biết Đức Giê-hô-va", "Ta sẽ không thả dân này đi", "Cả ba câu trên"]',
'[3]',
'Kinh Thánh ghi: "Pha-ra-ôn đáp rằng: Đức Giê-hô-va là ai, mà ta phải vâng lời người để cho Y-sơ-ra-ên đi?" (Xuất 5:2).',
'["Cựu Ước", "Pharaoh", "Từ chối"]',
'Exodus 5:2',
'vi',
true,
NOW(),
NOW()),

('q-exo-009', 'Exodus', 8, 7, 7, 'medium', 'multiple_choice_single',
'Pharaoh đã gọi ai để làm phép lạ tương tự như Moses?',
'["Các thầy phù thủy", "Các thầy tế lễ", "Các quan cận thần", "Các thầy bói"]',
'[0]',
'Kinh Thánh ghi: "Pha-ra-ôn bèn đòi các thầy phù thủy và thuật sĩ" (Xuất 8:7).',
'["Cựu Ước", "Phù thủy", "Pharaoh"]',
'Exodus 8:7',
'vi',
true,
NOW(),
NOW()),

('q-exo-010', 'Exodus', 12, 7, 7, 'medium', 'multiple_choice_single',
'Máu của chiên con trong Lễ Vượt Qua được bôi ở đâu?',
'["Cửa nhà", "Cửa sổ", "Mái nhà", "Sân nhà"]',
'[0]',
'Kinh Thánh ghi: "Họ sẽ lấy huyết đem bôi trên hai cây cột và mày cửa của nhà" (Xuất 12:7).',
'["Cựu Ước", "Lễ Vượt Qua", "Máu"]',
'Exodus 12:7',
'vi',
true,
NOW(),
NOW()),

('q-exo-011', 'Exodus', 15, 1, 1, 'medium', 'multiple_choice_single',
'Sau khi vượt qua Biển Đỏ, Moses và dân Y-sơ-ra-ên đã làm gì?',
'["Cầu nguyện", "Hát thánh ca", "Dâng của lễ", "Nhảy múa"]',
'[1]',
'Kinh Thánh ghi: "Bấy giờ Môi-se và dân Y-sơ-ra-ên hát bài ca nầy cho Đức Giê-hô-va" (Xuất 15:1).',
'["Cựu Ước", "Thánh ca", "Moses"]',
'Exodus 15:1',
'vi',
true,
NOW(),
NOW()),

('q-exo-012', 'Exodus', 16, 4, 4, 'medium', 'multiple_choice_single',
'Đức Chúa Trời đã ban cho dân Y-sơ-ra-ên thức ăn gì từ trời?',
'["Manna", "Bánh mì", "Cơm", "Khoai tây"]',
'[0]',
'Kinh Thánh ghi: "Nầy, ta sẽ làm cho bánh từ trên trời rơi xuống" - đó là manna (Xuất 16:4).',
'["Cựu Ước", "Manna", "Thức ăn"]',
'Exodus 16:4',
'vi',
true,
NOW(),
NOW()),

('q-exo-013', 'Exodus', 17, 6, 6, 'medium', 'multiple_choice_single',
'Moses đã lấy nước từ đâu khi dân Y-sơ-ra-ên khát nước?',
'["Từ hòn đá", "Từ cây cối", "Từ giếng", "Từ suối"]',
'[0]',
'Kinh Thánh ghi: "Ta sẽ đứng trước mặt ngươi, trên hòn đá ở Hô-rếp; ngươi sẽ đập hòn đá, nước sẽ bởi đó chảy ra" (Xuất 17:6).',
'["Cựu Ước", "Nước", "Hòn đá"]',
'Exodus 17:6',
'vi',
true,
NOW(),
NOW()),

('q-exo-014', 'Exodus', 20, 3, 3, 'medium', 'multiple_choice_single',
'Điều răn đầu tiên là gì?',
'["Trước mặt ta chớ có các thần khác", "Chớ làm tượng chạm", "Chớ lấy danh Đức Giê-hô-va làm chơi", "Nhớ ngày nghỉ"]',
'[0]',
'Kinh Thánh ghi: "Trước mặt ta chớ có các thần khác" (Xuất 20:3).',
'["Cựu Ước", "Mười điều răn", "Thần"]',
'Exodus 20:3',
'vi',
true,
NOW(),
NOW()),

('q-exo-015', 'Exodus', 24, 12, 12, 'medium', 'multiple_choice_single',
'Moses lên núi Sinai để làm gì?',
'["Nhận hai bảng đá", "Cầu nguyện", "Gặp Đức Chúa Trời", "Nghỉ ngơi"]',
'[0]',
'Kinh Thánh ghi: "Đức Giê-hô-va phán cùng Môi-se rằng: Hãy lên núi, đến cùng ta, và ở đó; ta sẽ ban cho ngươi hai bảng đá" (Xuất 24:12).',
'["Cựu Ước", "Núi Sinai", "Bảng đá"]',
'Exodus 24:12',
'vi',
true,
NOW(),
NOW()),

('q-exo-016', 'Exodus', 32, 4, 4, 'medium', 'multiple_choice_single',
'Dân Y-sơ-ra-ên đã làm con bò vàng bằng gì?',
'["Vàng", "Bạc", "Đồng", "Sắt"]',
'[0]',
'Kinh Thánh ghi: "A-rôn nhận lấy vàng nơi tay họ, đúc thành một con bò tơ" (Xuất 32:4).',
'["Cựu Ước", "Con bò vàng", "Aron"]',
'Exodus 32:4',
'vi',
true,
NOW(),
NOW()),

-- Câu hỏi khó (4 câu)
('q-exo-017', 'Exodus', 3, 5, 5, 'hard', 'multiple_choice_single',
'Đức Chúa Trời bảo Moses cởi giày vì đất đó là gì?',
'["Đất thánh", "Đất của ta", "Đất thiêng liêng", "Đất được chọn"]',
'[0]',
'Kinh Thánh ghi: "Đức Chúa Trời phán rằng: Chớ lại gần; hãy cởi giày ra, vì chỗ ngươi đứng là đất thánh" (Xuất 3:5).',
'["Cựu Ước", "Đất thánh", "Moses"]',
'Exodus 3:5',
'vi',
true,
NOW(),
NOW()),

('q-exo-018', 'Exodus', 12, 46, 46, 'hard', 'multiple_choice_single',
'Trong Lễ Vượt Qua, xương của chiên con phải như thế nào?',
'["Không được bẻ gãy", "Phải đốt cháy", "Phải chôn cất", "Phải ném đi"]',
'[0]',
'Kinh Thánh ghi: "Chẳng nên bẻ gãy một cái xương nào" (Xuất 12:46).',
'["Cựu Ước", "Lễ Vượt Qua", "Xương"]',
'Exodus 12:46',
'vi',
true,
NOW(),
NOW()),

('q-exo-019', 'Exodus', 25, 10, 10, 'hard', 'multiple_choice_single',
'Hòm Giao Ước được làm bằng gỗ gì?',
'["Gỗ bách", "Gỗ ô-liu", "Gỗ bá hương", "Gỗ thông"]',
'[0]',
'Kinh Thánh ghi: "Họ sẽ làm một cái hòm bằng cây bách" (Xuất 25:10).',
'["Cựu Ước", "Hòm Giao Ước", "Gỗ"]',
'Exodus 25:10',
'vi',
true,
NOW(),
NOW()),

('q-exo-020', 'Exodus', 34, 6, 6, 'hard', 'multiple_choice_single',
'Đức Chúa Trời tự mô tả mình là gì khi hiện ra với Moses?',
'["Đức Giê-hô-va, Đức Giê-hô-va, là Đức Chúa Trời nhân từ, thương xót, chậm giận, dư đầy ân huệ và thành thực", "Đức Giê-hô-va, Đức Chúa Trời toàn năng", "Đức Giê-hô-va, Đấng Thánh", "Đức Giê-hô-va, Đấng Chân Thật"]',
'[0]',
'Kinh Thánh ghi: "Đức Giê-hô-va, Đức Giê-hô-va, là Đức Chúa Trời nhân từ, thương xót, chậm giận, dư đầy ân huệ và thành thực" (Xuất 34:6).',
'["Cựu Ước", "Tính cách", "Đức Chúa Trời"]',
'Exodus 34:6',
'vi',
true,

NOW(),
NOW());
