-- Câu hỏi về Thi Thiên (Psalms) - 20 câu
INSERT IGNORE INTO questions (id, book, chapter, verse_start, verse_end, difficulty, type, content, options, correct_answer, explanation, tags, source, language, is_active, created_by, created_at, updated_at) VALUES

-- Câu hỏi dễ (6 câu)
('q-psa-001', 'Psalms', 23, 1, 1, 'easy', 'multiple_choice_single',
'Thi Thiên 23 bắt đầu bằng câu gì?',
'["Đức Giê-hô-va là Đấng chăn giữ tôi", "Đức Giê-hô-va là ánh sáng của tôi", "Đức Giê-hô-va là sức mạnh của tôi", "Đức Giê-hô-va là nơi nương náu của tôi"]',
'[0]',
'Kinh Thánh ghi: "Đức Giê-hô-va là Đấng chăn giữ tôi" (Thi 23:1).',
'["Cựu Ước", "Thi Thiên", "Chăn chiên"]',
'Psalms 23:1',
'vi',
true,
NOW(),
NOW()),

('q-psa-002', 'Psalms', 23, 4, 4, 'easy', 'multiple_choice_single',
'Trong Thi Thiên 23, khi đi qua trũng bóng chết, tác giả không sợ vì gì?',
'["Vì có Đức Chúa Trời ở cùng", "Vì có gậy và cây trượng", "Vì có ánh sáng", "Vì có bạn bè"]',
'[1]',
'Kinh Thánh ghi: "Dầu khi tôi đi trong trũng bóng chết, tôi sẽ chẳng sợ tai họa nào; vì Chúa ở cùng tôi" (Thi 23:4).',
'["Cựu Ước", "Thi Thiên", "Không sợ"]',
'Psalms 23:4',
'vi',
true,
NOW(),
NOW()),

('q-psa-003', 'Psalms', 1, 1, 1, 'easy', 'multiple_choice_single',
'Thi Thiên đầu tiên nói về người nào được phước?',
'["Người không đi theo mưu kế của kẻ ác", "Người không đứng trong đường tội nhân", "Người không ngồi trong chỗ của kẻ nhạo báng", "Cả ba câu trên"]',
'[3]',
'Kinh Thánh ghi: "Phước cho người nào chẳng theo mưu kế của kẻ ác, chẳng đứng trong đường tội nhân, không ngồi trong chỗ của kẻ nhạo báng" (Thi 1:1).',
'["Cựu Ước", "Thi Thiên", "Phước"]',
'Psalms 1:1',
'vi',
true,
NOW(),
NOW()),

('q-psa-004', 'Psalms', 100, 1, 1, 'easy', 'multiple_choice_single',
'Thi Thiên 100 kêu gọi làm gì?',
'["Hãy cất tiếng reo mừng cho Đức Giê-hô-va", "Hãy hát thánh ca", "Hãy cầu nguyện", "Hãy thờ phượng"]',
'[0]',
'Kinh Thánh ghi: "Hãy cất tiếng reo mừng cho Đức Giê-hô-va, cả thế gian!" (Thi 100:1).',
'["Cựu Ước", "Thi Thiên", "Reo mừng"]',
'Psalms 100:1',
'vi',
true,
NOW(),
NOW()),

('q-psa-005', 'Psalms', 91, 1, 1, 'easy', 'multiple_choice_single',
'Thi Thiên 91 nói về ai được bảo vệ?',
'["Người ở dưới bóng của Đấng Tối Cao", "Người tin cậy Đức Chúa Trời", "Người yêu mến Chúa", "Người vâng lời"]',
'[0]',
'Kinh Thánh ghi: "Người nào ở nơi kín đáo của Đấng Tối Cao, sẽ được hằng ở dưới bóng của Đấng Toàn năng" (Thi 91:1).',
'["Cựu Ước", "Thi Thiên", "Bảo vệ"]',
'Psalms 91:1',
'vi',
true,
NOW(),
NOW()),

('q-psa-006', 'Psalms', 46, 1, 1, 'easy', 'multiple_choice_single',
'Thi Thiên 46 nói Đức Chúa Trời là gì?',
'["Nơi nương náu và sức mạnh", "Ánh sáng và sự sống", "Tình yêu và lòng thương xót", "Chân lý và công lý"]',
'[0]',
'Kinh Thánh ghi: "Đức Chúa Trời là nơi nương náu và sức mạnh của chúng tôi" (Thi 46:1).',
'["Cựu Ước", "Thi Thiên", "Nương náu"]',
'Psalms 46:1',
'vi',
true,
NOW(),
NOW()),

-- Câu hỏi trung bình (10 câu)
('q-psa-007', 'Psalms', 23, 5, 5, 'medium', 'multiple_choice_single',
'Trong Thi Thiên 23, Đức Chúa Trời chuẩn bị bàn tiệc cho ai?',
'["Trước mặt kẻ thù nghịch", "Trước mặt bạn bè", "Trước mặt gia đình", "Trước mặt thiên sứ"]',
'[0]',
'Kinh Thánh ghi: "Chúa dọn bàn cho tôi trước mặt kẻ thù nghịch tôi" (Thi 23:5).',
'["Cựu Ước", "Thi Thiên", "Bàn tiệc"]',
'Psalms 23:5',
'vi',
true,
NOW(),
NOW()),

('q-psa-008', 'Psalms', 1, 2, 2, 'medium', 'multiple_choice_single',
'Người được phước trong Thi Thiên 1 có đặc điểm gì?',
'["Lấy làm vui về luật pháp của Đức Giê-hô-va", "Cầu nguyện mỗi ngày", "Dâng của lễ thường xuyên", "Hát thánh ca"]',
'[0]',
'Kinh Thánh ghi: "Song lấy làm vui về luật pháp của Đức Giê-hô-va" (Thi 1:2).',
'["Cựu Ước", "Thi Thiên", "Luật pháp"]',
'Psalms 1:2',
'vi',
true,
NOW(),
NOW()),

('q-psa-009', 'Psalms', 51, 10, 10, 'medium', 'multiple_choice_single',
'David cầu xin Đức Chúa Trời tạo trong mình điều gì?',
'["Lòng trong sạch", "Tấm lòng mới", "Tinh thần ngay thẳng", "Cả ba câu trên"]',
'[3]',
'Kinh Thánh ghi: "Đức Chúa Trời ôi! xin hãy dựng nên trong tôi một lòng trong sạch, và làm mới lại trong tôi một tinh thần ngay thẳng" (Thi 51:10).',
'["Cựu Ước", "Thi Thiên", "David"]',
'Psalms 51:10',
'vi',
true,
NOW(),
NOW()),

('q-psa-010', 'Psalms', 139, 14, 14, 'medium', 'multiple_choice_single',
'David nói mình được tạo nên như thế nào?',
'["Cách lạ lùng và đáng sợ", "Cách tuyệt vời", "Cách hoàn hảo", "Cách đặc biệt"]',
'[0]',
'Kinh Thánh ghi: "Tôi cảm tạ Chúa, vì tôi được dựng nên cách đáng sợ lạ lùng" (Thi 139:14).',
'["Cựu Ước", "Thi Thiên", "Tạo dựng"]',
'Psalms 139:14',
'vi',
true,
NOW(),
NOW()),

('q-psa-011', 'Psalms', 27, 1, 1, 'medium', 'multiple_choice_single',
'David nói Đức Giê-hô-va là gì của mình?',
'["Ánh sáng và sự cứu rỗi", "Sức mạnh và nơi nương náu", "Tình yêu và lòng thương xót", "Chân lý và công lý"]',
'[0]',
'Kinh Thánh ghi: "Đức Giê-hô-va là ánh sáng và sự cứu rỗi của tôi" (Thi 27:1).',
'["Cựu Ước", "Thi Thiên", "David"]',
'Psalms 27:1',
'vi',
true,
NOW(),
NOW()),

('q-psa-012', 'Psalms', 84, 10, 10, 'medium', 'multiple_choice_single',
'Tác giả Thi Thiên 84 nói một ngày trong hành lang Đức Chúa Trời đáng giá hơn gì?',
'["Một ngàn ngày", "Mười ngàn ngày", "Một trăm ngày", "Một năm"]',
'[0]',
'Kinh Thánh ghi: "Một ngày trong hành lang Chúa đáng hơn một ngàn ngày khác" (Thi 84:10).',
'["Cựu Ước", "Thi Thiên", "Hành lang"]',
'Psalms 84:10',
'vi',
true,
NOW(),
NOW()),

('q-psa-013', 'Psalms', 103, 12, 12, 'medium', 'multiple_choice_single',
'Đức Chúa Trời đã cất tội lỗi chúng ta xa như thế nào?',
'["Như từ đông sang tây", "Như từ bắc xuống nam", "Như từ trời xuống đất", "Như từ biển này sang biển kia"]',
'[0]',
'Kinh Thánh ghi: "Cũng như phương đông xa cách phương tây, Ngài đã cất khỏi chúng ta tội lỗi chúng ta" (Thi 103:12).',
'["Cựu Ước", "Thi Thiên", "Tội lỗi"]',
'Psalms 103:12',
'vi',
true,
NOW(),
NOW()),

('q-psa-014', 'Psalms', 119, 105, 105, 'medium', 'multiple_choice_single',
'Lời Chúa được ví như gì trong Thi Thiên 119?',
'["Ngọn đèn cho chân tôi", "Ánh sáng cho đường tôi", "Cả hai câu trên", "Không có câu nào đúng"]',
'[2]',
'Kinh Thánh ghi: "Lời Chúa là ngọn đèn cho chân tôi, Ánh sáng cho đường tôi" (Thi 119:105).',
'["Cựu Ước", "Thi Thiên", "Lời Chúa"]',
'Psalms 119:105',
'vi',
true,
NOW(),
NOW()),

('q-psa-015', 'Psalms', 37, 4, 4, 'medium', 'multiple_choice_single',
'Đức Chúa Trời sẽ ban cho ai những sự ước ao của lòng?',
'["Người tin cậy Chúa", "Người vâng lời", "Người yêu mến Chúa", "Người cầu nguyện"]',
'[0]',
'Kinh Thánh ghi: "Hãy phó thác đường lối mình cho Đức Giê-hô-va, và nhờ cậy nơi Ngài, thì Ngài sẽ làm thành" (Thi 37:5).',
'["Cựu Ước", "Thi Thiên", "Tin cậy"]',
'Psalms 37:5',
'vi',
true,
NOW(),
NOW()),

('q-psa-016', 'Psalms', 34, 8, 8, 'medium', 'multiple_choice_single',
'Tác giả Thi Thiên 34 mời gọi làm gì?',
'["Hãy nếm thử xem Đức Giê-hô-va tốt lành dường nào", "Hãy thờ phượng Đức Giê-hô-va", "Hãy cầu nguyện với Đức Giê-hô-va", "Hãy hát ca cho Đức Giê-hô-va"]',
'[0]',
'Kinh Thánh ghi: "Hãy nếm thử xem Đức Giê-hô-va tốt lành dường nào!" (Thi 34:8).',
'["Cựu Ước", "Thi Thiên", "Nếm thử"]',
'Psalms 34:8',
'vi',
true,
NOW(),
NOW()),

-- Câu hỏi khó (4 câu)
('q-psa-017', 'Psalms', 22, 1, 1, 'hard', 'multiple_choice_single',
'Thi Thiên 22 bắt đầu bằng câu gì mà Chúa Giê-su đã trích dẫn trên thập tự giá?',
'["Đức Chúa Trời tôi ơi! Đức Chúa Trời tôi ơi! Sao Ngài lìa bỏ tôi?", "Đức Chúa Trời tôi ơi! Sao Ngài không nghe tôi?", "Đức Chúa Trời tôi ơi! Sao Ngài không cứu tôi?", "Đức Chúa Trời tôi ơi! Sao Ngài không thương tôi?"]',
'[0]',
'Kinh Thánh ghi: "Đức Chúa Trời tôi ơi! Đức Chúa Trời tôi ơi! Sao Ngài lìa bỏ tôi?" (Thi 22:1).',
'["Cựu Ước", "Thi Thiên", "Chúa Giê-su"]',
'Psalms 22:1',
'vi',
true,
NOW(),
NOW()),

('q-psa-018', 'Psalms', 110, 1, 1, 'hard', 'multiple_choice_single',
'Thi Thiên 110 được coi là thi thiên tiên tri về ai?',
'["Đấng Mê-si-a", "Vua David", "Thầy tế lễ", "Tiên tri"]',
'[0]',
'Kinh Thánh ghi: "Đức Giê-hô-va phán cùng Chúa tôi rằng: Hãy ngồi bên hữu ta" - đây là lời tiên tri về Đấng Mê-si-a.',
'["Cựu Ước", "Thi Thiên", "Mê-si-a"]',
'Psalms 110:1',
'vi',
true,
NOW(),
NOW()),

('q-psa-019', 'Psalms', 2, 7, 7, 'hard', 'multiple_choice_single',
'Đức Chúa Trời nói với Đấng Mê-si-a như thế nào trong Thi Thiên 2?',
'["Ngươi là con ta", "Ngươi là đầy tớ ta", "Ngươi là bạn ta", "Ngươi là sứ giả ta"]',
'[0]',
'Kinh Thánh ghi: "Ta sẽ giảng ra mạng lịnh: Đức Giê-hô-va đã phán cùng ta: Con là con ta" (Thi 2:7).',
'["Cựu Ước", "Thi Thiên", "Con"]',
'Psalms 2:7',
'vi',
true,
NOW(),
NOW()),

('q-psa-020', 'Psalms', 45, 6, 6, 'hard', 'multiple_choice_single',
'Thi Thiên 45 nói về ngai của Đức Chúa Trời sẽ như thế nào?',
'["Đời đời bền vững", "Công bình và ngay thẳng", "Tốt lành và thánh khiết", "Quyền năng và vinh hiển"]',
'[0]',
'Kinh Thánh ghi: "Ngôi Chúa, hỡi Đức Chúa Trời, còn mãi mãi đời đời" (Thi 45:6).',
'["Cựu Ước", "Thi Thiên", "Ngôi"]',
'Psalms 45:6',
'vi',
true,

NOW(),
NOW());
