-- Câu hỏi mẫu cho Bible Quiz - Nội dung hay và chi tiết

-- Câu hỏi về Sáng Thế Ký (Genesis)
INSERT IGNORE INTO questions (id, book, chapter, verse_start, verse_end, difficulty, type, content, options, correct_answer, explanation, tags, source, language, is_active, created_by, created_at, updated_at) VALUES
('q-gen-001', 'Genesis', 1, 1, 1, 'easy', 'multiple_choice_single', 
'Trong câu đầu tiên của Kinh Thánh, "Ban đầu Đức Chúa Trời dựng nên trời đất" (Sáng 1:1), từ "ban đầu" trong tiếng Hê-bơ-rơ có nghĩa gì?',
'["Beresheet - Khởi nguyên tuyệt đối", "Rishon - Thứ nhất", "Tachlit - Mục đích", "Techilah - Bắt đầu"]',
'[0]',
'Beresheet (בראשית) có nghĩa là "khởi nguyên tuyệt đối", không chỉ là thời gian mà còn là nguyên lý cơ bản của vũ trụ.',
'["Sáng Thế Ký", "Ngôn ngữ Hê-bơ-rơ", "Từ vựng Kinh Thánh"]',
'Bible Study Guide',
'vi',
true,
'user-001',
NOW(),
NOW()),

('q-gen-002', 'Genesis', 2, 7, 7, 'medium', 'multiple_choice_single',
'Khi Đức Chúa Trời tạo nên A-đam, Ngài "hà sinh khí vào lỗ mũi" (Sáng 2:7). Từ "sinh khí" trong tiếng Hê-bơ-rơ là gì?',
'["Ruach - Thần khí", "Nephesh - Linh hồn", "Neshamah - Hơi thở sự sống", "Chay - Sự sống"]',
'[2]',
'Neshamah (נשמה) có nghĩa là "hơi thở sự sống", khác với ruach (thần khí) và nephesh (linh hồn).',
'["Sáng Thế Ký", "Tạo dựng", "Ngôn ngữ Hê-bơ-rơ"]',
'Biblical Hebrew Studies',
'vi',
true,
'user-001',
NOW(),
NOW()),

('q-gen-003', 'Genesis', 3, 15, 15, 'hard', 'multiple_choice_single',
'Trong lời tiên tri đầu tiên về Đấng Mê-si-a (Sáng 3:15), "dòng dõi người nữ sẽ đánh dập đầu ngươi", từ "dòng dõi" trong tiếng Hê-bơ-rơ có nghĩa gì?',
'["Zera - Hạt giống", "Toledot - Thế hệ", "Mishpachah - Gia tộc", "Am - Dân tộc"]',
'[0]',
'Zera (זרע) có nghĩa là "hạt giống", ám chỉ đến một người cụ thể sẽ đến từ dòng dõi người nữ.',
'["Sáng Thế Ký", "Tiên tri Mê-si-a", "Ngôn ngữ Hê-bơ-rơ"]',
'Messianic Prophecy Studies',
'vi',
true,
'user-001',
NOW(),
NOW()),

-- Câu hỏi về Xuất Ê-díp-tô Ký (Exodus)
('q-exo-001', 'Exodus', 3, 14, 14, 'easy', 'multiple_choice_single',
'Khi Môi-se hỏi tên Đức Chúa Trời, Ngài trả lời "Ta là Đấng Tự Hữu Hằng Hữu" (Xuất 3:14). Tên này trong tiếng Hê-bơ-rơ là gì?',
'["Yahweh", "Elohim", "Adonai", "El Shaddai"]',
'[0]',
'Yahweh (יהוה) có nghĩa là "Ta là Đấng Tự Hữu Hằng Hữu", tên riêng của Đức Chúa Trời.',
'["Xuất Ê-díp-tô Ký", "Tên Đức Chúa Trời", "Môi-se"]',
'Biblical Names Study',
'vi',
true,
'user-001',
NOW(),
NOW()),

('q-exo-002', 'Exodus', 12, 13, 13, 'medium', 'multiple_choice_single',
'Trong Lễ Vượt Qua, huyết chiên con được bôi lên "cây ngang và hai cây dọc" (Xuất 12:13). Điều này tạo thành hình gì?',
'["Hình thập tự", "Hình tam giác", "Hình vuông", "Hình tròn"]',
'[0]',
'Huyết bôi lên cây ngang và hai cây dọc tạo thành hình thập tự, tiên tri về sự chết của Chúa Giê-su.',
'["Xuất Ê-díp-tô Ký", "Lễ Vượt Qua", "Tiên tri Mê-si-a"]',
'Passover Studies',
'vi',
true,
'user-001',
NOW(),
NOW()),

-- Câu hỏi về Thi Thiên (Psalms)
('q-psa-001', 'Psalms', 23, 1, 1, 'easy', 'multiple_choice_single',
'Thi Thiên 23 bắt đầu bằng "Đức Giê-hô-va là Đấng chăn giữ tôi". Từ "chăn giữ" trong tiếng Hê-bơ-rơ có nghĩa gì?',
'["Raah - Chăn giữ, dẫn dắt", "Shamar - Bảo vệ", "Nahal - Dẫn dắt", "Yada - Biết"]',
'[0]',
'Raah (רעה) có nghĩa là "chăn giữ, dẫn dắt", không chỉ bảo vệ mà còn hướng dẫn và chăm sóc.',
'["Thi Thiên", "Chăn chiên", "Ngôn ngữ Hê-bơ-rơ"]',
'Psalm Studies',
'vi',
true,
'user-001',
NOW(),
NOW()),

('q-psa-002', 'Psalms', 46, 10, 10, 'medium', 'multiple_choice_single',
'Trong Thi Thiên 46:10, "Hãy yên lặng và biết rằng Ta là Đức Chúa Trời". Từ "yên lặng" trong tiếng Hê-bơ-rơ có nghĩa gì?',
'["Rapha - Buông tay, thả lỏng", "Shabbat - Nghỉ ngơi", "Dumah - Im lặng", "Chashah - Dừng lại"]',
'[0]',
'Rapha (רפה) có nghĩa là "buông tay, thả lỏng", không chỉ im lặng mà còn buông bỏ sự lo lắng.',
'["Thi Thiên", "Sự yên lặng", "Ngôn ngữ Hê-bơ-rơ"]',
'Psalm Studies',
'vi',
true,
'user-001',
NOW(),
NOW()),

-- Câu hỏi về Ma-thi-ơ (Matthew)
('q-mat-001', 'Matthew', 1, 21, 21, 'easy', 'multiple_choice_single',
'Thiên sứ báo cho Giô-sép rằng "người sẽ đặt tên con trẻ là Giê-su" (Ma-thi-ơ 1:21). Tên Giê-su trong tiếng Hê-bơ-rơ có nghĩa gì?',
'["Yeshua - Đức Giê-hô-va cứu rỗi", "Immanuel - Đức Chúa Trời ở cùng chúng ta", "Messiah - Đấng được xức dầu", "Adonai - Chúa"]',
'[0]',
'Yeshua (ישוע) có nghĩa là "Đức Giê-hô-va cứu rỗi", tên này nói lên sứ mệnh của Chúa Giê-su.',
'["Ma-thi-ơ", "Tên Chúa Giê-su", "Ngôn ngữ Hê-bơ-rơ"]',
'Gospel Studies',
'vi',
true,
'user-001',
NOW(),
NOW()),

('q-mat-002', 'Matthew', 5, 3, 3, 'medium', 'multiple_choice_single',
'Trong Bài Giảng Trên Núi, Chúa Giê-su nói "Phước cho những kẻ có lòng nghèo khó" (Ma-thi-ơ 5:3). Từ "nghèo khó" trong tiếng Hy Lạp có nghĩa gì?',
'["Ptochos - Nghèo khó về tinh thần", "Penichros - Thiếu thốn vật chất", "Apenes - Không có gì", "Elaion - Cần sự giúp đỡ"]',
'[0]',
'Ptochos (πτωχός) có nghĩa là "nghèo khó về tinh thần", nhận biết sự cần thiết của mình trước Đức Chúa Trời.',
'["Ma-thi-ơ", "Bài Giảng Trên Núi", "Ngôn ngữ Hy Lạp"]',
'Gospel Studies',
'vi',
true,
'user-001',
NOW(),
NOW()),

-- Câu hỏi về Giăng (John)
('q-joh-001', 'John', 1, 1, 1, 'easy', 'multiple_choice_single',
'Trong câu đầu tiên của sách Giăng, "Ban đầu có Ngôi Lời" (Giăng 1:1), từ "Ngôi Lời" trong tiếng Hy Lạp là gì?',
'["Logos - Ngôi Lời, Lý trí", "Rhema - Lời nói", "Graphe - Kinh Thánh", "Epistole - Thư tín"]',
'[0]',
'Logos (λόγος) có nghĩa là "Ngôi Lời, Lý trí", ám chỉ đến Chúa Giê-su là Ngôi Lời của Đức Chúa Trời.',
'["Giăng", "Ngôi Lời", "Ngôn ngữ Hy Lạp"]',
'Gospel Studies',
'vi',
true,
'user-001',
NOW(),
NOW()),

('q-joh-002', 'John', 3, 16, 16, 'medium', 'multiple_choice_single',
'Trong câu nổi tiếng "Vì Đức Chúa Trời yêu thương thế gian" (Giăng 3:16), từ "yêu thương" trong tiếng Hy Lạp có nghĩa gì?',
'["Agape - Tình yêu vô điều kiện", "Phileo - Tình yêu bạn bè", "Eros - Tình yêu lãng mạn", "Storge - Tình yêu gia đình"]',
'[0]',
'Agape (ἀγάπη) có nghĩa là "tình yêu vô điều kiện", tình yêu cao nhất và thuần khiết nhất.',
'["Giăng", "Tình yêu", "Ngôn ngữ Hy Lạp"]',
'Gospel Studies',
'vi',
true,
'user-001',
NOW(),
NOW()),

-- Câu hỏi về Rô-ma (Romans)
('q-rom-001', 'Romans', 8, 28, 28, 'easy', 'multiple_choice_single',
'Trong Rô-ma 8:28, "mọi sự hiệp lại làm ích cho kẻ yêu mến Đức Chúa Trời". Từ "hiệp lại" trong tiếng Hy Lạp có nghĩa gì?',
'["Sunergeo - Cùng làm việc", "Sun - Cùng nhau", "Ergon - Công việc", "Sunergeo - Hợp tác"]',
'[0]',
'Sunergeo (συνεργέω) có nghĩa là "cùng làm việc", mọi sự cùng nhau làm việc vì lợi ích của chúng ta.',
'["Rô-ma", "Sự hiệp lại", "Ngôn ngữ Hy Lạp"]',
'Pauline Studies',
'vi',
true,
'user-001',
NOW(),
NOW()),

('q-rom-002', 'Romans', 12, 2, 2, 'medium', 'multiple_choice_single',
'Trong Rô-ma 12:2, "đừng làm theo đời này, nhưng hãy biến hóa bởi sự đổi mới của tâm trí". Từ "biến hóa" trong tiếng Hy Lạp có nghĩa gì?',
'["Metamorphoo - Biến hóa từ bên trong", "Allasso - Thay đổi bên ngoài", "Metatithemi - Chuyển đổi", "Metastrepho - Đảo ngược"]',
'[0]',
'Metamorphoo (μεταμορφόω) có nghĩa là "biến hóa từ bên trong", như con bướm biến hóa từ sâu.',
'["Rô-ma", "Sự biến hóa", "Ngôn ngữ Hy Lạp"]',
'Pauline Studies',
'vi',
true,
'user-001',
NOW(),
NOW()),

-- Câu hỏi về Khải Huyền (Revelation)
('q-rev-001', 'Revelation', 1, 8, 8, 'easy', 'multiple_choice_single',
'Trong Khải Huyền 1:8, Chúa phán "Ta là An-pha và Ô-mê-ga". Điều này có nghĩa gì?',
'["Đầu tiên và cuối cùng", "A và Z", "Khởi nguyên và kết thúc", "Tất cả các ý trên"]',
'[3]',
'An-pha và Ô-mê-ga là chữ cái đầu và cuối của bảng chữ cái Hy Lạp, có nghĩa là "đầu tiên và cuối cùng", "khởi nguyên và kết thúc".',
'["Khải Huyền", "An-pha và Ô-mê-ga", "Chúa Giê-su"]',
'Revelation Studies',
'vi',
true,
'user-001',
NOW(),
NOW()),

('q-rev-002', 'Revelation', 21, 4, 4, 'medium', 'multiple_choice_single',
'Trong Khải Huyền 21:4, "Ngài sẽ lau ráo hết nước mắt khỏi mắt chúng". Từ "lau ráo" trong tiếng Hy Lạp có nghĩa gì?',
'["Exaleipho - Xóa bỏ hoàn toàn", "Apomasso - Lau sạch", "Kathairo - Làm sạch", "Agnizo - Thanh tẩy"]',
'[0]',
'Exaleipho (ἐξαλείφω) có nghĩa là "xóa bỏ hoàn toàn", không chỉ lau mà còn xóa bỏ vĩnh viễn.',
'["Khải Huyền", "Thiên đàng", "Ngôn ngữ Hy Lạp"]',
'Revelation Studies',
'vi',
true,
'user-001',
NOW(),
NOW());
