-- Genesis seed data: 70 questions (30 easy, 25 medium, 15 hard)
-- Source: Kinh Thánh Bản Truyền Thống 1926 (public domain)
-- Coverage: Ch 1-3 (10), Ch 4-11 (10), Ch 12-24 (15), Ch 25-36 (15), Ch 37-50 (20)

INSERT IGNORE INTO questions (
  id, book, chapter, verse_start, verse_end,
  difficulty, type, content, options, correct_answer,
  explanation, tags, source, language, review_status, approvals_count, is_active,
  created_at, updated_at
) VALUES

-- ═══════════════════════════════════════════════════════════════
-- CHƯƠNG 1-3: SÁNG TẠO VÀ SA NGÃ (10 câu: 5 easy, 3 medium, 2 hard)
-- ═══════════════════════════════════════════════════════════════

('bq-gen-001', 'Genesis', 1, 1, 1, 'easy', 'multiple_choice_single',
 'Theo Sáng Thế Ký 1:1, ai đã dựng nên trời đất?',
 '["Thiên sứ","Đức Chúa Trời","Môi-se","Áp-ra-ham"]',
 '[1]',
 'Sáng Thế Ký 1:1 — "Ban đầu Đức Chúa Trời dựng nên trời đất."',
 '["Sáng Thế Ký","Sáng tạo","Chương 1"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-gen-002', 'Genesis', 1, 3, 3, 'easy', 'multiple_choice_single',
 'Điều đầu tiên Đức Chúa Trời phán để tạo dựng là gì? (Sáng 1:3)',
 '["Phải có sự sáng","Phải có nước","Phải có đất","Phải có cây cối"]',
 '[0]',
 'Sáng Thế Ký 1:3 — "Đức Chúa Trời phán rằng: Phải có sự sáng; thì có sự sáng."',
 '["Sáng Thế Ký","Sáng tạo","Chương 1"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-gen-003', 'Genesis', 1, 27, 27, 'easy', 'multiple_choice_single',
 'Theo Sáng Thế Ký 1:27, con người được dựng nên giống như hình ảnh của ai?',
 '["Các thần","Thiên sứ","Tự nhiên","Đức Chúa Trời"]',
 '[3]',
 'Sáng Thế Ký 1:27 — "Đức Chúa Trời dựng nên loài người như hình Ngài; Ngài dựng nên loài người giống như hình Đức Chúa Trời."',
 '["Sáng Thế Ký","Sáng tạo","Con người"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-gen-004', 'Genesis', 2, 7, 7, 'easy', 'multiple_choice_single',
 'Đức Chúa Trời nắn loài người bằng chất liệu gì? (Sáng 2:7)',
 '["Bụi đất","Nước","Đá","Lửa"]',
 '[0]',
 'Sáng Thế Ký 2:7 — "Giê-hô-va Đức Chúa Trời bèn lấy bụi đất nắn nên hình người, hà sanh khí vào lỗ mũi."',
 '["Sáng Thế Ký","Sáng tạo","A-đam"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-gen-005', 'Genesis', 2, 22, 22, 'easy', 'multiple_choice_single',
 'Đức Chúa Trời dựng nên Ê-va từ phần nào của A-đam? (Sáng 2:22)',
 '["Bụi đất","Xương sườn","Tay","Chân"]',
 '[1]',
 'Sáng Thế Ký 2:22 — "Giê-hô-va Đức Chúa Trời bèn dùng xương sườn đã lấy nơi A-đam làm nên một người nữ."',
 '["Sáng Thế Ký","Sáng tạo","Ê-va"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-gen-006', 'Genesis', 1, 31, 31, 'medium', 'multiple_choice_single',
 'Sau khi hoàn tất sáng tạo, Đức Chúa Trời đánh giá mọi vật Ngài đã làm ra như thế nào? (Sáng 1:31)',
 '["Bình thường","Hoàn hảo","Tốt lành","Rất tốt lành"]',
 '[3]',
 'Sáng Thế Ký 1:31 — "Đức Chúa Trời thấy các việc Ngài đã làm thật rất tốt lành."',
 '["Sáng Thế Ký","Sáng tạo","Chương 1"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-gen-007', 'Genesis', 3, 6, 6, 'medium', 'multiple_choice_single',
 'Trong vườn Ê-đen, ai đã ăn trái cấm trước? (Sáng 3:6)',
 '["A-đam","Ê-va","Con rắn","Cả hai cùng lúc"]',
 '[1]',
 'Sáng Thế Ký 3:6 — "Người nữ thấy trái của cây đó bộ ăn ngon, lại đẹp mắt và quí vì để mở trí khôn, bèn hái ăn, rồi trao cho chồng đứng gần mình, chồng cũng ăn nữa."',
 '["Sáng Thế Ký","Sa ngã","Ê-va"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-gen-008', 'Genesis', 3, 15, 15, 'medium', 'multiple_choice_single',
 'Theo Sáng Thế Ký 3:15, dòng dõi người nữ sẽ làm gì với đầu con rắn?',
 '["Giày đạp","Tránh xa","Nói chuyện","Làm bạn"]',
 '[0]',
 'Sáng Thế Ký 3:15 — "Ta sẽ làm cho mầy cùng người nữ, dòng dõi mầy cùng dòng dõi người nữ nghịch thù nhau. Người sẽ giày đạp đầu mầy, còn mầy sẽ cắn gót chân người."',
 '["Sáng Thế Ký","Lời hứa","Tiên tri"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-gen-009', 'Genesis', 2, 17, 17, 'hard', 'multiple_choice_single',
 'Theo Sáng Thế Ký 2:17, hậu quả mà Đức Chúa Trời cảnh báo nếu ăn trái cấm là gì?',
 '["Bị đuổi khỏi vườn","Chắc chắn phải chết","Bị đau đớn","Mất trí khôn"]',
 '[1]',
 'Sáng Thế Ký 2:17 — "Nhưng về cây biết điều thiện và điều ác thì chớ hề ăn đến; vì một mai ngươi ăn, chắc sẽ chết."',
 '["Sáng Thế Ký","Sa ngã","Điều răn"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-gen-010', 'Genesis', 3, 21, 21, 'hard', 'multiple_choice_single',
 'Sau khi A-đam và Ê-va phạm tội, Đức Chúa Trời làm gì cho họ? (Sáng 3:21)',
 '["Đuổi ra khỏi vườn","Rủa sả họ","Lấy da thú kết áo dài cho mặc","Giết con rắn"]',
 '[2]',
 'Sáng Thế Ký 3:21 — "Giê-hô-va Đức Chúa Trời lấy da thú kết áo dài cho vợ chồng A-đam, và mặc lấy cho."',
 '["Sáng Thế Ký","Sa ngã","Ân điển"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

-- ═══════════════════════════════════════════════════════════════
-- CHƯƠNG 4-11: CA-IN, NÔ-Ê, BA-BÊN (10 câu: 5 easy, 3 medium, 2 hard)
-- ═══════════════════════════════════════════════════════════════

('bq-gen-011', 'Genesis', 4, 2, 2, 'easy', 'multiple_choice_single',
 'Ca-in và A-bên là con của ai? (Sáng 4:1-2)',
 '["Nô-ê","A-đam và Ê-va","Áp-ra-ham","Sết"]',
 '[1]',
 'Sáng Thế Ký 4:1-2 — "A-đam ăn ở với Ê-va, là vợ mình; nàng thọ thai sanh Ca-in... Nàng lại sanh em Ca-in, là A-bên."',
 '["Sáng Thế Ký","Ca-in","A-bên"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-gen-012', 'Genesis', 4, 2, 2, 'easy', 'multiple_choice_single',
 'A-bên làm nghề gì? (Sáng 4:2)',
 '["Làm ruộng","Chăn chiên","Thợ mộc","Thợ rèn"]',
 '[1]',
 'Sáng Thế Ký 4:2 — "A-bên làm nghề chăn chiên, còn Ca-in thì làm nghề cày đất."',
 '["Sáng Thế Ký","A-bên","Nghề nghiệp"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-gen-013', 'Genesis', 6, 14, 14, 'easy', 'multiple_choice_single',
 'Đức Chúa Trời bảo Nô-ê đóng tàu bằng loại gỗ gì? (Sáng 6:14)',
 '["Gỗ thông","Gỗ bách","Gỗ sồi","Gỗ tùng"]',
 '[1]',
 'Sáng Thế Ký 6:14 — "Ngươi hãy đóng một chiếc tàu bằng cây gô-phe (gỗ bách)."',
 '["Sáng Thế Ký","Nô-ê","Tàu"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-gen-014', 'Genesis', 7, 12, 12, 'easy', 'multiple_choice_single',
 'Trận nước lụt thời Nô-ê, mưa kéo dài bao nhiêu ngày đêm? (Sáng 7:12)',
 '["20 ngày đêm","40 ngày đêm","30 ngày đêm","50 ngày đêm"]',
 '[1]',
 'Sáng Thế Ký 7:12 — "Mưa xuống trên mặt đất trong bốn mươi ngày và bốn mươi đêm."',
 '["Sáng Thế Ký","Nô-ê","Nước lụt"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-gen-015', 'Genesis', 11, 4, 9, 'easy', 'multiple_choice_single',
 'Người ta xây tháp Ba-bên với mục đích gì? (Sáng 11:4)',
 '["Trốn nước lụt","Quan sát các vì sao","Thờ phượng Chúa","Làm cho mình nổi danh"]',
 '[3]',
 'Sáng Thế Ký 11:4 — "Nào! chúng ta hãy xây một cái thành và dựng lên một cái tháp... để ta làm cho rạng danh."',
 '["Sáng Thế Ký","Ba-bên","Kiêu ngạo"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-gen-016', 'Genesis', 4, 8, 8, 'medium', 'multiple_choice_single',
 'Ca-in đã làm gì với em mình là A-bên? (Sáng 4:8)',
 '["Giết","Xua đi","Đánh đuổi","Bỏ rơi"]',
 '[0]',
 'Sáng Thế Ký 4:8 — "Ca-in dấy lên cùng A-bên, em mình, và giết đi."',
 '["Sáng Thế Ký","Ca-in","A-bên"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-gen-017', 'Genesis', 5, 27, 27, 'medium', 'multiple_choice_single',
 'Mê-tu-sê-la sống được bao nhiêu tuổi, là người sống lâu nhất trong Kinh Thánh? (Sáng 5:27)',
 '["969 tuổi","950 tuổi","900 tuổi","1000 tuổi"]',
 '[0]',
 'Sáng Thế Ký 5:27 — "Mê-tu-sê-la hưởng thọ được chín trăm sáu mươi chín tuổi, rồi qua đời."',
 '["Sáng Thế Ký","Gia phả","Mê-tu-sê-la"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-gen-018', 'Genesis', 9, 13, 13, 'medium', 'multiple_choice_single',
 'Sau nước lụt, Đức Chúa Trời đặt điều gì trên mây làm dấu hiệu giao ước? (Sáng 9:13)',
 '["Đám mây lửa","Mống (cầu vồng)","Một ngôi sao","Ánh sáng"]',
 '[1]',
 'Sáng Thế Ký 9:13 — "Ta đặt mống của ta trên từng mây, dùng làm dấu chỉ sự giao ước của ta với đất."',
 '["Sáng Thế Ký","Nô-ê","Giao ước"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-gen-019', 'Genesis', 6, 9, 9, 'hard', 'multiple_choice_single',
 'Kinh Thánh mô tả Nô-ê là người như thế nào giữa người đồng thời? (Sáng 6:9)',
 '["Khôn ngoan và can đảm","Khiêm nhường và hiền lành","Giàu có và quyền thế","Công bình và trọn vẹn"]',
 '[3]',
 'Sáng Thế Ký 6:9 — "Nô-ê là một người công bình và trọn vẹn, đồng thời với người; Nô-ê đồng đi cùng Đức Chúa Trời."',
 '["Sáng Thế Ký","Nô-ê","Đức tin"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-gen-020', 'Genesis', 11, 7, 9, 'hard', 'multiple_choice_single',
 'Đức Chúa Trời làm gì để ngăn người xây tháp Ba-bên? (Sáng 11:7-9)',
 '["Giáng lửa từ trời","Gửi nước lụt","Phá hủy tháp","Làm lộn xộn tiếng nói và tản lạc họ"]',
 '[3]',
 'Sáng Thế Ký 11:7-9 — "Thôi! chúng ta hãy xuống, làm lộn xộn tiếng nói của chúng nó... Bởi cớ đó, đặt tên thành là Ba-bên."',
 '["Sáng Thế Ký","Ba-bên","Ngôn ngữ"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

-- ═══════════════════════════════════════════════════════════════
-- CHƯƠNG 12-24: ÁP-RA-HAM VÀ Y-SÁC (15 câu: 7 easy, 5 medium, 3 hard)
-- ═══════════════════════════════════════════════════════════════

('bq-gen-021', 'Genesis', 12, 1, 1, 'easy', 'multiple_choice_single',
 'Đức Chúa Trời kêu gọi Áp-ram (Áp-ra-ham) rời khỏi xứ nào? (Sáng 12:1)',
 '["U-rơ xứ Canh-đê","Ca-na-an","Ai Cập","Ba-by-lôn"]',
 '[0]',
 'Sáng Thế Ký 12:1 — "Đức Giê-hô-va phán cùng Áp-ram rằng: Ngươi hãy ra khỏi quê hương, vòng bà con và nhà cha ngươi."',
 '["Sáng Thế Ký","Áp-ra-ham","Kêu gọi"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-gen-022', 'Genesis', 12, 5, 5, 'easy', 'multiple_choice_single',
 'Áp-ram dẫn theo ai khi rời quê hương? (Sáng 12:5)',
 '["Y-sác","Lót","Ê-sau","Gia-cốp"]',
 '[1]',
 'Sáng Thế Ký 12:5 — "Áp-ram dẫn Sa-rai, vợ mình, và Lót, cháu mình... mà đi đến xứ Ca-na-an."',
 '["Sáng Thế Ký","Áp-ra-ham","Lót"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-gen-023', 'Genesis', 15, 5, 6, 'easy', 'multiple_choice_single',
 'Đức Chúa Trời hứa dòng dõi Áp-ram sẽ đông như gì? (Sáng 15:5)',
 '["Cây cối","Nước sông","Cát biển","Sao trên trời"]',
 '[3]',
 'Sáng Thế Ký 15:5 — "Ngươi hãy ngó lên trời, và nếu ngươi đếm được các ngôi sao thì hãy đếm đi. Ngài lại phán rằng: Dòng dõi ngươi cũng sẽ như vậy."',
 '["Sáng Thế Ký","Áp-ra-ham","Lời hứa"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-gen-024', 'Genesis', 17, 5, 5, 'easy', 'multiple_choice_single',
 'Đức Chúa Trời đổi tên Áp-ram thành gì? (Sáng 17:5)',
 '["Áp-ra-ham","Y-sác","Gia-cốp","Giô-sép"]',
 '[0]',
 'Sáng Thế Ký 17:5 — "Thiên hạ sẽ chẳng gọi ngươi là Áp-ram nữa, nhưng sẽ gọi là Áp-ra-ham, vì ta đặt ngươi làm tổ phụ của nhiều dân tộc."',
 '["Sáng Thế Ký","Áp-ra-ham","Tên mới"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-gen-025', 'Genesis', 21, 3, 3, 'easy', 'multiple_choice_single',
 'Con trai của Áp-ra-ham và Sa-ra tên là gì? (Sáng 21:3)',
 '["Ích-ma-ên","Y-sác","Ê-sau","Gia-cốp"]',
 '[1]',
 'Sáng Thế Ký 21:3 — "Áp-ra-ham đặt tên đứa trai mà Sa-ra sanh cho mình là Y-sác."',
 '["Sáng Thế Ký","Y-sác","Sa-ra"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-gen-026', 'Genesis', 22, 2, 2, 'easy', 'multiple_choice_single',
 'Đức Chúa Trời bảo Áp-ra-ham dâng Y-sác trên núi nào? (Sáng 22:2)',
 '["Ô-li-ve","Cạt-mên","Si-na-i","Mô-ri-a"]',
 '[3]',
 'Sáng Thế Ký 22:2 — "Hãy bắt đứa con một ngươi yêu dấu, là Y-sác... dâng nó làm của lễ thiêu trên một hòn núi kia, thuộc về địa phận Mô-ri-a."',
 '["Sáng Thế Ký","Áp-ra-ham","Thử thách"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-gen-027', 'Genesis', 24, 67, 67, 'easy', 'multiple_choice_single',
 'Y-sác cưới ai làm vợ? (Sáng 24:67)',
 '["Ra-chên","Rê-bê-ca","Sa-ra","Lê-a"]',
 '[1]',
 'Sáng Thế Ký 24:67 — "Y-sác bèn đưa Rê-bê-ca vào trại Sa-ra, mẹ mình, cưới nàng làm vợ."',
 '["Sáng Thế Ký","Y-sác","Rê-bê-ca"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-gen-028', 'Genesis', 14, 18, 20, 'medium', 'multiple_choice_single',
 'Mên-chi-xê-đéc, vua Sa-lem, đem gì ra đón Áp-ram? (Sáng 14:18)',
 '["Bánh và rượu","Chiên và bò","Vàng và bạc","Áo và vũ khí"]',
 '[0]',
 'Sáng Thế Ký 14:18 — "Mên-chi-xê-đéc, vua Sa-lem, sai đem bánh và rượu ra. Vả, vua nầy là thầy tế lễ của Đức Chúa Trời Chí Cao."',
 '["Sáng Thế Ký","Mên-chi-xê-đéc","Thầy tế lễ"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-gen-029', 'Genesis', 16, 15, 16, 'medium', 'multiple_choice_single',
 'A-ga sanh cho Áp-ram một con trai tên gì? (Sáng 16:15)',
 '["Ê-sau","Lót","Ích-ma-ên","Y-sác"]',
 '[2]',
 'Sáng Thế Ký 16:15 — "Rồi A-ga sanh được một con trai; Áp-ram đặt tên con trai đó là Ích-ma-ên."',
 '["Sáng Thế Ký","A-ga","Ích-ma-ên"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-gen-030', 'Genesis', 18, 14, 14, 'medium', 'multiple_choice_single',
 'Khi Sa-ra cười vì nghe tin mình sẽ có con, Đức Giê-hô-va phán gì? (Sáng 18:14)',
 '["Hãy chờ đợi","Sa-ra phải tin","Sa-ra sẽ bị phạt","Há có điều chi Đức Giê-hô-va làm không được chăng?"]',
 '[3]',
 'Sáng Thế Ký 18:14 — "Há có điều chi Đức Giê-hô-va làm không được chăng?"',
 '["Sáng Thế Ký","Sa-ra","Đức tin"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-gen-031', 'Genesis', 19, 26, 26, 'medium', 'multiple_choice_single',
 'Vợ của Lót bị biến thành gì khi ngoảnh lại nhìn thành Sô-đôm? (Sáng 19:26)',
 '["Tượng đá","Tượng muối","Bụi đất","Cột lửa"]',
 '[1]',
 'Sáng Thế Ký 19:26 — "Nhưng vợ của Lót quay ngó lại đằng sau mình, nên hóa ra một tượng muối."',
 '["Sáng Thế Ký","Lót","Sô-đôm"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-gen-032', 'Genesis', 22, 13, 13, 'medium', 'multiple_choice_single',
 'Khi Đức Chúa Trời ngăn Áp-ra-ham dâng Y-sác, con vật nào được dùng thay thế? (Sáng 22:13)',
 '["Chiên con","Bò đực","Chiên đực mắc sừng trong bụi cây","Bồ câu"]',
 '[2]',
 'Sáng Thế Ký 22:13 — "Áp-ra-ham nhướng mắt lên, thấy sau lưng một con chiên đực, sừng mắc trong bụi cây."',
 '["Sáng Thế Ký","Áp-ra-ham","Của lễ"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-gen-033', 'Genesis', 17, 10, 10, 'hard', 'multiple_choice_single',
 'Dấu hiệu giao ước giữa Đức Chúa Trời và Áp-ra-ham là gì? (Sáng 17:10)',
 '["Phép cắt bì","Dâng của lễ","Xây bàn thờ","Giữ ngày Sa-bát"]',
 '[0]',
 'Sáng Thế Ký 17:10 — "Mọi người nam trong vòng các ngươi phải chịu phép cắt bì; ấy là giao ước mà các ngươi phải giữ."',
 '["Sáng Thế Ký","Áp-ra-ham","Giao ước"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-gen-034', 'Genesis', 18, 32, 32, 'hard', 'multiple_choice_single',
 'Khi Áp-ra-ham cầu thay cho Sô-đôm, số người công bình cuối cùng ông xin Chúa tha là bao nhiêu? (Sáng 18:32)',
 '["Năm mươi","Ba mươi","Hai mươi","Mười"]',
 '[3]',
 'Sáng Thế Ký 18:32 — "Xin Chúa đừng giận, để tôi thưa chỉ lần nầy nữa: Ngộ trong đó tìm được mười người thì sao?"',
 '["Sáng Thế Ký","Áp-ra-ham","Cầu thay"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-gen-035', 'Genesis', 15, 13, 14, 'hard', 'multiple_choice_single',
 'Đức Chúa Trời báo trước cho Áp-ram rằng dòng dõi ông sẽ làm khách lạ và bị hà hiếp bao nhiêu năm? (Sáng 15:13)',
 '["200 năm","400 năm","300 năm","500 năm"]',
 '[1]',
 'Sáng Thế Ký 15:13 — "Phải biết rằng, dòng dõi ngươi sẽ ngụ trong một xứ chẳng thuộc về chúng nó, làm tôi mọi cho dân xứ đó và bị hà hiếp bốn trăm năm."',
 '["Sáng Thế Ký","Áp-ra-ham","Tiên tri"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

-- ═══════════════════════════════════════════════════════════════
-- CHƯƠNG 25-36: GIA-CỐP VÀ Ê-SAU (15 câu: 7 easy, 5 medium, 3 hard)
-- ═══════════════════════════════════════════════════════════════

('bq-gen-036', 'Genesis', 25, 25, 26, 'easy', 'multiple_choice_single',
 'Trong hai con trai sinh đôi của Y-sác, ai ra trước? (Sáng 25:25)',
 '["Cả hai cùng lúc","Không nói rõ","Ê-sau","Gia-cốp"]',
 '[2]',
 'Sáng Thế Ký 25:25 — "Đứa ra trước đỏ hồng, lông lá như một áo tơi lông; nên đặt tên là Ê-sau."',
 '["Sáng Thế Ký","Ê-sau","Sinh đôi"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-gen-037', 'Genesis', 25, 34, 34, 'easy', 'multiple_choice_single',
 'Ê-sau đã bán quyền trưởng nam để đổi lấy gì? (Sáng 25:34)',
 '["Vàng bạc","Chiên bò","Bánh và canh đậu phộng","Đất đai"]',
 '[2]',
 'Sáng Thế Ký 25:34 — "Rồi Gia-cốp đưa cho Ê-sau bánh và canh đậu phộng; Ê-sau ăn uống xong, đứng dậy đi. Ấy, Ê-sau khinh quyền trưởng nam là thế."',
 '["Sáng Thế Ký","Ê-sau","Quyền trưởng nam"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-gen-038', 'Genesis', 28, 12, 12, 'easy', 'multiple_choice_single',
 'Gia-cốp thấy gì trong giấc chiêm bao tại Bê-tên? (Sáng 28:12)',
 '["Ngôi sao sáng","Đám mây lớn","Dòng sông","Một cái thang bắc từ đất lên trời"]',
 '[3]',
 'Sáng Thế Ký 28:12 — "Thấy một cái thang bắc từ dưới đất, đầu đến tận trời, các thiên sứ của Đức Chúa Trời đi lên xuống trên thang đó."',
 '["Sáng Thế Ký","Gia-cốp","Bê-tên"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-gen-039', 'Genesis', 29, 20, 20, 'easy', 'multiple_choice_single',
 'Gia-cốp phải phục vụ La-ban bao nhiêu năm để cưới Ra-chên? (Sáng 29:20)',
 '["3 năm","5 năm","7 năm","10 năm"]',
 '[2]',
 'Sáng Thế Ký 29:20 — "Vậy, Gia-cốp vì Ra-chên, phải giúp việc bảy năm; nhưng bởi yêu nàng, nên coi bảy năm bằng chừng đôi ba bữa."',
 '["Sáng Thế Ký","Gia-cốp","Ra-chên"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-gen-040', 'Genesis', 29, 25, 25, 'easy', 'multiple_choice_single',
 'La-ban đã lừa Gia-cốp bằng cách gả cho ông ai thay vì Ra-chên? (Sáng 29:25)',
 '["Lê-a","Bi-la","Xinh-ba","Đi-na"]',
 '[0]',
 'Sáng Thế Ký 29:25 — "Rạng sáng ra, té ra là Lê-a! Gia-cốp bèn nói cùng La-ban rằng: Cậu đã đãi tôi cách chi vậy?"',
 '["Sáng Thế Ký","Gia-cốp","Lê-a"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-gen-041', 'Genesis', 32, 28, 28, 'easy', 'multiple_choice_single',
 'Sau khi vật lộn với thiên sứ, Gia-cốp được đổi tên thành gì? (Sáng 32:28)',
 '["Y-sơ-ra-ên","Áp-ra-ham","Giu-đa","Đa-ni-ên"]',
 '[0]',
 'Sáng Thế Ký 32:28 — "Tên ngươi sẽ chẳng là Gia-cốp nữa, nhưng tên là Y-sơ-ra-ên, vì ngươi đã vật lộn cùng Đức Chúa Trời và người ta."',
 '["Sáng Thế Ký","Gia-cốp","Y-sơ-ra-ên"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-gen-042', 'Genesis', 35, 18, 18, 'easy', 'multiple_choice_single',
 'Ra-chên qua đời khi sanh con trai nào? (Sáng 35:18)',
 '["Giu-đa","Đan","Bên-gia-min","Giô-sép"]',
 '[2]',
 'Sáng Thế Ký 35:18 — "Lúc gần trút linh hồn, vì nàng hầu chết, thì đặt đứa con trai tên là Bê-nô-ni; còn cha nó lại đặt tên là Bên-gia-min."',
 '["Sáng Thế Ký","Ra-chên","Bên-gia-min"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-gen-043', 'Genesis', 27, 16, 16, 'medium', 'multiple_choice_single',
 'Rê-bê-ca giúp Gia-cốp lừa Y-sác bằng cách lấy gì phủ lên tay và cổ? (Sáng 27:16)',
 '["Lông chiên","Lá cây","Da dê con","Vải thô"]',
 '[2]',
 'Sáng Thế Ký 27:16 — "Rồi lấy da dê con bọc hai tay và chỗ nhẵn nơi cổ người."',
 '["Sáng Thế Ký","Gia-cốp","Lừa dối"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-gen-044', 'Genesis', 30, 22, 24, 'medium', 'multiple_choice_single',
 'Ra-chên sanh con trai đầu lòng cho Gia-cốp tên là gì? (Sáng 30:24)',
 '["Ru-bên","Si-mê-ôn","Giu-đa","Giô-sép"]',
 '[3]',
 'Sáng Thế Ký 30:24 — "Nàng đặt tên đứa trai đó là Giô-sép, mà rằng: Cầu Đức Giê-hô-va thêm cho một con trai nữa!"',
 '["Sáng Thế Ký","Ra-chên","Giô-sép"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-gen-045', 'Genesis', 33, 4, 4, 'medium', 'multiple_choice_single',
 'Khi Gia-cốp gặp lại Ê-sau sau nhiều năm, Ê-sau phản ứng thế nào? (Sáng 33:4)',
 '["Tức giận đánh","Chạy đến ôm choàng và hôn","Từ chối gặp mặt","Đòi trả thù"]',
 '[1]',
 'Sáng Thế Ký 33:4 — "Nhưng Ê-sau chạy đến trước mặt người, ôm choàng lấy cổ mà hôn, rồi hai anh em đều khóc."',
 '["Sáng Thế Ký","Gia-cốp","Ê-sau"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-gen-046', 'Genesis', 28, 22, 22, 'medium', 'multiple_choice_single',
 'Tại Bê-tên, Gia-cốp hứa dâng cho Đức Chúa Trời phần bao nhiêu? (Sáng 28:22)',
 '["Một phần năm","Một phần mười","Một phần ba","Một nửa"]',
 '[1]',
 'Sáng Thế Ký 28:22 — "Và về các tài vật mà Ngài sẽ cho tôi, tôi sẽ dâng một phần mười cho Ngài."',
 '["Sáng Thế Ký","Gia-cốp","Phần mười"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-gen-047', 'Genesis', 31, 19, 19, 'medium', 'multiple_choice_single',
 'Khi Gia-cốp trốn khỏi La-ban, Ra-chên đã lấy trộm vật gì? (Sáng 31:19)',
 '["Vàng bạc","Pho tượng thần","Chiên dê","Lương thực"]',
 '[1]',
 'Sáng Thế Ký 31:19 — "Khi La-ban đi hớt lông chiên, thì Ra-chên lấy trộm các pho tượng thần của cha mình."',
 '["Sáng Thế Ký","Ra-chên","La-ban"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-gen-048', 'Genesis', 25, 30, 30, 'hard', 'multiple_choice_single',
 'Ê-sau còn có biệt danh nào khác? Tại sao? (Sáng 25:30)',
 '["Ê-đôm, vì món canh đỏ","Sê-i-rơ, vì ở trên núi","Y-sơ-ra-ên, vì vật lộn","Ca-na-an, vì ở xứ đó"]',
 '[0]',
 'Sáng Thế Ký 25:30 — "Ê-sau nói cùng Gia-cốp rằng: Xin cho tôi ăn món đỏ đó... Bởi cớ ấy, nên người ta gọi tên người là Ê-đôm."',
 '["Sáng Thế Ký","Ê-sau","Ê-đôm"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-gen-049', 'Genesis', 32, 25, 25, 'hard', 'multiple_choice_single',
 'Khi vật lộn với Gia-cốp, thiên sứ đã đánh vào phần nào trên thân thể ông? (Sáng 32:25)',
 '["Vai","Lưng","Xương hông","Đầu gối"]',
 '[2]',
 'Sáng Thế Ký 32:25 — "Khi người đó thấy mình không thắng nổi, bèn đánh vào xương hông của Gia-cốp; xương hông liền trặc."',
 '["Sáng Thế Ký","Gia-cốp","Vật lộn"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-gen-050', 'Genesis', 36, 1, 1, 'hard', 'multiple_choice_single',
 'Dòng dõi Ê-sau trở thành dân tộc nào, cư ngụ trên núi Sê-i-rơ? (Sáng 36:1,8)',
 '["Dân Mô-áp","Dân Am-môn","Dân Ê-đôm","Dân Phi-li-tin"]',
 '[2]',
 'Sáng Thế Ký 36:1,8 — "Đây là dòng dõi của Ê-sau, tức là Ê-đôm... Vậy, Ê-sau ở trên núi Sê-i-rơ."',
 '["Sáng Thế Ký","Ê-sau","Ê-đôm"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

-- ═══════════════════════════════════════════════════════════════
-- CHƯƠNG 37-50: GIÔ-SÉP (20 câu: 6 easy, 9 medium, 5 hard)
-- ═══════════════════════════════════════════════════════════════

('bq-gen-051', 'Genesis', 37, 3, 3, 'easy', 'multiple_choice_single',
 'Gia-cốp tặng cho Giô-sép món quà đặc biệt nào? (Sáng 37:3)',
 '["Đàn chiên","Vòng vàng","Một cái áo dài nhiều màu","Con lừa"]',
 '[2]',
 'Sáng Thế Ký 37:3 — "Y-sơ-ra-ên thương yêu Giô-sép hơn những con trai khác... may cho chàng một cái áo dài có nhiều sắc."',
 '["Sáng Thế Ký","Giô-sép","Áo nhiều màu"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-gen-052', 'Genesis', 37, 28, 28, 'easy', 'multiple_choice_single',
 'Các anh của Giô-sép bán chàng cho ai? (Sáng 37:28)',
 '["Người Ai Cập","Những lái buôn Ma-đi-an","Người Ca-na-an","Người Phi-li-tin"]',
 '[1]',
 'Sáng Thế Ký 37:28 — "Bán Giô-sép cho dân Ích-ma-ên giá hai mươi miếng bạc. Các lái buôn đó đem Giô-sép đến xứ Ê-díp-tô."',
 '["Sáng Thế Ký","Giô-sép","Bị bán"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-gen-053', 'Genesis', 39, 1, 1, 'easy', 'multiple_choice_single',
 'Tại Ai Cập, Giô-sép phục vụ trong nhà ai? (Sáng 39:1)',
 '["Quan chép","Quan dọn rượu","Pha-ra-ôn","Phô-ti-pha"]',
 '[3]',
 'Sáng Thế Ký 39:1 — "Giô-sép bị đem qua xứ Ê-díp-tô; Phô-ti-pha, quan thị vệ của Pha-ra-ôn, người Ê-díp-tô, mua chàng."',
 '["Sáng Thế Ký","Giô-sép","Phô-ti-pha"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-gen-054', 'Genesis', 41, 46, 46, 'easy', 'multiple_choice_single',
 'Giô-sép bao nhiêu tuổi khi ra mắt Pha-ra-ôn vua Ai Cập? (Sáng 41:46)',
 '["17 tuổi","25 tuổi","30 tuổi","40 tuổi"]',
 '[2]',
 'Sáng Thế Ký 41:46 — "Vả, khi Giô-sép ra mắt Pha-ra-ôn, vua Ê-díp-tô, thì người đã được ba mươi tuổi."',
 '["Sáng Thế Ký","Giô-sép","Tuổi"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-gen-055', 'Genesis', 45, 4, 4, 'easy', 'multiple_choice_single',
 'Khi tỏ danh mình cho các anh, Giô-sép nói: "Tôi là..." ai? (Sáng 45:4)',
 '["Người lạ","Quan án","Giô-sép, em mà các anh đã bán","Tể tướng Ai Cập"]',
 '[2]',
 'Sáng Thế Ký 45:4 — "Giô-sép lại nói cùng các anh rằng: Xin hãy lại gần tôi. Các anh bèn lại gần. Người nói: Tôi là Giô-sép, em mà các anh đã bán đặng đem qua xứ Ê-díp-tô."',
 '["Sáng Thế Ký","Giô-sép","Tỏ danh"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-gen-056', 'Genesis', 46, 27, 27, 'easy', 'multiple_choice_single',
 'Tổng cộng bao nhiêu người thuộc nhà Gia-cốp đến Ai Cập? (Sáng 46:27)',
 '["Bốn mươi","Bảy mươi","Sáu mươi","Năm mươi"]',
 '[1]',
 'Sáng Thế Ký 46:27 — "Hết thảy các người thuộc về nhà Gia-cốp đến xứ Ê-díp-tô là bảy mươi người."',
 '["Sáng Thế Ký","Gia-cốp","Ai Cập"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-gen-057', 'Genesis', 37, 9, 9, 'medium', 'multiple_choice_single',
 'Trong giấc chiêm bao thứ hai của Giô-sép, những gì quì lạy chàng? (Sáng 37:9)',
 '["Các con thú","Cây cối trong vườn","11 bó lúa","Mặt trời, mặt trăng và 11 ngôi sao"]',
 '[3]',
 'Sáng Thế Ký 37:9 — "Tôi còn chiêm bao nữa: mặt trời, mặt trăng và mười một ngôi sao đều quì lạy tôi."',
 '["Sáng Thế Ký","Giô-sép","Chiêm bao"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-gen-058', 'Genesis', 39, 20, 20, 'medium', 'multiple_choice_single',
 'Giô-sép bị bỏ tù vì tội gì (mà ông không phạm)? (Sáng 39:17-20)',
 '["Nổi loạn","Giết người","Ăn trộm","Bị vu cáo tấn công vợ Phô-ti-pha"]',
 '[3]',
 'Sáng Thế Ký 39:17-20 — "Nàng bèn lấy lời như vậy mà nói cùng chồng rằng: Tên nô lệ Hê-bơ-rơ... muốn đến giỡn cợt tôi... Chủ bỏ Giô-sép vào tù."',
 '["Sáng Thế Ký","Giô-sép","Ngục tù"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-gen-059', 'Genesis', 40, 8, 22, 'medium', 'multiple_choice_single',
 'Trong tù, Giô-sép giải nghĩa chiêm bao cho hai quan nào của Pha-ra-ôn? (Sáng 40:1-2)',
 '["Quan tư pháp và quan tài chính","Quan thị vệ và quan quân đội","Quan dọn rượu và quan làm bánh","Quan cận vệ và quan chép"]',
 '[2]',
 'Sáng Thế Ký 40:1-2 — "Quan dọn rượu và quan làm bánh phạm đến vua Ê-díp-tô, là chúa của mình."',
 '["Sáng Thế Ký","Giô-sép","Chiêm bao"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-gen-060', 'Genesis', 41, 29, 30, 'medium', 'multiple_choice_single',
 'Giô-sép giải nghĩa chiêm bao của Pha-ra-ôn: bao nhiêu năm được mùa và bao nhiêu năm đói kém? (Sáng 41:29-30)',
 '["5 năm và 5 năm","7 năm và 7 năm","10 năm và 10 năm","3 năm và 3 năm"]',
 '[1]',
 'Sáng Thế Ký 41:29-30 — "Nầy bảy năm sẽ được mùa lớn trong cả xứ Ê-díp-tô; rồi bảy năm đói kém sẽ xảy đến."',
 '["Sáng Thế Ký","Giô-sép","Chiêm bao"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-gen-061', 'Genesis', 42, 24, 24, 'medium', 'multiple_choice_single',
 'Khi các anh đến Ai Cập mua lúa, Giô-sép giữ ai lại làm con tin? (Sáng 42:24)',
 '["Lê-vi","Giu-đa","Ru-bên","Si-mê-ôn"]',
 '[3]',
 'Sáng Thế Ký 42:24 — "Giô-sép bèn lui ra khóc; đoạn, trở vào, truyền bắt trói Si-mê-ôn trước mặt họ."',
 '["Sáng Thế Ký","Giô-sép","Con tin"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-gen-062', 'Genesis', 43, 34, 34, 'medium', 'multiple_choice_single',
 'Khi đãi tiệc các anh, phần ăn của Bên-gia-min lớn hơn bao nhiêu lần so với anh em? (Sáng 43:34)',
 '["Hai lần","Ba lần","Năm lần","Mười lần"]',
 '[2]',
 'Sáng Thế Ký 43:34 — "Giô-sép lấy đồ ăn trước mặt mình mà phân phát cho anh em; phần của Bên-gia-min lớn hơn phần của anh em gấp năm."',
 '["Sáng Thế Ký","Giô-sép","Bên-gia-min"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-gen-063', 'Genesis', 44, 2, 2, 'medium', 'multiple_choice_single',
 'Giô-sép sai giấu vật gì trong bao lúa của Bên-gia-min để thử các anh? (Sáng 44:2)',
 '["Chén bạc","Vòng vàng","Áo dài","Tiền bạc"]',
 '[0]',
 'Sáng Thế Ký 44:2 — "Rồi hãy để chén bạc của ta trong miệng bao đứa út, cùng số bạc trả về lúa."',
 '["Sáng Thế Ký","Giô-sép","Thử thách"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-gen-064', 'Genesis', 47, 11, 11, 'medium', 'multiple_choice_single',
 'Giô-sép cho cha và anh em định cư tại vùng đất nào ở Ai Cập? (Sáng 47:11)',
 '["Đất Ca-na-an","Đất Ram-se","Đất Gô-sen","Đất Si-na-i"]',
 '[2]',
 'Sáng Thế Ký 47:11 — "Giô-sép vâng mạng Pha-ra-ôn, cho cha và anh em mình ở, và cấp đất đai cho họ trong miền tốt nhứt của xứ Ê-díp-tô, tại đất Ram-se."',
 '["Sáng Thế Ký","Giô-sép","Gô-sen"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-gen-065', 'Genesis', 50, 20, 20, 'medium', 'multiple_choice_single',
 'Giô-sép nói gì với anh em mình về việc họ bán ông? (Sáng 50:20)',
 '["Tôi quên hết rồi","Tôi không tha thứ","Tôi sẽ trả thù","Các anh toan hại tôi, nhưng Đức Chúa Trời toan làm điều ích"]',
 '[3]',
 'Sáng Thế Ký 50:20 — "Các anh toan hại tôi, nhưng Đức Chúa Trời lại toan làm điều ích cho tôi, hầu cho cứu sống dân sự đông đảo."',
 '["Sáng Thế Ký","Giô-sép","Tha thứ"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-gen-066', 'Genesis', 37, 28, 28, 'hard', 'multiple_choice_single',
 'Giô-sép bị bán với giá bao nhiêu miếng bạc? (Sáng 37:28)',
 '["Ba mươi miếng bạc","Bốn mươi miếng bạc","Mười miếng bạc","Hai mươi miếng bạc"]',
 '[3]',
 'Sáng Thế Ký 37:28 — "Bán Giô-sép cho dân Ích-ma-ên giá hai mươi miếng bạc."',
 '["Sáng Thế Ký","Giô-sép","Giá bán"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-gen-067', 'Genesis', 41, 51, 52, 'hard', 'multiple_choice_single',
 'Hai con trai của Giô-sép sanh tại Ai Cập tên là gì? (Sáng 41:51-52)',
 '["Ma-na-se và Ép-ra-im","Ru-bên và Si-mê-ôn","Ghê-rơ-sôn và Ê-li-ê-se","Phê-rết và Sê-rách"]',
 '[0]',
 'Sáng Thế Ký 41:51-52 — "Giô-sép đặt tên con đầu lòng là Ma-na-se... đặt tên đứa thứ nhì là Ép-ra-im."',
 '["Sáng Thế Ký","Giô-sép","Ma-na-se","Ép-ra-im"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-gen-068', 'Genesis', 48, 14, 14, 'hard', 'multiple_choice_single',
 'Khi chúc phước cho hai con Giô-sép, Gia-cốp đặt tay phải lên đầu ai? (Sáng 48:14)',
 '["Cả hai cùng lúc","Ép-ra-im (con thứ)","Ma-na-se (con cả)","Giô-sép"]',
 '[1]',
 'Sáng Thế Ký 48:14 — "Y-sơ-ra-ên đưa tay hữu ra đặt trên đầu Ép-ra-im, là đứa nhỏ, còn tay tả lại đặt trên đầu Ma-na-se."',
 '["Sáng Thế Ký","Gia-cốp","Chúc phước"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-gen-069', 'Genesis', 49, 10, 10, 'hard', 'multiple_choice_single',
 'Theo lời chúc phước của Gia-cốp, cây phủ việt sẽ không rời khỏi chi phái nào? (Sáng 49:10)',
 '["Giô-sép","Bên-gia-min","Ru-bên","Giu-đa"]',
 '[3]',
 'Sáng Thế Ký 49:10 — "Cây phủ việt chẳng hề dời khỏi Giu-đa, kẻ lập pháp không dứt khỏi giữa chân nó."',
 '["Sáng Thế Ký","Giu-đa","Tiên tri"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-gen-070', 'Genesis', 50, 26, 26, 'hard', 'multiple_choice_single',
 'Giô-sép qua đời lúc bao nhiêu tuổi và thi thể được xử lý thế nào? (Sáng 50:26)',
 '["120 tuổi, hỏa táng","90 tuổi, chôn bên cạnh cha","110 tuổi, ướp xác đặt trong quan tài tại Ai Cập","100 tuổi, chôn tại Ca-na-an"]',
 '[2]',
 'Sáng Thế Ký 50:26 — "Giô-sép qua đời, hưởng thọ được một trăm mười tuổi; người ta xông thuốc thơm cho xác người và liệm vào quan tài tại xứ Ê-díp-tô."',
 '["Sáng Thế Ký","Giô-sép","Qua đời"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW());
