-- Exodus (Xuất Ê-díp-tô Ký) seed data: 60 questions (25 easy, 22 medium, 13 hard)
-- Source: Kinh Thánh Bản Truyền Thống 1926 (public domain)

INSERT IGNORE INTO questions (
  id, book, chapter, verse_start, verse_end,
  difficulty, type, content, options, correct_answer,
  explanation, tags, source, language, review_status, approvals_count, is_active,
  created_at, updated_at
) VALUES

-- ═══════════════════════════════════════════════════════════════
-- EASY (25 questions)
-- ═══════════════════════════════════════════════════════════════

('bq-exo-001', 'Exodus', 1, 22, 22, 'easy', 'multiple_choice_single',
 'Pha-ra-ôn ra lệnh ném con trai người Hê-bơ-rơ xuống đâu? (Xuất 1:22)',
 '["Sông Ni-lơ","Biển Đỏ","Sa mạc","Hầm lửa"]',
 '[0]',
 'Xuất Ê-díp-tô Ký 1:22 — "Pha-ra-ôn bèn truyền lịnh cho cả dân mình rằng: Hễ con trai nào mới sanh của dân Hê-bơ-rơ, hãy liệng xuống sông."',
 '["Xuất Ê-díp-tô Ký","Môi-se","Chương 1"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-exo-002', 'Exodus', 2, 3, 3, 'easy', 'multiple_choice_single',
 'Mẹ Môi-se đặt ông trong vật gì thả trên sông Ni-lơ? (Xuất 2:3)',
 '["Một cái thuyền lớn","Một chiếc bè","Một cái rương mây","Một tấm ván"]',
 '[2]',
 'Xuất Ê-díp-tô Ký 2:3 — "Không thể giấu được nữa, bèn lấy một cái rương mây, trét chai và nhựa thông, để đứa trẻ vào, rồi đem thả trong đám sậy nơi mé sông."',
 '["Xuất Ê-díp-tô Ký","Môi-se","Ra đời"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-exo-003', 'Exodus', 2, 5, 6, 'easy', 'multiple_choice_single',
 'Ai đã vớt Môi-se lên khỏi sông Ni-lơ? (Xuất 2:5-6)',
 '["Vợ Pha-ra-ôn","Con gái Pha-ra-ôn","Nữ tì Pha-ra-ôn","Chị của Môi-se"]',
 '[1]',
 'Xuất Ê-díp-tô Ký 2:5 — "Con gái Pha-ra-ôn xuống sông tắm... thấy cái rương trong đám sậy, bèn sai con đòi đi vớt lên."',
 '["Xuất Ê-díp-tô Ký","Môi-se","Ra đời"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-exo-004', 'Exodus', 2, 10, 10, 'easy', 'multiple_choice_single',
 'Tên "Môi-se" có nghĩa là gì? (Xuất 2:10)',
 '["Được chọn","Vớt khỏi nước","Con trai vua","Người được cứu"]',
 '[1]',
 'Xuất Ê-díp-tô Ký 2:10 — "Nàng đặt tên là Môi-se, nói rằng: Vì ta đã vớt nó khỏi nước."',
 '["Xuất Ê-díp-tô Ký","Môi-se","Tên gọi"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-exo-005', 'Exodus', 3, 2, 2, 'easy', 'multiple_choice_single',
 'Đức Chúa Trời hiện ra với Môi-se qua hình ảnh gì tại núi Hô-rếp? (Xuất 3:2)',
 '["Đám mây","Bụi gai cháy","Cột lửa","Cầu vồng"]',
 '[1]',
 'Xuất Ê-díp-tô Ký 3:2 — "Thiên sứ của Đức Giê-hô-va hiện ra cùng người trong ngọn lửa, giữa bụi gai kia."',
 '["Xuất Ê-díp-tô Ký","Bụi gai cháy","Môi-se"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-exo-006', 'Exodus', 3, 5, 5, 'easy', 'multiple_choice_single',
 'Đức Chúa Trời bảo Môi-se làm gì khi đứng trước bụi gai cháy? (Xuất 3:5)',
 '["Quỳ xuống","Cởi giày ra","Che mặt","Nằm sấp"]',
 '[1]',
 'Xuất Ê-díp-tô Ký 3:5 — "Chớ lại gần đây, hãy cởi giày ra khỏi chân, vì chỗ ngươi đương đứng là đất thánh."',
 '["Xuất Ê-díp-tô Ký","Bụi gai cháy","Đất thánh"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-exo-007', 'Exodus', 3, 14, 14, 'easy', 'multiple_choice_single',
 'Đức Chúa Trời xưng danh Ngài với Môi-se là gì? (Xuất 3:14)',
 '["Ta là Đấng Toàn Năng","Ta là Đấng Tự Hữu Hằng Hữu","Ta là Chúa các chúa","Ta là Đấng Chí Cao"]',
 '[1]',
 'Xuất Ê-díp-tô Ký 3:14 — "Đức Chúa Trời phán rằng: Ta là Đấng Tự Hữu Hằng Hữu."',
 '["Xuất Ê-díp-tô Ký","Danh Chúa","Bụi gai cháy"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-exo-008', 'Exodus', 4, 2, 4, 'easy', 'multiple_choice_single',
 'Đức Chúa Trời biến cây gậy của Môi-se thành con gì? (Xuất 4:3)',
 '["Con chim","Con rắn","Con cá","Con sư tử"]',
 '[1]',
 'Xuất Ê-díp-tô Ký 4:3 — "Hãy liệng nó xuống đất. Người bèn liệng xuống đất, gậy bèn hóa thành một con rắn."',
 '["Xuất Ê-díp-tô Ký","Dấu lạ","Gậy Môi-se"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-exo-009', 'Exodus', 7, 20, 20, 'easy', 'multiple_choice_single',
 'Tai vạ đầu tiên giáng trên Ai Cập là gì? (Xuất 7:20)',
 '["Nước biến thành máu","Ếch nhái","Muỗi","Mụt nhọt"]',
 '[0]',
 'Xuất Ê-díp-tô Ký 7:20 — "Người giơ gậy lên, đập nước nơi sông trước mặt Pha-ra-ôn và quần thần; hết thảy nước trong sông biến thành máu."',
 '["Xuất Ê-díp-tô Ký","Mười tai vạ","Tai vạ 1"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-exo-010', 'Exodus', 8, 6, 6, 'easy', 'multiple_choice_single',
 'Tai vạ thứ hai giáng trên Ai Cập là gì? (Xuất 8:6)',
 '["Muỗi","Ếch nhái","Ruồi mòng","Châu chấu"]',
 '[1]',
 'Xuất Ê-díp-tô Ký 8:6 — "A-rôn giơ tay trên các sông ngòi ao đầm xứ Ê-díp-tô, ếch nhái bò lên lan khắp xứ."',
 '["Xuất Ê-díp-tô Ký","Mười tai vạ","Tai vạ 2"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-exo-011', 'Exodus', 12, 3, 6, 'easy', 'multiple_choice_single',
 'Trong lễ Vượt Qua, mỗi gia đình phải giết con vật gì? (Xuất 12:3)',
 '["Bò đực","Chiên con","Dê đực","Bồ câu"]',
 '[1]',
 'Xuất Ê-díp-tô Ký 12:3 — "Mỗi người tùy theo nhà mình phải bắt một con chiên con."',
 '["Xuất Ê-díp-tô Ký","Lễ Vượt Qua","Chiên con"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-exo-012', 'Exodus', 12, 7, 7, 'easy', 'multiple_choice_single',
 'Dân Y-sơ-ra-ên bôi huyết chiên con ở đâu trong lễ Vượt Qua? (Xuất 12:7)',
 '["Trên bàn thờ","Trên mặt đất","Trên hai cây cột và mày cửa","Trên áo"]',
 '[2]',
 'Xuất Ê-díp-tô Ký 12:7 — "Hãy lấy huyết đem bôi trên hai cây cột và mày cửa của nhà mình ăn thịt chiên con đó."',
 '["Xuất Ê-díp-tô Ký","Lễ Vượt Qua","Huyết"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-exo-013', 'Exodus', 12, 29, 29, 'easy', 'multiple_choice_single',
 'Tai vạ cuối cùng giáng trên Ai Cập là gì? (Xuất 12:29)',
 '["Tối tăm ba ngày","Chết các con đầu lòng","Mưa đá","Châu chấu"]',
 '[1]',
 'Xuất Ê-díp-tô Ký 12:29 — "Đức Giê-hô-va hành hại mọi con đầu lòng tại xứ Ê-díp-tô."',
 '["Xuất Ê-díp-tô Ký","Mười tai vạ","Tai vạ 10"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-exo-014', 'Exodus', 14, 21, 21, 'easy', 'multiple_choice_single',
 'Đức Chúa Trời dùng gì để rẽ nước Biển Đỏ? (Xuất 14:21)',
 '["Sấm sét","Gió đông thổi mạnh","Động đất","Lời phán"]',
 '[1]',
 'Xuất Ê-díp-tô Ký 14:21 — "Đức Giê-hô-va dùng gió đông thổi mạnh đuổi nước lại trọn cả đêm, làm cho biển thành đất khô."',
 '["Xuất Ê-díp-tô Ký","Biển Đỏ","Phép lạ"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-exo-015', 'Exodus', 14, 28, 28, 'easy', 'multiple_choice_single',
 'Điều gì xảy ra với quân Ai Cập khi đuổi theo dân Y-sơ-ra-ên qua Biển Đỏ? (Xuất 14:28)',
 '["Họ quay lại","Nước phủ lại chết hết","Họ bị lạc","Họ đầu hàng"]',
 '[1]',
 'Xuất Ê-díp-tô Ký 14:28 — "Nước trở lại bao phủ xe cộ, lính kỵ, cả đạo binh Pha-ra-ôn đã theo dân Y-sơ-ra-ên xuống biển; không còn sót lại một ai."',
 '["Xuất Ê-díp-tô Ký","Biển Đỏ","Quân Ai Cập"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-exo-016', 'Exodus', 16, 15, 15, 'easy', 'multiple_choice_single',
 'Thức ăn Đức Chúa Trời ban từ trời cho dân Y-sơ-ra-ên trong đồng vắng gọi là gì? (Xuất 16:15)',
 '["Bánh mì","Ma-na","Mật ong","Trái cây"]',
 '[1]',
 'Xuất Ê-díp-tô Ký 16:15 — "Khi dân Y-sơ-ra-ên thấy, bèn hỏi nhau rằng: Cái chi vậy? ... Môi-se nói: Ấy là bánh mà Đức Giê-hô-va ban cho các ngươi làm lương thực đó."',
 '["Xuất Ê-díp-tô Ký","Ma-na","Đồng vắng"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-exo-017', 'Exodus', 20, 3, 3, 'easy', 'multiple_choice_single',
 'Điều răn thứ nhất trong Mười Điều Răn là gì? (Xuất 20:3)',
 '["Không được giết người","Trước mặt ta, ngươi chớ có các thần khác","Hãy hiếu kính cha mẹ","Không được nói dối"]',
 '[1]',
 'Xuất Ê-díp-tô Ký 20:3 — "Trước mặt ta, ngươi chớ có các thần khác."',
 '["Xuất Ê-díp-tô Ký","Mười Điều Răn","Điều răn 1"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-exo-018', 'Exodus', 20, 8, 8, 'easy', 'multiple_choice_single',
 'Điều răn thứ tư dạy về điều gì? (Xuất 20:8)',
 '["Không trộm cắp","Nhớ ngày Sa-bát","Không tham lam","Không ngoại tình"]',
 '[1]',
 'Xuất Ê-díp-tô Ký 20:8 — "Hãy nhớ ngày nghỉ đặng làm nên ngày thánh."',
 '["Xuất Ê-díp-tô Ký","Mười Điều Răn","Ngày Sa-bát"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-exo-019', 'Exodus', 20, 12, 12, 'easy', 'multiple_choice_single',
 'Điều răn thứ năm dạy chúng ta phải làm gì? (Xuất 20:12)',
 '["Không giết người","Không trộm cắp","Hiếu kính cha mẹ","Không tham lam"]',
 '[2]',
 'Xuất Ê-díp-tô Ký 20:12 — "Hãy hiếu kính cha mẹ ngươi, hầu cho ngươi được sống lâu trên đất mà Giê-hô-va Đức Chúa Trời ngươi ban cho."',
 '["Xuất Ê-díp-tô Ký","Mười Điều Răn","Hiếu kính"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-exo-020', 'Exodus', 20, 13, 13, 'easy', 'multiple_choice_single',
 'Điều răn thứ sáu là gì? (Xuất 20:13)',
 '["Ngươi chớ tham lam","Ngươi chớ nói dối","Ngươi chớ ngoại tình","Ngươi chớ giết người"]',
 '[3]',
 'Xuất Ê-díp-tô Ký 20:13 — "Ngươi chớ giết người."',
 '["Xuất Ê-díp-tô Ký","Mười Điều Răn","Điều răn 6"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-exo-021', 'Exodus', 32, 4, 4, 'easy', 'multiple_choice_single',
 'Dân Y-sơ-ra-ên đã đúc hình tượng con gì bằng vàng? (Xuất 32:4)',
 '["Con sư tử","Con dê","Con chiên","Con bò con"]',
 '[3]',
 'Xuất Ê-díp-tô Ký 32:4 — "Người nhận lấy nơi tay họ, và dùng đục mà làm thành một con bò con đúc."',
 '["Xuất Ê-díp-tô Ký","Bò con vàng","Thờ hình tượng"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-exo-022', 'Exodus', 2, 1, 2, 'easy', 'multiple_choice_single',
 'Môi-se thuộc chi phái nào của Y-sơ-ra-ên? (Xuất 2:1)',
 '["Giu-đa","Lê-vi","Bên-gia-min","Ru-bên"]',
 '[1]',
 'Xuất Ê-díp-tô Ký 2:1 — "Một người thuộc nhà Lê-vi đi cưới con gái Lê-vi."',
 '["Xuất Ê-díp-tô Ký","Môi-se","Chi phái Lê-vi"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-exo-023', 'Exodus', 15, 20, 20, 'easy', 'multiple_choice_single',
 'Chị của Môi-se tên là gì? (Xuất 15:20)',
 '["Ra-chên","Sa-ra","Mi-ri-am","Rê-bê-ca"]',
 '[2]',
 'Xuất Ê-díp-tô Ký 15:20 — "Mi-ri-am, nữ tiên tri, là chị A-rôn, tay cầm trống cơm, các đàn bà đều đi theo."',
 '["Xuất Ê-díp-tô Ký","Mi-ri-am","Bài ca"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-exo-024', 'Exodus', 4, 14, 14, 'easy', 'multiple_choice_single',
 'Ai được Đức Chúa Trời chọn làm người nói thay cho Môi-se? (Xuất 4:14)',
 '["Giô-suê","A-rôn","Ca-lép","Ê-li"]',
 '[1]',
 'Xuất Ê-díp-tô Ký 4:14 — "A-rôn, anh ngươi, là người Lê-vi chẳng phải ở đó sao? Ta biết rằng người nói được giỏi."',
 '["Xuất Ê-díp-tô Ký","A-rôn","Người phát ngôn"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-exo-025', 'Exodus', 20, 4, 4, 'easy', 'multiple_choice_single',
 'Điều răn thứ hai cấm làm điều gì? (Xuất 20:4)',
 '["Giết người","Tham lam","Làm tượng chạm","Nói dối"]',
 '[2]',
 'Xuất Ê-díp-tô Ký 20:4 — "Ngươi chớ làm tượng chạm cho mình, cũng chớ làm tượng nào giống những vật trên trời cao kia."',
 '["Xuất Ê-díp-tô Ký","Mười Điều Răn","Điều răn 2"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

-- ═══════════════════════════════════════════════════════════════
-- MEDIUM (22 questions)
-- ═══════════════════════════════════════════════════════════════

('bq-exo-026', 'Exodus', 1, 15, 16, 'medium', 'multiple_choice_single',
 'Pha-ra-ôn ra lệnh cho hai bà mụ nào giết con trai Hê-bơ-rơ? (Xuất 1:15)',
 '["Si-bê-ra và Đê-bô-ra","Sip-ra và Phu-a","Ma-ri và An-ne","Ra-chên và Lê-a"]',
 '[1]',
 'Xuất Ê-díp-tô Ký 1:15 — "Vua Ê-díp-tô cũng phán cùng các bà mụ của dân Hê-bơ-rơ, tên một người là Sip-ra và tên người kia là Phu-a."',
 '["Xuất Ê-díp-tô Ký","Bà mụ","Chương 1"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-exo-027', 'Exodus', 2, 15, 15, 'medium', 'multiple_choice_single',
 'Sau khi giết người Ai Cập, Môi-se chạy trốn đến xứ nào? (Xuất 2:15)',
 '["Ca-na-an","Ma-đi-an","Ê-đôm","Mô-áp"]',
 '[1]',
 'Xuất Ê-díp-tô Ký 2:15 — "Pha-ra-ôn hay được, tìm giết Môi-se; nhưng Môi-se trốn khỏi mặt Pha-ra-ôn, đi ở tại xứ Ma-đi-an."',
 '["Xuất Ê-díp-tô Ký","Môi-se","Ma-đi-an"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-exo-028', 'Exodus', 2, 21, 22, 'medium', 'multiple_choice_single',
 'Vợ của Môi-se tại Ma-đi-an tên là gì? (Xuất 2:21)',
 '["Sê-phô-ra","Đê-bô-ra","Ra-háp","Rê-bê-ca"]',
 '[0]',
 'Xuất Ê-díp-tô Ký 2:21 — "Môi-se ưng ở cùng người, và người gả Sê-phô-ra, con gái mình cho Môi-se."',
 '["Xuất Ê-díp-tô Ký","Sê-phô-ra","Ma-đi-an"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-exo-029', 'Exodus', 3, 1, 1, 'medium', 'multiple_choice_single',
 'Bố vợ của Môi-se tên là gì? (Xuất 3:1)',
 '["Giê-trô","La-ban","Giê-se","Na-ba"]',
 '[0]',
 'Xuất Ê-díp-tô Ký 3:1 — "Vả, Môi-se chăn bầy chiên cho Giê-trô, ông gia mình, là thầy tế lễ xứ Ma-đi-an."',
 '["Xuất Ê-díp-tô Ký","Giê-trô","Ma-đi-an"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-exo-030', 'Exodus', 7, 7, 7, 'medium', 'multiple_choice_single',
 'Môi-se bao nhiêu tuổi khi nói chuyện với Pha-ra-ôn? (Xuất 7:7)',
 '["40 tuổi","60 tuổi","80 tuổi","100 tuổi"]',
 '[2]',
 'Xuất Ê-díp-tô Ký 7:7 — "Khi nói cùng Pha-ra-ôn, Môi-se đã được tám mươi tuổi, A-rôn đã được tám mươi ba tuổi."',
 '["Xuất Ê-díp-tô Ký","Tuổi Môi-se","Pha-ra-ôn"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-exo-031', 'Exodus', 8, 16, 17, 'medium', 'multiple_choice_single',
 'Tai vạ thứ ba giáng trên Ai Cập là gì? (Xuất 8:16-17)',
 '["Ruồi mòng","Muỗi","Châu chấu","Mụt nhọt"]',
 '[1]',
 'Xuất Ê-díp-tô Ký 8:16-17 — "A-rôn giơ gậy ra đập bụi trên đất, bụi liền hóa thành muỗi, bu trên mình người ta và súc vật."',
 '["Xuất Ê-díp-tô Ký","Mười tai vạ","Tai vạ 3"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-exo-032', 'Exodus', 9, 6, 6, 'medium', 'multiple_choice_single',
 'Tai vạ thứ năm ảnh hưởng đến đối tượng nào? (Xuất 9:6)',
 '["Cây cối","Sông ngòi","Súc vật","Nhà cửa"]',
 '[2]',
 'Xuất Ê-díp-tô Ký 9:6 — "Ngày mai, Đức Giê-hô-va làm sự đó; hết thảy súc vật của người Ê-díp-tô đều chết."',
 '["Xuất Ê-díp-tô Ký","Mười tai vạ","Tai vạ 5"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-exo-033', 'Exodus', 10, 22, 22, 'medium', 'multiple_choice_single',
 'Tai vạ thứ chín giáng trên Ai Cập là gì? (Xuất 10:22)',
 '["Mưa đá","Sự tối tăm dày đặc","Châu chấu","Mụt nhọt"]',
 '[1]',
 'Xuất Ê-díp-tô Ký 10:22 — "Môi-se giơ tay lên trời, bèn có sự tối tăm dày đặc trong ba ngày tại xứ Ê-díp-tô."',
 '["Xuất Ê-díp-tô Ký","Mười tai vạ","Tai vạ 9"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-exo-034', 'Exodus', 12, 11, 11, 'medium', 'multiple_choice_single',
 'Dân Y-sơ-ra-ên phải ăn lễ Vượt Qua trong tư thế nào? (Xuất 12:11)',
 '["Ngồi thong thả","Nằm dựa","Lưng thắt, chân mang giày, tay cầm gậy, ăn vội vàng","Quỳ gối cầu nguyện"]',
 '[2]',
 'Xuất Ê-díp-tô Ký 12:11 — "Lưng phải thắt, chân phải mang giày, tay cầm gậy, ăn vội vàng; ấy là lễ Vượt Qua của Đức Giê-hô-va."',
 '["Xuất Ê-díp-tô Ký","Lễ Vượt Qua","Cách ăn"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-exo-035', 'Exodus', 12, 40, 40, 'medium', 'multiple_choice_single',
 'Dân Y-sơ-ra-ên sống tại Ai Cập bao lâu? (Xuất 12:40)',
 '["200 năm","300 năm","400 năm","430 năm"]',
 '[3]',
 'Xuất Ê-díp-tô Ký 12:40 — "Thời kỳ dân Y-sơ-ra-ên kiều ngụ tại xứ Ê-díp-tô được bốn trăm ba mươi năm."',
 '["Xuất Ê-díp-tô Ký","Thời gian","Kiều ngụ"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-exo-036', 'Exodus', 13, 21, 21, 'medium', 'multiple_choice_single',
 'Ban ngày Đức Chúa Trời dẫn dân Y-sơ-ra-ên bằng gì? (Xuất 13:21)',
 '["Trụ lửa","Trụ mây","Ngôi sao","Cầu vồng"]',
 '[1]',
 'Xuất Ê-díp-tô Ký 13:21 — "Ban ngày, Đức Giê-hô-va đi trước dân sự, ở trong một trụ mây, để dẫn đường đi."',
 '["Xuất Ê-díp-tô Ký","Trụ mây","Dẫn đường"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-exo-037', 'Exodus', 16, 26, 26, 'medium', 'multiple_choice_single',
 'Ngày nào trong tuần không có ma-na rơi xuống? (Xuất 16:26)',
 '["Ngày thứ năm","Ngày thứ sáu","Ngày thứ bảy","Ngày thứ nhất"]',
 '[2]',
 'Xuất Ê-díp-tô Ký 16:26 — "Trong sáu ngày các ngươi sẽ đi lượm ma-na; nhưng ngày thứ bảy là ngày Sa-bát, sẽ không có đâu."',
 '["Xuất Ê-díp-tô Ký","Ma-na","Ngày Sa-bát"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-exo-038', 'Exodus', 17, 6, 6, 'medium', 'multiple_choice_single',
 'Tại Hô-rếp, Môi-se đập vào vật gì để nước chảy ra cho dân uống? (Xuất 17:6)',
 '["Mặt đất","Hòn đá","Gốc cây","Vách núi"]',
 '[1]',
 'Xuất Ê-díp-tô Ký 17:6 — "Ta sẽ đứng trước ngươi, ở nơi vầng đá tại Hô-rếp kia, ngươi hãy đập vầng đá, nước từ đó chảy ra, cho dân sự uống."',
 '["Xuất Ê-díp-tô Ký","Nước từ đá","Hô-rếp"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-exo-039', 'Exodus', 17, 12, 12, 'medium', 'multiple_choice_single',
 'Khi Môi-se mỏi tay trong trận chiến với A-ma-léc, ai đỡ tay ông? (Xuất 17:12)',
 '["Giô-suê và Ca-lép","A-rôn và Hu-rơ","A-rôn và Giô-suê","Ca-lép và Hu-rơ"]',
 '[1]',
 'Xuất Ê-díp-tô Ký 17:12 — "A-rôn và Hu-rơ nâng đỡ hai tay người, một người bên nầy, một người bên kia."',
 '["Xuất Ê-díp-tô Ký","A-ma-léc","A-rôn và Hu-rơ"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-exo-040', 'Exodus', 19, 18, 18, 'medium', 'multiple_choice_single',
 'Hiện tượng gì xảy ra khi Đức Chúa Trời ngự trên núi Si-na-i? (Xuất 19:18)',
 '["Mưa lớn","Núi bốc khói và rúng động","Trời quang đãng","Cầu vồng xuất hiện"]',
 '[1]',
 'Xuất Ê-díp-tô Ký 19:18 — "Cả núi Si-na-i đều ra khói, vì Đức Giê-hô-va ở trong lửa mà ngự xuống; khói ra khác nào khói của lò lửa lớn, và cả hòn núi đều rúng động cách kịch liệt."',
 '["Xuất Ê-díp-tô Ký","Núi Si-na-i","Sự hiện diện Chúa"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-exo-041', 'Exodus', 20, 14, 17, 'medium', 'multiple_choice_single',
 'Điều răn nào cấm tham muốn tài sản của người khác? (Xuất 20:17)',
 '["Điều răn thứ bảy","Điều răn thứ tám","Điều răn thứ chín","Điều răn thứ mười"]',
 '[3]',
 'Xuất Ê-díp-tô Ký 20:17 — "Ngươi chớ tham nhà kẻ lân cận ngươi... hay vật chi thuộc về kẻ lân cận ngươi."',
 '["Xuất Ê-díp-tô Ký","Mười Điều Răn","Tham lam"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-exo-042', 'Exodus', 25, 10, 10, 'medium', 'multiple_choice_single',
 'Hòm Giao Ước được làm bằng gỗ gì? (Xuất 25:10)',
 '["Gỗ bá hương","Gỗ si-tim","Gỗ tùng","Gỗ ô-liu"]',
 '[1]',
 'Xuất Ê-díp-tô Ký 25:10 — "Chúng hãy đóng một cái hòm bằng cây si-tim."',
 '["Xuất Ê-díp-tô Ký","Hòm Giao Ước","Đền Tạm"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-exo-043', 'Exodus', 28, 1, 1, 'medium', 'multiple_choice_single',
 'Ai được chọn làm thầy tế lễ đầu tiên của Y-sơ-ra-ên? (Xuất 28:1)',
 '["Môi-se","A-rôn","Giô-suê","Ca-lép"]',
 '[1]',
 'Xuất Ê-díp-tô Ký 28:1 — "Trong vòng dân Y-sơ-ra-ên, hãy chọn A-rôn, anh ngươi cùng các con trai người... đặng làm chức tế lễ trước mặt ta."',
 '["Xuất Ê-díp-tô Ký","A-rôn","Tế lễ"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-exo-044', 'Exodus', 31, 18, 18, 'medium', 'multiple_choice_single',
 'Hai bảng chứng được viết bằng gì? (Xuất 31:18)',
 '["Tay Môi-se","Ngón tay Đức Chúa Trời","Tay A-rôn","Thiên sứ"]',
 '[1]',
 'Xuất Ê-díp-tô Ký 31:18 — "Ban cho Môi-se hai bảng chứng, bảng đá, viết bởi ngón tay Đức Chúa Trời."',
 '["Xuất Ê-díp-tô Ký","Bảng chứng","Ngón tay Chúa"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-exo-045', 'Exodus', 32, 19, 19, 'medium', 'multiple_choice_single',
 'Khi thấy dân sự thờ bò con vàng, Môi-se đã làm gì với hai bảng đá? (Xuất 32:19)',
 '["Giấu đi","Liệng xuống chân núi bể ra","Trao cho A-rôn","Đặt trong hòm"]',
 '[1]',
 'Xuất Ê-díp-tô Ký 32:19 — "Khi đến gần trại quân, Môi-se thấy con bò con và sự nhảy múa, bèn nổi giận, liệng hai bảng chứng khỏi tay mình, bể ra nơi chân núi."',
 '["Xuất Ê-díp-tô Ký","Bảng đá","Bò con vàng"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-exo-046', 'Exodus', 34, 29, 29, 'medium', 'multiple_choice_single',
 'Điều gì xảy ra với mặt Môi-se khi ông từ núi Si-na-i xuống? (Xuất 34:29)',
 '["Mặt bị che khuất","Da mặt sáng rực","Mặt biến đổi hình dạng","Không có gì thay đổi"]',
 '[1]',
 'Xuất Ê-díp-tô Ký 34:29 — "Khi ở trên núi xuống, Môi-se không biết rằng da mặt mình sáng rực bởi vì đã hầu chuyện Đức Giê-hô-va."',
 '["Xuất Ê-díp-tô Ký","Mặt sáng rực","Núi Si-na-i"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-exo-047', 'Exodus', 40, 34, 34, 'medium', 'multiple_choice_single',
 'Khi dựng Đền Tạm xong, điều gì xảy ra? (Xuất 40:34)',
 '["Lửa từ trời rơi xuống","Trụ mây bao phủ Đền Tạm","Đất rúng động","Nước chảy ra từ Đền Tạm"]',
 '[1]',
 'Xuất Ê-díp-tô Ký 40:34 — "Áng mây bao phủ hội mạc, và sự vinh hiển của Đức Giê-hô-va đầy dẫy đền tạm."',
 '["Xuất Ê-díp-tô Ký","Đền Tạm","Vinh hiển Chúa"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

-- ═══════════════════════════════════════════════════════════════
-- HARD (13 questions)
-- ═══════════════════════════════════════════════════════════════

('bq-exo-048', 'Exodus', 1, 11, 11, 'hard', 'multiple_choice_single',
 'Dân Y-sơ-ra-ên xây hai thành nào để chứa đồ cho Pha-ra-ôn? (Xuất 1:11)',
 '["Giê-ri-cô và Ai","Phi-thôm và Ram-se","Thê-be và Mem-phi","Ôn và Hê-li-ô-bô-li"]',
 '[1]',
 'Xuất Ê-díp-tô Ký 1:11 — "Bắt làm xâu khổ, đặt đốc công lên trên, và dân Hê-bơ-rơ xây cho Pha-ra-ôn các thành Phi-thôm và Ram-se để chứa đồ."',
 '["Xuất Ê-díp-tô Ký","Nô lệ","Phi-thôm","Ram-se"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-exo-049', 'Exodus', 4, 24, 26, 'hard', 'multiple_choice_single',
 'Tại quán trọ, ai đã cắt dương bì con trai để cứu Môi-se? (Xuất 4:25)',
 '["Môi-se","A-rôn","Sê-phô-ra","Giê-trô"]',
 '[2]',
 'Xuất Ê-díp-tô Ký 4:25 — "Sê-phô-ra bèn lấy con dao bằng đá, cắt dương bì của con mình."',
 '["Xuất Ê-díp-tô Ký","Sê-phô-ra","Phép cắt bì"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-exo-050', 'Exodus', 7, 11, 11, 'hard', 'multiple_choice_single',
 'Các thuật sĩ Ai Cập cũng bắt chước phép lạ biến gậy thành rắn, nhưng điều gì xảy ra? (Xuất 7:12)',
 '["Rắn của họ lớn hơn","Gậy A-rôn nuốt gậy họ","Rắn của họ chết","Không có gì xảy ra"]',
 '[1]',
 'Xuất Ê-díp-tô Ký 7:12 — "Mỗi người liệng gậy mình xuống đất, gậy đều biến thành rắn; nhưng gậy A-rôn nuốt gậy của họ."',
 '["Xuất Ê-díp-tô Ký","Thuật sĩ","Gậy A-rôn"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-exo-051', 'Exodus', 9, 23, 24, 'hard', 'multiple_choice_single',
 'Tai vạ thứ bảy có đặc điểm gì khác thường? (Xuất 9:24)',
 '["Mưa đá lẫn lửa","Bão cát lớn","Sấm không ngừng","Gió lốc mạnh"]',
 '[0]',
 'Xuất Ê-díp-tô Ký 9:24 — "Vả, mưa đá sa xuống có lửa cháy lộn với, lớn lắm, nổi khắp xứ Ê-díp-tô."',
 '["Xuất Ê-díp-tô Ký","Mười tai vạ","Tai vạ 7"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-exo-052', 'Exodus', 12, 37, 37, 'hard', 'multiple_choice_single',
 'Khi ra khỏi Ai Cập, có bao nhiêu đàn ông đi bộ (không kể trẻ con)? (Xuất 12:37)',
 '["Chừng 200.000","Chừng 400.000","Chừng 600.000","Chừng 800.000"]',
 '[2]',
 'Xuất Ê-díp-tô Ký 12:37 — "Dân Y-sơ-ra-ên đi từ Ram-se đến Su-cốt, số không kể con nít, được chừng sáu mươi vạn người đàn ông đi bộ."',
 '["Xuất Ê-díp-tô Ký","Xuất hành","Số lượng"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-exo-053', 'Exodus', 15, 23, 25, 'hard', 'multiple_choice_single',
 'Tại Ma-ra, Môi-se bỏ vật gì vào nước đắng để nước trở nên ngọt? (Xuất 15:25)',
 '["Muối","Một khúc cây","Đá","Ma-na"]',
 '[1]',
 'Xuất Ê-díp-tô Ký 15:25 — "Đức Giê-hô-va bèn chỉ cho người một cây gỗ, người liệng xuống nước, nước bèn trở nên ngọt."',
 '["Xuất Ê-díp-tô Ký","Ma-ra","Nước đắng"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-exo-054', 'Exodus', 17, 14, 14, 'hard', 'multiple_choice_single',
 'Đức Chúa Trời phán sẽ làm gì với kỷ niệm của A-ma-léc? (Xuất 17:14)',
 '["Tha thứ cho họ","Xóa kỷ niệm họ khỏi thiên hạ","Làm họ làm nô lệ","Đuổi họ đi xa"]',
 '[1]',
 'Xuất Ê-díp-tô Ký 17:14 — "Ta sẽ xóa sạch kỷ niệm về A-ma-léc trong thiên hạ."',
 '["Xuất Ê-díp-tô Ký","A-ma-léc","Lời phán"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-exo-055', 'Exodus', 25, 18, 20, 'hard', 'multiple_choice_single',
 'Trên nắp thi ân của Hòm Giao Ước có bao nhiêu chê-ru-bin bằng vàng? (Xuất 25:18)',
 '["Một","Hai","Bốn","Sáu"]',
 '[1]',
 'Xuất Ê-díp-tô Ký 25:18 — "Cũng hãy làm hai tượng chê-ru-bin bằng vàng, đánh giát để nơi hai đầu nắp thi ân."',
 '["Xuất Ê-díp-tô Ký","Chê-ru-bin","Nắp thi ân"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-exo-056', 'Exodus', 26, 1, 1, 'hard', 'multiple_choice_single',
 'Đền Tạm được làm bằng bao nhiêu bức màn byssus? (Xuất 26:1)',
 '["Năm bức","Mười bức","Mười hai bức","Hai mươi bức"]',
 '[1]',
 'Xuất Ê-díp-tô Ký 26:1 — "Ngươi hãy dùng mười bức màn bằng vải gai mịn se, chỉ tím, đỏ điều, và đỏ sặm mà dựng đền tạm."',
 '["Xuất Ê-díp-tô Ký","Đền Tạm","Bức màn"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-exo-057', 'Exodus', 30, 13, 13, 'hard', 'multiple_choice_single',
 'Mỗi người Y-sơ-ra-ên phải nộp bao nhiêu siếc-lơ bạc làm thuế chuộc mạng? (Xuất 30:13)',
 '["Một siếc-lơ","Nửa siếc-lơ","Hai siếc-lơ","Năm siếc-lơ"]',
 '[1]',
 'Xuất Ê-díp-tô Ký 30:13 — "Mỗi người đều phải nộp nửa siếc-lơ, theo siếc-lơ của nơi thánh... nửa siếc-lơ dùng làm lễ vật dâng cho Đức Giê-hô-va."',
 '["Xuất Ê-díp-tô Ký","Thuế chuộc mạng","Siếc-lơ"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-exo-058', 'Exodus', 32, 20, 20, 'hard', 'multiple_choice_single',
 'Môi-se đã xử lý bò con vàng như thế nào? (Xuất 32:20)',
 '["Chôn xuống đất","Ném xuống biển","Đốt, nghiền thành bột, rắc trên mặt nước bắt dân uống","Đập vỡ rồi vứt đi"]',
 '[2]',
 'Xuất Ê-díp-tô Ký 32:20 — "Bèn lấy con bò con mà họ đã làm, đem đốt trong lửa, nghiền thành bột, rắc trên mặt nước, rồi bắt dân Y-sơ-ra-ên uống."',
 '["Xuất Ê-díp-tô Ký","Bò con vàng","Hình phạt"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-exo-059', 'Exodus', 33, 11, 11, 'hard', 'multiple_choice_single',
 'Đức Giê-hô-va phán cùng Môi-se như thế nào? (Xuất 33:11)',
 '["Qua giấc mơ","Qua thiên sứ","Mặt đối mặt như người ta nói chuyện với bạn hữu mình","Qua trụ mây"]',
 '[2]',
 'Xuất Ê-díp-tô Ký 33:11 — "Đức Giê-hô-va phán cùng Môi-se mặt đối mặt, như một người nói chuyện cùng bạn hữu mình."',
 '["Xuất Ê-díp-tô Ký","Mặt đối mặt","Mối quan hệ"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-exo-060', 'Exodus', 34, 6, 7, 'hard', 'multiple_choice_single',
 'Khi Đức Giê-hô-va đi ngang qua mặt Môi-se, Ngài tuyên bố Ngài là Đức Chúa Trời như thế nào? (Xuất 34:6)',
 '["Thánh khiết và công bình","Nhân từ, thương xót, chậm giận, đầy dẫy ân huệ và thành thực","Quyền năng và uy nghiêm","Khôn ngoan và tri thức"]',
 '[1]',
 'Xuất Ê-díp-tô Ký 34:6 — "Giê-hô-va! Giê-hô-va! là Đức Chúa Trời nhân từ, thương xót, chậm giận, đầy dẫy ân huệ và thành thực."',
 '["Xuất Ê-díp-tô Ký","Thuộc tính Chúa","Ân huệ"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW());
