-- Psalms (Thi Thiên) seed data: 60 questions (25 easy, 22 medium, 13 hard)
-- Source: Kinh Thánh Bản Truyền Thống 1926 (public domain)

INSERT IGNORE INTO questions (
  id, book, chapter, verse_start, verse_end,
  difficulty, type, content, options, correct_answer,
  explanation, tags, source, language, review_status, approvals_count, is_active,
  created_at, updated_at
) VALUES

-- ═══════════════════════════════════════════════════════════════
-- EASY (25 questions)
-- ═══════════════════════════════════════════════════════════════

('bq-psa-001', 'Psalms', 23, 1, 1, 'easy', 'multiple_choice_single',
 'Trong Thi Thiên 23:1, Đa-vít ví Đức Giê-hô-va như ai?',
 '["Vua","Đấng Chăn giữ","Quan xét","Thầy tế lễ"]',
 '[1]',
 'Thi Thiên 23:1 — "Đức Giê-hô-va là Đấng chăn giữ tôi; tôi sẽ chẳng thiếu thốn gì."',
 '["Thi Thiên","Thi Thiên 23","Đấng chăn giữ"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-psa-002', 'Psalms', 23, 2, 2, 'easy', 'multiple_choice_single',
 'Theo Thi Thiên 23:2, Đức Giê-hô-va dẫn tôi đến đâu?',
 '["Bên sa mạc","Trên núi cao","Đồng cỏ xanh tươi","Giữa biển cả"]',
 '[2]',
 'Thi Thiên 23:2 — "Ngài khiến tôi an nghỉ nơi đồng cỏ xanh tươi, dẫn tôi đến mé nước bình tịnh."',
 '["Thi Thiên","Thi Thiên 23","Đồng cỏ"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-psa-003', 'Psalms', 23, 4, 4, 'easy', 'multiple_choice_single',
 'Theo Thi Thiên 23:4, dù đi trong trũng bóng chết, tác giả không sợ vì lý do gì?',
 '["Vì có quân lính","Vì Chúa ở cùng tôi","Vì có vũ khí","Vì có bạn bè"]',
 '[1]',
 'Thi Thiên 23:4 — "Dầu khi tôi đi trong trũng bóng chết, tôi sẽ chẳng sợ tai họa nào; vì Chúa ở cùng tôi."',
 '["Thi Thiên","Thi Thiên 23","Bóng chết"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-psa-004', 'Psalms', 1, 1, 1, 'easy', 'multiple_choice_single',
 'Theo Thi Thiên 1:1, phước cho người nào?',
 '["Người giàu có","Người không theo mưu kế kẻ dữ","Người có quyền thế","Người sống lâu"]',
 '[1]',
 'Thi Thiên 1:1 — "Phước cho người nào chẳng theo mưu kế của kẻ dữ."',
 '["Thi Thiên","Thi Thiên 1","Phước"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-psa-005', 'Psalms', 1, 3, 3, 'easy', 'multiple_choice_single',
 'Theo Thi Thiên 1:3, người công bình được ví như gì?',
 '["Ngôi sao sáng","Cây trồng gần dòng nước","Hòn đá vững","Ngọn núi cao"]',
 '[1]',
 'Thi Thiên 1:3 — "Người ấy sẽ như cây trồng gần dòng nước, sanh bông trái theo thì tiết."',
 '["Thi Thiên","Thi Thiên 1","Cây"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-psa-006', 'Psalms', 100, 3, 3, 'easy', 'multiple_choice_single',
 'Theo Thi Thiên 100:3, chúng ta là gì trước mặt Đức Chúa Trời?',
 '["Bạn hữu Ngài","Dân sự Ngài, chiên của đồng cỏ Ngài","Con cái Ngài","Tôi tớ Ngài"]',
 '[1]',
 'Thi Thiên 100:3 — "Chính Ngài đã dựng nên chúng tôi, chúng tôi thuộc về Ngài; chúng tôi là dân sự Ngài, là bầy chiên của đồng cỏ Ngài."',
 '["Thi Thiên","Thi Thiên 100","Chiên"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-psa-007', 'Psalms', 100, 5, 5, 'easy', 'multiple_choice_single',
 'Theo Thi Thiên 100:5, sự nhân từ của Đức Giê-hô-va kéo dài bao lâu?',
 '["Một đời người","Một ngàn năm","Đời đời","Bảy mươi năm"]',
 '[2]',
 'Thi Thiên 100:5 — "Vì Đức Giê-hô-va là thiện; sự nhân từ Ngài còn đến đời đời, và sự thành tín Ngài còn đến muôn đời."',
 '["Thi Thiên","Thi Thiên 100","Nhân từ"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-psa-008', 'Psalms', 46, 1, 1, 'easy', 'multiple_choice_single',
 'Theo Thi Thiên 46:1, Đức Chúa Trời là gì cho chúng ta?',
 '["Vua và Chúa","Nơi nương náu và sức lực","Thầy dạy dỗ","Quan xét công bình"]',
 '[1]',
 'Thi Thiên 46:1 — "Đức Chúa Trời là nơi nương náu và sức lực của chúng tôi, Ngài sẵn giúp đỡ trong cơn gian truân."',
 '["Thi Thiên","Thi Thiên 46","Nương náu"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-psa-009', 'Psalms', 46, 10, 10, 'easy', 'multiple_choice_single',
 'Thi Thiên 46:10 kêu gọi chúng ta làm gì?',
 '["Hãy vui mừng","Hãy yên lặng và biết rằng ta là Đức Chúa Trời","Hãy ca ngợi","Hãy cầu nguyện"]',
 '[1]',
 'Thi Thiên 46:10 — "Hãy yên lặng và biết rằng ta là Đức Chúa Trời."',
 '["Thi Thiên","Thi Thiên 46","Yên lặng"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-psa-010', 'Psalms', 121, 1, 2, 'easy', 'multiple_choice_single',
 'Theo Thi Thiên 121:2, sự tiếp trợ chúng ta đến từ đâu?',
 '["Từ loài người","Từ Đức Giê-hô-va, Đấng dựng nên trời đất","Từ thiên sứ","Từ thiên nhiên"]',
 '[1]',
 'Thi Thiên 121:2 — "Sự tiếp trợ tôi đến từ Đức Giê-hô-va, là Đấng đã dựng nên trời và đất."',
 '["Thi Thiên","Thi Thiên 121","Tiếp trợ"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-psa-011', 'Psalms', 121, 4, 4, 'easy', 'multiple_choice_single',
 'Theo Thi Thiên 121:4, Đấng gìn giữ Y-sơ-ra-ên có bao giờ ngủ không?',
 '["Ngủ ban đêm","Chẳng hề ngủ, chẳng hề buồn ngủ","Ngủ vào mùa đông","Thỉnh thoảng ngủ"]',
 '[1]',
 'Thi Thiên 121:4 — "Đấng gìn giữ Y-sơ-ra-ên chẳng hề nhắm mắt, chẳng hề ngủ."',
 '["Thi Thiên","Thi Thiên 121","Gìn giữ"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-psa-012', 'Psalms', 150, 6, 6, 'easy', 'multiple_choice_single',
 'Theo Thi Thiên 150:6, ai nên ngợi khen Đức Giê-hô-va?',
 '["Chỉ người Lê-vi","Chỉ vua chúa","Phàm vật chi thở","Chỉ thiên sứ"]',
 '[2]',
 'Thi Thiên 150:6 — "Phàm vật chi thở, hãy ngợi khen Đức Giê-hô-va! Ha-lê-lu-gia!"',
 '["Thi Thiên","Thi Thiên 150","Ngợi khen"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-psa-013', 'Psalms', 27, 1, 1, 'easy', 'multiple_choice_single',
 'Theo Thi Thiên 27:1, Đức Giê-hô-va là gì cho Đa-vít?',
 '["Vua và Chúa","Ánh sáng và sự cứu rỗi","Thầy dạy dỗ","Bạn hữu thân thiết"]',
 '[1]',
 'Thi Thiên 27:1 — "Đức Giê-hô-va là ánh sáng và là sự cứu rỗi tôi: tôi sẽ sợ ai?"',
 '["Thi Thiên","Thi Thiên 27","Ánh sáng"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-psa-014', 'Psalms', 34, 8, 8, 'easy', 'multiple_choice_single',
 'Theo Thi Thiên 34:8, tác giả mời gọi chúng ta làm gì?',
 '["Hãy sợ hãi Chúa","Hãy nếm thử xem Đức Giê-hô-va tốt lành dường bao","Hãy dâng của lễ","Hãy giữ ngày Sa-bát"]',
 '[1]',
 'Thi Thiên 34:8 — "Khá nếm thử xem Đức Giê-hô-va tốt lành dường bao! Phước cho người nào nương náu mình nơi Ngài."',
 '["Thi Thiên","Thi Thiên 34","Nếm thử"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-psa-015', 'Psalms', 51, 1, 1, 'easy', 'multiple_choice_single',
 'Trong Thi Thiên 51, Đa-vít cầu xin Đức Chúa Trời điều gì?',
 '["Ban cho sự giàu có","Thương xót và xóa các vi phạm","Ban cho quyền lực","Trừng phạt kẻ thù"]',
 '[1]',
 'Thi Thiên 51:1 — "Đức Chúa Trời ôi! xin hãy thương xót tôi tùy lòng nhân từ của Chúa; xin hãy xóa các sự vi phạm tôi theo sự thương xót rất lớn của Chúa."',
 '["Thi Thiên","Thi Thiên 51","Ăn năn"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-psa-016', 'Psalms', 103, 1, 1, 'easy', 'multiple_choice_single',
 'Thi Thiên 103:1 mở đầu bằng lời kêu gọi nào?',
 '["Hãy sợ hãi Chúa","Hỡi linh hồn ta, khá ngợi khen Đức Giê-hô-va","Hãy vui mừng","Hãy khóc lóc ăn năn"]',
 '[1]',
 'Thi Thiên 103:1 — "Hỡi linh hồn ta, khá ngợi khen Đức Giê-hô-va! Mọi điều gì ở trong ta hãy ca tụng danh thánh của Ngài."',
 '["Thi Thiên","Thi Thiên 103","Ngợi khen"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-psa-017', 'Psalms', 103, 12, 12, 'easy', 'multiple_choice_single',
 'Theo Thi Thiên 103:12, Đức Chúa Trời đã đem tội lỗi chúng ta xa bao nhiêu?',
 '["Xa như biển sâu","Xa như phương đông cách phương tây","Xa như trời cách đất","Xa như ngày cách đêm"]',
 '[1]',
 'Thi Thiên 103:12 — "Phương đông xa cách phương tây bao nhiêu, thì Ngài đã đem sự vi phạm chúng tôi khỏi chúng tôi xa bấy nhiêu."',
 '["Thi Thiên","Thi Thiên 103","Tha thứ"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-psa-018', 'Psalms', 91, 1, 1, 'easy', 'multiple_choice_single',
 'Theo Thi Thiên 91:1, người nào ở nơi kín đáo của Đấng Chí Cao?',
 '["Người giàu có","Người ở nơi kín đáo","Người có quân đội","Người trẻ tuổi"]',
 '[1]',
 'Thi Thiên 91:1 — "Người nào ở nơi kín đáo của Đấng Chí Cao, sẽ được hằng ở dưới bóng của Đấng Toàn Năng."',
 '["Thi Thiên","Thi Thiên 91","Nơi kín đáo"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-psa-019', 'Psalms', 19, 1, 1, 'easy', 'multiple_choice_single',
 'Theo Thi Thiên 19:1, các từng trời rao truyền điều gì?',
 '["Sự phán xét","Sự vinh hiển của Đức Chúa Trời","Sự phạt","Ngày tận thế"]',
 '[1]',
 'Thi Thiên 19:1 — "Các từng trời rao truyền sự vinh hiển của Đức Chúa Trời, bầu trời giải tỏ công việc tay Ngài làm."',
 '["Thi Thiên","Thi Thiên 19","Vinh hiển"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-psa-020', 'Psalms', 8, 3, 4, 'easy', 'multiple_choice_single',
 'Trong Thi Thiên 8:4, tác giả hỏi Chúa về điều gì?',
 '["Loài người là gì mà Chúa nhớ đến","Tại sao có sự đau khổ","Khi nào Chúa trở lại","Ai sẽ cai trị"]',
 '[0]',
 'Thi Thiên 8:4 — "Loài người là gì mà Chúa nhớ đến? Con loài người là chi mà Chúa thăm viếng nó?"',
 '["Thi Thiên","Thi Thiên 8","Loài người"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-psa-021', 'Psalms', 37, 4, 4, 'easy', 'multiple_choice_single',
 'Theo Thi Thiên 37:4, nếu chúng ta lấy Đức Giê-hô-va làm vui thích, Ngài sẽ làm gì?',
 '["Ban cho sự giàu có","Ban cho điều lòng mình ao ước","Ban cho quyền lực","Ban cho sức khỏe"]',
 '[1]',
 'Thi Thiên 37:4 — "Cũng hãy khoái lạc nơi Đức Giê-hô-va, thì Ngài sẽ ban cho ngươi điều lòng mình ao ước."',
 '["Thi Thiên","Thi Thiên 37","Khoái lạc"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-psa-022', 'Psalms', 139, 14, 14, 'easy', 'multiple_choice_single',
 'Theo Thi Thiên 139:14, tác giả ngợi khen Chúa vì lý do gì?',
 '["Vì Chúa giàu có","Vì được dựng nên cách đáng sợ lạ lùng","Vì được ban cho vương quốc","Vì có nhiều con cái"]',
 '[1]',
 'Thi Thiên 139:14 — "Tôi cảm tạ Chúa, vì tôi được dựng nên cách đáng sợ lạ lùng. Công việc Chúa thật lạ lùng."',
 '["Thi Thiên","Thi Thiên 139","Dựng nên"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-psa-023', 'Psalms', 145, 3, 3, 'easy', 'multiple_choice_single',
 'Theo Thi Thiên 145:3, sự cao cả của Đức Giê-hô-va thế nào?',
 '["Có giới hạn","Không thể dò xét được","Chỉ ở trên trời","Tùy thời tiết"]',
 '[1]',
 'Thi Thiên 145:3 — "Đức Giê-hô-va là lớn và đáng ngợi khen thay; sự cao cả Ngài không thể dò xét được."',
 '["Thi Thiên","Thi Thiên 145","Cao cả"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-psa-024', 'Psalms', 91, 11, 11, 'easy', 'multiple_choice_single',
 'Theo Thi Thiên 91:11, Đức Chúa Trời truyền lệnh cho ai gìn giữ người tin kính?',
 '["Các tiên tri","Các thiên sứ","Các thầy tế lễ","Các vua"]',
 '[1]',
 'Thi Thiên 91:11 — "Vì Ngài sẽ ban lịnh cho thiên sứ Ngài gìn giữ ngươi trong các đường lối ngươi."',
 '["Thi Thiên","Thi Thiên 91","Thiên sứ"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-psa-025', 'Psalms', 100, 1, 2, 'easy', 'multiple_choice_single',
 'Thi Thiên 100:1 kêu gọi ai hãy cất tiếng reo mừng cho Đức Giê-hô-va?',
 '["Chỉ dân Y-sơ-ra-ên","Chỉ thầy tế lễ","Khắp thế gian","Chỉ các vua"]',
 '[2]',
 'Thi Thiên 100:1 — "Hỡi cả trái đất, hãy cất tiếng reo mừng cho Đức Giê-hô-va!"',
 '["Thi Thiên","Thi Thiên 100","Reo mừng"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

-- ═══════════════════════════════════════════════════════════════
-- MEDIUM (22 questions)
-- ═══════════════════════════════════════════════════════════════

('bq-psa-026', 'Psalms', 22, 1, 1, 'medium', 'multiple_choice_single',
 'Thi Thiên 22:1 bắt đầu với lời than phiền nào mà Chúa Giê-su cũng dùng trên thập tự giá?',
 '["Lạy Chúa, xin cứu con","Đức Chúa Trời tôi ơi! sao Ngài lìa bỏ tôi?","Xin tha tội cho họ","Mọi sự đã xong"]',
 '[1]',
 'Thi Thiên 22:1 — "Đức Chúa Trời tôi ơi! Đức Chúa Trời tôi ơi! sao Ngài lìa bỏ tôi?"',
 '["Thi Thiên","Thi Thiên 22","Tiên tri"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-psa-027', 'Psalms', 22, 16, 18, 'medium', 'multiple_choice_single',
 'Thi Thiên 22:16-18 tiên tri về điều gì liên quan đến Đấng Mê-si?',
 '["Sự phục sinh","Họ đâm tay và chân tôi, bắt thăm áo tôi","Sự thăng thiên","Sự tái lâm"]',
 '[1]',
 'Thi Thiên 22:16,18 — "Chúng nó đã xoi lủng tay và chân tôi... Chúng nó chia nhau áo xống tôi, bắt thăm về áo dài tôi."',
 '["Thi Thiên","Thi Thiên 22","Tiên tri","Đóng đinh"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-psa-028', 'Psalms', 51, 10, 10, 'medium', 'multiple_choice_single',
 'Đa-vít cầu xin Đức Chúa Trời dựng nên điều gì trong lòng ông? (Thi 51:10)',
 '["Sự khôn ngoan","Một lòng trong sạch","Sự can đảm","Một vương quốc"]',
 '[1]',
 'Thi Thiên 51:10 — "Đức Chúa Trời ôi! xin hãy dựng nên trong tôi một lòng trong sạch, và làm cho mới lại trong tôi một thần linh ngay thẳng."',
 '["Thi Thiên","Thi Thiên 51","Lòng trong sạch"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-psa-029', 'Psalms', 51, 17, 17, 'medium', 'multiple_choice_single',
 'Theo Thi Thiên 51:17, của lễ nào Đức Chúa Trời không khinh dể?',
 '["Của lễ thiêu lớn","Tấm lòng đau thương thống hối","Nhiều vàng bạc","Mười phần trăm"]',
 '[1]',
 'Thi Thiên 51:17 — "Của lễ đẹp lòng Đức Chúa Trời, ấy là tâm thần đau thương: Đức Chúa Trời ôi! lòng đau thương thống hối Chúa không khinh dể đâu."',
 '["Thi Thiên","Thi Thiên 51","Ăn năn"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-psa-030', 'Psalms', 90, 10, 10, 'medium', 'multiple_choice_single',
 'Theo Thi Thiên 90:10, tuổi thọ con người thường là bao nhiêu?',
 '["Năm mươi năm","Sáu mươi năm","Bảy mươi năm","Một trăm năm"]',
 '[2]',
 'Thi Thiên 90:10 — "Tuổi tác của chúng tôi đến được bảy mươi, còn nếu mạnh khỏe thì đến tám mươi."',
 '["Thi Thiên","Thi Thiên 90","Tuổi thọ"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-psa-031', 'Psalms', 90, 12, 12, 'medium', 'multiple_choice_single',
 'Môi-se cầu xin Đức Chúa Trời dạy điều gì trong Thi Thiên 90:12?',
 '["Dạy chúng tôi cầu nguyện","Dạy chúng tôi biết đếm các ngày","Dạy chúng tôi yêu thương","Dạy chúng tôi chiến đấu"]',
 '[1]',
 'Thi Thiên 90:12 — "Cầu xin Chúa dạy chúng tôi biết đếm các ngày chúng tôi, hầu cho chúng tôi được lòng khôn ngoan."',
 '["Thi Thiên","Thi Thiên 90","Khôn ngoan"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-psa-032', 'Psalms', 119, 105, 105, 'medium', 'multiple_choice_single',
 'Theo Thi Thiên 119:105, Lời Chúa được ví như gì?',
 '["Thanh gươm","Ngọn đèn cho chân tôi, ánh sáng cho đường lối tôi","Lá chắn","Tấm khiên"]',
 '[1]',
 'Thi Thiên 119:105 — "Lời Chúa là ngọn đèn cho chân tôi, ánh sáng cho đường lối tôi."',
 '["Thi Thiên","Thi Thiên 119","Lời Chúa"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-psa-033', 'Psalms', 119, 11, 11, 'medium', 'multiple_choice_single',
 'Theo Thi Thiên 119:11, tác giả giấu Lời Chúa ở đâu để không phạm tội?',
 '["Trên bàn","Trong hòm","Trong lòng","Trên tường"]',
 '[2]',
 'Thi Thiên 119:11 — "Tôi đã giấu lời Chúa trong lòng tôi, để tôi không phạm tội cùng Chúa."',
 '["Thi Thiên","Thi Thiên 119","Lời Chúa"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-psa-034', 'Psalms', 110, 1, 1, 'medium', 'multiple_choice_single',
 'Trong Thi Thiên 110:1, Đức Giê-hô-va phán cùng Chúa tôi (Đấng Mê-si) điều gì?',
 '["Hãy đi chiến đấu","Hãy ngồi bên hữu ta","Hãy đứng lên","Hãy xây đền thờ"]',
 '[1]',
 'Thi Thiên 110:1 — "Đức Giê-hô-va phán cùng Chúa tôi rằng: Hãy ngồi bên hữu ta, cho đến chừng nào ta đặt kẻ thù nghịch ngươi làm bệ chân cho ngươi."',
 '["Thi Thiên","Thi Thiên 110","Đấng Mê-si"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-psa-035', 'Psalms', 110, 4, 4, 'medium', 'multiple_choice_single',
 'Theo Thi Thiên 110:4, Đấng Mê-si là thầy tế lễ theo ban nào?',
 '["Ban A-rôn","Ban Mên-chi-xê-đéc","Ban Lê-vi","Ban Sa-đốc"]',
 '[1]',
 'Thi Thiên 110:4 — "Đức Giê-hô-va đã thề, không hề đổi ý, rằng: Ngươi là thầy tế lễ đời đời, tùy theo ban Mên-chi-xê-đéc."',
 '["Thi Thiên","Thi Thiên 110","Mên-chi-xê-đéc"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-psa-036', 'Psalms', 139, 7, 8, 'medium', 'multiple_choice_single',
 'Theo Thi Thiên 139:7-8, chúng ta có thể trốn khỏi Thần Chúa không?',
 '["Có thể nếu đi xa","Không thể, dù lên trời hay xuống âm phủ","Chỉ khi ngủ","Chỉ ở nơi thánh"]',
 '[1]',
 'Thi Thiên 139:7-8 — "Tôi sẽ đi đâu xa Thần Chúa? Tôi sẽ trốn đâu khỏi mặt Chúa? Nếu tôi lên trời, Chúa ở tại đó; nếu tôi nằm dưới âm phủ, kìa, Chúa cũng có ở đó."',
 '["Thi Thiên","Thi Thiên 139","Sự hiện diện"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-psa-037', 'Psalms', 139, 23, 24, 'medium', 'multiple_choice_single',
 'Đa-vít cầu xin Đức Chúa Trời dò xét điều gì trong Thi Thiên 139:23?',
 '["Dò xét kẻ thù","Dò xét lòng tôi và biết ý tưởng tôi","Dò xét đất nước","Dò xét lịch sử"]',
 '[1]',
 'Thi Thiên 139:23 — "Đức Chúa Trời ôi! xin hãy dò xét tôi, và biết lòng tôi; hãy thử thách tôi, và biết tư tưởng tôi."',
 '["Thi Thiên","Thi Thiên 139","Dò xét"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-psa-038', 'Psalms', 27, 4, 4, 'medium', 'multiple_choice_single',
 'Đa-vít xin Đức Giê-hô-va một điều gì trong Thi Thiên 27:4?',
 '["Một vương quốc lớn","Ở trong nhà Đức Giê-hô-va trọn đời","Nhiều con cái","Đánh bại kẻ thù"]',
 '[1]',
 'Thi Thiên 27:4 — "Tôi đã xin Đức Giê-hô-va một điều, và sẽ tìm kiếm điều ấy: ấy là tôi muốn trọn đời ở trong nhà Đức Giê-hô-va."',
 '["Thi Thiên","Thi Thiên 27","Ở trong nhà Chúa"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-psa-039', 'Psalms', 34, 18, 18, 'medium', 'multiple_choice_single',
 'Theo Thi Thiên 34:18, Đức Giê-hô-va ở gần ai?',
 '["Người giàu có","Người có quyền","Người có lòng đau thương","Người khôn ngoan"]',
 '[2]',
 'Thi Thiên 34:18 — "Đức Giê-hô-va ở gần những người có lòng đau thương, và cứu kẻ nào có tâm hồn thống hối."',
 '["Thi Thiên","Thi Thiên 34","Gần Chúa"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-psa-040', 'Psalms', 37, 25, 25, 'medium', 'multiple_choice_single',
 'Theo Thi Thiên 37:25, Đa-vít làm chứng rằng ông chưa bao giờ thấy điều gì?',
 '["Người ác hưởng phước","Người công bình bị bỏ, con cháu đi ăn mày","Mưa thiếu nước","Người giàu bị đau"]',
 '[1]',
 'Thi Thiên 37:25 — "Trước tôi trẻ, rày đã già, nhưng chưa hề thấy người công bình bị bỏ, hay là dòng dõi người đi ăn mày."',
 '["Thi Thiên","Thi Thiên 37","Công bình"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-psa-041', 'Psalms', 19, 7, 7, 'medium', 'multiple_choice_single',
 'Theo Thi Thiên 19:7, luật pháp của Đức Giê-hô-va có tác dụng gì?',
 '["Trừng phạt kẻ ác","Bổ linh hồn lại","Mang lại sự giàu có","Cho biết tương lai"]',
 '[1]',
 'Thi Thiên 19:7 — "Luật pháp của Đức Giê-hô-va là trọn vẹn, bổ linh hồn lại."',
 '["Thi Thiên","Thi Thiên 19","Luật pháp"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-psa-042', 'Psalms', 103, 3, 4, 'medium', 'multiple_choice_single',
 'Theo Thi Thiên 103:3, Đức Giê-hô-va tha thứ điều gì và chữa lành điều gì?',
 '["Tha tội lỗi và chữa lành thế giới","Tha hết tội ác và chữa lành các bịnh","Tha kẻ thù và chữa lành đất nước","Tha sự nghèo và chữa lành vết thương"]',
 '[1]',
 'Thi Thiên 103:3 — "Ấy là Ngài tha thứ các tội ác ngươi, chữa lành mọi bịnh tật ngươi."',
 '["Thi Thiên","Thi Thiên 103","Tha thứ","Chữa lành"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-psa-043', 'Psalms', 8, 5, 6, 'medium', 'multiple_choice_single',
 'Theo Thi Thiên 8:5, Đức Chúa Trời dựng loài người kém hơn ai một chút?',
 '["Kém hơn thiên sứ một chút","Kém hơn các ngôi sao","Kém hơn loài vật","Kém hơn núi non"]',
 '[0]',
 'Thi Thiên 8:5 — "Chúa làm người kém Đức Chúa Trời một chút, đội cho người sự vinh hiển và sang trọng."',
 '["Thi Thiên","Thi Thiên 8","Loài người"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-psa-044', 'Psalms', 91, 4, 4, 'medium', 'multiple_choice_single',
 'Theo Thi Thiên 91:4, Đức Chúa Trời che chở chúng ta bằng gì?',
 '["Lá chắn sắt","Lông và cánh Ngài","Đám mây lớn","Tường lửa"]',
 '[1]',
 'Thi Thiên 91:4 — "Ngài sẽ lấy lông Ngài mà che chở ngươi, và dưới cánh Ngài, ngươi sẽ được nương náu mình."',
 '["Thi Thiên","Thi Thiên 91","Che chở"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-psa-045', 'Psalms', 23, 5, 5, 'medium', 'multiple_choice_single',
 'Theo Thi Thiên 23:5, Đức Chúa Trời dọn bàn cho Đa-vít trước mặt ai?',
 '["Trước mặt bạn hữu","Trước mặt kẻ thù nghịch","Trước mặt gia đình","Trước mặt thiên sứ"]',
 '[1]',
 'Thi Thiên 23:5 — "Chúa dọn bàn cho tôi trước mặt kẻ thù nghịch tôi; Chúa xức dầu cho đầu tôi, chén tôi đầy tràn."',
 '["Thi Thiên","Thi Thiên 23","Bàn tiệc"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-psa-046', 'Psalms', 145, 18, 18, 'medium', 'multiple_choice_single',
 'Theo Thi Thiên 145:18, Đức Giê-hô-va ở gần những ai?',
 '["Mọi người cầu khẩn Ngài trong lẽ thật","Người giàu có","Người thông minh","Người có chức vụ"]',
 '[0]',
 'Thi Thiên 145:18 — "Đức Giê-hô-va ở gần mọi người cầu khẩn Ngài, tức là mọi người có lòng thành thực cầu khẩn Ngài."',
 '["Thi Thiên","Thi Thiên 145","Gần Chúa"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-psa-047', 'Psalms', 119, 9, 9, 'medium', 'multiple_choice_single',
 'Theo Thi Thiên 119:9, người trẻ tuổi giữ mình trong sạch bằng cách nào?',
 '["Ở yên một mình","Theo lời Chúa","Làm nhiều việc lành","Kiêng ăn"]',
 '[1]',
 'Thi Thiên 119:9 — "Người trẻ tuổi phải làm sao cho đường lối mình được trong sạch? Phải cẩn thận theo lời Chúa."',
 '["Thi Thiên","Thi Thiên 119","Người trẻ"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

-- ═══════════════════════════════════════════════════════════════
-- HARD (13 questions)
-- ═══════════════════════════════════════════════════════════════

('bq-psa-048', 'Psalms', 22, 6, 6, 'hard', 'multiple_choice_single',
 'Trong Thi Thiên 22:6, tác giả tự ví mình như con gì?',
 '["Con chiên","Con sâu","Con chim","Con bò"]',
 '[1]',
 'Thi Thiên 22:6 — "Nhưng tôi là một con sâu, chẳng phải người đâu; tôi bị loài người sỉ nhục, và bị dân chúng khinh dể."',
 '["Thi Thiên","Thi Thiên 22","Con sâu"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-psa-049', 'Psalms', 90, 1, 2, 'hard', 'multiple_choice_single',
 'Thi Thiên 90 được ghi là bài cầu nguyện của ai?',
 '["Đa-vít","Sa-lô-môn","A-sáp","Môi-se"]',
 '[3]',
 'Thi Thiên 90:1 (tiêu đề) — "Bài cầu nguyện của Môi-se, người của Đức Chúa Trời."',
 '["Thi Thiên","Thi Thiên 90","Môi-se"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-psa-050', 'Psalms', 90, 4, 4, 'hard', 'multiple_choice_single',
 'Theo Thi Thiên 90:4, một ngàn năm trong mắt Chúa giống như bao lâu?',
 '["Một giờ","Ngày hôm qua đã qua rồi","Một phút","Nháy mắt"]',
 '[1]',
 'Thi Thiên 90:4 — "Vì một ngàn năm trước mắt Chúa khác nào ngày hôm qua đã qua rồi, giống như một canh của đêm."',
 '["Thi Thiên","Thi Thiên 90","Thời gian"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-psa-051', 'Psalms', 119, 89, 89, 'hard', 'multiple_choice_single',
 'Theo Thi Thiên 119:89, Lời Đức Giê-hô-va được vững lập ở đâu?',
 '["Trên đất","Trên trời đời đời","Trong biển","Trên núi"]',
 '[1]',
 'Thi Thiên 119:89 — "Hỡi Đức Giê-hô-va, lời Ngài được vững lập đời đời trên trời."',
 '["Thi Thiên","Thi Thiên 119","Lời Chúa vững bền"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-psa-052', 'Psalms', 119, 164, 164, 'hard', 'multiple_choice_single',
 'Theo Thi Thiên 119:164, tác giả ngợi khen Đức Chúa Trời mấy lần trong ngày?',
 '["Ba lần","Năm lần","Bảy lần","Mười lần"]',
 '[2]',
 'Thi Thiên 119:164 — "Mỗi ngày tôi ngợi khen Chúa bảy lần, vì cớ các mạng lịnh công bình của Chúa."',
 '["Thi Thiên","Thi Thiên 119","Ngợi khen"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-psa-053', 'Psalms', 119, 176, 176, 'hard', 'multiple_choice_single',
 'Thi Thiên 119 có bao nhiêu câu, là chương dài nhất trong Kinh Thánh?',
 '["150 câu","166 câu","176 câu","188 câu"]',
 '[2]',
 'Thi Thiên 119:176 — Thi Thiên 119 có 176 câu, là chương dài nhất trong toàn bộ Kinh Thánh.',
 '["Thi Thiên","Thi Thiên 119","Chương dài nhất"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-psa-054', 'Psalms', 34, 1, 1, 'hard', 'multiple_choice_single',
 'Thi Thiên 34 được Đa-vít viết trong hoàn cảnh nào?',
 '["Khi lên ngôi vua","Khi giả điên trước A-bi-mê-léc","Khi chiến thắng Gô-li-át","Khi xây đền thờ"]',
 '[1]',
 'Thi Thiên 34 (tiêu đề) — "Thi thiên của Đa-vít, khi người giả dại trước mặt A-bi-mê-léc; vua đuổi người đi, và người đã đi."',
 '["Thi Thiên","Thi Thiên 34","Hoàn cảnh"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-psa-055', 'Psalms', 51, 4, 4, 'hard', 'multiple_choice_single',
 'Đa-vít thú nhận trong Thi Thiên 51:4 rằng ông phạm tội cùng ai?',
 '["U-ri","Bát-sê-ba","Chỉ cùng Chúa mà thôi","Dân Y-sơ-ra-ên"]',
 '[2]',
 'Thi Thiên 51:4 — "Tôi đã phạm tội cùng Chúa, chỉ cùng một mình Chúa thôi, và làm điều ác trước mặt Chúa."',
 '["Thi Thiên","Thi Thiên 51","Xưng tội"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-psa-056', 'Psalms', 137, 1, 1, 'hard', 'multiple_choice_single',
 'Trong Thi Thiên 137:1, dân Y-sơ-ra-ên ngồi bên sông nào mà khóc?',
 '["Sông Giô-đanh","Các sông Ba-by-lôn","Sông Ni-lơ","Sông Ơ-phơ-rát"]',
 '[1]',
 'Thi Thiên 137:1 — "Chúng tôi ngồi bên các sông Ba-by-lôn, và khóc khi nhớ lại Si-ôn."',
 '["Thi Thiên","Thi Thiên 137","Phu tù"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-psa-057', 'Psalms', 19, 10, 10, 'hard', 'multiple_choice_single',
 'Theo Thi Thiên 19:10, luật pháp Chúa quý hơn vật gì?',
 '["Bạc","Ngọc trai","Vàng, thật vàng ròng","Đá quý"]',
 '[2]',
 'Thi Thiên 19:10 — "Lời ấy quý hơn vàng, thật vàng ròng; ngọt hơn mật, hơn nước ngọt trong tàng ong."',
 '["Thi Thiên","Thi Thiên 19","Lời Chúa quý"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-psa-058', 'Psalms', 46, 4, 4, 'hard', 'multiple_choice_single',
 'Theo Thi Thiên 46:4, dòng sông nào làm vui cho thành Đức Chúa Trời?',
 '["Sông Giô-đanh","Một dòng sông có nhiều ngành","Sông Ơ-phơ-rát","Sông Ni-lơ"]',
 '[1]',
 'Thi Thiên 46:4 — "Một dòng sông, các ngành nó làm vui thành Đức Chúa Trời, là nơi thánh về chỗ ở của Đấng Chí Cao."',
 '["Thi Thiên","Thi Thiên 46","Dòng sông"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-psa-059', 'Psalms', 103, 15, 16, 'hard', 'multiple_choice_single',
 'Theo Thi Thiên 103:15-16, đời con người được ví như gì?',
 '["Hạt cát bên biển","Cỏ đồng nội, hoa nở rồi héo","Sóng biển","Đám mây bay"]',
 '[1]',
 'Thi Thiên 103:15-16 — "Đời loài người như cỏ, họ sanh ra như bông hoa nơi đồng; gió thổi trên bông hoa, kìa nó chẳng còn."',
 '["Thi Thiên","Thi Thiên 103","Đời tạm"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-psa-060', 'Psalms', 150, 3, 5, 'hard', 'multiple_choice_single',
 'Thi Thiên 150 kể bao nhiêu loại nhạc cụ để ngợi khen Đức Giê-hô-va?',
 '["Ba loại","Năm loại","Bảy loại","Chín loại"]',
 '[2]',
 'Thi Thiên 150:3-5 — Bảy loại: kèn, đàn sắt, đàn cầm, trống cơm, nhảy múa, nhạc khí bằng dây, ống sáo, chập chỏa kêu vang.',
 '["Thi Thiên","Thi Thiên 150","Nhạc cụ"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW());
