-- Matthew (Ma-thi-ơ) seed data: 80 questions (35 easy, 28 medium, 17 hard)
-- Source: Kinh Thanh Ban Truyen Thong 1926 (public domain)

INSERT IGNORE INTO questions (
  id, book, chapter, verse_start, verse_end,
  difficulty, type, content, options, correct_answer,
  explanation, tags, source, language, review_status, approvals_count, is_active,
  created_at, updated_at
) VALUES

-- ═══════════════════════════════════════════════════════════════
-- EASY (35 questions)
-- ═══════════════════════════════════════════════════════════════

-- Birth & Early Life (ch 1-2)
('bq-mat-001', 'Matthew', 1, 21, 21, 'easy', 'multiple_choice_single',
 'Thiên sứ bảo Giô-sép đặt tên con trẻ là gì? (Ma-thi-ơ 1:21)',
 '["Giăng","Đa-vít","Jêsus","Ê-li"]',
 '[2]',
 'Ma-thi-ơ 1:21 — "Người sẽ sanh một trai, ngươi khá đặt tên là Jêsus, vì chính con trai ấy sẽ cứu dân mình ra khỏi tội."',
 '["Ma-thi-ơ","Giáng sinh","Chúa Jêsus"]', 'BTT 1926', 'vi','ACTIVE', 0, 1, NOW(), NOW()),

('bq-mat-002', 'Matthew', 2, 1, 1, 'easy', 'multiple_choice_single',
 'Chúa Jêsus được sanh ra tại thành nào? (Ma-thi-ơ 2:1)',
 '["Na-xa-rét","Giê-ru-sa-lem","Ca-bê-na-um","Bết-lê-hem"]',
 '[3]',
 'Ma-thi-ơ 2:1 — "Khi Đức Chúa Jêsus đã sanh tại thành Bết-lê-hem, xứ Giu-đê, đời vua Hê-rốt."',
 '["Ma-thi-ơ","Giáng sinh","Bết-lê-hem"]', 'BTT 1926', 'vi','ACTIVE', 0, 1, NOW(), NOW()),

('bq-mat-003', 'Matthew', 2, 11, 11, 'easy', 'multiple_choice_single',
 'Các thầy bác sĩ từ phương Đông dâng cho con trẻ mấy thứ lễ vật? (Ma-thi-ơ 2:11)',
 '["Hai thứ","Bốn thứ","Ba thứ","Năm thứ"]',
 '[2]',
 'Ma-thi-ơ 2:11 — "Bèn sấp mình xuống mà thờ lạy Ngài, rồi bày của báu ra, dâng cho Ngài những lễ vật: vàng, nhũ hương, và một dược."',
 '["Ma-thi-ơ","Giáng sinh","Thầy bác sĩ"]', 'BTT 1926', 'vi','ACTIVE', 0, 1, NOW(), NOW()),

('bq-mat-004', 'Matthew', 2, 13, 14, 'easy', 'multiple_choice_single',
 'Giô-sép đem con trẻ và Ma-ri trốn sang xứ nào? (Ma-thi-ơ 2:13-14)',
 '["Ba-by-lôn","Ê-díp-tô","Sy-ri","Giu-đê"]',
 '[1]',
 'Ma-thi-ơ 2:13-14 — "Hãy đứng dậy, đem con trẻ và mẹ Ngài trốn qua xứ Ê-díp-tô."',
 '["Ma-thi-ơ","Giáng sinh","Ê-díp-tô"]', 'BTT 1926', 'vi','ACTIVE', 0, 1, NOW(), NOW()),

-- Baptism & Temptation (ch 3-4)
('bq-mat-005', 'Matthew', 3, 13, 16, 'easy', 'multiple_choice_single',
 'Ai đã làm phép báp-tem cho Chúa Jêsus? (Ma-thi-ơ 3:13)',
 '["Phi-e-rơ","Giăng Báp-tít","An-drê","Gia-cơ"]',
 '[1]',
 'Ma-thi-ơ 3:13 — "Khi ấy, Đức Chúa Jêsus từ xứ Ga-li-lê đến cùng Giăng tại sông Giô-đanh, đặng chịu người làm phép báp-tem."',
 '["Ma-thi-ơ","Báp-tem","Giăng Báp-tít"]', 'BTT 1926', 'vi','ACTIVE', 0, 1, NOW(), NOW()),

('bq-mat-006', 'Matthew', 4, 1, 2, 'easy', 'multiple_choice_single',
 'Chúa Jêsus kiêng ăn trong bao nhiêu ngày đêm trước khi bị cám dỗ? (Ma-thi-ơ 4:2)',
 '["Bảy ngày đêm","Hai mươi ngày đêm","Bốn mươi ngày đêm","Ba mươi ngày đêm"]',
 '[2]',
 'Ma-thi-ơ 4:2 — "Ngài đã kiêng ăn bốn mươi ngày bốn mươi đêm rồi, sau thì đói."',
 '["Ma-thi-ơ","Cám dỗ","Đồng vắng"]', 'BTT 1926', 'vi','ACTIVE', 0, 1, NOW(), NOW()),

('bq-mat-007', 'Matthew', 4, 19, 19, 'easy', 'multiple_choice_single',
 'Chúa Jêsus hứa sẽ làm Si-môn và Anh-rê trở nên gì? (Ma-thi-ơ 4:19)',
 '["Vua","Thầy tế lễ","Tay đánh lưới người","Tiên tri"]',
 '[2]',
 'Ma-thi-ơ 4:19 — "Hãy theo ta, ta sẽ cho các ngươi nên tay đánh lưới người."',
 '["Ma-thi-ơ","Môn đồ","Kêu gọi"]', 'BTT 1926', 'vi','ACTIVE', 0, 1, NOW(), NOW()),

-- Sermon on the Mount (ch 5-7)
('bq-mat-008', 'Matthew', 5, 3, 3, 'easy', 'multiple_choice_single',
 'Theo Bài giảng trên núi, ai là người có phước? (Ma-thi-ơ 5:3)',
 '["Người giàu có","Kẻ mạnh mẽ","Kẻ có lòng khó khăn","Người thông thái"]',
 '[2]',
 'Ma-thi-ơ 5:3 — "Phước cho những kẻ có lòng khó khăn, vì nước thiên đàng là của những kẻ ấy."',
 '["Ma-thi-ơ","Bài giảng trên núi","Phước lành"]', 'BTT 1926', 'vi','ACTIVE', 0, 1, NOW(), NOW()),

('bq-mat-009', 'Matthew', 5, 13, 13, 'easy', 'multiple_choice_single',
 'Chúa Jêsus ví các môn đồ như thứ gì trên đất? (Ma-thi-ơ 5:13)',
 '["Muối","Nước","Lửa","Gió"]',
 '[0]',
 'Ma-thi-ơ 5:13 — "Các ngươi là muối của đất."',
 '["Ma-thi-ơ","Bài giảng trên núi","Muối"]', 'BTT 1926', 'vi','ACTIVE', 0, 1, NOW(), NOW()),

('bq-mat-010', 'Matthew', 5, 14, 14, 'easy', 'multiple_choice_single',
 'Ngoài muối, Chúa Jêsus còn ví các môn đồ là gì? (Ma-thi-ơ 5:14)',
 '["Đường đi","Sự sáng của thế gian","Cây trái","Mưa từ trời"]',
 '[1]',
 'Ma-thi-ơ 5:14 — "Các ngươi là sự sáng của thế gian."',
 '["Ma-thi-ơ","Bài giảng trên núi","Ánh sáng"]', 'BTT 1926', 'vi','ACTIVE', 0, 1, NOW(), NOW()),

('bq-mat-011', 'Matthew', 6, 9, 13, 'easy', 'multiple_choice_single',
 'Bài cầu nguyện chung bắt đầu bằng câu nào? (Ma-thi-ơ 6:9)',
 '["Lạy Chúa xin thương xót","Xin Chúa giúp đỡ","Hỡi Đức Chúa Trời","Lạy Cha chúng tôi ở trên trời"]',
 '[3]',
 'Ma-thi-ơ 6:9 — "Lạy Cha chúng tôi ở trên trời, danh Cha được thánh."',
 '["Ma-thi-ơ","Bài giảng trên núi","Cầu nguyện"]', 'BTT 1926', 'vi','ACTIVE', 0, 1, NOW(), NOW()),

('bq-mat-012', 'Matthew', 7, 7, 7, 'easy', 'multiple_choice_single',
 'Theo Ma-thi-ơ 7:7, ai hỏi thì sẽ được điều gì?',
 '["Sẽ được thử thách","Sẽ được trả lời","Sẽ bị từ chối","Sẽ được ban cho"]',
 '[3]',
 'Ma-thi-ơ 7:7 — "Hãy xin, sẽ được; hãy tìm, sẽ gặp; hãy gõ cửa, sẽ mở cho."',
 '["Ma-thi-ơ","Bài giảng trên núi","Cầu nguyện"]', 'BTT 1926', 'vi','ACTIVE', 0, 1, NOW(), NOW()),

('bq-mat-013', 'Matthew', 7, 24, 25, 'easy', 'multiple_choice_single',
 'Người khôn ngoan xây nhà mình trên nền gì? (Ma-thi-ơ 7:24)',
 '["Trên cát","Trên hố sâu","Trên đá","Trên đất bằng"]',
 '[2]',
 'Ma-thi-ơ 7:24 — "Ta sẽ sánh người với một người khôn ngoan cất nhà mình trên hòn đá."',
 '["Ma-thi-ơ","Bài giảng trên núi","Ví dụ"]', 'BTT 1926', 'vi','ACTIVE', 0, 1, NOW(), NOW()),

-- Miracles (ch 8-14)
('bq-mat-014', 'Matthew', 8, 2, 3, 'easy', 'multiple_choice_single',
 'Chúa Jêsus chữa lành người mắc bệnh gì trong Ma-thi-ơ 8:2-3?',
 '["Mù mắt","Bại","Phung","Câm"]',
 '[2]',
 'Ma-thi-ơ 8:2-3 — "Có một người phung đến gần, lạy Ngài mà thưa rằng: Lạy Chúa, nếu Chúa khứng, chắc Chúa có thể khiến tôi sạch được. Ngài giơ tay rờ người, mà phán rằng: Ta khứng, hãy sạch đi."',
 '["Ma-thi-ơ","Phép lạ","Chữa lành"]', 'BTT 1926', 'vi','ACTIVE', 0, 1, NOW(), NOW()),

('bq-mat-015', 'Matthew', 8, 26, 26, 'easy', 'multiple_choice_single',
 'Chúa Jêsus quở gió và biển, điều gì đã xảy ra? (Ma-thi-ơ 8:26)',
 '["Biển yên lặng như tờ","Trời mưa to hơn","Thuyền chìm","Gió thổi mạnh hơn"]',
 '[0]',
 'Ma-thi-ơ 8:26 — "Ngài bèn đứng dậy, quở gió và biển; thì liền yên lặng như tờ."',
 '["Ma-thi-ơ","Phép lạ","Thiên nhiên"]', 'BTT 1926', 'vi','ACTIVE', 0, 1, NOW(), NOW()),

('bq-mat-016', 'Matthew', 9, 9, 9, 'easy', 'multiple_choice_single',
 'Ma-thi-ơ đang làm nghề gì khi được Chúa Jêsus kêu gọi? (Ma-thi-ơ 9:9)',
 '["Đánh cá","Thâu thuế","Chăn chiên","Thợ mộc"]',
 '[1]',
 'Ma-thi-ơ 9:9 — "Đức Chúa Jêsus thấy một người tên là Ma-thi-ơ, đang ngồi tại sở thâu thuế."',
 '["Ma-thi-ơ","Môn đồ","Kêu gọi"]', 'BTT 1926', 'vi','ACTIVE', 0, 1, NOW(), NOW()),

('bq-mat-017', 'Matthew', 14, 17, 20, 'easy', 'multiple_choice_single',
 'Chúa Jêsus dùng bao nhiêu ổ bánh và cá để cho 5000 người ăn? (Ma-thi-ơ 14:17)',
 '["Năm ổ bánh và hai con cá","Ba ổ bánh và một con cá","Bảy ổ bánh và ba con cá","Mười ổ bánh và năm con cá"]',
 '[0]',
 'Ma-thi-ơ 14:17 — "Môn đồ thưa rằng: Chúng tôi chỉ có đây năm cái bánh và hai con cá."',
 '["Ma-thi-ơ","Phép lạ","Hóa bánh"]', 'BTT 1926', 'vi','ACTIVE', 0, 1, NOW(), NOW()),

('bq-mat-018', 'Matthew', 14, 25, 29, 'easy', 'multiple_choice_single',
 'Ai đã bước đi trên mặt nước để đến cùng Chúa Jêsus? (Ma-thi-ơ 14:29)',
 '["Giăng","Gia-cơ","An-drê","Phi-e-rơ"]',
 '[3]',
 'Ma-thi-ơ 14:29 — "Phi-e-rơ bèn bước ra khỏi thuyền, đi trên mặt nước mà đến cùng Đức Chúa Jêsus."',
 '["Ma-thi-ơ","Phép lạ","Phi-e-rơ"]', 'BTT 1926', 'vi','ACTIVE', 0, 1, NOW(), NOW()),

('bq-mat-019', 'Matthew', 10, 2, 4, 'easy', 'multiple_choice_single',
 'Chúa Jêsus chọn bao nhiêu sứ đồ? (Ma-thi-ơ 10:2-4)',
 '["Bảy","Mười","Hai mươi","Mười hai"]',
 '[3]',
 'Ma-thi-ơ 10:2-4 — "Tên mười hai sứ đồ như sau: Thứ nhứt, Si-môn, cũng gọi là Phi-e-rơ..."',
 '["Ma-thi-ơ","Sứ đồ","Mười hai"]', 'BTT 1926', 'vi','ACTIVE', 0, 1, NOW(), NOW()),

('bq-mat-020', 'Matthew', 11, 28, 28, 'easy', 'multiple_choice_single',
 'Chúa Jêsus mời ai đến cùng Ngài để được yên nghỉ? (Ma-thi-ơ 11:28)',
 '["Hết thảy những kẻ mệt mỏi gánh nặng","Người giàu có","Các thầy tế lễ","Người Pha-ri-si"]',
 '[0]',
 'Ma-thi-ơ 11:28 — "Hỡi những kẻ mệt mỏi và gánh nặng, hãy đến cùng ta, ta sẽ cho các ngươi được yên nghỉ."',
 '["Ma-thi-ơ","Lời mời gọi","Yên nghỉ"]', 'BTT 1926', 'vi','ACTIVE', 0, 1, NOW(), NOW()),

-- Parables (ch 13, 18, 20, 25)
('bq-mat-021', 'Matthew', 13, 3, 8, 'easy', 'multiple_choice_single',
 'Trong ví dụ về người gieo giống, hột giống rơi trên đất tốt kết quả thế nào? (Ma-thi-ơ 13:8)',
 '["Bị chim ăn","Bị gai chẹt","Bị héo đi","Ra trái gấp trăm"]',
 '[3]',
 'Ma-thi-ơ 13:8 — "Lại có hột rơi nhằm đất tốt, thì sanh trái, hột thì được một trăm, hột sáu chục, hột ba chục."',
 '["Ma-thi-ơ","Ví dụ","Gieo giống"]', 'BTT 1926', 'vi','ACTIVE', 0, 1, NOW(), NOW()),

('bq-mat-022', 'Matthew', 13, 31, 32, 'easy', 'multiple_choice_single',
 'Nước thiên đàng được ví như hột giống nào nhỏ nhất? (Ma-thi-ơ 13:31)',
 '["Hột lúa mì","Hột đậu","Hột cải","Hột vừng"]',
 '[2]',
 'Ma-thi-ơ 13:31-32 — "Nước thiên đàng giống như một hột cải mà người kia lấy gieo trong ruộng mình. Hột ấy thật nhỏ hơn các giống khác."',
 '["Ma-thi-ơ","Ví dụ","Hột cải"]', 'BTT 1926', 'vi','ACTIVE', 0, 1, NOW(), NOW()),

('bq-mat-023', 'Matthew', 18, 12, 13, 'easy', 'multiple_choice_single',
 'Trong ví dụ con chiên lạc mất, người chăn có bao nhiêu con chiên? (Ma-thi-ơ 18:12)',
 '["Năm mươi","Một trăm","Bảy mươi","Hai trăm"]',
 '[1]',
 'Ma-thi-ơ 18:12 — "Ví bằng một người có một trăm con chiên, mà có một con đi lạc, thì người ấy há chẳng để chín mươi chín con lại trên núi, mà đi tìm con chiên lạc sao?"',
 '["Ma-thi-ơ","Ví dụ","Chiên lạc"]', 'BTT 1926', 'vi','ACTIVE', 0, 1, NOW(), NOW()),

('bq-mat-024', 'Matthew', 25, 1, 2, 'easy', 'multiple_choice_single',
 'Trong ví dụ mười người nữ đồng trinh, có bao nhiêu người khôn ngoan? (Ma-thi-ơ 25:2)',
 '["Ba","Bảy","Năm","Mười"]',
 '[2]',
 'Ma-thi-ơ 25:2 — "Trong các nàng đó, có năm người dại và năm người khôn."',
 '["Ma-thi-ơ","Ví dụ","Mười người nữ đồng trinh"]', 'BTT 1926', 'vi','ACTIVE', 0, 1, NOW(), NOW()),

-- Passion (ch 26-27)
('bq-mat-025', 'Matthew', 26, 15, 15, 'easy', 'multiple_choice_single',
 'Giu-đa bán Chúa Jêsus với giá bao nhiêu? (Ma-thi-ơ 26:15)',
 '["Ba mươi miếng bạc","Hai mươi miếng bạc","Mười miếng bạc","Năm mươi miếng bạc"]',
 '[0]',
 'Ma-thi-ơ 26:15 — "Mà hỏi rằng: Các thầy bằng lòng trả cho tôi bao nhiêu đặng tôi nộp người cho? Họ bèn trả cho hắn ba mươi miếng bạc."',
 '["Ma-thi-ơ","Thương khó","Giu-đa"]', 'BTT 1926', 'vi','ACTIVE', 0, 1, NOW(), NOW()),

('bq-mat-026', 'Matthew', 26, 34, 34, 'easy', 'multiple_choice_single',
 'Chúa Jêsus nói Phi-e-rơ sẽ chối Ngài mấy lần trước khi gà gáy? (Ma-thi-ơ 26:34)',
 '["Một lần","Ba lần","Hai lần","Bốn lần"]',
 '[1]',
 'Ma-thi-ơ 26:34 — "Quả thật, ta nói cùng ngươi, nội đêm nay, trước khi gà gáy, ngươi sẽ chối ta ba lần."',
 '["Ma-thi-ơ","Thương khó","Phi-e-rơ"]', 'BTT 1926', 'vi','ACTIVE', 0, 1, NOW(), NOW()),

('bq-mat-027', 'Matthew', 27, 2, 2, 'easy', 'multiple_choice_single',
 'Các thầy tế lễ nộp Chúa Jêsus cho ai để xét xử? (Ma-thi-ơ 27:2)',
 '["Quan tổng đốc Phi-lát","Vua Hê-rốt","Thầy cả thượng phẩm","Sê-sa"]',
 '[0]',
 'Ma-thi-ơ 27:2 — "Rồi trói Ngài, giải đi nộp cho quan tổng đốc Phi-lát."',
 '["Ma-thi-ơ","Thương khó","Phi-lát"]', 'BTT 1926', 'vi','ACTIVE', 0, 1, NOW(), NOW()),

('bq-mat-028', 'Matthew', 27, 37, 37, 'easy', 'multiple_choice_single',
 'Tấm bảng trên thập tự giá viết gì? (Ma-thi-ơ 27:37)',
 '["Tên tội nhân","Chết vì tội lỗi","Người nầy là Jêsus, vua dân Giu-đa","Kẻ phạm pháp"]',
 '[2]',
 'Ma-thi-ơ 27:37 — "Phía trên đầu Ngài, có đề chữ chỉ về án xử Ngài rằng: NGƯỜI NẦY LÀ JÊSUS, VUA DÂN GIU-ĐA."',
 '["Ma-thi-ơ","Thương khó","Thập tự giá"]', 'BTT 1926', 'vi','ACTIVE', 0, 1, NOW(), NOW()),

-- Resurrection (ch 28)
('bq-mat-029', 'Matthew', 28, 2, 2, 'easy', 'multiple_choice_single',
 'Ai đã lăn hòn đá khỏi cửa mộ Chúa Jêsus? (Ma-thi-ơ 28:2)',
 '["Phi-e-rơ","Thiên sứ của Chúa","Lính canh","Ma-ri Ma-đơ-len"]',
 '[1]',
 'Ma-thi-ơ 28:2 — "Một thiên sứ của Chúa ở trên trời xuống, đến lăn hòn đá ra rồi ngồi ở trên."',
 '["Ma-thi-ơ","Phục sinh","Thiên sứ"]', 'BTT 1926', 'vi','ACTIVE', 0, 1, NOW(), NOW()),

('bq-mat-030', 'Matthew', 28, 6, 6, 'easy', 'multiple_choice_single',
 'Thiên sứ nói gì về Chúa Jêsus tại mộ? (Ma-thi-ơ 28:6)',
 '["Ngài đang ngủ","Ngài ở trong mộ","Ngài đã đi xa","Ngài đã sống lại"]',
 '[3]',
 'Ma-thi-ơ 28:6 — "Ngài không ở đây đâu; Ngài đã sống lại rồi, như lời Ngài đã phán."',
 '["Ma-thi-ơ","Phục sinh","Sống lại"]', 'BTT 1926', 'vi','ACTIVE', 0, 1, NOW(), NOW()),

('bq-mat-031', 'Matthew', 28, 19, 19, 'easy', 'multiple_choice_single',
 'Chúa Jêsus truyền cho các môn đồ đi làm gì cho muôn dân? (Ma-thi-ơ 28:19)',
 '["Thu thuế","Khiến muôn dân trở nên môn đồ","Dạy luật pháp","Xây đền thờ"]',
 '[1]',
 'Ma-thi-ơ 28:19 — "Vậy, hãy đi dạy dỗ muôn dân, hãy nhân danh Đức Cha, Đức Con, và Đức Thánh Linh mà làm phép báp-tem cho họ."',
 '["Ma-thi-ơ","Đại mạng lệnh","Truyền giáo"]', 'BTT 1926', 'vi','ACTIVE', 0, 1, NOW(), NOW()),

('bq-mat-032', 'Matthew', 1, 18, 18, 'easy', 'multiple_choice_single',
 'Ma-ri chịu thai bởi ai? (Ma-thi-ơ 1:18)',
 '["Đức Thánh Linh","Giô-sép","Thiên sứ","Không được nói rõ"]',
 '[0]',
 'Ma-thi-ơ 1:18 — "Ma-ri, mẹ Ngài, đã hứa gả cho Giô-sép, song chưa ăn ở cùng nhau thì người đã chịu thai bởi Đức Thánh Linh."',
 '["Ma-thi-ơ","Giáng sinh","Đức Thánh Linh"]', 'BTT 1926', 'vi','ACTIVE', 0, 1, NOW(), NOW()),

('bq-mat-033', 'Matthew', 6, 24, 24, 'easy', 'multiple_choice_single',
 'Theo Chúa Jêsus, không ai làm tôi hai chủ được. Ngài nói không thể vừa làm tôi Đức Chúa Trời vừa làm tôi ai? (Ma-thi-ơ 6:24)',
 '["Vua chúa","Ma-môn (tiền tài)","Pha-ra-ôn","Sa-tan"]',
 '[1]',
 'Ma-thi-ơ 6:24 — "Các ngươi không có thể làm tôi Đức Chúa Trời lại làm tôi Ma-môn nữa."',
 '["Ma-thi-ơ","Bài giảng trên núi","Ma-môn"]', 'BTT 1926', 'vi','ACTIVE', 0, 1, NOW(), NOW()),

('bq-mat-034', 'Matthew', 12, 40, 40, 'easy', 'multiple_choice_single',
 'Chúa Jêsus nói Con người sẽ ở trong lòng đất bao lâu, giống Giô-na ở trong bụng cá? (Ma-thi-ơ 12:40)',
 '["Một ngày một đêm","Hai ngày hai đêm","Ba ngày ba đêm","Bảy ngày bảy đêm"]',
 '[2]',
 'Ma-thi-ơ 12:40 — "Vì Giô-na đã ở trong bụng cá lớn ba ngày ba đêm, cũng một thể ấy, Con người sẽ ở trong lòng đất ba ngày ba đêm."',
 '["Ma-thi-ơ","Tiên tri","Giô-na"]', 'BTT 1926', 'vi','ACTIVE', 0, 1, NOW(), NOW()),

('bq-mat-035', 'Matthew', 16, 16, 16, 'easy', 'multiple_choice_single',
 'Phi-e-rơ xưng nhận Chúa Jêsus là ai? (Ma-thi-ơ 16:16)',
 '["Đấng Christ, Con Đức Chúa Trời hằng sống","Giăng Báp-tít","Một tiên tri","Ê-li"]',
 '[0]',
 'Ma-thi-ơ 16:16 — "Si-môn Phi-e-rơ thưa rằng: Chúa là Đấng Christ, Con Đức Chúa Trời hằng sống."',
 '["Ma-thi-ơ","Đức tin","Phi-e-rơ"]', 'BTT 1926', 'vi','ACTIVE', 0, 1, NOW(), NOW()),

-- ═══════════════════════════════════════════════════════════════
-- MEDIUM (28 questions)
-- ═══════════════════════════════════════════════════════════════

-- Birth & Early Life (ch 1-2)
('bq-mat-036', 'Matthew', 1, 1, 1, 'medium', 'multiple_choice_single',
 'Ma-thi-ơ mở đầu gia phả Chúa Jêsus bằng dòng dõi của ai? (Ma-thi-ơ 1:1)',
 '["Nô-ê và Áp-ra-ham","Áp-ra-ham và Đa-vít","A-đam và Sết","Môi-se và A-rôn"]',
 '[1]',
 'Ma-thi-ơ 1:1 — "Gia phổ Đức Chúa Jêsus Christ, con cháu Đa-vít, con cháu Áp-ra-ham."',
 '["Ma-thi-ơ","Gia phả","Áp-ra-ham"]', 'BTT 1926', 'vi','ACTIVE', 0, 1, NOW(), NOW()),

('bq-mat-037', 'Matthew', 2, 2, 2, 'medium', 'multiple_choice_single',
 'Các thầy bác sĩ đã thấy dấu hiệu gì khi Vua dân Giu-đa ra đời? (Ma-thi-ơ 2:2)',
 '["Thiên sứ hiện ra","Ngôi sao Ngài","Tiếng nói từ trời","Ánh sáng lạ"]',
 '[1]',
 'Ma-thi-ơ 2:2 — "Vua dân Giu-đa mới sanh tại đâu? Vì chúng ta đã thấy ngôi sao Ngài bên Đông phương."',
 '["Ma-thi-ơ","Giáng sinh","Ngôi sao"]', 'BTT 1926', 'vi','ACTIVE', 0, 1, NOW(), NOW()),

('bq-mat-038', 'Matthew', 2, 16, 16, 'medium', 'multiple_choice_single',
 'Hê-rốt ra lệnh giết con trẻ từ bao nhiêu tuổi trở xuống? (Ma-thi-ơ 2:16)',
 '["Dưới một tuổi","Ba tuổi sấp xuống","Hai tuổi sấp xuống","Năm tuổi sấp xuống"]',
 '[2]',
 'Ma-thi-ơ 2:16 — "Bèn sai giết hết thảy con trai từ hai tuổi sấp xuống ở trong thành Bết-lê-hem."',
 '["Ma-thi-ơ","Hê-rốt","Bết-lê-hem"]', 'BTT 1926', 'vi','ACTIVE', 0, 1, NOW(), NOW()),

-- Sermon on the Mount (ch 5-7)
('bq-mat-039', 'Matthew', 5, 39, 39, 'medium', 'multiple_choice_single',
 'Chúa Jêsus dạy khi bị vả má bên hữu, phải làm gì? (Ma-thi-ơ 5:39)',
 '["Đánh lại","Bỏ chạy","Kiện ra tòa","Đưa má bên kia cho họ"]',
 '[3]',
 'Ma-thi-ơ 5:39 — "Song ta bảo các ngươi, đừng chống cự kẻ dữ. Trái lại, nếu ai vả má bên hữu ngươi, hãy đưa má bên kia cho họ."',
 '["Ma-thi-ơ","Bài giảng trên núi","Yêu thương"]', 'BTT 1926', 'vi','ACTIVE', 0, 1, NOW(), NOW()),

('bq-mat-040', 'Matthew', 5, 44, 44, 'medium', 'multiple_choice_single',
 'Chúa Jêsus dạy phải đối xử với kẻ thù nghịch mình thế nào? (Ma-thi-ơ 5:44)',
 '["Yêu họ và cầu nguyện cho họ","Tránh xa họ","Trừng phạt họ","Không nói chuyện với họ"]',
 '[0]',
 'Ma-thi-ơ 5:44 — "Hãy yêu kẻ thù nghịch, và cầu nguyện cho kẻ bắt bớ các ngươi."',
 '["Ma-thi-ơ","Bài giảng trên núi","Yêu kẻ thù"]', 'BTT 1926', 'vi','ACTIVE', 0, 1, NOW(), NOW()),

('bq-mat-041', 'Matthew', 6, 3, 4, 'medium', 'multiple_choice_single',
 'Khi bố thí, tay trái không nên biết điều gì? (Ma-thi-ơ 6:3)',
 '["Người nhận là ai","Nơi bố thí","Số tiền bao nhiêu","Tay hữu làm việc gì"]',
 '[3]',
 'Ma-thi-ơ 6:3 — "Song khi ngươi bố thí, đừng cho tay trái biết tay hữu làm việc gì."',
 '["Ma-thi-ơ","Bài giảng trên núi","Bố thí"]', 'BTT 1926', 'vi','ACTIVE', 0, 1, NOW(), NOW()),

('bq-mat-042', 'Matthew', 7, 13, 14, 'medium', 'multiple_choice_single',
 'Cửa dẫn đến sự sống được mô tả thế nào? (Ma-thi-ơ 7:14)',
 '["Rộng rãi và dễ đi","Được trang trí đẹp","Hẹp và đường chật","Luôn mở rộng"]',
 '[2]',
 'Ma-thi-ơ 7:14 — "Song cửa hẹp và đường chật dẫn đến sự sống, kẻ kiếm được thì ít."',
 '["Ma-thi-ơ","Bài giảng trên núi","Cửa hẹp"]', 'BTT 1926', 'vi','ACTIVE', 0, 1, NOW(), NOW()),

('bq-mat-043', 'Matthew', 6, 34, 34, 'medium', 'multiple_choice_single',
 'Chúa Jêsus dạy không nên lo lắng về điều gì? (Ma-thi-ơ 6:34)',
 '["Quá khứ","Người khác","Ngày mai","Công việc"]',
 '[2]',
 'Ma-thi-ơ 6:34 — "Vậy, chớ lo lắng chi về ngày mai; vì ngày mai sẽ lo về việc ngày mai."',
 '["Ma-thi-ơ","Bài giảng trên núi","Lo lắng"]', 'BTT 1926', 'vi','ACTIVE', 0, 1, NOW(), NOW()),

-- Miracles (ch 8-14)
('bq-mat-044', 'Matthew', 8, 5, 10, 'medium', 'multiple_choice_single',
 'Viên đội trưởng ở Ca-bê-na-um xin Chúa chữa ai? (Ma-thi-ơ 8:6)',
 '["Con trai mình","Vợ mình","Cha mình","Đầy tớ mình"]',
 '[3]',
 'Ma-thi-ơ 8:6 — "Thưa Chúa, đầy tớ tôi đau nằm ở nhà, bị tê bại lắm."',
 '["Ma-thi-ơ","Phép lạ","Đức tin"]', 'BTT 1926', 'vi','ACTIVE', 0, 1, NOW(), NOW()),

('bq-mat-045', 'Matthew', 9, 20, 22, 'medium', 'multiple_choice_single',
 'Người đàn bà bị bệnh mất huyết bao lâu trước khi rờ trôn áo Chúa? (Ma-thi-ơ 9:20)',
 '["Hai năm","Năm năm","Hai mươi năm","Mười hai năm"]',
 '[3]',
 'Ma-thi-ơ 9:20 — "Một người đàn bà bị mất huyết đã mười hai năm, đến phía sau Ngài, rờ trôn áo."',
 '["Ma-thi-ơ","Phép lạ","Chữa lành"]', 'BTT 1926', 'vi','ACTIVE', 0, 1, NOW(), NOW()),

('bq-mat-046', 'Matthew', 14, 21, 21, 'medium', 'multiple_choice_single',
 'Khi Chúa hóa bánh ra nhiều, có bao nhiêu người nam ăn (không kể đàn bà và con trẻ)? (Ma-thi-ơ 14:21)',
 '["Ba ngàn","Bốn ngàn","Năm ngàn","Bảy ngàn"]',
 '[2]',
 'Ma-thi-ơ 14:21 — "Số người ăn ước chừng năm ngàn, không kể đàn bà con nít."',
 '["Ma-thi-ơ","Phép lạ","Hóa bánh"]', 'BTT 1926', 'vi','ACTIVE', 0, 1, NOW(), NOW()),

('bq-mat-047', 'Matthew', 9, 2, 6, 'medium', 'multiple_choice_single',
 'Trước khi chữa lành người bại, Chúa Jêsus nói gì? (Ma-thi-ơ 9:2)',
 '["Hãy đứng dậy","Đức tin con lớn lắm","Tội lỗi con đã được tha","Hãy về nhà"]',
 '[2]',
 'Ma-thi-ơ 9:2 — "Hỡi con, hãy vững lòng, tội lỗi con đã được tha."',
 '["Ma-thi-ơ","Phép lạ","Tha tội"]', 'BTT 1926', 'vi','ACTIVE', 0, 1, NOW(), NOW()),

-- Parables
('bq-mat-048', 'Matthew', 13, 44, 44, 'medium', 'multiple_choice_single',
 'Nước thiên đàng giống như của báu giấu ở đâu? (Ma-thi-ơ 13:44)',
 '["Trong đền thờ","Trong ruộng","Trong nhà","Dưới biển"]',
 '[1]',
 'Ma-thi-ơ 13:44 — "Nước thiên đàng giống như của báu chôn trong một đám ruộng."',
 '["Ma-thi-ơ","Ví dụ","Của báu"]', 'BTT 1926', 'vi','ACTIVE', 0, 1, NOW(), NOW()),

('bq-mat-049', 'Matthew', 18, 21, 22, 'medium', 'multiple_choice_single',
 'Chúa Jêsus bảo Phi-e-rơ tha tội cho anh em bao nhiêu lần? (Ma-thi-ơ 18:22)',
 '["Bảy lần","Bảy mươi lần bảy","Mười lần","Ba lần"]',
 '[1]',
 'Ma-thi-ơ 18:22 — "Ta không nói cùng ngươi rằng đến bảy lần đâu, nhưng đến bảy mươi lần bảy."',
 '["Ma-thi-ơ","Tha thứ","Phi-e-rơ"]', 'BTT 1926', 'vi','ACTIVE', 0, 1, NOW(), NOW()),

('bq-mat-050', 'Matthew', 20, 1, 2, 'medium', 'multiple_choice_single',
 'Trong ví dụ thợ làm vườn nho, chủ thỏa thuận trả cho thợ bao nhiêu một ngày? (Ma-thi-ơ 20:2)',
 '["Hai đơ-ni-ê","Năm đơ-ni-ê","Một đơ-ni-ê","Mười đơ-ni-ê"]',
 '[2]',
 'Ma-thi-ơ 20:2 — "Khi người chủ đã định giá với con làm công, mỗi ngày một đơ-ni-ê."',
 '["Ma-thi-ơ","Ví dụ","Vườn nho"]', 'BTT 1926', 'vi','ACTIVE', 0, 1, NOW(), NOW()),

('bq-mat-051', 'Matthew', 25, 15, 15, 'medium', 'multiple_choice_single',
 'Trong ví dụ ta-lâng, người chủ giao cho đầy tớ thứ nhất bao nhiêu ta-lâng? (Ma-thi-ơ 25:15)',
 '["Một ta-lâng","Hai ta-lâng","Mười ta-lâng","Năm ta-lâng"]',
 '[3]',
 'Ma-thi-ơ 25:15 — "Chủ cho người nầy năm ta-lâng, người kia hai, người khác một, tùy theo tài mỗi người."',
 '["Ma-thi-ơ","Ví dụ","Ta-lâng"]', 'BTT 1926', 'vi','ACTIVE', 0, 1, NOW(), NOW()),

('bq-mat-052', 'Matthew', 25, 35, 36, 'medium', 'multiple_choice_single',
 'Trong ngày phán xét, Vua khen những người công bình vì đã làm điều gì cho Ngài? (Ma-thi-ơ 25:35)',
 '["Xây đền thờ","Đọc Kinh Thánh","Dâng nhiều tiền","Cho ăn khi đói, cho uống khi khát"]',
 '[3]',
 'Ma-thi-ơ 25:35 — "Vì ta đói, các ngươi đã cho ta ăn; ta khát, các ngươi đã cho ta uống; ta là khách lạ, các ngươi tiếp rước ta."',
 '["Ma-thi-ơ","Phán xét","Yêu thương"]', 'BTT 1926', 'vi','ACTIVE', 0, 1, NOW(), NOW()),

-- Passion & Resurrection (ch 26-28)
('bq-mat-053', 'Matthew', 26, 36, 36, 'medium', 'multiple_choice_single',
 'Chúa Jêsus đến nơi nào để cầu nguyện trước khi bị bắt? (Ma-thi-ơ 26:36)',
 '["Đền thờ","Ghết-sê-ma-nê","Núi Si-na-i","Bết-lê-hem"]',
 '[1]',
 'Ma-thi-ơ 26:36 — "Đức Chúa Jêsus đi cùng môn đồ đến một nơi kia, gọi là Ghết-sê-ma-nê."',
 '["Ma-thi-ơ","Thương khó","Ghết-sê-ma-nê"]', 'BTT 1926', 'vi','ACTIVE', 0, 1, NOW(), NOW()),

('bq-mat-054', 'Matthew', 26, 49, 49, 'medium', 'multiple_choice_single',
 'Giu-đa dùng dấu hiệu gì để chỉ cho lính biết Chúa Jêsus? (Ma-thi-ơ 26:49)',
 '["Hôn","Chỉ tay","Gọi tên","Khoác áo"]',
 '[0]',
 'Ma-thi-ơ 26:49 — "Liền đến gần Đức Chúa Jêsus mà nói rằng: Chào thầy! Rồi hôn Ngài."',
 '["Ma-thi-ơ","Thương khó","Giu-đa"]', 'BTT 1926', 'vi','ACTIVE', 0, 1, NOW(), NOW()),

('bq-mat-055', 'Matthew', 27, 46, 46, 'medium', 'multiple_choice_single',
 'Chúa Jêsus kêu lớn trên thập tự giá rằng gì? (Ma-thi-ơ 27:46)',
 '["Mọi việc đã xong","Cha ơi tha cho họ","Ê-li, Ê-li, lam-ma sa-bách-ta-ni","Ta khát"]',
 '[2]',
 'Ma-thi-ơ 27:46 — "Đức Chúa Jêsus kêu lớn tiếng rằng: Ê-li, Ê-li, lam-ma sa-bách-ta-ni? nghĩa là: Đức Chúa Trời tôi ơi! sao Ngài lìa bỏ tôi?"',
 '["Ma-thi-ơ","Thương khó","Thập tự giá"]', 'BTT 1926', 'vi','ACTIVE', 0, 1, NOW(), NOW()),

('bq-mat-056', 'Matthew', 27, 51, 51, 'medium', 'multiple_choice_single',
 'Khi Chúa Jêsus tắt hơi, điều gì xảy ra trong đền thờ? (Ma-thi-ơ 27:51)',
 '["Bức màn xé ra làm đôi","Đền thờ sụp đổ","Lửa cháy","Nước lụt"]',
 '[0]',
 'Ma-thi-ơ 27:51 — "Và nầy, bức màn trong đền thờ, xé ra làm hai từ trên chí dưới."',
 '["Ma-thi-ơ","Thương khó","Bức màn"]', 'BTT 1926', 'vi','ACTIVE', 0, 1, NOW(), NOW()),

('bq-mat-057', 'Matthew', 27, 57, 60, 'medium', 'multiple_choice_single',
 'Ai đã xin Phi-lát cho nhận xác Chúa Jêsus để chôn? (Ma-thi-ơ 27:57-58)',
 '["Phi-e-rơ","Giô-sép người A-ri-ma-thê","Ni-cô-đem","Giăng"]',
 '[1]',
 'Ma-thi-ơ 27:57-58 — "Có một người giàu, ở thành A-ri-ma-thê, tên là Giô-sép... đến xin xác Đức Chúa Jêsus."',
 '["Ma-thi-ơ","Chôn cất","Giô-sép"]', 'BTT 1926', 'vi','ACTIVE', 0, 1, NOW(), NOW()),

('bq-mat-058', 'Matthew', 28, 1, 1, 'medium', 'multiple_choice_single',
 'Ai là những người đầu tiên đến thăm mộ Chúa Jêsus? (Ma-thi-ơ 28:1)',
 '["Ma-ri Ma-đơ-len và Ma-ri khác","Phi-e-rơ và Giăng","Các sứ đồ","Lính canh"]',
 '[0]',
 'Ma-thi-ơ 28:1 — "Ma-ri Ma-đơ-len và Ma-ri khác, đến thăm mộ."',
 '["Ma-thi-ơ","Phục sinh","Ma-ri"]', 'BTT 1926', 'vi','ACTIVE', 0, 1, NOW(), NOW()),

('bq-mat-059', 'Matthew', 15, 32, 38, 'medium', 'multiple_choice_single',
 'Lần thứ hai Chúa cho đoàn dân ăn, có bao nhiêu người nam? (Ma-thi-ơ 15:38)',
 '["Ba ngàn","Bảy ngàn","Năm ngàn","Bốn ngàn"]',
 '[3]',
 'Ma-thi-ơ 15:38 — "Số người ăn là bốn ngàn, không kể đàn bà con nít."',
 '["Ma-thi-ơ","Phép lạ","Hóa bánh"]', 'BTT 1926', 'vi','ACTIVE', 0, 1, NOW(), NOW()),

('bq-mat-060', 'Matthew', 17, 1, 2, 'medium', 'multiple_choice_single',
 'Chúa Jêsus đem ba môn đồ nào lên núi khi hóa hình? (Ma-thi-ơ 17:1)',
 '["Phi-e-rơ, Gia-cơ, Giăng","Phi-e-rơ, An-drê, Giăng","Ma-thi-ơ, Gia-cơ, Giăng","Phi-e-rơ, Gia-cơ, An-drê"]',
 '[0]',
 'Ma-thi-ơ 17:1 — "Đức Chúa Jêsus đem Phi-e-rơ, Gia-cơ, và Giăng là em Gia-cơ, lên núi cao riêng."',
 '["Ma-thi-ơ","Hóa hình","Phi-e-rơ"]', 'BTT 1926', 'vi','ACTIVE', 0, 1, NOW(), NOW()),

('bq-mat-061', 'Matthew', 17, 3, 3, 'medium', 'multiple_choice_single',
 'Khi Chúa hóa hình, hai nhân vật nào hiện ra nói chuyện với Ngài? (Ma-thi-ơ 17:3)',
 '["Áp-ra-ham và Đa-vít","Môi-se và Ê-li","Ê-sai và Giê-rê-mi","Nô-ê và Đa-ni-ên"]',
 '[1]',
 'Ma-thi-ơ 17:3 — "Môi-se và Ê-li hiện đến, nói chuyện cùng Ngài."',
 '["Ma-thi-ơ","Hóa hình","Môi-se"]', 'BTT 1926', 'vi','ACTIVE', 0, 1, NOW(), NOW()),

('bq-mat-062', 'Matthew', 21, 8, 9, 'medium', 'multiple_choice_single',
 'Đoàn dân trải gì trên đường khi Chúa Jêsus vào thành Giê-ru-sa-lem? (Ma-thi-ơ 21:8)',
 '["Áo mình và nhánh cây","Hoa","Thảm đỏ","Cát vàng"]',
 '[0]',
 'Ma-thi-ơ 21:8 — "Bấy giờ phần nhiều trong đám dân đông trải áo mình trên đường; kẻ khác chặt nhánh cây trải trên đường."',
 '["Ma-thi-ơ","Vào thành","Giê-ru-sa-lem"]', 'BTT 1926', 'vi','ACTIVE', 0, 1, NOW(), NOW()),

('bq-mat-063', 'Matthew', 22, 37, 39, 'medium', 'multiple_choice_single',
 'Theo Chúa Jêsus, điều răn lớn hơn hết là gì? (Ma-thi-ơ 22:37)',
 '["Giữ ngày Sa-bát","Hết lòng yêu mến Chúa, Đức Chúa Trời ngươi","Không được giết người","Hiếu kính cha mẹ"]',
 '[1]',
 'Ma-thi-ơ 22:37 — "Ngươi hãy hết lòng, hết linh hồn, hết ý mà yêu mến Chúa, là Đức Chúa Trời ngươi."',
 '["Ma-thi-ơ","Điều răn","Yêu mến Chúa"]', 'BTT 1926', 'vi','ACTIVE', 0, 1, NOW(), NOW()),

-- ═══════════════════════════════════════════════════════════════
-- HARD (17 questions)
-- ═══════════════════════════════════════════════════════════════

('bq-mat-064', 'Matthew', 1, 17, 17, 'hard', 'multiple_choice_single',
 'Gia phả Ma-thi-ơ chia thành mấy đời, mỗi phần bao nhiêu đời? (Ma-thi-ơ 1:17)',
 '["Bốn phần, mỗi phần 10 đời","Ba phần, mỗi phần 14 đời","Hai phần, mỗi phần 21 đời","Ba phần, mỗi phần 12 đời"]',
 '[1]',
 'Ma-thi-ơ 1:17 — "Như vậy, từ Áp-ra-ham đến Đa-vít, cọng lại là mười bốn đời... cọng là mười bốn đời... cũng là mười bốn đời."',
 '["Ma-thi-ơ","Gia phả","Số liệu"]', 'BTT 1926', 'vi','ACTIVE', 0, 1, NOW(), NOW()),

('bq-mat-065', 'Matthew', 1, 23, 23, 'hard', 'multiple_choice_single',
 'Tên Em-ma-nu-ên trong Ma-thi-ơ 1:23 có nghĩa là gì?',
 '["Đấng Cứu Thế","Vua của vua","Con Đức Chúa Trời","Đức Chúa Trời ở cùng chúng ta"]',
 '[3]',
 'Ma-thi-ơ 1:23 — "Nầy, một gái đồng trinh sẽ chịu thai, và sanh một con trai, rồi người ta sẽ đặt tên con trai đó là Em-ma-nu-ên, nghĩa là Đức Chúa Trời ở cùng chúng ta."',
 '["Ma-thi-ơ","Tiên tri","Em-ma-nu-ên"]', 'BTT 1926', 'vi','ACTIVE', 0, 1, NOW(), NOW()),

('bq-mat-066', 'Matthew', 4, 4, 4, 'hard', 'multiple_choice_single',
 'Khi bị cám dỗ hóa đá thành bánh, Chúa Jêsus trả lời bằng câu Kinh Thánh nào? (Ma-thi-ơ 4:4)',
 '["Ngươi phải thờ phượng Chúa","Ngươi đừng thử Chúa","Người ta sống chẳng phải chỉ nhờ bánh","Hãy lui ra Sa-tan"]',
 '[2]',
 'Ma-thi-ơ 4:4 — "Người ta sống chẳng phải chỉ nhờ bánh mà thôi, song nhờ mọi lời nói ra từ miệng Đức Chúa Trời."',
 '["Ma-thi-ơ","Cám dỗ","Lời Chúa"]', 'BTT 1926', 'vi','ACTIVE', 0, 1, NOW(), NOW()),

('bq-mat-067', 'Matthew', 5, 17, 17, 'hard', 'multiple_choice_single',
 'Chúa Jêsus nói Ngài đến không phải để hủy bỏ luật pháp mà để làm gì? (Ma-thi-ơ 5:17)',
 '["Thay đổi luật","Bãi bỏ luật cũ","Viết lại luật","Làm cho trọn"]',
 '[3]',
 'Ma-thi-ơ 5:17 — "Các ngươi đừng tưởng ta đến đặng phá luật pháp hay là lời tiên tri; ta đến, không phải để phá, song để làm cho trọn."',
 '["Ma-thi-ơ","Bài giảng trên núi","Luật pháp"]', 'BTT 1926', 'vi','ACTIVE', 0, 1, NOW(), NOW()),

('bq-mat-068', 'Matthew', 6, 21, 21, 'hard', 'multiple_choice_single',
 'Theo Chúa Jêsus, của cải ở đâu thì lòng cũng ở đâu? (Ma-thi-ơ 6:21)',
 '["Ở trên đất","Ở đó","Ở trong đền thờ","Ở trên trời"]',
 '[1]',
 'Ma-thi-ơ 6:21 — "Vì chưng của cải ngươi ở đâu, thì lòng ngươi cũng ở đó."',
 '["Ma-thi-ơ","Bài giảng trên núi","Của cải"]', 'BTT 1926', 'vi','ACTIVE', 0, 1, NOW(), NOW()),

('bq-mat-069', 'Matthew', 7, 15, 15, 'hard', 'multiple_choice_single',
 'Chúa Jêsus ví tiên tri giả giống thú vật nào mặc lốt chiên? (Ma-thi-ơ 7:15)',
 '["Sư tử","Rắn","Cáo","Muông sói"]',
 '[3]',
 'Ma-thi-ơ 7:15 — "Hãy coi chừng tiên tri giả, là những kẻ mang lốt chiên đến cùng các ngươi, song bề trong thật là muông sói hay cắn xé."',
 '["Ma-thi-ơ","Bài giảng trên núi","Tiên tri giả"]', 'BTT 1926', 'vi','ACTIVE', 0, 1, NOW(), NOW()),

('bq-mat-070', 'Matthew', 13, 24, 30, 'hard', 'multiple_choice_single',
 'Trong ví dụ lúa mì và cỏ lùng, chủ bảo đầy tớ làm gì? (Ma-thi-ơ 13:30)',
 '["Để cả hai cùng lớn lên đến mùa gặt","Nhổ cỏ lùng ngay","Gieo thêm lúa mì","Bỏ ruộng đó"]',
 '[0]',
 'Ma-thi-ơ 13:30 — "Hãy để cho cả hai thứ cùng lớn lên cho đến mùa gặt."',
 '["Ma-thi-ơ","Ví dụ","Cỏ lùng"]', 'BTT 1926', 'vi','ACTIVE', 0, 1, NOW(), NOW()),

('bq-mat-071', 'Matthew', 13, 45, 46, 'hard', 'multiple_choice_single',
 'Người lái buôn tìm được viên ngọc quý đã làm gì? (Ma-thi-ơ 13:46)',
 '["Giấu nó đi","Bán hết gia tài mà mua","Cho người khác","Mang về cho vua"]',
 '[1]',
 'Ma-thi-ơ 13:46 — "Khi đã tìm được một hột châu quý giá, thì đi bán hết gia tài mình mà mua hột châu đó."',
 '["Ma-thi-ơ","Ví dụ","Ngọc quý"]', 'BTT 1926', 'vi','ACTIVE', 0, 1, NOW(), NOW()),

('bq-mat-072', 'Matthew', 16, 18, 18, 'hard', 'multiple_choice_single',
 'Chúa Jêsus nói sẽ lập Hội thánh trên nền nào? (Ma-thi-ơ 16:18)',
 '["Trên đá nầy","Trên đất","Trên cát","Trên núi Si-ôn"]',
 '[0]',
 'Ma-thi-ơ 16:18 — "Còn ta, ta bảo ngươi rằng: Ngươi là Phi-e-rơ, ta sẽ lập Hội thánh ta trên đá nầy."',
 '["Ma-thi-ơ","Hội thánh","Phi-e-rơ"]', 'BTT 1926', 'vi','ACTIVE', 0, 1, NOW(), NOW()),

('bq-mat-073', 'Matthew', 18, 3, 3, 'hard', 'multiple_choice_single',
 'Chúa Jêsus nói nếu không đổi lại, phải trở nên như ai để vào nước thiên đàng? (Ma-thi-ơ 18:3)',
 '["Như thiên sứ","Như tiên tri","Như thầy tế lễ","Như con trẻ"]',
 '[3]',
 'Ma-thi-ơ 18:3 — "Quả thật, ta nói cùng các ngươi, nếu các ngươi không đổi lại và nên như đứa trẻ, thì chẳng được vào nước thiên đàng đâu."',
 '["Ma-thi-ơ","Nước thiên đàng","Con trẻ"]', 'BTT 1926', 'vi','ACTIVE', 0, 1, NOW(), NOW()),

('bq-mat-074', 'Matthew', 19, 24, 24, 'hard', 'multiple_choice_single',
 'Chúa Jêsus so sánh người giàu vào nước Đức Chúa Trời khó hơn con gì chui qua lỗ kim? (Ma-thi-ơ 19:24)',
 '["Con lạc đà","Con lừa","Con bò","Con voi"]',
 '[0]',
 'Ma-thi-ơ 19:24 — "Con lạc đà chui qua lỗ kim còn dễ hơn người giàu vào nước Đức Chúa Trời."',
 '["Ma-thi-ơ","Sự giàu có","Nước Trời"]', 'BTT 1926', 'vi','ACTIVE', 0, 1, NOW(), NOW()),

('bq-mat-075', 'Matthew', 21, 12, 13, 'hard', 'multiple_choice_single',
 'Chúa Jêsus nói đền thờ phải gọi là gì, chứ không phải ổ trộm cướp? (Ma-thi-ơ 21:13)',
 '["Nhà vua","Nơi thánh","Nơi hiến tế","Nhà cầu nguyện"]',
 '[3]',
 'Ma-thi-ơ 21:13 — "Nhà ta sẽ gọi là nhà cầu nguyện; nhưng các ngươi đã làm thành cái ổ trộm cướp."',
 '["Ma-thi-ơ","Đền thờ","Thanh tẩy"]', 'BTT 1926', 'vi','ACTIVE', 0, 1, NOW(), NOW()),

('bq-mat-076', 'Matthew', 22, 21, 21, 'hard', 'multiple_choice_single',
 'Chúa Jêsus nói gì khi được hỏi về nộp thuế cho Sê-sa? (Ma-thi-ơ 22:21)',
 '["Hãy trả cho Sê-sa vật gì của Sê-sa","Đừng nộp thuế","Thuế là không công bằng","Hãy nộp gấp đôi"]',
 '[0]',
 'Ma-thi-ơ 22:21 — "Hãy trả cho Sê-sa vật gì của Sê-sa; và trả cho Đức Chúa Trời vật gì của Đức Chúa Trời."',
 '["Ma-thi-ơ","Thuế","Sê-sa"]', 'BTT 1926', 'vi','ACTIVE', 0, 1, NOW(), NOW()),

('bq-mat-077', 'Matthew', 24, 36, 36, 'hard', 'multiple_choice_single',
 'Ai biết ngày và giờ Chúa Jêsus trở lại? (Ma-thi-ơ 24:36)',
 '["Chỉ một mình Cha biết","Con người","Các thiên sứ","Các tiên tri"]',
 '[0]',
 'Ma-thi-ơ 24:36 — "Về ngày và giờ đó, chẳng có ai biết chi cả, thiên sứ trên trời hay là Con cũng vậy, song chỉ một mình Cha biết mà thôi."',
 '["Ma-thi-ơ","Tái lâm","Ngày giờ"]', 'BTT 1926', 'vi','ACTIVE', 0, 1, NOW(), NOW()),

('bq-mat-078', 'Matthew', 25, 31, 33, 'hard', 'multiple_choice_single',
 'Khi Con người phán xét, Ngài để chiên bên nào và dê bên nào? (Ma-thi-ơ 25:33)',
 '["Chiên bên hữu, dê bên tả","Chiên bên tả, dê bên hữu","Chiên phía trước, dê phía sau","Lẫn lộn"]',
 '[0]',
 'Ma-thi-ơ 25:33 — "Để chiên ở bên hữu và dê ở bên tả."',
 '["Ma-thi-ơ","Phán xét","Chiên và dê"]', 'BTT 1926', 'vi','ACTIVE', 0, 1, NOW(), NOW()),

('bq-mat-079', 'Matthew', 26, 26, 28, 'hard', 'multiple_choice_single',
 'Trong tiệc thánh, Chúa Jêsus nói chén rượu tượng trưng cho điều gì? (Ma-thi-ơ 26:28)',
 '["Nước sự sống","Sự vui mừng","Huyết của giao ước mới","Phước lành"]',
 '[2]',
 'Ma-thi-ơ 26:28 — "Vì nầy là huyết ta, huyết của sự giao ước đã đổ ra cho nhiều người được tha tội."',
 '["Ma-thi-ơ","Tiệc thánh","Giao ước"]', 'BTT 1926', 'vi','ACTIVE', 0, 1, NOW(), NOW()),

('bq-mat-080', 'Matthew', 28, 20, 20, 'hard', 'multiple_choice_single',
 'Chúa Jêsus hứa ở cùng các môn đồ đến bao giờ? (Ma-thi-ơ 28:20)',
 '["Đến cuối năm","Đến khi họ qua đời","Đến khi Ngài trở lại","Đến tận thế"]',
 '[3]',
 'Ma-thi-ơ 28:20 — "Và nầy, ta thường ở cùng các ngươi luôn cho đến tận thế."',
 '["Ma-thi-ơ","Đại mạng lệnh","Lời hứa"]', 'BTT 1926', 'vi','ACTIVE', 0, 1, NOW(), NOW());
