-- Romans (Rô-ma) seed data: 60 questions (25 easy, 22 medium, 13 hard)
-- Source: Kinh Thánh Bản Truyền Thống 1926 (public domain)

INSERT IGNORE INTO questions (
  id, book, chapter, verse_start, verse_end,
  difficulty, type, content, options, correct_answer,
  explanation, tags, source, language, review_status, approvals_count, is_active,
  created_at, updated_at
) VALUES

-- ═══════════════════════════════════════════════════════════════
-- EASY (25 questions)
-- ═══════════════════════════════════════════════════════════════

('bq-rom-001', 'Romans', 1, 16, 16, 'easy', 'multiple_choice_single',
 'Theo Rô-ma 1:16, Tin Lành là gì?',
 '["Luật pháp của Đức Chúa Trời","Quyền phép của Đức Chúa Trời để cứu mọi kẻ tin","Lời phán xét","Lịch sử dân Y-sơ-ra-ên"]',
 '[1]',
 'Rô-ma 1:16 — "Thật vậy, tôi không hổ thẹn về Tin Lành đâu, vì là quyền phép của Đức Chúa Trời để cứu mọi kẻ tin."',
 '["Rô-ma","Tin Lành","Quyền phép"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-rom-002', 'Romans', 3, 23, 23, 'easy', 'multiple_choice_single',
 'Theo Rô-ma 3:23, ai đã phạm tội?',
 '["Chỉ dân ngoại","Chỉ người Giu-đa","Mọi người, vì mọi người đều đã phạm tội","Chỉ người lớn"]',
 '[2]',
 'Rô-ma 3:23 — "Vì mọi người đều đã phạm tội, thiếu mất sự vinh hiển của Đức Chúa Trời."',
 '["Rô-ma","Tội lỗi","Mọi người"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-rom-003', 'Romans', 5, 8, 8, 'easy', 'multiple_choice_single',
 'Theo Rô-ma 5:8, Đức Chúa Trời tỏ lòng yêu thương khi nào?',
 '["Khi chúng ta vâng phục","Khi chúng ta cầu nguyện","Khi chúng ta còn là người có tội","Khi chúng ta làm lành"]',
 '[2]',
 'Rô-ma 5:8 — "Nhưng Đức Chúa Trời tỏ lòng yêu thương Ngài đối với chúng ta, khi chúng ta còn là người có tội, thì Đấng Christ vì chúng ta chịu chết."',
 '["Rô-ma","Tình yêu","Đấng Christ chịu chết"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-rom-004', 'Romans', 6, 23, 23, 'easy', 'multiple_choice_single',
 'Theo Rô-ma 6:23, tiền công của tội lỗi là gì?',
 '["Sự nghèo khổ","Sự chết","Sự đau khổ","Sự cô đơn"]',
 '[1]',
 'Rô-ma 6:23 — "Vì tiền công của tội lỗi là sự chết; nhưng sự ban cho của Đức Chúa Trời là sự sống đời đời trong Đức Chúa Jêsus Christ, Chúa chúng ta."',
 '["Rô-ma","Tội lỗi","Sự chết","Sự sống"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-rom-005', 'Romans', 6, 23, 23, 'easy', 'multiple_choice_single',
 'Theo Rô-ma 6:23, sự ban cho của Đức Chúa Trời là gì?',
 '["Sự giàu có","Sự khôn ngoan","Sự sống đời đời","Quyền lực"]',
 '[2]',
 'Rô-ma 6:23 — "Nhưng sự ban cho của Đức Chúa Trời là sự sống đời đời trong Đức Chúa Jêsus Christ, Chúa chúng ta."',
 '["Rô-ma","Sự ban cho","Sự sống đời đời"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-rom-006', 'Romans', 8, 1, 1, 'easy', 'multiple_choice_single',
 'Theo Rô-ma 8:1, có sự đoán phạt nào cho ai ở trong Đấng Christ không?',
 '["Có sự đoán phạt nhỏ","Chẳng còn có sự đoán phạt nào","Có sự đoán phạt tạm thời","Tùy trường hợp"]',
 '[1]',
 'Rô-ma 8:1 — "Cho nên hiện nay chẳng còn có sự đoán phạt nào cho những kẻ ở trong Đức Chúa Jêsus Christ."',
 '["Rô-ma","Không đoán phạt","Trong Đấng Christ"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-rom-007', 'Romans', 8, 28, 28, 'easy', 'multiple_choice_single',
 'Theo Rô-ma 8:28, mọi sự hiệp lại làm ích cho ai?',
 '["Cho mọi người","Cho kẻ yêu mến Đức Chúa Trời","Cho người giàu","Cho người Giu-đa"]',
 '[1]',
 'Rô-ma 8:28 — "Vả, chúng ta biết rằng mọi sự hiệp lại làm ích cho kẻ yêu mến Đức Chúa Trời."',
 '["Rô-ma","Mọi sự hiệp lại","Yêu mến Chúa"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-rom-008', 'Romans', 8, 31, 31, 'easy', 'multiple_choice_single',
 'Theo Rô-ma 8:31, nếu Đức Chúa Trời vùa giúp chúng ta, thì ai sẽ nghịch cùng chúng ta?',
 '["Sa-tan","Thế gian","Không ai nghịch được","Nhiều người"]',
 '[2]',
 'Rô-ma 8:31 — "Đức Chúa Trời đã vùa giúp chúng ta, thì còn ai nghịch với chúng ta?"',
 '["Rô-ma","Chúa vùa giúp","Chiến thắng"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-rom-009', 'Romans', 10, 9, 9, 'easy', 'multiple_choice_single',
 'Theo Rô-ma 10:9, phải làm gì để được cứu?',
 '["Làm nhiều việc lành","Miệng xưng Chúa Jêsus và lòng tin Đức Chúa Trời khiến Ngài sống lại","Giữ luật pháp","Dâng hiến nhiều"]',
 '[1]',
 'Rô-ma 10:9 — "Vậy nếu miệng ngươi xưng Đức Chúa Jêsus ra và lòng ngươi tin rằng Đức Chúa Trời đã khiến Ngài từ kẻ chết sống lại, thì ngươi sẽ được cứu."',
 '["Rô-ma","Xưng nhận","Được cứu"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-rom-010', 'Romans', 10, 17, 17, 'easy', 'multiple_choice_single',
 'Theo Rô-ma 10:17, đức tin đến từ đâu?',
 '["Từ việc làm lành","Từ sự nghe, và nghe bởi lời Đấng Christ","Từ sự suy gẫm","Từ sự kiêng ăn"]',
 '[1]',
 'Rô-ma 10:17 — "Như vậy, đức tin đến bởi sự người ta nghe, mà người ta nghe, là khi lời của Đấng Christ được rao giảng."',
 '["Rô-ma","Đức tin","Nghe Lời"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-rom-011', 'Romans', 12, 1, 1, 'easy', 'multiple_choice_single',
 'Theo Rô-ma 12:1, Phao-lô khuyên tín đồ dâng thân thể mình như thế nào?',
 '["Như một của lễ sống và thánh","Như một nô lệ","Như một chiến sĩ","Như một người đầy tớ"]',
 '[0]',
 'Rô-ma 12:1 — "Hãy dâng thân thể mình làm của lễ sống và thánh, đẹp lòng Đức Chúa Trời, ấy là sự thờ phượng phải lẽ của anh em."',
 '["Rô-ma","Của lễ sống","Thờ phượng"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-rom-012', 'Romans', 12, 2, 2, 'easy', 'multiple_choice_single',
 'Theo Rô-ma 12:2, chúng ta không nên làm gì?',
 '["Không nên cầu nguyện","Đừng làm theo đời nầy","Không nên đi nhà thờ","Không nên đọc sách"]',
 '[1]',
 'Rô-ma 12:2 — "Đừng làm theo đời nầy, nhưng hãy biến hóa bởi sự đổi mới của tâm thần mình."',
 '["Rô-ma","Biến hóa","Tâm thần"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-rom-013', 'Romans', 8, 38, 39, 'easy', 'multiple_choice_single',
 'Theo Rô-ma 8:38-39, điều gì có thể phân rẽ chúng ta khỏi sự yêu thương của Đức Chúa Trời?',
 '["Sự chết","Thiên sứ","Không có gì có thể phân rẽ","Quyền thế"]',
 '[2]',
 'Rô-ma 8:38-39 — "Tôi chắc rằng bất kỳ sự chết, sự sống, các thiên sứ... không có thể phân rẽ chúng ta khỏi sự yêu thương mà Đức Chúa Trời đã chứng cho chúng ta trong Đức Chúa Jêsus Christ."',
 '["Rô-ma","Tình yêu Chúa","Không phân rẽ"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-rom-014', 'Romans', 1, 1, 1, 'easy', 'multiple_choice_single',
 'Ai là tác giả thư Rô-ma? (Rô-ma 1:1)',
 '["Phi-e-rơ","Phao-lô","Giăng","Gia-cơ"]',
 '[1]',
 'Rô-ma 1:1 — "Phao-lô, tôi tớ Đức Chúa Jêsus Christ, được gọi làm sứ đồ, để riêng ra đặng giảng Tin Lành Đức Chúa Trời."',
 '["Rô-ma","Phao-lô","Tác giả"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-rom-015', 'Romans', 3, 10, 10, 'easy', 'multiple_choice_single',
 'Theo Rô-ma 3:10, có bao nhiêu người công bình?',
 '["Nhiều người","Một vài người","Chẳng có một người công bình nào, dẫu một người cũng không","Mười người"]',
 '[2]',
 'Rô-ma 3:10 — "Chẳng có một người công bình nào hết, dẫu một người cũng không."',
 '["Rô-ma","Công bình","Tội lỗi"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-rom-016', 'Romans', 5, 1, 1, 'easy', 'multiple_choice_single',
 'Theo Rô-ma 5:1, nhờ đức tin chúng ta được gì với Đức Chúa Trời?',
 '["Sự giàu có","Hòa thuận với Đức Chúa Trời","Quyền lực","Sự khôn ngoan"]',
 '[1]',
 'Rô-ma 5:1 — "Vậy chúng ta đã được xưng công bình bởi đức tin, thì được hòa thuận với Đức Chúa Trời, bởi Đức Chúa Jêsus Christ chúng ta."',
 '["Rô-ma","Xưng công bình","Hòa thuận"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-rom-017', 'Romans', 13, 1, 1, 'easy', 'multiple_choice_single',
 'Theo Rô-ma 13:1, mọi quyền phép đều đến từ đâu?',
 '["Từ loài người","Từ Đức Chúa Trời","Từ chính phủ","Từ quân đội"]',
 '[1]',
 'Rô-ma 13:1 — "Mọi người phải vâng phục các đấng cầm quyền trên mình; vì chẳng có quyền nào mà không đến bởi Đức Chúa Trời."',
 '["Rô-ma","Quyền phép","Vâng phục"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-rom-018', 'Romans', 12, 21, 21, 'easy', 'multiple_choice_single',
 'Theo Rô-ma 12:21, chúng ta nên thắng điều ác bằng cách nào?',
 '["Bằng sức mạnh","Bằng điều lành","Bằng sự trả thù","Bằng luật pháp"]',
 '[1]',
 'Rô-ma 12:21 — "Đừng để điều ác thắng mình, nhưng hãy lấy điều lành thắng điều ác."',
 '["Rô-ma","Thắng điều ác","Điều lành"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-rom-019', 'Romans', 10, 13, 13, 'easy', 'multiple_choice_single',
 'Theo Rô-ma 10:13, ai sẽ được cứu?',
 '["Người giữ luật pháp","Người dâng hiến nhiều","Ai kêu cầu danh Chúa","Người Do Thái"]',
 '[2]',
 'Rô-ma 10:13 — "Vì ai kêu cầu danh Chúa thì sẽ được cứu."',
 '["Rô-ma","Kêu cầu","Được cứu"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-rom-020', 'Romans', 12, 12, 12, 'easy', 'multiple_choice_single',
 'Theo Rô-ma 12:12, Phao-lô khuyên chúng ta điều gì?',
 '["Hãy vui mừng trong sự trông cậy, nhịn nhục trong hoạn nạn, bền lòng mà cầu nguyện","Hãy giàu có và thành công","Hãy du lịch khắp nơi","Hãy xây nhà lớn"]',
 '[0]',
 'Rô-ma 12:12 — "Hãy vui mừng trong sự trông cậy, nhịn nhục trong sự hoạn nạn, bền lòng mà cầu nguyện."',
 '["Rô-ma","Vui mừng","Cầu nguyện"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-rom-021', 'Romans', 8, 14, 14, 'easy', 'multiple_choice_single',
 'Theo Rô-ma 8:14, ai được gọi là con của Đức Chúa Trời?',
 '["Người giữ luật pháp","Người được Thánh Linh dẫn dắt","Người giàu có","Người Do Thái"]',
 '[1]',
 'Rô-ma 8:14 — "Vì hết thảy kẻ nào được Thánh Linh của Đức Chúa Trời dắt dẫn, đều là con của Đức Chúa Trời."',
 '["Rô-ma","Con Đức Chúa Trời","Thánh Linh"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-rom-022', 'Romans', 15, 13, 13, 'easy', 'multiple_choice_single',
 'Theo Rô-ma 15:13, Đức Chúa Trời được gọi là Đức Chúa Trời của điều gì?',
 '["Sự phán xét","Sự trông cậy","Chiến thắng","Sự giàu có"]',
 '[1]',
 'Rô-ma 15:13 — "Xin Đức Chúa Trời của sự trông cậy, làm cho anh em đầy dẫy mọi điều vui vẻ và mọi điều bình an."',
 '["Rô-ma","Trông cậy","Vui vẻ bình an"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-rom-023', 'Romans', 1, 17, 17, 'easy', 'multiple_choice_single',
 'Theo Rô-ma 1:17, người công bình sống bằng gì?',
 '["Bằng luật pháp","Bằng đức tin","Bằng việc làm","Bằng sự khôn ngoan"]',
 '[1]',
 'Rô-ma 1:17 — "Như có chép rằng: Người công bình sẽ sống bởi đức tin."',
 '["Rô-ma","Đức tin","Công bình"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-rom-024', 'Romans', 6, 4, 4, 'easy', 'multiple_choice_single',
 'Theo Rô-ma 6:4, phép báp-tem tượng trưng cho điều gì?',
 '["Sự rửa sạch","Chôn và sống lại với Đấng Christ","Sự thanh tẩy","Sự gia nhập hội thánh"]',
 '[1]',
 'Rô-ma 6:4 — "Vậy chúng ta đã bị chôn với Ngài bởi phép báp-tem trong sự chết Ngài, hầu cho Đấng Christ nhờ vinh hiển của Cha được từ kẻ chết sống lại thể nào, thì chúng ta cũng sống trong đời mới thể ấy."',
 '["Rô-ma","Phép báp-tem","Sống lại"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-rom-025', 'Romans', 13, 10, 10, 'easy', 'multiple_choice_single',
 'Theo Rô-ma 13:10, sự yêu thương là gì đối với luật pháp?',
 '["Vi phạm luật pháp","Sự làm trọn luật pháp","Thay thế luật pháp","Bỏ qua luật pháp"]',
 '[1]',
 'Rô-ma 13:10 — "Sự yêu thương chẳng hề làm hại kẻ lân cận; vậy yêu thương là sự làm trọn luật pháp."',
 '["Rô-ma","Yêu thương","Luật pháp"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

-- ═══════════════════════════════════════════════════════════════
-- MEDIUM (22 questions)
-- ═══════════════════════════════════════════════════════════════

('bq-rom-026', 'Romans', 1, 20, 20, 'medium', 'multiple_choice_single',
 'Theo Rô-ma 1:20, phẩm tính không thấy được của Đức Chúa Trời nhờ đâu mà nhận biết? (Rô-ma 1:20)',
 '["Nhờ Kinh Thánh","Nhờ các tiên tri","Nhờ vật dựng nên mà nhận biết","Nhờ phép lạ"]',
 '[2]',
 'Rô-ma 1:20 — "Bởi những sự trọn lành của Ngài mắt không thấy được... thì từ buổi sáng thế, vẫn sờ soạng nhận biết được nhờ những vật Ngài đã làm ra."',
 '["Rô-ma","Thiên nhiên","Nhận biết Chúa"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-rom-027', 'Romans', 2, 11, 11, 'medium', 'multiple_choice_single',
 'Theo Rô-ma 2:11, Đức Chúa Trời có thiên vị không?',
 '["Có, Ngài thiên vị người Do Thái","Đức Chúa Trời chẳng hề vị nể ai","Có, Ngài thiên vị người giàu","Tùy trường hợp"]',
 '[1]',
 'Rô-ma 2:11 — "Vì trước mặt Đức Chúa Trời, chẳng hề có sự tây vị ai."',
 '["Rô-ma","Công bình","Không thiên vị"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-rom-028', 'Romans', 3, 24, 24, 'medium', 'multiple_choice_single',
 'Theo Rô-ma 3:24, chúng ta được xưng công bình nhờ điều gì?',
 '["Nhờ việc làm","Nhờ ân điển Ngài ban không, bởi sự chuộc tội trong Đấng Christ","Nhờ giữ luật pháp","Nhờ dâng hiến"]',
 '[1]',
 'Rô-ma 3:24 — "Nhưng nhờ ân điển Ngài mà được xưng công bình nhưng không, bởi sự chuộc tội đã làm trọn trong Đức Chúa Jêsus Christ."',
 '["Rô-ma","Ân điển","Xưng công bình"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-rom-029', 'Romans', 4, 3, 3, 'medium', 'multiple_choice_single',
 'Theo Rô-ma 4:3, Áp-ra-ham được kể là công bình nhờ điều gì?',
 '["Nhờ dâng Y-sác","Áp-ra-ham tin Đức Chúa Trời, và điều đó kể là công bình cho người","Nhờ cắt bì","Nhờ giữ luật pháp"]',
 '[1]',
 'Rô-ma 4:3 — "Áp-ra-ham tin Đức Chúa Trời, và điều đó kể là công bình cho người."',
 '["Rô-ma","Áp-ra-ham","Đức tin"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-rom-030', 'Romans', 5, 3, 4, 'medium', 'multiple_choice_single',
 'Theo Rô-ma 5:3-4, hoạn nạn sinh ra điều gì?',
 '["Sự tức giận","Sự nhịn nhục","Sự chán nản","Sự oán hận"]',
 '[1]',
 'Rô-ma 5:3-4 — "Hoạn nạn sanh sự nhịn nhục, sự nhịn nhục sanh sự rèn tập, sự rèn tập sanh sự trông cậy."',
 '["Rô-ma","Hoạn nạn","Nhịn nhục"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-rom-031', 'Romans', 5, 12, 12, 'medium', 'multiple_choice_single',
 'Theo Rô-ma 5:12, tội lỗi vào thế gian qua một người, người đó là ai?',
 '["Ê-va","A-đam","Ca-in","Sa-tan"]',
 '[1]',
 'Rô-ma 5:12 — "Cho nên, như bởi một người mà tội lỗi vào trong thế gian, lại bởi tội lỗi mà có sự chết."',
 '["Rô-ma","A-đam","Tội lỗi nguyên thủy"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-rom-032', 'Romans', 6, 6, 6, 'medium', 'multiple_choice_single',
 'Theo Rô-ma 6:6, người cũ của chúng ta đã bị gì?',
 '["Bị thay đổi","Bị đóng đinh trên thập tự giá với Đấng Christ","Bị đuổi đi","Bị giấu đi"]',
 '[1]',
 'Rô-ma 6:6 — "Vì biết rằng người cũ của chúng ta đã bị đóng đinh trên thập tự giá với Ngài, hầu cho thân thể của tội lỗi bị tiêu diệt đi."',
 '["Rô-ma","Người cũ","Đóng đinh"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-rom-033', 'Romans', 7, 19, 19, 'medium', 'multiple_choice_single',
 'Phao-lô thú nhận điều gì trong Rô-ma 7:19?',
 '["Ông làm điều lành","Điều lành ông muốn thì không làm, còn điều dữ không muốn thì lại làm","Ông luôn vâng phục","Ông không bao giờ phạm tội"]',
 '[1]',
 'Rô-ma 7:19 — "Vì tôi không làm điều lành mình muốn, nhưng làm điều dữ mình không muốn."',
 '["Rô-ma","Xung đột nội tâm","Tội lỗi"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-rom-034', 'Romans', 8, 15, 15, 'medium', 'multiple_choice_single',
 'Theo Rô-ma 8:15, Thánh Linh cho chúng ta kêu Đức Chúa Trời bằng danh xưng gì?',
 '["Đức Chúa Trời","A-ba, Cha!","Đấng Toàn Năng","Chúa các chúa"]',
 '[1]',
 'Rô-ma 8:15 — "Bởi Thánh Linh đó, chúng ta kêu rằng: A-ba! Cha!"',
 '["Rô-ma","A-ba Cha","Thánh Linh"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-rom-035', 'Romans', 8, 26, 26, 'medium', 'multiple_choice_single',
 'Theo Rô-ma 8:26, Thánh Linh giúp chúng ta trong điều gì?',
 '["Trong sự làm việc","Giúp cho sự yếu đuối, cầu thay cho chúng ta","Trong sự học hỏi","Trong sự giàu có"]',
 '[1]',
 'Rô-ma 8:26 — "Cũng một lẽ ấy, Đức Thánh Linh giúp cho sự yếu đuối của chúng ta. Vì chúng ta chẳng biết sự gì mình phải xin đặng cầu nguyện cho xứng đáng; nhưng chính Đức Thánh Linh lấy sự thở than không thể nói ra được mà cầu khẩn thay cho chúng ta."',
 '["Rô-ma","Thánh Linh cầu thay","Yếu đuối"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-rom-036', 'Romans', 9, 21, 21, 'medium', 'multiple_choice_single',
 'Phao-lô dùng hình ảnh gì để minh họa quyền tối thượng của Đức Chúa Trời? (Rô-ma 9:21)',
 '["Người chăn và chiên","Thợ gốm và đất sét","Vua và dân","Thầy và trò"]',
 '[1]',
 'Rô-ma 9:21 — "Người thợ gốm há chẳng có quyền trên đất sét sao, cùng một đống mà làm ra hạng bình để dùng việc sang trọng, lại hạng khác để dùng việc hèn hạ?"',
 '["Rô-ma","Thợ gốm","Quyền tối thượng"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-rom-037', 'Romans', 11, 33, 33, 'medium', 'multiple_choice_single',
 'Phao-lô ca ngợi điều gì của Đức Chúa Trời trong Rô-ma 11:33?',
 '["Quyền năng","Sự giàu có, khôn ngoan và thông biết dò xét không thấu","Sự công bình","Sự nhân từ"]',
 '[1]',
 'Rô-ma 11:33 — "Ôi! sâu nhiệm thay là sự giàu có, khôn ngoan và thông biết của Đức Chúa Trời! Sự phán xét của Ngài nào ai thấu được, đường nẻo của Ngài nào ai hiểu được!"',
 '["Rô-ma","Sâu nhiệm","Khôn ngoan"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-rom-038', 'Romans', 12, 9, 9, 'medium', 'multiple_choice_single',
 'Theo Rô-ma 12:9, lòng yêu thương phải như thế nào?',
 '["Phải có điều kiện","Phải thật, không giả dối","Phải có giới hạn","Chỉ dành cho người thân"]',
 '[1]',
 'Rô-ma 12:9 — "Lòng yêu thương phải cho thật, hãy gớm sự dữ mà mến sự lành."',
 '["Rô-ma","Yêu thương thật","Ghét sự dữ"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-rom-039', 'Romans', 12, 19, 19, 'medium', 'multiple_choice_single',
 'Theo Rô-ma 12:19, ai có quyền báo thù?',
 '["Mỗi người tự báo thù","Sự trả thù thuộc về Chúa","Chính phủ","Không ai cả"]',
 '[1]',
 'Rô-ma 12:19 — "Hỡi kẻ rất yêu dấu của tôi ơi, chính mình chớ trả thù ai, nhưng hãy nhường cho cơn thạnh nộ của Đức Chúa Trời; vì có chép lời Chúa phán rằng: Sự trả thù thuộc về ta."',
 '["Rô-ma","Trả thù","Nhường cho Chúa"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-rom-040', 'Romans', 13, 8, 8, 'medium', 'multiple_choice_single',
 'Theo Rô-ma 13:8, chúng ta chỉ nên mắc nợ nhau điều gì?',
 '["Tiền bạc","Sự yêu thương nhau","Sự vâng phục","Sự giúp đỡ"]',
 '[1]',
 'Rô-ma 13:8 — "Đừng mắc nợ ai chi hết, chỉ mắc nợ về sự yêu thương nhau mà thôi."',
 '["Rô-ma","Mắc nợ","Yêu thương"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-rom-041', 'Romans', 14, 8, 8, 'medium', 'multiple_choice_single',
 'Theo Rô-ma 14:8, dù sống hay chết, chúng ta thuộc về ai?',
 '["Thuộc về chính mình","Thuộc về Chúa","Thuộc về gia đình","Thuộc về hội thánh"]',
 '[1]',
 'Rô-ma 14:8 — "Vì nếu chúng ta sống, là sống cho Chúa, và nếu chúng ta chết, là chết cho Chúa. Vậy nên chúng ta hoặc sống hoặc chết, đều thuộc về Chúa cả."',
 '["Rô-ma","Thuộc về Chúa","Sống và chết"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-rom-042', 'Romans', 14, 13, 13, 'medium', 'multiple_choice_single',
 'Theo Rô-ma 14:13, Phao-lô khuyên chúng ta đừng làm gì với anh em?',
 '["Đừng cạnh tranh","Đừng xét đoán nhau và đặt hòn đá vấp ngã","Đừng nói chuyện","Đừng gặp nhau"]',
 '[1]',
 'Rô-ma 14:13 — "Vậy chúng ta chớ xét đoán nhau; nhưng thà nhứt định đừng để hòn đá vấp ngã hoặc gây cớ phạm tội cho anh em mình."',
 '["Rô-ma","Xét đoán","Anh em yếu"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-rom-043', 'Romans', 15, 4, 4, 'medium', 'multiple_choice_single',
 'Theo Rô-ma 15:4, Kinh Thánh được viết để làm gì?',
 '["Để giải trí","Để dạy dỗ chúng ta, để nhờ sự nhịn nhục và an ủi mà có sự trông cậy","Để phán xét","Để ghi lại lịch sử"]',
 '[1]',
 'Rô-ma 15:4 — "Vả, mọi sự đã chép từ xưa đều để dạy dỗ chúng ta, hầu cho chúng ta nhờ sự nhịn nhục và sự yên ủi của Kinh Thánh mà có sự trông cậy."',
 '["Rô-ma","Kinh Thánh","Dạy dỗ"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-rom-044', 'Romans', 8, 17, 17, 'medium', 'multiple_choice_single',
 'Theo Rô-ma 8:17, nếu chúng ta là con cái Đức Chúa Trời, thì chúng ta cũng là gì?',
 '["Tôi tớ Ngài","Kẻ thừa kế của Đức Chúa Trời, và đồng kế tự với Đấng Christ","Bạn hữu Ngài","Thiên sứ"]',
 '[1]',
 'Rô-ma 8:17 — "Lại nếu chúng ta là con cái, thì cũng là kẻ kế tự, kế tự Đức Chúa Trời và đồng kế tự với Đấng Christ."',
 '["Rô-ma","Kế tự","Đồng kế tự"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-rom-045', 'Romans', 11, 26, 26, 'medium', 'multiple_choice_single',
 'Theo Rô-ma 11:26, điều gì sẽ xảy ra với cả dân Y-sơ-ra-ên?',
 '["Họ sẽ bị bỏ","Cả dân Y-sơ-ra-ên sẽ được cứu","Họ sẽ bị phân tán","Họ sẽ cai trị"]',
 '[1]',
 'Rô-ma 11:26 — "Vậy thì cả dân Y-sơ-ra-ên sẽ được cứu, như có chép rằng: Đấng Giải cứu sẽ đến từ Si-ôn."',
 '["Rô-ma","Y-sơ-ra-ên","Được cứu"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-rom-046', 'Romans', 12, 4, 5, 'medium', 'multiple_choice_single',
 'Phao-lô dùng hình ảnh gì để mô tả hội thánh trong Rô-ma 12:4-5?',
 '["Một tòa nhà","Một thân thể với nhiều chi thể","Một đội quân","Một gia đình"]',
 '[1]',
 'Rô-ma 12:4-5 — "Vì như trong một thân chúng ta có nhiều chi thể... thì chúng ta cũng vậy, tuy nhiều người, nhưng hiệp nhau làm một thân trong Đấng Christ."',
 '["Rô-ma","Thân thể","Hội thánh"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-rom-047', 'Romans', 13, 11, 12, 'medium', 'multiple_choice_single',
 'Theo Rô-ma 13:12, Phao-lô khuyên chúng ta lấy gì mà mặc vào?',
 '["Áo giáp bạc","Áo sáng láng","Áo của sự công bình","Áo của sự khôn ngoan"]',
 '[1]',
 'Rô-ma 13:12 — "Đêm đã khuya, ngày gần đến; vậy chúng ta hãy lột bỏ những việc tối tăm và mặc lấy áo giáp sáng láng."',
 '["Rô-ma","Áo giáp sáng láng","Tỉnh thức"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

-- ═══════════════════════════════════════════════════════════════
-- HARD (13 questions)
-- ═══════════════════════════════════════════════════════════════

('bq-rom-048', 'Romans', 1, 3, 4, 'hard', 'multiple_choice_single',
 'Theo Rô-ma 1:3-4, Đức Chúa Jêsus Christ theo xác thịt thuộc dòng dõi ai?',
 '["Áp-ra-ham","Đa-vít","Môi-se","A-rôn"]',
 '[1]',
 'Rô-ma 1:3-4 — "Về Con Ngài, theo xác thịt thì bởi dòng dõi vua Đa-vít sanh ra."',
 '["Rô-ma","Dòng dõi Đa-vít","Đấng Christ"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-rom-049', 'Romans', 3, 25, 25, 'hard', 'multiple_choice_single',
 'Theo Rô-ma 3:25, Đức Chúa Trời đã lập Đấng Christ làm gì bởi huyết Ngài?',
 '["Làm Vua","Làm của lễ chuộc tội","Làm thầy tế lễ","Làm tiên tri"]',
 '[1]',
 'Rô-ma 3:25 — "Là Đấng Đức Chúa Trời đã lập làm của lễ chuộc tội, bởi đức tin trong huyết Đấng ấy."',
 '["Rô-ma","Của lễ chuộc tội","Huyết"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-rom-050', 'Romans', 4, 17, 17, 'hard', 'multiple_choice_single',
 'Theo Rô-ma 4:17, Đức Chúa Trời có quyền năng gì?',
 '["Dời núi","Gọi những sự không có như đã có","Dừng mặt trời","Rẽ biển"]',
 '[1]',
 'Rô-ma 4:17 — "Đức Chúa Trời mà người đã tin, tức là Đấng ban sự sống cho kẻ chết và gọi những sự không có như đã có."',
 '["Rô-ma","Quyền năng Chúa","Đức tin"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-rom-051', 'Romans', 5, 17, 17, 'hard', 'multiple_choice_single',
 'Theo Rô-ma 5:17, nếu bởi tội một người mà sự chết cai trị, thì bởi một người khác mà điều gì lại càng hơn?',
 '["Sự giàu có","Ân điển và sự ban cho công bình cai trị trong sự sống","Quyền lực","Sự khôn ngoan"]',
 '[1]',
 'Rô-ma 5:17 — "Nếu bởi tội một người mà sự chết đã cai trị bởi một người ấy, thì huống chi những kẻ nhận ân điển dư dật và sự ban cho của sự công bình, sẽ nhờ một mình Đức Chúa Jêsus Christ mà cai trị trong sự sống, là còn dư dật hơn biết mấy."',
 '["Rô-ma","A-đam và Christ","Ân điển"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-rom-052', 'Romans', 7, 24, 24, 'hard', 'multiple_choice_single',
 'Phao-lô kêu lên điều gì trong Rô-ma 7:24?',
 '["Tôi vui mừng biết bao","Khốn nạn cho tôi! Ai sẽ cứu tôi thoát khỏi thân thể hay chết nầy?","Tôi mạnh mẽ biết bao","Tôi tự do rồi"]',
 '[1]',
 'Rô-ma 7:24 — "Khốn nạn cho tôi! Ai sẽ cứu tôi thoát khỏi thân thể hay chết nầy?"',
 '["Rô-ma","Xung đột nội tâm","Khốn nạn"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-rom-053', 'Romans', 8, 22, 23, 'hard', 'multiple_choice_single',
 'Theo Rô-ma 8:22, muôn vật đang làm gì?',
 '["Vui mừng","Cùng nhau than thở, chịu khó nhọc","Yên nghỉ","Ca ngợi"]',
 '[1]',
 'Rô-ma 8:22 — "Vì chúng ta biết rằng muôn vật đều than thở và chịu khó nhọc cho đến ngày nay."',
 '["Rô-ma","Muôn vật than thở","Chờ đợi"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-rom-054', 'Romans', 8, 29, 29, 'hard', 'multiple_choice_single',
 'Theo Rô-ma 8:29, Đức Chúa Trời đã định sẵn cho chúng ta trở nên giống ai?',
 '["Giống Môi-se","Giống hình bóng Con Ngài","Giống Áp-ra-ham","Giống thiên sứ"]',
 '[1]',
 'Rô-ma 8:29 — "Vì những kẻ Ngài đã biết trước, thì Ngài cũng đã định sẵn để nên giống như hình bóng Con Ngài."',
 '["Rô-ma","Giống Con Ngài","Định sẵn"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-rom-055', 'Romans', 9, 3, 3, 'hard', 'multiple_choice_single',
 'Phao-lô sẵn sàng chịu điều gì vì đồng bào Y-sơ-ra-ên? (Rô-ma 9:3)',
 '["Chịu nghèo khổ","Bị phân cách khỏi Đấng Christ","Chịu tù đày","Chịu mất tài sản"]',
 '[1]',
 'Rô-ma 9:3 — "Vì tôi nguyện vì anh em tôi, là bà con tôi theo phần xác, cho mình lìa khỏi Đấng Christ cũng được."',
 '["Rô-ma","Phao-lô","Hy sinh"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-rom-056', 'Romans', 9, 13, 13, 'hard', 'multiple_choice_single',
 'Đức Chúa Trời phán điều gì về Gia-cốp và Ê-sau trong Rô-ma 9:13?',
 '["Ta yêu cả hai","Ta yêu Gia-cốp và ghét Ê-sau","Ta chọn Ê-sau","Cả hai đều bị bỏ"]',
 '[1]',
 'Rô-ma 9:13 — "Như có chép rằng: Ta yêu Gia-cốp và ghét Ê-sau."',
 '["Rô-ma","Gia-cốp","Ê-sau","Tuyển chọn"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-rom-057', 'Romans', 11, 17, 18, 'hard', 'multiple_choice_single',
 'Phao-lô dùng hình ảnh gì để mô tả dân ngoại được ghép vào Y-sơ-ra-ên? (Rô-ma 11:17)',
 '["Viên gạch xây tường","Nhánh ô-li-ve hoang được ghép vào cây ô-li-ve nhà","Hạt giống trong ruộng","Cá trong lưới"]',
 '[1]',
 'Rô-ma 11:17 — "Nhưng nếu có một vài nhánh đã bị cắt, và ngươi vốn là cây ô-li-ve hoang được tháp vào đó."',
 '["Rô-ma","Ô-li-ve","Dân ngoại"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-rom-058', 'Romans', 11, 36, 36, 'hard', 'multiple_choice_single',
 'Rô-ma 11:36 tuyên bố mọi sự đều ra từ đâu, bởi ai, và vì ai?',
 '["Ra từ thiên nhiên","Muôn vật đều ra từ Ngài, bởi Ngài, và vì Ngài","Ra từ con người","Ra từ vũ trụ"]',
 '[1]',
 'Rô-ma 11:36 — "Vì muôn vật đều là từ Ngài, bởi Ngài, và vì Ngài. Vinh hiển cho Ngài đời đời vô cùng! A-men."',
 '["Rô-ma","Muôn vật","Vinh hiển"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-rom-059', 'Romans', 14, 17, 17, 'hard', 'multiple_choice_single',
 'Theo Rô-ma 14:17, nước Đức Chúa Trời không phải là gì?',
 '["Không phải là sự ăn uống, mà là sự công bình, bình an và vui vẻ trong Đức Thánh Linh","Không phải là quyền lực","Không phải là sự giàu có","Không phải là sự thống trị"]',
 '[0]',
 'Rô-ma 14:17 — "Vì nước Đức Chúa Trời chẳng tại sự ăn uống, nhưng tại sự công bình, bình an, vui vẻ bởi Đức Thánh Linh vậy."',
 '["Rô-ma","Nước Đức Chúa Trời","Công bình"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW()),

('bq-rom-060', 'Romans', 16, 25, 27, 'hard', 'multiple_choice_single',
 'Rô-ma 16:25-27 là lời kết thúc thư Rô-ma với nội dung gì?',
 '["Lời chào hỏi","Lời tụng vinh Đức Chúa Trời","Danh sách người nhận thư","Lời cảnh báo"]',
 '[1]',
 'Rô-ma 16:25,27 — "Đức Chúa Trời có quyền làm cho anh em vững vàng... Nguyện sự vinh hiển về nơi Đức Chúa Trời khôn ngoan có một, bởi Đức Chúa Jêsus Christ, đời đời vô cùng! A-men."',
 '["Rô-ma","Tụng vinh","Kết thúc"]', 'BTT 1926', 'vi', 'ACTIVE', 0, 1, NOW(), NOW());
