-- Insert sample Bible books
INSERT INTO books (id, name, name_vi, testament, order_index) VALUES
('1', 'Genesis', 'Sáng Thế Ký', 'OLD', 1),
('2', 'Exodus', 'Xuất Ê-díp-tô Ký', 'OLD', 2),
('3', 'Leviticus', 'Lê-vi Ký', 'OLD', 3),
('4', 'Numbers', 'Dân Số Ký', 'OLD', 4),
('5', 'Deuteronomy', 'Phục Truyền Luật Lệ Ký', 'OLD', 5),
('6', 'Joshua', 'Giô-suê', 'OLD', 6),
('7', 'Judges', 'Các Quan Xét', 'OLD', 7),
('8', 'Ruth', 'Ru-tơ', 'OLD', 8),
('9', '1 Samuel', '1 Sa-mu-ên', 'OLD', 9),
('10', '2 Samuel', '2 Sa-mu-ên', 'OLD', 10),
('11', '1 Kings', '1 Các Vua', 'OLD', 11),
('12', '2 Kings', '2 Các Vua', 'OLD', 12),
('13', '1 Chronicles', '1 Sử Ký', 'OLD', 13),
('14', '2 Chronicles', '2 Sử Ký', 'OLD', 14),
('15', 'Ezra', 'Ê-xơ-ra', 'OLD', 15),
('16', 'Nehemiah', 'Nê-hê-mi', 'OLD', 16),
('17', 'Esther', 'Ê-xơ-tê', 'OLD', 17),
('18', 'Job', 'Gióp', 'OLD', 18),
('19', 'Psalms', 'Thi Thiên', 'OLD', 19),
('20', 'Proverbs', 'Châm Ngôn', 'OLD', 20),
('21', 'Ecclesiastes', 'Truyền Đạo', 'OLD', 21),
('22', 'Song of Songs', 'Nhã Ca', 'OLD', 22),
('23', 'Isaiah', 'Ê-sai', 'OLD', 23),
('24', 'Jeremiah', 'Giê-rê-mi', 'OLD', 24),
('25', 'Lamentations', 'Ca Thương', 'OLD', 25),
('26', 'Ezekiel', 'Ê-xê-chi-ên', 'OLD', 26),
('27', 'Daniel', 'Đa-ni-ên', 'OLD', 27),
('28', 'Hosea', 'Ô-sê', 'OLD', 28),
('29', 'Joel', 'Giô-ên', 'OLD', 29),
('30', 'Amos', 'A-mốt', 'OLD', 30),
('31', 'Obadiah', 'Áp-đia', 'OLD', 31),
('32', 'Jonah', 'Giô-na', 'OLD', 32),
('33', 'Micah', 'Mi-chê', 'OLD', 33),
('34', 'Nahum', 'Na-hum', 'OLD', 34),
('35', 'Habakkuk', 'Ha-ba-cúc', 'OLD', 35),
('36', 'Zephaniah', 'Sô-phô-ni', 'OLD', 36),
('37', 'Haggai', 'A-ghê', 'OLD', 37),
('38', 'Zechariah', 'Xa-cha-ri', 'OLD', 38),
('39', 'Malachi', 'Ma-la-chi', 'OLD', 39),
('40', 'Matthew', 'Ma-thi-ơ', 'NEW', 40),
('41', 'Mark', 'Mác', 'NEW', 41),
('42', 'Luke', 'Lu-ca', 'NEW', 42),
('43', 'John', 'Giăng', 'NEW', 43),
('44', 'Acts', 'Công Vụ', 'NEW', 44),
('45', 'Romans', 'Rô-ma', 'NEW', 45),
('46', '1 Corinthians', '1 Cô-rinh-tô', 'NEW', 46),
('47', '2 Corinthians', '2 Cô-rinh-tô', 'NEW', 47),
('48', 'Galatians', 'Ga-la-ti', 'NEW', 48),
('49', 'Ephesians', 'Ê-phê-sô', 'NEW', 49),
('50', 'Philippians', 'Phi-líp', 'NEW', 50),
('51', 'Colossians', 'Cô-lô-se', 'NEW', 51),
('52', '1 Thessalonians', '1 Tê-sa-lô-ni-ca', 'NEW', 52),
('53', '2 Thessalonians', '2 Tê-sa-lô-ni-ca', 'NEW', 53),
('54', '1 Timothy', '1 Ti-mô-thê', 'NEW', 54),
('55', '2 Timothy', '2 Ti-mô-thê', 'NEW', 55),
('56', 'Titus', 'Tít', 'NEW', 56),
('57', 'Philemon', 'Phi-lê-môn', 'NEW', 57),
('58', 'Hebrews', 'Hê-bơ-rơ', 'NEW', 58),
('59', 'James', 'Gia-cơ', 'NEW', 59),
('60', '1 Peter', '1 Phi-e-rơ', 'NEW', 60),
('61', '2 Peter', '2 Phi-e-rơ', 'NEW', 61),
('62', '1 John', '1 Giăng', 'NEW', 62),
('63', '2 John', '2 Giăng', 'NEW', 63),
('64', '3 John', '3 Giăng', 'NEW', 64),
('65', 'Jude', 'Giu-đe', 'NEW', 65),
('66', 'Revelation', 'Khải Huyền', 'NEW', 66);

-- Insert sample questions (50 questions)
INSERT INTO questions (id, book, chapter, difficulty, type, content, options, correct_answer, explanation) VALUES
-- Genesis Questions (10 questions)
('1', 'Genesis', 1, 'easy', 'multiple_choice_single', 'Trong Sáng Thế Ký 1:1, Đức Chúa Trời đã làm gì?', JSON_ARRAY('Dựng nên trời và đất', 'Dựng nên con người', 'Phán xét thế gian', 'Lập giao ước với Áp-ra-ham'), 0, 'Sáng Thế Ký 1:1: "Ban đầu Đức Chúa Trời dựng nên trời và đất."'),
('2', 'Genesis', 1, 'easy', 'multiple_choice_single', 'Ngày thứ mấy Đức Chúa Trời tạo ra con người?', JSON_ARRAY('Ngày thứ 5', 'Ngày thứ 6', 'Ngày thứ 7', 'Ngày thứ 8'), 1, 'Sáng Thế Ký 1:26-31: Đức Chúa Trời tạo ra con người vào ngày thứ 6.'),
('3', 'Genesis', 2, 'medium', 'multiple_choice_single', 'Cây nào trong vườn Ê-đen mà Đức Chúa Trời cấm con người ăn?', JSON_ARRAY('Cây sự sống', 'Cây biết điều thiện và điều ác', 'Cây tri thức', 'Cây khôn ngoan'), 1, 'Sáng Thế Ký 2:17: "Nhưng về cây biết điều thiện và điều ác thì chớ hề ăn đến."'),
('4', 'Genesis', 3, 'easy', 'multiple_choice_single', 'Ai đã cám dỗ Ê-va ăn trái cấm?', JSON_ARRAY('Con rắn', 'Con quỷ', 'Thiên sứ sa ngã', 'Con người'), 0, 'Sáng Thế Ký 3:1: "Vả, con rắn là giống quỉ quyệt hơn mọi loài ngoài đồng."'),
('5', 'Genesis', 4, 'medium', 'multiple_choice_single', 'Ca-in đã giết em trai mình là ai?', JSON_ARRAY('A-bên', 'Sết', 'Ê-nót', 'Kê-nan'), 0, 'Sáng Thế Ký 4:8: "Ca-in nói cùng A-bên, em mình, rằng: Chúng ta hãy ra ngoài đồng. Khi hai người đang ở ngoài đồng, Ca-in xông vào A-bên, em mình, và giết đi."'),
('6', 'Genesis', 6, 'easy', 'multiple_choice_single', 'Nô-ê đã đóng tàu để làm gì?', JSON_ARRAY('Đi du lịch', 'Tránh nạn lụt', 'Đánh cá', 'Vận chuyển hàng hóa'), 1, 'Sáng Thế Ký 6:13-14: Đức Chúa Trời bảo Nô-ê đóng tàu để cứu gia đình và các loài động vật khỏi nạn lụt.'),
('7', 'Genesis', 12, 'medium', 'multiple_choice_single', 'Áp-ra-ham được Đức Chúa Trời hứa ban cho điều gì?', JSON_ARRAY('Vàng bạc', 'Đất đai', 'Con cái đông như sao trên trời', 'Sự khôn ngoan'), 2, 'Sáng Thế Ký 15:5: "Đức Giê-hô-va dẫn người ra ngoài, mà phán rằng: Ngươi hãy ngước mắt lên trời, đếm các ngôi sao, nếu đếm được. Ngài lại phán: Dòng dõi ngươi cũng sẽ như vậy."'),
('8', 'Genesis', 22, 'hard', 'multiple_choice_single', 'Áp-ra-ham đã dâng con trai mình là Y-sác lên làm của lễ thiêu ở đâu?', JSON_ARRAY('Núi Mô-ri-a', 'Núi Si-na-i', 'Núi Ô-li-ve', 'Núi Ca-na-an'), 0, 'Sáng Thế Ký 22:2: "Đức Chúa Trời phán: Hãy bắt đứa con một ngươi yêu dấu, là Y-sác, và đi đến xứ Mô-ri-a, nơi đó dâng đứa con làm của lễ thiêu."'),
('9', 'Genesis', 25, 'medium', 'multiple_choice_single', 'Ê-sau và Gia-cốp là con trai của ai?', JSON_ARRAY('Áp-ra-ham', 'Y-sác', 'Gia-cốp', 'Giô-sép'), 1, 'Sáng Thế Ký 25:19-26: "Đây là dòng dõi của Y-sác, con trai Áp-ra-ham... Rê-bê-ca vợ người thọ thai... Hai đứa con trai đang đánh nhau trong lòng mẹ... Đứa ra trước đỏ hồng, lông cùng mình như một áo tơi lông, đặt tên là Ê-sau. Kế em nó ra, tay nắm lấy gót Ê-sau, nên đặt tên là Gia-cốp."'),
('10', 'Genesis', 37, 'easy', 'multiple_choice_single', 'Giô-sép có bao nhiêu anh em?', JSON_ARRAY('10', '11', '12', '13'), 1, 'Sáng Thế Ký 37:2: "Đây là dòng dõi của Gia-cốp. Giô-sép, tuổi mười bảy, đi chăn chiên với các anh em mình." Giô-sép có 11 anh em.'),
-- Exodus Questions (10 questions)
('11', 'Exodus', 3, 'easy', 'multiple_choice_single', 'Môi-se gặp Đức Chúa Trời trong bụi gai cháy ở đâu?', JSON_ARRAY('Núi Si-na-i', 'Núi Hô-rếp', 'Núi Mô-ri-a', 'Núi Ô-li-ve'), 1, 'Xuất Ê-díp-tô Ký 3:1: "Vả, Môi-se chăn bầy chiên của Giê-trô, ông gia mình, là thầy tế lễ xứ Ma-đi-an. Dẫn bầy chiên qua bên kia đồng vắng, đến núi của Đức Chúa Trời, là Hô-rếp."'),
('12', 'Exodus', 4, 'medium', 'multiple_choice_single', 'Đức Chúa Trời đã ban cho Môi-se dấu hiệu gì để chứng minh quyền năng?', JSON_ARRAY('Gậy biến thành rắn', 'Tay biến thành phung', 'Nước biến thành máu', 'Tất cả các dấu hiệu trên'), 3, 'Xuất Ê-díp-tô Ký 4:1-9: Đức Chúa Trời ban cho Môi-se ba dấu hiệu: gậy biến thành rắn, tay biến thành phung, và nước biến thành máu.'),
('13', 'Exodus', 7, 'easy', 'multiple_choice_single', 'Pha-ra-ôn đã từ chối để dân Y-sơ-ra-ên đi thờ phượng Đức Chúa Trời bao nhiêu lần?', JSON_ARRAY('5 lần', '7 lần', '10 lần', '12 lần'), 2, 'Xuất Ê-díp-tô Ký 7-12: Pha-ra-ôn từ chối 10 lần trước khi chịu để dân Y-sơ-ra-ên đi.'),
('14', 'Exodus', 12, 'medium', 'multiple_choice_single', 'Lễ Vượt Qua được tổ chức vào tháng nào?', JSON_ARRAY('Tháng Ni-san', 'Tháng A-đa', 'Tháng Tê-bết', 'Tháng Si-van'), 0, 'Xuất Ê-díp-tô Ký 12:2: "Tháng nầy định làm tháng đầu cho các ngươi, tức là tháng giêng trong quanh năm." Tháng giêng là tháng Ni-san.'),
('15', 'Exodus', 14, 'easy', 'multiple_choice_single', 'Dân Y-sơ-ra-ên đã vượt qua Biển Đỏ như thế nào?', JSON_ARRAY('Bơi qua', 'Đi trên cầu', 'Nước rẽ ra', 'Đi trên thuyền'), 2, 'Xuất Ê-díp-tô Ký 14:21-22: "Môi-se giơ tay lên trên biển, Đức Giê-hô-va dẫn trận gió đông thổi mạnh đến, dồn biển lại trọn đêm; làm cho biển bày ra khô, nước bèn rẽ ra."'),
('16', 'Exodus', 16, 'medium', 'multiple_choice_single', 'Ma-na được ban cho dân Y-sơ-ra-ên trong bao nhiêu năm?', JSON_ARRAY('20 năm', '30 năm', '40 năm', '50 năm'), 2, 'Xuất Ê-díp-tô Ký 16:35: "Dân Y-sơ-ra-ên ăn ma-na trọn bốn mươi năm, cho đến khi vào bờ cõi xứ Ca-na-an."'),
('17', 'Exodus', 20, 'easy', 'multiple_choice_single', 'Mười điều răn được ban cho dân Y-sơ-ra-ên ở đâu?', JSON_ARRAY('Núi Si-na-i', 'Núi Hô-rếp', 'Núi Mô-ri-a', 'Núi Ô-li-ve'), 0, 'Xuất Ê-díp-tô Ký 19:1-20:18: Mười điều răn được ban trên núi Si-na-i.'),
('18', 'Exodus', 32, 'hard', 'multiple_choice_single', 'Khi Môi-se xuống núi và thấy dân chúng thờ lạy bò vàng, ông đã làm gì?', JSON_ARRAY('Cầu nguyện cho họ', 'Phá vỡ hai bảng đá', 'Trở lại núi', 'Trừng phạt họ'), 1, 'Xuất Ê-díp-tô Ký 32:19: "Vừa khi đến gần trại quân, thấy bò con và sự nhảy múa, thì cơn thạnh nộ của Môi-se nổi phừng lên, liền ném bảng đá khỏi tay mình, và làm bể nơi chân núi."'),
('19', 'Exodus', 40, 'medium', 'multiple_choice_single', 'Đền tạm được dựng lên lần đầu tiên vào ngày nào?', JSON_ARRAY('Ngày 1 tháng 1', 'Ngày 1 tháng 2', 'Ngày 1 tháng 3', 'Ngày 1 tháng 4'), 1, 'Xuất Ê-díp-tô Ký 40:17: "Vậy, ngày mồng một tháng giêng năm thứ hai, đền tạm được dựng lên."'),
('20', 'Exodus', 40, 'easy', 'multiple_choice_single', 'Khi đền tạm được dựng xong, điều gì đã xảy ra?', JSON_ARRAY('Động đất', 'Mây bao phủ', 'Lửa từ trời', 'Sấm sét'), 1, 'Xuất Ê-díp-tô Ký 40:34: "Mây bao phủ hội mạc, và sự vinh quang của Đức Giê-hô-va đầy dẫy đền tạm."'),
-- Matthew Questions (10 questions)
('21', 'Matthew', 1, 'easy', 'multiple_choice_single', 'Chúa Giê-su được sinh ra ở đâu?', JSON_ARRAY('Na-xa-rét', 'Bết-lê-hem', 'Giê-ru-sa-lem', 'Ga-li-lê'), 1, 'Ma-thi-ơ 2:1: "Khi Đức Chúa Jêsus đã sanh tại Bết-lê-hem xứ Giu-đê."'),
('22', 'Matthew', 2, 'medium', 'multiple_choice_single', 'Các nhà thông thái từ phương đông đã tìm thấy Chúa Giê-su nhờ điều gì?', JSON_ARRAY('Ngôi sao', 'Thiên sứ', 'Lời tiên tri', 'Giấc mơ'), 0, 'Ma-thi-ơ 2:2: "Các người đó thưa rằng: Vua dân Giu-đa mới sanh hiện ở đâu? Vì chúng ta đã thấy ngôi sao Ngài bên đông, nên đến để thờ lạy Ngài."'),
('23', 'Matthew', 3, 'easy', 'multiple_choice_single', 'Ai đã làm phép báp-tem cho Chúa Giê-su?', JSON_ARRAY('Phi-e-rơ', 'Gioan Báp-tít', 'Anh-rê', 'Gia-cơ'), 1, 'Ma-thi-ơ 3:13: "Khi ấy, Đức Chúa Jêsus từ xứ Ga-li-lê đến cùng Giăng tại sông Giô-đanh, để người làm phép báp-tem cho."'),
('24', 'Matthew', 4, 'medium', 'multiple_choice_single', 'Chúa Giê-su đã bị ma quỷ cám dỗ trong bao nhiêu ngày?', JSON_ARRAY('7 ngày', '21 ngày', '40 ngày', '49 ngày'), 2, 'Ma-thi-ơ 4:2: "Ngài đã kiêng ăn bốn mươi ngày bốn mươi đêm, rồi sau thì đói."'),
('25', 'Matthew', 5, 'easy', 'multiple_choice_single', 'Bài giảng trên núi bắt đầu với câu nào?', JSON_ARRAY('Phước cho những kẻ nghèo khó trong lòng', 'Hãy yêu kẻ thù nghịch', 'Các ngươi là muối của đất', 'Các ngươi là sự sáng của thế gian'), 0, 'Ma-thi-ơ 5:3: "Phước cho những kẻ nghèo khó trong lòng, vì nước thiên đàng là của những kẻ ấy!"'),
('26', 'Matthew', 6, 'medium', 'multiple_choice_single', 'Chúa Giê-su dạy cầu nguyện như thế nào?', JSON_ARRAY('Cầu nguyện nơi công cộng', 'Cầu nguyện trong phòng riêng', 'Cầu nguyện với nhiều lời', 'Cầu nguyện một mình'), 1, 'Ma-thi-ơ 6:6: "Song khi ngươi cầu nguyện, hãy vào phòng riêng, đóng cửa lại, rồi cầu nguyện Cha ngươi, ở nơi kín nhiệm đó."'),
('27', 'Matthew', 7, 'easy', 'multiple_choice_single', 'Chúa Giê-su dạy: "Hãy xin, sẽ được; hãy tìm, sẽ gặp; hãy gõ, cửa sẽ mở cho." Điều này nói về gì?', JSON_ARRAY('Sự cầu nguyện', 'Sự tìm kiếm', 'Sự gõ cửa', 'Tất cả các điều trên'), 3, 'Ma-thi-ơ 7:7-8: "Hãy xin, sẽ được; hãy tìm, sẽ gặp; hãy gõ cửa, sẽ mở cho. Bởi vì hễ ai xin thì được; ai tìm thì gặp; ai gõ cửa thì được mở."'),
('28', 'Matthew', 8, 'hard', 'multiple_choice_single', 'Chúa Giê-su đã chữa lành cho ai bằng cách chạm vào?', JSON_ARRAY('Người phung', 'Người mù', 'Người què', 'Người câm'), 0, 'Ma-thi-ơ 8:3: "Đức Chúa Jêsus giơ tay rờ người, mà phán rằng: Ta muốn, hãy sạch đi. Tức thì người phung được sạch."'),
('29', 'Matthew', 9, 'medium', 'multiple_choice_single', 'Chúa Giê-su đã gọi ai làm môn đồ đầu tiên?', JSON_ARRAY('Phi-e-rơ và Anh-rê', 'Gia-cơ và Giăng', 'Ma-thi-ơ', 'Tất cả các môn đồ'), 0, 'Ma-thi-ơ 4:18-20: "Khi đang đi dọc theo mé biển Ga-li-lê, Ngài thấy hai anh em kia, là Si-môn, cũng gọi là Phi-e-rơ, với Anh-rê, em người, đang thả lưới dưới biển."'),
('30', 'Matthew', 10, 'easy', 'multiple_choice_single', 'Chúa Giê-su đã sai 12 sứ đồ đi rao giảng với lời dặn gì?', JSON_ARRAY('Hãy đi khắp thế gian', 'Hãy đi đến cùng dân Y-sơ-ra-ên', 'Hãy đi đến các thành', 'Hãy đi đến các làng'), 1, 'Ma-thi-ơ 10:5-6: "Đức Chúa Jêsus sai mười hai sứ đồ nầy đi, và có truyền rằng: Đường đi các dân ngoại chớ vào, thành của dân Sa-ma-ri chớ vào; song thà đi đến cùng những con chiên lạc mất của nhà Y-sơ-ra-ên."'),
-- John Questions (10 questions)
('31', 'John', 1, 'easy', 'multiple_choice_single', 'Câu đầu tiên của sách Giăng là gì?', JSON_ARRAY('Ban đầu có Đức Chúa Trời', 'Ban đầu có Ngôi Lời', 'Ban đầu có Đức Chúa Jêsus', 'Ban đầu có sự sáng'), 1, 'Giăng 1:1: "Ban đầu có Ngôi Lời, Ngôi Lời ở cùng Đức Chúa Trời, và Ngôi Lời là Đức Chúa Trời."'),
('32', 'John', 1, 'medium', 'multiple_choice_single', 'Gioan Báp-tít đã làm chứng về Chúa Giê-su như thế nào?', JSON_ARRAY('Đây là Chiên Con của Đức Chúa Trời', 'Đây là Vua của dân Y-sơ-ra-ên', 'Đây là Đấng Mê-si', 'Đây là Con Đức Chúa Trời'), 0, 'Giăng 1:29: "Qua ngày sau, Giăng thấy Đức Chúa Jêsus đến cùng mình, thì nói rằng: Kìa, Chiên Con của Đức Chúa Trời, là Đấng cất tội lỗi thế gian đi!"'),
('33', 'John', 2, 'easy', 'multiple_choice_single', 'Phép lạ đầu tiên của Chúa Giê-su là gì?', JSON_ARRAY('Chữa lành người mù', 'Hóa bánh ra nhiều', 'Biến nước thành rượu', 'Đi trên mặt nước'), 2, 'Giăng 2:1-11: Chúa Giê-su biến nước thành rượu tại tiệc cưới Ca-na.'),
('34', 'John', 3, 'medium', 'multiple_choice_single', 'Chúa Giê-su nói với Ni-cô-đem về điều gì?', JSON_ARRAY('Sự tái sinh', 'Nước Đức Chúa Trời', 'Sự sống đời đời', 'Tất cả các điều trên'), 3, 'Giăng 3:1-21: Chúa Giê-su nói với Ni-cô-đem về sự tái sinh, nước Đức Chúa Trời, và sự sống đời đời.'),
('35', 'John', 4, 'easy', 'multiple_choice_single', 'Chúa Giê-su đã nói chuyện với người phụ nữ Sa-ma-ri bên giếng nào?', JSON_ARRAY('Giếng Gia-cốp', 'Giếng Bê-e-sê-ba', 'Giếng Si-khem', 'Giếng Ca-na-an'), 0, 'Giăng 4:6: "Tại đó có giếng Gia-cốp. Vả, Đức Chúa Jêsus đi đường mệt mỏi, nên ngồi gần bên giếng."'),
('36', 'John', 6, 'medium', 'multiple_choice_single', 'Chúa Giê-su đã hóa bánh cho bao nhiêu người?', JSON_ARRAY('3000 người', '4000 người', '5000 người', '6000 người'), 2, 'Giăng 6:10: "Đức Chúa Jêsus phán rằng: Hãy bảo chúng ngồi xuống. Vả, trong nơi đó có nhiều cỏ. Vậy, người ta ngồi xuống, số chừng năm ngàn người."'),
('37', 'John', 8, 'hard', 'multiple_choice_single', 'Chúa Giê-su nói: "Ta là sự sáng của thế gian" trong hoàn cảnh nào?', JSON_ARRAY('Khi chữa lành người mù', 'Khi dạy dỗ trong đền thờ', 'Khi nói với người phụ nữ ngoại tình', 'Khi tranh luận với người Pha-ri-si'), 1, 'Giăng 8:12: "Đức Chúa Jêsus lại cất tiếng phán cùng chúng rằng: Ta là sự sáng của thế gian; kẻ theo ta, chẳng đi trong nơi tối tăm, nhưng có ánh sáng của sự sống."'),
('38', 'John', 11, 'easy', 'multiple_choice_single', 'Chúa Giê-su đã làm cho ai sống lại?', JSON_ARRAY('Con gái Giai-ru', 'Con trai bà góa', 'La-xa-rơ', 'Tất cả các người trên'), 2, 'Giăng 11:43-44: "Nói xong, Ngài kêu lên một tiếng lớn rằng: Hỡi La-xa-rơ, hãy ra! Người chết đi ra, chân tay buộc bằng vải liệm, và mặt quấn bằng khăn."'),
('39', 'John', 14, 'medium', 'multiple_choice_single', 'Chúa Giê-su nói: "Ta là đường đi, chân lý, và sự sống" để trả lời câu hỏi của ai?', JSON_ARRAY('Phi-e-rơ', 'Gia-cơ', 'Thô-ma', 'Phi-líp'), 2, 'Giăng 14:5-6: "Thô-ma thưa rằng: Lạy Chúa, chúng tôi chẳng biết Chúa đi đâu, làm sao biết đường được? Đức Chúa Jêsus đáp rằng: Ta là đường đi, chân lý, và sự sống; chẳng bởi ta thì không ai được đến cùng Cha."'),
('40', 'John', 19, 'easy', 'multiple_choice_single', 'Chúa Giê-su đã bị đóng đinh trên thập tự giá ở đâu?', JSON_ARRAY('Gô-gô-tha', 'Ghi-sê-ma-nê', 'Bết-sai-đa', 'Bết-pha-giê'), 0, 'Giăng 19:17: "Ngài vác thập tự giá mình, đi đến ngoài thành, tại nơi gọi là Gô-gô-tha."'),
-- Acts Questions (10 questions)
('41', 'Acts', 1, 'easy', 'multiple_choice_single', 'Chúa Giê-su đã thăng thiên từ đâu?', JSON_ARRAY('Núi Ô-li-ve', 'Núi Si-na-i', 'Núi Mô-ri-a', 'Núi Hô-rếp'), 0, 'Công Vụ 1:12: "Bấy giờ, các sứ đồ từ núi gọi là Ô-li-ve trở về thành Giê-ru-sa-lem."'),
('42', 'Acts', 2, 'medium', 'multiple_choice_single', 'Đức Thánh Linh đã giáng xuống vào ngày nào?', JSON_ARRAY('Lễ Vượt Qua', 'Lễ Ngũ Tuần', 'Lễ Lều Tạm', 'Lễ Chuộc Tội'), 1, 'Công Vụ 2:1: "Đến ngày lễ Ngũ Tuần, môn đồ nhóm họp tại một chỗ."'),
('43', 'Acts', 3, 'easy', 'multiple_choice_single', 'Phi-e-rơ và Giăng đã chữa lành người què ở đâu?', JSON_ARRAY('Cửa Đẹp', 'Cửa Vàng', 'Cửa Nước', 'Cửa Cá'), 0, 'Công Vụ 3:2: "Có một người què từ lúc mới sanh, hằng ngày người ta đem đặt tại cửa đền thờ, gọi là Cửa Đẹp, để xin bố thí."'),
('44', 'Acts', 9, 'medium', 'multiple_choice_single', 'Sau-lơ đã được biến đổi trên đường đi đâu?', JSON_ARRAY('Đa-mách', 'Giê-ru-sa-lem', 'An-ti-ốt', 'Ê-phê-sô'), 0, 'Công Vụ 9:3: "Lúc đi đường, gần đến thành Đa-mách, thình lình có ánh sáng từ trời soi sáng chung quanh người."'),
('45', 'Acts', 10, 'easy', 'multiple_choice_single', 'Cọ-nê-li là người gì?', JSON_ARRAY('Người Do Thái', 'Người La Mã', 'Người Hy Lạp', 'Người Sa-ma-ri'), 1, 'Công Vụ 10:1: "Trong thành Sê-sa-rê có một người tên Cọ-nê-li, làm đội trưởng của đội binh gọi là Y-ta-li."'),
('46', 'Acts', 16, 'medium', 'multiple_choice_single', 'Phao-lô và Si-la đã bị bỏ tù ở đâu?', JSON_ARRAY('Phi-líp', 'Tê-sa-lô-ni-ca', 'Bê-rê', 'A-thên'), 0, 'Công Vụ 16:23: "Sau khi đánh đòn nhiều roi, họ bỏ tù, dặn người coi ngục phải cẩn thận giữ lấy."'),
('47', 'Acts', 17, 'hard', 'multiple_choice_single', 'Phao-lô đã tranh luận với các triết gia ở đâu?', JSON_ARRAY('A-thên', 'Cô-rinh-tô', 'Ê-phê-sô', 'Rô-ma'), 0, 'Công Vụ 17:18: "Một vài triết gia thuộc phái Ê-pi-cu-rê và phái Khắc-kỷ cũng tranh luận với người."'),
('48', 'Acts', 18, 'easy', 'multiple_choice_single', 'Phao-lô đã ở Cô-rinh-tô bao lâu?', JSON_ARRAY('6 tháng', '1 năm rưỡi', '2 năm', '3 năm'), 1, 'Công Vụ 18:11: "Phao-lô ở lại đó một năm sáu tháng, dạy đạo Đức Chúa Trời trong đám họ."'),
('49', 'Acts', 19, 'medium', 'multiple_choice_single', 'Phao-lô đã ở Ê-phê-sô bao lâu?', JSON_ARRAY('1 năm', '2 năm', '3 năm', '4 năm'), 2, 'Công Vụ 19:10: "Việc đó cứ luôn hai năm, đến nỗi mọi người ở trong cõi A-si, hoặc người Giu-đa hay người Gờ-réc, đều nghe đạo Chúa."'),
('50', 'Acts', 28, 'easy', 'multiple_choice_single', 'Phao-lô đã bị bắt và đưa đến Rô-ma vào năm nào?', JSON_ARRAY('Năm 60', 'Năm 61', 'Năm 62', 'Năm 63'), 1, 'Công Vụ 28:16: "Khi chúng ta đến thành Rô-ma, Phao-lô được phép ở riêng với người lính canh giữ." Phao-lô bị bắt vào năm 61 SCN.');
