-- Repeatable seed: base data (contents from resources/data.sql)
-- Dữ liệu mẫu cho Bible Quiz
-- Sách Kinh Thánh
INSERT IGNORE INTO books (id, name, name_vi, testament, order_index, created_at) VALUES
-- Cựu Ước
('book-001', 'Genesis', 'Sáng Thế Ký', 'OLD', 1, NOW()),
('book-002', 'Exodus', 'Xuất Ê-díp-tô Ký', 'OLD', 2, NOW()),
('book-003', 'Leviticus', 'Lê-vi Ký', 'OLD', 3, NOW()),
('book-004', 'Numbers', 'Dân Số Ký', 'OLD', 4, NOW()),
('book-005', 'Deuteronomy', 'Phục Truyền Luật Lệ Ký', 'OLD', 5, NOW()),
('book-006', 'Joshua', 'Giô-suê', 'OLD', 6, NOW()),
('book-007', 'Judges', 'Các Quan Xét', 'OLD', 7, NOW()),
('book-008', 'Ruth', 'Ru-tơ', 'OLD', 8, NOW()),
('book-009', '1 Samuel', '1 Sa-mu-ên', 'OLD', 9, NOW()),
('book-010', '2 Samuel', '2 Sa-mu-ên', 'OLD', 10, NOW()),
('book-011', '1 Kings', '1 Các Vua', 'OLD', 11, NOW()),
('book-012', '2 Kings', '2 Các Vua', 'OLD', 12, NOW()),
('book-013', '1 Chronicles', '1 Sử Ký', 'OLD', 13, NOW()),
('book-014', '2 Chronicles', '2 Sử Ký', 'OLD', 14, NOW()),
('book-015', 'Ezra', 'Ê-xơ-ra', 'OLD', 15, NOW()),
('book-016', 'Nehemiah', 'Nê-hê-mi', 'OLD', 16, NOW()),
('book-017', 'Esther', 'Ê-xơ-tê', 'OLD', 17, NOW()),
('book-018', 'Job', 'Gióp', 'OLD', 18, NOW()),
('book-019', 'Psalms', 'Thi Thiên', 'OLD', 19, NOW()),
('book-020', 'Proverbs', 'Châm Ngôn', 'OLD', 20, NOW()),
('book-021', 'Ecclesiastes', 'Truyền Đạo', 'OLD', 21, NOW()),
('book-022', 'Song of Songs', 'Nhã Ca', 'OLD', 22, NOW()),
('book-023', 'Isaiah', 'Ê-sai', 'OLD', 23, NOW()),
('book-024', 'Jeremiah', 'Giê-rê-mi', 'OLD', 24, NOW()),
('book-025', 'Lamentations', 'Ca Thương', 'OLD', 25, NOW()),
('book-026', 'Ezekiel', 'Ê-xê-chi-ên', 'OLD', 26, NOW()),
('book-027', 'Daniel', 'Đa-ni-ên', 'OLD', 27, NOW()),
('book-028', 'Hosea', 'Ô-sê', 'OLD', 28, NOW()),
('book-029', 'Joel', 'Giô-ên', 'OLD', 29, NOW()),
('book-030', 'Amos', 'A-mốt', 'OLD', 30, NOW()),
('book-031', 'Obadiah', 'Áp-đia', 'OLD', 31, NOW()),
('book-032', 'Jonah', 'Giô-na', 'OLD', 32, NOW()),
('book-033', 'Micah', 'Mi-chê', 'OLD', 33, NOW()),
('book-034', 'Nahum', 'Na-hum', 'OLD', 34, NOW()),
('book-035', 'Habakkuk', 'Ha-ba-cúc', 'OLD', 35, NOW()),
('book-036', 'Zephaniah', 'Sô-phô-ni', 'OLD', 36, NOW()),
('book-037', 'Haggai', 'A-ghê', 'OLD', 37, NOW()),
('book-038', 'Zechariah', 'Xa-cha-ri', 'OLD', 38, NOW()),
('book-039', 'Malachi', 'Ma-la-chi', 'OLD', 39, NOW()),

-- Tân Ước
('book-040', 'Matthew', 'Ma-thi-ơ', 'NEW', 40, NOW()),
('book-041', 'Mark', 'Mác', 'NEW', 41, NOW()),
('book-042', 'Luke', 'Lu-ca', 'NEW', 42, NOW()),
('book-043', 'John', 'Giăng', 'NEW', 43, NOW()),
('book-044', 'Acts', 'Công Vụ', 'NEW', 44, NOW()),
('book-045', 'Romans', 'Rô-ma', 'NEW', 45, NOW()),
('book-046', '1 Corinthians', '1 Cô-rinh-tô', 'NEW', 46, NOW()),
('book-047', '2 Corinthians', '2 Cô-rinh-tô', 'NEW', 47, NOW()),
('book-048', 'Galatians', 'Ga-la-ti', 'NEW', 48, NOW()),
('book-049', 'Ephesians', 'Ê-phê-sô', 'NEW', 49, NOW()),
('book-050', 'Philippians', 'Phi-líp', 'NEW', 50, NOW()),
('book-051', 'Colossians', 'Cô-lô-se', 'NEW', 51, NOW()),
('book-052', '1 Thessalonians', '1 Tê-sa-lô-ni-ca', 'NEW', 52, NOW()),
('book-053', '2 Thessalonians', '2 Tê-sa-lô-ni-ca', 'NEW', 53, NOW()),
('book-054', '1 Timothy', '1 Ti-mô-thê', 'NEW', 54, NOW()),
('book-055', '2 Timothy', '2 Ti-mô-thê', 'NEW', 55, NOW()),
('book-056', 'Titus', 'Tít', 'NEW', 56, NOW()),
('book-057', 'Philemon', 'Phi-lê-môn', 'NEW', 57, NOW()),
('book-058', 'Hebrews', 'Hê-bơ-rơ', 'NEW', 58, NOW()),
('book-059', 'James', 'Gia-cơ', 'NEW', 59, NOW()),
('book-060', '1 Peter', '1 Phi-e-rơ', 'NEW', 60, NOW()),
('book-061', '2 Peter', '2 Phi-e-rơ', 'NEW', 61, NOW()),
('book-062', '1 John', '1 Giăng', 'NEW', 62, NOW()),
('book-063', '2 John', '2 Giăng', 'NEW', 63, NOW()),
('book-064', '3 John', '3 Giăng', 'NEW', 64, NOW()),
('book-065', 'Jude', 'Giu-đe', 'NEW', 65, NOW()),
('book-066', 'Revelation', 'Khải Huyền', 'NEW', 66, NOW());

-- User mẫu
INSERT IGNORE INTO users (id, name, email, avatar_url, provider, role, created_at, updated_at) VALUES
('user-001', 'Nguyễn Văn An', 'an.nguyen@example.com', null, 'local', 'USER', NOW(), NOW()),
('user-002', 'Trần Thị Bình', 'binh.tran@example.com', null, 'local', 'USER', NOW(), NOW()),
('user-003', 'Lê Văn Cường', 'cuong.le@example.com', null, 'local', 'USER', NOW(), NOW()),
('user-004', 'Phạm Thị Dung', 'dung.pham@example.com', null, 'local', 'USER', NOW(), NOW()),
('user-005', 'Hoàng Văn Em', 'em.hoang@example.com', null, 'local', 'USER', NOW(), NOW()),
('user-006', 'Vũ Thị Phương', 'phuong.vu@example.com', null, 'local', 'USER', NOW(), NOW()),
('user-007', 'Đặng Văn Giang', 'giang.dang@example.com', null, 'local', 'USER', NOW(), NOW()),
('user-008', 'Bùi Thị Hoa', 'hoa.bui@example.com', null, 'local', 'USER', NOW(), NOW()),
('user-009', 'Ngô Văn Ích', 'ich.ngo@example.com', null, 'local', 'USER', NOW(), NOW()),
('user-010', 'Đinh Thị Kim', 'kim.dinh@example.com', null, 'local', 'USER', NOW(), NOW());


