-- Repeatable seed: Genesis questions (20 diverse questions)

INSERT IGNORE INTO questions (
  id, book, chapter, verse_start, verse_end, difficulty, type, content, options, correct_answer, explanation, tags, source, language, is_active, created_at, updated_at
) VALUES

-- Easy (6)
('q-gen2-001','Genesis',1,1,1,'easy','multiple_choice_single',
'Câu mở đầu Kinh Thánh (Sáng 1:1) khẳng định điều gì?',
'["Đức Chúa Trời dựng nên trời đất", "Con người xuất hiện", "Luật pháp ban ra", "Tội lỗi vào thế gian"]',
'[0]',
'Sáng 1:1: Ban đầu Đức Chúa Trời dựng nên trời đất.',
'["Cựu Ước","Khởi nguyên","Sáng tạo"]','Genesis 1:1','vi',true,NOW(),NOW()),

('q-gen2-002','Genesis',1,26,27,'easy','multiple_choice_single',
'Con người được tạo theo hình ảnh của ai?',
'["Đức Chúa Trời", "Thiên sứ", "Muông thú", "Tinh tú"]',
'[0]',
'Sáng 1:26-27: Chúng ta hãy làm nên loài người như hình Ta.',
'["Cựu Ước","Sáng tạo","Hình ảnh"]','Genesis 1:26-27','vi',true,NOW(),NOW()),

('q-gen2-003','Genesis',2,2,3,'easy','multiple_choice_single',
'Ngày thứ bảy Đức Chúa Trời làm gì?',
'["Nghỉ ngơi và thánh hóa ngày đó", "Tạo biển", "Tạo mặt trời", "Tạo chim cá"]',
'[0]',
'Sáng 2:2-3: Ngày thứ bảy Ngài nghỉ và thánh hóa ngày ấy.',
'["Cựu Ước","Ngày nghỉ","Thánh hóa"]','Genesis 2:2-3','vi',true,NOW(),NOW()),

('q-gen2-004','Genesis',2,18,25,'easy','multiple_choice_single',
'Vì sao Đức Chúa Trời tạo nên người nữ?',
'["Làm một trợ giúp thích hợp cho người nam", "Đông dân số", "Để cai trị", "Để làm nông"]',
'[0]',
'Sáng 2:18: Loài người ở một mình không tốt; Ta sẽ làm một người giúp đỡ tương xứng.',
'["Cựu Ước","Hôn nhân","Trợ giúp"]','Genesis 2:18-25','vi',true,NOW(),NOW()),

('q-gen2-005','Genesis',3,1,7,'easy','multiple_choice_single',
'Ai cám dỗ Ê-va ăn trái cấm?',
'["Con rắn", "Thiên sứ", "A-đam", "Ca-in"]',
'[0]',
'Sáng 3:1: Con rắn là loài khôn hơn hết thảy thú đồng.',
'["Cựu Ước","Sa ngã","Cám dỗ"]','Genesis 3:1-7','vi',true,NOW(),NOW()),

('q-gen2-006','Genesis',6,9,9,'easy','multiple_choice_single',
'Nô-ê được mô tả là người như thế nào?',
'["Công bình và trọn vẹn", "Giàu có và khôn ngoan", "Dũng cảm và mạnh mẽ", "Khéo tay và tài trí"]',
'[0]',
'Sáng 6:9: Nô-ê là người công bình, trọn vẹn trong đời mình.',
'["Cựu Ước","Nô-ê","Đức hạnh"]','Genesis 6:9','vi',true,NOW(),NOW()),

-- Medium (10)
('q-gen2-007','Genesis',7,1,10,'medium','multiple_choice_single',
'Vì sao Nô-ê và gia đình vào tàu trước lụt?',
'["Vâng lệnh Chúa vì sự công bình", "Tránh quân thù", "Tìm của báu", "Di cư"]',
'[0]',
'Sáng 7:1: Vì ta thấy ngươi là công bình trước mặt ta.',
'["Cựu Ước","Vâng phục","Cứu chuộc"]','Genesis 7:1-10','vi',true,NOW(),NOW()),

('q-gen2-008','Genesis',9,8,17,'medium','multiple_choice_single',
'Dấu hiệu giao ước Đức Chúa Trời với Nô-ê là gì?',
'["Cầu vồng", "Dấu ấn trên trán", "Hòn đá", "Cây ô-liu"]',
'[0]',
'Sáng 9:13: Ta đặt cung ta trên mây làm dấu giao ước.',
'["Cựu Ước","Giao ước","Cầu vồng"]','Genesis 9:8-17','vi',true,NOW(),NOW()),

('q-gen2-009','Genesis',12,1,3,'medium','multiple_choice_single',
'Đức Chúa Trời hứa gì với Áp-ram khi gọi ông?',
'["Làm nên một dân lớn và phước cho muôn dân", "Cho đất ngay lập tức", "Cho phép lạ tức thời", "Cho danh tiếng của cải"]',
'[0]',
'Sáng 12:2-3: Ta sẽ làm cho ngươi nên một dân lớn... các chi phái thế gian sẽ nhờ ngươi mà được phước.',
'["Cựu Ước","Gọi","Lời hứa"]','Genesis 12:1-3','vi',true,NOW(),NOW()),

('q-gen2-010','Genesis',15,5,6,'medium','multiple_choice_single',
'Áp-ram được kể là công bình vì sao?',
'["Ông tin Đức Chúa Trời", "Ông dâng của lễ lớn", "Ông giữ luật", "Ông làm phép lạ"]',
'[0]',
'Sáng 15:6: Áp-ram tin Đức Giê-hô-va, thì Ngài kể điều đó là công bình cho ông.',
'["Cựu Ước","Đức tin","Công chính hóa"]','Genesis 15:5-6','vi',true,NOW(),NOW()),

('q-gen2-011','Genesis',17,1,8,'medium','multiple_choice_single',
'Dấu chỉ giao ước với Áp-ra-ham là gì?',
'["Cắt bì", "Đổi tên", "Hy lễ", "Dâng phần mười"]',
'[0]',
'Sáng 17:10-11: Các ngươi phải chịu phép cắt bì.',
'["Cựu Ước","Giao ước","Dấu chỉ"]','Genesis 17:1-8','vi',true,NOW(),NOW()),

('q-gen2-012','Genesis',22,1,14,'medium','multiple_choice_single',
'Áp-ra-ham dâng ai làm của lễ thử thách đức tin?',
'["Y-sác", "Y-sau", "Giô-sép", "Ích-ma-ên"]',
'[0]',
'Sáng 22:2: Hãy đem con một ngươi là Y-sác... dâng làm của lễ thiêu.',
'["Cựu Ước","Thử thách","Đức tin"]','Genesis 22:1-14','vi',true,NOW(),NOW()),

('q-gen2-013','Genesis',28,10,22,'medium','multiple_choice_single',
'Gia-cốp thấy chiêm bao gì tại Bê-tên?',
'["Thang lên trời và thiên sứ lên xuống", "Xe lửa lửa", "Sấm chớp", "Sao rơi"]',
'[0]',
'Sáng 28:12: Một cái thang dựng trên đất, đầu chạm trời.',
'["Cựu Ước","Khải tượng","Giao ước"]','Genesis 28:10-22','vi',true,NOW(),NOW()),

('q-gen2-014','Genesis',32,22,32,'medium','multiple_choice_single',
'Tên "Y-sơ-ra-ên" được đặt khi nào?',
'["Gia-cốp vật lộn với một người đến rạng đông", "Sau khi qua sông Giô-đanh", "Khi cưới Ra-chên", "Khi sinh Giô-sép"]',
'[0]',
'Sáng 32:28: Ngươi đã vật lộn với Đức Chúa Trời và với người ta, và thắng.',
'["Cựu Ước","Đổi tên","Giao ước"]','Genesis 32:22-32','vi',true,NOW(),NOW()),

('q-gen2-015','Genesis',37,3,11,'medium','multiple_choice_single',
'Giô-sép bị anh em ghen ghét vì điều gì?',
'["Áo nhiều màu và chiêm bao", "Cướp trưởng nam", "Lấy phần mười", "Giàu có hơn"]',
'[0]',
'Sáng 37:3-11: Áo thêu nhiều màu và chiêm bao về tôn trọng.',
'["Cựu Ước","Gia đình","Quan phòng"]','Genesis 37:3-11','vi',true,NOW(),NOW()),

('q-gen2-016','Genesis',50,19,21,'medium','multiple_choice_single',
'Giô-sếp nói gì về điều ác anh em đã làm?',
'["Đức Chúa Trời biến điều ác thành điều lành", "Hãy quên đi", "Hãy đền bù", "Hãy ra tòa"]',
'[0]',
'Sáng 50:20: Các ngươi toan hại ta, nhưng Đức Chúa Trời toan làm điều lành.',
'["Cựu Ước","Quan phòng","Tha thứ"]','Genesis 50:19-21','vi',true,NOW(),NOW()),

-- Hard (4)
('q-gen2-017','Genesis',3,15,15,'hard','multiple_choice_single',
'Sáng 3:15 thường được gọi là gì trong thần học Cơ-đốc?',
'["Protoevangelium (Tin Lành đầu tiên)", "Shema", "Halakha", "Midrash"]',
'[0]',
'Sáng 3:15 báo trước dòng dõi người nữ sẽ đạp nát đầu con rắn.',
'["Cựu Ước","Tiên tri","Cứu rỗi"]','Genesis 3:15','vi',true,NOW(),NOW()),

('q-gen2-018','Genesis',14,18,20,'hard','multiple_choice_single',
'Mên-chi-xê-đéc là ai theo Sáng 14?',
'["Vua Sa-lem và thầy tế lễ của Đức Chúa Trời Chí Cao", "Vua Ai Cập", "Vua Ba-by-lôn", "Thầy tế lễ Lê-vi"]',
'[0]',
'Sáng 14:18: Mên-chi-xê-đéc là vua Sa-lem, thầy tế lễ của Đức Chúa Trời Chí Cao.',
'["Cựu Ước","Kiểu mẫu","Tế lễ"]','Genesis 14:18-20','vi',true,NOW(),NOW()),

('q-gen2-019','Genesis',22,14,14,'hard','multiple_choice_single',
'Danh Đức Giê-hô-va nào được Áp-ra-ham gọi sau sự kiện dâng Y-sác?',
'["Giê-hô-va Di-rê (Đức Giê-hô-va sẽ sắm sẵn)", "Giê-hô-va Ra-pha", "Giê-hô-va Nissi", "Giê-hô-va Shalom"]',
'[0]',
'Sáng 22:14: Áp-ra-ham đặt tên nơi đó là Giê-hô-va Di-rê.',
'["Cựu Ước","Danh Chúa","Đức tin"]','Genesis 22:14','vi',true,NOW(),NOW()),

('q-gen2-020','Genesis',49,8,12,'hard','multiple_choice_single',
'Lời chúc phước dành cho Giu-đa nhấn mạnh điều gì?',
'["Vương quyền sẽ không rời khỏi Giu-đa", "Sự khôn ngoan", "Sự giàu có", "Số con đông"]',
'[0]',
'Sáng 49:10: Cây phủ việt sẽ không rời khỏi Giu-đa cho đến khi Đấng Si-lô đến.',
'["Cựu Ước","Tiên tri","Vương quyền"]','Genesis 49:8-12','vi',true,NOW(),NOW());

-- Additional hard, logic-focused Genesis questions (appended)
INSERT IGNORE INTO questions (
  id, book, chapter, verse_start, verse_end, difficulty, type, content, options, correct_answer, explanation, tags, source, language, is_active, created_at, updated_at
) VALUES

('q-genH-001','Genesis',1,2,5,'hard','multiple_choice_single',
'Trật tự “tối tăm trước ánh sáng” (Sáng 1:2-5) gợi nguyên tắc nào để đọc toàn bộ Sáng Thế Ký?',
'["Từ hỗn mang đến trật tự nhờ lời phán", "Từ luật đến ân điển", "Từ con người đến Đức Chúa Trời", "Từ đất lên trời"]',
'[0]',
'Mô-típ xuyên suốt: lời Chúa biến hỗn mang (tohu va-bohu) thành trật tự và sự sống.',
'["Cựu Ước","Sáng tạo","Logic mô-típ"]','Genesis 1:2-5','vi',true,NOW(),NOW()),

('q-genH-002','Genesis',1,26,28,'hard','multiple_choice_single',
'“Hình ảnh Đức Chúa Trời” liên hệ thế nào với mệnh lệnh quản trị trong bối cảnh Cận Đông cổ?',
'["Đại diện vương quyền của Đức Chúa Trời trên tạo vật", "Hợp thức hóa bạo lực", "Chỉ cho nam", "Chỉ cho vua"]',
'[0]',
'Trong ANE, vua là hình ảnh thần; Sáng 1 mở rộng cho cả nam và nữ đại diện vương quyền của Đức Chúa Trời.',
'["Cựu Ước","Vương quyền","Nhân học thần học"]','Genesis 1:26-28','vi',true,NOW(),NOW()),

('q-genH-003','Genesis',2,15,17,'hard','multiple_choice_single',
'Cặp động từ “làm/giữ” (abad/shamar) trong Ê-đen ám chỉ vai trò nào?',
'["Tư tế canh giữ nơi thánh", "Vua trị vì", "Tiên tri giảng dạy", "Thẩm phán phân xử"]',
'[0]',
'Các động từ dùng cho Lê-vi hầu việc và canh giữ (Dân 3:7-8); Ê-đen như đền thờ sơ khởi.',
'["Cựu Ước","Đền thờ-Êđen","Tư tế"]','Genesis 2:15-17','vi',true,NOW(),NOW()),

('q-genH-004','Genesis',2,23,24,'hard','multiple_choice_single',
'Công thức “xương bởi xương, thịt bởi thịt” cho thấy hôn nhân mang bản chất gì?',
'["Hợp nhất giao ước", "Quan hệ sinh học", "Khế ước dân sự", "Liên minh bộ tộc"]',
'[0]',
'Ngôn ngữ giao ước về hợp nhất bản thể, nền tảng thần học cho hôn nhân.',
'["Cựu Ước","Hôn nhân","Giao ước"]','Genesis 2:23-24','vi',true,NOW(),NOW()),

('q-genH-005','Genesis',3,1,7,'hard','multiple_choice_single',
'Thủ thuật tu từ nào khiến con rắn gieo hoài nghi về lòng tốt của Đức Chúa Trời?',
'["Bóp méo lời phán (thêm/bớt) và đổi trọng tâm", "Đe dọa bạo lực", "Phủ nhận vườn Ê-đen", "Tấn công A-đam trực tiếp"]',
'[0]',
'3:1,3 cho thấy con rắn thêm/bớt, chuyển dư dật ân điển thành nhấn mạnh cấm đoán.',
'["Cựu Ước","Sa ngã","Ngụy biện"]','Genesis 3:1-7','vi',true,NOW(),NOW()),

('q-genH-006','Genesis',3,14,19,'hard','multiple_choice_single',
'Kết cấu án phạt 3:14-19 hé lộ điều gì về công lý giao ước?',
'["Thứ tự liên quan tác nhân-tội-lĩnh vực", "Ngẫu nhiên", "Thiên vị nam", "Thiên vị nữ"]',
'[0]',
'Án phạt tương xứng: rắn (quan hệ/ngụy biện), nữ (sinh sản/quan hệ), nam (lao động/đất).',
'["Cựu Ước","Công lý","Giao ước"]','Genesis 3:14-19','vi',true,NOW(),NOW()),

('q-genH-007','Genesis',4,6,7,'hard','multiple_choice_single',
'“Tội lỗi rình phục” được nhân hóa nhằm nhấn mạnh điều gì về đạo đức con người?',
'["Trách nhiệm làm chủ dục vọng", "Không thể chống cám dỗ", "Tiền định tuyệt đối", "Do môi trường"]',
'[0]',
'“Ngươi phải quản trị nó” khẳng định trách nhiệm đạo đức cá nhân.',
'["Cựu Ước","Đạo đức","Tự chủ"]','Genesis 4:6-7','vi',true,NOW(),NOW()),

('q-genH-008','Genesis',6,5,8,'hard','multiple_choice_single',
'“Đức Chúa Trời ăn năn” (6:6) hòa giải thế nào với chủ quyền Ngài?',
'["Ngôn ngữ nhân hình diễn tả nỗi đau giao ước", "Thay đổi bản tính", "Sai lầm tiên tri", "Do biên tập"]',
'[0]',
'“Ăn năn” là nhân hình học; nhấn mạnh bi thương giao ước trước bạo ác loài người.',
'["Cựu Ước","Nhân hình hóa","Thần học"]','Genesis 6:5-8','vi',true,NOW(),NOW()),

('q-genH-009','Genesis',8,20,22,'hard','multiple_choice_single',
'Vì sao lời hứa 8:22 không phủ nhận phán xét tương lai?',
'["Hứa về chu kỳ vũ trụ, không hủy diệt bằng lụt", "Phủ nhận mọi phán xét", "Ràng buộc chỉ thời Nô-ê", "Hủy luật gieo gặt"]',
'[0]',
'Phân biệt loại phán xét: không còn lụt toàn cầu; công lý vẫn vận hành lịch sử.',
'["Cựu Ước","Giao ước Nô-ê","Phán xét"]','Genesis 8:20-22','vi',true,NOW(),NOW()),

('q-genH-010','Genesis',9,6,9,'hard','multiple_choice_single',
'Cơ sở thần học của hình phạt đối với giết người trong 9:6 là gì?',
'["Hình ảnh Đức Chúa Trời nơi con người", "Lợi ích xã hội", "Sợ trả thù", "Luật bộ tộc"]',
'[0]',
'Giết người xúc phạm Đấng mà con người phản ánh; nhân phẩm có nền tảng thần học.',
'["Cựu Ước","Nhân phẩm","Công lý"]','Genesis 9:6','vi',true,NOW(),NOW()),

('q-genH-011','Genesis',11,1,9,'hard','multiple_choice_single',
'Tại sao Ba-bên bị phân tán dù công nghệ gạch/ngói là tiến bộ?',
'["Vì kiêu ngạo tự tôn và chống mệnh lệnh “đầy dẫy đất”", "Vì nghèo tài nguyên", "Vì bất đồng ngôn ngữ trước đó", "Vì thiên tai"]',
'[0]',
'Dự án “làm danh” minh chứng kiêu ngạo tập thể, nghịch gọi sai phái.',
'["Cựu Ước","Ba-bên","Kiêu ngạo"]','Genesis 11:1-9','vi',true,NOW(),NOW()),

('q-genH-012','Genesis',12,3,3,'hard','multiple_choice_single',
'Logic cứu chuộc của 12:3 đảo ngược lời rủa 3:14-19 theo cách nào?',
'["Phước cho muôn dân thay vì rủa sả lan rộng", "Chỉ phước cho Israel", "Hủy bỏ lao động", "Xóa sinh nở đau đớn"]',
'[0]',
'“Nhờ ngươi mọi chi phái được phước” tương phản mô-típ rủa sả của Sáng 3.',
'["Cựu Ước","Giao ước Áp-ra-ham","Phước lành"]','Genesis 12:3','vi',true,NOW(),NOW()),

('q-genH-013','Genesis',15,17,21,'hard','multiple_choice_single',
'Nghi lễ cắt giao ước (đi giữa các miếng thịt) chủ yếu nhấn mạnh điều gì?',
'["Tính một chiều của lời hứa—Đức Chúa Trời chịu trách nhiệm", "Song phương bình đẳng", "Điều kiện luật pháp", "Tượng trưng rỗng"]',
'[0]',
'Chỉ Chúa đi giữa; Ngài tự ràng buộc với Áp-ram.',
'["Cựu Ước","Lời hứa","Nghi lễ"]','Genesis 15:17-21','vi',true,NOW(),NOW()),

('q-genH-014','Genesis',18,22,33,'hard','multiple_choice_single',
'Lập luận của Áp-ra-ham về Sô-đôm bày tỏ điều gì về công lý của Đức Chúa Trời?',
'["Phân biệt người công bình/kẻ ác; không quét sạch bừa bãi", "Khoan dung vô điều kiện", "Không cần tiêu chuẩn", "Thiên vị họ hàng"]',
'[0]',
'Đối thoại pháp lý nhấn mạnh công lý và lòng thương xót dựa trên số người công bình.',
'["Cựu Ước","Công lý","Cầu thay"]','Genesis 18:22-33','vi',true,NOW(),NOW()),

('q-genH-015','Genesis',22,1,14,'hard','multiple_choice_single',
'“Thử thách” 22:1 giúp phân định gì giữa đức tin và mê tín?',
'["Đức tin vâng phục dựa trên lời Chúa, không phải nghi lễ bừa bãi", "Chấp nhận mọi hy sinh", "Tôn vinh bạo lực", "Xem thường đạo đức"]',
'[0]',
'Đức Chúa Trời ngăn tay Áp-ra-ham; mục tiêu là tin cậy vâng phục, không sát tế người.',
'["Cựu Ước","Thử thách","Đức tin"]','Genesis 22:1-14','vi',true,NOW(),NOW()),

('q-genH-016','Genesis',25,23,26,'hard','multiple_choice_single',
'Lời phán về hai dân (Ê-sau/Jacốp) cho thấy nguyên tắc nào về tuyển chọn?',
'["Dựa trên mục đích Chúa chứ không công lao", "Dựa trên công đức", "Dựa trên trưởng nam", "Dựa trên vũ lực"]',
'[0]',
'Tuyển chọn theo mục đích tể trị; lớn phục vụ nhỏ.',
'["Cựu Ước","Tuyển chọn","Chủ quyền"]','Genesis 25:23-26','vi',true,NOW(),NOW()),

('q-genH-017','Genesis',28,12,17,'hard','multiple_choice_single',
'Cầu thang Bê-tên liên hệ thế nào đến mô-típ đền thờ và hiện diện?',
'["Cửa trời—nơi gặp gỡ, báo trước đền thờ", "Chủ đề chiến trận", "Chủ đề nông nghiệp", "Chủ đề chính trị"]',
'[0]',
'“Cửa trời” và “nhà Đức Chúa Trời” gợi hình ảnh đền thờ/Ê-đen nơi hiện diện Chúa.',
'["Cựu Ước","Đền thờ","Hiện diện"]','Genesis 28:12-17','vi',true,NOW(),NOW()),

('q-genH-018','Genesis',32,24,30,'hard','multiple_choice_single',
'Vật lộn tại Ghép-bốc tái định nghĩa sức mạnh thuộc linh thế nào?',
'["Đầu hàng trong tranh chiến là lối vào phước lành", "Thắng bằng bạo lực", "Trí mưu lấn át", "Dòng dõi bảo đảm"]',
'[0]',
'“Ta sẽ không buông nếu không chúc phước” — sức mạnh đến từ lệ thuộc ân điển.',
'["Cựu Ước","Cầu nguyện","Đổi tên"]','Genesis 32:24-30','vi',true,NOW(),NOW()),

('q-genH-019','Genesis',37,26,28,'hard','multiple_choice_single',
'Quyết định bán Giô-sép thay vì giết thể hiện điều gì về ý định Chúa?',
'["Quan phòng chuyển ác thành lành qua trách nhiệm con người", "Định mệnh tất yếu", "Tình cờ thuần túy", "Ân xá tức thì"]',
'[0]',
'Sự ác không bị phủ nhận nhưng bị bẻ lái vào mục đích cứu chuộc (50:20).',
'["Cựu Ước","Quan phòng","Đạo đức"]','Genesis 37:26-28','vi',true,NOW(),NOW()),

('q-genH-020','Genesis',50,19,21,'hard','multiple_choice_single',
'Lập luận của Giô-sép trong 50:19-21 là mẫu mực nào cho thần học về sự dữ?',
'["Đồng tồn tại: con người toan ác, Đức Chúa Trời toan lành", "Nhị nguyên: thiện ác ngang hàng", "Phủ định ác", "Tất định luận tuyệt đối"]',
'[0]',
'Khẳng định đồng thời trách nhiệm con người và tể trị Chúa, hướng tới cứu chuộc.',
'["Cựu Ước","Thần học sự dữ","Quan phòng"]','Genesis 50:19-21','vi',true,NOW(),NOW()),

-- Batch 2: Advanced theological and literary analysis (50 questions)
('q-genH-021','Genesis',1,1,2,'hard','multiple_choice_single',
'Cụm từ "tohu va-bohu" (hỗn mang và trống không) trong Sáng 1:2 có ý nghĩa thần học gì?',
'["Trạng thái tiền-sáng tạo, không phải hư không tuyệt đối", "Hư không tuyệt đối", "Vật chất đã tồn tại", "Thời gian vô tận"]',
'[0]',
'Tohu va-bohu mô tả trạng thái chưa được tổ chức, không phải không tồn tại.',
'["Cựu Ước","Sáng tạo","Thần học"]','Genesis 1:1-2','vi',true,NOW(),NOW()),

('q-genH-022','Genesis',1,26,27,'hard','multiple_choice_single',
'Cụm từ "hình ảnh" (tselem) và "giống như" (demut) trong Sáng 1:26-27 có sự khác biệt gì?',
'["Tselem: bản chất cốt lõi; Demut: biểu hiện bên ngoài", "Hoàn toàn giống nhau", "Tselem: nam; Demut: nữ", "Ngược lại"]',
'[0]',
'Tselem nhấn mạnh bản chất thần học; demut nhấn mạnh biểu hiện thực tế.',
'["Cựu Ước","Nhân học","Ngôn ngữ"]','Genesis 1:26-27','vi',true,NOW(),NOW()),

('q-genH-023','Genesis',2,7,7,'hard','multiple_choice_single',
'Công thức "bụi đất + hơi thở = linh hồn sống" trong Sáng 2:7 cho thấy quan điểm gì về bản chất con người?',
'["Thể xác và linh hồn là một thể thống nhất", "Linh hồn độc lập với thể xác", "Chỉ có thể xác", "Chỉ có linh hồn"]',
'[0]',
'Con người là sự kết hợp hữu cơ giữa vật chất và tinh thần, không tách biệt.',
'["Cựu Ước","Nhân học","Thể xác-linh hồn"]','Genesis 2:7','vi',true,NOW(),NOW()),

('q-genH-024','Genesis',3,8,10,'hard','multiple_choice_single',
'Việc A-đam "trốn" khỏi Đức Chúa Trời trong Sáng 3:8-10 cho thấy điều gì về bản chất tội lỗi?',
'["Tội lỗi làm đứt đoạn mối quan hệ, không phải địa lý", "Chỉ là hành vi thể xác", "Đức Chúa Trời không biết", "Tình cờ"]',
'[0]',
'Tội lỗi là vấn đề quan hệ, không phải khoảng cách vật lý.',
'["Cựu Ước","Tội lỗi","Quan hệ"]','Genesis 3:8-10','vi',true,NOW(),NOW()),

('q-genH-025','Genesis',4,1,2,'hard','multiple_choice_single',
'Cụm từ "nhờ Đức Giê-hô-va" trong Sáng 4:1 cho thấy quan điểm gì về sinh sản?',
'["Sinh sản là ân điển từ Chúa, không phải tự nhiên", "Hoàn toàn tự nhiên", "Chỉ do nam", "Chỉ do nữ"]',
'[0]',
'Ngay cả sau sa ngã, sinh sản vẫn là ân điển thần thượng.',
'["Cựu Ước","Sinh sản","Ân điển"]','Genesis 4:1-2','vi',true,NOW(),NOW()),

('q-genH-026','Genesis',4,3,5,'hard','multiple_choice_single',
'Tại sao Đức Chúa Trời nhận của lễ A-bên mà không nhận của lễ Ca-in trong Sáng 4:3-5?',
'["A-bên dâng với đức tin và lòng thành", "Ca-in dâng sai loại", "A-bên dâng nhiều hơn", "Ca-in dâng muộn"]',
'[0]',
'Hê-bơ-rơ 11:4: "A-bên bởi đức tin dâng của lễ tốt hơn".',
'["Cựu Ước","Của lễ","Đức tin"]','Genesis 4:3-5','vi',true,NOW(),NOW()),

('q-genH-027','Genesis',6,1,4,'hard','multiple_choice_single',
'Đoạn "con trai Đức Chúa Trời" và "con gái loài người" trong Sáng 6:1-4 có thể hiểu thế nào?',
'["Dòng dõi Sết (con trai Đức Chúa Trời) kết hôn với dòng Ca-in", "Thiên sứ kết hôn người", "Thần linh kết hôn người", "Không thể hiểu"]',
'[0]',
'Giải thích phù hợp với bối cảnh: dòng dõi tin kính kết hôn với dòng không tin kính.',
'["Cựu Ước","Dòng dõi","Hôn nhân"]','Genesis 6:1-4','vi',true,NOW(),NOW()),

('q-genH-028','Genesis',7,11,12,'hard','multiple_choice_single',
'Chi tiết "các nguồn nước sâu" và "cửa sổ trên trời" trong Sáng 7:11-12 cho thấy điều gì về cơn lụt?',
'["Lụt toàn cầu từ cả dưới và trên", "Chỉ mưa", "Chỉ sóng thần", "Chỉ lụt địa phương"]',
'[0]',
'Mô tả lụt toàn cầu với nước từ cả dưới đất và trên trời.',
'["Cựu Ước","Lụt","Toàn cầu"]','Genesis 7:11-12','vi',true,NOW(),NOW()),

('q-genH-029','Genesis',8,21,22,'hard','multiple_choice_single',
'Lời hứa "không còn rủa sả đất" trong Sáng 8:21-22 có ý nghĩa gì trong bối cảnh lịch sử cứu chuộc?',
'["Đức Chúa Trời cam kết không hủy diệt toàn cầu nữa", "Không còn tội lỗi", "Không còn đau khổ", "Không còn chết"]',
'[0]',
'Giao ước Nô-ê đảm bảo sự ổn định của tạo vật cho kế hoạch cứu chuộc.',
'["Cựu Ước","Giao ước Nô-ê","Cứu chuộc"]','Genesis 8:21-22','vi',true,NOW(),NOW()),

('q-genH-030','Genesis',9,20,27,'hard','multiple_choice_single',
'Lời rủa sả Ca-na-an thay vì Cham trong Sáng 9:20-27 cho thấy nguyên tắc gì về tội lỗi?',
'["Tội lỗi của cha ảnh hưởng đến con cái", "Cham vô tội", "Ca-na-an có lỗi", "Ngẫu nhiên"]',
'[0]',
'Tội lỗi của Cham ảnh hưởng đến dòng dõi, đặc biệt là Ca-na-an.',
'["Cựu Ước","Tội lỗi","Hậu quả"]','Genesis 9:20-27','vi',true,NOW(),NOW()),

('q-genH-031','Genesis',11,1,9,'hard','multiple_choice_single',
'Cụm từ "một tiếng nói và một lời" trong Sáng 11:1 cho thấy điều gì về sự thống nhất?',
'["Thống nhất ngôn ngữ tạo ra kiêu ngạo tập thể", "Chỉ là ngôn ngữ", "Không có ý nghĩa", "Tích cực"]',
'[0]',
'Thống nhất ngôn ngữ dẫn đến kiêu ngạo và chống lại mệnh lệnh "đầy dẫy đất".',
'["Cựu Ước","Ba-bên","Kiêu ngạo"]','Genesis 11:1-9','vi',true,NOW(),NOW()),

('q-genH-032','Genesis',12,1,3,'hard','multiple_choice_single',
'Lời hứa "Ta sẽ làm cho ngươi nên một dân lớn" trong Sáng 12:1-3 có ý nghĩa gì trong bối cảnh Áp-ram 75 tuổi?',
'["Lời hứa siêu nhiên vượt khả năng tự nhiên", "Chỉ là khuyến khích", "Áp-ram sẽ có con ngay", "Không có ý nghĩa"]',
'[0]',
'Lời hứa đòi hỏi sự can thiệp siêu nhiên của Đức Chúa Trời.',
'["Cựu Ước","Lời hứa","Siêu nhiên"]','Genesis 12:1-3','vi',true,NOW(),NOW()),

('q-genH-033','Genesis',14,18,20,'hard','multiple_choice_single',
'Mên-chi-xê-đéc "đem bánh và rượu ra" có ý nghĩa gì trong bối cảnh tế lễ?',
'["Báo trước Bữa Tiệc Thánh của Chúa Giê-su", "Chỉ là lễ nghi", "Không có ý nghĩa", "Tình cờ"]',
'[0]',
'Mên-chi-xê-đéc là kiểu mẫu của Chúa Giê-su, bánh và rượu báo trước Tiệc Thánh.',
'["Cựu Ước","Mên-chi-xê-đéc","Tiên tri"]','Genesis 14:18-20','vi',true,NOW(),NOW()),

('q-genH-034','Genesis',15,5,6,'hard','multiple_choice_single',
'Cụm từ "kể là công bình" (tsedaqah) trong 15:6 có ý nghĩa thần học gì?',
'["Công chính hóa bởi đức tin, không phải việc làm", "Dựa trên việc làm", "Tự nhiên", "Ngẫu nhiên"]',
'[0]',
'Đây là nền tảng của giáo lý công chính hóa bởi đức tin trong Tân Ước.',
'["Cựu Ước","Công chính hóa","Đức tin"]','Genesis 15:5-6','vi',true,NOW(),NOW()),

('q-genH-035','Genesis',16,1,6,'hard','multiple_choice_single',
'Việc Sa-rai đưa A-ga cho Áp-ram cho thấy điều gì về sự vội vàng trong lời hứa?',
'["Con người cố gắng thực hiện lời hứa Chúa bằng cách riêng", "Đúng đắn", "Không có vấn đề", "Tình cờ"]',
'[0]',
'Sa-rai và Áp-ram cố gắng "giúp" Đức Chúa Trời thực hiện lời hứa.',
'["Cựu Ước","Lời hứa","Kiên nhẫn"]','Genesis 16:1-6','vi',true,NOW(),NOW()),

('q-genH-036','Genesis',17,1,8,'hard','multiple_choice_single',
'Giao ước cắt bì được thiết lập khi Áp-ram 99 tuổi có ý nghĩa gì?',
'["Dấu chỉ của giao ước vĩnh viễn", "Chỉ là nghi lễ", "Tạm thời", "Không quan trọng"]',
'[0]',
'Cắt bì là dấu chỉ vĩnh viễn của giao ước giữa Đức Chúa Trời và dân Ngài.',
'["Cựu Ước","Giao ước","Dấu chỉ"]','Genesis 17:1-8','vi',true,NOW(),NOW()),

('q-genH-037','Genesis',18,1,8,'hard','multiple_choice_single',
'Việc Áp-ra-ham "chạy" và "vội vàng" phục vụ khách cho thấy điều gì về lòng hiếu khách?',
'["Hiếu khách là bổn phận thiêng liêng", "Chỉ là phép lịch sự", "Không quan trọng", "Tình cờ"]',
'[0]',
'Trong văn hóa Cận Đông, hiếu khách là bổn phận thiêng liêng.',
'["Cựu Ước","Hiếu khách","Bổn phận"]','Genesis 18:1-8','vi',true,NOW(),NOW()),

('q-genH-038','Genesis',19,1,11,'hard','multiple_choice_single',
'Việc dân Sô-đôm muốn "biết" các thiên sứ cho thấy điều gì về tình trạng đạo đức?',
'["Suy đồi đạo đức đến mức cực độ", "Chỉ tò mò", "Bình thường", "Không có vấn đề"]',
'[0]',
'Sô-đôm đã suy đồi đến mức muốn cưỡng hiếp khách lạ.',
'["Cựu Ước","Sô-đôm","Suy đồi"]','Genesis 19:1-11','vi',true,NOW(),NOW()),

('q-genH-039','Genesis',20,1,18,'hard','multiple_choice_single',
'Việc Áp-ra-ham lại nói dối về Sa-rai cho thấy điều gì về bản tính con người?',
'["Con người có xu hướng lặp lại sai lầm cũ", "Đã thay đổi", "Không có vấn đề", "Tình cờ"]',
'[0]',
'Áp-ra-ham lặp lại sai lầm cũ ở Ai Cập, cho thấy bản tính con người.',
'["Cựu Ước","Sai lầm","Bản tính"]','Genesis 20:1-18','vi',true,NOW(),NOW()),

('q-genH-040','Genesis',21,1,7,'hard','multiple_choice_single',
'Việc Y-sác được sinh ra "đúng kỳ" cho thấy điều gì về lời hứa Chúa?',
'["Đức Chúa Trời giữ lời hứa đúng thời điểm", "Tình cờ", "Muộn", "Sớm"]',
'[0]',
'Y-sác sinh ra đúng thời điểm Chúa đã hứa, chứng minh sự thành tín của Ngài.',
'["Cựu Ước","Lời hứa","Thành tín"]','Genesis 21:1-7','vi',true,NOW(),NOW()),

('q-genH-041','Genesis',22,1,2,'hard','multiple_choice_single',
'Cụm từ "con một ngươi" trong 22:2 có ý nghĩa gì trong bối cảnh Y-sác là con duy nhất?',
'["Y-sác là con duy nhất của lời hứa", "Chỉ là con trai", "Không có ý nghĩa", "Tình cờ"]',
'[0]',
'Y-sác là con duy nhất của lời hứa, làm cho thử thách càng khó khăn hơn.',
'["Cựu Ước","Y-sác","Lời hứa"]','Genesis 22:1-2','vi',true,NOW(),NOW()),

('q-genH-042','Genesis',22,8,8,'hard','multiple_choice_single',
'Lời nói "Đức Chúa Trời sẽ sắm sẵn" của Áp-ra-ham cho thấy điều gì về đức tin?',
'["Đức tin vững chắc dù không thấy cách thực hiện", "Chỉ là hy vọng", "Không chắc chắn", "Tình cờ"]',
'[0]',
'Áp-ra-ham tin chắc Đức Chúa Trời sẽ cung cấp, dù không biết cách.',
'["Cựu Ước","Đức tin","Tin cậy"]','Genesis 22:8','vi',true,NOW(),NOW()),

('q-genH-043','Genesis',23,1,20,'hard','multiple_choice_single',
'Việc Áp-ra-ham mua hang đá Mặc-bê-la có ý nghĩa gì?',
'["Khẳng định quyền sở hữu đất hứa", "Chỉ là mua đất", "Không có ý nghĩa", "Tình cờ"]',
'[0]',
'Đây là lần đầu tiên Áp-ra-ham sở hữu đất trong đất hứa.',
'["Cựu Ước","Đất hứa","Sở hữu"]','Genesis 23:1-20','vi',true,NOW(),NOW()),

('q-genH-044','Genesis',24,1,67,'hard','multiple_choice_single',
'Việc Áp-ra-ham gửi đầy tớ tìm vợ cho Y-sác cho thấy điều gì về hôn nhân?',
'["Hôn nhân cần sự hướng dẫn của Đức Chúa Trời", "Chỉ là tình cảm", "Tự do hoàn toàn", "Không quan trọng"]',
'[0]',
'Áp-ra-ham muốn Y-sác kết hôn với người tin kính, không phải dân ngoại.',
'["Cựu Ước","Hôn nhân","Đức tin"]','Genesis 24:1-67','vi',true,NOW(),NOW()),

('q-genH-045','Genesis',25,21,26,'hard','multiple_choice_single',
'Việc Y-sác cầu nguyện cho vợ hiếm muộn cho thấy điều gì về vai trò của cầu nguyện?',
'["Cầu nguyện là phương tiện để nhận lãnh ân điển", "Không cần thiết", "Tình cờ", "Không hiệu quả"]',
'[0]',
'Y-sác cầu nguyện và Đức Chúa Trời đáp lời, cho thấy quyền năng cầu nguyện.',
'["Cựu Ước","Cầu nguyện","Ân điển"]','Genesis 25:21-26','vi',true,NOW(),NOW()),

('q-genH-046','Genesis',27,1,40,'hard','multiple_choice_single',
'Việc Gia-cốp lừa dối cha để nhận phước lành cho thấy điều gì về con người?',
'["Con người cố gắng thực hiện ý muốn Chúa bằng cách sai", "Đúng đắn", "Không có vấn đề", "Tình cờ"]',
'[0]',
'Gia-cốp cố gắng thực hiện lời tiên tri bằng cách lừa dối.',
'["Cựu Ước","Lừa dối","Ý muốn"]','Genesis 27:1-40','vi',true,NOW(),NOW()),

('q-genH-047','Genesis',28,10,22,'hard','multiple_choice_single',
'Lời hứa "Ta sẽ ở cùng ngươi" trong 28:15 có ý nghĩa gì?',
'["Đức Chúa Trời sẽ đồng hành dù Gia-cốp có lỗi", "Chỉ khi ngoan", "Có điều kiện", "Tình cờ"]',
'[0]',
'Đức Chúa Trời hứa đồng hành với Gia-cốp dù ông đã lừa dối.',
'["Cựu Ước","Đồng hành","Ân điển"]','Genesis 28:10-22','vi',true,NOW(),NOW()),

('q-genH-048','Genesis',29,1,30,'hard','multiple_choice_single',
'Việc Gia-cốp yêu Ra-chên hơn Lê-a cho thấy điều gì về tình yêu?',
'["Tình yêu có thể thiên vị, nhưng Đức Chúa Trời công bằng", "Hoàn toàn công bằng", "Không có vấn đề", "Tình cờ"]',
'[0]',
'Dù Gia-cốp thiên vị Ra-chên, Đức Chúa Trời vẫn ban phước cho Lê-a.',
'["Cựu Ước","Tình yêu","Công bằng"]','Genesis 29:1-30','vi',true,NOW(),NOW()),

('q-genH-049','Genesis',30,1,24,'hard','multiple_choice_single',
'Việc Lê-a và Ra-chên tranh giành sinh con cho thấy điều gì về cạnh tranh?',
'["Cạnh tranh có thể dẫn đến đa thê và đau khổ", "Tích cực", "Không có vấn đề", "Tình cờ"]',
'[0]',
'Cạnh tranh giữa hai chị em dẫn đến đa thê và đau khổ gia đình.',
'["Cựu Ước","Cạnh tranh","Đa thê"]','Genesis 30:1-24','vi',true,NOW(),NOW()),

('q-genH-050','Genesis',31,1-55,'hard','multiple_choice_single',
'Việc Gia-cốp trốn khỏi La-ban cho thấy điều gì về mối quan hệ gia đình?',
'["Gia đình có thể trở thành nơi bóc lột và lừa dối", "Luôn tốt", "Không có vấn đề", "Tình cờ"]',
'[0]',
'La-ban lừa dối Gia-cốp nhiều lần, buộc ông phải trốn đi.',
'["Cựu Ước","Gia đình","Lừa dối"]','Genesis 31:1-55','vi',true,NOW(),NOW()),

('q-genH-051','Genesis',32,1-32,'hard','multiple_choice_single',
'Việc Gia-cốp vật lộn với Đức Chúa Trời cho thấy điều gì về cầu nguyện?',
'["Cầu nguyện đôi khi là cuộc vật lộn thuộc linh", "Chỉ là thưa chuyện", "Không có ý nghĩa", "Tình cờ"]',
'[0]',
'Cầu nguyện có thể là cuộc vật lộn thuộc linh để nhận lãnh phước lành.',
'["Cựu Ước","Cầu nguyện","Vật lộn"]','Genesis 32:1-32','vi',true,NOW(),NOW()),

('q-genH-052','Genesis',33,1-20,'hard','multiple_choice_single',
'Việc Gia-cốp và Ê-sau hòa giải cho thấy điều gì về tha thứ?',
'["Tha thứ có thể hàn gắn mối quan hệ đã đổ vỡ", "Không thể", "Không cần thiết", "Tình cờ"]',
'[0]',
'Dù Gia-cốp đã lừa dối Ê-sau, họ vẫn có thể hòa giải.',
'["Cựu Ước","Tha thứ","Hòa giải"]','Genesis 33:1-20','vi',true,NOW(),NOW()),

('q-genH-053','Genesis',34,1-31,'hard','multiple_choice_single',
'Việc Si-mê-ôn và Lê-vi trả thù cho Đi-na cho thấy điều gì về công lý?',
'["Trả thù có thể dẫn đến bạo lực và tội lỗi", "Công bằng", "Cần thiết", "Tình cờ"]',
'[0]',
'Trả thù dẫn đến bạo lực và tội lỗi, không phải công lý thật.',
'["Cựu Ước","Trả thù","Bạo lực"]','Genesis 34:1-31','vi',true,NOW(),NOW()),

('q-genH-054','Genesis',35,1-15,'hard','multiple_choice_single',
'Việc Gia-cốp trở về Bê-tên cho thấy điều gì về sự ăn năn?',
'["Ăn năn đòi hỏi quay về nơi gặp gỡ Đức Chúa Trời", "Không cần thiết", "Tình cờ", "Không quan trọng"]',
'[0]',
'Gia-cốp quay về Bê-tên để thờ phượng Đức Chúa Trời sau những sai lầm.',
'["Cựu Ước","Ăn năn","Thờ phượng"]','Genesis 35:1-15','vi',true,NOW(),NOW()),

('q-genH-055','Genesis',37,1-36,'hard','multiple_choice_single',
'Việc anh em Gia-cốp ghen ghét Giô-sép cho thấy điều gì về ghen tị?',
'["Ghen tị có thể dẫn đến tội ác và đau khổ", "Bình thường", "Không có vấn đề", "Tình cờ"]',
'[0]',
'Ghen tị của anh em dẫn đến việc bán Giô-sép làm nô lệ.',
'["Cựu Ước","Ghen tị","Tội ác"]','Genesis 37:1-36','vi',true,NOW(),NOW()),

('q-genH-056','Genesis',38,1-30,'hard','multiple_choice_single',
'Câu chuyện Giu-đa và Ta-ma cho thấy điều gì về sự công bằng?',
'["Đức Chúa Trời có thể sử dụng cả tội lỗi để thực hiện ý muốn", "Chỉ dùng người tốt", "Không quan trọng", "Tình cờ"]',
'[0]',
'Dù Giu-đa có lỗi, Đức Chúa Trời vẫn sử dụng để thực hiện kế hoạch cứu chuộc.',
'["Cựu Ước","Công bằng","Kế hoạch"]','Genesis 38:1-30','vi',true,NOW(),NOW()),

('q-genH-057','Genesis',39,1-23,'hard','multiple_choice_single',
'Việc Giô-sép từ chối vợ của Phô-ti-pha cho thấy điều gì về đức hạnh?',
'["Đức hạnh đòi hỏi sự hy sinh và chịu đựng", "Dễ dàng", "Không cần thiết", "Tình cờ"]',
'[0]',
'Giô-sép chọn đức hạnh dù phải chịu tù đày.',
'["Cựu Ước","Đức hạnh","Hy sinh"]','Genesis 39:1-23','vi',true,NOW(),NOW()),

('q-genH-058','Genesis',40,1-23,'hard','multiple_choice_single',
'Việc Giô-sép giải mộng cho quan coi ngục cho thấy điều gì về ân tứ?',
'["Ân tứ của Đức Chúa Trời không bị giới hạn bởi hoàn cảnh", "Chỉ khi tự do", "Không quan trọng", "Tình cờ"]',
'[0]',
'Dù trong tù, Giô-sép vẫn có thể sử dụng ân tứ giải mộng.',
'["Cựu Ước","Ân tứ","Hoàn cảnh"]','Genesis 40:1-23','vi',true,NOW(),NOW()),

('q-genH-059','Genesis',41,1-57,'hard','multiple_choice_single',
'Việc Pha-ra-ôn đặt Giô-sép làm tể tướng cho thấy điều gì về sự thăng tiến?',
'["Đức Chúa Trời có thể thăng tiến người trong hoàn cảnh khó khăn", "Chỉ khi may mắn", "Không thể", "Tình cờ"]',
'[0]',
'Từ tù nhân đến tể tướng, cho thấy quyền năng của Đức Chúa Trời.',
'["Cựu Ước","Thăng tiến","Quyền năng"]','Genesis 41:1-57','vi',true,NOW(),NOW()),

('q-genH-060','Genesis',42,1-38,'hard','multiple_choice_single',
'Việc anh em Giô-sép không nhận ra ông cho thấy điều gì về sự thay đổi?',
'["Thời gian và hoàn cảnh có thể thay đổi con người hoàn toàn", "Không thể", "Tình cờ", "Không quan trọng"]',
'[0]',
'Anh em không nhận ra Giô-sép vì ông đã thay đổi hoàn toàn.',
'["Cựu Ước","Thay đổi","Thời gian"]','Genesis 42:1-38','vi',true,NOW(),NOW()),

('q-genH-061','Genesis',43,1-34,'hard','multiple_choice_single',
'Việc Gia-cốp gửi Bên-gia-min xuống Ai Cập cho thấy điều gì về tình yêu cha con?',
'["Tình yêu cha con có thể vượt qua nỗi sợ hãi", "Chỉ sợ hãi", "Không quan trọng", "Tình cờ"]',
'[0]',
'Dù sợ mất Bên-gia-min, Gia-cốp vẫn gửi con xuống Ai Cập.',
'["Cựu Ước","Tình yêu","Sợ hãi"]','Genesis 43:1-34','vi',true,NOW(),NOW()),

('q-genH-062','Genesis',44,1-34,'hard','multiple_choice_single',
'Việc Giu-đa xin thay thế Bên-gia-min cho thấy điều gì về sự thay đổi?',
'["Con người có thể thay đổi và trở nên tốt hơn", "Không thể", "Tình cờ", "Không quan trọng"]',
'[0]',
'Giu-đa đã thay đổi từ người bán em đến người sẵn sàng thay thế em.',
'["Cựu Ước","Thay đổi","Tốt hơn"]','Genesis 44:1-34','vi',true,NOW(),NOW()),

('q-genH-063','Genesis',45,1-28,'hard','multiple_choice_single',
'Việc Giô-sép tha thứ anh em cho thấy điều gì về sự tha thứ?',
'["Tha thứ có thể hàn gắn mối quan hệ đã đổ vỡ", "Không thể", "Không cần thiết", "Tình cờ"]',
'[0]',
'Giô-sép tha thứ anh em và hàn gắn mối quan hệ gia đình.',
'["Cựu Ước","Tha thứ","Hàn gắn"]','Genesis 45:1-28','vi',true,NOW(),NOW()),

('q-genH-064','Genesis',46,1-34,'hard','multiple_choice_single',
'Việc Gia-cốp xuống Ai Cập cho thấy điều gì về sự tin cậy?',
'["Tin cậy Đức Chúa Trời dù không hiểu kế hoạch", "Chỉ khi hiểu", "Không cần thiết", "Tình cờ"]',
'[0]',
'Gia-cốp tin cậy Đức Chúa Trời dù không hiểu tại sao phải xuống Ai Cập.',
'["Cựu Ước","Tin cậy","Kế hoạch"]','Genesis 46:1-34','vi',true,NOW(),NOW()),

('q-genH-065','Genesis',47,1-31,'hard','multiple_choice_single',
'Việc Gia-cốp chúc phước cho Pha-ra-ôn cho thấy điều gì về sự chúc phước?',
'["Người tin kính có thể chúc phước cho người khác", "Chỉ nhận", "Không thể", "Tình cờ"]',
'[0]',
'Gia-cốp chúc phước cho Pha-ra-ôn, cho thấy người tin kính có thể chúc phước.',
'["Cựu Ước","Chúc phước","Tin kính"]','Genesis 47:1-31','vi',true,NOW(),NOW()),

('q-genH-066','Genesis',48,1-22,'hard','multiple_choice_single',
'Việc Gia-cốp chúc phước cho Ép-ra-im trước Ma-na-se cho thấy điều gì về sự chọn lựa?',
'["Đức Chúa Trời có thể chọn người nhỏ hơn", "Chỉ người lớn", "Không thể", "Tình cờ"]',
'[0]',
'Dù Ma-na-se là con trưởng, Gia-cốp chúc phước cho Ép-ra-im trước.',
'["Cựu Ước","Chọn lựa","Con trưởng"]','Genesis 48:1-22','vi',true,NOW(),NOW()),

('q-genH-067','Genesis',49,1-28,'hard','multiple_choice_single',
'Lời chúc phước của Gia-cốp cho các con cho thấy điều gì về sự tiên tri?',
'["Lời chúc phước có thể chứa đựng lời tiên tri", "Chỉ là lời chúc", "Không có ý nghĩa", "Tình cờ"]',
'[0]',
'Lời chúc phước của Gia-cốp chứa đựng lời tiên tri về tương lai các chi phái.',
'["Cựu Ước","Tiên tri","Chúc phước"]','Genesis 49:1-28','vi',true,NOW(),NOW()),

('q-genH-068','Genesis',50,1-14,'hard','multiple_choice_single',
'Việc Giô-sép đưa xác Gia-cốp về Ca-na-an cho thấy điều gì về lòng hiếu thảo?',
'["Hiếu thảo đòi hỏi sự hy sinh và vâng lời", "Chỉ khi thuận tiện", "Không cần thiết", "Tình cờ"]',
'[0]',
'Giô-sép hy sinh để đưa xác cha về đất hứa theo lời thề.',
'["Cựu Ước","Hiếu thảo","Hy sinh"]','Genesis 50:1-14','vi',true,NOW(),NOW()),

('q-genH-069','Genesis',50,15-21,'hard','multiple_choice_single',
'Lời nói "Đức Chúa Trời toan làm điều lành" của Giô-sép cho thấy điều gì về quan phòng?',
'["Đức Chúa Trời có thể biến điều ác thành điều lành", "Không thể", "Chỉ điều tốt", "Tình cờ"]',
'[0]',
'Giô-sép hiểu rằng Đức Chúa Trời đã biến ý định ác của anh em thành điều lành.',
'["Cựu Ước","Quan phòng","Biến đổi"]','Genesis 50:15-21','vi',true,NOW(),NOW()),

('q-genH-070','Genesis',50,22-26,'hard','multiple_choice_single',
'Lời hứa của Giô-sép về việc đưa xương cốt về Ca-na-an cho thấy điều gì về đức tin?',
'["Đức tin vào lời hứa của Đức Chúa Trời về đất hứa", "Chỉ là hy vọng", "Không có ý nghĩa", "Tình cờ"]',
'[0]',
'Giô-sép tin chắc rằng Đức Chúa Trời sẽ đưa dân Y-sơ-ra-ên về đất hứa.',
'["Cựu Ước","Đức tin","Đất hứa"]','Genesis 50:22-26','vi',true,NOW(),NOW()),

-- Batch 3: Deep theological and philosophical analysis (50 questions)
('q-genH-071','Genesis',1,1,1,'hard','multiple_choice_single',
'Cụm từ "Ban đầu" (bereshit) trong 1:1 có ý nghĩa triết học gì?',
'["Khởi điểm tuyệt đối của thời gian và không gian", "Chỉ là thời điểm", "Tương đối", "Không có ý nghĩa"]',
'[0]',
'Bereshit khẳng định khởi điểm tuyệt đối, không phải chu kỳ vô tận.',
'["Cựu Ước","Triết học","Thời gian"]','Genesis 1:1','vi',true,NOW(),NOW()),

('q-genH-072','Genesis',1,2,2,'hard','multiple_choice_single',
'Cụm từ "Thần của Đức Chúa Trời" trong 1:2 cho thấy điều gì về Ba Ngôi?',
'["Thánh Linh hiện diện trong công cuộc sáng tạo", "Chỉ có Chúa Cha", "Không có ý nghĩa", "Tình cờ"]',
'[0]',
'Thánh Linh hiện diện từ đầu trong công cuộc sáng tạo.',
'["Cựu Ước","Ba Ngôi","Thánh Linh"]','Genesis 1:2','vi',true,NOW(),NOW()),

('q-genH-073','Genesis',1,3,5,'hard','multiple_choice_single',
'Việc Đức Chúa Trời "gọi" ánh sáng cho thấy điều gì về quyền năng Ngài?',
'["Lời phán có quyền năng tạo dựng", "Chỉ là mệnh lệnh", "Không có quyền năng", "Tình cờ"]',
'[0]',
'Lời phán của Đức Chúa Trời có quyền năng tạo dựng từ hư không.',
'["Cựu Ước","Quyền năng","Lời phán"]','Genesis 1:3-5','vi',true,NOW(),NOW()),

('q-genH-074','Genesis',1,6,8,'hard','multiple_choice_single',
'Việc tạo ra "vòm trời" (raqia) cho thấy quan điểm gì về vũ trụ?',
'["Vũ trụ có cấu trúc có tổ chức", "Hỗn mang", "Không có cấu trúc", "Tình cờ"]',
'[0]',
'Vòm trời tách biệt nước trên và dưới, tạo cấu trúc có tổ chức.',
'["Cựu Ước","Vũ trụ","Cấu trúc"]','Genesis 1:6-8','vi',true,NOW(),NOW()),

('q-genH-075','Genesis',1,9,13,'hard','multiple_choice_single',
'Việc tạo ra đất và biển riêng biệt cho thấy điều gì về sự đa dạng?',
'["Đức Chúa Trời tạo ra sự đa dạng có mục đích", "Chỉ là tình cờ", "Không có mục đích", "Hỗn mang"]',
'[0]',
'Đất và biển riêng biệt tạo ra môi trường đa dạng cho sự sống.',
'["Cựu Ước","Đa dạng","Mục đích"]','Genesis 1:9-13','vi',true,NOW(),NOW()),

('q-genH-076','Genesis',1,14-19,'hard','multiple_choice_single',
'Việc tạo ra mặt trời, mặt trăng và các ngôi sao cho thấy điều gì về thời gian?',
'["Thời gian được thiết lập bởi các thiên thể", "Thời gian tự nhiên", "Không có ý nghĩa", "Tình cờ"]',
'[0]',
'Các thiên thể được tạo ra để định thời gian và mùa.',
'["Cựu Ước","Thời gian","Thiên thể"]','Genesis 1:14-19','vi',true,NOW(),NOW()),

('q-genH-077','Genesis',1,20-23,'hard','multiple_choice_single',
'Việc tạo ra sinh vật biển và chim trước cho thấy điều gì về sự tiến hóa?',
'["Sự sống bắt đầu từ môi trường nước", "Từ đất", "Tình cờ", "Không có ý nghĩa"]',
'[0]',
'Sinh vật biển và chim được tạo ra trước, cho thấy sự sống bắt đầu từ nước.',
'["Cựu Ước","Sự sống","Môi trường"]','Genesis 1:20-23','vi',true,NOW(),NOW()),

('q-genH-078','Genesis',1,24-25,'hard','multiple_choice_single',
'Việc tạo ra thú vật "tùy theo loại" cho thấy điều gì về sự đa dạng sinh học?',
'["Đức Chúa Trời tạo ra sự đa dạng có mục đích", "Tình cờ", "Không có mục đích", "Hỗn mang"]',
'[0]',
'Mỗi loài được tạo ra "tùy theo loại" với đặc điểm riêng.',
'["Cựu Ước","Đa dạng","Loài"]','Genesis 1:24-25','vi',true,NOW(),NOW()),

('q-genH-079','Genesis',1,26-28,'hard','multiple_choice_single',
'Việc con người được tạo "theo hình ảnh Đức Chúa Trời" cho thấy điều gì về nhân phẩm?',
'["Con người có giá trị tuyệt đối", "Tương đối", "Không có giá trị", "Tình cờ"]',
'[0]',
'Hình ảnh Đức Chúa Trời cho con người giá trị tuyệt đối.',
'["Cựu Ước","Nhân phẩm","Giá trị"]','Genesis 1:26-28','vi',true,NOW(),NOW()),

('q-genH-080','Genesis',1,29-30,'hard','multiple_choice_single',
'Việc Đức Chúa Trời ban thức ăn cho con người và thú vật cho thấy điều gì về sự quan tâm?',
'["Đức Chúa Trời quan tâm đến nhu cầu của tạo vật", "Không quan tâm", "Tình cờ", "Không có ý nghĩa"]',
'[0]',
'Đức Chúa Trời cung cấp thức ăn cho tất cả tạo vật.',
'["Cựu Ước","Quan tâm","Cung cấp"]','Genesis 1:29-30','vi',true,NOW(),NOW()),

('q-genH-081','Genesis',2,1-3,'hard','multiple_choice_single',
'Việc Đức Chúa Trời "nghỉ ngơi" ngày thứ bảy cho thấy điều gì về sự hoàn thành?',
'["Công cuộc sáng tạo đã hoàn thành", "Chưa hoàn thành", "Tình cờ", "Không có ý nghĩa"]',
'[0]',
'Đức Chúa Trời nghỉ ngơi vì công cuộc sáng tạo đã hoàn thành.',
'["Cựu Ước","Hoàn thành","Nghỉ ngơi"]','Genesis 2:1-3','vi',true,NOW(),NOW()),

('q-genH-082','Genesis',2,4-7,'hard','multiple_choice_single',
'Việc tạo ra con người từ "bụi đất" cho thấy điều gì về bản chất con người?',
'["Con người có bản chất vật chất và tinh thần", "Chỉ vật chất", "Chỉ tinh thần", "Tình cờ"]',
'[0]',
'Con người được tạo từ bụi đất (vật chất) và hơi thở (tinh thần).',
'["Cựu Ước","Bản chất","Vật chất-tinh thần"]','Genesis 2:4-7','vi',true,NOW(),NOW()),

('q-genH-083','Genesis',2,8-9,'hard','multiple_choice_single',
'Việc đặt con người trong vườn Ê-đen cho thấy điều gì về môi trường sống?',
'["Con người được tạo ra trong môi trường hoàn hảo", "Không hoàn hảo", "Tình cờ", "Không có ý nghĩa"]',
'[0]',
'Vườn Ê-đen là môi trường hoàn hảo cho con người.',
'["Cựu Ước","Môi trường","Hoàn hảo"]','Genesis 2:8-9','vi',true,NOW(),NOW()),

('q-genH-084','Genesis',2,15-17,'hard','multiple_choice_single',
'Việc ban mệnh lệnh "không được ăn" cho thấy điều gì về sự tự do?',
'["Tự do đòi hỏi sự lựa chọn có trách nhiệm", "Không có tự do", "Tự do tuyệt đối", "Tình cờ"]',
'[0]',
'Mệnh lệnh tạo ra sự lựa chọn, cơ sở của tự do thật.',
'["Cựu Ước","Tự do","Lựa chọn"]','Genesis 2:15-17','vi',true,NOW(),NOW()),

('q-genH-085','Genesis',2,18-25,'hard','multiple_choice_single',
'Việc tạo ra người nữ "làm trợ giúp thích hợp" cho thấy điều gì về hôn nhân?',
'["Hôn nhân là sự bổ sung hoàn hảo", "Không cần thiết", "Tình cờ", "Không có ý nghĩa"]',
'[0]',
'Người nữ được tạo ra để bổ sung cho người nam một cách hoàn hảo.',
'["Cựu Ước","Hôn nhân","Bổ sung"]','Genesis 2:18-25','vi',true,NOW(),NOW()),

('q-genH-086','Genesis',3,1-5,'hard','multiple_choice_single',
'Việc con rắn "nói chuyện" với Ê-va cho thấy điều gì về sự cám dỗ?',
'["Cám dỗ thường đến từ nguồn bất ngờ", "Chỉ từ người", "Không có cám dỗ", "Tình cờ"]',
'[0]',
'Cám dỗ đến từ con rắn, nguồn bất ngờ và nguy hiểm.',
'["Cựu Ước","Cám dỗ","Nguồn"]','Genesis 3:1-5','vi',true,NOW(),NOW()),

('q-genH-087','Genesis',3,6-7,'hard','multiple_choice_single',
'Việc A-đam và Ê-va "mở mắt" sau khi ăn trái cấm cho thấy điều gì về tội lỗi?',
'["Tội lỗi thay đổi nhận thức về bản thân", "Không thay đổi", "Tích cực", "Tình cờ"]',
'[0]',
'Tội lỗi làm thay đổi nhận thức về bản thân và thế giới.',
'["Cựu Ước","Tội lỗi","Nhận thức"]','Genesis 3:6-7','vi',true,NOW(),NOW()),

('q-genH-088','Genesis',3,8-13,'hard','multiple_choice_single',
'Việc A-đam và Ê-va "trốn" khỏi Đức Chúa Trời cho thấy điều gì về hậu quả tội lỗi?',
'["Tội lỗi làm đứt đoạn mối quan hệ với Đức Chúa Trời", "Không ảnh hưởng", "Tích cực", "Tình cờ"]',
'[0]',
'Tội lỗi làm đứt đoạn mối quan hệ thân mật với Đức Chúa Trời.',
'["Cựu Ước","Hậu quả","Mối quan hệ"]','Genesis 3:8-13','vi',true,NOW(),NOW()),

('q-genH-089','Genesis',3,14-19,'hard','multiple_choice_single',
'Việc Đức Chúa Trời "rủa sả" con rắn, đất và con người cho thấy điều gì về công lý?',
'["Công lý đòi hỏi hậu quả tương xứng", "Không có hậu quả", "Tình cờ", "Không có ý nghĩa"]',
'[0]',
'Mỗi bên nhận hậu quả tương xứng với hành động của mình.',
'["Cựu Ước","Công lý","Hậu quả"]','Genesis 3:14-19','vi',true,NOW(),NOW()),

('q-genH-090','Genesis',3,20-21,'hard','multiple_choice_single',
'Việc Đức Chúa Trời "làm áo da" cho A-đam và Ê-va cho thấy điều gì về ân điển?',
'["Ân điển vượt qua sự phán xét", "Chỉ phán xét", "Không có ân điển", "Tình cờ"]',
'[0]',
'Dù có phán xét, Đức Chúa Trời vẫn cung cấp sự che chở.',
'["Cựu Ước","Ân điển","Che chở"]','Genesis 3:20-21','vi',true,NOW(),NOW()),

('q-genH-091','Genesis',3,22-24,'hard','multiple_choice_single',
'Việc đuổi A-đam và Ê-va khỏi vườn Ê-đen cho thấy điều gì về sự bảo vệ?',
'["Đức Chúa Trời bảo vệ con người khỏi sự chết vĩnh viễn", "Trừng phạt", "Không quan tâm", "Tình cờ"]',
'[0]',
'Đuổi khỏi vườn để ngăn con người ăn trái cây sự sống và chết vĩnh viễn.',
'["Cựu Ước","Bảo vệ","Sự chết"]','Genesis 3:22-24','vi',true,NOW(),NOW()),

('q-genH-092','Genesis',4,1-2,'hard','multiple_choice_single',
'Việc Ca-in và A-bên được sinh ra cho thấy điều gì về sự sinh sản?',
'["Sinh sản là ân điển từ Đức Chúa Trời", "Tự nhiên", "Tình cờ", "Không có ý nghĩa"]',
'[0]',
'Dù sau sa ngã, sinh sản vẫn là ân điển từ Đức Chúa Trời.',
'["Cựu Ước","Sinh sản","Ân điển"]','Genesis 4:1-2','vi',true,NOW(),NOW()),

('q-genH-093','Genesis',4,3-5,'hard','multiple_choice_single',
'Việc Đức Chúa Trời nhận của lễ A-bên mà không nhận Ca-in cho thấy điều gì về của lễ?',
'["Của lễ phải dâng với đức tin và lòng thành", "Chỉ cần dâng", "Không quan trọng", "Tình cờ"]',
'[0]',
'Của lễ được nhận dựa trên tấm lòng, không phải giá trị vật chất.',
'["Cựu Ước","Của lễ","Tấm lòng"]','Genesis 4:3-5','vi',true,NOW(),NOW()),

('q-genH-094','Genesis',4,6-7,'hard','multiple_choice_single',
'Lời cảnh báo của Đức Chúa Trời với Ca-in cho thấy điều gì về sự lựa chọn?',
'["Con người có thể chọn làm chủ tội lỗi", "Không thể", "Tình cờ", "Không có ý nghĩa"]',
'[0]',
'Đức Chúa Trời khuyến khích Ca-in chọn làm chủ tội lỗi.',
'["Cựu Ước","Lựa chọn","Làm chủ"]','Genesis 4:6-7','vi',true,NOW(),NOW()),

('q-genH-095','Genesis',4,8-16,'hard','multiple_choice_single',
'Việc Ca-in giết A-bên cho thấy điều gì về sự leo thang của tội lỗi?',
'["Tội lỗi có thể leo thang từ ghen tị đến giết người", "Không leo thang", "Tình cờ", "Không có ý nghĩa"]',
'[0]',
'Ghen tị dẫn đến giết người, cho thấy sự leo thang của tội lỗi.',
'["Cựu Ước","Leo thang","Tội lỗi"]','Genesis 4:8-16','vi',true,NOW(),NOW()),

('q-genH-096','Genesis',4,17-24,'hard','multiple_choice_single',
'Việc dòng dõi Ca-in phát triển văn minh cho thấy điều gì về tài năng con người?',
'["Con người vẫn có tài năng dù bị tội lỗi", "Mất hết tài năng", "Tình cờ", "Không có ý nghĩa"]',
'[0]',
'Dù bị tội lỗi, con người vẫn có thể phát triển văn minh.',
'["Cựu Ước","Tài năng","Văn minh"]','Genesis 4:17-24','vi',true,NOW(),NOW()),

('q-genH-097','Genesis',4,25-26,'hard','multiple_choice_single',
'Việc Sết được sinh ra cho thấy điều gì về sự hy vọng?',
'["Đức Chúa Trời ban hy vọng qua dòng dõi mới", "Không có hy vọng", "Tình cờ", "Không có ý nghĩa"]',
'[0]',
'Sết được sinh ra thay thế A-bên, mang lại hy vọng mới.',
'["Cựu Ước","Hy vọng","Dòng dõi"]','Genesis 4:25-26','vi',true,NOW(),NOW()),

('q-genH-098','Genesis',5,1-32,'hard','multiple_choice_single',
'Việc ghi chép tuổi thọ của các tổ phụ cho thấy điều gì về sự chết?',
'["Sự chết là hậu quả của tội lỗi", "Tự nhiên", "Tình cờ", "Không có ý nghĩa"]',
'[0]',
'Tuổi thọ giảm dần cho thấy sự chết là hậu quả của tội lỗi.',
'["Cựu Ước","Sự chết","Tuổi thọ"]','Genesis 5:1-32','vi',true,NOW(),NOW()),

('q-genH-099','Genesis',6,1-4,'hard','multiple_choice_single',
'Việc "con trai Đức Chúa Trời" kết hôn với "con gái loài người" cho thấy điều gì về sự suy đồi?',
'["Sự suy đồi đạo đức lan rộng", "Không suy đồi", "Tình cờ", "Không có ý nghĩa"]',
'[0]',
'Sự kết hôn giữa dòng tin kính và không tin kính dẫn đến suy đồi.',
'["Cựu Ước","Suy đồi","Kết hôn"]','Genesis 6:1-4','vi',true,NOW(),NOW()),

('q-genH-100','Genesis',6,5-8,'hard','multiple_choice_single',
'Việc Đức Chúa Trời "ăn năn" đã tạo ra loài người cho thấy điều gì về sự đau khổ?',
'["Đức Chúa Trời đau khổ vì tội lỗi con người", "Không đau khổ", "Tình cờ", "Không có ý nghĩa"]',
'[0]',
'Đức Chúa Trời đau khổ vì tội lỗi và bạo ác của loài người.',
'["Cựu Ước","Đau khổ","Tội lỗi"]','Genesis 6:5-8','vi',true,NOW(),NOW()),

('q-genH-101','Genesis',6,9-22,'hard','multiple_choice_single',
'Việc Nô-ê được mô tả là "công bình và trọn vẹn" cho thấy điều gì về sự công bình?',
'["Công bình có thể tồn tại trong thế giới tội lỗi", "Không thể", "Tình cờ", "Không có ý nghĩa"]',
'[0]',
'Dù trong thế giới tội lỗi, vẫn có người công bình như Nô-ê.',
'["Cựu Ước","Công bình","Tồn tại"]','Genesis 6:9-22','vi',true,NOW(),NOW()),

('q-genH-102','Genesis',7,1-24,'hard','multiple_choice_single',
'Việc cơn lụt hủy diệt toàn bộ loài người cho thấy điều gì về sự phán xét?',
'["Phán xét có thể toàn diện và triệt để", "Không toàn diện", "Tình cờ", "Không có ý nghĩa"]',
'[0]',
'Cơn lụt là sự phán xét toàn diện đối với tội lỗi loài người.',
'["Cựu Ước","Phán xét","Toàn diện"]','Genesis 7:1-24','vi',true,NOW(),NOW()),

('q-genH-103','Genesis',8,1-22,'hard','multiple_choice_single',
'Việc Đức Chúa Trời "nhớ đến" Nô-ê cho thấy điều gì về sự quan tâm?',
'["Đức Chúa Trời không quên những người công bình", "Có thể quên", "Tình cờ", "Không có ý nghĩa"]',
'[0]',
'Đức Chúa Trời nhớ đến Nô-ê và cứu ông khỏi cơn lụt.',
'["Cựu Ước","Quan tâm","Nhớ"]','Genesis 8:1-22','vi',true,NOW(),NOW()),

('q-genH-104','Genesis',9,1-17,'hard','multiple_choice_single',
'Việc thiết lập giao ước với Nô-ê cho thấy điều gì về sự tha thứ?',
'["Đức Chúa Trời tha thứ và bắt đầu lại", "Không tha thứ", "Tình cờ", "Không có ý nghĩa"]',
'[0]',
'Giao ước Nô-ê cho thấy Đức Chúa Trời tha thứ và bắt đầu lại.',
'["Cựu Ước","Tha thứ","Giao ước"]','Genesis 9:1-17','vi',true,NOW(),NOW()),

('q-genH-105','Genesis',9,18-29,'hard','multiple_choice_single',
'Việc Nô-ê say rượu và bị con trai nhạo báng cho thấy điều gì về sự yếu đuối?',
'["Ngay cả người công bình cũng có thể yếu đuối", "Không yếu đuối", "Tình cờ", "Không có ý nghĩa"]',
'[0]',
'Dù là người công bình, Nô-ê vẫn có thể yếu đuối.',
'["Cựu Ước","Yếu đuối","Công bình"]','Genesis 9:18-29','vi',true,NOW(),NOW()),

('q-genH-106','Genesis',10,1-32,'hard','multiple_choice_single',
'Việc ghi chép các dân tộc từ ba con trai Nô-ê cho thấy điều gì về sự đa dạng?',
'["Đức Chúa Trời tạo ra sự đa dạng dân tộc", "Không đa dạng", "Tình cờ", "Không có ý nghĩa"]',
'[0]',
'Từ ba con trai Nô-ê sinh ra tất cả các dân tộc trên đất.',
'["Cựu Ước","Đa dạng","Dân tộc"]','Genesis 10:1-32','vi',true,NOW(),NOW()),

('q-genH-107','Genesis',11,1-9,'hard','multiple_choice_single',
'Việc tháp Ba-bên bị phân tán cho thấy điều gì về sự kiêu ngạo?',
'["Kiêu ngạo dẫn đến sự phân tán", "Không ảnh hưởng", "Tích cực", "Tình cờ"]',
'[0]',
'Kiêu ngạo của con người dẫn đến sự phân tán ngôn ngữ.',
'["Cựu Ước","Kiêu ngạo","Phân tán"]','Genesis 11:1-9','vi',true,NOW(),NOW()),

('q-genH-108','Genesis',11,10-32,'hard','multiple_choice_single',
'Việc ghi chép dòng dõi từ Sết đến Áp-ram cho thấy điều gì về sự liên tục?',
'["Dòng dõi tin kính được bảo tồn", "Bị đứt đoạn", "Tình cờ", "Không có ý nghĩa"]',
'[0]',
'Dòng dõi tin kính từ Sết được bảo tồn đến Áp-ram.',
'["Cựu Ước","Liên tục","Dòng dõi"]','Genesis 11:10-32','vi',true,NOW(),NOW()),

('q-genH-109','Genesis',12,1-9,'hard','multiple_choice_single',
'Việc Áp-ram vâng lời Đức Chúa Trời rời khỏi quê hương cho thấy điều gì về đức tin?',
'["Đức tin đòi hỏi sự hy sinh và vâng phục", "Không cần hy sinh", "Tình cờ", "Không có ý nghĩa"]',
'[0]',
'Áp-ram hy sinh quê hương để vâng lời Đức Chúa Trời.',
'["Cựu Ước","Đức tin","Hy sinh"]','Genesis 12:1-9','vi',true,NOW(),NOW()),

('q-genH-110','Genesis',12,10-20,'hard','multiple_choice_single',
'Việc Áp-ram nói dối về Sa-rai ở Ai Cập cho thấy điều gì về sự yếu đuối?',
'["Ngay cả người tin kính cũng có thể yếu đuối", "Không yếu đuối", "Tình cờ", "Không có ý nghĩa"]',
'[0]',
'Dù tin kính, Áp-ram vẫn có thể yếu đuối và nói dối.',
'["Cựu Ước","Yếu đuối","Tin kính"]','Genesis 12:10-20','vi',true,NOW(),NOW()),

('q-genH-111','Genesis',13,1-18,'hard','multiple_choice_single',
'Việc Áp-ram nhường đất tốt cho Lót cho thấy điều gì về sự rộng lượng?',
'["Rộng lượng có thể dẫn đến phước lành", "Không dẫn đến", "Tình cờ", "Không có ý nghĩa"]',
'[0]',
'Áp-ram nhường đất tốt cho Lót và được Đức Chúa Trời ban phước.',
'["Cựu Ước","Rộng lượng","Phước lành"]','Genesis 13:1-18','vi',true,NOW(),NOW()),

('q-genH-112','Genesis',14,1-24,'hard','multiple_choice_single',
'Việc Áp-ram cứu Lót và từ chối của cải vua Sô-đôm cho thấy điều gì về sự công bình?',
'["Công bình đòi hỏi sự hy sinh và từ chối lợi ích", "Không cần hy sinh", "Tình cờ", "Không có ý nghĩa"]',
'[0]',
'Áp-ram cứu Lót và từ chối của cải để giữ sự công bình.',
'["Cựu Ước","Công bình","Hy sinh"]','Genesis 14:1-24','vi',true,NOW(),NOW()),

('q-genH-113','Genesis',15,1-21,'hard','multiple_choice_single',
'Việc Đức Chúa Trời lập giao ước với Áp-ram cho thấy điều gì về sự cam kết?',
'["Đức Chúa Trời cam kết với những người tin kính", "Không cam kết", "Tình cờ", "Không có ý nghĩa"]',
'[0]',
'Đức Chúa Trời lập giao ước với Áp-ram để cam kết lời hứa.',
'["Cựu Ước","Cam kết","Giao ước"]','Genesis 15:1-21','vi',true,NOW(),NOW()),

('q-genH-114','Genesis',16,1-16,'hard','multiple_choice_single',
'Việc A-ga sinh Ích-ma-ên cho thấy điều gì về hậu quả của sự vội vàng?',
'["Vội vàng có thể dẫn đến hậu quả lâu dài", "Không có hậu quả", "Tình cờ", "Không có ý nghĩa"]',
'[0]',
'Việc vội vàng của Sa-rai dẫn đến hậu quả lâu dài với Ích-ma-ên.',
'["Cựu Ước","Vội vàng","Hậu quả"]','Genesis 16:1-16','vi',true,NOW(),NOW()),

('q-genH-115','Genesis',17,1-27,'hard','multiple_choice_single',
'Việc đổi tên Áp-ram thành Áp-ra-ham cho thấy điều gì về sự thay đổi?',
'["Tên mới phản ánh sự thay đổi trong mối quan hệ", "Không thay đổi", "Tình cờ", "Không có ý nghĩa"]',
'[0]',
'Tên mới "Áp-ra-ham" phản ánh vai trò mới là cha của nhiều dân tộc.',
'["Cựu Ước","Thay đổi","Tên"]','Genesis 17:1-27','vi',true,NOW(),NOW()),

('q-genH-116','Genesis',18,1-15,'hard','multiple_choice_single',
'Việc ba người khách đến thăm Áp-ra-ham cho thấy điều gì về sự hiếu khách?',
'["Hiếu khách có thể dẫn đến phước lành bất ngờ", "Không dẫn đến", "Tình cờ", "Không có ý nghĩa"]',
'[0]',
'Hiếu khách của Áp-ra-ham dẫn đến lời hứa về Y-sác.',
'["Cựu Ước","Hiếu khách","Phước lành"]','Genesis 18:1-15','vi',true,NOW(),NOW()),

('q-genH-117','Genesis',18,16-33,'hard','multiple_choice_single',
'Việc Áp-ra-ham cầu thay cho Sô-đôm cho thấy điều gì về sự cầu thay?',
'["Cầu thay có thể thay đổi ý định của Đức Chúa Trời", "Không thể", "Tình cờ", "Không có ý nghĩa"]',
'[0]',
'Áp-ra-ham cầu thay cho Sô-đôm và Đức Chúa Trời lắng nghe.',
'["Cựu Ước","Cầu thay","Lắng nghe"]','Genesis 18:16-33','vi',true,NOW(),NOW()),

('q-genH-118','Genesis',19,1-29,'hard','multiple_choice_single',
'Việc Lót được cứu khỏi Sô-đôm cho thấy điều gì về sự công bình?',
'["Đức Chúa Trời cứu những người công bình", "Không cứu", "Tình cờ", "Không có ý nghĩa"]',
'[0]',
'Dù sống trong thành tội lỗi, Lót vẫn được cứu vì sự công bình.',
'["Cựu Ước","Công bình","Cứu"]','Genesis 19:1-29','vi',true,NOW(),NOW()),

('q-genH-119','Genesis',20,1-18,'hard','multiple_choice_single',
'Việc Áp-ra-ham lại nói dối về Sa-rai cho thấy điều gì về sự lặp lại?',
'["Con người có xu hướng lặp lại sai lầm cũ", "Không lặp lại", "Tình cờ", "Không có ý nghĩa"]',
'[0]',
'Áp-ra-ham lặp lại sai lầm cũ ở Ai Cập.',
'["Cựu Ước","Lặp lại","Sai lầm"]','Genesis 20:1-18','vi',true,NOW(),NOW()),

('q-genH-120','Genesis',21,1-21,'hard','multiple_choice_single',
'Việc Y-sác được sinh ra và Ích-ma-ên bị đuổi cho thấy điều gì về sự thay thế?',
'["Con của lời hứa thay thế con của xác thịt", "Không thay thế", "Tình cờ", "Không có ý nghĩa"]',
'[0]',
'Y-sác (con của lời hứa) thay thế Ích-ma-ên (con của xác thịt).',
'["Cựu Ước","Thay thế","Lời hứa"]','Genesis 21:1-21','vi',true,NOW(),NOW());


