-- Repeatable seed: Matthew questions (contents from resources/matthew-questions.sql)
-- Câu hỏi về Ma-thi-ơ (Matthew) - 20 câu
INSERT IGNORE INTO questions (id, book, chapter, verse_start, verse_end, difficulty, type, content, options, correct_answer, explanation, tags, source, language, is_active, created_at, updated_at) VALUES

-- Câu hỏi dễ (6 câu)
('q-mat-001', 'Matthew', 1, 21, 21, 'easy', 'multiple_choice_single',
'Thiên sứ bảo Joseph đặt tên con trai là gì?',
'["Giê-su", "Em-ma-nu-ên", "Christ", "Messiah"]',
'[0]',
'Kinh Thánh ghi: "Ngươi sẽ đặt tên con trai là Giê-su" (Ma-thi-ơ 1:21).',
'["Tân Ước", "Chúa Giê-su", "Tên"]',
'Matthew 1:21',
'vi',
true,
NOW(),
NOW()),

('q-mat-002', 'Matthew', 2, 1, 1, 'easy', 'multiple_choice_single',
'Chúa Giê-su được sinh ra ở đâu?',
'["Bết-lê-hem", "Giê-ru-sa-lem", "Nazareth", "Galilee"]',
'[0]',
'Kinh Thánh ghi: "Đức Chúa Jêsus sanh tại Bết-lê-hem" (Ma-thi-ơ 2:1).',
'["Tân Ước", "Chúa Giê-su", "Sinh ra"]',
'Matthew 2:1',
'vi',
true,
NOW(),
NOW()),

('q-mat-003', 'Matthew', 3, 16, 16, 'easy', 'multiple_choice_single',
'Khi Chúa Giê-su chịu phép báp-têm, Thánh Linh hiện xuống như gì?',
'["Chim bồ câu", "Ngọn lửa", "Gió mạnh", "Mây"]',
'[0]',
'Kinh Thánh ghi: "Thánh Linh của Đức Chúa Trời ngự xuống trên Ngài như chim bồ câu" (Ma-thi-ơ 3:16).',
'["Tân Ước", "Báp-têm", "Thánh Linh"]',
'Matthew 3:16',
'vi',
true,
NOW(),
NOW()),

('q-mat-004', 'Matthew', 4, 4, 4, 'easy', 'multiple_choice_single',
'Chúa Giê-su trả lời Satan rằng "Người ta sống chẳng phải chỉ nhờ bánh mà thôi, song nhờ mọi lời phán ra từ miệng Đức Chúa Trời" khi bị cám dỗ về điều gì?',
'["Biến đá thành bánh", "Nhảy từ nóc đền thờ", "Thờ lạy Satan", "Làm phép lạ"]',
'[0]',
'Kinh Thánh ghi: "Nếu ngươi là Con Đức Chúa Trời, thì hãy khiến những hòn đá nầy trở nên bánh đi" (Ma-thi-ơ 4:3).',
'["Tân Ước", "Cám dỗ", "Bánh"]',
'Matthew 4:4',
'vi',
true,
NOW(),
NOW()),

('q-mat-005', 'Matthew', 5, 3, 3, 'easy', 'multiple_choice_single',
'Phước đầu tiên trong Bài Giảng Trên Núi là gì?',
'["Phước cho những kẻ có lòng khó khăn", "Phước cho những kẻ than khóc", "Phước cho những kẻ nhu mì", "Phước cho những kẻ đói khát sự công bình"]',
'[0]',
'Kinh Thánh ghi: "Phước cho những kẻ có lòng khó khăn, vì nước thiên đàng là của những kẻ ấy!" (Ma-thi-ơ 5:3).',
'["Tân Ước", "Phước", "Khó khăn"]',
'Matthew 5:3',
'vi',
true,
NOW(),
NOW()),

('q-mat-006', 'Matthew', 6, 9, 9, 'easy', 'multiple_choice_single',
'Lời cầu nguyện "Lạy Cha chúng tôi ở trên trời" bắt đầu như thế nào?',
'["Danh Cha được tôn thánh", "Nước Cha được đến", "Ý Cha được nên", "Cả ba câu trên"]',
'[3]',
'Kinh Thánh ghi: "Lạy Cha chúng tôi ở trên trời! Danh Cha được tôn thánh; Nước Cha được đến; Ý Cha được nên" (Ma-thi-ơ 6:9-10).',
'["Tân Ước", "Cầu nguyện", "Lạy Cha"]',
'Matthew 6:9-10',
'vi',
true,
NOW(),
NOW()),

-- Câu hỏi trung bình (10 câu)
('q-mat-007', 'Matthew', 1, 23, 23, 'medium', 'multiple_choice_single',
'Tên "Em-ma-nu-ên" có nghĩa gì?',
'["Đức Chúa Trời ở cùng chúng ta", "Đức Chúa Trời cứu chúng ta", "Đức Chúa Trời yêu chúng ta", "Đức Chúa Trời tha thứ chúng ta"]',
'[0]',
'Kinh Thánh ghi: "Em-ma-nu-ên, nghĩa là: Đức Chúa Trời ở cùng chúng ta" (Ma-thi-ơ 1:23).',
'["Tân Ước", "Em-ma-nu-ên", "Nghĩa"]',
'Matthew 1:23',
'vi',
true,
NOW(),
NOW()),

('q-mat-008', 'Matthew', 2, 11, 11, 'medium', 'multiple_choice_single',
'Các nhà thông thái đã dâng cho Chúa Giê-su những gì?',
'["Vàng, nhũ hương và mộc dược", "Bạc, vàng và đá quý", "Lúa mì, dầu và rượu", "Quần áo, giày dép và thức ăn"]',
'[0]',
'Kinh Thánh ghi: "Họ mở các hộp báu ra, dâng cho Ngài những lễ vật: vàng, nhũ hương và mộc dược" (Ma-thi-ơ 2:11).',
'["Tân Ước", "Nhà thông thái", "Lễ vật"]',
'Matthew 2:11',
'vi',
true,
NOW(),
NOW()),

('q-mat-009', 'Matthew', 3, 17, 17, 'medium', 'multiple_choice_single',
'Khi Chúa Giê-su chịu phép báp-têm, có tiếng từ trời phán gì?',
'["Nầy là Con yêu dấu của ta", "Nầy là Đấng được chọn", "Nầy là Vua của ta", "Nầy là Đấng cứu thế"]',
'[0]',
'Kinh Thánh ghi: "Có tiếng từ trời phán rằng: Nầy là Con yêu dấu của ta, đẹp lòng ta mọi đường" (Ma-thi-ơ 3:17).',
'["Tân Ước", "Báp-têm", "Tiếng trời"]',
'Matthew 3:17',
'vi',
true,
NOW(),
NOW()),

('q-mat-010', 'Matthew', 4, 19, 19, 'medium', 'multiple_choice_single',
'Chúa Giê-su nói với Simon và Anh-rê rằng "Hãy theo ta, ta sẽ khiến các ngươi trở nên gì?"',
'["Những ngư phủ lưới người", "Những môn đồ", "Những sứ đồ", "Những thầy tế lễ"]',
'[0]',
'Kinh Thánh ghi: "Hãy theo ta, ta sẽ khiến các ngươi trở nên tay đánh lưới người" (Ma-thi-ơ 4:19).',
'["Tân Ước", "Gọi môn đồ", "Đánh lưới"]',
'Matthew 4:19',
'vi',
true,
NOW(),
NOW()),

('q-mat-011', 'Matthew', 5, 14, 14, 'medium', 'multiple_choice_single',
'Chúa Giê-su nói các môn đồ là gì của thế gian?',
'["Muối của đất", "Ánh sáng của thế gian", "Men của bột", "Cả ba câu trên"]',
'[3]',
'Kinh Thánh ghi: "Các ngươi là muối của đất... Các ngươi là sự sáng của thế gian" (Ma-thi-ơ 5:13-14).',
'["Tân Ước", "Muối", "Ánh sáng"]',
'Matthew 5:13-14',
'vi',
true,
NOW(),
NOW()),

('q-mat-012', 'Matthew', 6, 26, 26, 'medium', 'multiple_choice_single',
'Chúa Giê-su nói chim trời không gieo, không gặt, không thâu trữ vào kho, nhưng ai nuôi chúng?',
'["Cha các ngươi ở trên trời", "Đức Chúa Trời", "Thiên nhiên", "Cả ba câu trên"]',
'[0]',
'Kinh Thánh ghi: "Chim trời không gieo, không gặt, không thâu trữ vào kho; song Cha các ngươi ở trên trời nuôi nó" (Ma-thi-ơ 6:26).',
'["Tân Ước", "Chim trời", "Cha"]',
'Matthew 6:26',
'vi',
true,
NOW(),
NOW()),

('q-mat-013', 'Matthew', 7, 12, 12, 'medium', 'multiple_choice_single',
'Chúa Giê-su nói "Hễ điều chi mà các ngươi muốn người ta làm cho mình, thì cũng hãy làm điều đó cho họ" được gọi là gì?',
'["Luật và lời tiên tri", "Điều răn lớn", "Luật vàng", "Lời dạy quan trọng"]',
'[2]',
'Kinh Thánh ghi: "Ấy vậy, hễ điều chi mà các ngươi muốn người ta làm cho mình, thì cũng hãy làm điều đó cho họ, vì ấy là luật pháp và lời tiên tri" (Ma-thi-ơ 7:12).',
'["Tân Ước", "Luật vàng", "Làm cho người"]',
'Matthew 7:12',
'vi',
true,
NOW(),
NOW()),

('q-mat-014', 'Matthew', 8, 26, 26, 'medium', 'multiple_choice_single',
'Khi sóng biển nổi lên, Chúa Giê-su quở trách ai?',
'["Sóng biển", "Gió", "Các môn đồ", "Cả ba câu trên"]',
'[3]',
'Kinh Thánh ghi: "Ngài bèn đứng dậy, quở gió và biển, thì liền yên lặng như tờ" (Ma-thi-ơ 8:26).',
'["Tân Ước", "Phép lạ", "Sóng biển"]',
'Matthew 8:26',
'vi',
true,
NOW(),
NOW()),

('q-mat-015', 'Matthew', 9, 6, 6, 'medium', 'multiple_choice_single',
'Chúa Giê-su nói Con người có quyền gì trên đất?',
'["Tha tội", "Chữa bệnh", "Cả hai câu trên", "Không có quyền gì"]',
'[2]',
'Kinh Thánh ghi: "Vả, để các ngươi biết Con người ở dưới đất có quyền tha tội" (Ma-thi-ơ 9:6).',
'["Tân Ước", "Quyền", "Tha tội"]',
'Matthew 9:6',
'vi',
true,
NOW(),
NOW()),

('q-mat-016', 'Matthew', 10, 28, 28, 'medium', 'multiple_choice_single',
'Chúa Giê-su nói đừng sợ ai có thể giết thân thể mà không giết được linh hồn?',
'["Kẻ ác", "Kẻ thù", "Kẻ bắt bớ", "Cả ba câu trên"]',
'[3]',
'Kinh Thánh ghi: "Đừng sợ kẻ giết thân thể mà không thể giết linh hồn" (Ma-thi-ơ 10:28).',
'["Tân Ước", "Sợ hãi", "Linh hồn"]',
'Matthew 10:28',
'vi',
true,
NOW(),
NOW()),

-- Câu hỏi khó (4 câu)
('q-mat-017', 'Matthew', 5, 17, 17, 'hard', 'multiple_choice_single',
'Chúa Giê-su nói Ngài đến để làm gì với luật pháp?',
'["Hủy bỏ", "Thay đổi", "Làm cho trọn", "Bổ sung"]',
'[2]',
'Kinh Thánh ghi: "Ta đến không phải để phá luật pháp, song để làm cho trọn" (Ma-thi-ơ 5:17).',
'["Tân Ước", "Luật pháp", "Làm cho trọn"]',
'Matthew 5:17',
'vi',
true,
NOW(),
NOW()),

('q-mat-018', 'Matthew', 11, 28, 28, 'hard', 'multiple_choice_single',
'Chúa Giê-su mời gọi ai đến với Ngài?',
'["Hết thảy những ai mệt mỏi và gánh nặng", "Những người tin", "Những người vâng lời", "Những người cầu nguyện"]',
'[0]',
'Kinh Thánh ghi: "Hãy đến cùng ta, hỡi những kẻ mệt mỏi và gánh nặng, ta sẽ cho các ngươi được yên nghỉ" (Ma-thi-ơ 11:28).',
'["Tân Ước", "Mời gọi", "Mệt mỏi"]',
'Matthew 11:28',
'vi',
true,
NOW(),
NOW()),

('q-mat-019', 'Matthew', 16, 18, 18, 'hard', 'multiple_choice_single',
'Chúa Giê-su nói sẽ xây Hội thánh trên gì?',
'["Đá", "Đức tin", "Lời Chúa", "Cả ba câu trên"]',
'[0]',
'Kinh Thánh ghi: "Ta sẽ xây Hội thánh ta trên đá nầy" - ám chỉ lời tuyên xưng của Phi-e-rơ (Ma-thi-ơ 16:18).',
'["Tân Ước", "Hội thánh", "Đá"]',
'Matthew 16:18',
'vi',
true,
NOW(),
NOW()),

('q-mat-020', 'Matthew', 28, 19, 19, 'hard', 'multiple_choice_single',
'Chúa Giê-su truyền cho các môn đồ làm phép báp-têm nhân danh ai?',
'["Cha, Con và Thánh Linh", "Đức Chúa Trời", "Chúa Giê-su Christ", "Cả ba câu trên"]',
'[0]',
'Kinh Thánh ghi: "Hãy đi dạy dỗ muôn dân, hãy nhân danh Đức Cha, Đức Con, và Đức Thánh Linh mà làm phép báp-têm cho họ" (Ma-thi-ơ 28:19).',
'["Tân Ước", "Báp-têm", "Ba Ngôi"]',
'Matthew 28:19',
'vi',
true,
NOW(),
NOW());


