-- Repeatable seed: psalms questions (contents from resources/psalms-questions.sql)
-- Câu hỏi về Thi Thiên (Psalms) - 20 câu
INSERT IGNORE INTO questions (id, book, chapter, verse_start, verse_end, difficulty, type, content, options, correct_answer, explanation, tags, source, language, is_active, created_at, updated_at) VALUES

-- Câu hỏi dễ (6 câu)
('q-psa-001', 'Psalms', 23, 1, 1, 'easy', 'multiple_choice_single',
'Thi Thiên 23 bắt đầu bằng câu gì?',
'["Đức Giê-hô-va là Đấng chăn giữ tôi", "Đức Giê-hô-va là ánh sáng của tôi", "Đức Giê-hô-va là sức mạnh của tôi", "Đức Giê-hô-va là nơi nương náu của tôi"]',
'[0]',
'Kinh Thánh ghi: "Đức Giê-hô-va là Đấng chăn giữ tôi" (Thi 23:1).',
'["Cựu Ước", "Thi Thiên", "Chăn chiên"]',
'Psalms 23:1',
'vi',
true,
NOW(),
NOW()),

('q-psa-002', 'Psalms', 23, 4, 4, 'easy', 'multiple_choice_single',
'Trong Thi Thiên 23, khi đi qua trũng bóng chết, tác giả không sợ vì gì?',
'["Vì có Đức Chúa Trời ở cùng", "Vì có gậy và cây trượng", "Vì có ánh sáng", "Vì có bạn bè"]',
'[1]',
'Kinh Thánh ghi: "Dầu khi tôi đi trong trũng bóng chết, tôi sẽ chẳng sợ tai họa nào; vì Chúa ở cùng tôi" (Thi 23:4).',
'["Cựu Ước", "Thi Thiên", "Không sợ"]',
'Psalms 23:4',
'vi',
true,
NOW(),
NOW()),

('q-psa-003', 'Psalms', 1, 1, 1, 'easy', 'multiple_choice_single',
'Thi Thiên đầu tiên nói về người nào được phước?',
'["Người không đi theo mưu kế của kẻ ác", "Người không đứng trong đường tội nhân", "Người không ngồi trong chỗ của kẻ nhạo báng", "Cả ba câu trên"]',
'[3]',
'Kinh Thánh ghi: "Phước cho người nào chẳng theo mưu kế của kẻ ác, chẳng đứng trong đường tội nhân, không ngồi trong chỗ của kẻ nhạo báng" (Thi 1:1).',
'["Cựu Ước", "Thi Thiên", "Phước"]',
'Psalms 1:1',
'vi',
true,
NOW(),
NOW()),

('q-psa-004', 'Psalms', 100, 1, 1, 'easy', 'multiple_choice_single',
'Thi Thiên 100 kêu gọi làm gì?',
'["Hãy cất tiếng reo mừng cho Đức Giê-hô-va", "Hãy hát thánh ca", "Hãy cầu nguyện", "Hãy thờ phượng"]',
'[0]',
'Kinh Thánh ghi: "Hãy cất tiếng reo mừng cho Đức Giê-hô-va, cả thế gian!" (Thi 100:1).',
'["Cựu Ước", "Thi Thiên", "Reo mừng"]',
'Psalms 100:1',
'vi',
true,
NOW(),
NOW()),

('q-psa-005', 'Psalms', 91, 1, 1, 'easy', 'multiple_choice_single',
'Thi Thiên 91 nói về ai được bảo vệ?',
'["Người ở dưới bóng của Đấng Tối Cao", "Người tin cậy Đức Chúa Trời", "Người yêu mến Chúa", "Người vâng lời"]',
'[0]',
'Kinh Thánh ghi: "Người nào ở nơi kín đáo của Đấng Tối Cao, sẽ được hằng ở dưới bóng của Đấng Toàn năng" (Thi 91:1).',
'["Cựu Ước", "Thi Thiên", "Bảo vệ"]',
'Psalms 91:1',
'vi',
true,
NOW(),
NOW()),

('q-psa-006', 'Psalms', 46, 1, 1, 'easy', 'multiple_choice_single',
'Thi Thiên 46 nói Đức Chúa Trời là gì?',
'["Nơi nương náu và sức mạnh", "Ánh sáng và sự sống", "Tình yêu và lòng thương xót", "Chân lý và công lý"]',
'[0]',
'Kinh Thánh ghi: "Đức Chúa Trời là nơi nương náu và sức mạnh của chúng tôi" (Thi 46:1).',
'["Cựu Ước", "Thi Thiên", "Nương náu"]',
'Psalms 46:1',
'vi',
true,
NOW(),
NOW());


