-- Supplementary: Romans, 1-2 Corinthians, Galatians, Ephesians, Philippians, Hebrews, James, 1 Peter, 1 John, Revelation

-- ==================== ROMANS (need +8) ====================
INSERT IGNORE INTO questions (id, book, chapter, verse_start, verse_end, difficulty, type, content, options, correct_answer, explanation, tags, source, language, is_active, created_at, updated_at) VALUES
('q-rom-008', 'Romans', 1, 16, 16, 'easy', 'multiple_choice_single',
'Phao-lo tuyen bo: "Toi khong ho then ve Phuc Am vi no la ___ cua Duc Chua Troi de cuu moi ke tin"',
'["Quyen phep (suc manh)", "Loi noi", "Ke hoach", "Tri thuc"]',
'[0]', 'Ro-ma 1:16 - Phuc Am la quyen nang (dunamis) cua Chua de cuu roi.', '["Tan Uoc","Phuc Am","Quyen nang"]', 'Romans 1:16', 'vi', true, NOW(), NOW()),
('q-rom-009', 'Romans', 5, 1, 1, 'easy', 'multiple_choice_single',
'Khi duoc xung cong binh boi duc tin, chung ta co ___ voi Duc Chua Troi',
'["Hoa thuan (binh an)", "Chien tranh", "Khoang cach", "No nan"]',
'[0]', 'Ro-ma 5:1 - Cong binh boi duc tin mang lai hoa thuan voi Chua. Toi loi da bi xoa.', '["Tan Uoc","Cong binh","Hoa thuan"]', 'Romans 5:1', 'vi', true, NOW(), NOW()),
('q-rom-010', 'Romans', 5, 3, 4, 'medium', 'multiple_choice_single',
'Ro-ma 5:3-4: Hoan nan sinh nhin nhuc, nhin nhuc sinh ___, trai nghiem sinh hy vong',
'["Su trai nghiem (tinh cach)", "Su vui", "Su giau", "Su manh"]',
'[0]', 'Kho nan la qua trinh tao nen tinh cach va hy vong vung chac.', '["Tan Uoc","Thu thach","Tinh cach"]', 'Romans 5:3-4', 'vi', true, NOW(), NOW()),
('q-rom-011', 'Romans', 6, 1, 2, 'medium', 'multiple_choice_single',
'Phao-lo hoi: Co nen pham toi de an dien cang do them khong?',
'["Doan nhien khong! Chung ta da chet ve toi loi", "Co, an dien du", "Tuy truong hop", "Khong ro"]',
'[0]', 'Ro-ma 6:2 - An dien khong phai la co de pham toi. Nguoi tin that da chet ve toi loi.', '["Tan Uoc","An dien","Thanh khiet"]', 'Romans 6:1-2', 'vi', true, NOW(), NOW()),
('q-rom-012', 'Romans', 8, 1, 1, 'easy', 'fill_in_blank',
'Cho nen hien nay khong con su ___ nao cho nhung ke o trong Chua Gie-su (Ro-ma 8:1)',
'[]', '[]', 'Ro-ma 8:1 - Khong con su dinh toi! Tu do hoan toan cho nguoi o trong Chua Gie-su.', '["Tan Uoc","Tu do","Cong binh"]', 'Romans 8:1', 'vi', true, NOW(), NOW()),
('q-rom-013', 'Romans', 8, 31, 31, 'easy', 'multiple_choice_single',
'Ro-ma 8:31: "Neu Duc Chua Troi vung chung ta thi ai ___ chung ta?"',
'["Dich", "Giup", "Biet", "Hieu"]',
'[0]', 'Neu Chua dung ve phia chung ta, khong ai co the chong lai thanh cong.', '["Tan Uoc","An ninh","Chien thang"]', 'Romans 8:31', 'vi', true, NOW(), NOW()),
('q-rom-014', 'Romans', 12, 1, 1, 'medium', 'multiple_choice_single',
'Phao-lo khuyen dang than the lam gi?',
'["Cua le song va thanh, dep long Chua (su tho phuong phai le)", "Cua le thieu", "Dung cu", "Vu khi"]',
'[0]', 'Ro-ma 12:1 - Tho phuong that la dang ca cuoc doi cho Chua, khong chi trong nha tho.', '["Tan Uoc","Tho phuong","Dang hien"]', 'Romans 12:1', 'vi', true, NOW(), NOW()),
('q-rom-015', 'Romans', 12, 21, 21, 'easy', 'fill_in_blank',
'Dung de dieu ac thang minh nhung hay lay dieu ___ thang dieu ac (Ro-ma 12:21)',
'[]', '[]', 'Ro-ma 12:21 - Chien thang su ac khong bang bao luc ma bang su lanh.', '["Tan Uoc","Dieu lanh","Chien thang"]', 'Romans 12:21', 'vi', true, NOW(), NOW()),

-- ==================== 1 CORINTHIANS (need +12) ====================
('q-1co-004', '1 Corinthians', 1, 18, 18, 'medium', 'multiple_choice_single',
'Dao thap tu gia doi voi ke huong mat la dien dai nhung doi voi chung ta la gi?',
'["Quyen phep cua Duc Chua Troi", "Tri thuc", "Bi an", "Truyen thong"]',
'[0]', '1 Co 1:18 - Thap tu gia la su dien dai theo the gian nhung la quyen nang cuu roi cho nguoi tin.', '["Tan Uoc","Thap tu","Quyen nang"]', '1 Corinthians 1:18', 'vi', true, NOW(), NOW()),
('q-1co-005', '1 Corinthians', 2, 9, 9, 'easy', 'multiple_choice_single',
'1 Co 2:9: Mat chua thay, tai chua nghe, long chua nghi den dieu gi?',
'["Dieu Chua chuan bi cho nhung ai yeu Ngai", "Thien dang", "Phuc Am", "Phep la"]',
'[0]', 'Nhung dieu Chua chuan bi vuot qua tri tuong tuong cua con nguoi.', '["Tan Uoc","Hy vong","Phuc lanh"]', '1 Corinthians 2:9', 'vi', true, NOW(), NOW()),
('q-1co-006', '1 Corinthians', 3, 16, 16, 'easy', 'multiple_choice_single',
'1 Co 3:16: Than the chung ta la gi?',
'["Den tho cua Duc Thanh Linh", "Dung cu cua Chua", "Cua le", "Binh dat"]',
'[0]', 'Than the la den tho Thanh Linh ngu. Phai giu gin thanh khiet.', '["Tan Uoc","Den tho","Thanh Linh"]', '1 Corinthians 3:16', 'vi', true, NOW(), NOW()),
('q-1co-007', '1 Corinthians', 6, 19, 20, 'easy', 'fill_in_blank',
'Than the anh em la den tho cua Duc Thanh Linh. Anh em da duoc mua bang gia ___ (1 Co 6:20)',
'[]', '[]', 'Chua Gie-su tra gia bang mang song Ngai de chuoc chung ta.', '["Tan Uoc","Chuoc toi","Than the"]', '1 Corinthians 6:19-20', 'vi', true, NOW(), NOW()),
('q-1co-008', '1 Corinthians', 9, 24, 24, 'easy', 'multiple_choice_single',
'Phao-lo so sanh doi song tin do voi gi?',
'["Cuoc chay dua, hay chay de duoc giai", "Chien tran", "Buon ban", "Lam nong"]',
'[0]', '1 Co 9:24 - Doi song duc tin giong cuoc dua: can ky luat va no luc de dat dich.', '["Tan Uoc","Ky luat","Cuoc dua"]', '1 Corinthians 9:24', 'vi', true, NOW(), NOW()),
('q-1co-009', '1 Corinthians', 10, 13, 13, 'easy', 'multiple_choice_single',
'1 Co 10:13 hua gi ve su cam do?',
'["Chua khong de bi cam do qua suc chiu va luon cho loi thoat", "Se khong co cam do", "Cam do se het", "Phai tu chiu"]',
'[0]', 'Chua thanh tin: khong de cam do qua suc va luon cung cap loi thoat.', '["Tan Uoc","Cam do","Thanh tin"]', '1 Corinthians 10:13', 'vi', true, NOW(), NOW()),
('q-1co-010', '1 Corinthians', 12, 12, 14, 'medium', 'multiple_choice_single',
'Phao-lo so sanh Hoi thanh nhu gi?',
'["Than the co nhieu chi the, moi chi the deu can thiet", "Quan doi", "Toa nha", "Vuon nho"]',
'[0]', '1 Co 12:12-14 - Moi nguoi co an tu khac nhau nhung deu quan trong nhu cac bo phan trong than the.', '["Tan Uoc","Hoi thanh","An tu"]', '1 Corinthians 12:12-14', 'vi', true, NOW(), NOW()),
('q-1co-011', '1 Corinthians', 13, 1, 3, 'medium', 'multiple_choice_single',
'Neu co tai an tu nhung khong co tinh yeu thuong, Phao-lo noi minh nhu gi?',
'["Dong vang keu hay chap choeng vang", "Nguoi manh me", "Thien su", "Hoc gia"]',
'[0]', '1 Co 13:1 - Moi an tu deu vo gia tri neu khong co tinh yeu thuong.', '["Tan Uoc","Tinh yeu","An tu"]', '1 Corinthians 13:1-3', 'vi', true, NOW(), NOW()),
('q-1co-012', '1 Corinthians', 15, 55, 57, 'easy', 'fill_in_blank',
'Hoi su chet, noc doc nguoi o dau? Hoi am phu, su thang cua nguoi o dau? Cam ta Duc Chua Troi da cho chung ta su ___ boi Chua Gie-su',
'[]', '[]', '1 Co 15:55-57 - Chua Gie-su chien thang su chet. Su chet khong con quyen tren nguoi tin.', '["Tan Uoc","Phuc sinh","Chien thang"]', '1 Corinthians 15:55-57', 'vi', true, NOW(), NOW()),
('q-1co-013', '1 Corinthians', 15, 58, 58, 'easy', 'multiple_choice_single',
'1 Co 15:58 ket luan: Hay vung vang, lam viec Chua cach du day vi biet rang cong kho minh trong Chua se khong ___',
'["Vo ich", "Quen", "Mat", "Tre"]',
'[0]', 'Moi cong kho lam cho Chua deu co gia tri doi doi, khong bao gio uong phi.', '["Tan Uoc","Lam viec","Hy vong"]', '1 Corinthians 15:58', 'vi', true, NOW(), NOW()),
('q-1co-014', '1 Corinthians', 10, 31, 31, 'easy', 'multiple_choice_single',
'1 Co 10:31: Du an uong hay lam gi, hay lam tat ca vi ___ cua Duc Chua Troi',
'["Su vinh hien", "Su vui", "Loi ich", "Danh tieng"]',
'[0]', 'Moi hanh dong, du nho nhat, co the la hanh dong ton vinh Chua.', '["Tan Uoc","Vinh hien","Doi song"]', '1 Corinthians 10:31', 'vi', true, NOW(), NOW()),
('q-1co-015', '1 Corinthians', 16, 13, 14, 'easy', 'multiple_choice_single',
'1 Co 16:13-14 khuyen lam moi dieu trong tinh gi?',
'["Yeu thuong", "So hai", "Hy vong", "Cong binh"]',
'[0]', 'Tinh giac, vung tin, can dam, manh me - nhung lam moi dieu trong tinh yeu thuong.', '["Tan Uoc","Yeu thuong","Doi song"]', '1 Corinthians 16:13-14', 'vi', true, NOW(), NOW()),

-- ==================== 2 CORINTHIANS (need +13) ====================
('q-2co-003', '2 Corinthians', 1, 3, 4, 'easy', 'multiple_choice_single',
'2 Co 1:3 goi Chua la gi?',
'["Cha hay thuong xot va Chua cua moi su an uy", "Quan an", "Chien binh", "Vua"]',
'[0]', 'Chua an uy chung ta de chung ta co the an uy nguoi khac bang su an uy da nhan.', '["Tan Uoc","An uy","Thuong xot"]', '2 Corinthians 1:3-4', 'vi', true, NOW(), NOW()),
('q-2co-004', '2 Corinthians', 3, 17, 17, 'easy', 'multiple_choice_single',
'2 Co 3:17: "Chua la Than; Than cua Chua o dau thi o do co su ___"',
'["Tu do", "Binh an", "Vui mung", "Quyen nang"]',
'[0]', 'Su tu do that den tu Duc Thanh Linh, khong phai tu hoan canh.', '["Tan Uoc","Thanh Linh","Tu do"]', '2 Corinthians 3:17', 'vi', true, NOW(), NOW()),
('q-2co-005', '2 Corinthians', 4, 7, 7, 'medium', 'multiple_choice_single',
'2 Co 4:7: Chung ta co cua quy nay (Phuc Am) trong gi?',
'["Binh dat (chua yeu duoi)", "Binh vang", "Hom sat", "Tui da"]',
'[0]', 'De quyen nang toi cao thuoc ve Chua, khong phai chung ta. Su yeu duoi ton vinh Chua.', '["Tan Uoc","Yeu duoi","Quyen nang"]', '2 Corinthians 4:7', 'vi', true, NOW(), NOW()),
('q-2co-006', '2 Corinthians', 4, 17, 18, 'easy', 'multiple_choice_single',
'2 Co 4:17: Hoan nan nhe va tam thoi se dem lai gi?',
'["Su vinh hien doi doi vuot qua moi so sanh", "Su thoai mai", "Su giau co", "Danh tieng"]',
'[0]', 'Nhung kho nan hien tai khong dang so voi vinh quang mai sau.', '["Tan Uoc","Kho nan","Vinh hien"]', '2 Corinthians 4:17-18', 'vi', true, NOW(), NOW()),
('q-2co-007', '2 Corinthians', 5, 7, 7, 'easy', 'fill_in_blank',
'Vi chung ta buoc di boi ___ chot chang phai boi mat thay (2 Co 5:7)',
'[]', '[]', 'Doi song tin do dua tren duc tin, khong phai bang chung mat thay.', '["Tan Uoc","Duc tin","Buoc di"]', '2 Corinthians 5:7', 'vi', true, NOW(), NOW()),
('q-2co-008', '2 Corinthians', 5, 20, 20, 'easy', 'multiple_choice_single',
'Phao-lo noi chung ta la gi cho Chua?',
'["Su gia (dai su) thay mat Chua", "Day to", "Linh", "Hoc tro"]',
'[0]', 'Chung ta la dai su cua Chua tren dat, dai dien Ngai keu goi nguoi khac hoa thuan voi Chua.', '["Tan Uoc","Lam chung","Dai su"]', '2 Corinthians 5:20', 'vi', true, NOW(), NOW()),
('q-2co-009', '2 Corinthians', 8, 9, 9, 'medium', 'multiple_choice_single',
'2 Co 8:9: Chua Gie-su von giau nhung da tro nen ___ vi chung ta',
'["Ngheo", "Yeu", "Nho", "Thuong"]',
'[0]', 'Chua tu bo su giau co thien thuong de chung ta duoc giau co thuoc linh.', '["Tan Uoc","An dien","Hy sinh"]', '2 Corinthians 8:9', 'vi', true, NOW(), NOW()),
('q-2co-010', '2 Corinthians', 9, 7, 7, 'easy', 'multiple_choice_single',
'2 Co 9:7: Chua yeu nguoi cho di nhu the nao?',
'["Cach vui long", "Nhieu nhat", "Cong khai", "Bat buoc"]',
'[0]', 'Khong cho vi bat buoc hay tiec nuoi. Chua yeu nguoi cho voi tam long vui ve.', '["Tan Uoc","Dang hien","Vui long"]', '2 Corinthians 9:7', 'vi', true, NOW(), NOW()),
('q-2co-011', '2 Corinthians', 10, 4, 5, 'medium', 'fill_in_blank',
'Vu khi chung ta khong phai thuoc xac thit nhung co quyen nang cua Duc Chua Troi de pha do cac ___ (2 Co 10:4)',
'[]', '[]', 'Chien tran thuoc linh dung vu khi thuoc linh de pha do thanh tri suy nghi sai.', '["Tan Uoc","Chien tran","Vu khi"]', '2 Corinthians 10:4-5', 'vi', true, NOW(), NOW()),
('q-2co-012', '2 Corinthians', 13, 14, 14, 'easy', 'multiple_choice_single',
'2 Co 13:14 la loi chuc phuc Ba Ngoi noi tieng. Ba dieu la gi?',
'["An dien Chua Gie-su, tinh yeu Duc Chua Troi, su thong cong Duc Thanh Linh", "Duc tin, hy vong, yeu thuong", "Phuc lanh, binh an, vui mung", "Suc manh, khon ngoan, vinh hien"]',
'[0]', 'Loi chuc phuc Ba Ngoi duoc dung rong rai trong le bai.', '["Tan Uoc","Ba Ngoi","Chuc phuc"]', '2 Corinthians 13:14', 'vi', true, NOW(), NOW()),
('q-2co-013', '2 Corinthians', 6, 14, 14, 'easy', 'multiple_choice_single',
'2 Co 6:14: "Cho mang ___ khong can xung voi ke chua tin"',
'["Ach", "Ao", "Giay", "Non"]',
'[0]', 'Khong ket hop mat thiet voi nguoi khong cung duc tin vi anh sang va bong toi khong tuong hop.', '["Tan Uoc","Biet rieng","Moi quan he"]', '2 Corinthians 6:14', 'vi', true, NOW(), NOW()),
('q-2co-014', '2 Corinthians', 12, 10, 10, 'medium', 'multiple_choice_single',
'Phao-lo noi: "Khi toi yeu duoi ay la khi toi ___"',
'["Manh me", "Buon", "Met", "So"]',
'[0]', 'Nghich ly Co Doc: yeu duoi la khi Chua manh me qua chung ta nhat.', '["Tan Uoc","Yeu duoi","Suc manh"]', '2 Corinthians 12:10', 'vi', true, NOW(), NOW()),
('q-2co-015', '2 Corinthians', 1, 20, 20, 'easy', 'fill_in_blank',
'Tat ca loi hua cua Chua deu la ___ trong Chua Gie-su (2 Co 1:20)',
'[]', '[]', 'Moi loi hua cua Chua duoc xac nhan (co/phai/vang) qua Chua Gie-su.', '["Tan Uoc","Loi hua","Xac nhan"]', '2 Corinthians 1:20', 'vi', true, NOW(), NOW()),

-- ==================== GALATIANS (need +13) ====================
('q-gal-003', 'Galatians', 3, 28, 28, 'easy', 'multiple_choice_single',
'Ga 3:28: Trong Chua Gie-su khong con phan biet gi?',
'["Do-thai hay Hy-lap, no le hay tu do, nam hay nu", "Giau hay ngheo", "Tre hay gia", "Hoc hay dot"]',
'[0]', 'Trong Chua, moi nguoi deu binh dang va la mot trong Chua Gie-su.', '["Tan Uoc","Binh dang","Hiep nhat"]', 'Galatians 3:28', 'vi', true, NOW(), NOW()),
('q-gal-004', 'Galatians', 5, 1, 1, 'easy', 'multiple_choice_single',
'Ga 5:1: Chua Gie-su giai phong chung ta de lam gi?',
'["Duoc tu do, dung chiu ach no le nua", "Lam viec nhieu hon", "Giu luat nhieu hon", "Duoc giau co"]',
'[0]', 'Tu do trong Chua khong phai de song bua bai ma de song cho Chua va yeu thuong.', '["Tan Uoc","Tu do","An dien"]', 'Galatians 5:1', 'vi', true, NOW(), NOW()),
('q-gal-005', 'Galatians', 5, 16, 17, 'medium', 'multiple_choice_single',
'Ga 5:16-17 noi ve su xung dot giua dieu gi?',
'["Xac thit va Thanh Linh", "Tot va xau", "Cu va moi", "Ly tri va cam xuc"]',
'[0]', 'Xac thit va Thanh Linh chong nhau. Hay buoc di theo Thanh Linh de khong lam theo xac thit.', '["Tan Uoc","Xac thit","Thanh Linh"]', 'Galatians 5:16-17', 'vi', true, NOW(), NOW()),
('q-gal-006', 'Galatians', 6, 2, 2, 'easy', 'fill_in_blank',
'Hay mang ___ cho nhau nhu vay la lam tron luat phap cua Chua Gie-su (Ga 6:2)',
'[]', '[]', 'Luat cua Chua Gie-su = yeu thuong, the hien qua viec giup do nhau.', '["Tan Uoc","Yeu thuong","Giup do"]', 'Galatians 6:2', 'vi', true, NOW(), NOW()),
('q-gal-007', 'Galatians', 6, 7, 7, 'easy', 'multiple_choice_single',
'Ga 6:7: "Chua khong chiu nhao bao dau; vi ai gieo gi thi se ___"',
'["Gat nay", "Duoc nay", "That nay", "Mat nay"]',
'[0]', 'Luat gieo gat: hanh dong co hau qua. Gieo theo xac thit gat hu nat, gieo theo Thanh Linh gat su song.', '["Tan Uoc","Gieo gat","Hau qua"]', 'Galatians 6:7', 'vi', true, NOW(), NOW()),
('q-gal-008', 'Galatians', 6, 9, 9, 'easy', 'multiple_choice_single',
'Ga 6:9: "Chung ta dung ___ lam lanh vi se gat neu khong ngan long"',
'["Met nhoc (ngan)", "Vui ve", "Nhanh", "Cham"]',
'[0]', 'Lam lanh can kien nhan. Mua gat se den vao dung thoi diem.', '["Tan Uoc","Kien nhan","Lam lanh"]', 'Galatians 6:9', 'vi', true, NOW(), NOW()),
('q-gal-009', 'Galatians', 3, 13, 13, 'hard', 'multiple_choice_single',
'Ga 3:13: Chua Gie-su chuoc chung ta khoi su rua sap cua luat phap bang cach nao?',
'["Tro nen su rua sap vi chung ta (bi treo tren cay)", "Huy bo luat", "Doi luat", "Giu luat thay"]',
'[0]', 'Chua Gie-su ganh chiu hinh phat cua luat phap thay cho chung ta.', '["Tan Uoc","Cuu chuoc","Luat phap"]', 'Galatians 3:13', 'vi', true, NOW(), NOW()),
('q-gal-010', 'Galatians', 4, 4, 5, 'medium', 'multiple_choice_single',
'Ga 4:4: Khi ky han da duoc tron, Chua sai Con Ngai den the gian de lam gi?',
'["Chuoc nhung ke duoi quyen luat phap de chung ta duoc lam con nuoi", "Lam vua", "Phan xet", "Day do"]',
'[0]', 'Chua Gie-su den dung thoi diem de chuoc toi va ban cho chung ta dia vi con cai Chua.', '["Tan Uoc","Nhap the","Con nuoi"]', 'Galatians 4:4-5', 'vi', true, NOW(), NOW()),
('q-gal-011', 'Galatians', 5, 13, 13, 'easy', 'fill_in_blank',
'Anh em duoc goi den su tu do; nhung dung lay su tu do lam co cho xac thit; hay lay tinh yeu ma ___ nhau (Ga 5:13)',
'[]', '[]', 'Tu do that la tu do de phuc vu va yeu thuong, khong phai de song ich ky.', '["Tan Uoc","Tu do","Phuc vu"]', 'Galatians 5:13', 'vi', true, NOW(), NOW()),
('q-gal-012', 'Galatians', 5, 24, 24, 'medium', 'multiple_choice_single',
'Ga 5:24: Nhung ke thuoc ve Chua Gie-su da lam gi voi xac thit?',
'["Da dong dinh xac thit voi duc dam va me tham tren thap tu gia", "Bo qua", "An giau", "Tu choi"]',
'[0]', 'Dong dinh xac thit = quyet dinh dut khoat tu bo doi song theo xac thit.', '["Tan Uoc","Xac thit","Thanh khiet"]', 'Galatians 5:24', 'vi', true, NOW(), NOW()),
('q-gal-013', 'Galatians', 1, 6, 7, 'easy', 'multiple_choice_single',
'Phao-lo kinh ngac vi Hoi thanh Ga-la-ti lam gi?',
'["Nhanh chong bo Phuc Am that de theo phuc am khac", "Pham toi", "Bo nha tho", "Khong cau nguyen"]',
'[0]', 'Chi co mot Phuc Am that. Bat cu su thay doi nao deu la di lac.', '["Tan Uoc","Phuc Am","Canh bao"]', 'Galatians 1:6-7', 'vi', true, NOW(), NOW()),
('q-gal-014', 'Galatians', 3, 11, 11, 'easy', 'multiple_choice_single',
'Ga 3:11: "Khong ai duoc xung cong binh truoc Chua boi ___ ay la dieu hien nhien"',
'["Luat phap", "Viec lam", "Tri thuc", "Ton giao"]',
'[0]', 'Su cong binh den boi duc tin, khong phai boi giu luat phap.', '["Tan Uoc","Cong binh","Duc tin"]', 'Galatians 3:11', 'vi', true, NOW(), NOW()),
('q-gal-015', 'Galatians', 4, 6, 7, 'easy', 'fill_in_blank',
'Vi anh em la con cai Chua nen Chua sai Than cua Con Ngai vao long anh em keu len "Ap-ba, ___!" (Ga 4:6)',
'[]', '[]', 'Ap-ba = Cha oi (tieng A-ram than mat). Chung ta co quyen goi Chua la Cha nho Chua Gie-su.', '["Tan Uoc","Con cai","Than mat"]', 'Galatians 4:6-7', 'vi', true, NOW(), NOW()),

-- ==================== EPHESIANS (need +13) ====================
('q-eph-003', 'Ephesians', 1, 3, 3, 'easy', 'multiple_choice_single',
'Eph 1:3: Chua da ban cho chung ta moi phuc lanh gi?',
'["Moi phuc lanh thuoc linh o cac noi tren troi", "Phuc lanh vat chat", "Phuc lanh suc khoe", "Phuc lanh tai chinh"]',
'[0]', 'Phuc lanh Chua ban la thuoc linh va doi doi, khong chi vat chat.', '["Tan Uoc","Phuc lanh","Thuoc linh"]', 'Ephesians 1:3', 'vi', true, NOW(), NOW()),
('q-eph-004', 'Ephesians', 2, 10, 10, 'easy', 'multiple_choice_single',
'Eph 2:10: Chung ta la tac pham cua Chua, duoc tao dung trong Chua Gie-su de lam gi?',
'["Viec lanh ma Chua da chuan bi truoc", "Giu luat phap", "Duoc cuu", "Duoc nghi ngoi"]',
'[0]', 'Duoc cuu khong boi viec lam nhung DUOC CUU DE lam viec lanh.', '["Tan Uoc","Muc dich","Viec lanh"]', 'Ephesians 2:10', 'vi', true, NOW(), NOW()),
('q-eph-005', 'Ephesians', 3, 20, 20, 'easy', 'fill_in_blank',
'Chua co the lam tren ca moi dieu chung ta cau xin hay ___ (Eph 3:20)',
'[]', '[]', 'Quyen nang Chua vuot qua ca nhung gi chung ta co the tuong tuong hay cau xin.', '["Tan Uoc","Quyen nang","Cau nguyen"]', 'Ephesians 3:20', 'vi', true, NOW(), NOW()),
('q-eph-006', 'Ephesians', 4, 2, 3, 'easy', 'multiple_choice_single',
'Eph 4:2-3 khuyen song voi nhau the nao?',
'["Khiem nhuong, mem mai, nhin nhuc, lay tinh yeu nhuong nhin nhau", "Canh tranh", "Doc lap", "Ly tri"]',
'[0]', 'Giu gin su hiep nhat cua Thanh Linh bang moi lien ket binh an.', '["Tan Uoc","Hiep nhat","Khiem nhuong"]', 'Ephesians 4:2-3', 'vi', true, NOW(), NOW()),
('q-eph-007', 'Ephesians', 4, 26, 26, 'easy', 'multiple_choice_single',
'Eph 4:26: "Neu gian thi chot ___, dung de mat troi lan khi con dang gian"',
'["Pham toi", "Noi", "Lam", "Nghi"]',
'[0]', 'Co the gian nhung dung de con gian dan den toi loi. Giai quyet truoc khi het ngay.', '["Tan Uoc","Con gian","Doi song"]', 'Ephesians 4:26', 'vi', true, NOW(), NOW()),
('q-eph-008', 'Ephesians', 4, 32, 32, 'easy', 'multiple_choice_single',
'Eph 4:32: Hay o voi nhau nhu the nao?',
'["Nhan tu, danh du thuong xot, tha thu nhu Chua da tha thu anh em", "Cong binh", "Nghiem khac", "Lanh dam"]',
'[0]', 'Tha thu cho nguoi khac vi Chua da tha thu cho chung ta. Tha thu la ban sao cua an dien.', '["Tan Uoc","Tha thu","Nhan tu"]', 'Ephesians 4:32', 'vi', true, NOW(), NOW()),
('q-eph-009', 'Ephesians', 5, 25, 25, 'medium', 'multiple_choice_single',
'Eph 5:25: Nguoi chong phai yeu vo nhu ai?',
'["Nhu Chua Gie-su yeu Hoi thanh va phoi minh vi Hoi thanh", "Nhu yeu ban than", "Nhu yeu cha me", "Nhu yeu con cai"]',
'[0]', 'Tinh yeu hon nhan theo khuon mau Chua hy sinh vi Hoi thanh. Yeu la cho di khong phai nhan.', '["Tan Uoc","Hon nhan","Hy sinh"]', 'Ephesians 5:25', 'vi', true, NOW(), NOW()),
('q-eph-010', 'Ephesians', 6, 1, 3, 'easy', 'fill_in_blank',
'Hoi ke lam con cai, hay ___ cha me minh trong Chua vi dieu nay la phai le (Eph 6:1)',
'[]', '[]', 'Vang loi cha me trong Chua la dieu ran co loi hua: de nguoi song lau tren dat.', '["Tan Uoc","Gia dinh","Vang loi"]', 'Ephesians 6:1-3', 'vi', true, NOW(), NOW()),
('q-eph-011', 'Ephesians', 6, 12, 12, 'medium', 'multiple_choice_single',
'Eph 6:12: Chung ta chien dau khong phai voi thit va huyet nhung voi ai?',
'["Cac the luc, cac quyen binh, cac chua te bong toi", "Con nguoi", "Chinh phu", "Ban be"]',
'[0]', 'Chien tran that su la thuoc linh, chong lai the luc toi tam, khong phai con nguoi.', '["Tan Uoc","Chien tran","The luc toi"]', 'Ephesians 6:12', 'vi', true, NOW(), NOW()),
('q-eph-012', 'Ephesians', 6, 14, 17, 'easy', 'multiple_choice_single',
'Khi gioi toan than cua Chua gom nhung gi?',
'["Dai lung le that, ao giap cong binh, giay Phuc Am, khien duc tin, mu cuu roi, guom Thanh Linh", "Chi co guom", "Chi co khien", "Chi co mu"]',
'[0]', '6 mon khi gioi thuoc linh bao ve va tan cong. Loi Chua la vu khi tan cong duy nhat.', '["Tan Uoc","Khi gioi","Chien tran"]', 'Ephesians 6:14-17', 'vi', true, NOW(), NOW()),
('q-eph-013', 'Ephesians', 6, 18, 18, 'easy', 'multiple_choice_single',
'Eph 6:18 khuyen cau nguyen nhu the nao?',
'["Moi luc voi moi thu cau nguyen va nai xin boi Duc Thanh Linh", "Chi buoi sang", "Chi khi gap kho", "Chi o nha tho"]',
'[0]', 'Cau nguyen la vu khi thuoc linh can su dung lien tuc, khong chi luc gap nan.', '["Tan Uoc","Cau nguyen","Thanh Linh"]', 'Ephesians 6:18', 'vi', true, NOW(), NOW()),
('q-eph-014', 'Ephesians', 5, 15, 16, 'easy', 'fill_in_blank',
'Hay khen net o doi cho khon ngoan, hay tan dung ___ vi nhung ngay la xau (Eph 5:16)',
'[]', '[]', 'Thoi gian la quy gia. Hay song khon ngoan va su dung thoi gian cho dieu co gia tri doi doi.', '["Tan Uoc","Khon ngoan","Thoi gian"]', 'Ephesians 5:15-16', 'vi', true, NOW(), NOW()),
('q-eph-015', 'Ephesians', 5, 18, 19, 'easy', 'multiple_choice_single',
'Eph 5:18: Dung say ruou nhung hay day dau dieu gi?',
'["Duc Thanh Linh", "Tri thuc", "Vui ve", "Loi Chua"]',
'[0]', 'Day dau Thanh Linh thay vi say ruou. Thanh Linh mang lai su vui mung, hat xung va ta on.', '["Tan Uoc","Thanh Linh","Day dau"]', 'Ephesians 5:18-19', 'vi', true, NOW(), NOW()),

-- ==================== PHILIPPIANS (need +13) ====================
('q-phi-003', 'Philippians', 1, 6, 6, 'easy', 'multiple_choice_single',
'Phi 1:6: Dang nao da khoi lam viec lanh trong anh em se lam cho tron?',
'["Chinh Duc Chua Troi", "Chinh ban than", "Muc su", "Hoi thanh"]',
'[0]', 'Chua bat dau va se hoan tat. Su cuu roi la viec cua Chua tu dau den cuoi.', '["Tan Uoc","An ninh","Thanh tin"]', 'Philippians 1:6', 'vi', true, NOW(), NOW()),
('q-phi-004', 'Philippians', 1, 21, 21, 'medium', 'multiple_choice_single',
'Phao-lo noi: "Doi voi toi, song la ___ va chet la loi"',
'["Chua Gie-su", "Phuc vu", "Chien dau", "Hoc hoi"]',
'[0]', 'Song = Chua Gie-su (muc dich); chet = loi (ve voi Chua). Ca hai deu tot!', '["Tan Uoc","Phao-lo","Muc dich"]', 'Philippians 1:21', 'vi', true, NOW(), NOW()),
('q-phi-005', 'Philippians', 2, 3, 4, 'easy', 'multiple_choice_single',
'Phi 2:3: Hay coi nguoi khac nhu the nao?',
'["Tot hon minh", "Bang minh", "Kem hon minh", "Khong quan tam"]',
'[0]', 'Khiem nhuong: coi nguoi khac hon minh, khong chi lo cho rieng minh.', '["Tan Uoc","Khiem nhuong","Moi quan he"]', 'Philippians 2:3-4', 'vi', true, NOW(), NOW()),
('q-phi-006', 'Philippians', 2, 5, 8, 'hard', 'multiple_choice_single',
'Phi 2:5-8 mo ta Chua Gie-su lam gi du von co hinh Duc Chua Troi?',
'["Tu bo minh, lay hinh toi to, chiu chet tren thap tu", "Lam vua", "Phan xet", "Chien thang"]',
'[0]', 'Kenosis (tu bo minh): Chua Gie-su tu bo dia vi de phuc vu va hy sinh. Khuon mau khiem nhuong.', '["Tan Uoc","Nhap the","Khiem nhuong"]', 'Philippians 2:5-8', 'vi', true, NOW(), NOW()),
('q-phi-007', 'Philippians', 2, 9, 11, 'easy', 'multiple_choice_single',
'Vi su khiem nhuong, Chua nang Chua Gie-su len va ban danh tren moi danh. Moi dau goi se ___',
'["Quy xuong va moi luoi tuyen xung Gie-su la Chua", "Dung day", "Im lang", "So hai"]',
'[0]', 'Moi sinh vat se nhan biet Chua Gie-su la Chua vi vinh hien Duc Chua Cha.', '["Tan Uoc","Gie-su","Ton cao"]', 'Philippians 2:9-11', 'vi', true, NOW(), NOW()),
('q-phi-008', 'Philippians', 2, 14, 15, 'easy', 'fill_in_blank',
'Hay lam moi viec khong cam ran khong cai va de tro nen con cai Chua khong ti vet giua doi nay nhu ___',
'[]', '[]', 'Phi 2:15 - Nhu nhung vi sao sang trong the gian toi tam.', '["Tan Uoc","Lam chung","Doi song"]', 'Philippians 2:14-15', 'vi', true, NOW(), NOW()),
('q-phi-009', 'Philippians', 3, 8, 8, 'medium', 'multiple_choice_single',
'Phao-lo coi moi thu nhu gi so voi su nhan biet Chua Gie-su?',
'["Nhu rac ruoi (su lo)", "Nhu vang", "Nhu quy", "Nhu thuong"]',
'[0]', 'Phi 3:8 - Moi thu tren doi khong gi sanh duoc voi su nhan biet Chua Gie-su.', '["Tan Uoc","Phao-lo","Gia tri"]', 'Philippians 3:8', 'vi', true, NOW(), NOW()),
('q-phi-010', 'Philippians', 3, 13, 14, 'easy', 'multiple_choice_single',
'Phao-lo noi ong lam mot dieu: quen su o dang sau va vuon toi su o dang truoc de duoc gi?',
'["Giai thuong cua su keu goi tren troi", "Vinh quang tren dat", "Su khen ngoi", "Chuc vu lon hon"]',
'[0]', 'Dung mac ket o qua khu, hay tien ve phia truoc huong ve giai thuong.', '["Tan Uoc","Tien toi","Muc tieu"]', 'Philippians 3:13-14', 'vi', true, NOW(), NOW()),
('q-phi-011', 'Philippians', 4, 4, 4, 'easy', 'fill_in_blank',
'Hay ___ trong Chua luon luon. Toi lai noi nua: hay vui len! (Phi 4:4)',
'[]', '[]', 'Vui mung la menh lenh, khong phu thuoc hoan canh ma dua tren Chua.', '["Tan Uoc","Vui mung","Doi song"]', 'Philippians 4:4', 'vi', true, NOW(), NOW()),
('q-phi-012', 'Philippians', 4, 7, 7, 'easy', 'multiple_choice_single',
'Phi 4:7: Su binh an cua Chua vuot qua moi dieu gi?',
'["Moi su hieu biet (tri khon)", "Moi van de", "Moi cam xuc", "Moi kho khan"]',
'[0]', 'Su binh an cua Chua khong the giai thich bang ly tri, no giu gin long va tri chung ta.', '["Tan Uoc","Binh an","Cau nguyen"]', 'Philippians 4:7', 'vi', true, NOW(), NOW()),
('q-phi-013', 'Philippians', 4, 8, 8, 'easy', 'multiple_choice_single',
'Phi 4:8 khuyen suy nghi ve nhung dieu nao?',
'["That, ton trong, cong binh, tinh sach, dang yeu, co tieng tot", "Bat cu dieu gi", "Chi dieu vui", "Chi dieu lon"]',
'[0]', 'Kiem soat suy nghi bang cach tap trung vao nhung dieu tot dep cua Chua.', '["Tan Uoc","Suy nghi","Doi song"]', 'Philippians 4:8', 'vi', true, NOW(), NOW()),
('q-phi-014', 'Philippians', 4, 11, 12, 'medium', 'multiple_choice_single',
'Phao-lo noi ong da hoc duoc dieu gi?',
'["Thoa long trong moi hoan canh, du du dat hay thieu thon", "Cach lam giau", "Cach thoat kho", "Cach lanh dao"]',
'[0]', 'Su thoa long (contentment) khong phu thuoc hoan canh ma phu thuoc Chua.', '["Tan Uoc","Thoa long","Phao-lo"]', 'Philippians 4:11-12', 'vi', true, NOW(), NOW()),
('q-phi-015', 'Philippians', 4, 19, 19, 'easy', 'fill_in_blank',
'Duc Chua Troi toi se lam cho day du moi su can dung cua anh em y theo su ___ Ngai trong Chua Gie-su (Phi 4:19)',
'[]', '[]', 'Chua cung ung theo su giau co Ngai (vo han), khong phai theo su ngheo nan chung ta.', '["Tan Uoc","Cung ung","Loi hua"]', 'Philippians 4:19', 'vi', true, NOW(), NOW()),

-- ==================== HEBREWS (need +12), JAMES (+13), 1 PETER (+14), 1 JOHN (+13), REVELATION (+12) — abbreviated ====================

-- HEBREWS
('q-heb-004', 'Hebrews', 4, 12, 12, 'easy', 'multiple_choice_single',
'He 4:12 mo ta Loi Chua nhu gi?',
'["Song va linh nghiem, sac hon guom hai luoi", "Cuon sach", "Luat phap", "Truyen thong"]',
'[0]', 'Loi Chua song dong, xuyen thau tam long, phan biet tu tuong va y dinh.', '["Tan Uoc","Loi Chua","Quyen nang"]', 'Hebrews 4:12', 'vi', true, NOW(), NOW()),
('q-heb-005', 'Hebrews', 4, 15, 16, 'medium', 'multiple_choice_single',
'He 4:15: Chua Gie-su la Thay Te Le Thuong Pham nhu the nao?',
'["Bi cam do moi mat nhu chung ta nhung khong pham toi", "Khong bao gio bi cam do", "Khong hieu noi dau", "Chi la Chua"]',
'[0]', 'Chua Gie-su hieu su yeu duoi cua chung ta vi da trai qua moi thu. Nen hay manh dan den ngai an dien.', '["Tan Uoc","Te Le","Cam thong"]', 'Hebrews 4:15-16', 'vi', true, NOW(), NOW()),
('q-heb-006', 'Hebrews', 10, 25, 25, 'easy', 'fill_in_blank',
'Chung ta dung bo su ___ nhu mot vai nguoi quen lam (He 10:25)',
'[]', '[]', 'He 10:25 - Nhom hop voi nhau la quan trong, dac biet khi ngay Chua den gan.', '["Tan Uoc","Hoi thanh","Nhom hop"]', 'Hebrews 10:25', 'vi', true, NOW(), NOW()),
('q-heb-007', 'Hebrews', 11, 8, 10, 'easy', 'multiple_choice_single',
'He 11:8: Ap-ra-ham boi duc tin lam gi khi duoc goi?',
'["Vang loi di ma khong biet minh di dau", "Tu choi", "Hoi tai sao", "Chuan bi ky"]',
'[0]', 'Duc tin la vang loi du khong thay dich den. Ap-ra-ham la guong mau duc tin.', '["Tan Uoc","Duc tin","Vang loi"]', 'Hebrews 11:8-10', 'vi', true, NOW(), NOW()),
('q-heb-008', 'Hebrews', 12, 6, 6, 'easy', 'multiple_choice_single',
'He 12:6: Chua sua phat ai?',
'["Con cai ma Ngai yeu thuong", "Ke thu", "Ke ac", "Nguoi la"]',
'[0]', 'Su sua phat la dau hieu tinh yeu cua Cha, khong phai su bo roi.', '["Tan Uoc","Sua phat","Tinh yeu"]', 'Hebrews 12:6', 'vi', true, NOW(), NOW()),
('q-heb-009', 'Hebrews', 12, 11, 11, 'medium', 'fill_in_blank',
'Su sua phat luc dau khong vui nhung buon; nhung sau sinh trai ___ cho nguoi chiu luyen tap (He 12:11)',
'[]', '[]', 'Su ky luat sinh ra doi song cong binh va binh an. Kho nhung xung dang.', '["Tan Uoc","Sua phat","Cong binh"]', 'Hebrews 12:11', 'vi', true, NOW(), NOW()),
('q-heb-010', 'Hebrews', 13, 5, 5, 'easy', 'multiple_choice_single',
'He 13:5: Chua hua gi ve su hien dien cua Ngai?',
'["Ta se khong bo con, khong he lia con", "Ta se ban phuc", "Ta se tra thu", "Ta se doi"]',
'[0]', 'Chua luon o voi chung ta. Khong bao gio bo roi. Nen thoa long voi nhung gi co.', '["Tan Uoc","Su hien dien","An ninh"]', 'Hebrews 13:5', 'vi', true, NOW(), NOW()),
('q-heb-011', 'Hebrews', 13, 8, 8, 'easy', 'multiple_choice_single',
'He 13:8: Chua Gie-su Christ hom qua ngay nay va cho den doi doi deu nhu the nao?',
'["Khong thay doi", "Thay doi theo thoi dai", "Manh hon", "Khon ngoan hon"]',
'[0]', 'Chua Gie-su bat bien. Ngai giong hom qua, hom nay va mai mai.', '["Tan Uoc","Gie-su","Bat bien"]', 'Hebrews 13:8', 'vi', true, NOW(), NOW()),
('q-heb-012', 'Hebrews', 13, 15, 15, 'easy', 'fill_in_blank',
'Vay hay boi Ngai ma dang te le ngoi khen cho Chua khong that, tuc la ___ cua moi mieng tuyen xung danh Ngai (He 13:15)',
'[]', '[]', 'Te le ngoi khen = trai moi cua moi mieng. Ngoi khen Chua la cua le that.', '["Tan Uoc","Ngoi khen","Cua le"]', 'Hebrews 13:15', 'vi', true, NOW(), NOW()),
('q-heb-013', 'Hebrews', 9, 22, 22, 'hard', 'multiple_choice_single',
'He 9:22: Theo luat phap, khong co ___ thi khong co su tha toi',
'["Su do huyet (huyet)", "Cau nguyen", "Cua le", "An nan"]',
'[0]', 'Nguyen tac cot loi: tha toi can huyet. Huyet Chua Gie-su la cua le cuoi cung va tron ven nhat.', '["Tan Uoc","Cuu chuoc","Huyet"]', 'Hebrews 9:22', 'vi', true, NOW(), NOW()),
('q-heb-014', 'Hebrews', 11, 3, 3, 'medium', 'multiple_choice_single',
'He 11:3: Boi duc tin chung ta hieu rang the gioi duoc dung nen boi gi?',
'["Loi phan cua Duc Chua Troi", "Vu no lon", "Tu nhien", "Cac than"]',
'[0]', 'Duc tin chap nhan Chua sang tao vu tru bang Loi Ngai tu hu vo.', '["Tan Uoc","Duc tin","Sang tao"]', 'Hebrews 11:3', 'vi', true, NOW(), NOW()),
('q-heb-015', 'Hebrews', 10, 23, 23, 'easy', 'multiple_choice_single',
'He 10:23: Hay giu vung su tuyen xung ve su trong doi vi Dang da hua la gi?',
'["Thanh tin", "Manh me", "Khon ngoan", "Giau co"]',
'[0]', 'Chua thanh tin giu loi hua nen chung ta co the vung long tuyen xung duc tin.', '["Tan Uoc","Thanh tin","Trong doi"]', 'Hebrews 10:23', 'vi', true, NOW(), NOW()),

-- JAMES (+13)
('q-jam-003', 'James', 1, 5, 5, 'easy', 'multiple_choice_single',
'Gia-co 1:5: Neu ai thieu khon ngoan, hay lam gi?',
'["Cau xin Chua vi Ngai ban roi cho moi nguoi", "Hoc nhieu hon", "Hoi nguoi khac", "Doc sach"]',
'[0]', 'Chua ban khon ngoan roi rai va khong trach moc. Chi can xin!', '["Tan Uoc","Khon ngoan","Cau nguyen"]', 'James 1:5', 'vi', true, NOW(), NOW()),
('q-jam-004', 'James', 1, 12, 12, 'easy', 'fill_in_blank',
'Phuc cho nguoi chiu dung su thu thach vi se nhan duoc mao trieu cua su ___ (Gia-co 1:12)',
'[]', '[]', 'Mao trieu su song cho nguoi chiu dung va yeu men Chua.', '["Tan Uoc","Thu thach","Phuc"]', 'James 1:12', 'vi', true, NOW(), NOW()),
('q-jam-005', 'James', 1, 19, 20, 'easy', 'multiple_choice_single',
'Gia-co 1:19: Moi nguoi phai nhu the nao?',
'["Mau nghe, cham noi, cham gian", "Mau noi, cham nghe", "Noi nhieu", "Im lang"]',
'[0]', 'Lang nghe truoc khi noi va kiem che con gian. Khon ngoan thuc te.', '["Tan Uoc","Khon ngoan","Loi noi"]', 'James 1:19-20', 'vi', true, NOW(), NOW()),
('q-jam-006', 'James', 1, 22, 22, 'easy', 'multiple_choice_single',
'Gia-co 1:22: Hay lam gi voi Loi Chua?',
'["Lam theo, khong chi nghe suong", "Chi doc", "Chi nghe", "Chi hoc thuoc"]',
'[0]', 'Nghe Loi Chua ma khong lam la tu lua minh. Duc tin can hanh dong.', '["Tan Uoc","Loi Chua","Hanh dong"]', 'James 1:22', 'vi', true, NOW(), NOW()),
('q-jam-007', 'James', 3, 5, 6, 'easy', 'multiple_choice_single',
'Gia-co 3 so sanh cai luoi voi gi?',
'["Ngon lua nho dot chay rung lon", "Guom", "Chia khoa", "Con ran"]',
'[0]', 'Cai luoi nho nhung co the gay hai lon. Can kiem soat loi noi.', '["Tan Uoc","Loi noi","Luoi"]', 'James 3:5-6', 'vi', true, NOW(), NOW()),
('q-jam-008', 'James', 4, 7, 8, 'easy', 'multiple_choice_single',
'Gia-co 4:7: Hay chong tra ma quy thi no se ___',
'["Tron xa anh em", "Manh hon", "Quay lai", "An nau"]',
'[0]', 'Phai chong cu chu dung nhung buong. Va den gan Chua thi Ngai den gan anh em.', '["Tan Uoc","Chien tran","Chong tra"]', 'James 4:7-8', 'vi', true, NOW(), NOW()),
('q-jam-009', 'James', 4, 8, 8, 'easy', 'fill_in_blank',
'Hay den gan Duc Chua Troi thi Ngai se den ___ anh em (Gia-co 4:8)',
'[]', '[]', 'Moi quan he hai chieu: khi chung ta buoc den Chua, Ngai buoc den chung ta.', '["Tan Uoc","Gan gui","Moi quan he"]', 'James 4:8', 'vi', true, NOW(), NOW()),
('q-jam-010', 'James', 4, 10, 10, 'easy', 'multiple_choice_single',
'Gia-co 4:10: Hay tu ha minh truoc mat Chua thi Ngai se ___',
'["Nhac anh em len", "Tha thu", "Phat", "Doi"]',
'[0]', 'Khiem nhuong truoc Chua dan den su nang do tu Ngai.', '["Tan Uoc","Khiem nhuong","Cat nhac"]', 'James 4:10', 'vi', true, NOW(), NOW()),
('q-jam-011', 'James', 5, 13, 14, 'easy', 'multiple_choice_single',
'Gia-co 5:13: Khi gap kho, hay lam gi? Khi vui, hay lam gi?',
'["Kho: cau nguyen. Vui: hat ngoi khen", "Kho: im lang. Vui: an tiec", "Kho: khoc. Vui: cuoi", "Kho: ngu. Vui: chay"]',
'[0]', 'Moi cam xuc deu co the trinh len Chua: kho nan bang cau nguyen, vui mung bang ngoi khen.', '["Tan Uoc","Cau nguyen","Cam xuc"]', 'James 5:13-14', 'vi', true, NOW(), NOW()),
('q-jam-012', 'James', 5, 16, 16, 'easy', 'multiple_choice_single',
'Gia-co 5:16: "Loi cau nguyen cua nguoi ___ co quen nang lon"',
'["Cong binh", "Giau co", "Hoc thuc", "Co chuc vu"]',
'[0]', 'Quyen nang cau nguyen khong dua tren chuc vu ma dua tren doi song cong binh.', '["Tan Uoc","Cau nguyen","Cong binh"]', 'James 5:16', 'vi', true, NOW(), NOW()),
('q-jam-013', 'James', 2, 26, 26, 'easy', 'fill_in_blank',
'Nhu than the khong co linh hon la chet, duc tin khong co ___ cung chet (Gia-co 2:26)',
'[]', '[]', 'Duc tin song dong se bieu hien qua hanh dong cu the.', '["Tan Uoc","Duc tin","Viec lam"]', 'James 2:26', 'vi', true, NOW(), NOW()),
('q-jam-014', 'James', 3, 17, 17, 'medium', 'multiple_choice_single',
'Su khon ngoan tu tren co dac diem gi?',
'["Thanh sach, hoa thuan, mem mai, du tinh thuong xot", "Ly tri", "Sac ben", "Cung ran"]',
'[0]', 'Gia-co 3:17 - Khon ngoan tu Chua khac voi khon ngoan the gian. Dac diem la hoa binh va nhan tu.', '["Tan Uoc","Khon ngoan","Hoa thuan"]', 'James 3:17', 'vi', true, NOW(), NOW()),
('q-jam-015', 'James', 4, 14, 14, 'easy', 'multiple_choice_single',
'Gia-co 4:14 so sanh cuoc doi nhu gi?',
'["Hoi nuoc hien ra roi bien mat", "Dong song", "Ngon nui", "Cay lon"]',
'[0]', 'Cuoc doi ngan ngui nhu hoi nuoc. Hay song co y nghia va theo y Chua.', '["Tan Uoc","Cuoc doi","Ngan ngui"]', 'James 4:14', 'vi', true, NOW(), NOW()),

-- 1 PETER (+14)
('q-1pe-002', '1 Peter', 1, 3, 4, 'easy', 'multiple_choice_single',
'1 Phi 1:3-4: Su trai sinh ban cho chung ta san nghiep gi?',
'["San nghiep khong hu nat, khong o ue, khong suy tan, giu o tren troi", "Dat dai", "Vang bac", "Quyen luc"]',
'[0]', 'San nghiep doi doi duoc giu tren troi, khong bi mat hay hu hong.', '["Tan Uoc","Hy vong","San nghiep"]', '1 Peter 1:3-4', 'vi', true, NOW(), NOW()),
('q-1pe-003', '1 Peter', 1, 6, 7, 'medium', 'multiple_choice_single',
'1 Phi 1:7: Thu thach duc tin duoc so sanh voi gi?',
'["Vang duoc thu lua (lam tinh sach)", "Kim cuong", "Sat thep", "Da quy"]',
'[0]', 'Nhu vang duoc luyen trong lua, duc tin duoc lam tinh sach qua thu thach.', '["Tan Uoc","Thu thach","Duc tin"]', '1 Peter 1:6-7', 'vi', true, NOW(), NOW()),
('q-1pe-004', '1 Peter', 2, 9, 9, 'easy', 'multiple_choice_single',
'1 Phi 2:9: Tin do duoc goi la gi?',
'["Dong giong duoc chon, chuc te le nha vua, dan thanh, dan thuoc rieng", "Dan thuong", "Toi to", "Khach la"]',
'[0]', 'Moi tin do co dia vi cao quy trong Chua: vua va thay te le.', '["Tan Uoc","Dia vi","Dan Chua"]', '1 Peter 2:9', 'vi', true, NOW(), NOW()),
('q-1pe-005', '1 Peter', 2, 24, 24, 'easy', 'fill_in_blank',
'Ngai ganh toi loi chung ta trong than the Ngai tren ___ go de chung ta chet ve toi loi va song cho su cong binh (1 Phi 2:24)',
'[]', '[]', 'Thap tu la noi Chua ganh toi va ban su chua lanh cho chung ta.', '["Tan Uoc","Thap tu","Cuu chuoc"]', '1 Peter 2:24', 'vi', true, NOW(), NOW()),
('q-1pe-006', '1 Peter', 3, 15, 15, 'easy', 'multiple_choice_single',
'1 Phi 3:15: Hay luon san sang lam gi?',
'["Tra loi cho moi nguoi hoi ve su trong doi cua anh em", "Chien dau", "Bao thu", "Tron chay"]',
'[0]', 'San sang giai thich duc tin cach hien lanh va ton kinh.', '["Tan Uoc","Lam chung","San sang"]', '1 Peter 3:15', 'vi', true, NOW(), NOW()),
('q-1pe-007', '1 Peter', 4, 8, 8, 'easy', 'multiple_choice_single',
'1 Phi 4:8: "Truoc het hay co long ___ song dong vi tinh yeu phu lap nhieu toi"',
'["Yeu thuong nhau", "Vang loi", "Cau nguyen", "Kieng an"]',
'[0]', 'Tinh yeu thuong la dieu uu tien hang dau trong moi quan he.', '["Tan Uoc","Yeu thuong","Uu tien"]', '1 Peter 4:8', 'vi', true, NOW(), NOW()),
('q-1pe-008', '1 Peter', 4, 12, 13, 'medium', 'multiple_choice_single',
'1 Phi 4:12: Khi gap hoan nan vi Chua, hay lam gi?',
'["Hay vui mung vi duoc du phan dau kho cua Chua", "Buon rau", "Bo cuoc", "Gian du"]',
'[0]', 'Chiu kho vi Chua la dac an, khong phai bat hanh. Khi Ngai hien ra se duoc vui mung.', '["Tan Uoc","Hoan nan","Vui mung"]', '1 Peter 4:12-13', 'vi', true, NOW(), NOW()),
('q-1pe-009', '1 Peter', 5, 5, 5, 'easy', 'fill_in_blank',
'Duc Chua Troi chong cu ke kieu ngao ban on cho ke ___ (1 Phi 5:5)',
'[]', '[]', 'Khiem nhuong la dieu kien nhan an dien. Kieu ngao bi Chua chong cu.', '["Tan Uoc","Khiem nhuong","An dien"]', '1 Peter 5:5', 'vi', true, NOW(), NOW()),
('q-1pe-010', '1 Peter', 5, 8, 8, 'easy', 'multiple_choice_single',
'1 Phi 5:8 mo ta ma quy nhu gi?',
'["Su tu ruong, tim tham nuot nguoi", "Con ran", "Bong toi", "Gio bao"]',
'[0]', 'Hay tinh giac va canh giac vi ke thu dang tim cach pha huy.', '["Tan Uoc","Ma quy","Canh giac"]', '1 Peter 5:8', 'vi', true, NOW(), NOW()),
('q-1pe-011', '1 Peter', 2, 2, 2, 'easy', 'multiple_choice_single',
'1 Phi 2:2: Nhu tre so sinh, hay them ___ thuoc linh de lon len',
'["Sua tinh (Loi Chua)", "Banh", "Nuoc", "Thit"]',
'[0]', 'Loi Chua la thuc an thiet yeu de lon len thuoc linh, nhu sua cho tre so sinh.', '["Tan Uoc","Loi Chua","Truong thanh"]', '1 Peter 2:2', 'vi', true, NOW(), NOW()),
('q-1pe-012', '1 Peter', 1, 15, 16, 'easy', 'fill_in_blank',
'Hay nen ___ trong moi cach an o nhu Dang da goi anh em la thanh (1 Phi 1:15)',
'[]', '[]', 'Thanh khiet trong moi mat: suy nghi, loi noi, hanh dong, moi quan he.', '["Tan Uoc","Thanh khiet","Doi song"]', '1 Peter 1:15-16', 'vi', true, NOW(), NOW()),
('q-1pe-013', '1 Peter', 3, 3, 4, 'easy', 'multiple_choice_single',
'1 Phi 3:3-4: Ve dep that cua phu nu nam o dau?',
'["Nguoi be trong cua long: tam linh diu dang va yen lang", "Trang suc", "Y phuc", "Toc"]',
'[0]', 'Ve dep ben trong (tam linh) quy gia truoc mat Chua hon ve ben ngoai.', '["Tan Uoc","Ve dep","Tam linh"]', '1 Peter 3:3-4', 'vi', true, NOW(), NOW()),
('q-1pe-014', '1 Peter', 2, 11, 11, 'easy', 'multiple_choice_single',
'1 Phi 2:11 goi tin do la gi tren dat?',
'["Khach la va kiem cu (luot qua)", "Cong dan", "Chu nhan", "Quan an"]',
'[0]', 'Chung ta la khach tru tren dat, que huong that o tren troi.', '["Tan Uoc","Khach la","The gian"]', '1 Peter 2:11', 'vi', true, NOW(), NOW()),
('q-1pe-015', '1 Peter', 5, 10, 10, 'easy', 'multiple_choice_single',
'1 Phi 5:10: Sau khi chiu kho it lau, Chua se lam gi cho anh em?',
'["Chinh don, lam cho vung, them suc, dung tren nen vung", "De mac", "Doi thay", "Phat them"]',
'[0]', 'Kho nan la tam thoi. Chua se phuc hoi, lam cho vung va tang suc cho chung ta.', '["Tan Uoc","Phuc hoi","Hy vong"]', '1 Peter 5:10', 'vi', true, NOW(), NOW()),

-- 1 JOHN (+13)
('q-1jo-003', '1 John', 1, 7, 7, 'easy', 'multiple_choice_single',
'1 Giang 1:7: Neu chung ta buoc di trong su sang thi huyet Chua Gie-su lam gi?',
'["Tay sach moi toi loi chung ta", "Bao ve chung ta", "Chua lanh chung ta", "An uy chung ta"]',
'[0]', 'Buoc di trong su sang + huyet Chua = su tay sach lien tuc khoi toi loi.', '["Tan Uoc","Tay sach","Huyet"]', '1 John 1:7', 'vi', true, NOW(), NOW()),
('q-1jo-004', '1 John', 2, 1, 2, 'easy', 'multiple_choice_single',
'1 Giang 2:1-2: Khi pham toi, ai la Dang bao chua cho chung ta?',
'["Chua Gie-su Christ, Dang cong binh", "Thien su", "Moi-se", "Phi-e-ro"]',
'[0]', 'Chua Gie-su la luat su bao chua va cung la cua le chuoc toi cho chung ta.', '["Tan Uoc","Bao chua","Chuoc toi"]', '1 John 2:1-2', 'vi', true, NOW(), NOW()),
('q-1jo-005', '1 John', 2, 15, 16, 'easy', 'multiple_choice_single',
'1 Giang 2:15: "Dung yeu ___" vi moi su o trong do khong phai tu Cha',
'["The gian va nhung dieu thuoc the gian", "Gia dinh", "Cong viec", "Ban be"]',
'[0]', 'He thong gia tri the gian (duc ham muoi, duc ham mat, su kieu ngao) chong lai Chua.', '["Tan Uoc","The gian","Canh bao"]', '1 John 2:15-16', 'vi', true, NOW(), NOW()),
('q-1jo-006', '1 John', 3, 1, 1, 'easy', 'fill_in_blank',
'Hay xem Duc Chua Cha ban cho chung ta su yeu thuong dong nao, de chung ta duoc goi la ___ cua Duc Chua Troi (1 Giang 3:1)',
'[]', '[]', 'Dia vi cao quy nhat: con cai cua Chua! Khong phai toi to ma la con.', '["Tan Uoc","Con cai","Tinh yeu"]', '1 John 3:1', 'vi', true, NOW(), NOW()),
('q-1jo-007', '1 John', 3, 16, 16, 'easy', 'multiple_choice_single',
'1 Giang 3:16: Boi dieu nay chung ta biet tinh yeu thuong: Ngai da ___ vi chung ta',
'["Phoi mang song Ngai", "Cau nguyen", "Day do", "Chua lanh"]',
'[0]', 'Dinh nghia tinh yeu: hy sinh mang song. Va chung ta cung phai lam vay cho anh em.', '["Tan Uoc","Tinh yeu","Hy sinh"]', '1 John 3:16', 'vi', true, NOW(), NOW()),
('q-1jo-008', '1 John', 3, 18, 18, 'easy', 'multiple_choice_single',
'1 Giang 3:18: "Hay yeu thuong khong chi bang loi noi va luoi nhung bang ___"',
'["Viec lam va le that", "Cam xuc", "Tien bac", "Loi hua"]',
'[0]', 'Tinh yeu that bieu hien qua hanh dong cu the, khong chi loi noi.', '["Tan Uoc","Tinh yeu","Hanh dong"]', '1 John 3:18', 'vi', true, NOW(), NOW()),
('q-1jo-009', '1 John', 4, 4, 4, 'easy', 'fill_in_blank',
'Dang o trong cac con lon hon ke o trong ___ (1 Giang 4:4)',
'[]', '[]', 'Thanh Linh o trong tin do manh hon moi the luc toi tam trong the gian.', '["Tan Uoc","Chien thang","Thanh Linh"]', '1 John 4:4', 'vi', true, NOW(), NOW()),
('q-1jo-010', '1 John', 4, 18, 18, 'easy', 'multiple_choice_single',
'1 Giang 4:18: Tinh yeu tron ven lam gi voi su so hai?',
'["Cat bo su so hai", "Tang su so hai", "Khong lien quan", "Giau su so hai"]',
'[0]', 'Khi biet Chua yeu chung ta tron ven, su so hai bi xua tan.', '["Tan Uoc","Tinh yeu","So hai"]', '1 John 4:18', 'vi', true, NOW(), NOW()),
('q-1jo-011', '1 John', 4, 19, 19, 'easy', 'multiple_choice_single',
'1 Giang 4:19: "Chung ta yeu vi ___ da yeu chung ta truoc"',
'["Ngai (Chua)", "Chung ta muon", "Phai lam", "Tat nhien"]',
'[0]', 'Tinh yeu cua chung ta chi la phan hoi tinh yeu Chua da ban truoc.', '["Tan Uoc","Tinh yeu","Nguon"]', '1 John 4:19', 'vi', true, NOW(), NOW()),
('q-1jo-012', '1 John', 5, 3, 3, 'easy', 'multiple_choice_single',
'1 Giang 5:3: Yeu Chua la gi?',
'["Giu cac dieu ran Ngai, va dieu ran Ngai khong nang ne", "Cau nguyen nhieu", "Di nha tho", "Dang cua le"]',
'[0]', 'Yeu = vang loi. Va dieu ran Chua khong nang ne khi co Thanh Linh giup.', '["Tan Uoc","Vang loi","Tinh yeu"]', '1 John 5:3', 'vi', true, NOW(), NOW()),
('q-1jo-013', '1 John', 5, 11, 12, 'easy', 'fill_in_blank',
'Ai co Con thi co su ___; ai khong co Con Duc Chua Troi thi khong co su song (1 Giang 5:12)',
'[]', '[]', 'Su song doi doi gan lien voi Chua Gie-su. Co Ngai = co su song.', '["Tan Uoc","Su song","Chua Gie-su"]', '1 John 5:11-12', 'vi', true, NOW(), NOW()),
('q-1jo-014', '1 John', 5, 14, 15, 'easy', 'multiple_choice_single',
'1 Giang 5:14: Neu cau xin dieu gi theo y muon Chua thi Ngai se ___',
'["Nghe chung ta", "Suy nghi", "Doi", "Thu"]',
'[0]', 'Cau nguyen theo y Chua la chia khoa duoc Ngai nghe va dap loi.', '["Tan Uoc","Cau nguyen","Y Chua"]', '1 John 5:14-15', 'vi', true, NOW(), NOW()),
('q-1jo-015', '1 John', 4, 10, 10, 'medium', 'multiple_choice_single',
'1 Giang 4:10: Tinh yeu la the nay: khong phai chung ta yeu Chua nhung ___ da yeu chung ta va sai Con Ngai lam cua le chuoc toi',
'["Ngai", "Chung ta", "Thien su", "Tien tri"]',
'[0]', 'Tinh yeu khoi xuong tu Chua, khong phai tu chung ta. Chua chu dong yeu truoc.', '["Tan Uoc","Tinh yeu","Chu dong"]', '1 John 4:10', 'vi', true, NOW(), NOW()),

-- REVELATION (+12)
('q-rev-004', 'Revelation', 1, 8, 8, 'easy', 'multiple_choice_single',
'Khai 1:8: Chua tuyen bo Ngai la gi?',
'["An-pha va O-me-ga, Dang Hien Co Dang Da Co va Dang Se Den", "Vua", "Quan an", "Tien tri"]',
'[0]', 'Chua la dau va cuoi, co tu muon doi va se den. Ngai kiem soat lich su.', '["Tan Uoc","Khai huyen","Than tinh"]', 'Revelation 1:8', 'vi', true, NOW(), NOW()),
('q-rev-005', 'Revelation', 1, 17, 18, 'easy', 'multiple_choice_single',
'Chua Gie-su noi: "Ta la Dang Song; ta da chet nhung nay ta ___"',
'["Song doi doi va cam chia khoa cua su chet va am phu", "O tren troi", "Dang doi", "Nghi ngoi"]',
'[0]', 'Chua Gie-su da chien thang su chet va co quyen tren su chet va am phu.', '["Tan Uoc","Phuc sinh","Quyen nang"]', 'Revelation 1:17-18', 'vi', true, NOW(), NOW()),
('q-rev-006', 'Revelation', 2, 10, 10, 'easy', 'fill_in_blank',
'Hay trung tin cho den chet, ta se ban cho nguoi mao trieu su ___ (Khai 2:10)',
'[]', '[]', 'Phan thuong cho su trung tin: mao trieu su song. Trung tin den cuoi.', '["Tan Uoc","Trung tin","Phan thuong"]', 'Revelation 2:10', 'vi', true, NOW(), NOW()),
('q-rev-007', 'Revelation', 4, 8, 8, 'easy', 'multiple_choice_single',
'Bon sinh vat truoc ngai Chua keu ngay dem: "___! Thanh thay! Thanh thay la Chua..."',
'["Thanh thay", "Vinh hien", "Ha-le-lu-gia", "Quyen nang"]',
'[0]', 'Nhu E-sai 6:3, su thanh khiet cua Chua la chu de ngoi khen o thien dang.', '["Tan Uoc","Ngoi khen","Thien dang"]', 'Revelation 4:8', 'vi', true, NOW(), NOW()),
('q-rev-008', 'Revelation', 5, 5, 5, 'medium', 'multiple_choice_single',
'Ai xung dang mo cuon sach 7 an?',
'["Su Tu chi phai Giu-da, Got Da-vit (Chua Gie-su)", "Thien su Mi-ca-en", "Moi-se", "Da-vit"]',
'[0]', 'Chi Chua Gie-su xung dang vi Ngai da chien thang boi su chet va phuc sinh.', '["Tan Uoc","Chien Con","Xung dang"]', 'Revelation 5:5', 'vi', true, NOW(), NOW()),
('q-rev-009', 'Revelation', 5, 12, 12, 'easy', 'fill_in_blank',
'Chien Con da bi giet dang nhan quyen phep, su giau co, su khon ngoan, suc manh, ton quy, vinh hien va su ___!',
'[]', '[]', 'Khai 5:12 - Bay dieu ngoi khen danh cho Chien Con. Su ton vinh tron ven.', '["Tan Uoc","Ngoi khen","Chien Con"]', 'Revelation 5:12', 'vi', true, NOW(), NOW()),
('q-rev-010', 'Revelation', 7, 9, 10, 'easy', 'multiple_choice_single',
'Khai 7:9 mo ta doan dong khong ai dem duoc tu dau?',
'["Moi dan toc, moi nu phai, moi dan, moi tieng", "Chi Y-so-ra-en", "Chi thien su", "Chi tu dao"]',
'[0]', 'Thien dang la noi da van hoa, da sac toc. Phuc Am cho moi nguoi.', '["Tan Uoc","Thien dang","Moi dan toc"]', 'Revelation 7:9-10', 'vi', true, NOW(), NOW()),
('q-rev-011', 'Revelation', 12, 11, 11, 'medium', 'multiple_choice_single',
'Khai 12:11: Cac thanh do thang ma quy nho gi?',
'["Huyet Chien Con va loi lam chung cua ho", "Guom", "Quan doi", "Tri thuc"]',
'[0]', 'Vu khi chien thang: huyet Chua + loi lam chung + san sang chet vi Chua.', '["Tan Uoc","Chien thang","Lam chung"]', 'Revelation 12:11', 'vi', true, NOW(), NOW()),
('q-rev-012', 'Revelation', 19, 11, 16, 'easy', 'multiple_choice_single',
'Chua Gie-su tai lam cuoi tren ngua mau gi?',
'["Trang", "Do", "Den", "Vang"]',
'[0]', 'Khai 19:11 - Ngai la Dang Thanh Tin va Chan That, cuoi ngua trang, mac ao nhuom huyet.', '["Tan Uoc","Tai lam","Chien thang"]', 'Revelation 19:11-16', 'vi', true, NOW(), NOW()),
('q-rev-013', 'Revelation', 21, 1, 2, 'easy', 'multiple_choice_single',
'Khai 21:1: Sau su phan xet cuoi cung, Chua tao dieu gi?',
'["Troi moi va dat moi", "Den tho moi", "Vuon E-den moi", "Thanh pho moi"]',
'[0]', 'Moi su duoc lam moi hoan toan. Troi va dat cu da qua di.', '["Tan Uoc","Troi moi","Doi doi"]', 'Revelation 21:1-2', 'vi', true, NOW(), NOW()),
('q-rev-014', 'Revelation', 21, 3, 4, 'easy', 'fill_in_blank',
'Khai 21:3: "Nay leu tam cua Duc Chua Troi o giua loai nguoi! Ngai se o voi ho, ho se lam ___ Ngai"',
'[]', '[]', 'Muc dich cuoi cung cua lich su: Chua va con nguoi o voi nhau mai mai.', '["Tan Uoc","Doi doi","Hien dien"]', 'Revelation 21:3-4', 'vi', true, NOW(), NOW()),
('q-rev-015', 'Revelation', 22, 17, 17, 'easy', 'multiple_choice_single',
'Khai 22:17: Thanh Linh va co dau (Hoi thanh) noi gi?',
'["Hay den! Ai khat hay den va nhan nuoc su song khong", "Hay doi", "Hay cau nguyen", "Hay chien dau"]',
'[0]', 'Loi moi cuoi cung cua Kinh Thanh: Hay den nhan su song mien phi tu Chua.', '["Tan Uoc","Loi moi","Nuoc song"]', 'Revelation 22:17', 'vi', true, NOW(), NOW());
