-- Repeatable migration: New Testament questions (Matthew - Revelation)
-- Smart questions: context, theology, connections, application

-- ==================== MATTHEW ====================
INSERT IGNORE INTO questions (id, book, chapter, verse_start, verse_end, difficulty, type, content, options, correct_answer, explanation, tags, source, language, is_active, created_at, updated_at) VALUES

('q-mat-001', 'Matthew', 1, 21, 21, 'easy', 'multiple_choice_single',
'Ten "Gie-su" (Yeshua) co nghia la gi?',
'["Gie-ho-va cuu roi", "Duc Chua Troi o cung chung ta", "Dang duoc xuc dau", "Vua cua muon vua"]',
'[0]',
'Mat 1:21 - Gie-su (Yeshua) co nghia la "Gie-ho-va cuu roi". Ten Ngai bieu lo muc dich den the gian.',
'["Tan Uoc","Giang sinh","Danh Chua"]', 'Matthew 1:21', 'vi', true, NOW(), NOW()),

('q-mat-002', 'Matthew', 1, 23, 23, 'easy', 'fill_in_blank',
'Em-ma-nu-en co nghia la gi? (Tra loi 5-6 tu)',
'[]', '[]',
'Mat 1:23 - Em-ma-nu-en nghia la Duc Chua Troi o cung chung ta.',
'["Tan Uoc","Giang sinh","Danh Chua"]', 'Matthew 1:23', 'vi', true, NOW(), NOW()),

('q-mat-003', 'Matthew', 3, 16, 17, 'medium', 'multiple_choice_single',
'Tai Le Bap-tem cua Chua Gie-su, ca Ba Ngoi Duc Chua Troi hien dien nhu the nao?',
'["Con duoc bap-tem, Thanh Linh nhu chim bo cau, Cha phan tu troi", "Chi co Con va Cha", "Chi co Thanh Linh", "Khong ro rang"]',
'[0]',
'Mat 3:16-17 - Chua Gie-su (Con) chiu bap-tem, Duc Thanh Linh ngu xuong nhu chim bo cau, Duc Chua Cha phan: Day la Con yeu dau cua Ta.',
'["Tan Uoc","Bap-tem","Ba Ngoi"]', 'Matthew 3:16-17', 'vi', true, NOW(), NOW()),

('q-mat-004', 'Matthew', 4, 4, 4, 'easy', 'multiple_choice_single',
'Khi bi Sa-tan cam do bien da thanh banh, Chua Gie-su dap gi?',
'["Nguoi ta song khong chi nho banh, nhung boi moi loi Chua", "Ngươi khong duoc cam do Chua", "Hay lui ra Sa-tan", "Ta khong doi"]',
'[0]',
'Mat 4:4 - Chua Gie-su dung Loi Chua (Phuc truyen 8:3) de chong lai moi cam do cua Sa-tan.',
'["Tan Uoc","Cam do","Loi Chua"]', 'Matthew 4:4', 'vi', true, NOW(), NOW()),

('q-mat-005', 'Matthew', 5, 3, 3, 'medium', 'multiple_choice_single',
'Bat Phuc (Beatitudes) bat dau bang: "Phuc cho nhung nguoi ___"',
'["Co long kho khan (ngheo kho trong tam linh)", "Giau co", "Thanh cong", "Khon ngoan"]',
'[0]',
'Mat 5:3 - Phuc cho nhung ai y thuc su ngheo nan tam linh cua minh, vi nuoc thien dang thuoc ve ho.',
'["Tan Uoc","Bai Giang Tren Nui","Bat Phuc"]', 'Matthew 5:3', 'vi', true, NOW(), NOW()),

('q-mat-006', 'Matthew', 5, 44, 44, 'medium', 'multiple_choice_single',
'Chua Gie-su day dieu gi ve ke thu?',
'["Hay yeu ke thu va cau nguyen cho ke bat bo cac nguoi", "Hay tranh xa ke thu", "Hay bao thu cong bang", "Hay tha thu nhung khong can yeu"]',
'[0]',
'Mat 5:44 - Day la su day dang cap nhat cua Chua Gie-su, vuot qua moi luat phap va dao duc thuong tinh.',
'["Tan Uoc","Bai Giang Tren Nui","Yeu thuong"]', 'Matthew 5:44', 'vi', true, NOW(), NOW()),

('q-mat-007', 'Matthew', 6, 9, 13, 'easy', 'multiple_choice_single',
'Bai cau nguyen mau cua Chua Gie-su bat dau bang loi nao?',
'["Lay Cha chung con o tren troi", "Lay Duc Chua Troi", "Lay Chua", "Lay Dang Toan Nang"]',
'[0]',
'Mat 6:9 - Chua Gie-su day chung ta goi Chua la Cha, the hien moi quan he ga gui voi Ngai.',
'["Tan Uoc","Cau nguyen","Bai cau nguyen mau"]', 'Matthew 6:9-13', 'vi', true, NOW(), NOW()),

('q-mat-008', 'Matthew', 6, 33, 33, 'easy', 'fill_in_blank',
'Hay tim kiem ___ va su cong binh cua Ngai truoc het, roi moi dieu ay se duoc them cho.',
'[]', '[]',
'Mat 6:33 - Hay tim kiem nuoc Duc Chua Troi va su cong binh truoc, Chua se lo lieu moi nhu cau khac.',
'["Tan Uoc","Bai Giang Tren Nui","Uu tien"]', 'Matthew 6:33', 'vi', true, NOW(), NOW()),

('q-mat-009', 'Matthew', 7, 13, 14, 'medium', 'multiple_choice_single',
'Chua Gie-su noi ve hai con duong: cua hep dan den dau?',
'["Su song", "Thien dang", "Su khon ngoan", "Su binh an"]',
'[0]',
'Mat 7:14 - Cua hep, duong chat dan den su song, va it nguoi tim duoc. Cua rong, duong khoan dan den su huy diet.',
'["Tan Uoc","Bai Giang Tren Nui","Su lua chon"]', 'Matthew 7:13-14', 'vi', true, NOW(), NOW()),

('q-mat-010', 'Matthew', 16, 16, 16, 'easy', 'multiple_choice_single',
'Phi-e-ro tuyen bo ve Chua Gie-su: "Thay la ___"',
'["Dang Christ, Con Duc Chua Troi hang song", "Mot vi tien tri", "Thay giao vi dai", "Vua Y-so-ra-en"]',
'[0]',
'Mat 16:16 - Day la loi tuyen xung duc tin quan trong nhat cua Phi-e-ro, duoc Chua Gie-su khen ngoi.',
'["Tan Uoc","Phi-e-ro","Duc tin"]', 'Matthew 16:16', 'vi', true, NOW(), NOW()),

('q-mat-011', 'Matthew', 22, 37, 39, 'easy', 'multiple_choice_single',
'Chua Gie-su noi dieu ran nao la lon nhat?',
'["Yeu Chua het long, het linh hon, het tri", "Khong giet nguoi", "Giu ngay Sa-bat", "Khong tho hinh tuong"]',
'[0]',
'Mat 22:37-38 - Yeu Chua het long la dieu ran lon nhat, va yeu nguoi nhu minh la dieu ran thu hai.',
'["Tan Uoc","Dieu ran","Yeu thuong"]', 'Matthew 22:37-39', 'vi', true, NOW(), NOW()),

('q-mat-012', 'Matthew', 28, 19, 20, 'easy', 'multiple_choice_single',
'Dai mang lenh (Great Commission) cua Chua Gie-su la gi?',
'["Hay di khien moi dan toc tro thanh mon do", "Hay xay nha tho", "Hay giu luat phap", "Hay cau nguyen lien tuc"]',
'[0]',
'Mat 28:19 - Hay di khien moi dan toc tro thanh mon do, lam bap-tem nhan danh Cha, Con va Thanh Linh.',
'["Tan Uoc","Dai mang lenh","Mon do"]', 'Matthew 28:19-20', 'vi', true, NOW(), NOW()),

-- ==================== MARK ====================

('q-mar-001', 'Mark', 2, 17, 17, 'easy', 'multiple_choice_single',
'Chua Gie-su noi: "Nguoi khoe manh khong can thay thuoc, nhung nguoi ___ moi can"',
'["Dau", "Ngheo", "Co don", "Yeu duoi"]',
'[0]',
'Mac 2:17 - Chua Gie-su den khong phai de goi nguoi cong binh, nhung de goi ke co toi an nan.',
'["Tan Uoc","Su vu Gie-su","An dien"]', 'Mark 2:17', 'vi', true, NOW(), NOW()),

('q-mar-002', 'Mark', 10, 45, 45, 'medium', 'multiple_choice_single',
'Chua Gie-su noi Con Nguoi den khong phai de duoc ___, nhung de ___',
'["Phuc vu / phuc vu va phoi mang song lam gia chuoc", "Lam vua / lam vua", "Duoc ton tho / ton tho", "Xet doan / tha thu"]',
'[0]',
'Mac 10:45 - Day la tom tat su vu cua Chua Gie-su: phuc vu va hy sinh mang song chuoc toi cho nhieu nguoi.',
'["Tan Uoc","Phuc vu","Cuu chuoc"]', 'Mark 10:45', 'vi', true, NOW(), NOW()),

('q-mar-003', 'Mark', 12, 41, 44, 'easy', 'multiple_choice_single',
'Tai sao Chua Gie-su khen ba goa bo 2 dong xu nho?',
'["Ba cho tat ca nhung gi ba co de song", "Vi ba ngheo", "Vi ba co duc tin", "Vi ba lam cong khai"]',
'[0]',
'Mac 12:44 - Nguoi giau cho tu su du, nhung ba goa cho tat ca nhung gi ba co de sinh song. Chua nhin tam long va su hy sinh.',
'["Tan Uoc","Dang hien","Tam long"]', 'Mark 12:41-44', 'vi', true, NOW(), NOW()),

-- ==================== LUKE ====================

('q-luk-001', 'Luke', 1, 37, 37, 'easy', 'fill_in_blank',
'Thien su Gab-ri-en noi voi Ma-ri: "Vi khong viec chi Duc Chua Troi chang ___"',
'[]', '[]',
'Lu-ca 1:37 - Khong viec chi Duc Chua Troi chang lam duoc. Loi khang dinh quyen nang vo han cua Chua.',
'["Tan Uoc","Giang sinh","Quyen nang"]', 'Luke 1:37', 'vi', true, NOW(), NOW()),

('q-luk-002', 'Luke', 2, 7, 7, 'easy', 'multiple_choice_single',
'Chua Gie-su duoc sinh ra o dau?',
'["Trong chuong gia suc tai Bet-le-hem", "Trong cung dien", "Trong nha hoi", "Trong nha tro"]',
'[0]',
'Lu-ca 2:7 - Ma-ri sinh con trai dau long, bo trong khan, dat nam trong mang co vi khong co cho trong nha tro.',
'["Tan Uoc","Giang sinh","Khiem nhuong"]', 'Luke 2:7', 'vi', true, NOW(), NOW()),

('q-luk-003', 'Luke', 10, 30, 37, 'easy', 'multiple_choice_single',
'Trong chuyen ngu ngon Nguoi Sa-ma-ri Nhan Lanh, ai da giup nguoi bi cuop?',
'["Nguoi Sa-ma-ri", "Thay te le", "Nguoi Le-vi", "Quan linh La-ma"]',
'[0]',
'Lu-ca 10:33-34 - Nguoi Sa-ma-ri (bi nguoi Do-thai khinh che) lai la nguoi duy nhat dong long thuong xot va giup do.',
'["Tan Uoc","Du ngon","Yeu thuong"]', 'Luke 10:30-37', 'vi', true, NOW(), NOW()),

('q-luk-004', 'Luke', 15, 4, 7, 'easy', 'multiple_choice_single',
'Trong du ngon Chien Con Lac Mat, nguoi chan co bao nhieu con chien truoc khi mat 1 con?',
'["100 con", "50 con", "200 con", "99 con"]',
'[0]',
'Lu-ca 15:4 - Nguoi chan co 100 con, mat 1, bo 99 con lai de di tim con bi lac. Minh hoa tinh yeu cua Chua doi voi ke toi loi.',
'["Tan Uoc","Du ngon","Tinh yeu Chua"]', 'Luke 15:4-7', 'vi', true, NOW(), NOW()),

('q-luk-005', 'Luke', 15, 11, 32, 'medium', 'multiple_choice_single',
'Trong du ngon Dua Con Hoang Dang, khi con tro ve, nguoi cha lam gi?',
'["Chay ra om hon va lam tiec mung", "Trach mang truoc roi tha thu", "Tu choi gap mat", "Bat lam toi tro"]',
'[0]',
'Lu-ca 15:20-24 - Cha chay ra om va hon con, mac ao tot nhat, deo nhan, lam tiec. Hinh anh dep ve Chua chao don ke toi loi an nan.',
'["Tan Uoc","Du ngon","Tha thu"]', 'Luke 15:11-32', 'vi', true, NOW(), NOW()),

('q-luk-006', 'Luke', 23, 34, 34, 'easy', 'fill_in_blank',
'Tren thap tu, Chua Gie-su cau nguyen: "Lay Cha, xin ___ cho ho vi ho khong biet minh lam dieu gi"',
'[]', '[]',
'Lu-ca 23:34 - Ngay ca khi bi dong dinh, Chua Gie-su van cau xin su tha thu cho nhung ke giet Ngai.',
'["Tan Uoc","Thap tu","Tha thu"]', 'Luke 23:34', 'vi', true, NOW(), NOW()),

('q-luk-007', 'Luke', 23, 43, 43, 'medium', 'multiple_choice_single',
'Chua Gie-su hua gi voi ten cuop an nan tren thap tu?',
'["Hom nay nguoi se o voi ta trong Ba-ra-di", "Nguoi se duoc phuc sinh", "Toi cua nguoi da duoc tha", "Nguoi se duoc nho den"]',
'[0]',
'Lu-ca 23:43 - Su cuu roi chi can duc tin chan that, khong can viec lam. Ten cuop chi can tin va duoc Chua hua thien dang.',
'["Tan Uoc","Thap tu","An dien"]', 'Luke 23:43', 'vi', true, NOW(), NOW()),

-- ==================== JOHN ====================

('q-joh-001', 'John', 1, 1, 1, 'medium', 'multiple_choice_single',
'Giang 1:1 noi "Ban dau co Ngoi Loi." Ngoi Loi la ai?',
'["Chua Gie-su Christ", "Duc Chua Cha", "Duc Thanh Linh", "Thien su"]',
'[0]',
'Giang 1:1,14 - Ngoi Loi la Chua Gie-su, Dang tu muon doi o cung Duc Chua Troi va chinh la Duc Chua Troi.',
'["Tan Uoc","Than tinh Gie-su","Giang"]', 'John 1:1', 'vi', true, NOW(), NOW()),

('q-joh-002', 'John', 1, 14, 14, 'hard', 'multiple_choice_single',
'Giang 1:14 "Ngoi Loi da tro nen xac thit" day ve giao ly nao?',
'["Su nhap the (Incarnation) - Chua tro nen con nguoi", "Su sang tao", "Su phuc sinh", "Su tai lam"]',
'[0]',
'Giang 1:14 - Ngoi Loi (Chua Gie-su) tro nen xac thit, o giua chung ta - day la giao ly nhap the, Chua tron ven la Duc Chua Troi va tron ven la con nguoi.',
'["Tan Uoc","Than hoc","Nhap the"]', 'John 1:14', 'vi', true, NOW(), NOW()),

('q-joh-003', 'John', 3, 16, 16, 'easy', 'multiple_choice_single',
'Giang 3:16 duoc goi la "cau goc cua Phuc Am" vi sao?',
'["Tom tat toan bo su diep cuu roi: tinh yeu Chua, Con Ngai, duc tin, su song doi doi", "Vi la cau dai nhat", "Vi la cau dau tien", "Vi duoc viet boi Chua Gie-su"]',
'[0]',
'Giang 3:16 - Vi Duc Chua Troi yeu thuong the gian den noi ban Con mot Ngai, hau cho he ai tin Con ay khong bi hu mat ma duoc su song doi doi.',
'["Tan Uoc","Phuc Am","Cuu roi"]', 'John 3:16', 'vi', true, NOW(), NOW()),

('q-joh-004', 'John', 3, 3, 3, 'medium', 'multiple_choice_single',
'Chua Gie-su noi voi Ni-co-dem dieu kien de vao nuoc Chua la gi?',
'["Phai duoc sinh lai (tai sinh)", "Phai giu luat phap", "Phai dang cua le", "Phai lam viec lanh"]',
'[0]',
'Giang 3:3 - Phai duoc sinh lai tu nuoc va Thanh Linh. Khong phai sinh the xac lan nua ma la sinh thuoc linh.',
'["Tan Uoc","Tai sinh","Cuu roi"]', 'John 3:3', 'vi', true, NOW(), NOW()),

('q-joh-005', 'John', 8, 32, 32, 'easy', 'fill_in_blank',
'Chua Gie-su phan: "Cac nguoi se biet le that, va le that se buong ___ cho cac nguoi"',
'[]', '[]',
'Giang 8:32 - Le that (Chua Gie-su) giai phong chung ta khoi su no le cua toi loi.',
'["Tan Uoc","Le that","Tu do"]', 'John 8:32', 'vi', true, NOW(), NOW()),

('q-joh-006', 'John', 11, 25, 26, 'easy', 'multiple_choice_single',
'Chua Gie-su tuyen bo: "Ta la su ___ va su song"',
'["Song lai", "Binh an", "Yeu thuong", "Cong binh"]',
'[0]',
'Giang 11:25 - Chua Gie-su la su song lai va su song. Ai tin Ngai, du da chet, cung se song.',
'["Tan Uoc","Phuc sinh","Duc tin"]', 'John 11:25-26', 'vi', true, NOW(), NOW()),

('q-joh-007', 'John', 13, 34, 35, 'easy', 'multiple_choice_single',
'Chua Gie-su noi nguoi ta se nhan biet mon do Ngai nho dau hieu gi?',
'["Yeu thuong nhau", "Lam phep la", "Kien thuc Kinh Thanh", "Di nha tho"]',
'[0]',
'Giang 13:35 - Dau hieu cua mon do that la tinh yeu thuong lan nhau, khong phai tai nang hay kien thuc.',
'["Tan Uoc","Mon do","Yeu thuong"]', 'John 13:34-35', 'vi', true, NOW(), NOW()),

('q-joh-008', 'John', 14, 6, 6, 'easy', 'multiple_choice_single',
'Chua Gie-su phan: "Ta la duong di, le that va su song. Khong ai den duoc voi Cha ma khong ___"',
'["Boi ta", "Boi viec lanh", "Boi luat phap", "Boi ton giao"]',
'[0]',
'Giang 14:6 - Chua Gie-su la con duong duy nhat den voi Duc Chua Cha, khong co con duong nao khac.',
'["Tan Uoc","Con duong","Doc nhat"]', 'John 14:6', 'vi', true, NOW(), NOW()),

('q-joh-009', 'John', 15, 5, 5, 'medium', 'fill_in_blank',
'Chua Gie-su noi: "Ta la goc nho, cac nguoi la ___"',
'[]', '[]',
'Giang 15:5 - Ta la goc nho, cac nguoi la nhanh. Ai cu o trong ta thi ket nhieu qua.',
'["Tan Uoc","Goc nho","Lien ket"]', 'John 15:5', 'vi', true, NOW(), NOW()),

('q-joh-010', 'John', 19, 30, 30, 'easy', 'multiple_choice_single',
'Loi cuoi cung cua Chua Gie-su tren thap tu theo sach Giang la gi?',
'["Moi viec da duoc tron (It is finished)", "Lay Cha, con pho linh hon con", "Lay Cha, sao Cha bo con", "Con khat"]',
'[0]',
'Giang 19:30 - "Tetelestai" - Da hoan tat! Cong trinh cuu chuoc da duoc thanh toan tron ven.',
'["Tan Uoc","Thap tu","Cuu chuoc"]', 'John 19:30', 'vi', true, NOW(), NOW()),

('q-joh-011', 'John', 20, 29, 29, 'medium', 'multiple_choice_single',
'Sau khi Tho-ma so vao vet thuong, Chua Gie-su noi dieu gi ve duc tin?',
'["Phuc cho nhung ke khong thay ma tin", "Nguoi phai tin nhieu hon", "Duc tin can chung co", "Hay noi cho nguoi khac"]',
'[0]',
'Giang 20:29 - Chua Gie-su khen nhung ai tin ma khong can thay bang mat, nhu chung ta ngay nay.',
'["Tan Uoc","Phuc sinh","Duc tin"]', 'John 20:29', 'vi', true, NOW(), NOW()),

-- ==================== ACTS ====================

('q-act-001', 'Acts', 1, 8, 8, 'easy', 'multiple_choice_single',
'Truoc khi thang thien, Chua Gie-su hua cac mon do se nhan duoc gi?',
'["Quyen phep khi Duc Thanh Linh giang tren", "Vang bac", "Quyen luc chinh tri", "Su khon ngoan"]',
'[0]',
'Cong vu 1:8 - Khi Duc Thanh Linh giang tren, cac nguoi se nhan lanh quyen phep va lam chung ta khap dat.',
'["Tan Uoc","Thanh Linh","Lam chung"]', 'Acts 1:8', 'vi', true, NOW(), NOW()),

('q-act-002', 'Acts', 2, 1, 4, 'easy', 'multiple_choice_single',
'Ngay Le Ngu Tuan, dau hieu Duc Thanh Linh giang xuong la gi?',
'["Gio manh, luoi lua, noi cac thu tieng", "Chim bo cau", "Dam may sang", "Dong dat"]',
'[0]',
'Cong vu 2:2-4 - Gio tu troi, luoi lua dau tren dau moi nguoi, va ho noi cac thu tieng khac boi quyen nang Thanh Linh.',
'["Tan Uoc","Le Ngu Tuan","Thanh Linh"]', 'Acts 2:1-4', 'vi', true, NOW(), NOW()),

('q-act-003', 'Acts', 2, 38, 38, 'medium', 'multiple_choice_single',
'Phi-e-ro rao giang ngay Le Ngu Tuan, keu goi moi nguoi lam gi?',
'["An nan va chiu bap-tem nhan danh Chua Gie-su", "Giu luat Moi-se", "Roi Gie-ru-sa-lem", "Dang cua le"]',
'[0]',
'Cong vu 2:38 - Phi-e-ro keu goi an nan (doi huong), bap-tem nhan danh Chua, va nhan lanh Duc Thanh Linh.',
'["Tan Uoc","Giao ly","An nan"]', 'Acts 2:38', 'vi', true, NOW(), NOW()),

('q-act-004', 'Acts', 9, 3, 6, 'easy', 'multiple_choice_single',
'Sau-lo (sau la su do Phao-lo) gap Chua Gie-su tren duong di dau?',
'["Da-mat", "Gie-ru-sa-lem", "An-ti-ot", "La-ma"]',
'[0]',
'Cong vu 9:3 - Tren duong Da-mat, anh sang tu troi chieu xuong va Chua Gie-su phan voi Sau-lo.',
'["Tan Uoc","Phao-lo","Bien doi"]', 'Acts 9:3-6', 'vi', true, NOW(), NOW()),

('q-act-005', 'Acts', 16, 31, 31, 'easy', 'fill_in_blank',
'Phao-lo noi voi nguoi giu nguc Phi-lip: "Hay ___ Duc Chua Gie-su thi nguoi va ca nha deu se duoc cuu"',
'[]', '[]',
'Cong vu 16:31 - Tin Chua Gie-su Christ la dieu kien duy nhat de duoc cuu roi.',
'["Tan Uoc","Cuu roi","Duc tin"]', 'Acts 16:31', 'vi', true, NOW(), NOW()),

-- ==================== ROMANS ====================

('q-rom-001', 'Romans', 3, 23, 23, 'easy', 'multiple_choice_single',
'Ro-ma 3:23 noi rang ai da pham toi?',
'["Moi nguoi deu da pham toi", "Chi ke ac", "Chi nguoi ngoai dao", "Chi A-dam va E-va"]',
'[0]',
'Ro-ma 3:23 - Vi moi nguoi deu da pham toi, thieu mat su vinh hien cua Duc Chua Troi. Khong ai ngoai le.',
'["Tan Uoc","Cuu roi","Toi loi"]', 'Romans 3:23', 'vi', true, NOW(), NOW()),

('q-rom-002', 'Romans', 5, 8, 8, 'easy', 'multiple_choice_single',
'Theo Ro-ma 5:8, Chua bay to tinh yeu voi chung ta khi nao?',
'["Khi chung ta con la nguoi co toi", "Khi chung ta lam lanh", "Khi chung ta cau nguyen", "Khi chung ta an nan"]',
'[0]',
'Ro-ma 5:8 - Dang khi chung ta con la ke co toi, Chua Gie-su da chet thay cho chung ta. Tinh yeu vo dieu kien.',
'["Tan Uoc","An dien","Tinh yeu"]', 'Romans 5:8', 'vi', true, NOW(), NOW()),

('q-rom-003', 'Romans', 6, 23, 23, 'easy', 'multiple_choice_single',
'Ro-ma 6:23 noi: "Tien cong cua toi loi la su chet, nhung an dien cua Duc Chua Troi la ___"',
'["Su song doi doi trong Chua Gie-su Christ", "Su tha thu", "Su binh an", "Su khon ngoan"]',
'[0]',
'Ro-ma 6:23 - Toi loi dan den su chet, nhung mon qua mien phi cua Chua la su song doi doi qua Chua Gie-su.',
'["Tan Uoc","Cuu roi","An dien"]', 'Romans 6:23', 'vi', true, NOW(), NOW()),

('q-rom-004', 'Romans', 8, 28, 28, 'easy', 'fill_in_blank',
'Moi su hiep lai lam ___ cho ke yeu men Duc Chua Troi (Ro-ma 8:28)',
'[]', '[]',
'Ro-ma 8:28 - Chua bien moi su thanh ich loi cho nhung ai yeu men Ngai va duoc goi theo y muon Ngai.',
'["Tan Uoc","Chu quyen","An uy"]', 'Romans 8:28', 'vi', true, NOW(), NOW()),

('q-rom-005', 'Romans', 8, 38, 39, 'medium', 'multiple_choice_single',
'Theo Ro-ma 8:38-39, dieu gi co the phan cach chung ta khoi tinh yeu cua Chua?',
'["Khong gi ca - khong su chet, su song, hay bat cu dieu gi", "Toi loi nghiem trong", "Su bo dao", "Su phan boi"]',
'[0]',
'Ro-ma 8:38-39 - Khong co gi co the phan cach chung ta khoi tinh yeu cua Duc Chua Troi trong Chua Gie-su Christ.',
'["Tan Uoc","An dien","Tinh yeu"]', 'Romans 8:38-39', 'vi', true, NOW(), NOW()),

('q-rom-006', 'Romans', 10, 9, 10, 'medium', 'multiple_choice_single',
'Ro-ma 10:9 noi hai dieu kien de duoc cuu la gi?',
'["Mieng tuyen xung Gie-su la Chua va long tin Chua da song lai", "Chiu bap-tem va giu luat phap", "An nan va dang cua le", "Cau nguyen va an chay"]',
'[0]',
'Ro-ma 10:9 - Neu mieng nguoi tuyen xung Gie-su la Chua va long nguoi tin Duc Chua Troi da keo Ngai tu ke chet song lai thi nguoi se duoc cuu.',
'["Tan Uoc","Cuu roi","Tuyen xung"]', 'Romans 10:9-10', 'vi', true, NOW(), NOW()),

('q-rom-007', 'Romans', 12, 2, 2, 'medium', 'multiple_choice_single',
'Ro-ma 12:2 khuyen chung ta dung lam theo doi nay nhung hay doi moi the nao?',
'["Doi moi tam tri", "Doi moi hanh vi", "Doi moi hinh thuc", "Doi moi moi truong"]',
'[0]',
'Ro-ma 12:2 - Su bien doi bat dau tu tam tri. Khi tam tri duoc doi moi boi Loi Chua, hanh vi se thay doi.',
'["Tan Uoc","Bien doi","Tam tri"]', 'Romans 12:2', 'vi', true, NOW(), NOW()),

-- ==================== 1 & 2 CORINTHIANS ====================

('q-1co-001', '1 Corinthians', 13, 4, 7, 'easy', 'multiple_choice_single',
'Theo 1 Co-rinh-to 13, tinh yeu thuong bat dau bang dieu gi?',
'["Hay nhin nhuc va nhan tu", "Hay hy sinh", "Hay cho di", "Hay tha thu"]',
'[0]',
'1 Co 13:4 - Tinh yeu hay nhin nhuc, tinh yeu hay nhan tu. Nhin nhuc va nhan tu la nen tang cua tinh yeu thuong that.',
'["Tan Uoc","Tinh yeu","Doi song"]', '1 Corinthians 13:4-7', 'vi', true, NOW(), NOW()),

('q-1co-002', '1 Corinthians', 13, 13, 13, 'easy', 'multiple_choice_single',
'Trong ba dieu con lai mai: duc tin, su tram trong va tinh yeu thuong, dieu nao lon hon het?',
'["Tinh yeu thuong", "Duc tin", "Su tram trong (hy vong)", "Ca ba bang nhau"]',
'[0]',
'1 Co 13:13 - Tinh yeu thuong lon hon het vi no la ban tinh cua Duc Chua Troi (1 Giang 4:8).',
'["Tan Uoc","Tinh yeu","Than hoc"]', '1 Corinthians 13:13', 'vi', true, NOW(), NOW()),

('q-1co-003', '1 Corinthians', 15, 3, 4, 'hard', 'multiple_choice_single',
'Theo 1 Co 15:3-4, Phuc Am co the tom tat trong may dieu cot loi?',
'["3 dieu: Christ chet vi toi, duoc chon va song lai ngay thu ba", "1 dieu: tin Chua", "5 dieu rang buoc", "7 bi tich"]',
'[0]',
'1 Co 15:3-4 - Phuc Am la: Christ chet vi toi loi (1), duoc chon (2), va song lai ngay thu ba (3) dung nhu Kinh Thanh.',
'["Tan Uoc","Phuc Am","Cot loi"]', '1 Corinthians 15:3-4', 'vi', true, NOW(), NOW()),

('q-2co-001', '2 Corinthians', 5, 17, 17, 'easy', 'multiple_choice_single',
'2 Co 5:17 noi khi ai o trong Chua Gie-su thi nguoi ay la gi?',
'["Tao vat moi", "Nguoi tot hon", "Thanh nhan", "Thien su"]',
'[0]',
'2 Co 5:17 - Neu ai o trong Dang Christ thi nguoi ay la tao vat moi. Nhung su cu da qua di, nay moi su deu tro nen moi.',
'["Tan Uoc","Tai sinh","Doi moi"]', '2 Corinthians 5:17', 'vi', true, NOW(), NOW()),

('q-2co-002', '2 Corinthians', 12, 9, 9, 'medium', 'fill_in_blank',
'Chua phan voi Phao-lo: "An dien ta du cho nguoi roi, vi suc manh cua ta nen tron ven trong su ___"',
'[]', '[]',
'2 Co 12:9 - Suc manh cua Chua nen tron ven trong su yeu duoi cua chung ta.',
'["Tan Uoc","An dien","Suc manh"]', '2 Corinthians 12:9', 'vi', true, NOW(), NOW()),

-- ==================== GALATIANS & EPHESIANS ====================

('q-gal-001', 'Galatians', 2, 20, 20, 'medium', 'multiple_choice_single',
'Phao-lo noi: "Toi da bi dong dinh vao thap tu gia voi Dang Christ, ma toi song, khong phai la toi song nua, nhung ___"',
'["Dang Christ song trong toi", "Toi song cho Chua", "Toi la tao vat moi", "Toi duoc tu do"]',
'[0]',
'Ga-la-ti 2:20 - Doi song Co Doc la de Dang Christ song qua chung ta, khong phai tu luc minh.',
'["Tan Uoc","Doi song moi","Dang Christ"]', 'Galatians 2:20', 'vi', true, NOW(), NOW()),

('q-gal-002', 'Galatians', 5, 22, 23, 'easy', 'multiple_choice_single',
'Trai cua Thanh Linh bat dau bang gi?',
'["Yeu thuong", "Vui mung", "Binh an", "Nhin nhuc"]',
'[0]',
'Ga 5:22 - Trai Thanh Linh: yeu thuong, vui mung, binh an, nhin nhuc, nhan tu, hien lanh, trung tin, mem mai, tiet do.',
'["Tan Uoc","Thanh Linh","Trai Linh"]', 'Galatians 5:22-23', 'vi', true, NOW(), NOW()),

('q-eph-001', 'Ephesians', 2, 8, 9, 'easy', 'multiple_choice_single',
'Theo E-phe-so 2:8-9, chung ta duoc cuu boi dieu gi?',
'["Boi an dien, qua duc tin, khong phai boi viec lam", "Boi viec lanh", "Boi giu luat phap", "Boi bap-tem"]',
'[0]',
'Eph 2:8-9 - Vi nho an dien, boi duc tin, ma anh em duoc cuu. Dieu nay khong phai tu noi anh em, ay la su ban cho cua Duc Chua Troi.',
'["Tan Uoc","Cuu roi","An dien"]', 'Ephesians 2:8-9', 'vi', true, NOW(), NOW()),

('q-eph-002', 'Ephesians', 6, 11, 13, 'medium', 'multiple_choice_single',
'E-phe-so 6 noi ve khi gioi toan than cua Duc Chua Troi. Tai sao chung ta can mac khi gioi nay?',
'["De dung vung chong lai muu ke cua ma quy", "De tan cong ke thu", "De duoc manh me", "De bao ve gia dinh"]',
'[0]',
'Eph 6:11 - Chung ta chien tran khong phai voi loai nguoi ma voi cac the luc thuoc linh o cac mien tren troi.',
'["Tan Uoc","Chien tran thuoc linh","Khi gioi"]', 'Ephesians 6:11-13', 'vi', true, NOW(), NOW()),

-- ==================== PHILIPPIANS & COLOSSIANS ====================

('q-phi-001', 'Philippians', 4, 6, 7, 'easy', 'multiple_choice_single',
'Phi-lip 4:6 day chung ta lam gi thay vi lo lang?',
'["Cau nguyen, nai xin voi su ta on", "Co gang hon nua", "Dung suy nghi ve van de", "Nho nguoi khac giup"]',
'[0]',
'Phi 4:6-7 - Dung lo lang gi het, nhung trong moi su hay dung loi cau nguyen, nai xin va ta on trinh cac su cau xin minh cho Duc Chua Troi.',
'["Tan Uoc","Cau nguyen","Binh an"]', 'Philippians 4:6-7', 'vi', true, NOW(), NOW()),

('q-phi-002', 'Philippians', 4, 13, 13, 'easy', 'fill_in_blank',
'Toi lam duoc moi su nho Dang ban ___ cho toi (Phi-lip 4:13)',
'[]', '[]',
'Phi 4:13 - Toi lam duoc moi su nho Dang ban suc cho toi. Khong phai tu luc ma la nho suc Chua.',
'["Tan Uoc","Suc manh","Tin cay"]', 'Philippians 4:13', 'vi', true, NOW(), NOW()),

-- ==================== HEBREWS ====================

('q-heb-001', 'Hebrews', 11, 1, 1, 'medium', 'multiple_choice_single',
'He-bo-ro 11:1 dinh nghia duc tin la gi?',
'["Su vung tin dieu minh dang trong doi, bang chung dieu minh khong thay", "Tin khong can ly do", "Cam giac tot dep", "Su lac quan"]',
'[0]',
'He 11:1 - Duc tin la su vung tin ve nhung dieu minh trong doi, bang chung ve nhung dieu minh khong thay.',
'["Tan Uoc","Duc tin","Dinh nghia"]', 'Hebrews 11:1', 'vi', true, NOW(), NOW()),

('q-heb-002', 'Hebrews', 11, 6, 6, 'easy', 'multiple_choice_single',
'Theo He-bo-ro 11:6, khong co duc tin thi khong the nao lam gi?',
'["Dap long Duc Chua Troi (dep long Ngai)", "Cau nguyen", "Vao nha tho", "Doc Kinh Thanh"]',
'[0]',
'He 11:6 - Khong co duc tin thi khong the nao dep long Ngai. Ai den gan Chua phai tin rang Ngai hien huu va thuong nhung ke tim kiem Ngai.',
'["Tan Uoc","Duc tin","Dep long Chua"]', 'Hebrews 11:6', 'vi', true, NOW(), NOW()),

('q-heb-003', 'Hebrews', 12, 1, 2, 'medium', 'multiple_choice_single',
'He-bo-ro 12:2 khuyen chung ta chay dua bang cach nhin vao ai?',
'["Chua Gie-su, Dang khoi dau va hoan tat duc tin", "Cac vi anh hung duc tin", "Chinh minh", "Thien su"]',
'[0]',
'He 12:2 - Mat huong ve Duc Chua Gie-su, la cu Dang khoi dau va hoan tat duc tin chung ta.',
'["Tan Uoc","Duc tin","Kien nhan"]', 'Hebrews 12:1-2', 'vi', true, NOW(), NOW()),

-- ==================== JAMES & 1 PETER ====================

('q-jam-001', 'James', 1, 2, 3, 'medium', 'multiple_choice_single',
'Gia-co 1:2 day chung ta phan ung the nao khi gap thu thach?',
'["Hay co su vui mung tron ven", "Hay kien nhan chiu dung", "Hay cau nguyen lien tuc", "Hay tim cach thoat"]',
'[0]',
'Gia-co 1:2-3 - Hay co su vui mung tron ven vi thu thach sinh su nhin nhuc, va nhin nhuc sinh su tron ven.',
'["Tan Uoc","Thu thach","Vui mung"]', 'James 1:2-3', 'vi', true, NOW(), NOW()),

('q-jam-002', 'James', 2, 17, 17, 'easy', 'multiple_choice_single',
'Gia-co 2:17 noi duc tin khong co ___ thi la duc tin chet',
'["Viec lam", "Cau nguyen", "Kien thuc", "Cam xuc"]',
'[0]',
'Gia-co 2:17 - Duc tin that se the hien qua hanh dong. Khong co viec lam, duc tin chi la ly thuyet.',
'["Tan Uoc","Duc tin","Hanh dong"]', 'James 2:17', 'vi', true, NOW(), NOW()),

('q-1pe-001', '1 Peter', 5, 7, 7, 'easy', 'fill_in_blank',
'Hay trao moi ___ minh cho Ngai vi Ngai hay cham soc anh em (1 Phi 5:7)',
'[]', '[]',
'1 Phi 5:7 - Hay trao moi lo lang minh cho Chua vi Ngai cham soc chung ta.',
'["Tan Uoc","Lo lang","Tin cay"]', '1 Peter 5:7', 'vi', true, NOW(), NOW()),

-- ==================== 1 JOHN & REVELATION ====================

('q-1jo-001', '1 John', 4, 8, 8, 'easy', 'multiple_choice_single',
'1 Giang 4:8 dinh nghia Duc Chua Troi la gi?',
'["Duc Chua Troi la su yeu thuong", "Duc Chua Troi la su sang", "Duc Chua Troi la than", "Duc Chua Troi la lua"]',
'[0]',
'1 Giang 4:8 - Duc Chua Troi la su yeu thuong. Ai khong yeu thuong thi khong biet Duc Chua Troi.',
'["Tan Uoc","Ban tinh Chua","Yeu thuong"]', '1 John 4:8', 'vi', true, NOW(), NOW()),

('q-1jo-002', '1 John', 1, 9, 9, 'easy', 'multiple_choice_single',
'Neu chung ta xung nhan toi minh, Chua se lam gi theo 1 Giang 1:9?',
'["Tha toi va lam sach moi su gian ac", "Hinh phat chung ta", "Quay mat di", "Doi chung ta chung minh"]',
'[0]',
'1 Giang 1:9 - Chua thanh tin va cong binh se tha toi va lam sach moi su gian ac. Chi can xung nhan chan that.',
'["Tan Uoc","Tha thu","Xung toi"]', '1 John 1:9', 'vi', true, NOW(), NOW()),

('q-rev-001', 'Revelation', 3, 20, 20, 'easy', 'multiple_choice_single',
'Khai huyen 3:20 noi: "Nay ta dung truoc cua ma go. Neu ai nghe tieng ta ma ___, ta se vao"',
'["Mo cua", "Cau nguyen", "Goi ten ta", "Chay den"]',
'[0]',
'Khai 3:20 - Chua Gie-su dung truoc cua long moi nguoi va go. Ngai khong ep buoc ma cho chung ta tu mo cua.',
'["Tan Uoc","Loi moi","Tu do y chi"]', 'Revelation 3:20', 'vi', true, NOW(), NOW()),

('q-rev-002', 'Revelation', 21, 4, 4, 'easy', 'multiple_choice_single',
'Khai huyen 21:4 mo ta thien dang nhu the nao?',
'["Khong con nuoc mat, su chet, tang che, dau kho", "Duong pho vang", "Thien than ca hat", "Am nhac bat tan"]',
'[0]',
'Khai 21:4 - Chua se lau moi nuoc mat, khong con su chet, tang che, keu la hay dau don nua. Su cu da qua roi.',
'["Tan Uoc","Thien dang","Hy vong"]', 'Revelation 21:4', 'vi', true, NOW(), NOW()),

('q-rev-003', 'Revelation', 22, 20, 20, 'easy', 'fill_in_blank',
'Cau cuoi cung cua Kinh Thanh: "Phai, ta den mau. A-men, lay Chua Gie-su, xin hay ___!"',
'[]', '[]',
'Khai 22:20 - Xin hay den! Day la su khat khao va hy vong lon nhat cua Hoi Thanh: Chua se tro lai.',
'["Tan Uoc","Tai lam","Hy vong"]', 'Revelation 22:20', 'vi', true, NOW(), NOW());
