-- Supplementary: Matthew, Mark, Luke, John, Acts

-- ==================== MATTHEW (need +3) ====================
INSERT IGNORE INTO questions (id, book, chapter, verse_start, verse_end, difficulty, type, content, options, correct_answer, explanation, tags, source, language, is_active, created_at, updated_at) VALUES
('q-mat-013', 'Matthew', 11, 28, 28, 'easy', 'multiple_choice_single',
'Chua Gie-su moi: "Hoi ke met moi va gang nang, hay den cung ta, ta se cho cac nguoi duoc ___"',
'["Nghi ngoi", "Suc manh", "Khon ngoan", "Giau co"]',
'[0]', 'Mat 11:28 - Chua moi tat ca nguoi dang ganh nang den voi Ngai de duoc nghi ngoi that su.', '["Tan Uoc","Loi moi","Nghi ngoi"]', 'Matthew 11:28', 'vi', true, NOW(), NOW()),
('q-mat-014', 'Matthew', 18, 21, 22, 'medium', 'multiple_choice_single',
'Phi-e-ro hoi tha thu bao nhieu lan. Chua Gie-su dap bao nhieu?',
'["70 lan 7 (khong gioi han)", "7 lan", "3 lan", "100 lan"]',
'[0]', 'Mat 18:22 - Tha thu khong co gioi han. 70 lan 7 nghia la luon luon tha thu.', '["Tan Uoc","Tha thu","Mon do"]', 'Matthew 18:21-22', 'vi', true, NOW(), NOW()),
('q-mat-015', 'Matthew', 25, 40, 40, 'medium', 'fill_in_blank',
'He khi cac nguoi lam dieu do cho mot nguoi ___ nhat trong nhung anh em ta, ay la lam cho chinh ta (Mat 25:40)',
'[]', '[]', 'Mat 25:40 - Phuc vu nguoi nho be la phuc vu chinh Chua.', '["Tan Uoc","Phuc vu","Yeu thuong"]', 'Matthew 25:40', 'vi', true, NOW(), NOW()),

-- ==================== MARK (need +12) ====================
('q-mar-004', 'Mark', 1, 15, 15, 'easy', 'multiple_choice_single',
'Su diep dau tien cua Chua Gie-su khi bat dau su vu la gi?',
'["Ky da tron, nuoc Chua da den gan, hay an nan va tin Phuc Am", "Hay giu luat phap", "Hay theo ta", "Hay xay den tho"]',
'[0]', 'Mac 1:15 - Tom tat toan bo su diep cua Chua Gie-su trong mot cau.', '["Tan Uoc","Phuc Am","An nan"]', 'Mark 1:15', 'vi', true, NOW(), NOW()),
('q-mar-005', 'Mark', 4, 39, 39, 'easy', 'multiple_choice_single',
'Chua Gie-su noi gi de bien lang?',
'["Im di, lang di!", "Hay binh an", "Hay yen tinh", "Dung so"]',
'[0]', 'Mac 4:39 - Chua co quyen tren thien nhien. Gio va bien deu vang loi Ngai.', '["Tan Uoc","Phep la","Quyen nang"]', 'Mark 4:39', 'vi', true, NOW(), NOW()),
('q-mar-006', 'Mark', 5, 36, 36, 'easy', 'fill_in_blank',
'Chua noi voi Giai-ru: "Dung so, chi ___!" (Mac 5:36)',
'[]', '[]', 'Mac 5:36 - Chua khuyen tin du tinh huong tuyet vong. Roi Ngai lam con gai Giai-ru song lai.', '["Tan Uoc","Duc tin","Phep la"]', 'Mark 5:36', 'vi', true, NOW(), NOW()),
('q-mar-007', 'Mark', 6, 41, 44, 'easy', 'multiple_choice_single',
'Chua Gie-su cho 5000 nguoi an voi bao nhieu banh va ca?',
'["5 cai banh va 2 con ca", "7 banh va 3 ca", "3 banh va 5 ca", "10 banh"]',
'[0]', 'Mac 6:41 - Tu 5 banh 2 ca, 5000 nguoi an no va con du 12 gio day.', '["Tan Uoc","Phep la","Cung ung"]', 'Mark 6:41-44', 'vi', true, NOW(), NOW()),
('q-mar-008', 'Mark', 8, 34, 34, 'medium', 'multiple_choice_single',
'Chua Gie-su noi dieu kien theo Ngai la gi?',
'["Tu bo minh, vac thap tu gia va theo ta", "Hoc thuc", "Giau co", "Tai nang"]',
'[0]', 'Mac 8:34 - Theo Chua doi hoi tu bo y rieng va san sang chiu kho vi Ngai.', '["Tan Uoc","Mon do","Thap tu"]', 'Mark 8:34', 'vi', true, NOW(), NOW()),
('q-mar-009', 'Mark', 9, 23, 24, 'easy', 'multiple_choice_single',
'Nguoi cha xin Chua chua con bi quy am noi: "Toi tin, xin Chua giup su ___"',
'["It duc tin cua toi", "Yeu duoi cua toi", "So hai cua toi", "Ngu dot cua toi"]',
'[0]', 'Mac 9:24 - Loi cau nguyen that tha nhat: thua nhan duc tin yeu va xin Chua giup.', '["Tan Uoc","Duc tin","That tha"]', 'Mark 9:23-24', 'vi', true, NOW(), NOW()),
('q-mar-010', 'Mark', 10, 14, 15, 'easy', 'multiple_choice_single',
'Chua Gie-su noi phai nhan nuoc Chua nhu ai?',
'["Nhu con tre", "Nhu hoc gia", "Nhu chien binh", "Nhu vua"]',
'[0]', 'Mac 10:15 - Con tre tin don gian, khong nghi ngo. Duc tin can su don so va tin cay.', '["Tan Uoc","Nuoc Chua","Khiem nhuong"]', 'Mark 10:14-15', 'vi', true, NOW(), NOW()),
('q-mar-011', 'Mark', 10, 27, 27, 'easy', 'fill_in_blank',
'Loai nguoi thi khong the duoc nhung ___ thi khong co gi la khong duoc (Mac 10:27)',
'[]', '[]', 'Mac 10:27 - Doi voi Duc Chua Troi moi su deu co the. Khong gi la qua kho cho Chua.', '["Tan Uoc","Quyen nang","Duc tin"]', 'Mark 10:27', 'vi', true, NOW(), NOW()),
('q-mar-012', 'Mark', 11, 24, 24, 'easy', 'multiple_choice_single',
'Mac 11:24: Khi cau nguyen, hay tin rang minh da ___ thi se duoc',
'["Nhan duoc", "Nghe", "Thay", "Hieu"]',
'[0]', 'Cau nguyen voi duc tin la tin rang Chua da nghe va dap loi truoc khi thay ket qua.', '["Tan Uoc","Cau nguyen","Duc tin"]', 'Mark 11:24', 'vi', true, NOW(), NOW()),
('q-mar-013', 'Mark', 14, 36, 36, 'medium', 'multiple_choice_single',
'Tai Get-se-ma-ne, Chua Gie-su cau nguyen: "Ap-ba, Cha oi, xin cat chen nay, nhung khong theo ___"',
'["Y con nhung theo y Cha", "Y the gian", "Y mon do", "Y thay te le"]',
'[0]', 'Mac 14:36 - Chua Gie-su phuc tung y Cha du biet su dau kho phia truoc. Khuon mau cau nguyen.', '["Tan Uoc","Get-se-ma-ne","Vang phuc"]', 'Mark 14:36', 'vi', true, NOW(), NOW()),
('q-mar-014', 'Mark', 15, 34, 34, 'hard', 'multiple_choice_single',
'Chua Gie-su keu tren thap tu: "E-loi, E-loi, la-ma sa-bac-ta-ni?" Day la tieng gi?',
'["A-ram, nghia la: Duc Chua Troi toi, sao Ngai bo toi?", "He-bo-ro", "Hy Lap", "La-tinh"]',
'[0]', 'Mac 15:34 - Trich Thi 22:1. Chua Gie-su ganh toi loi nhan loai va bi Cha quay mat.', '["Tan Uoc","Thap tu","Cuu chuoc"]', 'Mark 15:34', 'vi', true, NOW(), NOW()),
('q-mar-015', 'Mark', 16, 15, 15, 'easy', 'multiple_choice_single',
'Chua Gie-su sai mon do: "Hay di khap ___ giang Phuc Am cho moi loai nguoi"',
'["The gian", "Giu-de", "Gie-ru-sa-lem", "Y-so-ra-en"]',
'[0]', 'Mac 16:15 - Phuc Am khong chi cho nguoi Do-thai ma cho moi nguoi, moi noi, moi dan toc.', '["Tan Uoc","Dai mang lenh","Truyen giao"]', 'Mark 16:15', 'vi', true, NOW(), NOW()),

-- ==================== LUKE (need +8) ====================
('q-luk-008', 'Luke', 4, 18, 19, 'medium', 'multiple_choice_single',
'Chua Gie-su doc E-sai 61 tai Na-xa-ret va tuyen bo Ngai den de lam gi?',
'["Giang Phuc Am cho ke ngheo, chua lanh ke dau kho, phong thich ke bi giam", "Lam vua", "Xay den tho", "Lap quan doi"]',
'[0]', 'Lu-ca 4:18-19 - Chua tuyen bo su vu cua Ngai dung loi E-sai: giai phong va chua lanh toan dien.', '["Tan Uoc","Su vu","Giai phong"]', 'Luke 4:18-19', 'vi', true, NOW(), NOW()),
('q-luk-009', 'Luke', 6, 38, 38, 'easy', 'multiple_choice_single',
'Lu-ca 6:38: "Hay ___ thi se duoc; do day, dam nhan, lat boi trao vao long cac nguoi"',
'["Cho", "Xin", "Tim", "Go"]',
'[0]', 'Nguyen tac rong rai: cho di se nhan lai gap boi. Chua thuong nguoi rong rai.', '["Tan Uoc","Rong rai","Cho di"]', 'Luke 6:38', 'vi', true, NOW(), NOW()),
('q-luk-010', 'Luke', 9, 23, 23, 'easy', 'fill_in_blank',
'Ai muon theo ta thi phai tu bo minh, moi ngay vac ___ minh ma theo ta (Lu-ca 9:23)',
'[]', '[]', 'Vac thap tu gia moi ngay = san sang chiu kho va tu bo y rieng moi ngay.', '["Tan Uoc","Mon do","Thap tu"]', 'Luke 9:23', 'vi', true, NOW(), NOW()),
('q-luk-011', 'Luke', 10, 41, 42, 'easy', 'multiple_choice_single',
'Giua Ma-the boi roi phuc vu va Ma-ri ngoi nghe, Chua khen ai?',
'["Ma-ri, vi chon phan tot nhat", "Ma-the, vi cham chi", "Ca hai", "Khong ai"]',
'[0]', 'Lu-ca 10:42 - Ma-ri chon phan tot nhat: ngoi duoi chan Chua nghe Loi Ngai. Moi quan he hon phuc vu.', '["Tan Uoc","Ma-ri","Uu tien"]', 'Luke 10:41-42', 'vi', true, NOW(), NOW()),
('q-luk-012', 'Luke', 12, 15, 15, 'easy', 'multiple_choice_single',
'Chua Gie-su canh bao: "Hay giu minh ve moi thu ___"',
'["Tham lam, vi su song khong o tai su du dat", "So hai", "Kieu ngao", "Ghen ty"]',
'[0]', 'Lu-ca 12:15 - Su song that khong phu thuoc tai san. Bai hoc trong du ngon nguoi giau kho ngu.', '["Tan Uoc","Tham lam","Gia tri"]', 'Luke 12:15', 'vi', true, NOW(), NOW()),
('q-luk-013', 'Luke', 17, 15, 16, 'easy', 'multiple_choice_single',
'Trong 10 nguoi phung duoc chua lanh, bao nhieu nguoi quay lai cam on?',
'["Chi 1 nguoi (va la nguoi Sa-ma-ri)", "5 nguoi", "Tat ca 10", "Khong ai"]',
'[0]', 'Lu-ca 17:15-16 - Chi 1/10 biet on. Chua Gie-su hoi: 9 nguoi kia dau? Bai hoc ve long biet on.', '["Tan Uoc","Biet on","Phep la"]', 'Luke 17:15-16', 'vi', true, NOW(), NOW()),
('q-luk-014', 'Luke', 18, 13, 14, 'medium', 'multiple_choice_single',
'Trong du ngon nguoi thu thue va Pha-ri-si, ai duoc xung cong binh?',
'["Nguoi thu thue, vi khiem nhuong an nan", "Nguoi Pha-ri-si, vi lam nhieu viec tot", "Ca hai", "Khong ai"]',
'[0]', 'Lu-ca 18:14 - Nguoi thu thue chi biet keu: Chua oi, xin thuong xot ke co toi. Va duoc xung cong binh.', '["Tan Uoc","Khiem nhuong","Cong binh"]', 'Luke 18:13-14', 'vi', true, NOW(), NOW()),
('q-luk-015', 'Luke', 19, 10, 10, 'easy', 'fill_in_blank',
'Con Nguoi da den tim va ___ ke bi mat (Lu-ca 19:10)',
'[]', '[]', 'Lu-ca 19:10 - Tom tat su vu cua Chua Gie-su: tim va cuu ke bi mat (nhu Xa-che).', '["Tan Uoc","Cuu roi","Muc dich"]', 'Luke 19:10', 'vi', true, NOW(), NOW()),

-- ==================== JOHN (need +4) ====================
('q-joh-012', 'John', 4, 13, 14, 'medium', 'multiple_choice_single',
'Chua Gie-su noi voi nguoi dan ba Sa-ma-ri ve nuoc gi?',
'["Nuoc song, uong roi se khong bao gio khat nua", "Nuoc gieng Gia-cop", "Nuoc bien", "Nuoc mua"]',
'[0]', 'Giang 4:14 - Nuoc song = Duc Thanh Linh va su song doi doi. Thoa man noi khat su that.', '["Tan Uoc","Nuoc song","Thanh Linh"]', 'John 4:13-14', 'vi', true, NOW(), NOW()),
('q-joh-013', 'John', 6, 35, 35, 'easy', 'multiple_choice_single',
'Chua Gie-su tuyen bo: "Ta la ___ su song"',
'["Banh", "Nuoc", "Anh sang", "Cua"]',
'[0]', 'Giang 6:35 - Ai den cung ta se khong doi, ai tin ta se khong khat. Chua la nguon nuoi duong thuoc linh.', '["Tan Uoc","Ta la","Banh song"]', 'John 6:35', 'vi', true, NOW(), NOW()),
('q-joh-014', 'John', 10, 10, 10, 'easy', 'fill_in_blank',
'Ke trom den chi de cuop giet va huy diet; con ta den hau cho chien duoc su ___ va du day (Giang 10:10)',
'[]', '[]', 'Giang 10:10 - Chua Gie-su ban su song du day, khong phai chi du song ma song tron ven.', '["Tan Uoc","Su song","Du day"]', 'John 10:10', 'vi', true, NOW(), NOW()),
('q-joh-015', 'John', 10, 11, 11, 'easy', 'multiple_choice_single',
'Chua Gie-su noi: "Ta la Dang chan hien lanh; dang chan hien lanh vi chien ma ___"',
'["Phoi mang song minh", "Chien dau", "Tim co xanh", "Xay chuong"]',
'[0]', 'Giang 10:11 - Dang Chan Tot Lanh hy sinh mang song vi bay chien. Hinh anh dep ve Chua Gie-su.', '["Tan Uoc","Dang Chan","Hy sinh"]', 'John 10:11', 'vi', true, NOW(), NOW()),

-- ==================== ACTS (need +10) ====================
('q-act-006', 'Acts', 2, 42, 42, 'easy', 'multiple_choice_single',
'Hoi thanh dau tien ben do trong 4 dieu gi?',
'["Su day cua su do, su thong cong, le be banh, su cau nguyen", "Chi cau nguyen", "Chi nghe giang", "Chi an uong"]',
'[0]', 'Cong vu 2:42 - Bon cot tru cua Hoi thanh: day do, thong cong, be banh, cau nguyen.', '["Tan Uoc","Hoi thanh","Nen tang"]', 'Acts 2:42', 'vi', true, NOW(), NOW()),
('q-act-007', 'Acts', 3, 6, 6, 'easy', 'multiple_choice_single',
'Phi-e-ro noi voi nguoi que truoc den tho: "Vang bac ta khong co, nhung ta cho nguoi dieu ta co: nhan danh ___ hay dung day va buoc di"',
'["Chua Gie-su Christ", "Duc Chua Troi", "Moi-se", "E-li"]',
'[0]', 'Cong vu 3:6 - Quyen nang chua lanh den tu danh Chua Gie-su, khong phai tien bac.', '["Tan Uoc","Phep la","Danh Chua"]', 'Acts 3:6', 'vi', true, NOW(), NOW()),
('q-act-008', 'Acts', 4, 12, 12, 'easy', 'multiple_choice_single',
'Cong vu 4:12 tuyen bo: "Chang co su cuu roi trong ai khac; vi duoi troi khong co danh nao khac ban cho loai nguoi de chung ta phai nho do ma duoc cuu"',
'["Chua Gie-su la con duong cuu roi duy nhat", "Co nhieu con duong", "Bat ky ai cung cuu", "Khong ai biet"]',
'[0]', 'Su doc nhat cua Chua Gie-su trong su cuu roi. Khong co danh nao khac.', '["Tan Uoc","Cuu roi","Doc nhat"]', 'Acts 4:12', 'vi', true, NOW(), NOW()),
('q-act-009', 'Acts', 4, 31, 31, 'easy', 'fill_in_blank',
'Khi cau nguyen xong, noi ho nhom deu ___, ai nay duoc day dau Duc Thanh Linh (Cong vu 4:31)',
'[]', '[]', 'Cong vu 4:31 - Noi rung dong khi Thanh Linh day dau. Ho giang Loi Chua cach dan di.', '["Tan Uoc","Thanh Linh","Cau nguyen"]', 'Acts 4:31', 'vi', true, NOW(), NOW()),
('q-act-010', 'Acts', 5, 29, 29, 'easy', 'multiple_choice_single',
'Khi bi cam giang dao, cac su do dap: "Phai vang loi ___ hon la vang loi nguoi ta"',
'["Duc Chua Troi", "Luong tam", "Luat phap", "Truyen thong"]',
'[0]', 'Cong vu 5:29 - Khi luat nguoi chong lai luat Chua, phai chon vang loi Chua.', '["Tan Uoc","Can dam","Vang loi"]', 'Acts 5:29', 'vi', true, NOW(), NOW()),
('q-act-011', 'Acts', 7, 59, 60, 'medium', 'multiple_choice_single',
'E-tien, vi tu dao dau tien, cau nguyen dieu gi khi bi nem da?',
'["Lay Chua, xin dung ke toi nay cho ho", "Xin bao thu", "Xin cuu con", "Xin phat ho"]',
'[0]', 'Cong vu 7:60 - Giong Chua Gie-su, E-tien tha thu cho ke giet minh. Tieu chuan tha thu cao nhat.', '["Tan Uoc","E-tien","Tha thu"]', 'Acts 7:59-60', 'vi', true, NOW(), NOW()),
('q-act-012', 'Acts', 8, 30, 31, 'easy', 'multiple_choice_single',
'Phi-lip hoi hoan quan E-thi-o-bi: "Ong co hieu dieu minh doc khong?" Ong dap the nao?',
'["Lam sao hieu duoc neu khong ai giai nghia?", "Toi hieu roi", "Khong can giup", "Toi dang hoc"]',
'[0]', 'Cong vu 8:31 - Can nguoi giai thich Kinh Thanh. Vai tro quan trong cua nguoi day do.', '["Tan Uoc","Phuc Am","Giai nghia"]', 'Acts 8:30-31', 'vi', true, NOW(), NOW()),
('q-act-013', 'Acts', 13, 22, 22, 'medium', 'fill_in_blank',
'Chua goi Da-vit la nguoi vua ___ ta (Cong vu 13:22)',
'[]', '[]', 'Cong vu 13:22 - Phao-lo trich loi nay. Da-vit khong hoan hao nhung tam long luon huong ve Chua.', '["Tan Uoc","Da-vit","Tam long"]', 'Acts 13:22', 'vi', true, NOW(), NOW()),
('q-act-014', 'Acts', 17, 11, 11, 'easy', 'multiple_choice_single',
'Dan Be-re duoc khen vi lam gi khi nghe Phao-lo giang?',
'["Hang ngay xem xet Kinh Thanh de kiem tra dieu Phao-lo noi co dung khong", "Tin ngay", "Tu choi", "Im lang"]',
'[0]', 'Cong vu 17:11 - Mau muc: nghe giang roi kiem tra lai voi Kinh Thanh. Khong tin mu quang.', '["Tan Uoc","Be-re","Kinh Thanh"]', 'Acts 17:11', 'vi', true, NOW(), NOW()),
('q-act-015', 'Acts', 20, 35, 35, 'easy', 'multiple_choice_single',
'Phao-lo trich loi Chua Gie-su: "Ban cho co phuc hon ___"',
'["Nhan", "Xin", "Giu", "Doi"]',
'[0]', 'Cong vu 20:35 - Loi cua Chua Gie-su khong co trong Phuc Am nhung duoc Phao-lo truyen lai.', '["Tan Uoc","Rong rai","Phuc"]', 'Acts 20:35', 'vi', true, NOW(), NOW());
