-- Supplementary: Joshua, Judges, Ruth, 1-2 Samuel, 1-2 Kings, Nehemiah, Esther

-- ==================== JOSHUA (need +12) ====================
INSERT IGNORE INTO questions (id, book, chapter, verse_start, verse_end, difficulty, type, content, options, correct_answer, explanation, tags, source, language, is_active, created_at, updated_at) VALUES
('q-jos-004', 'Joshua', 1, 3, 3, 'easy', 'multiple_choice_single',
'Chua hua cho Gio-sue moi noi ban chan ong dat len se thuoc ve ai?',
'["Dan Y-so-ra-en", "Rieng Gio-sue", "Chi phai Giu-da", "Chi cac chien binh"]',
'[0]', 'Gio-sue 1:3 - Moi noi ban chan cac nguoi dat len, ta ban cho cac nguoi. Nhung van phai buoc di de nhan lay.', '["Cuu Uoc","Dat Hua","Loi hua"]', 'Joshua 1:3', 'vi', true, NOW(), NOW()),
('q-jos-005', 'Joshua', 2, 1, 6, 'easy', 'multiple_choice_single',
'Ai da giup giau hai tham tu Y-so-ra-en tai Gie-ri-co?',
'["Ra-hab, nguoi ky nu", "Mot thuong gia", "Vien quan thanh", "Mot thay te le"]',
'[0]', 'Gio-sue 2:4 - Ra-hab giau 2 tham tu tren mai nha. Ba tin Chua va duoc cuu khi thanh bi ha (He 11:31).', '["Cuu Uoc","Ra-hab","Duc tin"]', 'Joshua 2:1-6', 'vi', true, NOW(), NOW()),
('q-jos-006', 'Joshua', 2, 18, 21, 'medium', 'multiple_choice_single',
'Ra-hab phai treo gi noi cua so de duoc cuu khi Gie-ri-co bi tan cong?',
'["Day chi dieu (do)", "Co trang", "Cot khoi", "Den dau"]',
'[0]', 'Gio-sue 2:18 - Day chi dieu nhu huyet chien con Le Vuot Qua. Hinh bong ve su cuu roi boi huyet.', '["Cuu Uoc","Ra-hab","Hinh bong"]', 'Joshua 2:18-21', 'vi', true, NOW(), NOW()),
('q-jos-007', 'Joshua', 3, 14, 17, 'easy', 'multiple_choice_single',
'Khi thay te le khieng Hom Giao Uoc buoc xuong, dong song nao re ra?',
'["Song Gio-dan", "Song Ni-lo", "Bien Do", "Song O-phat"]',
'[0]', 'Gio-sue 3:15-17 - Song Gio-dan re ra khi chan thay te le cham nuoc, giong nhu Bien Do.', '["Cuu Uoc","Phep la","Gio-dan"]', 'Joshua 3:14-17', 'vi', true, NOW(), NOW()),
('q-jos-008', 'Joshua', 4, 6, 7, 'easy', 'multiple_choice_single',
'12 hon da tu song Gio-dan duoc dung len de lam gi?',
'["Lam dau ky niem de con chau nho phep la Chua", "Lam ban tho", "Xay tuong thanh", "Lam vu khi"]',
'[0]', 'Gio-sue 4:7 - Moi khi con chau hoi, cha me se ke lai phep la Chua re song Gio-dan.', '["Cuu Uoc","Ky niem","Truyen thong"]', 'Joshua 4:6-7', 'vi', true, NOW(), NOW()),
('q-jos-009', 'Joshua', 5, 13, 15, 'medium', 'multiple_choice_single',
'Truoc tran Gie-ri-co, Gio-sue gap ai cam guom?',
'["Tuong cua doi quan Duc Gie-ho-va", "Thien su Gab-ri-en", "Tien tri Moi-se", "Mot chien binh"]',
'[0]', 'Gio-sue 5:14 - Tuong quan doi Chua xuat hien, Gio-sue sup xuong tho. Co the la su hien ra cua Chua Gie-su truoc nhap the.', '["Cuu Uoc","Thien su","Chien tran"]', 'Joshua 5:13-15', 'vi', true, NOW(), NOW()),
('q-jos-010', 'Joshua', 7, 20, 21, 'medium', 'multiple_choice_single',
'Tai sao Y-so-ra-en thua tran tai A-hi? Vi toi cua ai?',
'["A-can, vi lay vat bi cam tu Gie-ri-co", "Gio-sue, vi sai chien thuat", "Dan su, vi so hai", "Thay te le, vi khong cau nguyen"]',
'[0]', 'Gio-sue 7:20-21 - A-can giau ao choang, bac va vang. Toi loi mot nguoi anh huong ca cong dong.', '["Cuu Uoc","Toi loi","Hau qua"]', 'Joshua 7:20-21', 'vi', true, NOW(), NOW()),
('q-jos-011', 'Joshua', 10, 12, 13, 'easy', 'multiple_choice_single',
'Phep la nao xay ra khi Gio-sue chien dau voi lien minh 5 vua?',
'["Mat troi va mat trang dung lai", "Lua tu troi", "Dong dat", "Bao to"]',
'[0]', 'Gio-sue 10:13 - Mat troi dung giua troi ca ngay de Y-so-ra-en hoan tat chien thang.', '["Cuu Uoc","Phep la","Chien tran"]', 'Joshua 10:12-13', 'vi', true, NOW(), NOW()),
('q-jos-012', 'Joshua', 14, 10, 12, 'easy', 'multiple_choice_single',
'Ca-lep xin phan dat nao lam san nghiep du da 85 tuoi?',
'["Vung doi nui co nguoi khong lo A-na-kim", "Dong bang mau mo", "Bo bien", "Gie-ru-sa-lem"]',
'[0]', 'Gio-sue 14:12 - Ca-lep xin noi kho nhat vi tin Chua. Du 85 tuoi van manh me va san sang chien dau.', '["Cuu Uoc","Ca-lep","Duc tin"]', 'Joshua 14:10-12', 'vi', true, NOW(), NOW()),
('q-jos-013', 'Joshua', 21, 45, 45, 'easy', 'fill_in_blank',
'Gio-sue 21:45: "Trong cac loi lanh ma Duc Gie-ho-va da phan cung nha Y-so-ra-en, khong co loi nao la ___"',
'[]', '[]', 'Khong co loi nao la vo hieu. Tat ca deu ung nghiem. Chua giu moi loi hua.', '["Cuu Uoc","Loi hua","Thanh tin"]', 'Joshua 21:45', 'vi', true, NOW(), NOW()),
('q-jos-014', 'Joshua', 23, 14, 14, 'medium', 'multiple_choice_single',
'Loi cuoi cua Gio-sue nhan manh dieu gi?',
'["Chua thanh tin giu moi loi hua, hay trung tin voi Ngai", "Hay chien dau tiep", "Hay xay nhieu thanh", "Hay tang quan doi"]',
'[0]', 'Gio-sue 23:14 - Gio-sue lam chung rang khong loi nao cua Chua that bai. Khuyen dan trung tin.', '["Cuu Uoc","Gio-sue","Thanh tin"]', 'Joshua 23:14', 'vi', true, NOW(), NOW()),
('q-jos-015', 'Joshua', 24, 23, 24, 'medium', 'fill_in_blank',
'Dan su dap loi Gio-sue: "Chung toi se phuc vu Duc Gie-ho-va va ___ tieng Ngai"',
'[]', '[]', 'Gio-sue 24:24 - Dan su cam ket phuc vu va vang loi. Gio-sue dat giao uoc tai Si-chem.', '["Cuu Uoc","Giao uoc","Vang loi"]', 'Joshua 24:23-24', 'vi', true, NOW(), NOW()),

-- ==================== JUDGES (need +14) ====================
('q-jdg-002', 'Judges', 2, 16, 18, 'easy', 'multiple_choice_single',
'Trong sach Cac Quan Xet, Chua dung len nhung nguoi gi de giai cuu dan?',
'["Cac quan xet (giai cuu)", "Cac vua", "Cac tien tri", "Cac thay te le"]',
'[0]', 'Cac Quan Xet 2:16 - Chua dung len cac quan xet de giai cuu dan khoi ke ap buc. Chu ky: toi loi > ap buc > keu cau > giai cuu.', '["Cuu Uoc","Quan xet","Chu ky"]', 'Judges 2:16-18', 'vi', true, NOW(), NOW()),
('q-jdg-003', 'Judges', 2, 11, 15, 'medium', 'multiple_choice_single',
'Chu ky lap di lap lai trong sach Cac Quan Xet la gi?',
'["Toi loi > Hinh phat > Keu cau > Giai cuu > Binh an > Toi loi lai", "Chien tranh > Hoa binh", "Xay dung > Huy diet", "Giau co > Ngheo kho"]',
'[0]', 'Cac Quan Xet 2:11-19 - Chu ky nay lap lai nhieu lan, cho thay ban chat con nguoi va su nhan nai cua Chua.', '["Cuu Uoc","Chu ky","Ban chat nguoi"]', 'Judges 2:11-15', 'vi', true, NOW(), NOW()),
('q-jdg-004', 'Judges', 4, 4, 5, 'easy', 'multiple_choice_single',
'Nu quan xet duy nhat trong Kinh Thanh la ai?',
'["De-bo-ra", "Ra-hab", "Ru-to", "E-xo-te"]',
'[0]', 'Cac Quan Xet 4:4 - De-bo-ra vua la nu tien tri vua la quan xet xet xu dan Y-so-ra-en.', '["Cuu Uoc","De-bo-ra","Lanh dao"]', 'Judges 4:4-5', 'vi', true, NOW(), NOW()),
('q-jdg-005', 'Judges', 4, 21, 21, 'medium', 'multiple_choice_single',
'Ai da ha tuong Si-se-ra bang cai coc leu?',
'["Gia-en", "De-bo-ra", "Ba-rac", "Mi-ri-am"]',
'[0]', 'Cac Quan Xet 4:21 - Gia-en dong coc leu qua mang tang Si-se-ra khi ong ngu. Chien thang den tu noi bat ngo.', '["Cuu Uoc","Gia-en","Chien thang"]', 'Judges 4:21', 'vi', true, NOW(), NOW()),
('q-jdg-006', 'Judges', 6, 12, 15, 'easy', 'multiple_choice_single',
'Khi thien su goi Ghe-de-on la "nguoi dung cam", ong dang lam gi?',
'["Dap lua mi trong bon ep nho vi so quan Ma-dian", "Chien dau", "Cau nguyen", "Ngu"]',
'[0]', 'Cac Quan Xet 6:11-12 - Ghe-de-on dang so hai tron tranh nhung Chua thay tiem nang trong ong.', '["Cuu Uoc","Ghe-de-on","Su keu goi"]', 'Judges 6:12-15', 'vi', true, NOW(), NOW()),
('q-jdg-007', 'Judges', 6, 36, 40, 'easy', 'multiple_choice_single',
'Ghe-de-on dung gi de thu Chua?',
'["Bong long cuu (suong va kho)", "Lua va nuoc", "Da va gay", "Trai va rau"]',
'[0]', 'Cac Quan Xet 6:37-40 - Ghe-de-on thu Chua 2 lan bang bong long cuu. Chua nhan nai voi su yeu duoi cua ong.', '["Cuu Uoc","Ghe-de-on","Duc tin"]', 'Judges 6:36-40', 'vi', true, NOW(), NOW()),
('q-jdg-008', 'Judges', 7, 7, 7, 'medium', 'multiple_choice_single',
'Chua giam quan doi Ghe-de-on tu 32,000 xuong con bao nhieu?',
'["300 nguoi", "1000 nguoi", "3000 nguoi", "100 nguoi"]',
'[0]', 'Cac Quan Xet 7:7 - Chi 300 nguoi de Chua duoc vinh hien. Chien thang khong nho so dong ma nho quyen nang Chua.', '["Cuu Uoc","Ghe-de-on","Quyen nang Chua"]', 'Judges 7:7', 'vi', true, NOW(), NOW()),
('q-jdg-009', 'Judges', 7, 20, 20, 'easy', 'fill_in_blank',
'300 nguoi cua Ghe-de-on su dung vu khi gi? Ken, binh va ___',
'[]', '[]', 'Cac Quan Xet 7:20 - Ken, binh va duoc (duoi la lua). Vu khi khong thuong thuc nhung chien thang boi Chua.', '["Cuu Uoc","Ghe-de-on","Chien thang"]', 'Judges 7:20', 'vi', true, NOW(), NOW()),
('q-jdg-010', 'Judges', 11, 30, 35, 'hard', 'multiple_choice_single',
'Giep-the da hua dieu gi voi Chua truoc tran chien?',
'["Dang lam cua le thieu vat dau tien buoc ra cua don ong", "Xay den tho", "Nhip an 40 ngay", "Cho tat ca chien loi pham"]',
'[0]', 'Cac Quan Xet 11:30-31 - Loi hua hap tap cua Giep-the dan den hau qua dau long khi chinh con gai ong buoc ra.', '["Cuu Uoc","Giep-the","Loi hua"]', 'Judges 11:30-35', 'vi', true, NOW(), NOW()),
('q-jdg-011', 'Judges', 13, 5, 5, 'easy', 'multiple_choice_single',
'Sam-son duoc biet rieng lam gi tu khi con trong bung me?',
'["Nguoi Na-xi-re cho Duc Chua Troi", "Vua", "Thay te le", "Tien tri"]',
'[0]', 'Cac Quan Xet 13:5 - Sam-son la nguoi Na-xi-re tu trong bung me, duoc biet rieng de giai cuu Y-so-ra-en.', '["Cuu Uoc","Sam-son","Na-xi-re"]', 'Judges 13:5', 'vi', true, NOW(), NOW()),
('q-jdg-012', 'Judges', 14, 5, 6, 'easy', 'multiple_choice_single',
'Sam-son da xe con gi bang tay khong boi Than Chua cam dong?',
'["Su tu", "Gau", "Soi", "Bo rung"]',
'[0]', 'Cac Quan Xet 14:6 - Than cua Chua cam dong Sam-son va ong xe con su tu nhu xe de con.', '["Cuu Uoc","Sam-son","Suc manh"]', 'Judges 14:5-6', 'vi', true, NOW(), NOW()),
('q-jdg-013', 'Judges', 15, 15, 16, 'easy', 'multiple_choice_single',
'Sam-son dung vu khi gi danh ha 1000 nguoi Phi-li-tin?',
'["Xuong ham lua", "Guom", "Trang nom", "Giao"]',
'[0]', 'Cac Quan Xet 15:15 - Sam-son dung xuong ham lua tuoi danh chet 1000 nguoi.', '["Cuu Uoc","Sam-son","Chien dau"]', 'Judges 15:15-16', 'vi', true, NOW(), NOW()),
('q-jdg-014', 'Judges', 16, 28, 30, 'medium', 'multiple_choice_single',
'Sam-son chet nhu the nao?',
'["Xo sap den cua nguoi Phi-li-tin, chet chung voi ke thu", "Bi giet trong giac ngu", "Bi nem tu cao", "Benh tat"]',
'[0]', 'Cac Quan Xet 16:30 - Sam-son cau nguyen lan cuoi, duoc suc va xo hai cot den. Chet nhieu hon khi song.', '["Cuu Uoc","Sam-son","Hy sinh"]', 'Judges 16:28-30', 'vi', true, NOW(), NOW()),
('q-jdg-015', 'Judges', 21, 25, 25, 'medium', 'fill_in_blank',
'Cau cuoi sach Cac Quan Xet: "Trong thoi do Y-so-ra-en khong co vua; moi nguoi lam theo y ___"',
'[]', '[]', 'Cac Quan Xet 21:25 - Khi khong co lanh dao tin kinh, moi nguoi tu lam theo y minh. Hau qua la hon loan.', '["Cuu Uoc","Quan xet","Vo luat"]', 'Judges 21:25', 'vi', true, NOW(), NOW()),

-- ==================== RUTH (need +13) ====================
('q-rut-003', 'Ruth', 1, 1, 2, 'easy', 'multiple_choice_single',
'Gia dinh Na-o-mi roi Bet-le-hem di xu Mo-ap vi ly do gi?',
'["Nan doi", "Chien tranh", "Tim viec", "Duoc moi"]',
'[0]', 'Ru-to 1:1 - Nan doi tai Bet-le-hem (nghia la "nha banh") khien gia dinh E-li-me-lec di xu Mo-ap.', '["Cuu Uoc","Ru-to","Nan doi"]', 'Ruth 1:1-2', 'vi', true, NOW(), NOW()),
('q-rut-004', 'Ruth', 1, 4, 5, 'easy', 'multiple_choice_single',
'Hai con dau nguoi Mo-ap cua Na-o-mi ten la gi?',
'["Ru-to va Op-ba", "Ru-to va Ra-hab", "Op-ba va Mi-ri-am", "Ru-to va De-bo-ra"]',
'[0]', 'Ru-to 1:4 - Hai con trai Na-o-mi cuoi Ru-to va Op-ba tai Mo-ap.', '["Cuu Uoc","Ru-to","Nhan vat"]', 'Ruth 1:4-5', 'vi', true, NOW(), NOW()),
('q-rut-005', 'Ruth', 1, 14, 16, 'medium', 'multiple_choice_single',
'Op-ba va Ru-to phan ung khac nhau the nao khi Na-o-mi bao ve?',
'["Op-ba tro ve Mo-ap, Ru-to o lai theo Na-o-mi", "Ca hai o lai", "Ca hai tro ve", "Ru-to tro ve, Op-ba o lai"]',
'[0]', 'Ru-to 1:14-16 - Op-ba chon an toan, Ru-to chon trung tin. Hai su lua chon dan den hai cuoc doi khac nhau.', '["Cuu Uoc","Ru-to","Trung tin"]', 'Ruth 1:14-16', 'vi', true, NOW(), NOW()),
('q-rut-006', 'Ruth', 1, 20, 21, 'easy', 'multiple_choice_single',
'Na-o-mi doi ten thanh Ma-ra. Ma-ra co nghia la gi?',
'["Cay dang", "Vui ve", "Binh an", "Hy vong"]',
'[0]', 'Ru-to 1:20 - Na-o-mi (diu ngot) doi thanh Ma-ra (cay dang) vi mat chong va hai con trai.', '["Cuu Uoc","Na-o-mi","Kho nan"]', 'Ruth 1:20-21', 'vi', true, NOW(), NOW()),
('q-rut-007', 'Ruth', 2, 2, 3, 'easy', 'multiple_choice_single',
'Ru-to lam gi de nuoi Na-o-mi?',
'["Muot lua (nhat lua rot) tren dong ruong", "Ban hang", "Lam banh", "Chan chien"]',
'[0]', 'Ru-to 2:2 - Ru-to muot lua theo luat phap cho phep nguoi ngheo nhat lua sot tren dong (Le-vi 19:9).', '["Cuu Uoc","Ru-to","Cham chi"]', 'Ruth 2:2-3', 'vi', true, NOW(), NOW()),
('q-rut-008', 'Ruth', 2, 4, 4, 'easy', 'fill_in_blank',
'Bo-o chao tho gat: "Nguyen Duc Gie-ho-va o cung cac ___"',
'[]', '[]', 'Ru-to 2:4 - Loi chao cho thay moi truong lam viec tin kinh cua Bo-o.', '["Cuu Uoc","Bo-o","Phuc lanh"]', 'Ruth 2:4', 'vi', true, NOW(), NOW()),
('q-rut-009', 'Ruth', 2, 11, 12, 'medium', 'multiple_choice_single',
'Bo-o khen Ru-to vi dieu gi?',
'["Bo xu so di theo me chong den xu la, nau nau duoi canh Chua", "Sac dep", "Su khon ngoan", "Su giau co"]',
'[0]', 'Ru-to 2:11-12 - Bo-o nhan ra duc tin va long trung thanh cua Ru-to. Chua thuong nhung ke den nau nau duoi canh Ngai.', '["Cuu Uoc","Bo-o","Duc tin"]', 'Ruth 2:11-12', 'vi', true, NOW(), NOW()),
('q-rut-010', 'Ruth', 3, 9, 9, 'medium', 'multiple_choice_single',
'Ru-to xin Bo-o lam gi tai san lua?',
'["Lam nguoi chuoc san nghiep (go-el) cho ba", "Cuoi ba", "Cho ba an", "Bao ve ba"]',
'[0]', 'Ru-to 3:9 - Hay dat vai ao nguoi tren toi to, vi nguoi la nguoi co quyen chuoc lai (go-el). Hinh bong ve Chua chuoc chung ta.', '["Cuu Uoc","Go-el","Cuu chuoc"]', 'Ruth 3:9', 'vi', true, NOW(), NOW()),
('q-rut-011', 'Ruth', 3, 12, 13, 'hard', 'multiple_choice_single',
'Khai niem "go-el" (nguoi chuoc) trong sach Ru-to la hinh bong cua ai?',
'["Chua Gie-su - Dang Chuoc Toi cua chung ta", "Moi-se", "Da-vit", "Ap-ra-ham"]',
'[0]', 'Bo-o lam go-el: chuoc dat, cuoi Ru-to, bao toan dong doi. Chua Gie-su lam go-el: chuoc toi, cuoi Hoi Thanh, ban su song.', '["Cuu Uoc","Hinh bong","Cuu chuoc"]', 'Ruth 3:12-13', 'vi', true, NOW(), NOW()),
('q-rut-012', 'Ruth', 4, 1, 6, 'medium', 'multiple_choice_single',
'Tai sao nguoi ba con gan hon Bo-o tu choi quyen chuoc?',
'["So lam hu san nghiep cua minh", "Khong co tien", "Khong thich Ru-to", "Dang benh"]',
'[0]', 'Ru-to 4:6 - Nguoi go-el gan hon tu choi vi so thiet hai cho san nghiep. Bo-o san long hy sinh.', '["Cuu Uoc","Bo-o","Hy sinh"]', 'Ruth 4:1-6', 'vi', true, NOW(), NOW()),
('q-rut-013', 'Ruth', 4, 9, 10, 'easy', 'multiple_choice_single',
'Bo-o cuoi Ru-to va mua lai san nghiep cua ai?',
'["E-li-me-lec, chong Na-o-mi", "Na-o-mi", "Op-ba", "Mot nguoi la"]',
'[0]', 'Ru-to 4:9-10 - Bo-o chuoc toan bo san nghiep va cuoi Ru-to de bao toan danh cua nguoi chet.', '["Cuu Uoc","Bo-o","Cuu chuoc"]', 'Ruth 4:9-10', 'vi', true, NOW(), NOW()),
('q-rut-014', 'Ruth', 4, 14, 15, 'easy', 'fill_in_blank',
'Phu nu noi voi Na-o-mi rang Ru-to con hon ___ con trai (Ru-to 4:15)',
'[]', '[]', 'Ru-to 4:15 - Ru-to yeu me chong, con hon bay con trai. Tinh yeu va trung tin duoc ton vinh.', '["Cuu Uoc","Ru-to","Tinh yeu"]', 'Ruth 4:14-15', 'vi', true, NOW(), NOW()),
('q-rut-015', 'Ruth', 4, 17, 17, 'easy', 'multiple_choice_single',
'Con trai cua Bo-o va Ru-to ten la gi?',
'["O-bet", "Gie-se", "Da-vit", "Sa-lo-mon"]',
'[0]', 'Ru-to 4:17 - O-bet la cha Gie-se, ong noi Da-vit. Ru-to la ba co cua dong doi vua va cua Chua Gie-su.', '["Cuu Uoc","Gia pha","O-bet"]', 'Ruth 4:17', 'vi', true, NOW(), NOW()),

-- ==================== 1 SAMUEL (need +11) ====================
('q-1sa-005', '1 Samuel', 1, 10, 11, 'easy', 'multiple_choice_single',
'An-ne cau xin Chua dieu gi tai den tam?',
'["Mot dua con trai va hua dang no cho Chua", "Su giau co", "Suc khoe", "Chien thang"]',
'[0]', '1 Sa 1:11 - An-ne cau nguyen trong nuoc mat va hua dang con cho Chua. Chua nham loi ba.', '["Cuu Uoc","An-ne","Cau nguyen"]', '1 Samuel 1:10-11', 'vi', true, NOW(), NOW()),
('q-1sa-006', '1 Samuel', 2, 12, 17, 'medium', 'multiple_choice_single',
'Hai con trai He-li la Hop-ni va Phi-ne-a lam dieu gi sai?',
'["An trom cua le va song vo dao duc", "Tho tuong", "Bo tron", "Chong lai vua"]',
'[0]', '1 Sa 2:12-17 - Ho khong biet Chua, cuop cua le va song vo dao duc. Hau qua: ca hai chet cung ngay.', '["Cuu Uoc","Hinh phat","Te le"]', '1 Samuel 2:12-17', 'vi', true, NOW(), NOW()),
('q-1sa-007', '1 Samuel', 4, 21, 22, 'medium', 'fill_in_blank',
'Khi Hom Giao Uoc bi cuop, con dau He-li dat ten con la Y-ca-bot nghia la: "Su ___ da roi Y-so-ra-en"',
'[]', '[]', '1 Sa 4:21 - Y-ca-bot = su vinh hien da roi khoi. Hom Giao Uoc bi nguoi Phi-li-tin bat.', '["Cuu Uoc","Hom Giao Uoc","Vinh hien"]', '1 Samuel 4:21-22', 'vi', true, NOW(), NOW()),
('q-1sa-008', '1 Samuel', 8, 5, 7, 'medium', 'multiple_choice_single',
'Dan Y-so-ra-en xin Sa-mu-en dieu gi khien Chua buon?',
'["Xin mot vua nhu cac dan toc khac", "Xin nhieu cua cai", "Xin chien thang", "Xin mot tien tri moi"]',
'[0]', '1 Sa 8:7 - Chua noi: Ho khong tu choi con dau, nhung tu choi ta lam vua ho. Dan chon nguoi thay vi Chua.', '["Cuu Uoc","Vuong quyen","Tu choi"]', '1 Samuel 8:5-7', 'vi', true, NOW(), NOW()),
('q-1sa-009', '1 Samuel', 9, 2, 2, 'easy', 'multiple_choice_single',
'Sau-lo, vua dau tien cua Y-so-ra-en, duoc mo ta nhu the nao?',
'["Cao hon moi nguoi tu vai tro len, dep trai", "Khon ngoan nhat", "Manh me nhat", "Giau nhat"]',
'[0]', '1 Sa 9:2 - Sau-lo co hinh thuc ben ngoai an tuong nhung tam long khong vung.', '["Cuu Uoc","Sau-lo","Hinh thuc"]', '1 Samuel 9:2', 'vi', true, NOW(), NOW()),
('q-1sa-010', '1 Samuel', 13, 14, 14, 'medium', 'multiple_choice_single',
'Sa-mu-en noi Chua tim mot nguoi nhu the nao de thay Sau-lo?',
'["Mot nguoi vua long Chua", "Nguoi manh nhat", "Nguoi khon ngoan nhat", "Nguoi tu phu hoang gia"]',
'[0]', '1 Sa 13:14 - Chua tim nguoi vua long Ngai. Da-vit duoc goi la nguoi vua long Chua (Cong vu 13:22).', '["Cuu Uoc","Da-vit","Tam long"]', '1 Samuel 13:14', 'vi', true, NOW(), NOW()),
('q-1sa-011', '1 Samuel', 15, 22, 22, 'easy', 'multiple_choice_single',
'Sa-mu-en noi: "Su vang loi tot hon ___, su nghe theo tot hon mo cua chien duc"',
'["Cua te le", "Vang bac", "Chien thang", "Tri thuc"]',
'[0]', '1 Sa 15:22 - Chua muon su vang loi tu tam long hon la hinh thuc ton giao ben ngoai.', '["Cuu Uoc","Vang loi","Te le"]', '1 Samuel 15:22', 'vi', true, NOW(), NOW()),
('q-1sa-012', '1 Samuel', 18, 1, 3, 'easy', 'multiple_choice_single',
'Tinh ban noi tieng nhat Kinh Thanh la giua ai?',
'["Da-vit va Gio-na-than", "Moi-se va A-ron", "Da-vit va Sa-mu-en", "Ap-ra-ham va Lot"]',
'[0]', '1 Sa 18:1 - Gio-na-than yeu Da-vit nhu chinh minh. Tinh ban trung tin bat chap hoan canh.', '["Cuu Uoc","Tinh ban","Trung tin"]', '1 Samuel 18:1-3', 'vi', true, NOW(), NOW()),
('q-1sa-013', '1 Samuel', 24, 4, 7, 'hard', 'multiple_choice_single',
'Khi co co hoi giet Sau-lo trong hang, Da-vit lam gi?',
'["Chi cat vai ao Sau-lo va ray an han vi da lam dieu do", "Giet Sau-lo", "Bo tron", "Bat Sau-lo"]',
'[0]', '1 Sa 24:5-7 - Da-vit ton trong Sau-lo la nguoi duoc Chua xuc dau, du Sau-lo muon giet ong. Bai hoc ve ton trong quyen binh.', '["Cuu Uoc","Da-vit","Ton trong"]', '1 Samuel 24:4-7', 'vi', true, NOW(), NOW()),
('q-1sa-014', '1 Samuel', 17, 34, 37, 'easy', 'fill_in_blank',
'Da-vit noi voi Sau-lo rang ong da giet con ___ va con gau khi chan chien',
'[]', '[]', '1 Sa 17:36 - Da-vit da giet su tu va gau. Kinh nghiem truoc do chuan bi cho tran Go-li-at.', '["Cuu Uoc","Da-vit","Chuan bi"]', '1 Samuel 17:34-37', 'vi', true, NOW(), NOW()),
('q-1sa-015', '1 Samuel', 26, 9, 11, 'medium', 'multiple_choice_single',
'Lan thu hai co co hoi giet Sau-lo, Da-vit lay gi thay vi giet?',
'["Giao va binh nuoc cua Sau-lo", "Ao choang", "Vuong mien", "Guom"]',
'[0]', '1 Sa 26:11-12 - Da-vit tiep tuc ton trong mang song cua Sau-lo, chi lay giao va binh nuoc lam bang chung.', '["Cuu Uoc","Da-vit","Nhan nai"]', '1 Samuel 26:9-12', 'vi', true, NOW(), NOW()),

-- ==================== 2 SAMUEL (need +14) ====================
('q-2sa-002', '2 Samuel', 5, 4, 5, 'easy', 'multiple_choice_single',
'Da-vit lam vua tong cong bao nhieu nam?',
'["40 nam (7 nam tai Hep-ron, 33 nam tai Gie-ru-sa-lem)", "30 nam", "20 nam", "50 nam"]',
'[0]', '2 Sa 5:4-5 - Da-vit len ngoi luc 30 tuoi va cai tri 40 nam.', '["Cuu Uoc","Da-vit","Tri vi"]', '2 Samuel 5:4-5', 'vi', true, NOW(), NOW()),
('q-2sa-003', '2 Samuel', 6, 14, 15, 'easy', 'multiple_choice_single',
'Da-vit lam gi khi Hom Giao Uoc duoc ruoc ve Gie-ru-sa-lem?',
'["Nhay mua het suc truoc mat Chua", "Ngoi tren ngai", "Dang cua le im lang", "Doc luat phap"]',
'[0]', '2 Sa 6:14 - Da-vit nhay mua het suc truoc mat Chua, khong quan tam hinh anh vua. Tho phuong het long.', '["Cuu Uoc","Da-vit","Tho phuong"]', '2 Samuel 6:14-15', 'vi', true, NOW(), NOW()),
('q-2sa-004', '2 Samuel', 7, 12, 13, 'hard', 'multiple_choice_single',
'Giao uoc Da-vit (2 Sa 7) hua dieu quan trong nao?',
'["Ngoi vua cua dong doi Da-vit se con doi doi", "Da-vit se song mai", "Den tho khong bao gio bi pha", "Y-so-ra-en luon thang tran"]',
'[0]', '2 Sa 7:12-13 - Ngoi vua doi doi cua dong doi Da-vit ung nghiem noi Chua Gie-su (Lu-ca 1:32-33).', '["Cuu Uoc","Giao uoc","Cuu The"]', '2 Samuel 7:12-13', 'vi', true, NOW(), NOW()),
('q-2sa-005', '2 Samuel', 9, 1, 7, 'easy', 'multiple_choice_single',
'Da-vit to long nhan tu voi ai vi loi cua Gio-na-than?',
'["Me-phi-bo-set, con Gio-na-than", "Sau-lo", "Ap-ne", "Si-me-i"]',
'[0]', '2 Sa 9:7 - Me-phi-bo-set bi que ca hai chan nhung duoc Da-vit moi an dong ban vua suot doi.', '["Cuu Uoc","Da-vit","An dien"]', '2 Samuel 9:1-7', 'vi', true, NOW(), NOW()),
('q-2sa-006', '2 Samuel', 11, 2, 4, 'easy', 'multiple_choice_single',
'Toi lon cua Da-vit voi Bat-se-ba bat dau khi nao?',
'["Khi Da-vit o lai Gie-ru-sa-lem thay vi ra tran", "Khi di tham dat", "Khi ngu trua", "Khi an tiec"]',
'[0]', '2 Sa 11:1-2 - Vao mua cac vua ra tran, Da-vit o nha. Su nhan roi dan den cam do va toi loi.', '["Cuu Uoc","Da-vit","Cam do"]', '2 Samuel 11:2-4', 'vi', true, NOW(), NOW()),
('q-2sa-007', '2 Samuel', 11, 14, 17, 'medium', 'multiple_choice_single',
'Da-vit lam gi de che giau toi voi Bat-se-ba?',
'["Sap dat cho chong ba la U-ri chet tran", "Tron khoi Gie-ru-sa-lem", "Doi lo cho U-ri", "Gui U-ri di xa"]',
'[0]', '2 Sa 11:15 - Da-vit viet thu cho Jo-ap bo U-ri vao cho nguy hiem nhat. Toi pham toi dan den toi gian tiep giet nguoi.', '["Cuu Uoc","Da-vit","Toi loi"]', '2 Samuel 11:14-17', 'vi', true, NOW(), NOW()),
('q-2sa-008', '2 Samuel', 12, 13, 13, 'easy', 'fill_in_blank',
'Khi Na-than doi dien, Da-vit noi: "Toi da ___ cung Duc Gie-ho-va"',
'[]', '[]', '2 Sa 12:13 - Da-vit thu nhan toi ngay lap tuc, khong bien ho. Thi thien 51 la loi an nan cua ong.', '["Cuu Uoc","Da-vit","An nan"]', '2 Samuel 12:13', 'vi', true, NOW(), NOW()),
('q-2sa-009', '2 Samuel', 12, 23, 23, 'medium', 'multiple_choice_single',
'Khi con trai chet, Da-vit noi dieu gi ve hy vong?',
'["Toi se di den no, nhung no se khong tro lai voi toi", "Chua se cho con khac", "Toi se khong buon nua", "Toi se quen di"]',
'[0]', '2 Sa 12:23 - Da-vit tin rang se gap con minh o the gioi ben kia. Hy vong ve su song sau khi chet.', '["Cuu Uoc","Da-vit","Hy vong"]', '2 Samuel 12:23', 'vi', true, NOW(), NOW()),
('q-2sa-010', '2 Samuel', 15, 13, 14, 'easy', 'multiple_choice_single',
'Con trai nao cua Da-vit noi loan va tu xung lam vua?',
'["Ap-sa-lom", "Am-non", "Sa-lo-mon", "A-do-ni-gia"]',
'[0]', '2 Sa 15:13-14 - Ap-sa-lom noi loan, Da-vit phai tron khoi Gie-ru-sa-lem. Hau qua cua toi loi gia dinh.', '["Cuu Uoc","Ap-sa-lom","Noi loan"]', '2 Samuel 15:13-14', 'vi', true, NOW(), NOW()),
('q-2sa-011', '2 Samuel', 18, 33, 33, 'easy', 'multiple_choice_single',
'Khi Ap-sa-lom chet, Da-vit phan ung the nao?',
'["Khoc va uoc minh chet thay con", "Vui mung vi het noi loan", "Im lang", "Gian du"]',
'[0]', '2 Sa 18:33 - Du Ap-sa-lom noi loan, Da-vit van la nguoi cha dau kho. Oi Ap-sa-lom, con toi oi!', '["Cuu Uoc","Da-vit","Tinh cha"]', '2 Samuel 18:33', 'vi', true, NOW(), NOW()),
('q-2sa-012', '2 Samuel', 22, 2, 3, 'easy', 'fill_in_blank',
'Da-vit hat: "Duc Gie-ho-va la hon ___ toi, la don luy toi, la Dang giai cuu toi"',
'[]', '[]', '2 Sa 22:2 - Bai ca ta on cua Da-vit dung nhieu hinh anh ve su bao ve cua Chua.', '["Cuu Uoc","Da-vit","Ngoi khen"]', '2 Samuel 22:2-3', 'vi', true, NOW(), NOW()),
('q-2sa-013', '2 Samuel', 23, 1, 5, 'medium', 'multiple_choice_single',
'Loi cuoi cung cua Da-vit nhan manh giao uoc voi Chua la gi?',
'["Giao uoc doi doi, khong thay doi", "Tam thoi", "Co dieu kien", "Chi cho Sa-lo-mon"]',
'[0]', '2 Sa 23:5 - Da-vit xac nhan giao uoc doi doi ma Chua lap voi nha ong.', '["Cuu Uoc","Da-vit","Giao uoc"]', '2 Samuel 23:1-5', 'vi', true, NOW(), NOW()),
('q-2sa-014', '2 Samuel', 24, 24, 24, 'medium', 'multiple_choice_single',
'Da-vit noi dieu gi khi mua san lua de lap ban tho?',
'["Toi khong dang cho Chua cua le ma khong ton phi gi", "Toi tra gia tot nhat", "Chua dang duoc tat ca", "Toi cho tat ca"]',
'[0]', '2 Sa 24:24 - Cua le that doi hoi su hy sinh. Khong dang cho Chua dieu khong ton phi gi.', '["Cuu Uoc","Da-vit","Cua le"]', '2 Samuel 24:24', 'vi', true, NOW(), NOW()),
('q-2sa-015', '2 Samuel', 7, 18, 22, 'medium', 'fill_in_blank',
'Da-vit cau nguyen: "Chua Gie-ho-va oi, toi la ai va nha toi la gi ma Ngai da dem toi den buc ___?"',
'[]', '[]', '2 Sa 7:18 - Da-vit khiem nhuong truoc su nhan tu cua Chua. Tu ke chan chien tro thanh vua.', '["Cuu Uoc","Da-vit","Khiem nhuong"]', '2 Samuel 7:18-22', 'vi', true, NOW(), NOW()),

-- ==================== 1 KINGS (need +13) ====================
('q-1ki-003', '1 Kings', 6, 1, 2, 'easy', 'multiple_choice_single',
'Sa-lo-mon xay den tho mat bao lau?',
'["7 nam", "3 nam", "40 nam", "12 nam"]',
'[0]', '1 Cac Vua 6:38 - Den tho duoc xay trong 7 nam. Mot cong trinh hung vi.', '["Cuu Uoc","Sa-lo-mon","Den tho"]', '1 Kings 6:1-2', 'vi', true, NOW(), NOW()),
('q-1ki-004', '1 Kings', 8, 27, 27, 'hard', 'multiple_choice_single',
'Khi khanh thanh den tho, Sa-lo-mon tuyen bo dieu gi ve Chua?',
'["Troi cua cac tang troi khong chua noi Ngai, huong chi den nay", "Den nay la nha cua Chua", "Chua chi o trong den", "Chua vui ve nhan den"]',
'[0]', '1 Cac Vua 8:27 - Sa-lo-mon hieu rang Chua khong bi gioi han trong den tho. Ngai lon hon moi cong trinh.', '["Cuu Uoc","Den tho","Than hoc"]', '1 Kings 8:27', 'vi', true, NOW(), NOW()),
('q-1ki-005', '1 Kings', 10, 1, 9, 'easy', 'multiple_choice_single',
'Nu hoang xu nao den tham va thu su khon ngoan cua Sa-lo-mon?',
'["Nu hoang xu Se-ba", "Nu hoang Ai-cap", "Nu hoang Ba-by-lon", "Nu hoang Ba-tu"]',
'[0]', '1 Cac Vua 10:1 - Nu hoang Se-ba den voi cau hoi kho. Ba kinh ngac truoc su khon ngoan va su giau co cua Sa-lo-mon.', '["Cuu Uoc","Sa-lo-mon","Khon ngoan"]', '1 Kings 10:1-9', 'vi', true, NOW(), NOW()),
('q-1ki-006', '1 Kings', 11, 4, 4, 'medium', 'multiple_choice_single',
'Tai sao Sa-lo-mon sa nga cuoi doi?',
'["Cac vo ngoai bang xoay long ong theo cac than khac", "Mat tri nho", "Bi benh", "Bi phan boi"]',
'[0]', '1 Cac Vua 11:4 - Sa-lo-mon co 700 vo va 300 hau, ho lam long ong nghieng theo than ngoai bang.', '["Cuu Uoc","Sa-lo-mon","Sa nga"]', '1 Kings 11:4', 'vi', true, NOW(), NOW()),
('q-1ki-007', '1 Kings', 12, 16, 19, 'medium', 'multiple_choice_single',
'Vuong quoc bi chia cat vi loi cua ai?',
'["Ro-bo-am, vi tu choi giam ganh nang cho dan", "Gie-ro-bo-am", "Sa-lo-mon", "A-hi-gia"]',
'[0]', '1 Cac Vua 12:16 - Ro-bo-am nghe loi ban tre, tang ganh nang. 10 chi phai ly khai, chi con Giu-da va Ben-gia-min.', '["Cuu Uoc","Chia cat","Ro-bo-am"]', '1 Kings 12:16-19', 'vi', true, NOW(), NOW()),
('q-1ki-008', '1 Kings', 17, 4, 6, 'easy', 'multiple_choice_single',
'Chua dung gi de nuoi E-li ben suoi Ke-rit?',
'["Qua va chim dem dem dem banh va thit den", "Ma-na tu troi", "Trai cay rung", "Nguoi dan dia phuong"]',
'[0]', '1 Cac Vua 17:6 - Qua dem banh va thit cho E-li sang va chieu. Chua lo lieu cach la lung.', '["Cuu Uoc","E-li","Chua lo lieu"]', '1 Kings 17:4-6', 'vi', true, NOW(), NOW()),
('q-1ki-009', '1 Kings', 17, 14, 16, 'easy', 'multiple_choice_single',
'Phep la nao xay ra voi ba goa Sa-rep-ta?',
'["Hu bot va ve dau khong het suot mua doi", "Nuoc bien thanh ruou", "Con trai song lai", "Nha duoc xay moi"]',
'[0]', '1 Cac Vua 17:16 - Hu bot khong voi, ve dau khong can. Chua lo lieu khi chung ta vang loi.', '["Cuu Uoc","E-li","Phep la"]', '1 Kings 17:14-16', 'vi', true, NOW(), NOW()),
('q-1ki-010', '1 Kings', 17, 22, 22, 'medium', 'fill_in_blank',
'E-li cau nguyen va con trai ba goa duoc Chua lam cho ___ lai',
'[]', '[]', '1 Cac Vua 17:22 - Chua nghe loi E-li va linh hon dua tre tro lai. Phep la phuc sinh dau tien trong Kinh Thanh.', '["Cuu Uoc","E-li","Phuc sinh"]', '1 Kings 17:22', 'vi', true, NOW(), NOW()),
('q-1ki-011', '1 Kings', 19, 4, 4, 'easy', 'multiple_choice_single',
'Sau chien thang tren nui Cat-men, E-li phan ung the nao khi Gie-sa-ben de doa?',
'["So hai va bo chay vao dong vang, muon chet", "Vui mung", "Chien dau tiep", "Cau nguyen them"]',
'[0]', '1 Cac Vua 19:4 - Ngay ca tien tri vi dai nhat cung co luc yeu duoi. Chua nhan tu cham soc E-li.', '["Cuu Uoc","E-li","Yeu duoi"]', '1 Kings 19:4', 'vi', true, NOW(), NOW()),
('q-1ki-012', '1 Kings', 19, 11, 12, 'medium', 'multiple_choice_single',
'Chua hien ra voi E-li tai nui Ho-rep bang gi?',
'["Tieng nho nhe (tieng pham pham)", "Gio bao", "Dong dat", "Lua"]',
'[0]', '1 Cac Vua 19:12 - Chua khong o trong gio bao, dong dat hay lua, ma trong tieng nho nhe. Chua noi trong su yen tinh.', '["Cuu Uoc","E-li","Tieng Chua"]', '1 Kings 19:11-12', 'vi', true, NOW(), NOW()),
('q-1ki-013', '1 Kings', 19, 18, 18, 'easy', 'multiple_choice_single',
'Chua noi con lai bao nhieu nguoi chua tung quy goi truoc Ba-an?',
'["7000 nguoi", "100 nguoi", "1000 nguoi", "Chi E-li"]',
'[0]', '1 Cac Vua 19:18 - 7000 nguoi chua quy goi Ba-an. E-li khong co don nhu ong tuong.', '["Cuu Uoc","E-li","Dan so con lai"]', '1 Kings 19:18', 'vi', true, NOW(), NOW()),
('q-1ki-014', '1 Kings', 19, 19, 21, 'easy', 'multiple_choice_single',
'E-li goi E-li-se lam mon do bang cach nao?',
'["Nem ao choang minh len E-li-se", "Goi ten ong", "Gui thu", "Sai nguoi den"]',
'[0]', '1 Cac Vua 19:19 - Ao choang tien tri la bieu tuong truyen chuc vu va quyen nang.', '["Cuu Uoc","E-li-se","Mon do"]', '1 Kings 19:19-21', 'vi', true, NOW(), NOW()),
('q-1ki-015', '1 Kings', 21, 17, 19, 'medium', 'fill_in_blank',
'E-li doi dien vua A-hab vi toi cuop vuon nho cua ___',
'[]', '[]', '1 Cac Vua 21:17-19 - Na-bot bi giet oan de A-hab cuop vuon nho. Chua sai E-li tuyen bo hinh phat.', '["Cuu Uoc","A-hab","Cong binh"]', '1 Kings 21:17-19', 'vi', true, NOW(), NOW()),

-- ==================== 2 KINGS (need +14) ====================
('q-2ki-002', '2 Kings', 2, 9, 9, 'easy', 'multiple_choice_single',
'E-li-se xin dieu gi truoc khi E-li duoc cat di?',
'["Hai phan than cua E-li", "Su giau co", "Quyen luc", "Song lau"]',
'[0]', '2 Cac Vua 2:9 - Hai phan than (phan truong tu) cho thay E-li-se muon tiep noi su vu cach tron ven.', '["Cuu Uoc","E-li-se","Than Linh"]', '2 Kings 2:9', 'vi', true, NOW(), NOW()),
('q-2ki-003', '2 Kings', 4, 1, 7, 'easy', 'multiple_choice_single',
'E-li-se giup ba goa co no bang phep la gi?',
'["Dau o-liu tu binh chay khong het vao cac binh khac", "Vang tu troi", "Con giai no", "Ban tho gui tien"]',
'[0]', '2 Cac Vua 4:6 - Dau chay day moi binh ba muon duoc. Chua nhan len dieu it oi de du dung.', '["Cuu Uoc","E-li-se","Phep la"]', '2 Kings 4:1-7', 'vi', true, NOW(), NOW()),
('q-2ki-004', '2 Kings', 4, 32, 35, 'medium', 'multiple_choice_single',
'E-li-se lam gi de con trai nguoi phu nu Su-nem song lai?',
'["Nam ap len dua tre va cau nguyen", "Rao luat phap", "Dang cua le", "Goi tien tri khac"]',
'[0]', '2 Cac Vua 4:34 - E-li-se nam ap len, mieng ke mieng, mat ke mat. Dua tre hat xi 7 lan va song lai.', '["Cuu Uoc","E-li-se","Phuc sinh"]', '2 Kings 4:32-35', 'vi', true, NOW(), NOW()),
('q-2ki-005', '2 Kings', 5, 1, 14, 'easy', 'multiple_choice_single',
'Tuong Na-a-man duoc chua benh phung bang cach nao?',
'["Tam 7 lan duoi song Gio-dan", "Uong thuoc", "Dang cua le", "Cau nguyen"]',
'[0]', '2 Cac Vua 5:14 - Na-a-man tam 7 lan theo loi E-li-se. Du ban dau gian du vi nghi cach nay qua don gian.', '["Cuu Uoc","Na-a-man","Vang loi"]', '2 Kings 5:1-14', 'vi', true, NOW(), NOW()),
('q-2ki-006', '2 Kings', 5, 15, 16, 'easy', 'fill_in_blank',
'Sau khi duoc chua lanh, Na-a-man tuyen bo: "Khong co Duc Chua Troi nao khac trong khap dat ngoai ___"',
'[]', '[]', '2 Cac Vua 5:15 - Nguoi ngoai bang nhan biet Chua cua Y-so-ra-en la Chua duy nhat.', '["Cuu Uoc","Na-a-man","Duc tin"]', '2 Kings 5:15-16', 'vi', true, NOW(), NOW()),
('q-2ki-007', '2 Kings', 6, 16, 17, 'easy', 'multiple_choice_single',
'E-li-se noi voi day to: "Dung so, vi nhung ke o voi chung ta dong hon..." Khi mat mo ra thay gi?',
'["Nui day xe lua va ngua lua bao quanh", "Doi quan lon", "Thien su", "Dam may sang"]',
'[0]', '2 Cac Vua 6:17 - The gioi thuoc linh co quan doi Chua bao ve. Dieu mat thuong khong thay.', '["Cuu Uoc","E-li-se","Bao ve"]', '2 Kings 6:16-17', 'vi', true, NOW(), NOW()),
('q-2ki-008', '2 Kings', 17, 6, 6, 'medium', 'multiple_choice_single',
'Vuong quoc phia Bac (Y-so-ra-en) bi de quoc nao tieu diet nam 722 TCN?',
'["A-si-ri", "Ba-by-lon", "Ai-cap", "Ba-tu"]',
'[0]', '2 Cac Vua 17:6 - A-si-ri bat Y-so-ra-en lam phu tu. 10 chi phai bi phan tan khong bao gio phuc hoi.', '["Cuu Uoc","Lich su","Luu day"]', '2 Kings 17:6', 'vi', true, NOW(), NOW()),
('q-2ki-009', '2 Kings', 22, 8, 11, 'medium', 'multiple_choice_single',
'Vua Gio-si-a tim thay gi trong den tho da duoc quyen lang?',
'["Sach luat phap (Torah)", "Hom Giao Uoc", "Vang bac", "Ao thay te le"]',
'[0]', '2 Cac Vua 22:8 - Tim lai sach luat phap dan den cuoc cai cach lon nhat trong lich su Giu-da.', '["Cuu Uoc","Gio-si-a","Cai cach"]', '2 Kings 22:8-11', 'vi', true, NOW(), NOW()),
('q-2ki-010', '2 Kings', 23, 25, 25, 'easy', 'multiple_choice_single',
'Vua nao duoc khen la yeu Chua het long, het linh hon, het suc hon bat ky vua nao?',
'["Gio-si-a", "Da-vit", "Sa-lo-mon", "E-xe-chia"]',
'[0]', '2 Cac Vua 23:25 - Truoc va sau Gio-si-a, khong co vua nao quay lai Chua het long nhu ong.', '["Cuu Uoc","Gio-si-a","Het long"]', '2 Kings 23:25', 'vi', true, NOW(), NOW()),
('q-2ki-011', '2 Kings', 20, 1, 6, 'easy', 'multiple_choice_single',
'Chua them bao nhieu nam cho vua E-xe-chia sau khi ong cau nguyen?',
'["15 nam", "7 nam", "10 nam", "40 nam"]',
'[0]', '2 Cac Vua 20:6 - Chua nghe loi cau nguyen cua E-xe-chia va them 15 nam cho doi ong.', '["Cuu Uoc","E-xe-chia","Cau nguyen"]', '2 Kings 20:1-6', 'vi', true, NOW(), NOW()),
('q-2ki-012', '2 Kings', 25, 8, 11, 'easy', 'multiple_choice_single',
'Vuong quoc Giu-da bi de quoc nao tieu diet va den tho bi pha nam 586 TCN?',
'["Ba-by-lon (Ne-bu-cat-net-sa)", "A-si-ri", "Ai-cap", "Ba-tu"]',
'[0]', '2 Cac Vua 25:8-9 - Ne-bu-cat-net-sa dot den tho, pha tuong thanh va bat dan luu day Ba-by-lon.', '["Cuu Uoc","Lich su","Luu day"]', '2 Kings 25:8-11', 'vi', true, NOW(), NOW()),
('q-2ki-013', '2 Kings', 2, 23, 24, 'medium', 'fill_in_blank',
'Khi tre nho nhao bong E-li-se, hai con ___ tu rung ra ve 42 dua',
'[]', '[]', '2 Cac Vua 2:24 - Hai con gau cai tu rung ra. Bai hoc ve ton trong nguoi cua Chua.', '["Cuu Uoc","E-li-se","Ton trong"]', '2 Kings 2:23-24', 'vi', true, NOW(), NOW()),
('q-2ki-014', '2 Kings', 4, 42, 44, 'easy', 'multiple_choice_single',
'E-li-se cho bao nhieu nguoi an voi 20 o banh lua mach?',
'["100 nguoi va con du", "50 nguoi", "200 nguoi", "1000 nguoi"]',
'[0]', '2 Cac Vua 4:44 - 100 nguoi an va con du. Tien bao phep la Chua Gie-su cho 5000 nguoi an.', '["Cuu Uoc","E-li-se","Phep la"]', '2 Kings 4:42-44', 'vi', true, NOW(), NOW()),
('q-2ki-015', '2 Kings', 13, 21, 21, 'hard', 'multiple_choice_single',
'Dieu gi xay ra khi mot xac chet cham xuong cua E-li-se trong mo?',
'["Nguoi chet song lai", "Mo sang len", "Dat rung", "Am thanh lon"]',
'[0]', '2 Cac Vua 13:21 - Ngay ca sau khi chet, xuong E-li-se van co quyen nang phuc sinh. Cho thay quyen nang Chua.', '["Cuu Uoc","E-li-se","Phuc sinh"]', '2 Kings 13:21', 'vi', true, NOW(), NOW()),

-- ==================== NEHEMIAH (need +14) ====================
('q-neh-002', 'Nehemiah', 1, 3, 4, 'easy', 'multiple_choice_single',
'Khi nghe tin tuong thanh Gie-ru-sa-lem do nat, Ne-he-mi lam gi?',
'["Khoc, kieng an va cau nguyen nhieu ngay", "Lap tuc len duong", "Gian du", "Bo mac"]',
'[0]', 'Ne-he-mi 1:4 - Ne-he-mi dau buon va cau nguyen truoc khi hanh dong. Cau nguyen truoc roi lam sau.', '["Cuu Uoc","Ne-he-mi","Cau nguyen"]', 'Nehemiah 1:3-4', 'vi', true, NOW(), NOW()),
('q-neh-003', 'Nehemiah', 1, 11, 11, 'easy', 'multiple_choice_single',
'Ne-he-mi giu chuc vu gi cho vua Ba-tu?',
'["Quan dang ruou (nguoi rot ruou)", "Tuong quan", "Co van", "Thu ky"]',
'[0]', 'Ne-he-mi 1:11 - Chuc quan dang ruou rat duoc tin cay vi phai bao dam ruou khong bi dau doc.', '["Cuu Uoc","Ne-he-mi","Chuc vu"]', 'Nehemiah 1:11', 'vi', true, NOW(), NOW()),
('q-neh-004', 'Nehemiah', 2, 4, 5, 'medium', 'multiple_choice_single',
'Truoc khi xin phep vua Ac-ta-xe-xe, Ne-he-mi lam gi?',
'["Tham cau nguyen voi Chua", "Chuan bi bai dien van", "Hoi y co van", "Viet thu"]',
'[0]', 'Ne-he-mi 2:4 - Ne-he-mi cau nguyen "tham" ngay luc dang noi chuyen voi vua. Cau nguyen bat cu luc nao.', '["Cuu Uoc","Ne-he-mi","Cau nguyen"]', 'Nehemiah 2:4-5', 'vi', true, NOW(), NOW()),
('q-neh-005', 'Nehemiah', 4, 9, 9, 'easy', 'multiple_choice_single',
'Khi bi ke thu de doa, Ne-he-mi lam gi?',
'["Cau nguyen va dat nguoi canh gac", "Chi cau nguyen", "Chi dat linh canh", "Ngung xay"]',
'[0]', 'Ne-he-mi 4:9 - Vua cau nguyen vua hanh dong thuc te. Tin cay Chua nhung van lam phan minh.', '["Cuu Uoc","Ne-he-mi","Duc tin"]', 'Nehemiah 4:9', 'vi', true, NOW(), NOW()),
('q-neh-006', 'Nehemiah', 4, 17, 17, 'easy', 'fill_in_blank',
'Nhung nguoi xay tuong, mot tay lam viec, mot tay cam ___',
'[]', '[]', 'Ne-he-mi 4:17 - Vua xay vua san sang chien dau. Tinh than canh giac va lam viec.', '["Cuu Uoc","Ne-he-mi","Canh giac"]', 'Nehemiah 4:17', 'vi', true, NOW(), NOW()),
('q-neh-007', 'Nehemiah', 6, 3, 3, 'medium', 'multiple_choice_single',
'Khi ke thu moi Ne-he-mi xuong de ngung xay, ong tra loi the nao?',
'["Toi dang lam viec lon, khong the xuong duoc", "Toi se den ngay", "De toi suy nghi", "Gui nguoi thay"]',
'[0]', 'Ne-he-mi 6:3 - Ne-he-mi tu choi bi phan tam boi ke thu. Tap trung vao su menh Chua giao.', '["Cuu Uoc","Ne-he-mi","Tap trung"]', 'Nehemiah 6:3', 'vi', true, NOW(), NOW()),
('q-neh-008', 'Nehemiah', 6, 15, 16, 'easy', 'multiple_choice_single',
'Tuong thanh Gie-ru-sa-lem duoc xay lai trong bao lau?',
'["52 ngay", "6 thang", "1 nam", "7 nam"]',
'[0]', 'Ne-he-mi 6:15 - 52 ngay! Ke thu nhan ra day la viec cua Chua vi khong ai lam nhanh vay tu suc minh.', '["Cuu Uoc","Ne-he-mi","Phep la"]', 'Nehemiah 6:15-16', 'vi', true, NOW(), NOW()),
('q-neh-009', 'Nehemiah', 8, 10, 10, 'easy', 'multiple_choice_single',
'Ne-he-mi noi: "Su vui ve cua Duc Gie-ho-va la ___"',
'["Suc luc cua cac nguoi", "Phuc lanh cua cac nguoi", "Hy vong cua cac nguoi", "Muc dich cua cac nguoi"]',
'[0]', 'Ne-he-mi 8:10 - Su vui ve tu Chua ban cho suc manh de doi dien moi hoan canh.', '["Cuu Uoc","Ne-he-mi","Vui ve"]', 'Nehemiah 8:10', 'vi', true, NOW(), NOW()),
('q-neh-010', 'Nehemiah', 8, 1, 3, 'medium', 'multiple_choice_single',
'Ai doc sach luat phap cho dan su nghe tu sang den trua?',
'["E-xo-ra, thay thong giao", "Ne-he-mi", "Cac thay te le", "Dan su tu doc"]',
'[0]', 'Ne-he-mi 8:1-3 - E-xo-ra doc Torah va cac nguoi Le-vi giai nghia. Dan su dung nghe tu sang den trua.', '["Cuu Uoc","E-xo-ra","Loi Chua"]', 'Nehemiah 8:1-3', 'vi', true, NOW(), NOW()),
('q-neh-011', 'Nehemiah', 9, 17, 17, 'easy', 'fill_in_blank',
'Ne-he-mi 9:17: "Ngai la Duc Chua Troi san sang tha thu, hay lam on, hay thuong xot, cham ___"',
'[]', '[]', 'Ne-he-mi 9:17 - Chua cham gian, day on thuong. Du dan su noi loan, Chua van nhan tu.', '["Cuu Uoc","Tinh Chua","Tha thu"]', 'Nehemiah 9:17', 'vi', true, NOW(), NOW()),
('q-neh-012', 'Nehemiah', 5, 7, 11, 'medium', 'multiple_choice_single',
'Ne-he-mi trach cac quan truong vi dieu gi?',
'["Cho vay lay loi bat cong voi dan ngheo", "Khong xay tuong", "Tho tuong", "Khong cau nguyen"]',
'[0]', 'Ne-he-mi 5:7 - Ne-he-mi bao ve dan ngheo khoi bi boc lot boi chinh nguoi cung dan toc.', '["Cuu Uoc","Ne-he-mi","Cong binh"]', 'Nehemiah 5:7-11', 'vi', true, NOW(), NOW()),
('q-neh-013', 'Nehemiah', 13, 15, 18, 'easy', 'multiple_choice_single',
'Ne-he-mi cam dieu gi vao ngay Sa-bat?',
'["Buon ban va van chuyen hang hoa", "Nau an", "Di bo", "Noi chuyen"]',
'[0]', 'Ne-he-mi 13:15-19 - Ne-he-mi dong cong thanh truoc ngay Sa-bat de ngan thuong gia buon ban.', '["Cuu Uoc","Ne-he-mi","Sa-bat"]', 'Nehemiah 13:15-18', 'vi', true, NOW(), NOW()),
('q-neh-014', 'Nehemiah', 2, 11, 16, 'easy', 'multiple_choice_single',
'Ne-he-mi lam gi ban dem truoc khi tuyen bo ke hoach xay tuong?',
'["Bi mat di xem xet tinh trang tuong thanh", "Cau nguyen", "Hop voi quan truong", "Ngu nghi"]',
'[0]', 'Ne-he-mi 2:13 - Ne-he-mi bi mat khao sat tuong thanh ban dem de nam ro tinh hinh truoc khi hanh dong.', '["Cuu Uoc","Ne-he-mi","Chuan bi"]', 'Nehemiah 2:11-16', 'vi', true, NOW(), NOW()),
('q-neh-015', 'Nehemiah', 12, 43, 43, 'easy', 'multiple_choice_single',
'Khi tuong thanh hoan tat, dan su lam gi?',
'["Dang te le va vui mung, tieng vui nghe xa", "Im lang ta on", "An chay", "Khoc vi cam dong"]',
'[0]', 'Ne-he-mi 12:43 - Ngay hom do ho dang cua te le lon va vui mung vi Chua cho ho vui. Tieng nghe tu xa.', '["Cuu Uoc","Ne-he-mi","Vui mung"]', 'Nehemiah 12:43', 'vi', true, NOW(), NOW()),

-- ==================== ESTHER (need +14) ====================
('q-est-002', 'Esther', 1, 10, 12, 'easy', 'multiple_choice_single',
'Tai sao hoang hau Vat-ti bi phe truoc?',
'["Tu choi den khi vua goi trong tiec ruou", "Phan boi vua", "Benh tat", "Muon lam nu hoang khac"]',
'[0]', 'E-xo-te 1:12 - Hoang hau Vat-ti tu choi den truoc vua. Dieu nay mo duong cho E-xo-te tro thanh hoang hau.', '["Cuu Uoc","E-xo-te","Chu quyen"]', 'Esther 1:10-12', 'vi', true, NOW(), NOW()),
('q-est-003', 'Esther', 2, 7, 7, 'easy', 'multiple_choice_single',
'E-xo-te la nguoi dan toc nao?',
'["Do-thai (goc phai Ben-gia-min)", "Ba-tu", "Ai-cap", "Ba-by-lon"]',
'[0]', 'E-xo-te 2:5-7 - Ten Do-thai la Ha-da-sa. E-xo-te (Esther) la ten Ba-tu. Mo coi duoc Mot-do-che nuoi.', '["Cuu Uoc","E-xo-te","Than the"]', 'Esther 2:7', 'vi', true, NOW(), NOW()),
('q-est-004', 'Esther', 2, 17, 17, 'easy', 'multiple_choice_single',
'E-xo-te duoc chon lam hoang hau thay cho ai?',
'["Vat-ti", "Se-re", "Mi-ri-am", "Khong ai"]',
'[0]', 'E-xo-te 2:17 - Vua yeu E-xo-te hon tat ca va dat vuong mien tren dau ba.', '["Cuu Uoc","E-xo-te","Hoang hau"]', 'Esther 2:17', 'vi', true, NOW(), NOW()),
('q-est-005', 'Esther', 3, 1, 6, 'easy', 'multiple_choice_single',
'Ha-man muon tieu diet dan Do-thai vi ly do gi?',
'["Vi Mot-do-che tu choi quy lay ha", "Vi dan Do-thai khong dong thue", "Vi ho tho than khac", "Vi ho manh hon"]',
'[0]', 'E-xo-te 3:5-6 - Mot-do-che tu choi quy lay Ha-man. Su kieu ngao cua Ha-man khien han muon giet ca dan toc.', '["Cuu Uoc","Ha-man","Kieu ngao"]', 'Esther 3:1-6', 'vi', true, NOW(), NOW()),
('q-est-006', 'Esther', 3, 7, 7, 'medium', 'multiple_choice_single',
'Ha-man boc tham (Pu-rim) de chon ngay nao tieu diet dan Do-thai?',
'["Ngay 13 thang 12 (A-da)", "Ngay 1 thang 1", "Ngay 14 thang 1", "Ngay 10 thang 7"]',
'[0]', 'E-xo-te 3:7,13 - Tu "Pu-rim" (boc tham) tro thanh ten le hoi ky niem su giai cuu.', '["Cuu Uoc","Pu-rim","Le hoi"]', 'Esther 3:7', 'vi', true, NOW(), NOW()),
('q-est-007', 'Esther', 4, 3, 3, 'easy', 'fill_in_blank',
'Khi nghe chieu chi diet Do-thai, dan su khoc loc, ___ an va nam tren bao',
'[]', '[]', 'E-xo-te 4:3 - Su tang thuong lon trong moi tinh. Dan su kieng an va cau nguyen.', '["Cuu Uoc","E-xo-te","Kieng an"]', 'Esther 4:3', 'vi', true, NOW(), NOW()),
('q-est-008', 'Esther', 4, 16, 16, 'medium', 'multiple_choice_single',
'E-xo-te xin dan su lam gi truoc khi ba vao gap vua khong duoc moi?',
'["Kieng an 3 ngay 3 dem", "Cau nguyen 7 ngay", "Dang cua le", "Chay tron"]',
'[0]', 'E-xo-te 4:16 - E-xo-te san sang chet: "Neu phai chet thi toi chet." Can dam tu duc tin.', '["Cuu Uoc","E-xo-te","Can dam"]', 'Esther 4:16', 'vi', true, NOW(), NOW()),
('q-est-009', 'Esther', 5, 2, 3, 'easy', 'multiple_choice_single',
'Khi E-xo-te vao gap vua khong duoc moi, vua lam gi?',
'["Dua cay truong vang ra cho ba cham vao (chap nhan)", "Gian du", "Duoi ba ra", "Pho mac"]',
'[0]', 'E-xo-te 5:2 - Vua dua truong vang = chap nhan va ban an tu. Chua bao ve E-xo-te.', '["Cuu Uoc","E-xo-te","Bao ve"]', 'Esther 5:2-3', 'vi', true, NOW(), NOW()),
('q-est-010', 'Esther', 6, 1, 3, 'hard', 'multiple_choice_single',
'Dem truoc khi Ha-man dinh treo co Mot-do-che, dieu "ngau nhien" nao xay ra?',
'["Vua mat ngu va doc sach su ky, phat hien Mot-do-che chua duoc thuong", "Vua mo thay", "Thien su bao", "Tin tu xa den"]',
'[0]', 'E-xo-te 6:1-2 - Chua dieu khien su kien "ngau nhien" de bao ve dan Ngai. Khong co chu "Chua" trong sach nhung su quan phong o khap noi.', '["Cuu Uoc","Chu quyen","E-xo-te"]', 'Esther 6:1-3', 'vi', true, NOW(), NOW()),
('q-est-011', 'Esther', 7, 3, 4, 'easy', 'multiple_choice_single',
'Tai tiec ruou, E-xo-te xin vua dieu gi?',
'["Cuu mang ba va dan toc ba", "Dat dai", "Vang bac", "Quyen luc"]',
'[0]', 'E-xo-te 7:3-4 - E-xo-te bay to than phan Do-thai va to cao Ha-man. Su can dam cuu ca dan toc.', '["Cuu Uoc","E-xo-te","Can dam"]', 'Esther 7:3-4', 'vi', true, NOW(), NOW()),
('q-est-012', 'Esther', 7, 10, 10, 'easy', 'multiple_choice_single',
'Ha-man bi treo co tren cai gi?',
'["Moc treo chinh han chuan bi cho Mot-do-che", "Moc treo trong nguc", "Cay lon", "Tuong thanh"]',
'[0]', 'E-xo-te 7:10 - Su ao ngay: Ha-man bi treo tren chinh cai moc han lam cho Mot-do-che. Ai dao ho se sa vao do.', '["Cuu Uoc","Ha-man","Cong binh"]', 'Esther 7:10', 'vi', true, NOW(), NOW()),
('q-est-013', 'Esther', 8, 11, 11, 'medium', 'multiple_choice_single',
'Vua khong the rut lai chieu chi cua Ha-man nhung cho phep dan Do-thai lam gi?',
'["Tu bao ve va chong lai ke tan cong ho", "Bo tron", "Nau tron", "Xin an tu"]',
'[0]', 'E-xo-te 8:11 - Luat Ba-tu khong the rut lai, nhung vua ban chieu chi moi cho phep dan Do-thai tu ve.', '["Cuu Uoc","E-xo-te","Giai cuu"]', 'Esther 8:11', 'vi', true, NOW(), NOW()),
('q-est-014', 'Esther', 9, 20, 22, 'easy', 'fill_in_blank',
'Le Pu-rim duoc to chuc hang nam de ky niem su ___ cua dan Do-thai',
'[]', '[]', 'E-xo-te 9:22 - Le Pu-rim ky niem su giai cuu. Dan su vui mung, trao qua va giup nguoi ngheo.', '["Cuu Uoc","Pu-rim","Le hoi"]', 'Esther 9:20-22', 'vi', true, NOW(), NOW()),
('q-est-015', 'Esther', 10, 3, 3, 'easy', 'multiple_choice_single',
'Cuoi sach, Mot-do-che tro thanh gi?',
'["Te tuong (nguoi thu nhi sau vua)", "Vua", "Tuong quan", "Thay te le"]',
'[0]', 'E-xo-te 10:3 - Tu nguoi bi de doa treo co thanh te tuong. Chua doi nguoc tinh the cho dan Ngai.', '["Cuu Uoc","Mot-do-che","Cat nhac"]', 'Esther 10:3', 'vi', true, NOW(), NOW());
