-- Supplementary: Psalms, Proverbs, Ecclesiastes, Job, Song of Songs

-- ==================== PSALMS (need +7) ====================
INSERT IGNORE INTO questions (id, book, chapter, verse_start, verse_end, difficulty, type, content, options, correct_answer, explanation, tags, source, language, is_active, created_at, updated_at) VALUES
('q-psa-009', 'Psalms', 103, 12, 12, 'easy', 'multiple_choice_single',
'Thi 103:12 noi Chua cat toi loi xa bao nhieu?',
'["Xa nhu phuong dong cach phuong tay", "70 lan 7", "Muon doi", "Den tan cung dat"]',
'[0]', 'Phuong dong va phuong tay khong bao gio gap nhau - toi loi da bi xoa bo hoan toan.', '["Cuu Uoc","Thi thien","Tha thu"]', 'Psalms 103:12', 'vi', true, NOW(), NOW()),
('q-psa-010', 'Psalms', 19, 1, 1, 'easy', 'multiple_choice_single',
'Thi 19:1 noi troi ke ra dieu gi cua Duc Chua Troi?',
'["Su vinh hien", "Su phan xet", "Su khon ngoan", "Su giau co"]',
'[0]', 'Thi 19:1 - Cac tang troi rao truyen cong viec tay Ngai. Thien nhien la bang chung ve Dang Sang Tao.', '["Cuu Uoc","Thi thien","Sang tao"]', 'Psalms 19:1', 'vi', true, NOW(), NOW()),
('q-psa-011', 'Psalms', 27, 4, 4, 'medium', 'fill_in_blank',
'Da-vit xin mot dieu: duoc o trong ___ cua Duc Gie-ho-va tron doi toi (Thi 27:4)',
'[]', '[]', 'Thi 27:4 - Dieu duy nhat Da-vit ao uoc la su hien dien cua Chua, khong phai vat chat.', '["Cuu Uoc","Thi thien","Tho phuong"]', 'Psalms 27:4', 'vi', true, NOW(), NOW()),
('q-psa-012', 'Psalms', 34, 8, 8, 'easy', 'multiple_choice_single',
'Thi 34:8: "Hay ___ xem Duc Gie-ho-va tot lanh dung bao!"',
'["Nem thu", "Suy nghi", "Lang nghe", "Nhin"]',
'[0]', 'Thi 34:8 - Hay nem thu (trai nghiem) su tot lanh cua Chua. Duc tin can trai nghiem ca nhan.', '["Cuu Uoc","Thi thien","Trai nghiem"]', 'Psalms 34:8', 'vi', true, NOW(), NOW()),
('q-psa-013', 'Psalms', 37, 4, 4, 'easy', 'multiple_choice_single',
'Thi 37:4: "Hay lay Duc Gie-ho-va lam dieu ___" thi Ngai se ban cho dieu long ao uoc',
'["Vui thich", "Dau tien", "Quan trong", "Duy nhat"]',
'[0]', 'Thi 37:4 - Khi vui thich trong Chua, Ngai doi moi long ao uoc cua chung ta cho phu hop y Ngai.', '["Cuu Uoc","Thi thien","Vui thich"]', 'Psalms 37:4', 'vi', true, NOW(), NOW()),
('q-psa-014', 'Psalms', 91, 1, 2, 'easy', 'multiple_choice_single',
'Thi 91 mo ta nguoi nau nau noi Chua duoc bao ve khoi dieu gi?',
'["Tat ca: on dich, mui ten, bong toi, tai va", "Chi benh tat", "Chi chien tranh", "Chi ke thu"]',
'[0]', 'Thi 91:3-10 - Bai thi thien ve su bao ve toan dien cua Chua cho nguoi tin cay Ngai.', '["Cuu Uoc","Thi thien","Bao ve"]', 'Psalms 91:1-2', 'vi', true, NOW(), NOW()),
('q-psa-015', 'Psalms', 150, 6, 6, 'easy', 'fill_in_blank',
'Cau cuoi cua sach Thi thien: "Pham vat nao co hoi tho hay ngoi khen Duc ___!"',
'[]', '[]', 'Thi 150:6 - Sach Thi thien ket thuc bang loi keu goi moi sinh vat ngoi khen Chua.', '["Cuu Uoc","Thi thien","Ngoi khen"]', 'Psalms 150:6', 'vi', true, NOW(), NOW()),

-- ==================== PROVERBS (need +10) ====================
('q-pro-006', 'Proverbs', 4, 23, 23, 'easy', 'multiple_choice_single',
'Cham 4:23 day chung ta phai gin giu gi hon het?',
'["Tam long (long minh)", "Tien bac", "Suc khoe", "Danh tieng"]',
'[0]', 'Cham 4:23 - Hay gin giu long con hon het, vi cac nguon su song do ma ra.', '["Cuu Uoc","Khon ngoan","Tam long"]', 'Proverbs 4:23', 'vi', true, NOW(), NOW()),
('q-pro-007', 'Proverbs', 6, 6, 8, 'easy', 'multiple_choice_single',
'Cham ngon khuen ke luoi bieng hoc tap tu con vat nao?',
'["Con kien", "Con ong", "Con chim", "Con soc"]',
'[0]', 'Cham 6:6 - Hay den xem con kien, hoi ke luoi bieng oi. No tich tru luong thuc du khong co chi huy.', '["Cuu Uoc","Khon ngoan","Sieu nang"]', 'Proverbs 6:6-8', 'vi', true, NOW(), NOW()),
('q-pro-008', 'Proverbs', 10, 12, 12, 'easy', 'fill_in_blank',
'Cham 10:12: "Su ghen ghet gay ra su cai va; nhung ___ phu lap het thay cac toi loi"',
'[]', '[]', 'Cham 10:12 - Tinh yeu thuong phu lap toi loi. Phi-e-ro trich cau nay (1 Phi 4:8).', '["Cuu Uoc","Khon ngoan","Yeu thuong"]', 'Proverbs 10:12', 'vi', true, NOW(), NOW()),
('q-pro-009', 'Proverbs', 11, 2, 2, 'easy', 'multiple_choice_single',
'Cham 11:2: "Khi su kieu ngao den, thi su ___ cung den"',
'["Sy nhuc", "Thanh cong", "Giau co", "Quyen luc"]',
'[0]', 'Cham 11:2 - Kieu ngao dan den sy nhuc. Khiem nhuong moi mang lai su khon ngoan.', '["Cuu Uoc","Khon ngoan","Khiem nhuong"]', 'Proverbs 11:2', 'vi', true, NOW(), NOW()),
('q-pro-010', 'Proverbs', 12, 1, 1, 'easy', 'multiple_choice_single',
'Cham 12:1 noi ai la nguoi ngu dai?',
'["Ke ghet su sua phat", "Ke khong hoc", "Ke ngheo", "Ke tre"]',
'[0]', 'Cham 12:1 - Ai yeu su sua phat thi yeu tri thuc, ke ghet su trach phat la ngu dai.', '["Cuu Uoc","Khon ngoan","Sua phat"]', 'Proverbs 12:1', 'vi', true, NOW(), NOW()),
('q-pro-011', 'Proverbs', 15, 1, 1, 'easy', 'multiple_choice_single',
'Cham 15:1 day: "Loi dap mem lam ___"',
'["Nguoi tan con gian", "Nguoi hoa nha", "Nguoi khon ngoan", "Nguoi vui ve"]',
'[0]', 'Cham 15:1 - Loi dap mem lam nguoi tan con gian, nhung loi xoc xa tro su nong gian.', '["Cuu Uoc","Khon ngoan","Loi noi"]', 'Proverbs 15:1', 'vi', true, NOW(), NOW()),
('q-pro-012', 'Proverbs', 16, 3, 3, 'easy', 'fill_in_blank',
'Cham 16:3: "Hay ___ cac viec lam con cho Duc Gie-ho-va thi nhung muu tinh con se duoc thanh"',
'[]', '[]', 'Cham 16:3 - Hay pho thac (giao pho) viec cho Chua va ke hoach se thanh cong.', '["Cuu Uoc","Khon ngoan","Pho thac"]', 'Proverbs 16:3', 'vi', true, NOW(), NOW()),
('q-pro-013', 'Proverbs', 16, 18, 18, 'easy', 'multiple_choice_single',
'Cham 16:18: "Su kieu ngao di truoc su ___"',
'["Bai hoai", "Thanh cong", "Giau co", "Khon ngoan"]',
'[0]', 'Cham 16:18 - Su kieu ngao di truoc su bai hoai, tinh tu phu di truoc su sa nga.', '["Cuu Uoc","Khon ngoan","Kieu ngao"]', 'Proverbs 16:18', 'vi', true, NOW(), NOW()),
('q-pro-014', 'Proverbs', 18, 24, 24, 'medium', 'multiple_choice_single',
'Cham 18:24 noi ve nguoi ban nhu the nao?',
'["Co ban than hon anh em ruot", "Ban nhieu la tot", "Ban it la du", "Khong can ban"]',
'[0]', 'Cham 18:24 - Chat luong hon so luong. Mot ban than that con gan gui hon anh em ruot.', '["Cuu Uoc","Khon ngoan","Tinh ban"]', 'Proverbs 18:24', 'vi', true, NOW(), NOW()),
('q-pro-015', 'Proverbs', 14, 12, 12, 'medium', 'multiple_choice_single',
'Cham 14:12: "Co mot con duong coi dung truoc mat nguoi ta nhung cuoi cung la duong ___"',
'["Su chet", "Giau co", "Thanh cong", "Binh an"]',
'[0]', 'Cham 14:12 - Khong phai moi con duong nhin dung deu dung that. Can su huong dan cua Chua.', '["Cuu Uoc","Khon ngoan","Su lua chon"]', 'Proverbs 14:12', 'vi', true, NOW(), NOW()),

-- ==================== ECCLESIASTES (need +13) ====================
('q-ecc-003', 'Ecclesiastes', 1, 2, 2, 'easy', 'multiple_choice_single',
'Cau noi noi tieng cua sach Truyen Dao la gi?',
'["Hu khong cua hu khong, thay deu hu khong", "Moi su deu tot", "Hay vui huong", "Thoi gian la vang"]',
'[0]', 'Truyen dao 1:2 - Hebel (hu khong/hoi nuoc) noi len tinh tam thoi va vo nghia cua doi song duoi mat troi khi khong co Chua.', '["Cuu Uoc","Truyen dao","Hu khong"]', 'Ecclesiastes 1:2', 'vi', true, NOW(), NOW()),
('q-ecc-004', 'Ecclesiastes', 3, 11, 11, 'medium', 'multiple_choice_single',
'Truyen dao 3:11 noi Chua dat gi trong long nguoi ta?',
'["Su doi doi (y niem ve su vinh cuu)", "Su khon ngoan", "Su vui ve", "Su so hai"]',
'[0]', 'Truyen dao 3:11 - Chua dat su doi doi trong long nguoi. Chung ta duoc tao dung de huong ve vinh cuu.', '["Cuu Uoc","Truyen dao","Vinh cuu"]', 'Ecclesiastes 3:11', 'vi', true, NOW(), NOW()),
('q-ecc-005', 'Ecclesiastes', 4, 9, 10, 'easy', 'multiple_choice_single',
'Truyen dao 4:9 noi gi ve viec lam chung?',
'["Hai nguoi hon mot vi ho duoc cong gia tot", "Mot nguoi tot hon", "Ba nguoi la tot nhat", "Khong khac biet"]',
'[0]', 'Truyen dao 4:9-10 - Hai nguoi hon mot. Neu nguoi nay te, nguoi kia do day. Gia tri cua tinh ban va cong dong.', '["Cuu Uoc","Truyen dao","Cong dong"]', 'Ecclesiastes 4:9-10', 'vi', true, NOW(), NOW()),
('q-ecc-006', 'Ecclesiastes', 4, 12, 12, 'easy', 'fill_in_blank',
'Truyen dao 4:12: "Mot soi day ___ khong de gi dut"',
'[]', '[]', 'Truyen dao 4:12 - Day ba tao (ba soi) khong de dut. Bieu tuong cho tinh ban hoac hon nhan co Chua lam trung tam.', '["Cuu Uoc","Truyen dao","Hiep nhat"]', 'Ecclesiastes 4:12', 'vi', true, NOW(), NOW()),
('q-ecc-007', 'Ecclesiastes', 5, 10, 10, 'easy', 'multiple_choice_single',
'Truyen dao 5:10 noi gi ve tien bac?',
'["Ai yeu bac khong bao gio du bac", "Tien mang lai hanh phuc", "Hay tich tru nhieu", "Tien la goc cua moi ac"]',
'[0]', 'Truyen dao 5:10 - Tien bac khong bao gio du cho nguoi yeu no. Su tham lam khong bao gio thoa man.', '["Cuu Uoc","Truyen dao","Tien bac"]', 'Ecclesiastes 5:10', 'vi', true, NOW(), NOW()),
('q-ecc-008', 'Ecclesiastes', 7, 2, 2, 'hard', 'multiple_choice_single',
'Tai sao Sa-lo-mon noi den nha co tang tot hon den nha an tiec?',
'["Vi o do nguoi ta suy nghi ve le cuoi cung va song khon ngoan hon", "Vi re hon", "Vi yen tinh hon", "Vi ton giao hon"]',
'[0]', 'Truyen dao 7:2 - Doi dien voi su chet giup chung ta suy nghi nghiem tuc ve y nghia cuoc song.', '["Cuu Uoc","Truyen dao","Su chet"]', 'Ecclesiastes 7:2', 'vi', true, NOW(), NOW()),
('q-ecc-009', 'Ecclesiastes', 9, 10, 10, 'easy', 'multiple_choice_single',
'Truyen dao 9:10 khuyen lam viec nhu the nao?',
'["Het suc lam moi viec tay minh lam", "Lam vua du", "Chi lam khi thich", "De nguoi khac lam"]',
'[0]', 'Truyen dao 9:10 - Hay het long lam viec vi trong Am phu khong co viec lam hay tri thuc nua.', '["Cuu Uoc","Truyen dao","Can cu"]', 'Ecclesiastes 9:10', 'vi', true, NOW(), NOW()),
('q-ecc-010', 'Ecclesiastes', 11, 1, 1, 'medium', 'fill_in_blank',
'Truyen dao 11:1: "Hay rai banh con tren mat ___; vi khoi lau con se gap lai"',
'[]', '[]', 'Truyen dao 11:1 - Hay rong rai ban cho, du khong thay ket qua ngay. Sau nay se duoc bao dap.', '["Cuu Uoc","Truyen dao","Rong rai"]', 'Ecclesiastes 11:1', 'vi', true, NOW(), NOW()),
('q-ecc-011', 'Ecclesiastes', 11, 4, 4, 'easy', 'multiple_choice_single',
'Truyen dao 11:4 canh bao dieu gi?',
'["Ke ngong gio se khong gieo, ke nhin may se khong gat", "Hay cho thoi tiet tot", "Hay ke hoach ky", "Dung voi vang"]',
'[0]', 'Truyen dao 11:4 - Dung cho dieu kien hoan hao, hay hanh dong ngay. Cho doi mai se khong bao gio bat dau.', '["Cuu Uoc","Truyen dao","Hanh dong"]', 'Ecclesiastes 11:4', 'vi', true, NOW(), NOW()),
('q-ecc-012', 'Ecclesiastes', 12, 1, 1, 'easy', 'multiple_choice_single',
'Truyen dao 12:1 khuyen hay nho Dang Sang Tao khi nao?',
'["Trong nhung ngay thanh xuan (tre tuoi)", "Khi gia", "Khi gap kho khan", "Khi thanh cong"]',
'[0]', 'Truyen dao 12:1 - Hay nho Chua khi con tre, dung cho den khi gia moi tim kiem Ngai.', '["Cuu Uoc","Truyen dao","Thanh xuan"]', 'Ecclesiastes 12:1', 'vi', true, NOW(), NOW()),
('q-ecc-013', 'Ecclesiastes', 3, 4, 4, 'easy', 'fill_in_blank',
'Co ky khoc, va co ky ___; co ky buon rau va co ky nhay mua (Truyen dao 3:4)',
'[]', '[]', 'Truyen dao 3:4 - Moi mua trong doi deu co muc dich. Chua dieu khien moi thoi ky.', '["Cuu Uoc","Truyen dao","Thoi dinh"]', 'Ecclesiastes 3:4', 'vi', true, NOW(), NOW()),
('q-ecc-014', 'Ecclesiastes', 7, 8, 8, 'easy', 'multiple_choice_single',
'Truyen dao 7:8: "Su cuoi cung cua mot viec hon su ___ no"',
'["Bat dau", "Giua", "Ke hoach", "Y tuong"]',
'[0]', 'Truyen dao 7:8 - Su kien nhan tot hon su kieu ngao. Hay dung xet doan qua som.', '["Cuu Uoc","Truyen dao","Kien nhan"]', 'Ecclesiastes 7:8', 'vi', true, NOW(), NOW()),
('q-ecc-015', 'Ecclesiastes', 12, 7, 7, 'medium', 'multiple_choice_single',
'Truyen dao 12:7 noi khi chet, than linh tro ve dau?',
'["Tro ve cung Duc Chua Troi la Dang da ban cho", "Tan bien", "O lai dat", "Di den Am phu"]',
'[0]', 'Truyen dao 12:7 - Bui tro ve bui, than linh tro ve cung Chua. Con nguoi co phan thuoc linh vinh cuu.', '["Cuu Uoc","Truyen dao","Su chet"]', 'Ecclesiastes 12:7', 'vi', true, NOW(), NOW()),

-- ==================== JOB (15 moi) ====================
('q-job-001', 'Job', 1, 1, 1, 'easy', 'multiple_choice_single',
'Kinh Thanh mo ta Giop la nguoi nhu the nao?',
'["Tron ven, chinh truc, kinh so Chua, lanh xa dieu ac", "Giau nhat", "Khon ngoan nhat", "Manh nhat"]',
'[0]', 'Giop 1:1 - Giop la nguoi tron ven va ngay thang, kinh so Duc Chua Troi va lanh xa dieu ac.', '["Cuu Uoc","Giop","Cong binh"]', 'Job 1:1', 'vi', true, NOW(), NOW()),
('q-job-002', 'Job', 1, 9, 11, 'medium', 'multiple_choice_single',
'Sa-tan to cao Giop kinh so Chua vi ly do gi?',
'["Vi Chua bao ve va ban phuc, khong phai tu tam long", "Vi Giop so hinh phat", "Vi Giop muon duoc khen", "Vi Giop ngu dot"]',
'[0]', 'Giop 1:9-11 - Sa-tan to cao rang Giop chi tin vi duoc loi. Chua cho phep thu thach de chung minh duc tin that.', '["Cuu Uoc","Giop","Thu thach"]', 'Job 1:9-11', 'vi', true, NOW(), NOW()),
('q-job-003', 'Job', 1, 21, 21, 'easy', 'fill_in_blank',
'Giop noi: "Toi tran truong loi long me, se tran truong tro ve. Duc Gie-ho-va da ban cho, Duc Gie-ho-va lai ___"',
'[]', '[]', 'Giop 1:21 - Duc Gie-ho-va da ban cho va lay di. Dang chuc tung danh Duc Gie-ho-va.', '["Cuu Uoc","Giop","Tin cay"]', 'Job 1:21', 'vi', true, NOW(), NOW()),
('q-job-004', 'Job', 2, 9, 10, 'easy', 'multiple_choice_single',
'Vo Giop noi ong nen lam gi? Giop dap the nao?',
'["Vo noi: rua Chua di roi chet. Giop: chung ta nhan phuc thi khong nhan hoa sao?", "Ca hai khoc", "Ca hai cau nguyen", "Ca hai bo cuoc"]',
'[0]', 'Giop 2:9-10 - Giop tu choi bo duc tin du nguoi than nhat khuyen ong tu bo.', '["Cuu Uoc","Giop","Duc tin"]', 'Job 2:9-10', 'vi', true, NOW(), NOW()),
('q-job-005', 'Job', 13, 15, 15, 'medium', 'multiple_choice_single',
'Giop tuyen bo dieu gi du dang chiu kho?',
'["Du Ngai giet toi, toi van tin cay Ngai", "Toi se bo Chua", "Toi vo toi", "Chua bat cong"]',
'[0]', 'Giop 13:15 - Duc tin khong dieu kien: tin cay Chua du trong hoan canh xau nhat.', '["Cuu Uoc","Giop","Duc tin"]', 'Job 13:15', 'vi', true, NOW(), NOW()),
('q-job-006', 'Job', 19, 25, 26, 'easy', 'multiple_choice_single',
'Giop tuyen bo: "Toi biet rang Dang ___ toi hang song"',
'["Cuu chuoc", "Sang tao", "Phan xet", "Bao ve"]',
'[0]', 'Giop 19:25 - Giua kho nan, Giop tuyen bo tin vao Dang Cuu Chuoc hang song va su phuc sinh.', '["Cuu Uoc","Giop","Cuu chuoc"]', 'Job 19:25-26', 'vi', true, NOW(), NOW()),
('q-job-007', 'Job', 38, 1, 4, 'medium', 'multiple_choice_single',
'Chua tra loi Giop tu dau?',
'["Tu trong con gio loc", "Tu troi", "Tu bui gai chay", "Tu dam may"]',
'[0]', 'Giop 38:1 - Chua phan tu gio loc, hoi Giop nhieu cau hoi ve sang tao de cho thay su khon ngoan vo han cua Ngai.', '["Cuu Uoc","Giop","Chu quyen"]', 'Job 38:1-4', 'vi', true, NOW(), NOW()),
('q-job-008', 'Job', 38, 4, 4, 'easy', 'fill_in_blank',
'Chua hoi Giop: "Nguoi o dau khi ta dat nen ___?"',
'[]', '[]', 'Giop 38:4 - Chua hoi: Nguoi o dau khi ta dat nen trai dat? Giop nhan ra minh qua nho be truoc Dang Sang Tao.', '["Cuu Uoc","Giop","Sang tao"]', 'Job 38:4', 'vi', true, NOW(), NOW()),
('q-job-009', 'Job', 40, 4, 5, 'easy', 'multiple_choice_single',
'Sau khi Chua phan, Giop phan ung the nao?',
'["Lay tay bung mieng, khong dap nua", "Tranh luan tiep", "Gian du", "Bo chay"]',
'[0]', 'Giop 40:4-5 - Giop nhan ra su nho be cua minh truoc su vi dai cua Chua va im lang.', '["Cuu Uoc","Giop","Khiem nhuong"]', 'Job 40:4-5', 'vi', true, NOW(), NOW()),
('q-job-010', 'Job', 42, 5, 6, 'medium', 'multiple_choice_single',
'Giop noi: "Truoc tai toi nghe don ve Chua, nhung bay gio ___"',
'["Mat toi da thay Ngai", "Toi hieu Ngai", "Toi tin Ngai", "Toi biet Ngai"]',
'[0]', 'Giop 42:5 - Tu tin nghe noi den trai nghiem ca nhan. Kho nan dan Giop den su hieu biet sau hon ve Chua.', '["Cuu Uoc","Giop","Trai nghiem"]', 'Job 42:5-6', 'vi', true, NOW(), NOW()),
('q-job-011', 'Job', 42, 10, 12, 'easy', 'multiple_choice_single',
'Cuoi cung Chua ban cho Giop bao nhieu so voi truoc?',
'["Gap doi moi thu", "Bang cu", "It hon", "Gap ba"]',
'[0]', 'Giop 42:10 - Chua phuc hoi gap doi. Chua thuong nguoi kien nhan chiu dung (Gia-co 5:11).', '["Cuu Uoc","Giop","Phuc hoi"]', 'Job 42:10-12', 'vi', true, NOW(), NOW()),
('q-job-012', 'Job', 28, 28, 28, 'easy', 'multiple_choice_single',
'Giop 28:28 ket luan su khon ngoan that la gi?',
'["Kinh so Chua va lanh xa dieu ac", "Hoc nhieu", "Kinh nghiem", "Tri thuc"]',
'[0]', 'Giop 28:28 - Giong nhu Cham 1:7 va Truyen dao 12:13. Su khon ngoan bat dau va ket thuc o su kinh so Chua.', '["Cuu Uoc","Giop","Khon ngoan"]', 'Job 28:28', 'vi', true, NOW(), NOW()),
('q-job-013', 'Job', 1, 22, 22, 'easy', 'fill_in_blank',
'Trong moi su do, Giop khong pham ___ va khong trach Duc Chua Troi (Giop 1:22)',
'[]', '[]', 'Giop 1:22 - Du mat het con cai va tai san, Giop khong pham toi bang loi noi.', '["Cuu Uoc","Giop","Trung tin"]', 'Job 1:22', 'vi', true, NOW(), NOW()),
('q-job-014', 'Job', 5, 17, 17, 'medium', 'multiple_choice_single',
'E-li-pha noi: "Phuc thay nguoi nao Duc Chua Troi ___"',
'["Sua phat, chot khinh de su trach phat cua Dang Toan Nang", "Yeu thuong", "Ban phuc", "Bao ve"]',
'[0]', 'Giop 5:17 - Su trach phat cua Chua la dau hieu tinh yeu, khong phai su bo roi (He 12:6).', '["Cuu Uoc","Giop","Sua phat"]', 'Job 5:17', 'vi', true, NOW(), NOW()),
('q-job-015', 'Job', 42, 7, 8, 'hard', 'multiple_choice_single',
'Chua trach 3 ban cua Giop vi ly do gi?',
'["Ho khong noi dung ve Chua nhu Giop", "Ho khong cau nguyen", "Ho bo Giop", "Ho tho tuong"]',
'[0]', 'Giop 42:7 - Du Giop than van, ong van trung thuc voi Chua. 3 ban co giao ly gon gang nhung sai ve ban tinh Chua.', '["Cuu Uoc","Giop","Than hoc"]', 'Job 42:7-8', 'vi', true, NOW(), NOW());
