-- Supplementary: Exodus, Leviticus, Numbers, Deuteronomy (to reach 15 each)

-- ==================== EXODUS (need +5) ====================
INSERT IGNORE INTO questions (id, book, chapter, verse_start, verse_end, difficulty, type, content, options, correct_answer, explanation, tags, source, language, is_active, created_at, updated_at) VALUES
('q-exo-011', 'Exodus', 15, 20, 21, 'easy', 'multiple_choice_single',
'Ai da hat bai ca chien thang sau khi vuot Bien Do?',
'["Mi-ri-am, chi Moi-se", "Moi-se", "A-ron", "Gio-sue"]',
'[0]', 'Xuat 15:20 - Mi-ri-am cam trong com va dan dau phu nu hat ngoi khen Chua.', '["Cuu Uoc","Ngoi khen","Mi-ri-am"]', 'Exodus 15:20-21', 'vi', true, NOW(), NOW()),
('q-exo-012', 'Exodus', 17, 11, 12, 'medium', 'multiple_choice_single',
'Khi Moi-se gio tay len trong tran danh A-ma-lec, dieu gi xay ra?',
'["Y-so-ra-en thang; khi ha tay xuong thi thua", "Lua tu troi roi xuong", "Nuoc tu da chay ra", "Dat rung chuyen"]',
'[0]', 'Xuat 17:11 - A-ron va Ho-ro do tay Moi-se de Y-so-ra-en thang. Hinh anh ve su cau nguyen lien tuc.', '["Cuu Uoc","Chien tran","Cau nguyen"]', 'Exodus 17:11-12', 'vi', true, NOW(), NOW()),
('q-exo-013', 'Exodus', 25, 10, 22, 'hard', 'multiple_choice_single',
'Hom Giao Uoc chua nhung gi ben trong?',
'["Hai bang da, binh ma-na, gay A-ron da nay mam", "Chi hai bang da", "Chi binh ma-na", "Sach luat phap"]',
'[0]', 'He-bo-ro 9:4 liet ke 3 vat trong Hom: hai bang luat, binh ma-na vang, va gay A-ron nay mam.', '["Cuu Uoc","Hom Giao Uoc","Den tam"]', 'Exodus 25:10-22', 'vi', true, NOW(), NOW()),
('q-exo-014', 'Exodus', 32, 1, 4, 'easy', 'multiple_choice_single',
'Khi Moi-se len nui Si-nai lau, dan su lam tuong gi de tho?',
'["Bo con vang", "Tuong ran", "Cot da", "Cay lon"]',
'[0]', 'Xuat 32:4 - A-ron lam bo con vang tu vang cua dan su. Day la toi tho hinh tuong lon nhat cua Y-so-ra-en.', '["Cuu Uoc","Hinh tuong","Toi loi"]', 'Exodus 32:1-4', 'vi', true, NOW(), NOW()),
('q-exo-015', 'Exodus', 34, 29, 30, 'medium', 'fill_in_blank',
'Khi Moi-se tu nui Si-nai xuong, mat ong nhu the nao? (1 tu)',
'[]', '[]', 'Xuat 34:29 - Mat Moi-se chieu sang (phat sang) vi da noi chuyen voi Chua. Dan su so khong dam den gan.', '["Cuu Uoc","Moi-se","Vinh quang"]', 'Exodus 34:29-30', 'vi', true, NOW(), NOW()),

-- ==================== LEVITICUS (need +12) ====================
('q-lev-004', 'Leviticus', 1, 3, 4, 'easy', 'multiple_choice_single',
'Cua le thieu phai la thu vat nhu the nao?',
'["Khong ti vet, con duc", "Bat ky con vat nao", "Con cai nhat", "Con lon nhat"]',
'[0]', 'Le-vi 1:3 - Cua le thieu phai la con duc khong ti vet. Hinh bong cua Chua Gie-su toan hao.', '["Cuu Uoc","Te le","Cua le"]', 'Leviticus 1:3-4', 'vi', true, NOW(), NOW()),
('q-lev-005', 'Leviticus', 11, 1, 8, 'easy', 'multiple_choice_single',
'Theo luat thanh sach, thu vat nao duoc an?',
'["Thu vat co mong che va nhoi lai", "Tat ca thu vat", "Chi thu vat lon", "Thu vat co sung"]',
'[0]', 'Le-vi 11:3 - Thu vat thanh sach phai co hai dieu kien: mong che va nhoi lai (nhu bo, de, cuu).', '["Cuu Uoc","Luat phap","Thanh sach"]', 'Leviticus 11:1-8', 'vi', true, NOW(), NOW()),
('q-lev-006', 'Leviticus', 23, 5, 8, 'medium', 'multiple_choice_single',
'Le Vuot Qua duoc to chuc vao thang may trong lich Do-thai?',
'["Thang gieng (Nisan), ngay 14", "Thang 7, ngay 1", "Thang 3, ngay 6", "Thang 10, ngay 15"]',
'[0]', 'Le-vi 23:5 - Ngay 14 thang gieng la Le Vuot Qua cua Duc Gie-ho-va.', '["Cuu Uoc","Le hoi","Vuot Qua"]', 'Leviticus 23:5-8', 'vi', true, NOW(), NOW()),
('q-lev-007', 'Leviticus', 23, 15, 16, 'hard', 'multiple_choice_single',
'Le Ngu Tuan (Shavuot) duoc to chuc bao ngay sau Le Vuot Qua?',
'["50 ngay", "40 ngay", "30 ngay", "7 ngay"]',
'[0]', 'Le-vi 23:16 - 50 ngay sau ngay Sa-bat cua Le Vuot Qua. Tan Uoc: Duc Thanh Linh giang lam dung ngay nay (Cong vu 2).', '["Cuu Uoc","Le hoi","Ngu Tuan"]', 'Leviticus 23:15-16', 'vi', true, NOW(), NOW()),
('q-lev-008', 'Leviticus', 25, 10, 10, 'medium', 'multiple_choice_single',
'Nam Hoan Hi (Jubilee) duoc to chuc moi bao nhieu nam?',
'["50 nam", "7 nam", "40 nam", "100 nam"]',
'[0]', 'Le-vi 25:10 - Moi 50 nam la Nam Hoan Hi: tra tu do cho no le, tra dat ve cho chu cu. Bieu tuong su giai phong.', '["Cuu Uoc","Luat phap","Hoan Hi"]', 'Leviticus 25:10', 'vi', true, NOW(), NOW()),
('q-lev-009', 'Leviticus', 19, 2, 2, 'easy', 'fill_in_blank',
'Duc Gie-ho-va phan: "Hay nen ___ vi ta, Gie-ho-va Duc Chua Troi cac nguoi, von la thanh" (Le-vi 19:2)',
'[]', '[]', 'Le-vi 19:2 - Thanh khiet la ban tinh Chua va la tieu chuan cho dan su Ngai.', '["Cuu Uoc","Thanh khiet","Luat phap"]', 'Leviticus 19:2', 'vi', true, NOW(), NOW()),
('q-lev-010', 'Leviticus', 16, 29, 30, 'medium', 'multiple_choice_single',
'Ngay Le Chuoc Toi (Yom Kippur) dien ra vao ngay nao?',
'["Ngay 10 thang 7", "Ngay 14 thang 1", "Ngay 1 thang 7", "Ngay 15 thang 1"]',
'[0]', 'Le-vi 16:29 - Ngay 10 thang bay la Le Chuoc Toi, ngay thanh khiet nhat trong nam.', '["Cuu Uoc","Le hoi","Chuoc toi"]', 'Leviticus 16:29-30', 'vi', true, NOW(), NOW()),
('q-lev-011', 'Leviticus', 23, 34, 36, 'easy', 'multiple_choice_single',
'Le Leu Tam (Sukkot) nham ky niem su kien gi?',
'["Dan Y-so-ra-en song trong leu trai 40 nam trong dong vang", "Ngay sang the", "Le gat mua", "Ngay vuot Bien Do"]',
'[0]', 'Le-vi 23:43 - De con chau Y-so-ra-en nho rang Chua cho to phu ho song trong leu trai khi dan ra khoi Ai-cap.', '["Cuu Uoc","Le hoi","Dong vang"]', 'Leviticus 23:34-36', 'vi', true, NOW(), NOW()),
('q-lev-012', 'Leviticus', 10, 1, 2, 'medium', 'multiple_choice_single',
'Na-dap va A-bi-hu, con A-ron, bi chet vi lam gi?',
'["Dang lua la truoc mat Chua ma Ngai khong phan dinh", "An trom cua le", "Tho tuong", "Bo tron"]',
'[0]', 'Le-vi 10:1-2 - Ho dang lua la (khong duoc phep) truoc mat Chua. Lua tu Chua phat ra thieu ho. Bai hoc ve su ton kinh Chua.', '["Cuu Uoc","Te le","Thanh khiet"]', 'Leviticus 10:1-2', 'vi', true, NOW(), NOW()),
('q-lev-013', 'Leviticus', 4, 2, 3, 'easy', 'multiple_choice_single',
'Cua le chuoc toi duoc dang khi nao?',
'["Khi ai pham toi khong co y", "Chi vao Le Chuoc Toi", "Moi ngay Sa-bat", "Khi muon ta on"]',
'[0]', 'Le-vi 4:2 - Cua le chuoc toi danh cho nguoi pham toi vi khong biet. Cho thay Chua nghiem tuc voi moi toi loi.', '["Cuu Uoc","Te le","Chuoc toi"]', 'Leviticus 4:2-3', 'vi', true, NOW(), NOW()),
('q-lev-014', 'Leviticus', 26, 3, 6, 'easy', 'multiple_choice_single',
'Le-vi 26 hua dieu gi neu dan su vang loi Chua?',
'["Mua thuan gio hoa, binh an, phuc lanh", "Giau co vo tan", "Chien thang moi ke thu", "Song doi doi"]',
'[0]', 'Le-vi 26:3-6 - Chua hua mua thuan, mua mang doi dao, binh an trong xu va khong con thu hoang.', '["Cuu Uoc","Phuc lanh","Vang loi"]', 'Leviticus 26:3-6', 'vi', true, NOW(), NOW()),
('q-lev-015', 'Leviticus', 20, 26, 26, 'medium', 'fill_in_blank',
'Chua phan: "Hay lam nguoi ___ cho ta vi ta Gie-ho-va von la thanh" (Le-vi 20:26)',
'[]', '[]', 'Le-vi 20:26 - Chua biet rieng dan su de thuoc rieng ve Ngai. Thanh khiet = duoc biet rieng cho Chua.', '["Cuu Uoc","Thanh khiet","Biet rieng"]', 'Leviticus 20:26', 'vi', true, NOW(), NOW()),

-- ==================== NUMBERS (need +11) ====================
('q-num-005', 'Numbers', 6, 1, 8, 'medium', 'multiple_choice_single',
'Nguoi Na-xi-re phai kieng cu nhung gi?',
'["Ruou nho, khong cat toc, khong cham xac chet", "Chi kieng ruou", "An chay", "Song mot minh"]',
'[0]', 'Dan 6:2-7 - Loi hua Na-xi-re gom 3 dieu: kieng ruou, khong cat toc, tranh xac chet. Sam-son la nguoi Na-xi-re noi tieng.', '["Cuu Uoc","Loi hua","Na-xi-re"]', 'Numbers 6:1-8', 'vi', true, NOW(), NOW()),
('q-num-006', 'Numbers', 11, 4, 6, 'easy', 'multiple_choice_single',
'Dan Y-so-ra-en ca than trong dong vang vi muon an gi thay vi ma-na?',
'["Thit, dua chuot, dua gang, toi, hanh", "Banh mi va pho mat", "Trai cay", "Ca va com"]',
'[0]', 'Dan 11:5 - Ho nho mon an o Ai-cap va chan ngan ma-na. Bai hoc ve long biet on.', '["Cuu Uoc","Dong vang","Ca than"]', 'Numbers 11:4-6', 'vi', true, NOW(), NOW()),
('q-num-007', 'Numbers', 12, 1, 10, 'medium', 'multiple_choice_single',
'Mi-ri-am bi phat benh phung vi lam gi?',
'["Noi nghich cung Moi-se", "Tho tuong", "Ca than ve ma-na", "Bo tron"]',
'[0]', 'Dan 12:1-10 - Mi-ri-am va A-ron noi nghich Moi-se. Chua phat Mi-ri-am benh phung 7 ngay. Bai hoc ve ton trong nguoi lanh dao Chua chon.', '["Cuu Uoc","Mi-ri-am","Ky luat"]', 'Numbers 12:1-10', 'vi', true, NOW(), NOW()),
('q-num-008', 'Numbers', 14, 18, 18, 'easy', 'fill_in_blank',
'Dan 14:18: "Duc Gie-ho-va cham gian va day on ___, hay tha su gian ac va toi loi"',
'[]', '[]', 'Dan 14:18 - Chua cham gian, day on thuong, tha thu toi loi nhung khong ke ke co toi la vo toi.', '["Cuu Uoc","Tinh Chua","Tha thu"]', 'Numbers 14:18', 'vi', true, NOW(), NOW()),
('q-num-009', 'Numbers', 16, 31, 33, 'easy', 'multiple_choice_single',
'Co-re, Da-than va A-bi-ram bi phat the nao vi noi loan chong Moi-se?',
'["Dat ha mieng nuot ho song", "Lua tu troi thieu", "Benh dich", "Nuoc lu cuon di"]',
'[0]', 'Dan 16:32 - Dat ha mieng nuot ho va ca gia dinh. Bai hoc ve hau qua cua viec chong lai quyen binh Chua thiet lap.', '["Cuu Uoc","Noi loan","Hinh phat"]', 'Numbers 16:31-33', 'vi', true, NOW(), NOW()),
('q-num-010', 'Numbers', 17, 8, 8, 'easy', 'multiple_choice_single',
'Gay cua ai da nay mam, tro bong va sinh qua hanh nhan?',
'["Gay cua A-ron", "Gay cua Moi-se", "Gay cua Gio-sue", "Gay cua Ca-lep"]',
'[0]', 'Dan 17:8 - Gay A-ron nay mam de xac nhan ong la thay te le Chua chon.', '["Cuu Uoc","A-ron","Te le"]', 'Numbers 17:8', 'vi', true, NOW(), NOW()),
('q-num-011', 'Numbers', 20, 11, 12, 'medium', 'multiple_choice_single',
'Tai sao Moi-se khong duoc vao Dat Hua?',
'["Dap gay vao da thay vi phan truyen voi da", "Vi ong qua gia", "Vi dan su toi loi", "Vi ong giet nguoi Ai-cap"]',
'[0]', 'Dan 20:12 - Moi-se dap da 2 lan thay vi phan truyen. Chua noi: vi khong tin ta de ton thanh ta truoc dan.', '["Cuu Uoc","Moi-se","Vang loi"]', 'Numbers 20:11-12', 'vi', true, NOW(), NOW()),
('q-num-012', 'Numbers', 22, 28, 30, 'easy', 'multiple_choice_single',
'Con vat nao da noi tieng nguoi voi tien tri Ba-la-am?',
'["Con lua cai", "Con ran", "Con chim", "Con de"]',
'[0]', 'Dan 22:28 - Duc Gie-ho-va mo mieng con lua va no noi voi Ba-la-am. Thien su Chua dung chan duong.', '["Cuu Uoc","Ba-la-am","Phep la"]', 'Numbers 22:28-30', 'vi', true, NOW(), NOW()),
('q-num-013', 'Numbers', 23, 19, 19, 'medium', 'fill_in_blank',
'Dan 23:19: "Duc Chua Troi khong phai la nguoi de Ngai ___"',
'[]', '[]', 'Dan 23:19 - Chua khong phai la nguoi de noi doi. Ngai da phan, ha chang lam? Ngai thanh tin tuyet doi.', '["Cuu Uoc","Tinh Chua","Thanh tin"]', 'Numbers 23:19', 'vi', true, NOW(), NOW()),
('q-num-014', 'Numbers', 27, 18, 20, 'easy', 'multiple_choice_single',
'Ai duoc chon lam nguoi ke nhiem Moi-se lanh dao dan Y-so-ra-en?',
'["Gio-sue", "Ca-lep", "A-ron", "E-le-a-xa"]',
'[0]', 'Dan 27:18 - Chua chon Gio-sue, nguoi co Than cua Ngai ngu tren, de lanh dao dan su vao Dat Hua.', '["Cuu Uoc","Gio-sue","Lanh dao"]', 'Numbers 27:18-20', 'vi', true, NOW(), NOW()),
('q-num-015', 'Numbers', 24, 17, 17, 'hard', 'multiple_choice_single',
'Ba-la-am tien tri: "Mot ngoi sao se moc tu Gia-cop." Day la tien tri ve ai?',
'["Chua Gie-su Christ - Dang Cuu The", "Vua Da-vit", "Moi-se", "Gio-sue"]',
'[0]', 'Dan 24:17 - Ngoi sao tu Gia-cop la tien tri ve Dang Cuu The. Cac nha thong thai theo ngoi sao den Bet-le-hem (Mat 2:2).', '["Cuu Uoc","Tien tri","Cuu The"]', 'Numbers 24:17', 'vi', true, NOW(), NOW()),

-- ==================== DEUTERONOMY (need +11) ====================
('q-deu-005', 'Deuteronomy', 8, 3, 3, 'medium', 'multiple_choice_single',
'Tai sao Chua cho dan an ma-na trong dong vang?',
'["De day rang nguoi ta song khong chi nho banh ma boi Loi Chua", "Vi khong co thuc an khac", "De thu duc tin", "Vi dan xin"]',
'[0]', 'Phuc truyen 8:3 - Chua Gie-su trich chinh cau nay khi bi Sa-tan cam do (Mat 4:4).', '["Cuu Uoc","Loi Chua","Bai hoc"]', 'Deuteronomy 8:3', 'vi', true, NOW(), NOW()),
('q-deu-006', 'Deuteronomy', 7, 6, 6, 'easy', 'multiple_choice_single',
'Chua chon dan Y-so-ra-en vi ly do gi?',
'["Vi tinh yeu cua Ngai va loi hua voi to phu, khong phai vi ho dong", "Vi ho dong nhat", "Vi ho tot lanh nhat", "Vi ho manh nhat"]',
'[0]', 'Phuc truyen 7:7-8 - Chua chon Y-so-ra-en khong vi ho dong hay gioi, ma vi tinh yeu va loi giao uoc.', '["Cuu Uoc","Duoc chon","Tinh yeu"]', 'Deuteronomy 7:6', 'vi', true, NOW(), NOW()),
('q-deu-007', 'Deuteronomy', 10, 12, 13, 'easy', 'multiple_choice_single',
'Phuc truyen 10:12 noi Chua doi hoi dan su dieu gi?',
'["Kinh so Chua, di theo duong Ngai, yeu men va phuc vu Ngai het long", "Xay den tho", "Chinh phuc cac dan toc", "Dang nhieu cua le"]',
'[0]', 'Phuc truyen 10:12 - Tom tat toan bo luat phap trong mot cau: kinh so, yeu men va phuc vu Chua.', '["Cuu Uoc","Dieu ran","Phuc vu"]', 'Deuteronomy 10:12-13', 'vi', true, NOW(), NOW()),
('q-deu-008', 'Deuteronomy', 11, 18, 19, 'medium', 'multiple_choice_single',
'Moi-se day dan su phai lam gi voi Loi Chua?',
'["Buoc vao tay, deo tren tran, day con cai, viet tren cua", "Chi doc moi Sa-bat", "Chi thay te le hoc", "Giu kin trong Hom Giao Uoc"]',
'[0]', 'Phuc truyen 11:18-20 - Loi Chua phai tham nhap moi khia canh cuoc song: ca nhan, gia dinh, xa hoi.', '["Cuu Uoc","Loi Chua","Giao duc"]', 'Deuteronomy 11:18-19', 'vi', true, NOW(), NOW()),
('q-deu-009', 'Deuteronomy', 28, 1, 6, 'easy', 'multiple_choice_single',
'Phuc truyen 28 hua phuc lanh cho ai?',
'["Nguoi vang giong Chua", "Nguoi giau co", "Thay te le", "Vua"]',
'[0]', 'Phuc truyen 28:1-2 - Neu vang giong Chua, moi phuc lanh se den tren nguoi va theo kip nguoi.', '["Cuu Uoc","Phuc lanh","Vang loi"]', 'Deuteronomy 28:1-6', 'vi', true, NOW(), NOW()),
('q-deu-010', 'Deuteronomy', 29, 29, 29, 'hard', 'multiple_choice_single',
'Phuc truyen 29:29 phan biet dieu gi?',
'["Nhung dieu kin nhiem thuoc Chua, nhung dieu bay to thuoc chung ta", "Luat phap va an dien", "Cuu Uoc va Tan Uoc", "Troi va dat"]',
'[0]', 'Phuc truyen 29:29 - Co nhung dieu Chua giu kin va nhung dieu Ngai bay to. Chung ta chiu trach nhiem voi nhung gi da duoc bay to.', '["Cuu Uoc","Than hoc","Su hieu biet"]', 'Deuteronomy 29:29', 'vi', true, NOW(), NOW()),
('q-deu-011', 'Deuteronomy', 30, 19, 19, 'easy', 'multiple_choice_single',
'Moi-se keu goi dan su chon dieu gi?',
'["Su song va phuc lanh (thay vi su chet va rao rua)", "Dat Hua", "Vua", "Chien tranh"]',
'[0]', 'Phuc truyen 30:19 - Moi-se dat truoc dan su hai duong: su song va su chet, phuc lanh va rao rua. Hay chon su song!', '["Cuu Uoc","Su chon lua","Su song"]', 'Deuteronomy 30:19', 'vi', true, NOW(), NOW()),
('q-deu-012', 'Deuteronomy', 32, 4, 4, 'easy', 'fill_in_blank',
'Moi-se hat: "Ngai la Von Da, cong viec Ngai tron ___" (Phuc truyen 32:4)',
'[]', '[]', 'Phuc truyen 32:4 - Moi duong loi Ngai la cong binh, Duc Chua Troi thanh tin khong co su gian ta.', '["Cuu Uoc","Moi-se","Tinh Chua"]', 'Deuteronomy 32:4', 'vi', true, NOW(), NOW()),
('q-deu-013', 'Deuteronomy', 33, 27, 27, 'easy', 'multiple_choice_single',
'Phuc truyen 33:27 mo ta Chua nhu the nao?',
'["Noi an nau doi doi, canh tay doi doi o duoi do", "Vua tren ngoi", "Chien binh", "Quan an"]',
'[0]', 'Phuc truyen 33:27 - Duc Chua Troi doi doi la noi an nau nguoi. Canh tay doi doi o duoi do nguoi.', '["Cuu Uoc","An nau","Bao ve"]', 'Deuteronomy 33:27', 'vi', true, NOW(), NOW()),
('q-deu-014', 'Deuteronomy', 34, 5, 7, 'easy', 'multiple_choice_single',
'Moi-se qua doi o tuoi bao nhieu?',
'["120 tuoi", "80 tuoi", "100 tuoi", "150 tuoi"]',
'[0]', 'Phuc truyen 34:7 - Moi-se huong tho 120 tuoi. Mat chua loa, suc chua giam.', '["Cuu Uoc","Moi-se","Cuoc doi"]', 'Deuteronomy 34:5-7', 'vi', true, NOW(), NOW()),
('q-deu-015', 'Deuteronomy', 6, 6, 7, 'medium', 'fill_in_blank',
'Phuc truyen 6:7 day phai noi Loi Chua voi con cai khi nao? (4 luc)',
'[]', '[]', 'Phuc truyen 6:7 - Khi ngoi trong nha, khi di ngoai duong, khi nam va khi dung day. Nghia la moi luc.', '["Cuu Uoc","Giao duc","Gia dinh"]', 'Deuteronomy 6:6-7', 'vi', true, NOW(), NOW());
