-- Supplementary: Romans, 1-2 Corinthians, Galatians, Ephesians, Philippians, Hebrews, James, 1 Peter, 1 John, Revelation

-- ==================== ROMANS ====================
INSERT IGNORE INTO questions (id, book, chapter, verse_start, verse_end, difficulty, type, content, options, correct_answer, explanation, tags, source, language, is_active, created_at, updated_at) VALUES
('q-rom-008', 'Romans', 1, 16, 16, 'easy', 'multiple_choice_single',
'Phao-lô tuyên bố: "Tôi không hổ thẹn về Phúc Âm vì nó là ___ của Đức Chúa Trời để cứu mọi kẻ tin"',
'["Quyền phép (sức mạnh)", "Lời nói", "Kế hoạch", "Tri thức"]',
'[0]', 'Rô-ma 1:16 - Phúc Âm là quyền năng (dunamis) của Chúa để cứu rỗi.', '["Tân Ước","Phúc Âm","Quyền năng"]', 'Romans 1:16', 'vi', true, NOW(), NOW()),
('q-rom-009', 'Romans', 5, 1, 1, 'easy', 'multiple_choice_single',
'Khi được xưng công bình bởi đức tin, chúng ta có ___ với Đức Chúa Trời',
'["Hòa thuận (bình an)", "Chiến tranh", "Khoảng cách", "Nợ nần"]',
'[0]', 'Rô-ma 5:1 - Công bình bởi đức tin mang lại hòa thuận với Chúa. Tội lỗi đã bị xóa.', '["Tân Ước","Công bình","Hòa thuận"]', 'Romans 5:1', 'vi', true, NOW(), NOW()),
('q-rom-010', 'Romans', 5, 3, 4, 'medium', 'multiple_choice_single',
'Rô-ma 5:3-4: Hoạn nạn sinh nhịn nhục, nhịn nhục sinh ___, trải nghiệm sinh hy vọng',
'["Sự trải nghiệm (tính cách)", "Sự vui", "Sự giàu", "Sự mạnh"]',
'[0]', 'Khó khăn là quá trình tạo nên tính cách và hy vọng vững chắc.', '["Tân Ước","Thử thách","Tính cách"]', 'Romans 5:3-4', 'vi', true, NOW(), NOW()),
('q-rom-011', 'Romans', 6, 1, 2, 'medium', 'multiple_choice_single',
'Phao-lô hỏi: Có nên phạm tội để ân điển càng dư thêm không?',
'["Đoán nhiên không! Chúng ta đã chết về tội lỗi", "Có, ân điển dư", "Tùy trường hợp", "Không rõ"]',
'[0]', 'Rô-ma 6:2 - Ân điển không phải cớ để phạm tội. Người tin thật đã chết về tội lỗi.', '["Tân Ước","Ân điển","Thánh khiết"]', 'Romans 6:1-2', 'vi', true, NOW(), NOW()),
('q-rom-013', 'Romans', 8, 31, 31, 'easy', 'multiple_choice_single',
'Rô-ma 8:31: "Nếu Đức Chúa Trời vùng chúng ta thì ai ___ chúng ta?"',
'["Địch", "Giúp", "Biết", "Hiểu"]',
'[0]', 'Nếu Chúa đứng về phía chúng ta, không ai có thể chống lại thành công.', '["Tân Ước","An ninh","Chiến thắng"]', 'Romans 8:31', 'vi', true, NOW(), NOW()),
('q-rom-014', 'Romans', 12, 1, 1, 'medium', 'multiple_choice_single',
'Phao-lô khuyên dâng thân thể làm gì?',
'["Của lễ sống và thánh, đẹp lòng Chúa (sự thờ phượng phải lẽ)", "Của lễ thiêu", "Dụng cụ", "Vũ khí"]',
'[0]', 'Rô-ma 12:1 - Thờ phượng thật là dâng cả cuộc đời cho Chúa, không chỉ trong nhà thờ.', '["Tân Ước","Thờ phượng","Dâng hiến"]', 'Romans 12:1', 'vi', true, NOW(), NOW());

-- ==================== 1 CORINTHIANS ====================
INSERT IGNORE INTO questions (id, book, chapter, verse_start, verse_end, difficulty, type, content, options, correct_answer, explanation, tags, source, language, is_active, created_at, updated_at) VALUES
('q-1co-004', '1 Corinthians', 1, 18, 18, 'medium', 'multiple_choice_single',
'Đạo thập tự giá đối với kẻ hư mất là điên dại nhưng đối với chúng ta là gì?',
'["Quyền phép của Đức Chúa Trời", "Tri thức", "Bí ẩn", "Truyền thống"]',
'[0]', '1 Cô 1:18 - Thập tự giá là sự điên dại theo thế gian nhưng là quyền năng cứu rỗi cho người tin.', '["Tân Ước","Thập tự","Quyền năng"]', '1 Corinthians 1:18', 'vi', true, NOW(), NOW()),
('q-1co-005', '1 Corinthians', 2, 9, 9, 'easy', 'multiple_choice_single',
'1 Cô 2:9: Mắt chưa thấy, tai chưa nghe, lòng chưa nghĩ đến điều gì?',
'["Điều Chúa chuẩn bị cho những ai yêu Ngài", "Thiên đàng", "Phúc Âm", "Phép lạ"]',
'[0]', 'Những điều Chúa chuẩn bị vượt qua trí tưởng tượng của con người.', '["Tân Ước","Hy vọng","Phúc lành"]', '1 Corinthians 2:9', 'vi', true, NOW(), NOW()),
('q-1co-006', '1 Corinthians', 3, 16, 16, 'easy', 'multiple_choice_single',
'1 Cô 3:16: Thân thể chúng ta là gì?',
'["Đền thờ của Đức Thánh Linh", "Dụng cụ của Chúa", "Của lễ", "Bình đất"]',
'[0]', 'Thân thể là đền thờ Thánh Linh ngự. Phải giữ gìn thánh khiết.', '["Tân Ước","Đền thờ","Thánh Linh"]', '1 Corinthians 3:16', 'vi', true, NOW(), NOW()),
('q-1co-008', '1 Corinthians', 9, 24, 24, 'easy', 'multiple_choice_single',
'Phao-lô so sánh đời sống tín đồ với gì?',
'["Cuộc chạy đua, hãy chạy để được giải", "Chiến trận", "Buôn bán", "Làm nông"]',
'[0]', '1 Cô 9:24 - Đời sống đức tin giống cuộc đua: cần kỷ luật và nỗ lực để đạt đích.', '["Tân Ước","Kỷ luật","Cuộc đua"]', '1 Corinthians 9:24', 'vi', true, NOW(), NOW()),
('q-1co-009', '1 Corinthians', 10, 13, 13, 'easy', 'multiple_choice_single',
'1 Cô 10:13 hứa gì về sự cám dỗ?',
'["Chúa không để bị cám dỗ quá sức chịu và luôn cho lối thoát", "Sẽ không có cám dỗ", "Cám dỗ sẽ hết", "Phải tự chịu"]',
'[0]', 'Chúa thành tín: không để cám dỗ quá sức và luôn cung cấp lối thoát.', '["Tân Ước","Cám dỗ","Thành tín"]', '1 Corinthians 10:13', 'vi', true, NOW(), NOW()),
('q-1co-010', '1 Corinthians', 12, 12, 14, 'medium', 'multiple_choice_single',
'Phao-lô so sánh Hội thánh như gì?',
'["Thân thể có nhiều chi thể, mỗi chi thể đều cần thiết", "Quân đội", "Tòa nhà", "Vườn nho"]',
'[0]', '1 Cô 12:12-14 - Mỗi người có ân tứ khác nhau nhưng đều quan trọng như các bộ phận trong thân thể.', '["Tân Ước","Hội thánh","Ân tứ"]', '1 Corinthians 12:12-14', 'vi', true, NOW(), NOW()),
('q-1co-011', '1 Corinthians', 13, 1, 3, 'medium', 'multiple_choice_single',
'Nếu có tài ân tứ nhưng không có tình yêu thương, Phao-lô nói mình như gì?',
'["Đồng vàng kêu hay chập chõe vang", "Người mạnh mẽ", "Thiên sứ", "Học giả"]',
'[0]', '1 Cô 13:1 - Mọi ân tứ đều vô giá trị nếu không có tình yêu thương.', '["Tân Ước","Tình yêu","Ân tứ"]', '1 Corinthians 13:1-3', 'vi', true, NOW(), NOW()),
('q-1co-013', '1 Corinthians', 15, 58, 58, 'easy', 'multiple_choice_single',
'1 Cô 15:58 kết luận: Hãy vững vàng, làm việc Chúa cách dư dẫy vì biết rằng công khó mình trong Chúa sẽ không ___',
'["Vô ích", "Quên", "Mất", "Trễ"]',
'[0]', 'Mọi công khó làm cho Chúa đều có giá trị đời đời, không bao giờ uổng phí.', '["Tân Ước","Làm việc","Hy vọng"]', '1 Corinthians 15:58', 'vi', true, NOW(), NOW()),
('q-1co-014', '1 Corinthians', 10, 31, 31, 'easy', 'multiple_choice_single',
'1 Cô 10:31: Dù ăn uống hay làm gì, hãy làm tất cả vì ___ của Đức Chúa Trời',
'["Sự vinh hiển", "Sự vui", "Lợi ích", "Danh tiếng"]',
'[0]', 'Mọi hành động, dù nhỏ nhất, có thể là hành động tôn vinh Chúa.', '["Tân Ước","Vinh hiển","Đời sống"]', '1 Corinthians 10:31', 'vi', true, NOW(), NOW()),
('q-1co-015', '1 Corinthians', 16, 13, 14, 'easy', 'multiple_choice_single',
'1 Cô 16:13-14 khuyên làm mọi điều trong tình gì?',
'["Yêu thương", "Sợ hãi", "Hy vọng", "Công bình"]',
'[0]', 'Tỉnh giác, vững tin, can đảm, mạnh mẽ - nhưng làm mọi điều trong tình yêu thương.', '["Tân Ước","Yêu thương","Đời sống"]', '1 Corinthians 16:13-14', 'vi', true, NOW(), NOW());

-- ==================== 2 CORINTHIANS ====================
INSERT IGNORE INTO questions (id, book, chapter, verse_start, verse_end, difficulty, type, content, options, correct_answer, explanation, tags, source, language, is_active, created_at, updated_at) VALUES
('q-2co-003', '2 Corinthians', 1, 3, 4, 'easy', 'multiple_choice_single',
'2 Cô 1:3 gọi Chúa là gì?',
'["Cha hay thương xót và Chúa của mọi sự an ủi", "Quan án", "Chiến binh", "Vua"]',
'[0]', 'Chúa an ủi chúng ta để chúng ta có thể an ủi người khác bằng sự an ủi đã nhận.', '["Tân Ước","An ủi","Thương xót"]', '2 Corinthians 1:3-4', 'vi', true, NOW(), NOW()),
('q-2co-004', '2 Corinthians', 3, 17, 17, 'easy', 'multiple_choice_single',
'2 Cô 3:17: "Chúa là Thần; Thần của Chúa ở đâu thì ở đó có sự ___"',
'["Tự do", "Bình an", "Vui mừng", "Quyền năng"]',
'[0]', 'Sự tự do thật đến từ Đức Thánh Linh, không phải từ hoàn cảnh.', '["Tân Ước","Thánh Linh","Tự do"]', '2 Corinthians 3:17', 'vi', true, NOW(), NOW()),
('q-2co-005', '2 Corinthians', 4, 7, 7, 'medium', 'multiple_choice_single',
'2 Cô 4:7: Chúng ta có của quý này (Phúc Âm) trong gì?',
'["Bình đất (chứa yếu đuối)", "Bình vàng", "Hòm sắt", "Túi da"]',
'[0]', 'Để quyền năng tối cao thuộc về Chúa, không phải chúng ta. Sự yếu đuối tôn vinh Chúa.', '["Tân Ước","Yếu đuối","Quyền năng"]', '2 Corinthians 4:7', 'vi', true, NOW(), NOW()),
('q-2co-006', '2 Corinthians', 4, 17, 18, 'easy', 'multiple_choice_single',
'2 Cô 4:17: Hoạn nạn nhẹ và tạm thời sẽ đem lại gì?',
'["Sự vinh hiển đời đời vượt qua mọi so sánh", "Sự thoải mái", "Sự giàu có", "Danh tiếng"]',
'[0]', 'Những khó khăn hiện tại không đáng so với vinh quang mãi sau.', '["Tân Ước","Khó khăn","Vinh hiển"]', '2 Corinthians 4:17-18', 'vi', true, NOW(), NOW()),
('q-2co-008', '2 Corinthians', 5, 20, 20, 'easy', 'multiple_choice_single',
'Phao-lô nói chúng ta là gì cho Chúa?',
'["Sứ giả (đại sứ) thay mặt Chúa", "Đầy tớ", "Linh", "Học trò"]',
'[0]', 'Chúng ta là đại sứ của Chúa trên đất, đại diện Ngài kêu gọi người khác hòa thuận với Chúa.', '["Tân Ước","Làm chứng","Đại sứ"]', '2 Corinthians 5:20', 'vi', true, NOW(), NOW()),
('q-2co-009', '2 Corinthians', 8, 9, 9, 'medium', 'multiple_choice_single',
'2 Cô 8:9: Chúa Giê-su vốn giàu nhưng đã trở nên ___ vì chúng ta',
'["Nghèo", "Yếu", "Nhỏ", "Thường"]',
'[0]', 'Chúa từ bỏ sự giàu có thiên thượng để chúng ta được giàu có thuộc linh.', '["Tân Ước","Ân điển","Hy sinh"]', '2 Corinthians 8:9', 'vi', true, NOW(), NOW()),
('q-2co-010', '2 Corinthians', 9, 7, 7, 'easy', 'multiple_choice_single',
'2 Cô 9:7: Chúa yêu người cho đi như thế nào?',
'["Cách vui lòng", "Nhiều nhất", "Công khai", "Bắt buộc"]',
'[0]', 'Không cho vì bắt buộc hay tiếc nuối. Chúa yêu người cho với tâm lòng vui vẻ.', '["Tân Ước","Dâng hiến","Vui lòng"]', '2 Corinthians 9:7', 'vi', true, NOW(), NOW()),
('q-2co-012', '2 Corinthians', 13, 14, 14, 'easy', 'multiple_choice_single',
'2 Cô 13:14 là lời chúc phước Ba Ngôi nổi tiếng. Ba điều là gì?',
'["Ân điển Chúa Giê-su, tình yêu Đức Chúa Trời, sự thông công Đức Thánh Linh", "Đức tin, hy vọng, yêu thương", "Phúc lành, bình an, vui mừng", "Sức mạnh, khôn ngoan, vinh hiển"]',
'[0]', 'Lời chúc phước Ba Ngôi được dùng rộng rãi trong lễ bái.', '["Tân Ước","Ba Ngôi","Chúc phước"]', '2 Corinthians 13:14', 'vi', true, NOW(), NOW()),
('q-2co-013', '2 Corinthians', 6, 14, 14, 'easy', 'multiple_choice_single',
'2 Cô 6:14: "Chớ mang ___ không cân xứng với kẻ chưa tin"',
'["Ách", "Áo", "Giày", "Nón"]',
'[0]', 'Không kết hợp mật thiết với người không cùng đức tin vì ánh sáng và bóng tối không tương hợp.', '["Tân Ước","Biệt riêng","Mối quan hệ"]', '2 Corinthians 6:14', 'vi', true, NOW(), NOW()),
('q-2co-014', '2 Corinthians', 12, 10, 10, 'medium', 'multiple_choice_single',
'Phao-lô nói: "Khi tôi yếu đuối ấy là khi tôi ___"',
'["Mạnh mẽ", "Buồn", "Mệt", "Sợ"]',
'[0]', 'Nghịch lý Cơ Đốc: yếu đuối là khi Chúa mạnh mẽ qua chúng ta nhất.', '["Tân Ước","Yếu đuối","Sức mạnh"]', '2 Corinthians 12:10', 'vi', true, NOW(), NOW());

-- ==================== GALATIANS ====================
INSERT IGNORE INTO questions (id, book, chapter, verse_start, verse_end, difficulty, type, content, options, correct_answer, explanation, tags, source, language, is_active, created_at, updated_at) VALUES
('q-gal-003', 'Galatians', 3, 28, 28, 'easy', 'multiple_choice_single',
'Ga 3:28: Trong Chúa Giê-su không còn phân biệt gì?',
'["Do-thái hay Hy-lạp, nô lệ hay tự do, nam hay nữ", "Giàu hay nghèo", "Trẻ hay già", "Học hay dốt"]',
'[0]', 'Trong Chúa, mọi người đều bình đẳng và là một trong Chúa Giê-su.', '["Tân Ước","Bình đẳng","Hiệp nhất"]', 'Galatians 3:28', 'vi', true, NOW(), NOW()),
('q-gal-004', 'Galatians', 5, 1, 1, 'easy', 'multiple_choice_single',
'Ga 5:1: Chúa Giê-su giải phóng chúng ta để làm gì?',
'["Được tự do, đừng chịu ách nô lệ nữa", "Làm việc nhiều hơn", "Giữ luật nhiều hơn", "Được giàu có"]',
'[0]', 'Tự do trong Chúa không phải để sống bừa bãi mà để sống cho Chúa và yêu thương.', '["Tân Ước","Tự do","Ân điển"]', 'Galatians 5:1', 'vi', true, NOW(), NOW()),
('q-gal-005', 'Galatians', 5, 16, 17, 'medium', 'multiple_choice_single',
'Ga 5:16-17 nói về sự xung đột giữa điều gì?',
'["Xác thịt và Thánh Linh", "Tốt và xấu", "Cũ và mới", "Lý trí và cảm xúc"]',
'[0]', 'Xác thịt và Thánh Linh chống nhau. Hãy bước đi theo Thánh Linh để không làm theo xác thịt.', '["Tân Ước","Xác thịt","Thánh Linh"]', 'Galatians 5:16-17', 'vi', true, NOW(), NOW()),
('q-gal-007', 'Galatians', 6, 7, 7, 'easy', 'multiple_choice_single',
'Ga 6:7: "Chúa không chịu nhạo báng đâu; vì ai gieo gì thì sẽ ___"',
'["Gặt nấy", "Được nấy", "Thất nấy", "Mất nấy"]',
'[0]', 'Luật gieo gặt: hành động có hậu quả. Gieo theo xác thịt gặt hư nát, gieo theo Thánh Linh gặt sự sống.', '["Tân Ước","Gieo gặt","Hậu quả"]', 'Galatians 6:7', 'vi', true, NOW(), NOW()),
('q-gal-008', 'Galatians', 6, 9, 9, 'easy', 'multiple_choice_single',
'Ga 6:9: "Chúng ta đừng ___ làm lành vì sẽ gặt nếu không nản lòng"',
'["Mệt nhọc (nản)", "Vui vẻ", "Nhanh", "Chậm"]',
'[0]', 'Làm lành cần kiên nhẫn. Mùa gặt sẽ đến vào đúng thời điểm.', '["Tân Ước","Kiên nhẫn","Làm lành"]', 'Galatians 6:9', 'vi', true, NOW(), NOW()),
('q-gal-009', 'Galatians', 3, 13, 13, 'hard', 'multiple_choice_single',
'Ga 3:13: Chúa Giê-su chuộc chúng ta khỏi sự rủa sả của luật pháp bằng cách nào?',
'["Trở nên sự rủa sả vì chúng ta (bị treo trên cây)", "Hủy bỏ luật", "Đổi luật", "Giữ luật thay"]',
'[0]', 'Chúa Giê-su gánh chịu hình phạt của luật pháp thay cho chúng ta.', '["Tân Ước","Cứu chuộc","Luật pháp"]', 'Galatians 3:13', 'vi', true, NOW(), NOW()),
('q-gal-010', 'Galatians', 4, 4, 5, 'medium', 'multiple_choice_single',
'Ga 4:4: Khi kỳ hạn đã được trọn, Chúa sai Con Ngài đến thế gian để làm gì?',
'["Chuộc những kẻ dưới quyền luật pháp để chúng ta được làm con nuôi", "Làm vua", "Phán xét", "Dạy dỗ"]',
'[0]', 'Chúa Giê-su đến đúng thời điểm để chuộc tội và ban cho chúng ta địa vị con cái Chúa.', '["Tân Ước","Nhập thể","Con nuôi"]', 'Galatians 4:4-5', 'vi', true, NOW(), NOW()),
('q-gal-012', 'Galatians', 5, 24, 24, 'medium', 'multiple_choice_single',
'Ga 5:24: Những kẻ thuộc về Chúa Giê-su đã làm gì với xác thịt?',
'["Đã đóng đinh xác thịt với dục dâm và mê tham trên thập tự giá", "Bỏ qua", "Ẩn giấu", "Từ chối"]',
'[0]', 'Đóng đinh xác thịt = quyết định dứt khoát từ bỏ đời sống theo xác thịt.', '["Tân Ước","Xác thịt","Thánh khiết"]', 'Galatians 5:24', 'vi', true, NOW(), NOW()),
('q-gal-013', 'Galatians', 1, 6, 7, 'easy', 'multiple_choice_single',
'Phao-lô kinh ngạc vì Hội thánh Ga-la-ti làm gì?',
'["Nhanh chóng bỏ Phúc Âm thật để theo phúc âm khác", "Phạm tội", "Bỏ nhà thờ", "Không cầu nguyện"]',
'[0]', 'Chỉ có một Phúc Âm thật. Bất cứ sự thay đổi nào đều là đi lạc.', '["Tân Ước","Phúc Âm","Cảnh báo"]', 'Galatians 1:6-7', 'vi', true, NOW(), NOW()),
('q-gal-014', 'Galatians', 3, 11, 11, 'easy', 'multiple_choice_single',
'Ga 3:11: "Không ai được xưng công bình trước Chúa bởi ___ ấy là điều hiển nhiên"',
'["Luật pháp", "Việc làm", "Tri thức", "Tôn giáo"]',
'[0]', 'Sự công bình đến bởi đức tin, không phải bởi giữ luật pháp.', '["Tân Ước","Công bình","Đức tin"]', 'Galatians 3:11', 'vi', true, NOW(), NOW());

-- ==================== EPHESIANS ====================
INSERT IGNORE INTO questions (id, book, chapter, verse_start, verse_end, difficulty, type, content, options, correct_answer, explanation, tags, source, language, is_active, created_at, updated_at) VALUES
('q-eph-003', 'Ephesians', 1, 3, 3, 'easy', 'multiple_choice_single',
'Ê-phê 1:3: Chúa đã ban cho chúng ta mọi phúc lành gì?',
'["Mọi phúc lành thuộc linh ở các nơi trên trời", "Phúc lành vật chất", "Phúc lành sức khỏe", "Phúc lành tài chính"]',
'[0]', 'Phúc lành Chúa ban là thuộc linh và đời đời, không chỉ vật chất.', '["Tân Ước","Phúc lành","Thuộc linh"]', 'Ephesians 1:3', 'vi', true, NOW(), NOW()),
('q-eph-004', 'Ephesians', 2, 10, 10, 'easy', 'multiple_choice_single',
'Ê-phê 2:10: Chúng ta là tác phẩm của Chúa, được tạo dựng trong Chúa Giê-su để làm gì?',
'["Việc lành mà Chúa đã chuẩn bị trước", "Giữ luật pháp", "Được cứu", "Được nghỉ ngơi"]',
'[0]', 'Được cứu không bởi việc làm nhưng ĐƯỢC CỨU ĐỂ làm việc lành.', '["Tân Ước","Mục đích","Việc lành"]', 'Ephesians 2:10', 'vi', true, NOW(), NOW()),
('q-eph-006', 'Ephesians', 4, 2, 3, 'easy', 'multiple_choice_single',
'Ê-phê 4:2-3 khuyên sống với nhau thế nào?',
'["Khiêm nhường, mềm mại, nhịn nhục, lấy tình yêu nhường nhịn nhau", "Cạnh tranh", "Độc lập", "Lý trí"]',
'[0]', 'Giữ gìn sự hiệp nhất của Thánh Linh bằng mối liên kết bình an.', '["Tân Ước","Hiệp nhất","Khiêm nhường"]', 'Ephesians 4:2-3', 'vi', true, NOW(), NOW()),
('q-eph-007', 'Ephesians', 4, 26, 26, 'easy', 'multiple_choice_single',
'Ê-phê 4:26: "Nếu giận thì chớ ___, đừng để mặt trời lặn khi còn đang giận"',
'["Phạm tội", "Nói", "Làm", "Nghĩ"]',
'[0]', 'Có thể giận nhưng đừng để cơn giận dẫn đến tội lỗi. Giải quyết trước khi hết ngày.', '["Tân Ước","Cơn giận","Đời sống"]', 'Ephesians 4:26', 'vi', true, NOW(), NOW()),
('q-eph-008', 'Ephesians', 4, 32, 32, 'easy', 'multiple_choice_single',
'Ê-phê 4:32: Hãy ở với nhau như thế nào?',
'["Nhân từ, đánh đải thương xót, tha thứ như Chúa đã tha thứ anh em", "Công bình", "Nghiêm khắc", "Lạnh đạm"]',
'[0]', 'Tha thứ cho người khác vì Chúa đã tha thứ cho chúng ta. Tha thứ là bản sao của ân điển.', '["Tân Ước","Tha thứ","Nhân từ"]', 'Ephesians 4:32', 'vi', true, NOW(), NOW()),
('q-eph-009', 'Ephesians', 5, 25, 25, 'medium', 'multiple_choice_single',
'Ê-phê 5:25: Người chồng phải yêu vợ như ai?',
'["Như Chúa Giê-su yêu Hội thánh và phối mình vì Hội thánh", "Như yêu bản thân", "Như yêu cha mẹ", "Như yêu con cái"]',
'[0]', 'Tình yêu hôn nhân theo khuôn mẫu Chúa hy sinh vì Hội thánh. Yêu là cho đi không phải nhận.', '["Tân Ước","Hôn nhân","Hy sinh"]', 'Ephesians 5:25', 'vi', true, NOW(), NOW()),
('q-eph-011', 'Ephesians', 6, 12, 12, 'medium', 'multiple_choice_single',
'Ê-phê 6:12: Chúng ta chiến đấu không phải với thịt và huyết nhưng với ai?',
'["Các thế lực, các quyền binh, các chúa tể bóng tối", "Con người", "Chính phủ", "Bạn bè"]',
'[0]', 'Chiến trận thật sự là thuộc linh, chống lại thế lực tối tăm, không phải con người.', '["Tân Ước","Chiến trận","Thế lực tối"]', 'Ephesians 6:12', 'vi', true, NOW(), NOW()),
('q-eph-012', 'Ephesians', 6, 14, 17, 'easy', 'multiple_choice_single',
'Khi giới toàn thân của Chúa gồm những gì?',
'["Đai lưng lẽ thật, áo giáp công bình, giày Phúc Âm, khiên đức tin, mũ cứu rỗi, gươm Thánh Linh", "Chỉ có gươm", "Chỉ có khiên", "Chỉ có mũ"]',
'[0]', '6 món khí giới thuộc linh bảo vệ và tấn công. Lời Chúa là vũ khí tấn công duy nhất.', '["Tân Ước","Khí giới","Chiến trận"]', 'Ephesians 6:14-17', 'vi', true, NOW(), NOW()),
('q-eph-013', 'Ephesians', 6, 18, 18, 'easy', 'multiple_choice_single',
'Ê-phê 6:18 khuyên cầu nguyện như thế nào?',
'["Mọi lúc với mọi thứ cầu nguyện và nài xin bởi Đức Thánh Linh", "Chỉ buổi sáng", "Chỉ khi gặp khó", "Chỉ ở nhà thờ"]',
'[0]', 'Cầu nguyện là vũ khí thuộc linh cần sử dụng liên tục, không chỉ lúc gặp nạn.', '["Tân Ước","Cầu nguyện","Thánh Linh"]', 'Ephesians 6:18', 'vi', true, NOW(), NOW()),
('q-eph-015', 'Ephesians', 5, 18, 19, 'easy', 'multiple_choice_single',
'Ê-phê 5:18: Đừng say rượu nhưng hãy đầy dẫy điều gì?',
'["Đức Thánh Linh", "Tri thức", "Vui vẻ", "Lời Chúa"]',
'[0]', 'Đầy dẫy Thánh Linh thay vì say rượu. Thánh Linh mang lại sự vui mừng, hát xướng và tạ ơn.', '["Tân Ước","Thánh Linh","Đầy dẫy"]', 'Ephesians 5:18-19', 'vi', true, NOW(), NOW());

-- ==================== PHILIPPIANS ====================
INSERT IGNORE INTO questions (id, book, chapter, verse_start, verse_end, difficulty, type, content, options, correct_answer, explanation, tags, source, language, is_active, created_at, updated_at) VALUES
('q-phi-003', 'Philippians', 1, 6, 6, 'easy', 'multiple_choice_single',
'Phi 1:6: Đấng nào đã khởi làm việc lành trong anh em sẽ làm cho trọn?',
'["Chính Đức Chúa Trời", "Chính bản thân", "Mục sư", "Hội thánh"]',
'[0]', 'Chúa bắt đầu và sẽ hoàn tất. Sự cứu rỗi là việc của Chúa từ đầu đến cuối.', '["Tân Ước","An ninh","Thành tín"]', 'Philippians 1:6', 'vi', true, NOW(), NOW()),
('q-phi-004', 'Philippians', 1, 21, 21, 'medium', 'multiple_choice_single',
'Phao-lô nói: "Đối với tôi, sống là ___ và chết là lợi"',
'["Chúa Giê-su", "Phục vụ", "Chiến đấu", "Học hỏi"]',
'[0]', 'Sống = Chúa Giê-su (mục đích); chết = lợi (về với Chúa). Cả hai đều tốt!', '["Tân Ước","Phao-lô","Mục đích"]', 'Philippians 1:21', 'vi', true, NOW(), NOW()),
('q-phi-005', 'Philippians', 2, 3, 4, 'easy', 'multiple_choice_single',
'Phi 2:3: Hãy coi người khác như thế nào?',
'["Tốt hơn mình", "Bằng mình", "Kém hơn mình", "Không quan tâm"]',
'[0]', 'Khiêm nhường: coi người khác hơn mình, không chỉ lo cho riêng mình.', '["Tân Ước","Khiêm nhường","Mối quan hệ"]', 'Philippians 2:3-4', 'vi', true, NOW(), NOW()),
('q-phi-006', 'Philippians', 2, 5, 8, 'hard', 'multiple_choice_single',
'Phi 2:5-8 mô tả Chúa Giê-su làm gì dù vốn có hình Đức Chúa Trời?',
'["Tự bỏ mình, lấy hình tôi tớ, chịu chết trên thập tự", "Làm vua", "Phán xét", "Chiến thắng"]',
'[0]', 'Kenosis (tự bỏ mình): Chúa Giê-su từ bỏ địa vị để phục vụ và hy sinh. Khuôn mẫu khiêm nhường.', '["Tân Ước","Nhập thể","Khiêm nhường"]', 'Philippians 2:5-8', 'vi', true, NOW(), NOW()),
('q-phi-007', 'Philippians', 2, 9, 11, 'easy', 'multiple_choice_single',
'Vì sự khiêm nhường, Chúa nâng Chúa Giê-su lên và ban danh trên mọi danh. Mọi đầu gối sẽ ___',
'["Quỳ xuống và mọi lưỡi tuyên xưng Giê-su là Chúa", "Đứng dậy", "Im lặng", "Sợ hãi"]',
'[0]', 'Mọi sinh vật sẽ nhận biết Chúa Giê-su là Chúa vì vinh hiển Đức Chúa Cha.', '["Tân Ước","Giê-su","Tôn cao"]', 'Philippians 2:9-11', 'vi', true, NOW(), NOW()),
('q-phi-009', 'Philippians', 3, 8, 8, 'medium', 'multiple_choice_single',
'Phao-lô coi mọi thứ như gì so với sự nhận biết Chúa Giê-su?',
'["Như rác rưởi (sự lỗ)", "Như vàng", "Như quý", "Như thường"]',
'[0]', 'Phi 3:8 - Mọi thứ trên đời không gì sánh được với sự nhận biết Chúa Giê-su.', '["Tân Ước","Phao-lô","Giá trị"]', 'Philippians 3:8', 'vi', true, NOW(), NOW()),
('q-phi-010', 'Philippians', 3, 13, 14, 'easy', 'multiple_choice_single',
'Phao-lô nói ông làm một điều: quên sự ở đằng sau và vươn tới sự ở đằng trước để được gì?',
'["Giải thưởng của sự kêu gọi trên trời", "Vinh quang trên đất", "Sự khen ngợi", "Chức vụ lớn hơn"]',
'[0]', 'Đừng mắc kẹt ở quá khứ, hãy tiến về phía trước hướng về giải thưởng.', '["Tân Ước","Tiến tới","Mục tiêu"]', 'Philippians 3:13-14', 'vi', true, NOW(), NOW()),
('q-phi-012', 'Philippians', 4, 7, 7, 'easy', 'multiple_choice_single',
'Phi 4:7: Sự bình an của Chúa vượt qua mọi điều gì?',
'["Mọi sự hiểu biết (trí khôn)", "Mọi vấn đề", "Mọi cảm xúc", "Mọi khó khăn"]',
'[0]', 'Sự bình an của Chúa không thể giải thích bằng lý trí, nó giữ gìn lòng và trí chúng ta.', '["Tân Ước","Bình an","Cầu nguyện"]', 'Philippians 4:7', 'vi', true, NOW(), NOW()),
('q-phi-013', 'Philippians', 4, 8, 8, 'easy', 'multiple_choice_single',
'Phi 4:8 khuyên suy nghĩ về những điều nào?',
'["Thật, tôn trọng, công bình, tinh sạch, đáng yêu, có tiếng tốt", "Bất cứ điều gì", "Chỉ điều vui", "Chỉ điều lớn"]',
'[0]', 'Kiểm soát suy nghĩ bằng cách tập trung vào những điều tốt đẹp của Chúa.', '["Tân Ước","Suy nghĩ","Đời sống"]', 'Philippians 4:8', 'vi', true, NOW(), NOW()),
('q-phi-014', 'Philippians', 4, 11, 12, 'medium', 'multiple_choice_single',
'Phao-lô nói ông đã học được điều gì?',
'["Thỏa lòng trong mọi hoàn cảnh, dù dư dật hay thiếu thốn", "Cách làm giàu", "Cách thoát khổ", "Cách lãnh đạo"]',
'[0]', 'Sự thỏa lòng (contentment) không phụ thuộc hoàn cảnh mà phụ thuộc Chúa.', '["Tân Ước","Thỏa lòng","Phao-lô"]', 'Philippians 4:11-12', 'vi', true, NOW(), NOW());

-- ==================== HEBREWS, JAMES, 1 PETER, 1 JOHN, REVELATION ====================

-- HEBREWS
INSERT IGNORE INTO questions (id, book, chapter, verse_start, verse_end, difficulty, type, content, options, correct_answer, explanation, tags, source, language, is_active, created_at, updated_at) VALUES
('q-heb-004', 'Hebrews', 4, 12, 12, 'easy', 'multiple_choice_single',
'Hê 4:12 mô tả Lời Chúa như gì?',
'["Sống và linh nghiệm, sắc hơn gươm hai lưỡi", "Cuốn sách", "Luật pháp", "Truyền thống"]',
'[0]', 'Lời Chúa sống động, xuyên thấu tâm lòng, phân biệt tư tưởng và ý định.', '["Tân Ước","Lời Chúa","Quyền năng"]', 'Hebrews 4:12', 'vi', true, NOW(), NOW()),
('q-heb-005', 'Hebrews', 4, 15, 16, 'medium', 'multiple_choice_single',
'Hê 4:15: Chúa Giê-su là Thầy Tế Lễ Thượng Phẩm như thế nào?',
'["Bị cám dỗ mọi mặt như chúng ta nhưng không phạm tội", "Không bao giờ bị cám dỗ", "Không hiểu nỗi đau", "Chỉ là Chúa"]',
'[0]', 'Chúa Giê-su hiểu sự yếu đuối của chúng ta vì đã trải qua mọi thứ. Nên hãy mạnh dạn đến ngôi ân điển.', '["Tân Ước","Tế Lễ","Cảm thông"]', 'Hebrews 4:15-16', 'vi', true, NOW(), NOW()),
('q-heb-007', 'Hebrews', 11, 8, 10, 'easy', 'multiple_choice_single',
'Hê 11:8: Áp-ra-ham bởi đức tin làm gì khi được gọi?',
'["Vâng lời đi mà không biết mình đi đâu", "Từ chối", "Hỏi tại sao", "Chuẩn bị kỹ"]',
'[0]', 'Đức tin là vâng lời dù không thấy đích đến. Áp-ra-ham là gương mẫu đức tin.', '["Tân Ước","Đức tin","Vâng lời"]', 'Hebrews 11:8-10', 'vi', true, NOW(), NOW()),
('q-heb-008', 'Hebrews', 12, 6, 6, 'easy', 'multiple_choice_single',
'Hê 12:6: Chúa sửa phạt ai?',
'["Con cái mà Ngài yêu thương", "Kẻ thù", "Kẻ ác", "Người lạ"]',
'[0]', 'Sự sửa phạt là dấu hiệu tình yêu của Cha, không phải sự bỏ rơi.', '["Tân Ước","Sửa phạt","Tình yêu"]', 'Hebrews 12:6', 'vi', true, NOW(), NOW()),
('q-heb-010', 'Hebrews', 13, 5, 5, 'easy', 'multiple_choice_single',
'Hê 13:5: Chúa hứa gì về sự hiện diện của Ngài?',
'["Ta sẽ không bỏ con, không hề lìa con", "Ta sẽ ban phúc", "Ta sẽ trả thù", "Ta sẽ đổi"]',
'[0]', 'Chúa luôn ở với chúng ta. Không bao giờ bỏ rơi. Nên thỏa lòng với những gì có.', '["Tân Ước","Sự hiện diện","An ninh"]', 'Hebrews 13:5', 'vi', true, NOW(), NOW()),
('q-heb-011', 'Hebrews', 13, 8, 8, 'easy', 'multiple_choice_single',
'Hê 13:8: Chúa Giê-su Christ hôm qua ngày nay và cho đến đời đời đều như thế nào?',
'["Không thay đổi", "Thay đổi theo thời đại", "Mạnh hơn", "Khôn ngoan hơn"]',
'[0]', 'Chúa Giê-su bất biến. Ngài giống hôm qua, hôm nay và mãi mãi.', '["Tân Ước","Giê-su","Bất biến"]', 'Hebrews 13:8', 'vi', true, NOW(), NOW()),
('q-heb-013', 'Hebrews', 9, 22, 22, 'hard', 'multiple_choice_single',
'Hê 9:22: Theo luật pháp, không có ___ thì không có sự tha tội',
'["Sự đổ huyết (huyết)", "Cầu nguyện", "Của lễ", "Ăn năn"]',
'[0]', 'Nguyên tắc cốt lõi: tha tội cần huyết. Huyết Chúa Giê-su là của lễ cuối cùng và trọn vẹn nhất.', '["Tân Ước","Cứu chuộc","Huyết"]', 'Hebrews 9:22', 'vi', true, NOW(), NOW()),
('q-heb-014', 'Hebrews', 11, 3, 3, 'medium', 'multiple_choice_single',
'Hê 11:3: Bởi đức tin chúng ta hiểu rằng thế giới được dựng nên bởi gì?',
'["Lời phán của Đức Chúa Trời", "Vụ nổ lớn", "Tự nhiên", "Các thần"]',
'[0]', 'Đức tin chấp nhận Chúa sáng tạo vũ trụ bằng Lời Ngài từ hư vô.', '["Tân Ước","Đức tin","Sáng tạo"]', 'Hebrews 11:3', 'vi', true, NOW(), NOW()),
('q-heb-015', 'Hebrews', 10, 23, 23, 'easy', 'multiple_choice_single',
'Hê 10:23: Hãy giữ vững sự tuyên xưng về sự trông đợi vì Đấng đã hứa là gì?',
'["Thành tín", "Mạnh mẽ", "Khôn ngoan", "Giàu có"]',
'[0]', 'Chúa thành tín giữ lời hứa nên chúng ta có thể vững lòng tuyên xưng đức tin.', '["Tân Ước","Thành tín","Trông đợi"]', 'Hebrews 10:23', 'vi', true, NOW(), NOW());

-- JAMES
INSERT IGNORE INTO questions (id, book, chapter, verse_start, verse_end, difficulty, type, content, options, correct_answer, explanation, tags, source, language, is_active, created_at, updated_at) VALUES
('q-jam-003', 'James', 1, 5, 5, 'easy', 'multiple_choice_single',
'Gia-cơ 1:5: Nếu ai thiếu khôn ngoan, hãy làm gì?',
'["Cầu xin Chúa vì Ngài ban rộng rãi cho mọi người", "Học nhiều hơn", "Hỏi người khác", "Đọc sách"]',
'[0]', 'Chúa ban khôn ngoan rộng rãi và không trách móc. Chỉ cần xin!', '["Tân Ước","Khôn ngoan","Cầu nguyện"]', 'James 1:5', 'vi', true, NOW(), NOW()),
('q-jam-005', 'James', 1, 19, 20, 'easy', 'multiple_choice_single',
'Gia-cơ 1:19: Mọi người phải như thế nào?',
'["Mau nghe, chậm nói, chậm giận", "Mau nói, chậm nghe", "Nói nhiều", "Im lặng"]',
'[0]', 'Lắng nghe trước khi nói và kiềm chế cơn giận. Khôn ngoan thực tế.', '["Tân Ước","Khôn ngoan","Lời nói"]', 'James 1:19-20', 'vi', true, NOW(), NOW()),
('q-jam-006', 'James', 1, 22, 22, 'easy', 'multiple_choice_single',
'Gia-cơ 1:22: Hãy làm gì với Lời Chúa?',
'["Làm theo, không chỉ nghe suông", "Chỉ đọc", "Chỉ nghe", "Chỉ học thuộc"]',
'[0]', 'Nghe Lời Chúa mà không làm là tự lừa mình. Đức tin cần hành động.', '["Tân Ước","Lời Chúa","Hành động"]', 'James 1:22', 'vi', true, NOW(), NOW()),
('q-jam-007', 'James', 3, 5, 6, 'easy', 'multiple_choice_single',
'Gia-cơ 3 so sánh cái lưỡi với gì?',
'["Ngọn lửa nhỏ đốt cháy rừng lớn", "Gươm", "Chìa khóa", "Con rắn"]',
'[0]', 'Cái lưỡi nhỏ nhưng có thể gây hại lớn. Cần kiểm soát lời nói.', '["Tân Ước","Lời nói","Lưỡi"]', 'James 3:5-6', 'vi', true, NOW(), NOW()),
('q-jam-008', 'James', 4, 7, 8, 'easy', 'multiple_choice_single',
'Gia-cơ 4:7: Hãy chống trả ma quỷ thì nó sẽ ___',
'["Trốn xa anh em", "Mạnh hơn", "Quay lại", "Ẩn náu"]',
'[0]', 'Phải chống cự chủ động nhưng buông. Và đến gần Chúa thì Ngài đến gần anh em.', '["Tân Ước","Chiến trận","Chống trả"]', 'James 4:7-8', 'vi', true, NOW(), NOW()),
('q-jam-010', 'James', 4, 10, 10, 'easy', 'multiple_choice_single',
'Gia-cơ 4:10: Hãy tự hạ mình trước mặt Chúa thì Ngài sẽ ___',
'["Nhắc anh em lên", "Tha thứ", "Phạt", "Đổi"]',
'[0]', 'Khiêm nhường trước Chúa dẫn đến sự nâng đỡ từ Ngài.', '["Tân Ước","Khiêm nhường","Cất nhắc"]', 'James 4:10', 'vi', true, NOW(), NOW()),
('q-jam-011', 'James', 5, 13, 14, 'easy', 'multiple_choice_single',
'Gia-cơ 5:13: Khi gặp khó, hãy làm gì? Khi vui, hãy làm gì?',
'["Khó: cầu nguyện. Vui: hát ngợi khen", "Khó: im lặng. Vui: ăn tiệc", "Khó: khóc. Vui: cười", "Khó: ngủ. Vui: chạy"]',
'[0]', 'Mọi cảm xúc đều có thể trình lên Chúa: khó khăn bằng cầu nguyện, vui mừng bằng ngợi khen.', '["Tân Ước","Cầu nguyện","Cảm xúc"]', 'James 5:13-14', 'vi', true, NOW(), NOW()),
('q-jam-012', 'James', 5, 16, 16, 'easy', 'multiple_choice_single',
'Gia-cơ 5:16: "Lời cầu nguyện của người ___ có quyền năng lớn"',
'["Công bình", "Giàu có", "Học thức", "Có chức vụ"]',
'[0]', 'Quyền năng cầu nguyện không dựa trên chức vụ mà dựa trên đời sống công bình.', '["Tân Ước","Cầu nguyện","Công bình"]', 'James 5:16', 'vi', true, NOW(), NOW()),
('q-jam-014', 'James', 3, 17, 17, 'medium', 'multiple_choice_single',
'Sự khôn ngoan từ trên có đặc điểm gì?',
'["Thanh sạch, hòa thuận, mềm mại, đủ tình thương xót", "Lý trí", "Sắc bén", "Cứng rắn"]',
'[0]', 'Gia-cơ 3:17 - Khôn ngoan từ Chúa khác với khôn ngoan thế gian. Đặc điểm là hòa bình và nhân từ.', '["Tân Ước","Khôn ngoan","Hòa thuận"]', 'James 3:17', 'vi', true, NOW(), NOW()),
('q-jam-015', 'James', 4, 14, 14, 'easy', 'multiple_choice_single',
'Gia-cơ 4:14 so sánh cuộc đời như gì?',
'["Hơi nước hiện ra rồi biến mất", "Dòng sông", "Ngọn núi", "Cây lớn"]',
'[0]', 'Cuộc đời ngắn ngủi như hơi nước. Hãy sống có ý nghĩa và theo ý Chúa.', '["Tân Ước","Cuộc đời","Ngắn ngủi"]', 'James 4:14', 'vi', true, NOW(), NOW());

-- 1 PETER
INSERT IGNORE INTO questions (id, book, chapter, verse_start, verse_end, difficulty, type, content, options, correct_answer, explanation, tags, source, language, is_active, created_at, updated_at) VALUES
('q-1pe-002', '1 Peter', 1, 3, 4, 'easy', 'multiple_choice_single',
'1 Phi 1:3-4: Sự tái sinh ban cho chúng ta sản nghiệp gì?',
'["Sản nghiệp không hư nát, không ô uế, không suy tàn, giữ ở trên trời", "Đất đai", "Vàng bạc", "Quyền lực"]',
'[0]', 'Sản nghiệp đời đời được giữ trên trời, không bị mất hay hư hỏng.', '["Tân Ước","Hy vọng","Sản nghiệp"]', '1 Peter 1:3-4', 'vi', true, NOW(), NOW()),
('q-1pe-003', '1 Peter', 1, 6, 7, 'medium', 'multiple_choice_single',
'1 Phi 1:7: Thử thách đức tin được so sánh với gì?',
'["Vàng được thử lửa (làm tinh sạch)", "Kim cương", "Sắt thép", "Đá quý"]',
'[0]', 'Như vàng được luyện trong lửa, đức tin được làm tinh sạch qua thử thách.', '["Tân Ước","Thử thách","Đức tin"]', '1 Peter 1:6-7', 'vi', true, NOW(), NOW()),
('q-1pe-004', '1 Peter', 2, 9, 9, 'easy', 'multiple_choice_single',
'1 Phi 2:9: Tín đồ được gọi là gì?',
'["Dòng giống được chọn, chức tế lễ nhà vua, dân thánh, dân thuộc riêng", "Dân thường", "Tôi tớ", "Khách lạ"]',
'[0]', 'Mọi tín đồ có địa vị cao quý trong Chúa: vua và thầy tế lễ.', '["Tân Ước","Địa vị","Dân Chúa"]', '1 Peter 2:9', 'vi', true, NOW(), NOW()),
('q-1pe-006', '1 Peter', 3, 15, 15, 'easy', 'multiple_choice_single',
'1 Phi 3:15: Hãy luôn sẵn sàng làm gì?',
'["Trả lời cho mọi người hỏi về sự trông đợi của anh em", "Chiến đấu", "Báo thù", "Trốn chạy"]',
'[0]', 'Sẵn sàng giải thích đức tin cách hiền lành và tôn kính.', '["Tân Ước","Làm chứng","Sẵn sàng"]', '1 Peter 3:15', 'vi', true, NOW(), NOW()),
('q-1pe-007', '1 Peter', 4, 8, 8, 'easy', 'multiple_choice_single',
'1 Phi 4:8: "Trước hết hãy có lòng ___ sống động vì tình yêu phủ lấp nhiều tội"',
'["Yêu thương nhau", "Vâng lời", "Cầu nguyện", "Kiêng ăn"]',
'[0]', 'Tình yêu thương là điều ưu tiên hàng đầu trong mọi quan hệ.', '["Tân Ước","Yêu thương","Ưu tiên"]', '1 Peter 4:8', 'vi', true, NOW(), NOW()),
('q-1pe-008', '1 Peter', 4, 12, 13, 'medium', 'multiple_choice_single',
'1 Phi 4:12: Khi gặp hoạn nạn vì Chúa, hãy làm gì?',
'["Hãy vui mừng vì được dự phần đau khổ của Chúa", "Buồn rầu", "Bỏ cuộc", "Giận dữ"]',
'[0]', 'Chịu khổ vì Chúa là đặc ân, không phải bất hạnh. Khi Ngài hiện ra sẽ được vui mừng.', '["Tân Ước","Hoạn nạn","Vui mừng"]', '1 Peter 4:12-13', 'vi', true, NOW(), NOW()),
('q-1pe-010', '1 Peter', 5, 8, 8, 'easy', 'multiple_choice_single',
'1 Phi 5:8 mô tả ma quỷ như gì?',
'["Sư tử rống, tìm tham nuốt người", "Con rắn", "Bóng tối", "Gió bão"]',
'[0]', 'Hãy tỉnh giác và cảnh giác vì kẻ thù đang tìm cách phá hủy.', '["Tân Ước","Ma quỷ","Cảnh giác"]', '1 Peter 5:8', 'vi', true, NOW(), NOW()),
('q-1pe-011', '1 Peter', 2, 2, 2, 'easy', 'multiple_choice_single',
'1 Phi 2:2: Như trẻ sơ sinh, hãy thèm ___ thuộc linh để lớn lên',
'["Sữa tinh (Lời Chúa)", "Bánh", "Nước", "Thịt"]',
'[0]', 'Lời Chúa là thức ăn thiết yếu để lớn lên thuộc linh, như sữa cho trẻ sơ sinh.', '["Tân Ước","Lời Chúa","Trưởng thành"]', '1 Peter 2:2', 'vi', true, NOW(), NOW()),
('q-1pe-013', '1 Peter', 3, 3, 4, 'easy', 'multiple_choice_single',
'1 Phi 3:3-4: Vẻ đẹp thật của phụ nữ nằm ở đâu?',
'["Người bề trong của lòng: tâm linh dịu dàng và yên lặng", "Trang sức", "Y phục", "Tóc"]',
'[0]', 'Vẻ đẹp bên trong (tâm linh) quý giá trước mặt Chúa hơn vẻ bên ngoài.', '["Tân Ước","Vẻ đẹp","Tâm linh"]', '1 Peter 3:3-4', 'vi', true, NOW(), NOW()),
('q-1pe-014', '1 Peter', 2, 11, 11, 'easy', 'multiple_choice_single',
'1 Phi 2:11 gọi tín đồ là gì trên đất?',
'["Khách lạ và kiều cư (lướt qua)", "Công dân", "Chủ nhân", "Quan án"]',
'[0]', 'Chúng ta là khách trú trên đất, quê hương thật ở trên trời.', '["Tân Ước","Khách lạ","Thế gian"]', '1 Peter 2:11', 'vi', true, NOW(), NOW()),
('q-1pe-015', '1 Peter', 5, 10, 10, 'easy', 'multiple_choice_single',
'1 Phi 5:10: Sau khi chịu khổ ít lâu, Chúa sẽ làm gì cho anh em?',
'["Chỉnh đốn, làm cho vững, thêm sức, đứng trên nền vững", "Để mặc", "Đổi thay", "Phạt thêm"]',
'[0]', 'Khó khăn là tạm thời. Chúa sẽ phục hồi, làm cho vững và tăng sức cho chúng ta.', '["Tân Ước","Phục hồi","Hy vọng"]', '1 Peter 5:10', 'vi', true, NOW(), NOW());

-- 1 JOHN
INSERT IGNORE INTO questions (id, book, chapter, verse_start, verse_end, difficulty, type, content, options, correct_answer, explanation, tags, source, language, is_active, created_at, updated_at) VALUES
('q-1jo-003', '1 John', 1, 7, 7, 'easy', 'multiple_choice_single',
'1 Giăng 1:7: Nếu chúng ta bước đi trong sự sáng thì huyết Chúa Giê-su làm gì?',
'["Tẩy sạch mọi tội lỗi chúng ta", "Bảo vệ chúng ta", "Chữa lành chúng ta", "An ủi chúng ta"]',
'[0]', 'Bước đi trong sự sáng + huyết Chúa = sự tẩy sạch liên tục khỏi tội lỗi.', '["Tân Ước","Tẩy sạch","Huyết"]', '1 John 1:7', 'vi', true, NOW(), NOW()),
('q-1jo-004', '1 John', 2, 1, 2, 'easy', 'multiple_choice_single',
'1 Giăng 2:1-2: Khi phạm tội, ai là Đấng bào chữa cho chúng ta?',
'["Chúa Giê-su Christ, Đấng công bình", "Thiên sứ", "Môi-se", "Phi-e-rô"]',
'[0]', 'Chúa Giê-su là luật sư bào chữa và cũng là của lễ chuộc tội cho chúng ta.', '["Tân Ước","Bào chữa","Chuộc tội"]', '1 John 2:1-2', 'vi', true, NOW(), NOW()),
('q-1jo-005', '1 John', 2, 15, 16, 'easy', 'multiple_choice_single',
'1 Giăng 2:15: "Đừng yêu ___" vì mọi sự ở trong đó không phải từ Cha',
'["Thế gian và những điều thuộc thế gian", "Gia đình", "Công việc", "Bạn bè"]',
'[0]', 'Hệ thống giá trị thế gian (dục ham muốn, dục ham mắt, sự kiêu ngạo) chống lại Chúa.', '["Tân Ước","Thế gian","Cảnh báo"]', '1 John 2:15-16', 'vi', true, NOW(), NOW()),
('q-1jo-007', '1 John', 3, 16, 16, 'easy', 'multiple_choice_single',
'1 Giăng 3:16: Bởi điều này chúng ta biết tình yêu thương: Ngài đã ___ vì chúng ta',
'["Phó mạng sống Ngài", "Cầu nguyện", "Dạy dỗ", "Chữa lành"]',
'[0]', 'Định nghĩa tình yêu: hy sinh mạng sống. Và chúng ta cũng phải làm vậy cho anh em.', '["Tân Ước","Tình yêu","Hy sinh"]', '1 John 3:16', 'vi', true, NOW(), NOW()),
('q-1jo-008', '1 John', 3, 18, 18, 'easy', 'multiple_choice_single',
'1 Giăng 3:18: "Hãy yêu thương không chỉ bằng lời nói và lưỡi nhưng bằng ___"',
'["Việc làm và lẽ thật", "Cảm xúc", "Tiền bạc", "Lời hứa"]',
'[0]', 'Tình yêu thật biểu hiện qua hành động cụ thể, không chỉ lời nói.', '["Tân Ước","Tình yêu","Hành động"]', '1 John 3:18', 'vi', true, NOW(), NOW()),
('q-1jo-010', '1 John', 4, 18, 18, 'easy', 'multiple_choice_single',
'1 Giăng 4:18: Tình yêu trọn vẹn làm gì với sự sợ hãi?',
'["Cất bỏ sự sợ hãi", "Tăng sự sợ hãi", "Không liên quan", "Giấu sự sợ hãi"]',
'[0]', 'Khi biết Chúa yêu chúng ta trọn vẹn, sự sợ hãi bị xua tan.', '["Tân Ước","Tình yêu","Sợ hãi"]', '1 John 4:18', 'vi', true, NOW(), NOW()),
('q-1jo-011', '1 John', 4, 19, 19, 'easy', 'multiple_choice_single',
'1 Giăng 4:19: "Chúng ta yêu vì ___ đã yêu chúng ta trước"',
'["Ngài (Chúa)", "Chúng ta muốn", "Phải làm", "Tất nhiên"]',
'[0]', 'Tình yêu của chúng ta chỉ là phản hồi tình yêu Chúa đã ban trước.', '["Tân Ước","Tình yêu","Nguồn"]', '1 John 4:19', 'vi', true, NOW(), NOW()),
('q-1jo-012', '1 John', 5, 3, 3, 'easy', 'multiple_choice_single',
'1 Giăng 5:3: Yêu Chúa là gì?',
'["Giữ các điều răn Ngài, và điều răn Ngài không nặng nề", "Cầu nguyện nhiều", "Đi nhà thờ", "Dâng của lễ"]',
'[0]', 'Yêu = vâng lời. Và điều răn Chúa không nặng nề khi có Thánh Linh giúp.', '["Tân Ước","Vâng lời","Tình yêu"]', '1 John 5:3', 'vi', true, NOW(), NOW()),
('q-1jo-014', '1 John', 5, 14, 15, 'easy', 'multiple_choice_single',
'1 Giăng 5:14: Nếu cầu xin điều gì theo ý muốn Chúa thì Ngài sẽ ___',
'["Nghe chúng ta", "Suy nghĩ", "Đợi", "Thử"]',
'[0]', 'Cầu nguyện theo ý Chúa là chìa khóa được Ngài nghe và đáp lời.', '["Tân Ước","Cầu nguyện","Ý Chúa"]', '1 John 5:14-15', 'vi', true, NOW(), NOW()),
('q-1jo-015', '1 John', 4, 10, 10, 'medium', 'multiple_choice_single',
'1 Giăng 4:10: Tình yêu là thế này: không phải chúng ta yêu Chúa nhưng ___ đã yêu chúng ta và sai Con Ngài làm của lễ chuộc tội',
'["Ngài", "Chúng ta", "Thiên sứ", "Tiên tri"]',
'[0]', 'Tình yêu khởi xướng từ Chúa, không phải từ chúng ta. Chúa chủ động yêu trước.', '["Tân Ước","Tình yêu","Chủ động"]', '1 John 4:10', 'vi', true, NOW(), NOW());

-- REVELATION
INSERT IGNORE INTO questions (id, book, chapter, verse_start, verse_end, difficulty, type, content, options, correct_answer, explanation, tags, source, language, is_active, created_at, updated_at) VALUES
('q-rev-004', 'Revelation', 1, 8, 8, 'easy', 'multiple_choice_single',
'Khải 1:8: Chúa tuyên bố Ngài là gì?',
'["An-pha và Ô-mê-ga, Đấng Hiện Có Đấng Đã Có và Đấng Sẽ Đến", "Vua", "Quan án", "Tiên tri"]',
'[0]', 'Chúa là đầu và cuối, có từ muôn đời và sẽ đến. Ngài kiểm soát lịch sử.', '["Tân Ước","Khải huyền","Thần tính"]', 'Revelation 1:8', 'vi', true, NOW(), NOW()),
('q-rev-005', 'Revelation', 1, 17, 18, 'easy', 'multiple_choice_single',
'Chúa Giê-su nói: "Ta là Đấng Sống; ta đã chết nhưng nay ta ___"',
'["Sống đời đời và cầm chìa khóa của sự chết và âm phủ", "Ở trên trời", "Đang đợi", "Nghỉ ngơi"]',
'[0]', 'Chúa Giê-su đã chiến thắng sự chết và có quyền trên sự chết và âm phủ.', '["Tân Ước","Phục sinh","Quyền năng"]', 'Revelation 1:17-18', 'vi', true, NOW(), NOW()),
('q-rev-007', 'Revelation', 4, 8, 8, 'easy', 'multiple_choice_single',
'Bốn sinh vật trước ngôi Chúa kêu ngày đêm: "___! Thánh thay! Thánh thay là Chúa..."',
'["Thánh thay", "Vinh hiển", "Ha-lê-lu-gia", "Quyền năng"]',
'[0]', 'Như Ê-sai 6:3, sự thánh khiết của Chúa là chủ đề ngợi khen ở thiên đàng.', '["Tân Ước","Ngợi khen","Thiên đàng"]', 'Revelation 4:8', 'vi', true, NOW(), NOW()),
('q-rev-008', 'Revelation', 5, 5, 5, 'medium', 'multiple_choice_single',
'Ai xứng đáng mở cuộn sách 7 ấn?',
'["Sư Tử chi phái Giu-đa, Gốc Đa-vít (Chúa Giê-su)", "Thiên sứ Mi-ca-en", "Môi-se", "Đa-vít"]',
'[0]', 'Chỉ Chúa Giê-su xứng đáng vì Ngài đã chiến thắng bởi sự chết và phục sinh.', '["Tân Ước","Chiên Con","Xứng đáng"]', 'Revelation 5:5', 'vi', true, NOW(), NOW()),
('q-rev-010', 'Revelation', 7, 9, 10, 'easy', 'multiple_choice_single',
'Khải 7:9 mô tả đoàn đông không ai đếm được từ đâu?',
'["Mọi dân tộc, mọi nữ phái, mọi dân, mọi tiếng", "Chỉ Y-sơ-ra-ên", "Chỉ thiên sứ", "Chỉ tử đạo"]',
'[0]', 'Thiên đàng là nơi đa văn hóa, đa sắc tộc. Phúc Âm cho mọi người.', '["Tân Ước","Thiên đàng","Mọi dân tộc"]', 'Revelation 7:9-10', 'vi', true, NOW(), NOW()),
('q-rev-011', 'Revelation', 12, 11, 11, 'medium', 'multiple_choice_single',
'Khải 12:11: Các thánh đồ thắng ma quỷ nhờ gì?',
'["Huyết Chiên Con và lời làm chứng của họ", "Gươm", "Quân đội", "Tri thức"]',
'[0]', 'Vũ khí chiến thắng: huyết Chúa + lời làm chứng + sẵn sàng chết vì Chúa.', '["Tân Ước","Chiến thắng","Làm chứng"]', 'Revelation 12:11', 'vi', true, NOW(), NOW()),
('q-rev-012', 'Revelation', 19, 11, 16, 'easy', 'multiple_choice_single',
'Chúa Giê-su tái lâm cưỡi ngựa màu gì?',
'["Trắng", "Đỏ", "Đen", "Vàng"]',
'[0]', 'Khải 19:11 - Ngài là Đấng Thành Tín và Chân Thật, cưỡi ngựa trắng, mặc áo nhuốm huyết.', '["Tân Ước","Tái lâm","Chiến thắng"]', 'Revelation 19:11-16', 'vi', true, NOW(), NOW()),
('q-rev-013', 'Revelation', 21, 1, 2, 'easy', 'multiple_choice_single',
'Khải 21:1: Sau sự phán xét cuối cùng, Chúa tạo điều gì?',
'["Trời mới và đất mới", "Đền thờ mới", "Vườn Ê-đen mới", "Thành phố mới"]',
'[0]', 'Mọi sự được làm mới hoàn toàn. Trời và đất cũ đã qua đi.', '["Tân Ước","Trời mới","Đời đời"]', 'Revelation 21:1-2', 'vi', true, NOW(), NOW()),
('q-rev-015', 'Revelation', 22, 17, 17, 'easy', 'multiple_choice_single',
'Khải 22:17: Thánh Linh và cô dâu (Hội thánh) nói gì?',
'["Hãy đến! Ai khát hãy đến và nhận nước sự sống không", "Hãy đợi", "Hãy cầu nguyện", "Hãy chiến đấu"]',
'[0]', 'Lời mời cuối cùng của Kinh Thánh: Hãy đến nhận sự sống miễn phí từ Chúa.', '["Tân Ước","Lời mời","Nước sống"]', 'Revelation 22:17', 'vi', true, NOW(), NOW());
