-- Supplementary: Joshua, Judges, Ruth, 1-2 Samuel, 1-2 Kings, Nehemiah, Esther

-- ==================== JOSHUA ====================
INSERT IGNORE INTO questions (id, book, chapter, verse_start, verse_end, difficulty, type, content, options, correct_answer, explanation, tags, source, language, is_active, created_at, updated_at) VALUES
('q-jos-004', 'Joshua', 1, 3, 3, 'easy', 'multiple_choice_single',
'Chúa hứa cho Gio-sue mọi nơi bàn chân ông đặt lên sẽ thuộc về ai?',
'["Dân Y-so-ra-en", "Riêng Gio-sue", "Chi phái Giu-đa", "Chỉ các chiến binh"]',
'[0]', 'Gio-sue 1:3 - Mọi nơi bàn chân các ngươi đặt lên, ta ban cho các ngươi. Nhưng vẫn phải bước đi để nhận lấy.', '["Cựu Ước","Đất Hứa","Lời hứa"]', 'Joshua 1:3', 'vi', true, NOW(), NOW()),
('q-jos-005', 'Joshua', 2, 1, 6, 'easy', 'multiple_choice_single',
'Ai đã giúp giấu hai thám tử Y-so-ra-en tại Gie-ri-co?',
'["Ra-hab, người kỹ nữ", "Một thương gia", "Viên quan thành", "Một thầy tế lễ"]',
'[0]', 'Gio-sue 2:4 - Ra-hab giấu 2 thám tử trên mái nhà. Bà tin Chúa và được cứu khi thành bị hạ (He 11:31).', '["Cựu Ước","Ra-hab","Đức tin"]', 'Joshua 2:1-6', 'vi', true, NOW(), NOW()),
('q-jos-006', 'Joshua', 2, 18, 21, 'medium', 'multiple_choice_single',
'Ra-hab phải treo gì nơi cửa sổ để được cứu khi Gie-ri-co bị tấn công?',
'["Dây chỉ điều (đỏ)", "Cờ trắng", "Cột khói", "Đèn dầu"]',
'[0]', 'Gio-sue 2:18 - Dây chỉ điều như huyết chiên con Lễ Vượt Qua. Hình bóng về sự cứu rỗi bởi huyết.', '["Cựu Ước","Ra-hab","Hình bóng"]', 'Joshua 2:18-21', 'vi', true, NOW(), NOW()),
('q-jos-007', 'Joshua', 3, 14, 17, 'easy', 'multiple_choice_single',
'Khi thầy tế lễ khiêng Hòm Giao Ước bước xuống, dòng sông nào rẽ ra?',
'["Sông Gio-đan", "Sông Ni-lô", "Biển Đỏ", "Sông Ô-phát"]',
'[0]', 'Gio-sue 3:15-17 - Sông Gio-đan rẽ ra khi chân thầy tế lễ chạm nước, giống như Biển Đỏ.', '["Cựu Ước","Phép lạ","Gio-đan"]', 'Joshua 3:14-17', 'vi', true, NOW(), NOW()),
('q-jos-008', 'Joshua', 4, 6, 7, 'easy', 'multiple_choice_single',
'12 hòn đá từ sông Gio-đan được dựng lên để làm gì?',
'["Làm dấu kỷ niệm để con cháu nhớ phép lạ Chúa", "Làm bàn thờ", "Xây tường thành", "Làm vũ khí"]',
'[0]', 'Gio-sue 4:7 - Mỗi khi con cháu hỏi, cha mẹ sẽ kể lại phép lạ Chúa rẽ sông Gio-đan.', '["Cựu Ước","Kỷ niệm","Truyền thống"]', 'Joshua 4:6-7', 'vi', true, NOW(), NOW()),
('q-jos-009', 'Joshua', 5, 13, 15, 'medium', 'multiple_choice_single',
'Trước trận Gie-ri-co, Gio-sue gặp ai cầm gươm?',
'["Tướng của đội quân Đức Gie-hô-va", "Thiên sứ Gáp-ri-ên", "Tiên tri Môi-se", "Một chiến binh"]',
'[0]', 'Gio-sue 5:14 - Tướng quân đội Chúa xuất hiện, Gio-sue sụp xuống thờ. Có thể là sự hiện ra của Chúa Giê-su trước nhập thể.', '["Cựu Ước","Thiên sứ","Chiến trận"]', 'Joshua 5:13-15', 'vi', true, NOW(), NOW()),
('q-jos-010', 'Joshua', 7, 20, 21, 'medium', 'multiple_choice_single',
'Tại sao Y-so-ra-en thua trận tại A-hi? Vì tội của ai?',
'["A-can, vì lấy vật bị cấm từ Gie-ri-co", "Gio-sue, vì sai chiến thuật", "Dân sự, vì sợ hãi", "Thầy tế lễ, vì không cầu nguyện"]',
'[0]', 'Gio-sue 7:20-21 - A-can giấu áo choàng, bạc và vàng. Tội lỗi một người ảnh hưởng cả cộng đồng.', '["Cựu Ước","Tội lỗi","Hậu quả"]', 'Joshua 7:20-21', 'vi', true, NOW(), NOW()),
('q-jos-011', 'Joshua', 10, 12, 13, 'easy', 'multiple_choice_single',
'Phép lạ nào xảy ra khi Gio-sue chiến đấu với liên minh 5 vua?',
'["Mặt trời và mặt trăng đứng lại", "Lửa từ trời", "Động đất", "Bão tố"]',
'[0]', 'Gio-sue 10:13 - Mặt trời đứng giữa trời cả ngày để Y-so-ra-en hoàn tất chiến thắng.', '["Cựu Ước","Phép lạ","Chiến trận"]', 'Joshua 10:12-13', 'vi', true, NOW(), NOW()),
('q-jos-012', 'Joshua', 14, 10, 12, 'easy', 'multiple_choice_single',
'Ca-lép xin phần đất nào làm sản nghiệp dù đã 85 tuổi?',
'["Vùng đồi núi có người khổng lồ A-na-kim", "Đồng bằng màu mỡ", "Bờ biển", "Gie-ru-sa-lem"]',
'[0]', 'Gio-sue 14:12 - Ca-lép xin nơi khó nhất vì tin Chúa. Dù 85 tuổi vẫn mạnh mẽ và sẵn sàng chiến đấu.', '["Cựu Ước","Ca-lép","Đức tin"]', 'Joshua 14:10-12', 'vi', true, NOW(), NOW()),
('q-jos-014', 'Joshua', 23, 14, 14, 'medium', 'multiple_choice_single',
'Lời cuối của Gio-sue nhấn mạnh điều gì?',
'["Chúa thành tín giữ mọi lời hứa, hãy trung tín với Ngài", "Hãy chiến đấu tiếp", "Hãy xây nhiều thành", "Hãy tăng quân đội"]',
'[0]', 'Gio-sue 23:14 - Gio-sue làm chứng rằng không lời nào của Chúa thất bại. Khuyên dân trung tín.', '["Cựu Ước","Gio-sue","Thành tín"]', 'Joshua 23:14', 'vi', true, NOW(), NOW()),

-- ==================== JUDGES ====================
('q-jdg-002', 'Judges', 2, 16, 18, 'easy', 'multiple_choice_single',
'Trong sách Các Quan Xét, Chúa dùng lên những người gì để giải cứu dân?',
'["Các quan xét (giải cứu)", "Các vua", "Các tiên tri", "Các thầy tế lễ"]',
'[0]', 'Các Quan Xét 2:16 - Chúa dùng lên các quan xét để giải cứu dân khỏi kẻ áp bức. Chu kỳ: tội lỗi > áp bức > kêu cầu > giải cứu.', '["Cựu Ước","Quan xét","Chu kỳ"]', 'Judges 2:16-18', 'vi', true, NOW(), NOW()),
('q-jdg-003', 'Judges', 2, 11, 15, 'medium', 'multiple_choice_single',
'Chu kỳ lặp đi lặp lại trong sách Các Quan Xét là gì?',
'["Tội lỗi > Hình phạt > Kêu cầu > Giải cứu > Bình an > Tội lỗi lại", "Chiến tranh > Hòa bình", "Xây dựng > Hủy diệt", "Giàu có > Nghèo khó"]',
'[0]', 'Các Quan Xét 2:11-19 - Chu kỳ này lặp lại nhiều lần, cho thấy bản chất con người và sự nhân nại của Chúa.', '["Cựu Ước","Chu kỳ","Bản chất người"]', 'Judges 2:11-15', 'vi', true, NOW(), NOW()),
('q-jdg-004', 'Judges', 4, 4, 5, 'easy', 'multiple_choice_single',
'Nữ quan xét duy nhất trong Kinh Thánh là ai?',
'["Đê-bô-ra", "Ra-hab", "Ru-tơ", "E-xơ-tê"]',
'[0]', 'Các Quan Xét 4:4 - Đê-bô-ra vừa là nữ tiên tri vừa là quan xét xét xử dân Y-so-ra-en.', '["Cựu Ước","Đê-bô-ra","Lãnh đạo"]', 'Judges 4:4-5', 'vi', true, NOW(), NOW()),
('q-jdg-005', 'Judges', 4, 21, 21, 'medium', 'multiple_choice_single',
'Ai đã hạ tướng Si-sê-ra bằng cái cọc lều?',
'["Gia-ên", "Đê-bô-ra", "Ba-rác", "Mi-ri-am"]',
'[0]', 'Các Quan Xét 4:21 - Gia-ên đóng cọc lều qua màng tang Si-sê-ra khi ông ngủ. Chiến thắng đến từ nơi bất ngờ.', '["Cựu Ước","Gia-ên","Chiến thắng"]', 'Judges 4:21', 'vi', true, NOW(), NOW()),
('q-jdg-006', 'Judges', 6, 12, 15, 'easy', 'multiple_choice_single',
'Khi thiên sứ gọi Ghê-đê-ôn là "người dũng cảm", ông đang làm gì?',
'["Đập lúa mì trong bồn ép nho vì sợ quân Ma-đi-an", "Chiến đấu", "Cầu nguyện", "Ngủ"]',
'[0]', 'Các Quan Xét 6:11-12 - Ghê-đê-ôn đang sợ hãi trốn tránh nhưng Chúa thấy tiềm năng trong ông.', '["Cựu Ước","Ghê-đê-ôn","Sự kêu gọi"]', 'Judges 6:12-15', 'vi', true, NOW(), NOW()),
('q-jdg-007', 'Judges', 6, 36, 40, 'easy', 'multiple_choice_single',
'Ghê-đê-ôn dùng gì để thử Chúa?',
'["Bông lông cừu (sương và khô)", "Lửa và nước", "Đá và gậy", "Trái và rau"]',
'[0]', 'Các Quan Xét 6:37-40 - Ghê-đê-ôn thử Chúa 2 lần bằng bông lông cừu. Chúa nhân nại với sự yếu đuối của ông.', '["Cựu Ước","Ghê-đê-ôn","Đức tin"]', 'Judges 6:36-40', 'vi', true, NOW(), NOW()),
('q-jdg-008', 'Judges', 7, 7, 7, 'medium', 'multiple_choice_single',
'Chúa giảm quân đội Ghê-đê-ôn từ 32,000 xuống còn bao nhiêu?',
'["300 người", "1000 người", "3000 người", "100 người"]',
'[0]', 'Các Quan Xét 7:7 - Chỉ 300 người để Chúa được vinh hiển. Chiến thắng không nhờ số đông mà nhờ quyền năng Chúa.', '["Cựu Ước","Ghê-đê-ôn","Quyền năng Chúa"]', 'Judges 7:7', 'vi', true, NOW(), NOW()),
('q-jdg-010', 'Judges', 11, 30, 35, 'hard', 'multiple_choice_single',
'Giép-thê đã hứa điều gì với Chúa trước trận chiến?',
'["Dâng làm của lễ thiêu vật đầu tiên bước ra cửa đón ông", "Xây đền thờ", "Nhịn ăn 40 ngày", "Cho tất cả chiến lợi phẩm"]',
'[0]', 'Các Quan Xét 11:30-31 - Lời hứa hấp tấp của Giép-thê dẫn đến hậu quả đau lòng khi chính con gái ông bước ra.', '["Cựu Ước","Giép-thê","Lời hứa"]', 'Judges 11:30-35', 'vi', true, NOW(), NOW()),
('q-jdg-011', 'Judges', 13, 5, 5, 'easy', 'multiple_choice_single',
'Sam-sôn được biệt riêng làm gì từ khi còn trong bụng mẹ?',
'["Người Na-xi-rê cho Đức Chúa Trời", "Vua", "Thầy tế lễ", "Tiên tri"]',
'[0]', 'Các Quan Xét 13:5 - Sam-sôn là người Na-xi-rê từ trong bụng mẹ, được biệt riêng để giải cứu Y-so-ra-en.', '["Cựu Ước","Sam-sôn","Na-xi-rê"]', 'Judges 13:5', 'vi', true, NOW(), NOW()),
('q-jdg-012', 'Judges', 14, 5, 6, 'easy', 'multiple_choice_single',
'Sam-sôn đã xé con gì bằng tay không bởi Thần Chúa cảm động?',
'["Sư tử", "Gấu", "Sói", "Bò rừng"]',
'[0]', 'Các Quan Xét 14:6 - Thần của Chúa cảm động Sam-sôn và ông xé con sư tử như xé đứa con.', '["Cựu Ước","Sam-sôn","Sức mạnh"]', 'Judges 14:5-6', 'vi', true, NOW(), NOW()),
('q-jdg-013', 'Judges', 15, 15, 16, 'easy', 'multiple_choice_single',
'Sam-sôn dùng vũ khí gì đánh hạ 1000 người Phi-li-tin?',
'["Xương hàm lừa", "Gươm", "Trành nỏm", "Giáo"]',
'[0]', 'Các Quan Xét 15:15 - Sam-sôn dùng xương hàm lừa tươi đánh chết 1000 người.', '["Cựu Ước","Sam-sôn","Chiến đấu"]', 'Judges 15:15-16', 'vi', true, NOW(), NOW()),
('q-jdg-014', 'Judges', 16, 28, 30, 'medium', 'multiple_choice_single',
'Sam-sôn chết như thế nào?',
'["Xô sập đền của người Phi-li-tin, chết chung với kẻ thù", "Bị giết trong giấc ngủ", "Bị ném từ cao", "Bệnh tật"]',
'[0]', 'Các Quan Xét 16:30 - Sam-sôn cầu nguyện lần cuối, được sức và xô hai cột đền. Chết nhiều hơn khi sống.', '["Cựu Ước","Sam-sôn","Hy sinh"]', 'Judges 16:28-30', 'vi', true, NOW(), NOW()),

-- ==================== RUTH ====================
('q-rut-003', 'Ruth', 1, 1, 2, 'easy', 'multiple_choice_single',
'Gia đình Na-ô-mi rời Bết-le-hem đi xứ Mô-áp vì lý do gì?',
'["Nạn đói", "Chiến tranh", "Tìm việc", "Được mời"]',
'[0]', 'Ru-tơ 1:1 - Nạn đói tại Bết-le-hem (nghĩa là "nhà bánh") khiến gia đình Ê-li-me-léc đi xứ Mô-áp.', '["Cựu Ước","Ru-tơ","Nạn đói"]', 'Ruth 1:1-2', 'vi', true, NOW(), NOW()),
('q-rut-004', 'Ruth', 1, 4, 5, 'easy', 'multiple_choice_single',
'Hai con dâu người Mô-áp của Na-ô-mi tên là gì?',
'["Ru-tơ và Óp-ba", "Ru-tơ và Ra-hab", "Óp-ba và Mi-ri-am", "Ru-tơ và Đê-bô-ra"]',
'[0]', 'Ru-tơ 1:4 - Hai con trai Na-ô-mi cưới Ru-tơ và Óp-ba tại Mô-áp.', '["Cựu Ước","Ru-tơ","Nhân vật"]', 'Ruth 1:4-5', 'vi', true, NOW(), NOW()),
('q-rut-005', 'Ruth', 1, 14, 16, 'medium', 'multiple_choice_single',
'Óp-ba và Ru-tơ phản ứng khác nhau thế nào khi Na-ô-mi bảo về?',
'["Óp-ba trở về Mô-áp, Ru-tơ ở lại theo Na-ô-mi", "Cả hai ở lại", "Cả hai trở về", "Ru-tơ trở về, Óp-ba ở lại"]',
'[0]', 'Ru-tơ 1:14-16 - Óp-ba chọn an toàn, Ru-tơ chọn trung tín. Hai sự lựa chọn dẫn đến hai cuộc đời khác nhau.', '["Cựu Ước","Ru-tơ","Trung tín"]', 'Ruth 1:14-16', 'vi', true, NOW(), NOW()),
('q-rut-006', 'Ruth', 1, 20, 21, 'easy', 'multiple_choice_single',
'Na-ô-mi đổi tên thành Ma-ra. Ma-ra có nghĩa là gì?',
'["Cay đắng", "Vui vẻ", "Bình an", "Hy vọng"]',
'[0]', 'Ru-tơ 1:20 - Na-ô-mi (dịu ngọt) đổi thành Ma-ra (cay đắng) vì mất chồng và hai con trai.', '["Cựu Ước","Na-ô-mi","Khổ nạn"]', 'Ruth 1:20-21', 'vi', true, NOW(), NOW()),
('q-rut-007', 'Ruth', 2, 2, 3, 'easy', 'multiple_choice_single',
'Ru-tơ làm gì để nuôi Na-ô-mi?',
'["Mót lúa (nhặt lúa rớt) trên đồng ruộng", "Bán hàng", "Làm bánh", "Chăn chiên"]',
'[0]', 'Ru-tơ 2:2 - Ru-tơ mót lúa theo luật pháp cho phép người nghèo nhặt lúa sót trên đồng (Lê-vi 19:9).', '["Cựu Ước","Ru-tơ","Chăm chỉ"]', 'Ruth 2:2-3', 'vi', true, NOW(), NOW()),
('q-rut-009', 'Ruth', 2, 11, 12, 'medium', 'multiple_choice_single',
'Bô-ô khen Ru-tơ vì điều gì?',
'["Bỏ xứ sở đi theo mẹ chồng đến xứ lạ, nấu nấu dưới cánh Chúa", "Sắc đẹp", "Sự khôn ngoan", "Sự giàu có"]',
'[0]', 'Ru-tơ 2:11-12 - Bô-ô nhận ra đức tin và lòng trung thành của Ru-tơ. Chúa thương những kẻ đến nương náu dưới cánh Ngài.', '["Cựu Ước","Bô-ô","Đức tin"]', 'Ruth 2:11-12', 'vi', true, NOW(), NOW()),
('q-rut-010', 'Ruth', 3, 9, 9, 'medium', 'multiple_choice_single',
'Ru-tơ xin Bô-ô làm gì tại sân lúa?',
'["Làm người chuộc sản nghiệp (gô-el) cho bà", "Cưới bà", "Cho bà ăn", "Bảo vệ bà"]',
'[0]', 'Ru-tơ 3:9 - Hãy đặt vạt áo người trên tôi tớ, vì người là người có quyền chuộc lại (gô-el). Hình bóng về Chúa chuộc chúng ta.', '["Cựu Ước","Gô-el","Cứu chuộc"]', 'Ruth 3:9', 'vi', true, NOW(), NOW()),
('q-rut-011', 'Ruth', 3, 12, 13, 'hard', 'multiple_choice_single',
'Khái niệm "gô-el" (người chuộc) trong sách Ru-tơ là hình bóng của ai?',
'["Chúa Giê-su - Đấng Chuộc Tội của chúng ta", "Môi-se", "Đa-vít", "Áp-ra-ham"]',
'[0]', 'Bô-ô làm gô-el: chuộc đất, cưới Ru-tơ, bảo toàn dòng dõi. Chúa Giê-su làm gô-el: chuộc tội, cưới Hội Thánh, ban sự sống.', '["Cựu Ước","Hình bóng","Cứu chuộc"]', 'Ruth 3:12-13', 'vi', true, NOW(), NOW()),
('q-rut-012', 'Ruth', 4, 1, 6, 'medium', 'multiple_choice_single',
'Tại sao người bà con gần hơn Bô-ô từ chối quyền chuộc?',
'["Sợ làm hư sản nghiệp của mình", "Không có tiền", "Không thích Ru-tơ", "Đang bệnh"]',
'[0]', 'Ru-tơ 4:6 - Người gô-el gần hơn từ chối vì sợ thiệt hại cho sản nghiệp. Bô-ô sẵn lòng hy sinh.', '["Cựu Ước","Bô-ô","Hy sinh"]', 'Ruth 4:1-6', 'vi', true, NOW(), NOW()),
('q-rut-013', 'Ruth', 4, 9, 10, 'easy', 'multiple_choice_single',
'Bô-ô cưới Ru-tơ và mua lại sản nghiệp của ai?',
'["Ê-li-me-léc, chồng Na-ô-mi", "Na-ô-mi", "Óp-ba", "Một người lạ"]',
'[0]', 'Ru-tơ 4:9-10 - Bô-ô chuộc toàn bộ sản nghiệp và cưới Ru-tơ để bảo toàn danh của người chết.', '["Cựu Ước","Bô-ô","Cứu chuộc"]', 'Ruth 4:9-10', 'vi', true, NOW(), NOW()),
('q-rut-015', 'Ruth', 4, 17, 17, 'easy', 'multiple_choice_single',
'Con trai của Bô-ô và Ru-tơ tên là gì?',
'["Ô-bết", "Giê-se", "Đa-vít", "Sa-lô-môn"]',
'[0]', 'Ru-tơ 4:17 - Ô-bết là cha Giê-se, ông nội Đa-vít. Ru-tơ là bà cố của dòng dõi vua và của Chúa Giê-su.', '["Cựu Ước","Gia phả","Ô-bết"]', 'Ruth 4:17', 'vi', true, NOW(), NOW()),

-- ==================== 1 SAMUEL ====================
('q-1sa-005', '1 Samuel', 1, 10, 11, 'easy', 'multiple_choice_single',
'An-ne cầu xin Chúa điều gì tại đền tạm?',
'["Một đứa con trai và hứa dâng nó cho Chúa", "Sự giàu có", "Sức khỏe", "Chiến thắng"]',
'[0]', '1 Sa 1:11 - An-ne cầu nguyện trong nước mắt và hứa dâng con cho Chúa. Chúa nhậm lời bà.', '["Cựu Ước","An-ne","Cầu nguyện"]', '1 Samuel 1:10-11', 'vi', true, NOW(), NOW()),
('q-1sa-006', '1 Samuel', 2, 12, 17, 'medium', 'multiple_choice_single',
'Hai con trai Hê-li là Hốp-ni và Phi-nê-a làm điều gì sai?',
'["Ăn trộm của lễ và sống vô đạo đức", "Thờ tượng", "Bỏ trốn", "Chống lại vua"]',
'[0]', '1 Sa 2:12-17 - Họ không biết Chúa, cướp của lễ và sống vô đạo đức. Hậu quả: cả hai chết cùng ngày.', '["Cựu Ước","Hình phạt","Tế lễ"]', '1 Samuel 2:12-17', 'vi', true, NOW(), NOW()),
('q-1sa-008', '1 Samuel', 8, 5, 7, 'medium', 'multiple_choice_single',
'Dân Y-so-ra-en xin Sa-mu-en điều gì khiến Chúa buồn?',
'["Xin một vua như các dân tộc khác", "Xin nhiều của cải", "Xin chiến thắng", "Xin một tiên tri mới"]',
'[0]', '1 Sa 8:7 - Chúa nói: Họ không từ chối con đâu, nhưng từ chối ta làm vua họ. Dân chọn người thay vì Chúa.', '["Cựu Ước","Vương quyền","Từ chối"]', '1 Samuel 8:5-7', 'vi', true, NOW(), NOW()),
('q-1sa-009', '1 Samuel', 9, 2, 2, 'easy', 'multiple_choice_single',
'Sau-lơ, vua đầu tiên của Y-so-ra-en, được mô tả như thế nào?',
'["Cao hơn mọi người từ vai trở lên, đẹp trai", "Khôn ngoan nhất", "Mạnh mẽ nhất", "Giàu nhất"]',
'[0]', '1 Sa 9:2 - Sau-lơ có hình thức bên ngoài ấn tượng nhưng tâm lòng không vững.', '["Cựu Ước","Sau-lơ","Hình thức"]', '1 Samuel 9:2', 'vi', true, NOW(), NOW()),
('q-1sa-010', '1 Samuel', 13, 14, 14, 'medium', 'multiple_choice_single',
'Sa-mu-en nói Chúa tìm một người như thế nào để thay Sau-lơ?',
'["Một người vừa lòng Chúa", "Người mạnh nhất", "Người khôn ngoan nhất", "Người từ phú hoàng gia"]',
'[0]', '1 Sa 13:14 - Chúa tìm người vừa lòng Ngài. Đa-vít được gọi là người vừa lòng Chúa (Công vụ 13:22).', '["Cựu Ước","Đa-vít","Tâm lòng"]', '1 Samuel 13:14', 'vi', true, NOW(), NOW()),
('q-1sa-011', '1 Samuel', 15, 22, 22, 'easy', 'multiple_choice_single',
'Sa-mu-en nói: "Sự vâng lời tốt hơn ___, sự nghe theo tốt hơn mỡ của chiên đực"',
'["Của tế lễ", "Vàng bạc", "Chiến thắng", "Tri thức"]',
'[0]', '1 Sa 15:22 - Chúa muốn sự vâng lời từ tâm lòng hơn là hình thức tôn giáo bên ngoài.', '["Cựu Ước","Vâng lời","Tế lễ"]', '1 Samuel 15:22', 'vi', true, NOW(), NOW()),
('q-1sa-012', '1 Samuel', 18, 1, 3, 'easy', 'multiple_choice_single',
'Tình bạn nổi tiếng nhất Kinh Thánh là giữa ai?',
'["Đa-vít và Giô-na-than", "Môi-se và A-rôn", "Đa-vít và Sa-mu-en", "Áp-ra-ham và Lót"]',
'[0]', '1 Sa 18:1 - Giô-na-than yêu Đa-vít như chính mình. Tình bạn trung tín bất chấp hoàn cảnh.', '["Cựu Ước","Tình bạn","Trung tín"]', '1 Samuel 18:1-3', 'vi', true, NOW(), NOW()),
('q-1sa-013', '1 Samuel', 24, 4, 7, 'hard', 'multiple_choice_single',
'Khi có cơ hội giết Sau-lơ trong hang, Đa-vít làm gì?',
'["Chỉ cắt vạt áo Sau-lơ và ray rứt ân hận vì đã làm điều đó", "Giết Sau-lơ", "Bỏ trốn", "Bắt Sau-lơ"]',
'[0]', '1 Sa 24:5-7 - Đa-vít tôn trọng Sau-lơ là người được Chúa xức dầu, dù Sau-lơ muốn giết ông. Bài học về tôn trọng quyền bính.', '["Cựu Ước","Đa-vít","Tôn trọng"]', '1 Samuel 24:4-7', 'vi', true, NOW(), NOW()),
('q-1sa-015', '1 Samuel', 26, 9, 11, 'medium', 'multiple_choice_single',
'Lần thứ hai có cơ hội giết Sau-lơ, Đa-vít lấy gì thay vì giết?',
'["Giáo và bình nước của Sau-lơ", "Áo choàng", "Vương miện", "Gươm"]',
'[0]', '1 Sa 26:11-12 - Đa-vít tiếp tục tôn trọng mạng sống của Sau-lơ, chỉ lấy giáo và bình nước làm bằng chứng.', '["Cựu Ước","Đa-vít","Nhân nại"]', '1 Samuel 26:9-12', 'vi', true, NOW(), NOW()),

-- ==================== 2 SAMUEL ====================
('q-2sa-002', '2 Samuel', 5, 4, 5, 'easy', 'multiple_choice_single',
'Đa-vít làm vua tổng cộng bao nhiêu năm?',
'["40 năm (7 năm tại Hếp-rôn, 33 năm tại Gie-ru-sa-lem)", "30 năm", "20 năm", "50 năm"]',
'[0]', '2 Sa 5:4-5 - Đa-vít lên ngôi lúc 30 tuổi và cai trị 40 năm.', '["Cựu Ước","Đa-vít","Trị vì"]', '2 Samuel 5:4-5', 'vi', true, NOW(), NOW()),
('q-2sa-003', '2 Samuel', 6, 14, 15, 'easy', 'multiple_choice_single',
'Đa-vít làm gì khi Hòm Giao Ước được rước về Gie-ru-sa-lem?',
'["Nhảy múa hết sức trước mặt Chúa", "Ngồi trên ngai", "Dâng của lễ im lặng", "Đọc luật pháp"]',
'[0]', '2 Sa 6:14 - Đa-vít nhảy múa hết sức trước mặt Chúa, không quan tâm hình ảnh vua. Thờ phượng hết lòng.', '["Cựu Ước","Đa-vít","Thờ phượng"]', '2 Samuel 6:14-15', 'vi', true, NOW(), NOW()),
('q-2sa-004', '2 Samuel', 7, 12, 13, 'hard', 'multiple_choice_single',
'Giao ước Đa-vít (2 Sa 7) hứa điều quan trọng nào?',
'["Ngôi vua của dòng dõi Đa-vít sẽ còn đời đời", "Đa-vít sẽ sống mãi", "Đền thờ không bao giờ bị phá", "Y-so-ra-en luôn thắng trận"]',
'[0]', '2 Sa 7:12-13 - Ngôi vua đời đời của dòng dõi Đa-vít ứng nghiệm nơi Chúa Giê-su (Lu-ca 1:32-33).', '["Cựu Ước","Giao ước","Cứu Thế"]', '2 Samuel 7:12-13', 'vi', true, NOW(), NOW()),
('q-2sa-005', '2 Samuel', 9, 1, 7, 'easy', 'multiple_choice_single',
'Đa-vít tỏ lòng nhân từ với ai vì lời của Giô-na-than?',
'["Mê-phi-bô-sết, con Giô-na-than", "Sau-lơ", "Áp-ne", "Si-mê-i"]',
'[0]', '2 Sa 9:7 - Mê-phi-bô-sết bị quẹo cả hai chân nhưng được Đa-vít mời ăn đồng bàn vua suốt đời.', '["Cựu Ước","Đa-vít","Ân điển"]', '2 Samuel 9:1-7', 'vi', true, NOW(), NOW()),
('q-2sa-006', '2 Samuel', 11, 2, 4, 'easy', 'multiple_choice_single',
'Tội lớn của Đa-vít với Bát-sê-ba bắt đầu khi nào?',
'["Khi Đa-vít ở lại Gie-ru-sa-lem thay vì ra trận", "Khi đi thăm đất", "Khi ngủ trưa", "Khi ăn tiệc"]',
'[0]', '2 Sa 11:1-2 - Vào mùa các vua ra trận, Đa-vít ở nhà. Sự nhàn rỗi dẫn đến cám dỗ và tội lỗi.', '["Cựu Ước","Đa-vít","Cám dỗ"]', '2 Samuel 11:2-4', 'vi', true, NOW(), NOW()),
('q-2sa-007', '2 Samuel', 11, 14, 17, 'medium', 'multiple_choice_single',
'Đa-vít làm gì để che giấu tội với Bát-sê-ba?',
'["Sắp đặt cho chồng bà là U-ri chết trận", "Trốn khỏi Gie-ru-sa-lem", "Đổi lộ cho U-ri", "Gửi U-ri đi xa"]',
'[0]', '2 Sa 11:15 - Đa-vít viết thư cho Giô-áp bỏ U-ri vào chỗ nguy hiểm nhất. Tội phạm tội dẫn đến tội gián tiếp giết người.', '["Cựu Ước","Đa-vít","Tội lỗi"]', '2 Samuel 11:14-17', 'vi', true, NOW(), NOW()),
('q-2sa-009', '2 Samuel', 12, 23, 23, 'medium', 'multiple_choice_single',
'Khi con trai chết, Đa-vít nói điều gì về hy vọng?',
'["Tôi sẽ đi đến nó, nhưng nó sẽ không trở lại với tôi", "Chúa sẽ cho con khác", "Tôi sẽ không buồn nữa", "Tôi sẽ quên đi"]',
'[0]', '2 Sa 12:23 - Đa-vít tin rằng sẽ gặp con mình ở thế giới bên kia. Hy vọng về sự sống sau khi chết.', '["Cựu Ước","Đa-vít","Hy vọng"]', '2 Samuel 12:23', 'vi', true, NOW(), NOW()),
('q-2sa-010', '2 Samuel', 15, 13, 14, 'easy', 'multiple_choice_single',
'Con trai nào của Đa-vít nổi loạn và tự xưng làm vua?',
'["Áp-sa-lôm", "Am-nôn", "Sa-lô-môn", "A-đô-ni-gia"]',
'[0]', '2 Sa 15:13-14 - Áp-sa-lôm nổi loạn, Đa-vít phải trốn khỏi Gie-ru-sa-lem. Hậu quả của tội lỗi gia đình.', '["Cựu Ước","Áp-sa-lôm","Nổi loạn"]', '2 Samuel 15:13-14', 'vi', true, NOW(), NOW()),
('q-2sa-011', '2 Samuel', 18, 33, 33, 'easy', 'multiple_choice_single',
'Khi Áp-sa-lôm chết, Đa-vít phản ứng thế nào?',
'["Khóc và ước mình chết thay con", "Vui mừng vì hết nổi loạn", "Im lặng", "Giận dữ"]',
'[0]', '2 Sa 18:33 - Dù Áp-sa-lôm nổi loạn, Đa-vít vẫn là người cha đau khổ. Ôi Áp-sa-lôm, con tôi ơi!', '["Cựu Ước","Đa-vít","Tình cha"]', '2 Samuel 18:33', 'vi', true, NOW(), NOW()),
('q-2sa-013', '2 Samuel', 23, 1, 5, 'medium', 'multiple_choice_single',
'Lời cuối cùng của Đa-vít nhấn mạnh giao ước với Chúa là gì?',
'["Giao ước đời đời, không thay đổi", "Tạm thời", "Có điều kiện", "Chỉ cho Sa-lô-môn"]',
'[0]', '2 Sa 23:5 - Đa-vít xác nhận giao ước đời đời mà Chúa lập với nhà ông.', '["Cựu Ước","Đa-vít","Giao ước"]', '2 Samuel 23:1-5', 'vi', true, NOW(), NOW()),
('q-2sa-014', '2 Samuel', 24, 24, 24, 'medium', 'multiple_choice_single',
'Đa-vít nói điều gì khi mua sân lúa để lập bàn thờ?',
'["Tôi không dâng cho Chúa của lễ mà không tốn phí gì", "Tôi trả giá tốt nhất", "Chúa đáng được tất cả", "Tôi cho tất cả"]',
'[0]', '2 Sa 24:24 - Của lễ thật đòi hỏi sự hy sinh. Không dâng cho Chúa điều không tốn phí gì.', '["Cựu Ước","Đa-vít","Của lễ"]', '2 Samuel 24:24', 'vi', true, NOW(), NOW()),

-- ==================== 1 KINGS ====================
('q-1ki-003', '1 Kings', 6, 1, 2, 'easy', 'multiple_choice_single',
'Sa-lô-môn xây đền thờ mất bao lâu?',
'["7 năm", "3 năm", "40 năm", "12 năm"]',
'[0]', '1 Các Vua 6:38 - Đền thờ được xây trong 7 năm. Một công trình hùng vĩ.', '["Cựu Ước","Sa-lô-môn","Đền thờ"]', '1 Kings 6:1-2', 'vi', true, NOW(), NOW()),
('q-1ki-004', '1 Kings', 8, 27, 27, 'hard', 'multiple_choice_single',
'Khi khánh thành đền thờ, Sa-lô-môn tuyên bố điều gì về Chúa?',
'["Trời của các tầng trời không chứa nổi Ngài, huống chi đền này", "Đền này là nhà của Chúa", "Chúa chỉ ở trong đền", "Chúa vui vẻ nhận đền"]',
'[0]', '1 Các Vua 8:27 - Sa-lô-môn hiểu rằng Chúa không bị giới hạn trong đền thờ. Ngài lớn hơn mọi công trình.', '["Cựu Ước","Đền thờ","Thần học"]', '1 Kings 8:27', 'vi', true, NOW(), NOW()),
('q-1ki-005', '1 Kings', 10, 1, 9, 'easy', 'multiple_choice_single',
'Nữ hoàng xứ nào đến thăm và thử sự khôn ngoan của Sa-lô-môn?',
'["Nữ hoàng xứ Sê-ba", "Nữ hoàng Ai-cập", "Nữ hoàng Ba-by-lôn", "Nữ hoàng Ba-tư"]',
'[0]', '1 Các Vua 10:1 - Nữ hoàng Sê-ba đến với câu hỏi khó. Bà kinh ngạc trước sự khôn ngoan và sự giàu có của Sa-lô-môn.', '["Cựu Ước","Sa-lô-môn","Khôn ngoan"]', '1 Kings 10:1-9', 'vi', true, NOW(), NOW()),
('q-1ki-006', '1 Kings', 11, 4, 4, 'medium', 'multiple_choice_single',
'Tại sao Sa-lô-môn sa ngã cuối đời?',
'["Các vợ ngoại bang xoay lòng ông theo các thần khác", "Mất trí nhớ", "Bị bệnh", "Bị phản bội"]',
'[0]', '1 Các Vua 11:4 - Sa-lô-môn có 700 vợ và 300 hầu, họ làm lòng ông nghiêng theo thần ngoại bang.', '["Cựu Ước","Sa-lô-môn","Sa ngã"]', '1 Kings 11:4', 'vi', true, NOW(), NOW()),
('q-1ki-007', '1 Kings', 12, 16, 19, 'medium', 'multiple_choice_single',
'Vương quốc bị chia cắt vì lỗi của ai?',
'["Rô-bô-am, vì từ chối giảm gánh nặng cho dân", "Giê-rô-bô-am", "Sa-lô-môn", "A-hi-gia"]',
'[0]', '1 Các Vua 12:16 - Rô-bô-am nghe lời bạn trẻ, tăng gánh nặng. 10 chi phái ly khai, chỉ còn Giu-đa và Bên-gia-min.', '["Cựu Ước","Chia cắt","Rô-bô-am"]', '1 Kings 12:16-19', 'vi', true, NOW(), NOW()),
('q-1ki-008', '1 Kings', 17, 4, 6, 'easy', 'multiple_choice_single',
'Chúa dùng gì để nuôi Ê-li bên suối Kê-rít?',
'["Quạ và chim đem đem bánh và thịt đến", "Ma-na từ trời", "Trái cây rừng", "Người dân địa phương"]',
'[0]', '1 Các Vua 17:6 - Quạ đem bánh và thịt cho Ê-li sáng và chiều. Chúa lo liệu cách lạ lùng.', '["Cựu Ước","Ê-li","Chúa lo liệu"]', '1 Kings 17:4-6', 'vi', true, NOW(), NOW()),
('q-1ki-009', '1 Kings', 17, 14, 16, 'easy', 'multiple_choice_single',
'Phép lạ nào xảy ra với bà góa Sa-rép-ta?',
'["Hũ bột và vẻ dầu không hết suốt mùa đói", "Nước biển thành rượu", "Con trai sống lại", "Nhà được xây mới"]',
'[0]', '1 Các Vua 17:16 - Hũ bột không vơi, vẻ dầu không cạn. Chúa lo liệu khi chúng ta vâng lời.', '["Cựu Ước","Ê-li","Phép lạ"]', '1 Kings 17:14-16', 'vi', true, NOW(), NOW()),
('q-1ki-011', '1 Kings', 19, 4, 4, 'easy', 'multiple_choice_single',
'Sau chiến thắng trên núi Cát-men, Ê-li phản ứng thế nào khi Giê-sa-bên đe dọa?',
'["Sợ hãi bỏ chạy vào đồng vắng, muốn chết", "Vui mừng", "Chiến đấu tiếp", "Cầu nguyện thêm"]',
'[0]', '1 Các Vua 19:4 - Ngay cả tiên tri vĩ đại nhất cũng có lúc yếu đuối. Chúa nhân từ chăm sóc Ê-li.', '["Cựu Ước","Ê-li","Yếu đuối"]', '1 Kings 19:4', 'vi', true, NOW(), NOW()),
('q-1ki-012', '1 Kings', 19, 11, 12, 'medium', 'multiple_choice_single',
'Chúa hiện ra với Ê-li tại núi Hô-rếp bằng gì?',
'["Tiếng nhỏ nhẹ (tiếng phảm phảm)", "Gió bão", "Động đất", "Lửa"]',
'[0]', '1 Các Vua 19:12 - Chúa không ở trong gió bão, động đất hay lửa, mà trong tiếng nhỏ nhẹ. Chúa nói trong sự yên tĩnh.', '["Cựu Ước","Ê-li","Tiếng Chúa"]', '1 Kings 19:11-12', 'vi', true, NOW(), NOW()),
('q-1ki-013', '1 Kings', 19, 18, 18, 'easy', 'multiple_choice_single',
'Chúa nói còn lại bao nhiêu người chưa từng quỳ gối trước Ba-an?',
'["7000 người", "100 người", "1000 người", "Chỉ Ê-li"]',
'[0]', '1 Các Vua 19:18 - 7000 người chưa quỳ gối Ba-an. Ê-li không cô đơn như ông tưởng.', '["Cựu Ước","Ê-li","Dân số còn lại"]', '1 Kings 19:18', 'vi', true, NOW(), NOW()),
('q-1ki-014', '1 Kings', 19, 19, 21, 'easy', 'multiple_choice_single',
'Ê-li gọi Ê-li-sê làm môn đồ bằng cách nào?',
'["Ném áo choàng mình lên Ê-li-sê", "Gọi tên ông", "Gửi thư", "Sai người đến"]',
'[0]', '1 Các Vua 19:19 - Áo choàng tiên tri là biểu tượng truyền chức vụ và quyền năng.', '["Cựu Ước","Ê-li-sê","Môn đồ"]', '1 Kings 19:19-21', 'vi', true, NOW(), NOW()),

-- ==================== 2 KINGS ====================
('q-2ki-002', '2 Kings', 2, 9, 9, 'easy', 'multiple_choice_single',
'Ê-li-sê xin điều gì trước khi Ê-li được cất đi?',
'["Hai phần thần của Ê-li", "Sự giàu có", "Quyền lực", "Sống lâu"]',
'[0]', '2 Các Vua 2:9 - Hai phần thần (phần trưởng tử) cho thấy Ê-li-sê muốn tiếp nối sứ vụ cách trọn vẹn.', '["Cựu Ước","Ê-li-sê","Thánh Linh"]', '2 Kings 2:9', 'vi', true, NOW(), NOW()),
('q-2ki-003', '2 Kings', 4, 1, 7, 'easy', 'multiple_choice_single',
'Ê-li-sê giúp bà góa có nợ bằng phép lạ gì?',
'["Dầu ô-liu từ bình chảy không hết vào các bình khác", "Vàng từ trời", "Con giải nợ", "Bàn thờ gửi tiền"]',
'[0]', '2 Các Vua 4:6 - Dầu chảy đầy mọi bình bà muốn được. Chúa nhân lên điều ít ỏi để đủ dùng.', '["Cựu Ước","Ê-li-sê","Phép lạ"]', '2 Kings 4:1-7', 'vi', true, NOW(), NOW()),
('q-2ki-004', '2 Kings', 4, 32, 35, 'medium', 'multiple_choice_single',
'Ê-li-sê làm gì để con trai người phụ nữ Su-nem sống lại?',
'["Nằm áp lên đứa trẻ và cầu nguyện", "Rao luật pháp", "Dâng của lễ", "Gọi tiên tri khác"]',
'[0]', '2 Các Vua 4:34 - Ê-li-sê nằm áp lên, miệng kề miệng, mắt kề mắt. Đứa trẻ hắt xì 7 lần và sống lại.', '["Cựu Ước","Ê-li-sê","Phục sinh"]', '2 Kings 4:32-35', 'vi', true, NOW(), NOW()),
('q-2ki-005', '2 Kings', 5, 1, 14, 'easy', 'multiple_choice_single',
'Tướng Na-a-man được chữa bệnh phong bằng cách nào?',
'["Tắm 7 lần dưới sông Gio-đan", "Uống thuốc", "Dâng của lễ", "Cầu nguyện"]',
'[0]', '2 Các Vua 5:14 - Na-a-man tắm 7 lần theo lời Ê-li-sê. Dù ban đầu giận dữ vì nghĩ cách này quá đơn giản.', '["Cựu Ước","Na-a-man","Vâng lời"]', '2 Kings 5:1-14', 'vi', true, NOW(), NOW()),
('q-2ki-007', '2 Kings', 6, 16, 17, 'easy', 'multiple_choice_single',
'Ê-li-sê nói với đầy tớ: "Đừng sợ, vì những kẻ ở với chúng ta đông hơn..." Khi mắt mở ra thấy gì?',
'["Núi đầy xe lửa và ngựa lửa bao quanh", "Đội quân lớn", "Thiên sứ", "Đám mây sáng"]',
'[0]', '2 Các Vua 6:17 - Thế giới thuộc linh có quân đội Chúa bảo vệ. Điều mắt thường không thấy.', '["Cựu Ước","Ê-li-sê","Bảo vệ"]', '2 Kings 6:16-17', 'vi', true, NOW(), NOW()),
('q-2ki-008', '2 Kings', 17, 6, 6, 'medium', 'multiple_choice_single',
'Vương quốc phía Bắc (Y-so-ra-en) bị đế quốc nào tiêu diệt năm 722 TCN?',
'["A-si-ri", "Ba-by-lôn", "Ai-cập", "Ba-tư"]',
'[0]', '2 Các Vua 17:6 - A-si-ri bắt Y-so-ra-en làm phu tù. 10 chi phái bị phân tán không bao giờ phục hồi.', '["Cựu Ước","Lịch sử","Lưu đày"]', '2 Kings 17:6', 'vi', true, NOW(), NOW()),
('q-2ki-009', '2 Kings', 22, 8, 11, 'medium', 'multiple_choice_single',
'Vua Giô-si-a tìm thấy gì trong đền thờ đã được quên lãng?',
'["Sách luật pháp (Torah)", "Hòm Giao Ước", "Vàng bạc", "Áo thầy tế lễ"]',
'[0]', '2 Các Vua 22:8 - Tìm lại sách luật pháp dẫn đến cuộc cải cách lớn nhất trong lịch sử Giu-đa.', '["Cựu Ước","Giô-si-a","Cải cách"]', '2 Kings 22:8-11', 'vi', true, NOW(), NOW()),
('q-2ki-010', '2 Kings', 23, 25, 25, 'easy', 'multiple_choice_single',
'Vua nào được khen là yêu Chúa hết lòng, hết linh hồn, hết sức hơn bất kỳ vua nào?',
'["Giô-si-a", "Đa-vít", "Sa-lô-môn", "Ê-xê-chia"]',
'[0]', '2 Các Vua 23:25 - Trước và sau Giô-si-a, không có vua nào quay lại Chúa hết lòng như ông.', '["Cựu Ước","Giô-si-a","Hết lòng"]', '2 Kings 23:25', 'vi', true, NOW(), NOW()),
('q-2ki-011', '2 Kings', 20, 1, 6, 'easy', 'multiple_choice_single',
'Chúa thêm bao nhiêu năm cho vua Ê-xê-chia sau khi ông cầu nguyện?',
'["15 năm", "7 năm", "10 năm", "40 năm"]',
'[0]', '2 Các Vua 20:6 - Chúa nghe lời cầu nguyện của Ê-xê-chia và thêm 15 năm cho đời ông.', '["Cựu Ước","Ê-xê-chia","Cầu nguyện"]', '2 Kings 20:1-6', 'vi', true, NOW(), NOW()),
('q-2ki-012', '2 Kings', 25, 8, 11, 'easy', 'multiple_choice_single',
'Vương quốc Giu-đa bị đế quốc nào tiêu diệt và đền thờ bị phá năm 586 TCN?',
'["Ba-by-lôn (Nê-bu-cát-nết-sa)", "A-si-ri", "Ai-cập", "Ba-tư"]',
'[0]', '2 Các Vua 25:8-9 - Nê-bu-cát-nết-sa đốt đền thờ, phá tường thành và bắt dân lưu đày Ba-by-lôn.', '["Cựu Ước","Lịch sử","Lưu đày"]', '2 Kings 25:8-11', 'vi', true, NOW(), NOW()),
('q-2ki-014', '2 Kings', 4, 42, 44, 'easy', 'multiple_choice_single',
'Ê-li-sê cho bao nhiêu người ăn với 20 ổ bánh lúa mạch?',
'["100 người và còn dư", "50 người", "200 người", "1000 người"]',
'[0]', '2 Các Vua 4:44 - 100 người ăn và còn dư. Tiền báo phép lạ Chúa Giê-su cho 5000 người ăn.', '["Cựu Ước","Ê-li-sê","Phép lạ"]', '2 Kings 4:42-44', 'vi', true, NOW(), NOW()),
('q-2ki-015', '2 Kings', 13, 21, 21, 'hard', 'multiple_choice_single',
'Điều gì xảy ra khi một xác chết chạm xuống cốt của Ê-li-sê trong mồ?',
'["Người chết sống lại", "Mồ sáng lên", "Đất rung", "Âm thanh lớn"]',
'[0]', '2 Các Vua 13:21 - Ngay cả sau khi chết, xương Ê-li-sê vẫn có quyền năng phục sinh. Cho thấy quyền năng Chúa.', '["Cựu Ước","Ê-li-sê","Phục sinh"]', '2 Kings 13:21', 'vi', true, NOW(), NOW()),

-- ==================== NEHEMIAH ====================
('q-neh-002', 'Nehemiah', 1, 3, 4, 'easy', 'multiple_choice_single',
'Khi nghe tin tường thành Gie-ru-sa-lem đổ nát, Nê-hê-mi làm gì?',
'["Khóc, kiêng ăn và cầu nguyện nhiều ngày", "Lập tức lên đường", "Giận dữ", "Bỏ mặc"]',
'[0]', 'Nê-hê-mi 1:4 - Nê-hê-mi đau buồn và cầu nguyện trước khi hành động. Cầu nguyện trước rồi làm sau.', '["Cựu Ước","Nê-hê-mi","Cầu nguyện"]', 'Nehemiah 1:3-4', 'vi', true, NOW(), NOW()),
('q-neh-003', 'Nehemiah', 1, 11, 11, 'easy', 'multiple_choice_single',
'Nê-hê-mi giữ chức vụ gì cho vua Ba-tư?',
'["Quan dâng rượu (người rót rượu)", "Tướng quân", "Cố vấn", "Thư ký"]',
'[0]', 'Nê-hê-mi 1:11 - Chức quan dâng rượu rất được tin cậy vì phải bảo đảm rượu không bị đầu độc.', '["Cựu Ước","Nê-hê-mi","Chức vụ"]', 'Nehemiah 1:11', 'vi', true, NOW(), NOW()),
('q-neh-004', 'Nehemiah', 2, 4, 5, 'medium', 'multiple_choice_single',
'Trước khi xin phép vua Ác-ta-xéc-xe, Nê-hê-mi làm gì?',
'["Thầm cầu nguyện với Chúa", "Chuẩn bị bài diễn văn", "Hỏi ý cố vấn", "Viết thư"]',
'[0]', 'Nê-hê-mi 2:4 - Nê-hê-mi cầu nguyện "thầm" ngay lúc đang nói chuyện với vua. Cầu nguyện bất cứ lúc nào.', '["Cựu Ước","Nê-hê-mi","Cầu nguyện"]', 'Nehemiah 2:4-5', 'vi', true, NOW(), NOW()),
('q-neh-005', 'Nehemiah', 4, 9, 9, 'easy', 'multiple_choice_single',
'Khi bị kẻ thù đe dọa, Nê-hê-mi làm gì?',
'["Cầu nguyện và đặt người canh gác", "Chỉ cầu nguyện", "Chỉ đặt lính canh", "Ngừng xây"]',
'[0]', 'Nê-hê-mi 4:9 - Vừa cầu nguyện vừa hành động thực tế. Tin cậy Chúa nhưng vẫn làm phần mình.', '["Cựu Ước","Nê-hê-mi","Đức tin"]', 'Nehemiah 4:9', 'vi', true, NOW(), NOW()),
('q-neh-007', 'Nehemiah', 6, 3, 3, 'medium', 'multiple_choice_single',
'Khi kẻ thù mời Nê-hê-mi xuống để ngừng xây, ông trả lời thế nào?',
'["Tôi đang làm việc lớn, không thể xuống được", "Tôi sẽ đến ngay", "Để tôi suy nghĩ", "Gửi người thay"]',
'[0]', 'Nê-hê-mi 6:3 - Nê-hê-mi từ chối bị phân tâm bởi kẻ thù. Tập trung vào sứ mệnh Chúa giao.', '["Cựu Ước","Nê-hê-mi","Tập trung"]', 'Nehemiah 6:3', 'vi', true, NOW(), NOW()),
('q-neh-008', 'Nehemiah', 6, 15, 16, 'easy', 'multiple_choice_single',
'Tường thành Gie-ru-sa-lem được xây lại trong bao lâu?',
'["52 ngày", "6 tháng", "1 năm", "7 năm"]',
'[0]', 'Nê-hê-mi 6:15 - 52 ngày! Kẻ thù nhận ra đây là việc của Chúa vì không ai làm nhanh vậy từ sức mình.', '["Cựu Ước","Nê-hê-mi","Phép lạ"]', 'Nehemiah 6:15-16', 'vi', true, NOW(), NOW()),
('q-neh-009', 'Nehemiah', 8, 10, 10, 'easy', 'multiple_choice_single',
'Nê-hê-mi nói: "Sự vui vẻ của Đức Gie-hô-va là ___"',
'["Sức lực của các ngươi", "Phúc lành của các ngươi", "Hy vọng của các ngươi", "Mục đích của các ngươi"]',
'[0]', 'Nê-hê-mi 8:10 - Sự vui vẻ từ Chúa ban cho sức mạnh để đối diện mọi hoàn cảnh.', '["Cựu Ước","Nê-hê-mi","Vui vẻ"]', 'Nehemiah 8:10', 'vi', true, NOW(), NOW()),
('q-neh-010', 'Nehemiah', 8, 1, 3, 'medium', 'multiple_choice_single',
'Ai đọc sách luật pháp cho dân sự nghe từ sáng đến trưa?',
'["E-xơ-ra, thầy thông giáo", "Nê-hê-mi", "Các thầy tế lễ", "Dân sự tự đọc"]',
'[0]', 'Nê-hê-mi 8:1-3 - E-xơ-ra đọc Torah và các người Lê-vi giải nghĩa. Dân sự đứng nghe từ sáng đến trưa.', '["Cựu Ước","E-xơ-ra","Lời Chúa"]', 'Nehemiah 8:1-3', 'vi', true, NOW(), NOW()),
('q-neh-012', 'Nehemiah', 5, 7, 11, 'medium', 'multiple_choice_single',
'Nê-hê-mi trách các quan trưởng vì điều gì?',
'["Cho vay lấy lời bất công với dân nghèo", "Không xây tường", "Thờ tượng", "Không cầu nguyện"]',
'[0]', 'Nê-hê-mi 5:7 - Nê-hê-mi bảo vệ dân nghèo khỏi bị bóc lột bởi chính người cùng dân tộc.', '["Cựu Ước","Nê-hê-mi","Công bằng"]', 'Nehemiah 5:7-11', 'vi', true, NOW(), NOW()),
('q-neh-013', 'Nehemiah', 13, 15, 18, 'easy', 'multiple_choice_single',
'Nê-hê-mi cấm điều gì vào ngày Sa-bát?',
'["Buôn bán và vận chuyển hàng hóa", "Nấu ăn", "Đi bộ", "Nói chuyện"]',
'[0]', 'Nê-hê-mi 13:15-19 - Nê-hê-mi đóng cổng thành trước ngày Sa-bát để ngăn thương gia buôn bán.', '["Cựu Ước","Nê-hê-mi","Sa-bát"]', 'Nehemiah 13:15-18', 'vi', true, NOW(), NOW()),
('q-neh-014', 'Nehemiah', 2, 11, 16, 'easy', 'multiple_choice_single',
'Nê-hê-mi làm gì ban đêm trước khi tuyên bố kế hoạch xây tường?',
'["Bí mật đi xem xét tình trạng tường thành", "Cầu nguyện", "Họp với quan trưởng", "Ngủ nghỉ"]',
'[0]', 'Nê-hê-mi 2:13 - Nê-hê-mi bí mật khảo sát tường thành ban đêm để nắm rõ tình hình trước khi hành động.', '["Cựu Ước","Nê-hê-mi","Chuẩn bị"]', 'Nehemiah 2:11-16', 'vi', true, NOW(), NOW()),
('q-neh-015', 'Nehemiah', 12, 43, 43, 'easy', 'multiple_choice_single',
'Khi tường thành hoàn tất, dân sự làm gì?',
'["Dâng tế lễ và vui mừng, tiếng vui nghe xa", "Im lặng tạ ơn", "Ăn chay", "Khóc vì cảm động"]',
'[0]', 'Nê-hê-mi 12:43 - Ngày hôm đó họ dâng của tế lễ lớn và vui mừng vì Chúa cho họ vui. Tiếng nghe từ xa.', '["Cựu Ước","Nê-hê-mi","Vui mừng"]', 'Nehemiah 12:43', 'vi', true, NOW(), NOW()),

-- ==================== ESTHER ====================
('q-est-002', 'Esther', 1, 10, 12, 'easy', 'multiple_choice_single',
'Tại sao hoàng hậu Vát-ti bị phế truất?',
'["Từ chối đến khi vua gọi trong tiệc rượu", "Phản bội vua", "Bệnh tật", "Muốn làm nữ hoàng khác"]',
'[0]', 'E-xơ-tê 1:12 - Hoàng hậu Vát-ti từ chối đến trước vua. Điều này mở đường cho E-xơ-tê trở thành hoàng hậu.', '["Cựu Ước","E-xơ-tê","Chủ quyền"]', 'Esther 1:10-12', 'vi', true, NOW(), NOW()),
('q-est-003', 'Esther', 2, 7, 7, 'easy', 'multiple_choice_single',
'E-xơ-tê là người dân tộc nào?',
'["Do-thái (gốc phái Bên-gia-min)", "Ba-tư", "Ai-cập", "Ba-by-lôn"]',
'[0]', 'E-xơ-tê 2:5-7 - Tên Do-thái là Ha-đa-sa. E-xơ-tê (Esther) là tên Ba-tư. Mồ côi được Mạc-đô-chê nuôi.', '["Cựu Ước","E-xơ-tê","Thân thế"]', 'Esther 2:7', 'vi', true, NOW(), NOW()),
('q-est-004', 'Esther', 2, 17, 17, 'easy', 'multiple_choice_single',
'E-xơ-tê được chọn làm hoàng hậu thay cho ai?',
'["Vát-ti", "Sê-re", "Mi-ri-am", "Không ai"]',
'[0]', 'E-xơ-tê 2:17 - Vua yêu E-xơ-tê hơn tất cả và đặt vương miện trên đầu bà.', '["Cựu Ước","E-xơ-tê","Hoàng hậu"]', 'Esther 2:17', 'vi', true, NOW(), NOW()),
('q-est-005', 'Esther', 3, 1, 6, 'easy', 'multiple_choice_single',
'Ha-man muốn tiêu diệt dân Do-thái vì lý do gì?',
'["Vì Mạc-đô-chê từ chối quỳ lạy hắn", "Vì dân Do-thái không đóng thuế", "Vì họ thờ thần khác", "Vì họ mạnh hơn"]',
'[0]', 'E-xơ-tê 3:5-6 - Mạc-đô-chê từ chối quỳ lạy Ha-man. Sự kiêu ngạo của Ha-man khiến hắn muốn giết cả dân tộc.', '["Cựu Ước","Ha-man","Kiêu ngạo"]', 'Esther 3:1-6', 'vi', true, NOW(), NOW()),
('q-est-006', 'Esther', 3, 7, 7, 'medium', 'multiple_choice_single',
'Ha-man bốc thăm (Pu-rim) để chọn ngày nào tiêu diệt dân Do-thái?',
'["Ngày 13 tháng 12 (A-đa)", "Ngày 1 tháng 1", "Ngày 14 tháng 1", "Ngày 10 tháng 7"]',
'[0]', 'E-xơ-tê 3:7,13 - Từ "Pu-rim" (bốc thăm) trở thành tên lễ hội kỷ niệm sự giải cứu.', '["Cựu Ước","Pu-rim","Lễ hội"]', 'Esther 3:7', 'vi', true, NOW(), NOW()),
('q-est-008', 'Esther', 4, 16, 16, 'medium', 'multiple_choice_single',
'E-xơ-tê xin dân sự làm gì trước khi bà vào gặp vua không được mời?',
'["Kiêng ăn 3 ngày 3 đêm", "Cầu nguyện 7 ngày", "Dâng của lễ", "Chạy trốn"]',
'[0]', 'E-xơ-tê 4:16 - E-xơ-tê sẵn sàng chết: "Nếu phải chết thì tôi chết." Can đảm từ đức tin.', '["Cựu Ước","E-xơ-tê","Can đảm"]', 'Esther 4:16', 'vi', true, NOW(), NOW()),
('q-est-009', 'Esther', 5, 2, 3, 'easy', 'multiple_choice_single',
'Khi E-xơ-tê vào gặp vua không được mời, vua làm gì?',
'["Đưa cây trượng vàng ra cho bà chạm vào (chấp nhận)", "Giận dữ", "Đuổi bà ra", "Phó mặc"]',
'[0]', 'E-xơ-tê 5:2 - Vua đưa trượng vàng = chấp nhận và ban ân từ. Chúa bảo vệ E-xơ-tê.', '["Cựu Ước","E-xơ-tê","Bảo vệ"]', 'Esther 5:2-3', 'vi', true, NOW(), NOW()),
('q-est-010', 'Esther', 6, 1, 3, 'hard', 'multiple_choice_single',
'Đêm trước khi Ha-man định treo cổ Mạc-đô-chê, điều "ngẫu nhiên" nào xảy ra?',
'["Vua mất ngủ và đọc sách sử ký, phát hiện Mạc-đô-chê chưa được thưởng", "Vua mơ thấy", "Thiên sứ báo", "Tin từ xa đến"]',
'[0]', 'E-xơ-tê 6:1-2 - Chúa điều khiển sự kiện "ngẫu nhiên" để bảo vệ dân Ngài. Không có chữ "Chúa" trong sách nhưng sự quan phòng ở khắp nơi.', '["Cựu Ước","Chủ quyền","E-xơ-tê"]', 'Esther 6:1-3', 'vi', true, NOW(), NOW()),
('q-est-011', 'Esther', 7, 3, 4, 'easy', 'multiple_choice_single',
'Tại tiệc rượu, E-xơ-tê xin vua điều gì?',
'["Cứu mạng bà và dân tộc bà", "Đất đai", "Vàng bạc", "Quyền lực"]',
'[0]', 'E-xơ-tê 7:3-4 - E-xơ-tê bày tỏ thân phận Do-thái và tố cáo Ha-man. Sự can đảm cứu cả dân tộc.', '["Cựu Ước","E-xơ-tê","Can đảm"]', 'Esther 7:3-4', 'vi', true, NOW(), NOW()),
('q-est-012', 'Esther', 7, 10, 10, 'easy', 'multiple_choice_single',
'Ha-man bị treo cổ trên cái gì?',
'["Mộc treo chính hắn chuẩn bị cho Mạc-đô-chê", "Mộc treo trong ngục", "Cây lớn", "Tường thành"]',
'[0]', 'E-xơ-tê 7:10 - Sự ảo ngay: Ha-man bị treo trên chính cái mộc hắn làm cho Mạc-đô-chê. Ai đào hố sẽ sa vào đó.', '["Cựu Ước","Ha-man","Công bằng"]', 'Esther 7:10', 'vi', true, NOW(), NOW()),
('q-est-013', 'Esther', 8, 11, 11, 'medium', 'multiple_choice_single',
'Vua không thể rút lại chiếu chỉ của Ha-man nhưng cho phép dân Do-thái làm gì?',
'["Tự bảo vệ và chống lại kẻ tấn công họ", "Bỏ trốn", "Náu trốn", "Xin ân tứ"]',
'[0]', 'E-xơ-tê 8:11 - Luật Ba-tư không thể rút lại, nhưng vua ban chiếu chỉ mới cho phép dân Do-thái tự vệ.', '["Cựu Ước","E-xơ-tê","Giải cứu"]', 'Esther 8:11', 'vi', true, NOW(), NOW()),
('q-est-015', 'Esther', 10, 3, 3, 'easy', 'multiple_choice_single',
'Cuối sách, Mạc-đô-chê trở thành gì?',
'["Tể tướng (người thứ nhì sau vua)", "Vua", "Tướng quân", "Thầy tế lễ"]',
'[0]', 'E-xơ-tê 10:3 - Từ người bị đe dọa treo cổ thành tể tướng. Chúa đổi ngược tình thế cho dân Ngài.', '["Cựu Ước","Mạc-đô-chê","Cất nhắc"]', 'Esther 10:3', 'vi', true, NOW(), NOW());
