-- Supplementary: Psalms, Proverbs, Ecclesiastes, Job, Song of Songs

-- ==================== PSALMS ====================
INSERT IGNORE INTO questions (id, book, chapter, verse_start, verse_end, difficulty, type, content, options, correct_answer, explanation, tags, source, language, is_active, created_at, updated_at) VALUES
('q-psa-009', 'Psalms', 103, 12, 12, 'easy', 'multiple_choice_single',
'Thi 103:12 nói Chúa cắt tội lỗi xa bao nhiêu?',
'["Xa như phương đông cách phương tây", "70 lần 7", "Muôn đời", "Đến tận cùng đất"]',
'[0]', 'Phương đông và phương tây không bao giờ gặp nhau - tội lỗi đã bị xóa bỏ hoàn toàn.', '["Cựu Ước","Thi thiên","Tha thứ"]', 'Psalms 103:12', 'vi', true, NOW(), NOW()),
('q-psa-010', 'Psalms', 19, 1, 1, 'easy', 'multiple_choice_single',
'Thi 19:1 nói trời kể ra điều gì của Đức Chúa Trời?',
'["Sự vinh hiển", "Sự phán xét", "Sự khôn ngoan", "Sự giàu có"]',
'[0]', 'Thi 19:1 - Các tầng trời rao truyền công việc tay Ngài. Thiên nhiên là bằng chứng về Đấng Sáng Tạo.', '["Cựu Ước","Thi thiên","Sáng tạo"]', 'Psalms 19:1', 'vi', true, NOW(), NOW()),
('q-psa-012', 'Psalms', 34, 8, 8, 'easy', 'multiple_choice_single',
'Thi 34:8: "Hãy ___ xem Đức Giê-hô-va tốt lành dường bao!"',
'["Nếm thử", "Suy nghĩ", "Lắng nghe", "Nhìn"]',
'[0]', 'Thi 34:8 - Hãy nếm thử (trải nghiệm) sự tốt lành của Chúa. Đức tin cần trải nghiệm cá nhân.', '["Cựu Ước","Thi thiên","Trải nghiệm"]', 'Psalms 34:8', 'vi', true, NOW(), NOW()),
('q-psa-013', 'Psalms', 37, 4, 4, 'easy', 'multiple_choice_single',
'Thi 37:4: "Hãy lấy Đức Giê-hô-va làm điều ___" thì Ngài sẽ ban cho điều lòng ao ước',
'["Vui thích", "Đầu tiên", "Quan trọng", "Duy nhất"]',
'[0]', 'Thi 37:4 - Khi vui thích trong Chúa, Ngài đổi mới lòng ao ước của chúng ta cho phù hợp ý Ngài.', '["Cựu Ước","Thi thiên","Vui thích"]', 'Psalms 37:4', 'vi', true, NOW(), NOW()),
('q-psa-014', 'Psalms', 91, 1, 2, 'easy', 'multiple_choice_single',
'Thi 91 mô tả người nương náu nơi Chúa được bảo vệ khỏi điều gì?',
'["Tất cả: ôn dịch, mũi tên, bóng tối, tai vạ", "Chỉ bệnh tật", "Chỉ chiến tranh", "Chỉ kẻ thù"]',
'[0]', 'Thi 91:3-10 - Bài thi thiên về sự bảo vệ toàn diện của Chúa cho người tin cậy Ngài.', '["Cựu Ước","Thi thiên","Bảo vệ"]', 'Psalms 91:1-2', 'vi', true, NOW(), NOW()),

-- ==================== PROVERBS ====================
('q-pro-006', 'Proverbs', 4, 23, 23, 'easy', 'multiple_choice_single',
'Châm 4:23 dạy chúng ta phải gìn giữ gì hơn hết?',
'["Tâm lòng (lòng mình)", "Tiền bạc", "Sức khỏe", "Danh tiếng"]',
'[0]', 'Châm 4:23 - Hãy gìn giữ lòng con hơn hết, vì các nguồn sự sống đó mà ra.', '["Cựu Ước","Khôn ngoan","Tâm lòng"]', 'Proverbs 4:23', 'vi', true, NOW(), NOW()),
('q-pro-007', 'Proverbs', 6, 6, 8, 'easy', 'multiple_choice_single',
'Châm ngôn khuyên kẻ lười biếng học tập từ con vật nào?',
'["Con kiến", "Con ong", "Con chim", "Con sóc"]',
'[0]', 'Châm 6:6 - Hãy đến xem con kiến, hỡi kẻ lười biếng ơi. Nó tích trữ lương thực dù không có chỉ huy.', '["Cựu Ước","Khôn ngoan","Siêu năng"]', 'Proverbs 6:6-8', 'vi', true, NOW(), NOW()),
('q-pro-009', 'Proverbs', 11, 2, 2, 'easy', 'multiple_choice_single',
'Châm 11:2: "Khi sự kiêu ngạo đến, thì sự ___ cũng đến"',
'["Sỉ nhục", "Thành công", "Giàu có", "Quyền lực"]',
'[0]', 'Châm 11:2 - Kiêu ngạo dẫn đến sỉ nhục. Khiêm nhường mới mang lại sự khôn ngoan.', '["Cựu Ước","Khôn ngoan","Khiêm nhường"]', 'Proverbs 11:2', 'vi', true, NOW(), NOW()),
('q-pro-010', 'Proverbs', 12, 1, 1, 'easy', 'multiple_choice_single',
'Châm 12:1 nói ai là người ngu dại?',
'["Kẻ ghét sự sửa phạt", "Kẻ không học", "Kẻ nghèo", "Kẻ trẻ"]',
'[0]', 'Châm 12:1 - Ai yêu sự sửa phạt thì yêu tri thức, kẻ ghét sự trách phạt là ngu dại.', '["Cựu Ước","Khôn ngoan","Sửa phạt"]', 'Proverbs 12:1', 'vi', true, NOW(), NOW()),
('q-pro-011', 'Proverbs', 15, 1, 1, 'easy', 'multiple_choice_single',
'Châm 15:1 dạy: "Lời đáp mềm làm ___"',
'["Người tan cơn giận", "Người hòa nhã", "Người khôn ngoan", "Người vui vẻ"]',
'[0]', 'Châm 15:1 - Lời đáp mềm làm người tan cơn giận, nhưng lời xốc xả trở sự nóng giận.', '["Cựu Ước","Khôn ngoan","Lời nói"]', 'Proverbs 15:1', 'vi', true, NOW(), NOW()),
('q-pro-013', 'Proverbs', 16, 18, 18, 'easy', 'multiple_choice_single',
'Châm 16:18: "Sự kiêu ngạo đi trước sự ___"',
'["Bại hoại", "Thành công", "Giàu có", "Khôn ngoan"]',
'[0]', 'Châm 16:18 - Sự kiêu ngạo đi trước sự bại hoại, tính tự phụ đi trước sự sa ngã.', '["Cựu Ước","Khôn ngoan","Kiêu ngạo"]', 'Proverbs 16:18', 'vi', true, NOW(), NOW()),
('q-pro-014', 'Proverbs', 18, 24, 24, 'medium', 'multiple_choice_single',
'Châm 18:24 nói về người bạn như thế nào?',
'["Có bạn thân hơn anh em ruột", "Bạn nhiều là tốt", "Bạn ít là đủ", "Không cần bạn"]',
'[0]', 'Châm 18:24 - Chất lượng hơn số lượng. Một bạn thân thật còn gần gũi hơn anh em ruột.', '["Cựu Ước","Khôn ngoan","Tình bạn"]', 'Proverbs 18:24', 'vi', true, NOW(), NOW()),
('q-pro-015', 'Proverbs', 14, 12, 12, 'medium', 'multiple_choice_single',
'Châm 14:12: "Có một con đường coi dường trước mặt người ta nhưng cuối cùng là đường ___"',
'["Sự chết", "Giàu có", "Thành công", "Bình an"]',
'[0]', 'Châm 14:12 - Không phải mọi con đường nhìn đúng đều đúng thật. Cần sự hướng dẫn của Chúa.', '["Cựu Ước","Khôn ngoan","Sự chọn lựa"]', 'Proverbs 14:12', 'vi', true, NOW(), NOW()),

-- ==================== ECCLESIASTES ====================
('q-ecc-003', 'Ecclesiastes', 1, 2, 2, 'easy', 'multiple_choice_single',
'Câu nói nổi tiếng của sách Truyền Đạo là gì?',
'["Hư không của hư không, thảy đều hư không", "Mọi sự đều tốt", "Hãy vui hưởng", "Thời gian là vàng"]',
'[0]', 'Truyền đạo 1:2 - Hebel (hư không/hơi nước) nói lên tính tạm thời và vô nghĩa của đời sống dưới mặt trời khi không có Chúa.', '["Cựu Ước","Truyền đạo","Hư không"]', 'Ecclesiastes 1:2', 'vi', true, NOW(), NOW()),
('q-ecc-004', 'Ecclesiastes', 3, 11, 11, 'medium', 'multiple_choice_single',
'Truyền đạo 3:11 nói Chúa đặt gì trong lòng người ta?',
'["Sự đời đời (ý niệm về sự vĩnh cửu)", "Sự khôn ngoan", "Sự vui vẻ", "Sự sợ hãi"]',
'[0]', 'Truyền đạo 3:11 - Chúa đặt sự đời đời trong lòng người. Chúng ta được tạo dựng để hướng về vĩnh cửu.', '["Cựu Ước","Truyền đạo","Vĩnh cửu"]', 'Ecclesiastes 3:11', 'vi', true, NOW(), NOW()),
('q-ecc-005', 'Ecclesiastes', 4, 9, 10, 'easy', 'multiple_choice_single',
'Truyền đạo 4:9 nói gì về việc làm chung?',
'["Hai người hơn một vì họ được công giá tốt", "Một người tốt hơn", "Ba người là tốt nhất", "Không khác biệt"]',
'[0]', 'Truyền đạo 4:9-10 - Hai người hơn một. Nếu người này té, người kia đỡ dậy. Giá trị của tình bạn và cộng đồng.', '["Cựu Ước","Truyền đạo","Cộng đồng"]', 'Ecclesiastes 4:9-10', 'vi', true, NOW(), NOW()),
('q-ecc-007', 'Ecclesiastes', 5, 10, 10, 'easy', 'multiple_choice_single',
'Truyền đạo 5:10 nói gì về tiền bạc?',
'["Ai yêu bạc không bao giờ đủ bạc", "Tiền mang lại hạnh phúc", "Hãy tích trữ nhiều", "Tiền là gốc của mọi ác"]',
'[0]', 'Truyền đạo 5:10 - Tiền bạc không bao giờ đủ cho người yêu nó. Sự tham lam không bao giờ thỏa mãn.', '["Cựu Ước","Truyền đạo","Tiền bạc"]', 'Ecclesiastes 5:10', 'vi', true, NOW(), NOW()),
('q-ecc-008', 'Ecclesiastes', 7, 2, 2, 'hard', 'multiple_choice_single',
'Tại sao Sa-lo-mon nói đến nhà có tang tốt hơn đến nhà ăn tiệc?',
'["Vì ở đó người ta suy nghĩ về lẽ cuối cùng và sống khôn ngoan hơn", "Vì rẻ hơn", "Vì yên tĩnh hơn", "Vì tôn giáo hơn"]',
'[0]', 'Truyền đạo 7:2 - Đối diện với sự chết giúp chúng ta suy nghĩ nghiêm túc về ý nghĩa cuộc sống.', '["Cựu Ước","Truyền đạo","Sự chết"]', 'Ecclesiastes 7:2', 'vi', true, NOW(), NOW()),
('q-ecc-009', 'Ecclesiastes', 9, 10, 10, 'easy', 'multiple_choice_single',
'Truyền đạo 9:10 khuyên làm việc như thế nào?',
'["Hết sức làm mọi việc tay mình làm", "Làm vừa đủ", "Chỉ làm khi thích", "Để người khác làm"]',
'[0]', 'Truyền đạo 9:10 - Hãy hết lòng làm việc vì trong Âm phủ không có việc làm hay tri thức nữa.', '["Cựu Ước","Truyền đạo","Cần cù"]', 'Ecclesiastes 9:10', 'vi', true, NOW(), NOW()),
('q-ecc-011', 'Ecclesiastes', 11, 4, 4, 'easy', 'multiple_choice_single',
'Truyền đạo 11:4 cảnh báo điều gì?',
'["Kẻ ngóng gió sẽ không gieo, kẻ nhìn mây sẽ không gặt", "Hãy chờ thời tiết tốt", "Hãy kế hoạch kỹ", "Đừng vội vàng"]',
'[0]', 'Truyền đạo 11:4 - Đừng chờ điều kiện hoàn hảo, hãy hành động ngay. Chờ đợi mãi sẽ không bao giờ bắt đầu.', '["Cựu Ước","Truyền đạo","Hành động"]', 'Ecclesiastes 11:4', 'vi', true, NOW(), NOW()),
('q-ecc-012', 'Ecclesiastes', 12, 1, 1, 'easy', 'multiple_choice_single',
'Truyền đạo 12:1 khuyên hãy nhớ Đấng Sáng Tạo khi nào?',
'["Trong những ngày thanh xuân (trẻ tuổi)", "Khi già", "Khi gặp khó khăn", "Khi thành công"]',
'[0]', 'Truyền đạo 12:1 - Hãy nhớ Chúa khi còn trẻ, đừng chờ đến khi già mới tìm kiếm Ngài.', '["Cựu Ước","Truyền đạo","Thanh xuân"]', 'Ecclesiastes 12:1', 'vi', true, NOW(), NOW()),
('q-ecc-014', 'Ecclesiastes', 7, 8, 8, 'easy', 'multiple_choice_single',
'Truyền đạo 7:8: "Sự cuối cùng của một việc hơn sự ___ nó"',
'["Bắt đầu", "Giữa", "Kế hoạch", "Ý tưởng"]',
'[0]', 'Truyền đạo 7:8 - Sự kiên nhẫn tốt hơn sự kiêu ngạo. Hãy đừng xét đoán quá sớm.', '["Cựu Ước","Truyền đạo","Kiên nhẫn"]', 'Ecclesiastes 7:8', 'vi', true, NOW(), NOW()),
('q-ecc-015', 'Ecclesiastes', 12, 7, 7, 'medium', 'multiple_choice_single',
'Truyền đạo 12:7 nói khi chết, thần linh trở về đâu?',
'["Trở về cùng Đức Chúa Trời là Đấng đã ban cho", "Tan biến", "Ở lại đất", "Đi đến Âm phủ"]',
'[0]', 'Truyền đạo 12:7 - Bụi trở về bụi, thần linh trở về cùng Chúa. Con người có phần thuộc linh vĩnh cửu.', '["Cựu Ước","Truyền đạo","Sự chết"]', 'Ecclesiastes 12:7', 'vi', true, NOW(), NOW()),

-- ==================== JOB ====================
('q-job-001', 'Job', 1, 1, 1, 'easy', 'multiple_choice_single',
'Kinh Thánh mô tả Gióp là người như thế nào?',
'["Trọn vẹn, chính trực, kính sợ Chúa, lánh xa điều ác", "Giàu nhất", "Khôn ngoan nhất", "Mạnh nhất"]',
'[0]', 'Gióp 1:1 - Gióp là người trọn vẹn và ngay thẳng, kính sợ Đức Chúa Trời và lánh xa điều ác.', '["Cựu Ước","Gióp","Công bình"]', 'Job 1:1', 'vi', true, NOW(), NOW()),
('q-job-002', 'Job', 1, 9, 11, 'medium', 'multiple_choice_single',
'Sa-tan tố cáo Gióp kính sợ Chúa vì lý do gì?',
'["Vì Chúa bảo vệ và ban phúc, không phải tự tâm lòng", "Vì Gióp sợ hình phạt", "Vì Gióp muốn được khen", "Vì Gióp ngu dốt"]',
'[0]', 'Gióp 1:9-11 - Sa-tan tố cáo rằng Gióp chỉ tin vì được lợi. Chúa cho phép thử thách để chứng minh đức tin thật.', '["Cựu Ước","Gióp","Thử thách"]', 'Job 1:9-11', 'vi', true, NOW(), NOW()),
('q-job-004', 'Job', 2, 9, 10, 'easy', 'multiple_choice_single',
'Vợ Gióp nói ông nên làm gì? Gióp đáp thế nào?',
'["Vợ nói: rủa Chúa đi rồi chết. Gióp: chúng ta nhận phúc thì không nhận họa sao?", "Cả hai khóc", "Cả hai cầu nguyện", "Cả hai bỏ cuộc"]',
'[0]', 'Gióp 2:9-10 - Gióp từ chối bỏ đức tin dù người thân nhất khuyên ông từ bỏ.', '["Cựu Ước","Gióp","Đức tin"]', 'Job 2:9-10', 'vi', true, NOW(), NOW()),
('q-job-005', 'Job', 13, 15, 15, 'medium', 'multiple_choice_single',
'Gióp tuyên bố điều gì dù đang chịu khổ?',
'["Dù Ngài giết tôi, tôi vẫn tin cậy Ngài", "Tôi sẽ bỏ Chúa", "Tôi vô tội", "Chúa bất công"]',
'[0]', 'Gióp 13:15 - Đức tin không điều kiện: tin cậy Chúa dù trong hoàn cảnh xấu nhất.', '["Cựu Ước","Gióp","Đức tin"]', 'Job 13:15', 'vi', true, NOW(), NOW()),
('q-job-006', 'Job', 19, 25, 26, 'easy', 'multiple_choice_single',
'Gióp tuyên bố: "Tôi biết rằng Đấng ___ tôi hằng sống"',
'["Cứu chuộc", "Sáng tạo", "Phán xét", "Bảo vệ"]',
'[0]', 'Gióp 19:25 - Giữa khổ nạn, Gióp tuyên bố tin vào Đấng Cứu Chuộc hằng sống và sự phục sinh.', '["Cựu Ước","Gióp","Cứu chuộc"]', 'Job 19:25-26', 'vi', true, NOW(), NOW()),
('q-job-007', 'Job', 38, 1, 4, 'medium', 'multiple_choice_single',
'Chúa trả lời Gióp từ đâu?',
'["Từ trong cơn gió lốc", "Từ trời", "Từ bụi gai cháy", "Từ đám mây"]',
'[0]', 'Gióp 38:1 - Chúa phán từ gió lốc, hỏi Gióp nhiều câu hỏi về sáng tạo để cho thấy sự khôn ngoan vô hạn của Ngài.', '["Cựu Ước","Gióp","Chủ quyền"]', 'Job 38:1-4', 'vi', true, NOW(), NOW()),
('q-job-009', 'Job', 40, 4, 5, 'easy', 'multiple_choice_single',
'Sau khi Chúa phán, Gióp phản ứng thế nào?',
'["Lấy tay bịt miệng, không đáp nữa", "Tranh luận tiếp", "Giận dữ", "Bỏ chạy"]',
'[0]', 'Gióp 40:4-5 - Gióp nhận ra sự nhỏ bé của mình trước sự vĩ đại của Chúa và im lặng.', '["Cựu Ước","Gióp","Khiêm nhường"]', 'Job 40:4-5', 'vi', true, NOW(), NOW()),
('q-job-010', 'Job', 42, 5, 6, 'medium', 'multiple_choice_single',
'Gióp nói: "Trước tai tôi nghe đồn về Chúa, nhưng bây giờ ___"',
'["Mắt tôi đã thấy Ngài", "Tôi hiểu Ngài", "Tôi tin Ngài", "Tôi biết Ngài"]',
'[0]', 'Gióp 42:5 - Từ tin nghe nói đến trải nghiệm cá nhân. Khổ nạn dẫn Gióp đến sự hiểu biết sâu hơn về Chúa.', '["Cựu Ước","Gióp","Trải nghiệm"]', 'Job 42:5-6', 'vi', true, NOW(), NOW()),
('q-job-011', 'Job', 42, 10, 12, 'easy', 'multiple_choice_single',
'Cuối cùng Chúa ban cho Gióp bao nhiêu so với trước?',
'["Gấp đôi mọi thứ", "Bằng cũ", "Ít hơn", "Gấp ba"]',
'[0]', 'Gióp 42:10 - Chúa phục hồi gấp đôi. Chúa thương người kiên nhẫn chịu đựng (Gia-cơ 5:11).', '["Cựu Ước","Gióp","Phục hồi"]', 'Job 42:10-12', 'vi', true, NOW(), NOW()),
('q-job-012', 'Job', 28, 28, 28, 'easy', 'multiple_choice_single',
'Gióp 28:28 kết luận sự khôn ngoan thật là gì?',
'["Kính sợ Chúa và lánh xa điều ác", "Học nhiều", "Kinh nghiệm", "Tri thức"]',
'[0]', 'Gióp 28:28 - Giống như Châm 1:7 và Truyền đạo 12:13. Sự khôn ngoan bắt đầu và kết thúc ở sự kính sợ Chúa.', '["Cựu Ước","Gióp","Khôn ngoan"]', 'Job 28:28', 'vi', true, NOW(), NOW()),
('q-job-014', 'Job', 5, 17, 17, 'medium', 'multiple_choice_single',
'Ê-li-pha nói: "Phước thay người nào Đức Chúa Trời ___"',
'["Sửa phạt, chớ khinh dể sự trách phạt của Đấng Toàn Năng", "Yêu thương", "Ban phúc", "Bảo vệ"]',
'[0]', 'Gióp 5:17 - Sự trách phạt của Chúa là dấu hiệu tình yêu, không phải sự bỏ rơi (Hê 12:6).', '["Cựu Ước","Gióp","Sửa phạt"]', 'Job 5:17', 'vi', true, NOW(), NOW()),
('q-job-015', 'Job', 42, 7, 8, 'hard', 'multiple_choice_single',
'Chúa trách 3 bạn của Gióp vì lý do gì?',
'["Họ không nói đúng về Chúa như Gióp", "Họ không cầu nguyện", "Họ bỏ Gióp", "Họ thờ tượng"]',
'[0]', 'Gióp 42:7 - Dù Gióp than van, ông vẫn trung thực với Chúa. 3 bạn có giáo lý gọn gàng nhưng sai về bản tính Chúa.', '["Cựu Ước","Gióp","Thần học"]', 'Job 42:7-8', 'vi', true, NOW(), NOW());
