-- Supplementary: Exodus, Leviticus, Numbers, Deuteronomy (to reach 15 each)

-- ==================== EXODUS ====================
INSERT IGNORE INTO questions (id, book, chapter, verse_start, verse_end, difficulty, type, content, options, correct_answer, explanation, tags, source, language, is_active, created_at, updated_at) VALUES
('q-exo-011', 'Exodus', 15, 20, 21, 'easy', 'multiple_choice_single',
'Ai đã hát bài ca chiến thắng sau khi vượt Biển Đỏ?',
'["Mi-ri-am, chị Moi-se", "Moi-se", "A-ron", "Gio-sue"]',
'[0]', 'Xuất 15:20 - Mi-ri-am cầm trống cơm và dẫn đầu phụ nữ hát ngợi khen Chúa.', '["Cựu Ước","Ngợi khen","Mi-ri-am"]', 'Exodus 15:20-21', 'vi', true, NOW(), NOW()),
('q-exo-012', 'Exodus', 17, 11, 12, 'medium', 'multiple_choice_single',
'Khi Moi-se giơ tay lên trong trận đánh A-ma-lec, điều gì xảy ra?',
'["Y-so-ra-en thắng; khi hạ tay xuống thì thua", "Lửa từ trời rơi xuống", "Nước từ đá chảy ra", "Đất rung chuyển"]',
'[0]', 'Xuất 17:11 - A-ron và Ho-ro đỡ tay Moi-se để Y-so-ra-en thắng. Hình ảnh về sự cầu nguyện liên tục.', '["Cựu Ước","Chiến trận","Cầu nguyện"]', 'Exodus 17:11-12', 'vi', true, NOW(), NOW()),
('q-exo-013', 'Exodus', 25, 10, 22, 'hard', 'multiple_choice_single',
'Hòm Giao Ước chứa những gì bên trong?',
'["Hai bảng đá, bình ma-na, gậy A-ron đã nảy mầm", "Chỉ hai bảng đá", "Chỉ bình ma-na", "Sách luật pháp"]',
'[0]', 'Hê-bơ-rơ 9:4 liệt kê 3 vật trong Hòm: hai bảng luật, bình ma-na vàng, và gậy A-ron nảy mầm.', '["Cựu Ước","Hòm Giao Ước","Đền tạm"]', 'Exodus 25:10-22', 'vi', true, NOW(), NOW()),
('q-exo-014', 'Exodus', 32, 1, 4, 'easy', 'multiple_choice_single',
'Khi Moi-se lên núi Si-nai lâu, dân sự làm tượng gì để thờ?',
'["Bò con vàng", "Tượng rắn", "Cột đá", "Cây lớn"]',
'[0]', 'Xuất 32:4 - A-ron làm bò con vàng từ vàng của dân sự. Đây là tội thờ hình tượng lớn nhất của Y-so-ra-en.', '["Cựu Ước","Hình tượng","Tội lỗi"]', 'Exodus 32:1-4', 'vi', true, NOW(), NOW()),

-- ==================== LEVITICUS ====================
('q-lev-004', 'Leviticus', 1, 3, 4, 'easy', 'multiple_choice_single',
'Của lễ thiêu phải là thú vật như thế nào?',
'["Không tì vết, con đực", "Bất kỳ con vật nào", "Con cái nhất", "Con lớn nhất"]',
'[0]', 'Lê-vi 1:3 - Của lễ thiêu phải là con đực không tì vết. Hình bóng của Chúa Giê-su toàn hảo.', '["Cựu Ước","Tế lễ","Của lễ"]', 'Leviticus 1:3-4', 'vi', true, NOW(), NOW()),
('q-lev-005', 'Leviticus', 11, 1, 8, 'easy', 'multiple_choice_single',
'Theo luật thánh sạch, thú vật nào được ăn?',
'["Thú vật có móng chẻ và nhơi lại", "Tất cả thú vật", "Chỉ thú vật lớn", "Thú vật có sừng"]',
'[0]', 'Lê-vi 11:3 - Thú vật thánh sạch phải có hai điều kiện: móng chẻ và nhơi lại (như bò, dê, cừu).', '["Cựu Ước","Luật pháp","Thánh sạch"]', 'Leviticus 11:1-8', 'vi', true, NOW(), NOW()),
('q-lev-006', 'Leviticus', 23, 5, 8, 'medium', 'multiple_choice_single',
'Lễ Vượt Qua được tổ chức vào tháng mấy trong lịch Do-thái?',
'["Tháng giêng (Nisan), ngày 14", "Tháng 7, ngày 1", "Tháng 3, ngày 6", "Tháng 10, ngày 15"]',
'[0]', 'Lê-vi 23:5 - Ngày 14 tháng giêng là Lễ Vượt Qua của Đức Giê-hô-va.', '["Cựu Ước","Lễ hội","Vượt Qua"]', 'Leviticus 23:5-8', 'vi', true, NOW(), NOW()),
('q-lev-007', 'Leviticus', 23, 15, 16, 'hard', 'multiple_choice_single',
'Lễ Ngũ Tuần (Shavuot) được tổ chức bao ngày sau Lễ Vượt Qua?',
'["50 ngày", "40 ngày", "30 ngày", "7 ngày"]',
'[0]', 'Lê-vi 23:16 - 50 ngày sau ngày Sa-bat của Lễ Vượt Qua. Tân Ước: Đức Thánh Linh giáng lâm đúng ngày này (Công vụ 2).', '["Cựu Ước","Lễ hội","Ngũ Tuần"]', 'Leviticus 23:15-16', 'vi', true, NOW(), NOW()),
('q-lev-008', 'Leviticus', 25, 10, 10, 'medium', 'multiple_choice_single',
'Năm Hoan Hỉ (Jubilee) được tổ chức mỗi bao nhiêu năm?',
'["50 năm", "7 năm", "40 năm", "100 năm"]',
'[0]', 'Lê-vi 25:10 - Mỗi 50 năm là Năm Hoan Hỉ: trả tự do cho nô lệ, trả đất về cho chủ cũ. Biểu tượng sự giải phóng.', '["Cựu Ước","Luật pháp","Hoan Hỉ"]', 'Leviticus 25:10', 'vi', true, NOW(), NOW()),
('q-lev-010', 'Leviticus', 16, 29, 30, 'medium', 'multiple_choice_single',
'Ngày Lễ Chuộc Tội (Yom Kippur) diễn ra vào ngày nào?',
'["Ngày 10 tháng 7", "Ngày 14 tháng 1", "Ngày 1 tháng 7", "Ngày 15 tháng 1"]',
'[0]', 'Lê-vi 16:29 - Ngày 10 tháng bảy là Lễ Chuộc Tội, ngày thánh khiết nhất trong năm.', '["Cựu Ước","Lễ hội","Chuộc tội"]', 'Leviticus 16:29-30', 'vi', true, NOW(), NOW()),
('q-lev-011', 'Leviticus', 23, 34, 36, 'easy', 'multiple_choice_single',
'Lễ Lều Tạm (Sukkot) nhằm kỷ niệm sự kiện gì?',
'["Dân Y-so-ra-en sống trong lều trại 40 năm trong đồng vắng", "Ngày sáng thế", "Lễ gặt mùa", "Ngày vượt Biển Đỏ"]',
'[0]', 'Lê-vi 23:43 - Để con cháu Y-so-ra-en nhớ rằng Chúa cho tổ phụ họ sống trong lều trại khi dân ra khỏi Ai-cập.', '["Cựu Ước","Lễ hội","Đồng vắng"]', 'Leviticus 23:34-36', 'vi', true, NOW(), NOW()),
('q-lev-012', 'Leviticus', 10, 1, 2, 'medium', 'multiple_choice_single',
'Na-dap và A-bi-hu, con A-ron, bị chết vì làm gì?',
'["Dâng lửa lạ trước mặt Chúa mà Ngài không phán định", "Ăn trộm của lễ", "Thờ tượng", "Bỏ trốn"]',
'[0]', 'Lê-vi 10:1-2 - Họ dâng lửa lạ (không được phép) trước mặt Chúa. Lửa từ Chúa phát ra thiêu họ. Bài học về sự tôn kính Chúa.', '["Cựu Ước","Tế lễ","Thánh khiết"]', 'Leviticus 10:1-2', 'vi', true, NOW(), NOW()),
('q-lev-013', 'Leviticus', 4, 2, 3, 'easy', 'multiple_choice_single',
'Của lễ chuộc tội được dâng khi nào?',
'["Khi ai phạm tội không có ý", "Chỉ vào Lễ Chuộc Tội", "Mỗi ngày Sa-bat", "Khi muốn tạ ơn"]',
'[0]', 'Lê-vi 4:2 - Của lễ chuộc tội dành cho người phạm tội vì không biết. Cho thấy Chúa nghiêm túc với mọi tội lỗi.', '["Cựu Ước","Tế lễ","Chuộc tội"]', 'Leviticus 4:2-3', 'vi', true, NOW(), NOW()),
('q-lev-014', 'Leviticus', 26, 3, 6, 'easy', 'multiple_choice_single',
'Lê-vi 26 hứa điều gì nếu dân sự vâng lời Chúa?',
'["Mưa thuận gió hòa, bình an, phúc lành", "Giàu có vô tận", "Chiến thắng mọi kẻ thù", "Sống đời đời"]',
'[0]', 'Lê-vi 26:3-6 - Chúa hứa mưa thuận, mùa màng dồi dào, bình an trong xứ và không còn thú hoang.', '["Cựu Ước","Phúc lành","Vâng lời"]', 'Leviticus 26:3-6', 'vi', true, NOW(), NOW()),

-- ==================== NUMBERS ====================
('q-num-005', 'Numbers', 6, 1, 8, 'medium', 'multiple_choice_single',
'Người Na-xi-re phải kiêng cữ những gì?',
'["Rượu nho, không cắt tóc, không chạm xác chết", "Chỉ kiêng rượu", "Ăn chay", "Sống một mình"]',
'[0]', 'Dân 6:2-7 - Lời hứa Na-xi-re gồm 3 điều: kiêng rượu, không cắt tóc, tránh xác chết. Sam-son là người Na-xi-re nổi tiếng.', '["Cựu Ước","Lời hứa","Na-xi-re"]', 'Numbers 6:1-8', 'vi', true, NOW(), NOW()),
('q-num-006', 'Numbers', 11, 4, 6, 'easy', 'multiple_choice_single',
'Dân Y-so-ra-en ca thán trong đồng vắng vì muốn ăn gì thay vì ma-na?',
'["Thịt, dưa chuột, dưa gang, tỏi, hành", "Bánh mì và phô mai", "Trái cây", "Cá và cơm"]',
'[0]', 'Dân 11:5 - Họ nhớ món ăn ở Ai-cập và chán ngán ma-na. Bài học về lòng biết ơn.', '["Cựu Ước","Đồng vắng","Ca thán"]', 'Numbers 11:4-6', 'vi', true, NOW(), NOW()),
('q-num-007', 'Numbers', 12, 1, 10, 'medium', 'multiple_choice_single',
'Mi-ri-am bị phạt bệnh phung vì làm gì?',
'["Nói nghịch cùng Moi-se", "Thờ tượng", "Ca thán về ma-na", "Bỏ trốn"]',
'[0]', 'Dân 12:1-10 - Mi-ri-am và A-ron nói nghịch Moi-se. Chúa phạt Mi-ri-am bệnh phung 7 ngày. Bài học về tôn trọng người lãnh đạo Chúa chọn.', '["Cựu Ước","Mi-ri-am","Kỷ luật"]', 'Numbers 12:1-10', 'vi', true, NOW(), NOW()),
('q-num-009', 'Numbers', 16, 31, 33, 'easy', 'multiple_choice_single',
'Cô-rê, Đa-than và A-bi-ram bị phạt thế nào vì nổi loạn chống Moi-se?',
'["Đất há miệng nuốt họ sống", "Lửa từ trời thiêu", "Bệnh dịch", "Nước lũ cuốn đi"]',
'[0]', 'Dân 16:32 - Đất há miệng nuốt họ và cả gia đình. Bài học về hậu quả của việc chống lại quyền bính Chúa thiết lập.', '["Cựu Ước","Nổi loạn","Hình phạt"]', 'Numbers 16:31-33', 'vi', true, NOW(), NOW()),
('q-num-010', 'Numbers', 17, 8, 8, 'easy', 'multiple_choice_single',
'Gậy của ai đã nảy mầm, trổ bông và sinh quả hạnh nhân?',
'["Gậy của A-ron", "Gậy của Moi-se", "Gậy của Gio-sue", "Gậy của Ca-lep"]',
'[0]', 'Dân 17:8 - Gậy A-ron nảy mầm để xác nhận ông là thầy tế lễ Chúa chọn.', '["Cựu Ước","A-ron","Tế lễ"]', 'Numbers 17:8', 'vi', true, NOW(), NOW()),
('q-num-011', 'Numbers', 20, 11, 12, 'medium', 'multiple_choice_single',
'Tại sao Moi-se không được vào Đất Hứa?',
'["Đập gậy vào đá thay vì phán truyền với đá", "Vì ông quá già", "Vì dân sự tội lỗi", "Vì ông giết người Ai-cập"]',
'[0]', 'Dân 20:12 - Moi-se đập đá 2 lần thay vì phán truyền. Chúa nói: vì không tin Ta để tôn thánh Ta trước dân.', '["Cựu Ước","Moi-se","Vâng lời"]', 'Numbers 20:11-12', 'vi', true, NOW(), NOW()),
('q-num-012', 'Numbers', 22, 28, 30, 'easy', 'multiple_choice_single',
'Con vật nào đã nói tiếng người với tiên tri Ba-la-am?',
'["Con lừa cái", "Con rắn", "Con chim", "Con dê"]',
'[0]', 'Dân 22:28 - Đức Giê-hô-va mở miệng con lừa và nó nói với Ba-la-am. Thiên sứ Chúa đứng chặn đường.', '["Cựu Ước","Ba-la-am","Phép lạ"]', 'Numbers 22:28-30', 'vi', true, NOW(), NOW()),
('q-num-014', 'Numbers', 27, 18, 20, 'easy', 'multiple_choice_single',
'Ai được chọn làm người kế nhiệm Moi-se lãnh đạo dân Y-so-ra-en?',
'["Gio-sue", "Ca-lep", "A-ron", "Ê-lê-a-xa"]',
'[0]', 'Dân 27:18 - Chúa chọn Gio-sue, người có Thần của Ngài ngự trên, để lãnh đạo dân sự vào Đất Hứa.', '["Cựu Ước","Gio-sue","Lãnh đạo"]', 'Numbers 27:18-20', 'vi', true, NOW(), NOW()),
('q-num-015', 'Numbers', 24, 17, 17, 'hard', 'multiple_choice_single',
'Ba-la-am tiên tri: "Một ngôi sao sẽ mọc từ Gia-cốp." Đây là tiên tri về ai?',
'["Chúa Giê-su Christ - Đấng Cứu Thế", "Vua Đa-vít", "Moi-se", "Gio-sue"]',
'[0]', 'Dân 24:17 - Ngôi sao từ Gia-cốp là tiên tri về Đấng Cứu Thế. Các nhà thông thái theo ngôi sao đến Bết-lê-hem (Mat 2:2).', '["Cựu Ước","Tiên tri","Cứu Thế"]', 'Numbers 24:17', 'vi', true, NOW(), NOW()),

-- ==================== DEUTERONOMY ====================
('q-deu-005', 'Deuteronomy', 8, 3, 3, 'medium', 'multiple_choice_single',
'Tại sao Chúa cho dân ăn ma-na trong đồng vắng?',
'["Để dạy rằng người ta sống không chỉ nhờ bánh mà bởi Lời Chúa", "Vì không có thức ăn khác", "Để thử đức tin", "Vì dân xin"]',
'[0]', 'Phục truyền 8:3 - Chúa Giê-su trích chính câu này khi bị Sa-tan cám dỗ (Mat 4:4).', '["Cựu Ước","Lời Chúa","Bài học"]', 'Deuteronomy 8:3', 'vi', true, NOW(), NOW()),
('q-deu-006', 'Deuteronomy', 7, 6, 6, 'easy', 'multiple_choice_single',
'Chúa chọn dân Y-so-ra-en vì lý do gì?',
'["Vì tình yêu của Ngài và lời hứa với tổ phụ, không phải vì họ đông", "Vì họ đông nhất", "Vì họ tốt lành nhất", "Vì họ mạnh nhất"]',
'[0]', 'Phục truyền 7:7-8 - Chúa chọn Y-so-ra-en không vì họ đông hay giỏi, mà vì tình yêu và lời giao ước.', '["Cựu Ước","Được chọn","Tình yêu"]', 'Deuteronomy 7:6', 'vi', true, NOW(), NOW()),
('q-deu-007', 'Deuteronomy', 10, 12, 13, 'easy', 'multiple_choice_single',
'Phục truyền 10:12 nói Chúa đòi hỏi dân sự điều gì?',
'["Kính sợ Chúa, đi theo đường Ngài, yêu mến và phục vụ Ngài hết lòng", "Xây đền thờ", "Chinh phục các dân tộc", "Dâng nhiều của lễ"]',
'[0]', 'Phục truyền 10:12 - Tóm tắt toàn bộ luật pháp trong một câu: kính sợ, yêu mến và phục vụ Chúa.', '["Cựu Ước","Điều răn","Phục vụ"]', 'Deuteronomy 10:12-13', 'vi', true, NOW(), NOW()),
('q-deu-008', 'Deuteronomy', 11, 18, 19, 'medium', 'multiple_choice_single',
'Moi-se dạy dân sự phải làm gì với Lời Chúa?',
'["Buộc vào tay, đeo trên trán, dạy con cái, viết trên cửa", "Chỉ đọc mỗi Sa-bat", "Chỉ thầy tế lễ học", "Giữ kín trong Hòm Giao Ước"]',
'[0]', 'Phục truyền 11:18-20 - Lời Chúa phải thấm nhập mọi khía cạnh cuộc sống: cá nhân, gia đình, xã hội.', '["Cựu Ước","Lời Chúa","Giáo dục"]', 'Deuteronomy 11:18-19', 'vi', true, NOW(), NOW()),
('q-deu-009', 'Deuteronomy', 28, 1, 6, 'easy', 'multiple_choice_single',
'Phục truyền 28 hứa phúc lành cho ai?',
'["Người vâng giọng Chúa", "Người giàu có", "Thầy tế lễ", "Vua"]',
'[0]', 'Phục truyền 28:1-2 - Nếu vâng giọng Chúa, mọi phúc lành sẽ đến trên người và theo kịp người.', '["Cựu Ước","Phúc lành","Vâng lời"]', 'Deuteronomy 28:1-6', 'vi', true, NOW(), NOW()),
('q-deu-010', 'Deuteronomy', 29, 29, 29, 'hard', 'multiple_choice_single',
'Phục truyền 29:29 phân biệt điều gì?',
'["Những điều kín nhiệm thuộc Chúa, những điều bày tỏ thuộc chúng ta", "Luật pháp và ân điển", "Cựu Ước và Tân Ước", "Trời và đất"]',
'[0]', 'Phục truyền 29:29 - Có những điều Chúa giữ kín và những điều Ngài bày tỏ. Chúng ta chịu trách nhiệm với những gì đã được bày tỏ.', '["Cựu Ước","Thần học","Sự hiểu biết"]', 'Deuteronomy 29:29', 'vi', true, NOW(), NOW()),
('q-deu-011', 'Deuteronomy', 30, 19, 19, 'easy', 'multiple_choice_single',
'Moi-se kêu gọi dân sự chọn điều gì?',
'["Sự sống và phúc lành (thay vì sự chết và rủa sả)", "Đất Hứa", "Vua", "Chiến tranh"]',
'[0]', 'Phục truyền 30:19 - Moi-se đặt trước dân sự hai đường: sự sống và sự chết, phúc lành và rủa sả. Hãy chọn sự sống!', '["Cựu Ước","Sự chọn lựa","Sự sống"]', 'Deuteronomy 30:19', 'vi', true, NOW(), NOW()),
('q-deu-013', 'Deuteronomy', 33, 27, 27, 'easy', 'multiple_choice_single',
'Phục truyền 33:27 mô tả Chúa như thế nào?',
'["Nơi ẩn náu đời đời, cánh tay đời đời ở dưới đỡ", "Vua trên ngôi", "Chiến binh", "Quan án"]',
'[0]', 'Phục truyền 33:27 - Đức Chúa Trời đời đời là nơi ẩn náu người. Cánh tay đời đời ở dưới đỡ người.', '["Cựu Ước","Ẩn náu","Bảo vệ"]', 'Deuteronomy 33:27', 'vi', true, NOW(), NOW()),
('q-deu-014', 'Deuteronomy', 34, 5, 7, 'easy', 'multiple_choice_single',
'Moi-se qua đời ở tuổi bao nhiêu?',
'["120 tuổi", "80 tuổi", "100 tuổi", "150 tuổi"]',
'[0]', 'Phục truyền 34:7 - Moi-se hưởng thọ 120 tuổi. Mắt chưa lòa, sức chưa giảm.', '["Cựu Ước","Moi-se","Cuộc đời"]', 'Deuteronomy 34:5-7', 'vi', true, NOW(), NOW());
