-- Supplementary: Isaiah, Jeremiah, Lamentations, Ezekiel, Daniel, Minor Prophets

-- ==================== ISAIAH ====================
INSERT IGNORE INTO questions (id, book, chapter, verse_start, verse_end, difficulty, type, content, options, correct_answer, explanation, tags, source, language, is_active, created_at, updated_at) VALUES
('q-isa-008', 'Isaiah', 1, 18, 18, 'easy', 'multiple_choice_single',
'E-sai 1:18: "Dù tội lỗi các ngươi như màu đỏ, sẽ trở nên ___"',
'["Trắng như tuyết", "Sạch như nước", "Mới như ban đầu", "Đẹp như hoa"]',
'[0]', 'Chúa hứa tha thứ hoàn toàn, biến đổi tội lỗi đỏ như máu thành trắng như tuyết.', '["Cựu Ước","E-sai","Tha thứ"]', 'Isaiah 1:18', 'vi', true, NOW(), NOW()),
('q-isa-009', 'Isaiah', 6, 1, 3, 'medium', 'multiple_choice_single',
'Sê-ra-phim kêu với nhau điều gì trong khải tượng của E-sai?',
'["Thánh thay, thánh thay, thánh thay là Đức Giê-hô-va vạn quân", "Vinh hiển cho Chúa", "Ha-lê-lu-gia", "A-men"]',
'[0]', 'E-sai 6:3 - Thánh thay (Kadosh) được lặp lại 3 lần, nhấn mạnh sự thánh khiết tuyệt đối của Chúa.', '["Cựu Ước","E-sai","Thánh khiết"]', 'Isaiah 6:1-3', 'vi', true, NOW(), NOW()),
('q-isa-011', 'Isaiah', 11, 6, 9, 'easy', 'multiple_choice_single',
'E-sai 11:6 mô tả vương quốc hòa bình: "Chó sói sẽ ở với ___"',
'["Chiên con", "Sư tử", "Gấu", "Dê"]',
'[0]', 'E-sai 11:6 - Khải tượng về thời đại hòa bình khi Đấng Cứu Thế cai trị, mọi thù địch sẽ hòa giải.', '["Cựu Ước","Tiên tri","Hòa bình"]', 'Isaiah 11:6-9', 'vi', true, NOW(), NOW()),
('q-isa-012', 'Isaiah', 40, 8, 8, 'easy', 'multiple_choice_single',
'E-sai 40:8: "Cỏ khô, hoa rụi, nhưng ___ của Đức Chúa Trời chúng ta còn lại đời đời"',
'["Lời", "Tình yêu", "Giao ước", "Đền thờ"]',
'[0]', 'Mọi thứ trên đất đều tạm thời nhưng Lời Chúa thì vĩnh viễn. 1 Phi 1:24-25 trích câu này.', '["Cựu Ước","E-sai","Lời Chúa"]', 'Isaiah 40:8', 'vi', true, NOW(), NOW()),
('q-isa-014', 'Isaiah', 55, 8, 9, 'medium', 'multiple_choice_single',
'E-sai 55:8-9 nói ý tưởng và đường lối của Chúa so với con người thế nào?',
'["Cao hơn bao nhiêu trời cao hơn đất", "Giống nhau", "Hơi khác", "Không thể so sánh"]',
'[0]', 'Ý tưởng Chúa cao hơn ý tưởng con người như trời cao hơn đất. Chúng ta không thể hiểu hết Chúa.', '["Cựu Ước","E-sai","Chủ quyền"]', 'Isaiah 55:8-9', 'vi', true, NOW(), NOW()),
('q-isa-015', 'Isaiah', 64, 8, 8, 'easy', 'multiple_choice_single',
'E-sai 64:8 so sánh Chúa và chúng ta như gì?',
'["Thợ gốm và đất sét", "Cha và con", "Vua và dân", "Thầy và trò"]',
'[0]', 'Chúa là thợ gốm, chúng ta là đất sét. Ngài có quyền năng nhào chúng ta thành bất cứ điều gì Ngài muốn.', '["Cựu Ước","E-sai","Chủ quyền"]', 'Isaiah 64:8', 'vi', true, NOW(), NOW()),

-- ==================== JEREMIAH ====================
('q-jer-005', 'Jeremiah', 1, 6, 8, 'easy', 'multiple_choice_single',
'Giê-rê-mi viện cớ gì khi Chúa gọi?',
'["Tôi còn trẻ quá, không biết nói", "Tôi không xứng đáng", "Tôi sợ kẻ thù", "Tôi đang bận"]',
'[0]', 'Giê 1:6-7 - Giê-rê-mi còn trẻ nhưng Chúa nói: Đừng nói tôi còn trẻ. Hãy đi khắp nơi ta sai người.', '["Cựu Ước","Giê-rê-mi","Sự kêu gọi"]', 'Jeremiah 1:6-8', 'vi', true, NOW(), NOW()),
('q-jer-006', 'Jeremiah', 2, 13, 13, 'medium', 'multiple_choice_single',
'Chúa tố cáo dân sự phạm hai tội gì?',
'["Bỏ nguồn nước sống để đào hồ nứt không giữ được nước", "Thờ tượng", "Giết người", "Làm biếng"]',
'[0]', 'Giê 2:13 - Hai tội: bỏ Chúa (nguồn nước sống) và tìm sự thỏa mãn nơi khác (hồ nứt rò rỉ).', '["Cựu Ước","Giê-rê-mi","Phản bội"]', 'Jeremiah 2:13', 'vi', true, NOW(), NOW()),
('q-jer-007', 'Jeremiah', 17, 9, 9, 'easy', 'multiple_choice_single',
'Giê-rê-mi 17:9 nói gì về tâm lòng con người?',
'["Dối trá hơn mọi vật, ai biết được?", "Tâm lòng luôn tốt", "Tâm lòng là trung lập", "Tâm lòng luôn đúng"]',
'[0]', 'Lòng người ta dối trá hơn mọi vật và rất là xấu xa. Ai biết được? Chỉ Chúa biết.', '["Cựu Ước","Giê-rê-mi","Tâm lòng"]', 'Jeremiah 17:9', 'vi', true, NOW(), NOW()),
('q-jer-008', 'Jeremiah', 18, 1, 6, 'easy', 'multiple_choice_single',
'Giê-rê-mi học bài học gì tại nhà thợ gốm?',
'["Chúa là thợ gốm có quyền năng đặt thành bất cứ dạng nào", "Phải làm việc chăm chỉ", "Đất sét là quý", "Hãy kiên nhẫn"]',
'[0]', 'Giê 18:6 - Như thợ gốm có quyền trên đất sét, Chúa có quyền trên mọi dân mọi nước.', '["Cựu Ước","Giê-rê-mi","Chủ quyền"]', 'Jeremiah 18:1-6', 'vi', true, NOW(), NOW()),
('q-jer-010', 'Jeremiah', 31, 3, 3, 'easy', 'multiple_choice_single',
'Giê 31:3: Chúa nói yêu dân sự bằng loại tình yêu nào?',
'["Tình yêu đời đời", "Tình yêu có điều kiện", "Tình yêu tạm thời", "Tình yêu mới"]',
'[0]', 'Ta đã yêu ngươi bằng một tình yêu đời đời, nên ta lấy sự nhân từ mà kéo ngươi.', '["Cựu Ước","Giê-rê-mi","Tình yêu"]', 'Jeremiah 31:3', 'vi', true, NOW(), NOW()),
('q-jer-012', 'Jeremiah', 38, 6, 6, 'medium', 'multiple_choice_single',
'Giê-rê-mi bị quăng xuống đâu vì rao giảng sự thật?',
'["Giếng bùn (hố bùn)", "Ngục", "Hố sâu", "Hang tối"]',
'[0]', 'Giê 38:6 - Họ thòng xuống Giê-rê-mi bằng dây vào giếng bùn. Giá của việc nói sự thật.', '["Cựu Ước","Giê-rê-mi","Bức hại"]', 'Jeremiah 38:6', 'vi', true, NOW(), NOW()),
('q-jer-013', 'Jeremiah', 52, 12, 13, 'easy', 'multiple_choice_single',
'Lời tiên tri của Giê-rê-mi về việc Giê-ru-sa-lem bị phá có ứng nghiệm không?',
'["Có, Ba-by-lon phá thành và đền thờ năm 586 TCN", "Không", "Chỉ một phần", "Chưa biết"]',
'[0]', 'Giê 52:12-13 - Mọi lời tiên tri đều ứng nghiệm. Giê-ru-sa-lem bị phá và dân bị lưu đày 70 năm đúng như Giê-rê-mi nói.', '["Cựu Ước","Giê-rê-mi","Ứng nghiệm"]', 'Jeremiah 52:12-13', 'vi', true, NOW(), NOW()),
('q-jer-014', 'Jeremiah', 17, 7, 8, 'easy', 'multiple_choice_single',
'Giê 17:7-8 so sánh người tin cậy Chúa như gì?',
'["Cây trồng gần nước, lá xanh, ra trái không dứt", "Núi cao", "Ngôi sao", "Chiến binh"]',
'[0]', 'Giống Thi 1:3 - Người tin cậy Chúa như cây có rễ sâu, không sợ hạn hán.', '["Cựu Ước","Giê-rê-mi","Tin cậy"]', 'Jeremiah 17:7-8', 'vi', true, NOW(), NOW()),
('q-jer-015', 'Jeremiah', 10, 23, 23, 'medium', 'multiple_choice_single',
'Giê 10:23: Giê-rê-mi thừa nhận điều gì về con người?',
'["Đường của loài người không do nơi chính mình, không tự định bước mình", "Con người tự lập", "Con người mạnh mẽ", "Con người khôn ngoan"]',
'[0]', 'Con người không thể tự hướng dẫn đời sống mình. Chúng ta cần sự dẫn dắt của Chúa.', '["Cựu Ước","Giê-rê-mi","Phụ thuộc"]', 'Jeremiah 10:23', 'vi', true, NOW(), NOW()),

-- ==================== LAMENTATIONS ====================
('q-lam-001', 'Lamentations', 3, 22, 23, 'easy', 'multiple_choice_single',
'Ca thương 3:22-23 nói ân điển Chúa như thế nào?',
'["Mỗi buổi sáng đều mới, sự thành tín Ngài là lớn", "Có giới hạn", "Chỉ cho người xứng đáng", "Đã hết"]',
'[0]', 'Giữa đau khổ, tác giả khám phá rằng ân điển Chúa mới mới sinh mỗi buổi sáng.', '["Cựu Ước","Ca thương","Ân điển"]', 'Lamentations 3:22-23', 'vi', true, NOW(), NOW()),
('q-lam-003', 'Lamentations', 1, 1, 1, 'easy', 'multiple_choice_single',
'Sách Ca Thương than khóc về sự kiện gì?',
'["Giê-ru-sa-lem và đền thờ bị phá hủy bởi Ba-by-lon", "Cái chết của Môi-se", "Nạn đói", "Chiến tranh với Phi-li-tin"]',
'[0]', 'Ca thương là 5 bài thơ than khóc về sự sụp đổ của Giê-ru-sa-lem năm 586 TCN.', '["Cựu Ước","Ca thương","Giê-ru-sa-lem"]', 'Lamentations 1:1', 'vi', true, NOW(), NOW()),
('q-lam-004', 'Lamentations', 3, 31, 33, 'medium', 'multiple_choice_single',
'Dù hình phạt, Ca thương 3:31-33 tin điều gì về Chúa?',
'["Chúa không bỏ cho đến đời và không muốn làm khổ con người", "Chúa đã bỏ rời", "Chúa giận mãi", "Không có hy vọng"]',
'[0]', 'Dù kỷ luật, Chúa không bỏ con cái Ngài mãi. Sự hình phạt là tạm thời, tình yêu là đời đời.', '["Cựu Ước","Ca thương","Hy vọng"]', 'Lamentations 3:31-33', 'vi', true, NOW(), NOW()),
('q-lam-005', 'Lamentations', 3, 40, 40, 'easy', 'multiple_choice_single',
'Ca thương 3:40 kêu gọi dân sự làm gì?',
'["Hãy xét xem và thử đường lối mình, rồi trở lại cùng Chúa", "Hãy chạy trốn", "Hãy chiến đấu", "Hãy quên đi"]',
'[0]', 'Sự tự xét mình và ăn năn là bước đầu của sự phục hồi.', '["Cựu Ước","Ca thương","Ăn năn"]', 'Lamentations 3:40', 'vi', true, NOW(), NOW()),
('q-lam-007', 'Lamentations', 2, 11, 11, 'easy', 'multiple_choice_single',
'Tác giả mô tả nỗi đau thế nào?',
'["Mắt tôi không còn nước mắt, ruột tôi sôi động", "Tôi im lặng", "Tôi bỏ đi", "Tôi quên"]',
'[0]', 'Ca thương 2:11 - Nỗi đau của tác giả rất sâu sắc, không che giấu cảm xúc trước Chúa.', '["Cựu Ước","Ca thương","Đau khổ"]', 'Lamentations 2:11', 'vi', true, NOW(), NOW()),
('q-lam-008', 'Lamentations', 3, 26, 26, 'easy', 'multiple_choice_single',
'Ca thương 3:26 dạy làm gì khi đợi Chúa?',
'["Yên lặng và đợi cho sự cứu rỗi của Chúa", "Kêu la", "Giận dữ", "Hành động ngay"]',
'[0]', 'Sự yên lặng và kiên nhẫn trong đợi Chúa là tốt. Không phải thụ động mà là tin cậy.', '["Cựu Ước","Ca thương","Kiên nhẫn"]', 'Lamentations 3:26', 'vi', true, NOW(), NOW()),
('q-lam-009', 'Lamentations', 1, 18, 18, 'medium', 'multiple_choice_single',
'Tác giả thừa nhận nguyên nhân của sự sụp đổ là gì?',
'["Dân sự đã nổi loạn nghịch cùng Chúa", "Vì kẻ thù mạnh hơn", "Vì vận xui", "Vì thiên tai"]',
'[0]', 'Ca thương 1:18 - Đức Giê-hô-va là công bình vì tôi đã phạm điều răn Ngài. Nhận trách nhiệm thay vì đổ lỗi.', '["Cựu Ước","Ca thương","Ăn năn"]', 'Lamentations 1:18', 'vi', true, NOW(), NOW()),
('q-lam-010', 'Lamentations', 3, 37, 38, 'hard', 'multiple_choice_single',
'Ca thương 3:37-38 dạy gì về chủ quyền của Chúa?',
'["Không ai nói điều gì mà thành nếu Chúa không treo", "Chúa không kiểm soát tất cả", "Chỉ điều tốt đến từ Chúa", "Con người tự quyết định"]',
'[0]', 'Cả điều lành và điều dữ đều ở dưới sự cho phép của Chúa. Ngài tối cao trên mọi sự.', '["Cựu Ước","Ca thương","Chủ quyền"]', 'Lamentations 3:37-38', 'vi', true, NOW(), NOW()),
('q-lam-012', 'Lamentations', 3, 21, 21, 'easy', 'multiple_choice_single',
'Trước khi nói về ân điển mới, tác giả làm gì?',
'["Nhắc lại và suy nghĩ trong lòng, nên có hy vọng", "Quên đi", "Giận dữ", "Bỏ cuộc"]',
'[0]', 'Ca thương 3:21 - Khi nhớ lại ân điển Chúa, hy vọng phục hồi. Ký ức về sự tốt lành của Chúa làm nỗi đau dễ chịu hơn.', '["Cựu Ước","Ca thương","Hy vọng"]', 'Lamentations 3:21', 'vi', true, NOW(), NOW()),
('q-lam-013', 'Lamentations', 3, 27, 27, 'easy', 'multiple_choice_single',
'Ca thương 3:27: "Người ta chịu ___ từ lúc trẻ thơ thì tốt"',
'["Ách (gánh nặng)", "Phúc lành", "Sự vui", "Tri thức"]',
'[0]', 'Học vâng phục và chịu khó từ trẻ giúp xây dựng tính cách.', '["Cựu Ước","Ca thương","Kỷ luật"]', 'Lamentations 3:27', 'vi', true, NOW(), NOW()),
('q-lam-014', 'Lamentations', 2, 19, 19, 'medium', 'multiple_choice_single',
'Ca thương 2:19 khuyên đổ lòng ra như nước trước ai?',
'["Trước mặt Chúa", "Trước dân sự", "Trước thầy tế lễ", "Trước kẻ thù"]',
'[0]', 'Hãy đổ lòng ra như nước trước mặt Chúa. Kinh Thánh khuyên bày tỏ cảm xúc thật với Chúa.', '["Cựu Ước","Ca thương","Cầu nguyện"]', 'Lamentations 2:19', 'vi', true, NOW(), NOW()),

-- ==================== EZEKIEL ====================
('q-eze-002', 'Ezekiel', 36, 26, 26, 'easy', 'multiple_choice_single',
'Chúa hứa ban cho dân sự điều gì thay cho tâm lòng bằng đá?',
'["Tâm lòng bằng thịt (tâm lòng mới)", "Trí khôn ngoan", "Sức mạnh", "Sự giàu có"]',
'[0]', 'Exe 36:26 - Chúa cắt bỏ tâm lòng bằng đá và ban tâm lòng mềm mại. Ứng nghiệm qua Đức Thánh Linh.', '["Cựu Ước","E-xe-chi-en","Tâm lòng mới"]', 'Ezekiel 36:26', 'vi', true, NOW(), NOW()),
('q-eze-004', 'Ezekiel', 34, 11, 12, 'easy', 'multiple_choice_single',
'Chúa nói sẽ làm gì khi những kẻ chăn không làm tròn bổn phận?',
'["Chính Ngài sẽ tìm và chăm sóc bầy chiên", "Phạt kẻ chăn", "Để bầy chiên tự lo", "Tìm kẻ chăn mới"]',
'[0]', 'Exe 34:11 - Chúa là Đấng Chăn Hiền Lành thật sự. Chúa Giê-su tự xưng là Đấng Chăn Hiền Lành (Giăng 10:11).', '["Cựu Ước","E-xe-chi-en","Đấng Chăn"]', 'Ezekiel 34:11-12', 'vi', true, NOW(), NOW()),
('q-eze-005', 'Ezekiel', 18, 4, 4, 'medium', 'multiple_choice_single',
'Exe 18:4 dạy nguyên tắc gì về trách nhiệm tội lỗi?',
'["Linh hồn nào phạm tội thì linh hồn ấy sẽ chết (mỗi người chịu trách nhiệm tội mình)", "Con chịu tội cha", "Cha chịu tội con", "Cả gia đình chịu"]',
'[0]', 'Mỗi người chịu trách nhiệm về tội lỗi của chính mình. Không ai bị phạt vì tội người khác.', '["Cựu Ước","E-xe-chi-en","Trách nhiệm"]', 'Ezekiel 18:4', 'vi', true, NOW(), NOW()),
('q-eze-006', 'Ezekiel', 33, 11, 11, 'easy', 'multiple_choice_single',
'Chúa có vui vẻ khi kẻ ác chết không?',
'["Không, Chúa muốn kẻ ác ăn năn và sống", "Có, vì là công bình", "Chúa không quan tâm", "Tùy trường hợp"]',
'[0]', 'Exe 33:11 - Ta không vui vẻ về sự chết của kẻ ác nhưng muốn kẻ ác ăn năn và sống.', '["Cựu Ước","E-xe-chi-en","Ăn năn"]', 'Ezekiel 33:11', 'vi', true, NOW(), NOW()),
('q-eze-007', 'Ezekiel', 1, 4, 10, 'hard', 'multiple_choice_single',
'Khải tượng đầu tiên của E-xe-chi-en mô tả gì?',
'["Bốn sinh vật có cánh và bánh xe, vinh quang Chúa", "Đền thờ", "Chiến trận", "Vườn Ê-đen"]',
'[0]', 'Exe 1:4-10 - Khải tượng phức tạp về ngai Chúa với 4 sinh vật có mặt người, sư tử, bò, và chim ưng.', '["Cựu Ước","E-xe-chi-en","Khải tượng"]', 'Ezekiel 1:4-10', 'vi', true, NOW(), NOW()),
('q-eze-008', 'Ezekiel', 47, 1, 9, 'medium', 'multiple_choice_single',
'Khải tượng về dòng sông từ đền thờ chảy ra có ý nghĩa gì?',
'["Nước sự sống từ sự hiện diện Chúa chảy ra chữa lành mọi nơi", "Tưới vườn", "Cung cấp nước uống", "Tạo biển mới"]',
'[0]', 'Exe 47:9 - Nước này chảy đến đâu thì có sự sống ở đó. Khải 22:1 cũng mô tả sông nước sự sống.', '["Cựu Ước","E-xe-chi-en","Nước sống"]', 'Ezekiel 47:1-9', 'vi', true, NOW(), NOW()),
('q-eze-010', 'Ezekiel', 36, 27, 27, 'medium', 'multiple_choice_single',
'Chúa hứa sẽ đặt gì bên trong dân sự để họ vâng lời?',
'["Thần ta (Đức Thánh Linh) bên trong các ngươi", "Luật pháp mới", "Tiên tri mới", "Vua mới"]',
'[0]', 'Exe 36:27 - Chúa sẽ đặt Thần Ngài bên trong để dân sự vâng lời từ bên trong. Ứng nghiệm Lễ Ngũ Tuần.', '["Cựu Ước","E-xe-chi-en","Thánh Linh"]', 'Ezekiel 36:27', 'vi', true, NOW(), NOW()),
('q-eze-011', 'Ezekiel', 37, 21, 22, 'easy', 'multiple_choice_single',
'Khải tượng xương khô cũng tiên tri về điều gì cho dân Y-sơ-ra-ên?',
'["Sự phục hồi và thống nhất Y-sơ-ra-ên", "Sự hủy diệt", "Chiến tranh mới", "Di cư"]',
'[0]', 'Exe 37:22 - Chúa hứa làm họ thành một dân tộc dưới một vua. Y-sơ-ra-ên phục quốc năm 1948.', '["Cựu Ước","E-xe-chi-en","Phục hồi"]', 'Ezekiel 37:21-22', 'vi', true, NOW(), NOW()),
('q-eze-012', 'Ezekiel', 22, 30, 30, 'medium', 'multiple_choice_single',
'Chúa nói: "Ta đã tìm một người đứng nơi trổ-rộng trước mặt ta vì xứ này nhưng ___"',
'["Không tìm được ai", "Tìm được một người", "Tìm được nhiều người", "Không cần"]',
'[0]', 'Exe 22:30 - Chúa tìm người cầu thay nhưng không có ai. Sự cần đầu người cầu nguyện cho dân tộc.', '["Cựu Ước","E-xe-chi-en","Cầu thay"]', 'Ezekiel 22:30', 'vi', true, NOW(), NOW()),
('q-eze-013', 'Ezekiel', 2, 6, 7, 'easy', 'multiple_choice_single',
'Chúa phán với E-xe-chi-en: "Đừng ___ họ và đừng sợ lời nói họ"',
'["Sợ", "Nghe", "Tin", "Yêu"]',
'[0]', 'Exe 2:6 - Chúa khuyên can đảm nói sự thật dù bị chống đối.', '["Cựu Ước","E-xe-chi-en","Can đảm"]', 'Ezekiel 2:6-7', 'vi', true, NOW(), NOW()),
('q-eze-014', 'Ezekiel', 34, 23, 24, 'hard', 'multiple_choice_single',
'Chúa hứa sẽ đặt "tôi tớ ta là Đa-vít" làm đấng chăn. Đây tiên tri về ai?',
'["Chúa Giê-su - Đấng Chăn Hiền Lành từ dòng dõi Đa-vít", "Vua Đa-vít phục sinh", "Một hậu duệ của Đa-vít", "Sa-lô-môn"]',
'[0]', 'Exe 34:23-24 - Đấng Chăn Đa-vít là Chúa Giê-su, hậu duệ Đa-vít và là Vua đời đời (Giăng 10:11).', '["Cựu Ước","Tiên tri","Đấng Chăn"]', 'Ezekiel 34:23-24', 'vi', true, NOW(), NOW()),

-- ==================== DANIEL ====================
('q-dan-003', 'Daniel', 1, 8, 8, 'easy', 'multiple_choice_single',
'Đa-ni-ên định ý trong lòng không làm gì tại Ba-by-lon?',
'["Không tự ô mình bằng thức ăn và rượu của vua", "Không học tiếng Ba-by-lon", "Không làm việc", "Không nói chuyện"]',
'[0]', 'Đa-ni-ên 1:8 - Đa-ni-ên giữ nguyên tắc dù ở xứ lạ. Chúa ban phước cho sự trung tín.', '["Cựu Ước","Đa-ni-ên","Trung tín"]', 'Daniel 1:8', 'vi', true, NOW(), NOW()),
('q-dan-004', 'Daniel', 2, 44, 45, 'hard', 'multiple_choice_single',
'Giấc mơ của vua Nê-bu-cát-nết-sa về pho tượng tiên tri về điều gì?',
'["Các đế quốc thế giới và vương quốc đời đời của Chúa", "Chỉ về Ba-by-lon", "Về tương lai gần", "Về chiến tranh"]',
'[0]', 'Đa-ni-ên 2:44 - Hòn đá không bị tay cắt ra = Vương quốc Chúa sẽ hạ mọi vương quốc và còn lại đời đời.', '["Cựu Ước","Đa-ni-ên","Tiên tri"]', 'Daniel 2:44-45', 'vi', true, NOW(), NOW()),
('q-dan-005', 'Daniel', 3, 25, 25, 'easy', 'multiple_choice_single',
'Khi nhìn vào lò lửa, vua thấy bao nhiêu người thay vì 3?',
'["4 người, người thứ tư giống như con của các thần", "5 người", "3 người", "2 người"]',
'[0]', 'Đa-ni-ên 3:25 - Người thứ tư có thể là thiên sứ hoặc sự hiện ra của Chúa. Ngài ở cùng con cái Ngài trong lửa.', '["Cựu Ước","Đa-ni-ên","Bảo vệ"]', 'Daniel 3:25', 'vi', true, NOW(), NOW()),
('q-dan-006', 'Daniel', 4, 30, 33, 'medium', 'multiple_choice_single',
'Vua Nê-bu-cát-nết-sa bị phạt thế nào vì kiêu ngạo?',
'["Sống như thú vật, ăn cỏ 7 kỳ cho đến khi nhận ra Chúa cai trị", "Mất ngôi", "Bị giết", "Bị lưu đày"]',
'[0]', 'Đa-ni-ên 4:33 - 7 kỳ sống như thú. Khi hồi tâm, vua ngợi khen Chúa. Bài học về sự khiêm nhường.', '["Cựu Ước","Đa-ni-ên","Kiêu ngạo"]', 'Daniel 4:30-33', 'vi', true, NOW(), NOW()),
('q-dan-007', 'Daniel', 5, 5, 5, 'easy', 'multiple_choice_single',
'Trong tiệc của vua Bên-sa-xa, điều gì xuất hiện trên tường?',
'["Bàn tay viết chữ trên tường", "Lửa", "Mặt người", "Ánh sáng"]',
'[0]', 'Đa-ni-ên 5:5 - Bàn tay viết: Mê-nê, Mê-nê, Tê-ken, U-phác-sin. Vương quốc đã được cân và thiếu.', '["Cựu Ước","Đa-ni-ên","Phán xét"]', 'Daniel 5:5', 'vi', true, NOW(), NOW()),
('q-dan-009', 'Daniel', 6, 10, 10, 'easy', 'multiple_choice_single',
'Khi biết luật cấm cầu nguyện, Đa-ni-ên làm gì?',
'["Vẫn cầu nguyện 3 lần mỗi ngày như trước", "Cầu nguyện kín", "Ngưng cầu nguyện", "Cầu nguyện ít hơn"]',
'[0]', 'Đa-ni-ên 6:10 - Đa-ni-ên không thay đổi thói quen cầu nguyện dù bị đe dọa. Đức tin không bị đe dọa.', '["Cựu Ước","Đa-ni-ên","Cầu nguyện"]', 'Daniel 6:10', 'vi', true, NOW(), NOW()),
('q-dan-010', 'Daniel', 7, 13, 14, 'hard', 'multiple_choice_single',
'Đa-ni-ên 7:13 thấy "một Đấng giống như Con Người" đến trên mây trời. Đây là ai?',
'["Chúa Giê-su Christ", "Thiên sứ Mi-ca-ên", "Môi-se", "Ê-li"]',
'[0]', 'Chúa Giê-su tự xưng là Con Người (Mat 26:64) và trích Đa-ni-ên 7:13 về sự tái lâm của Ngài.', '["Cựu Ước","Tiên tri","Con Người"]', 'Daniel 7:13-14', 'vi', true, NOW(), NOW()),
('q-dan-011', 'Daniel', 9, 25, 26, 'hard', 'multiple_choice_single',
'Lời tiên tri 70 tuần lễ (490 năm) của Đa-ni-ên tiên tri về sự kiện gì?',
'["Thời điểm Đấng Cứu Thế đến và bị giết", "Sự phục hồi đền thờ", "Ngày tận thế", "Lễ Ngũ Tuần"]',
'[0]', 'Đa-ni-ên 9:25-26 - 69 tuần (483 năm) từ lúc ra lệnh xây lại đến khi Đấng Cứu Thế bị cắt off. Ứng nghiệm chính xác.', '["Cựu Ước","Tiên tri","Thời điểm"]', 'Daniel 9:25-26', 'vi', true, NOW(), NOW()),
('q-dan-012', 'Daniel', 12, 2, 3, 'medium', 'multiple_choice_single',
'Đa-ni-ên 12:2 tiên tri về điều gì?',
'["Sự phục sinh: người sống lại, kẻ được sống đời đời, kẻ bị xấu hổ đời đời", "Chỉ sự phục sinh người tốt", "Không có phục sinh", "Chỉ phục sinh thuộc linh"]',
'[0]', 'Đa-ni-ên 12:2 - Một trong những tiên tri rõ ràng nhất về sự phục sinh trong Cựu Ước.', '["Cựu Ước","Đa-ni-ên","Phục sinh"]', 'Daniel 12:2-3', 'vi', true, NOW(), NOW()),
('q-dan-014', 'Daniel', 10, 12, 13, 'medium', 'multiple_choice_single',
'Tại sao thiên sứ đến với Đa-ni-ên bị trễ 21 ngày?',
'["Bị quan trưởng Ba-tư (thế lực thuộc linh) cản trở", "Bị lạc đường", "Chúa giao việc khác", "Không biết"]',
'[0]', 'Đa-ni-ên 10:13 - Có chiến trận thuộc linh đằng sau mọi sự. Cầu nguyện ảnh hưởng thế giới vô hình.', '["Cựu Ước","Đa-ni-ên","Chiến trận linh"]', 'Daniel 10:12-13', 'vi', true, NOW(), NOW()),
('q-dan-015', 'Daniel', 12, 13, 13, 'easy', 'multiple_choice_single',
'Lời cuối cùng Chúa nói với Đa-ni-ên là gì?',
'["Hãy đi cho đến cuối cùng, người sẽ nghỉ ngơi và sẽ đứng lại trong phần mình", "Hãy viết thêm", "Hãy nói cho người khác", "Hãy đợi"]',
'[0]', 'Đa-ni-ên 12:13 - Lời hứa phục sinh và phần thưởng cho người trung tín. Hy vọng cho mọi tín đồ.', '["Cựu Ước","Đa-ni-ên","Hy vọng"]', 'Daniel 12:13', 'vi', true, NOW(), NOW()),

-- ==================== MINOR PROPHETS ====================
-- Hosea (15), Joel (15), Amos (15) — abbreviated to key verses
-- Micah, Habakkuk, Jonah, Malachi

-- MICAH
('q-mic-003', 'Micah', 7, 18, 18, 'easy', 'multiple_choice_single',
'Mi-che 7:18: "Ai là Đức Chúa Trời giống như Ngài, ___ sự gian ác?"',
'["Hay tha", "Phạt", "Nhớ", "Ghi"]',
'[0]', 'Chúa hay tha sự gian ác, không giữ giận đời đời vì Ngài lấy sự nhân từ làm vui.', '["Cựu Ước","Mi-che","Tha thứ"]', 'Micah 7:18', 'vi', true, NOW(), NOW()),
('q-mic-005', 'Micah', 4, 3, 3, 'easy', 'multiple_choice_single',
'Mi-che 4:3 tiên tri thời đại hòa bình: "Họ sẽ rèn gươm thành ___"',
'["Lưỡi cày", "Trang sức", "Dụng cụ", "Khiên"]',
'[0]', 'Vũ khí biến thành dụng cụ nông nghiệp. Không còn học chiến trận nữa.', '["Cựu Ước","Mi-che","Hòa bình"]', 'Micah 4:3', 'vi', true, NOW(), NOW()),
('q-mic-006', 'Micah', 3, 8, 8, 'medium', 'multiple_choice_single',
'Mi-che tuyên bố ông đầy quyền năng nhờ điều gì?',
'["Thần của Đức Giê-hô-va, sự công bình và sức mạnh", "Học thức", "Kinh nghiệm", "Chức vụ"]',
'[0]', 'Mi-che 3:8 - Quyền năng phục vụ đến từ Thánh Linh, không phải từ bản thân tiên tri.', '["Cựu Ước","Mi-che","Quyền năng"]', 'Micah 3:8', 'vi', true, NOW(), NOW()),
('q-mic-007', 'Micah', 5, 4, 4, 'easy', 'multiple_choice_single',
'Đấng Cứu Thế từ Bết-lê-hem sẽ chăn dân sự bằng gì?',
'["Sức mạnh của Đức Giê-hô-va", "Gươm", "Trí khôn", "Quân đội"]',
'[0]', 'Mi-che 5:4 - Đấng Chăn vĩ đại sẽ đứng trong sức Chúa và chăm sóc dân sự.', '["Cựu Ước","Mi-che","Đấng Chăn"]', 'Micah 5:4', 'vi', true, NOW(), NOW()),
('q-mic-009', 'Micah', 6, 6, 7, 'medium', 'multiple_choice_single',
'Mi-che 6:6-7 hỏi: Chúa có muốn hàng ngàn con chiên hay dầu ô-liu không?',
'["Không, Chúa muốn công bình, nhân từ và khiêm nhường", "Có, càng nhiều càng tốt", "Chỉ cần một ít", "Tùy lúc"]',
'[0]', 'Chúa không muốn hình thức tôn giáo mà muốn đời sống công bình và khiêm nhường.', '["Cựu Ước","Mi-che","Công bình"]', 'Micah 6:6-7', 'vi', true, NOW(), NOW()),
('q-mic-010', 'Micah', 1, 3, 4, 'easy', 'multiple_choice_single',
'Mi-che cảnh báo sự phán xét của Chúa sẽ đến trên thành nào?',
'["Sa-ma-ri và Giê-ru-sa-lem", "Chỉ Sa-ma-ri", "Chỉ Giê-ru-sa-lem", "Ni-ni-ve"]',
'[0]', 'Mi-che 1:5 - Cả hai kinh đô đều phạm tội và cả hai sẽ bị phán xét. Chúa công bình với mọi người.', '["Cựu Ước","Mi-che","Phán xét"]', 'Micah 1:3-5', 'vi', true, NOW(), NOW()),
('q-mic-011', 'Micah', 4, 1, 2, 'medium', 'multiple_choice_single',
'Mi-che tiên tri: trong những ngày sau rốt, núi của nhà Chúa sẽ như thế nào?',
'["Được lập lên trên chóp các núi, dân tộc sẽ đổ đến", "Bị phá hủy", "Bị ẩn", "Bị quên"]',
'[0]', 'Mi-che 4:1-2 - Vương quốc Chúa sẽ được tôn cao và mọi dân tộc sẽ đến học đường lối Ngài.', '["Cựu Ước","Mi-che","Ngày sau"]', 'Micah 4:1-2', 'vi', true, NOW(), NOW()),
('q-mic-014', 'Micah', 7, 7, 7, 'easy', 'multiple_choice_single',
'Mi-che tuyên bố: "Phần ta, ta sẽ trông đợi ai?"',
'["Đức Giê-hô-va", "Vua", "Quân đội", "Bạn bè"]',
'[0]', 'Mi-che 7:7 - Dù hoàn cảnh nào, Mi-che chọn trông đợi và tin cậy Chúa.', '["Cựu Ước","Mi-che","Trông đợi"]', 'Micah 7:7', 'vi', true, NOW(), NOW()),
('q-mic-015', 'Micah', 7, 8, 8, 'medium', 'multiple_choice_single',
'Mi-che 7:8: "Khi ta bị té thì ta sẽ ___; khi ta ngồi trong tối thì Đức Giê-hô-va là ánh sáng ta"',
'["Đứng lên lại", "Nằm mãi", "Kêu cầu", "Bỏ cuộc"]',
'[0]', 'Dù sa ngã, người tin Chúa sẽ đứng lên lại vì Chúa là ánh sáng trong bóng tối.', '["Cựu Ước","Mi-che","Hy vọng"]', 'Micah 7:8', 'vi', true, NOW(), NOW()),

-- HABAKKUK
('q-hab-002', 'Habakkuk', 1, 2, 3, 'medium', 'multiple_choice_single',
'Ha-ba-cúc hỏi Chúa câu hỏi gì?',
'["Tại sao Chúa im lặng trước bất công và bạo lực?", "Khi nào Chúa đến?", "Tại sao tôi khổ?", "Chúa ở đâu?"]',
'[0]', 'Ha-ba-cúc 1:2 - Tiên tri thật thà hỏi Chúa về sự bất công. Chúa cho phép hỏi và than vãn.', '["Cựu Ước","Ha-ba-cúc","Công bình"]', 'Habakkuk 1:2-3', 'vi', true, NOW(), NOW()),
('q-hab-003', 'Habakkuk', 1, 5, 5, 'easy', 'multiple_choice_single',
'Chúa trả lời Ha-ba-cúc: "Hãy nhìn các dân tộc và ___"',
'["Kinh ngạc, vì ta sẽ làm một việc mà người không tin", "Sợ hãi", "Vui mừng", "Chạy trốn"]',
'[0]', 'Chúa đang làm việc ngay cả khi chúng ta không nhìn thấy hay hiểu.', '["Cựu Ước","Ha-ba-cúc","Tin cậy"]', 'Habakkuk 1:5', 'vi', true, NOW(), NOW()),
('q-hab-004', 'Habakkuk', 2, 2, 3, 'easy', 'multiple_choice_single',
'Chúa bảo Ha-ba-cúc viết khải tượng xuống để làm gì?',
'["Để người đọc chạy được (rõ ràng)", "Để giữ kín", "Để dâng cho vua", "Để đọc ở đền thờ"]',
'[0]', 'Ha-ba-cúc 2:2 - Khải tượng phải rõ ràng để mọi người đọc được. Lời Chúa cần được truyền đạt để hiểu.', '["Cựu Ước","Ha-ba-cúc","Khải tượng"]', 'Habakkuk 2:2-3', 'vi', true, NOW(), NOW()),
('q-hab-006', 'Habakkuk', 2, 20, 20, 'easy', 'multiple_choice_single',
'Ha 2:20: "Đức Giê-hô-va ngự trong đền thánh Ngài; cả đất hãy ___"',
'["Nên lặng trước mặt Ngài", "Ngợi khen", "Kêu gọi", "Vui mừng"]',
'[0]', 'Sự tôn kính và yên lặng trước sự hiện diện của Chúa.', '["Cựu Ước","Ha-ba-cúc","Tôn kính"]', 'Habakkuk 2:20', 'vi', true, NOW(), NOW()),
('q-hab-007', 'Habakkuk', 3, 2, 2, 'medium', 'multiple_choice_single',
'Ha-ba-cúc cầu nguyện: "Xin Ngài làm sự nghiệp Ngài sống lại giữa các năm và trong cơn ___ hãy nhớ sự thương xót"',
'["Thiết giam (giận dữ)", "Vui vẻ", "Bình an", "Chiến tranh"]',
'[0]', 'Ngay cả khi Chúa phán xét, Ha-ba-cúc xin Ngài nhớ sự thương xót.', '["Cựu Ước","Ha-ba-cúc","Cầu nguyện"]', 'Habakkuk 3:2', 'vi', true, NOW(), NOW()),
('q-hab-008', 'Habakkuk', 3, 17, 18, 'medium', 'multiple_choice_single',
'Ha-ba-cúc 3:17-18: Dù không có trái, không mùa, không bầy, ông vẫn làm gì?',
'["Vui mừng trong Đức Giê-hô-va", "Than vãn", "Bỏ cuộc", "Tìm nơi khác"]',
'[0]', 'Đức tin không điều kiện: vui mừng trong Chúa dù mất tất cả. Đỉnh cao của đức tin.', '["Cựu Ước","Ha-ba-cúc","Đức tin"]', 'Habakkuk 3:17-18', 'vi', true, NOW(), NOW()),
('q-hab-010', 'Habakkuk', 2, 3, 3, 'easy', 'multiple_choice_single',
'Ha 2:3 dạy gì về lời hứa của Chúa?',
'["Khải tượng còn đợi đến kỳ, nhưng chắc chắn sẽ đến, hãy đợi", "Có thể không đến", "Sẽ đến ngay", "Không chắc"]',
'[0]', 'Lời hứa Chúa có thể trễ nhưng không bao giờ thất bại. Hãy kiên nhẫn đợi.', '["Cựu Ước","Ha-ba-cúc","Kiên nhẫn"]', 'Habakkuk 2:3', 'vi', true, NOW(), NOW()),
('q-hab-011', 'Habakkuk', 1, 12, 12, 'easy', 'multiple_choice_single',
'Ha-ba-cúc gọi Chúa bằng danh hiệu nào?',
'["Đức Chúa Trời đời đời và Vầng Đá", "Vua của vua", "Chiến binh", "Quan án"]',
'[0]', 'Ha-ba-cúc 1:12 - Vầng Đá (Tsur) = nơi vững chắc và ẩn náu. Chúa đời đời và không thay đổi.', '["Cựu Ước","Ha-ba-cúc","Danh Chúa"]', 'Habakkuk 1:12', 'vi', true, NOW(), NOW()),
('q-hab-013', 'Habakkuk', 2, 6, 8, 'medium', 'multiple_choice_single',
'Ha-ba-cúc chương 2 tuyên bố mấy lời khốn cho ai?',
'["Kẻ tham lam, bóc lột, bạo lực, say sưa và thờ tượng", "Người nghèo", "Người bệnh", "Tiên tri giả"]',
'[0]', 'Năm lời khốn nhằm kẻ ác, cảnh báo rằng Chúa thấy và sẽ phán xét mọi bất công.', '["Cựu Ước","Ha-ba-cúc","Phán xét"]', 'Habakkuk 2:6-20', 'vi', true, NOW(), NOW()),
('q-hab-014', 'Habakkuk', 3, 3, 4, 'easy', 'multiple_choice_single',
'Ha-ba-cúc mô tả Chúa đến trong vinh quang như thế nào?',
'["Vinh quang che trời, ánh sáng từ tay Ngài", "Yên lặng", "Nhỏ nhẹ", "Không thấy"]',
'[0]', 'Ha-ba-cúc 3:3-4 - Mô tả Chúa đến trong quyền năng và vinh quang bất tận.', '["Cựu Ước","Ha-ba-cúc","Vinh quang"]', 'Habakkuk 3:3-4', 'vi', true, NOW(), NOW()),
('q-hab-015', 'Habakkuk', 3, 16, 16, 'easy', 'multiple_choice_single',
'Khi nghe Chúa phán, Ha-ba-cúc phản ứng thế nào?',
'["Run rẩy nhưng vẫn đợi Chúa", "Vui mừng", "Bỏ chạy", "Giận dữ"]',
'[0]', 'Ha-ba-cúc 3:16 - Kính sợ trước sự vĩ đại của Chúa nhưng vẫn yên lặng đợi ngày Ngài hành động.', '["Cựu Ước","Ha-ba-cúc","Kính sợ"]', 'Habakkuk 3:16', 'vi', true, NOW(), NOW()),

-- JONAH
('q-jon-002', 'Jonah', 1, 1, 3, 'easy', 'multiple_choice_single',
'Chúa sai Giona đi Ni-ni-ve nhưng ông trốn đi đâu?',
'["Ta-rê-si (hướng ngược lại)", "Ai-cập", "Ba-by-lon", "Mô-áp"]',
'[0]', 'Giona 1:3 - Giona trốn chạy khỏi mặt Chúa bằng tàu đi Ta-rê-si, hướng ngược hoàn toàn.', '["Cựu Ước","Giona","Bất tuân"]', 'Jonah 1:1-3', 'vi', true, NOW(), NOW()),
('q-jon-003', 'Jonah', 1, 4, 5, 'easy', 'multiple_choice_single',
'Khi Giona trốn, Chúa làm gì?',
'["Sai bão lớn trên biển", "Gửi thiên sứ", "Để mặc", "Gọi tiên tri khác"]',
'[0]', 'Giona 1:4 - Chúa không để Giona trốn thành công. Bão lớn để đưa ông quay lại.', '["Cựu Ước","Giona","Kỷ luật"]', 'Jonah 1:4-5', 'vi', true, NOW(), NOW()),
('q-jon-004', 'Jonah', 1, 12, 12, 'medium', 'multiple_choice_single',
'Giona nói với thủy thủ làm gì để biển lặng?',
'["Ném tôi xuống biển", "Cầu nguyện", "Quét dọn tàu", "Quay lại"]',
'[0]', 'Giona 1:12 - Giona nhận trách nhiệm và sẵn sàng chịu hậu quả tội lỗi mình.', '["Cựu Ước","Giona","Trách nhiệm"]', 'Jonah 1:12', 'vi', true, NOW(), NOW()),
('q-jon-006', 'Jonah', 2, 9, 9, 'easy', 'multiple_choice_single',
'Giona tuyên bố từ trong bụng cá: "Sự ___ đến từ Đức Giê-hô-va"',
'["Cứu rỗi", "Phán xét", "Khôn ngoan", "Bình an"]',
'[0]', 'Giona 2:9 - Dù trong hoàn cảnh tuyệt vọng nhất, Giona nhận ra chỉ Chúa cứu rỗi.', '["Cựu Ước","Giona","Cứu rỗi"]', 'Jonah 2:9', 'vi', true, NOW(), NOW()),
('q-jon-007', 'Jonah', 3, 3, 4, 'easy', 'multiple_choice_single',
'Lần thứ hai Chúa gọi, Giona làm gì?',
'["Vâng lời đi Ni-ni-ve rao giảng", "Trốn lần nữa", "Hỏi tại sao", "Nghỉ ngơi"]',
'[0]', 'Giona 3:3 - Lần này Giona vâng lời. Chúa cho cơ hội thứ hai.', '["Cựu Ước","Giona","Vâng lời"]', 'Jonah 3:3-4', 'vi', true, NOW(), NOW()),
('q-jon-008', 'Jonah', 3, 5, 5, 'easy', 'multiple_choice_single',
'Dân Ni-ni-ve phản ứng thế nào khi nghe Giona rao giảng?',
'["Tin Đức Chúa Trời, kiêng ăn và ăn năn", "Bỏ mặc", "Giận dữ", "Cười nhạo"]',
'[0]', 'Giona 3:5 - Cả thành ăn năn từ vua đến dân! Sự ăn năn lớn nhất trong Cựu Ước.', '["Cựu Ước","Giona","Ăn năn"]', 'Jonah 3:5', 'vi', true, NOW(), NOW()),
('q-jon-009', 'Jonah', 3, 10, 10, 'easy', 'multiple_choice_single',
'Khi Ni-ni-ve ăn năn, Chúa làm gì?',
'["Đổi ý và không hủy diệt họ", "Vẫn phạt họ", "Trì hoãn hình phạt", "Để mặc"]',
'[0]', 'Giona 3:10 - Chúa đổi ý khi dân sự ăn năn. Ngài nhân từ và sẵn sàng tha thứ.', '["Cựu Ước","Giona","Tha thứ"]', 'Jonah 3:10', 'vi', true, NOW(), NOW()),
('q-jon-010', 'Jonah', 4, 1, 2, 'medium', 'multiple_choice_single',
'Tại sao Giona giận khi Ni-ni-ve được tha?',
'["Vì ông đã biết Chúa nhân từ và sẽ tha, ông không muốn kẻ thù được cứu", "Vì mất uy tín", "Vì mệt mỏi", "Vì sợ"]',
'[0]', 'Giona 4:2 - Giona thừa nhận biết từ đầu Chúa sẽ tha. Vấn đề của ông là lòng hẹp hòi và kỳ thị dân tộc.', '["Cựu Ước","Giona","Nhân từ"]', 'Jonah 4:1-2', 'vi', true, NOW(), NOW()),
('q-jon-012', 'Jonah', 4, 11, 11, 'medium', 'multiple_choice_single',
'Chúa kết thúc sách Giona bằng câu hỏi gì?',
'["Ta lại không thương xót Ni-ni-ve với 120,000 người không phân biệt tay phải tay trái sao?", "Ngươi có vui không?", "Ngươi có vâng lời không?", "Ngươi ở đâu?"]',
'[0]', 'Giona 4:11 - Chúa thương mọi người, kể cả kẻ thù. Tình yêu Chúa không có ranh giới dân tộc.', '["Cựu Ước","Giona","Tình yêu"]', 'Jonah 4:11', 'vi', true, NOW(), NOW()),
('q-jon-013', 'Jonah', 4, 2, 2, 'easy', 'multiple_choice_single',
'Giona mô tả Chúa là gì khiến ông giận?',
'["Hay làm ơn, thương xót, chậm giận, đầy ơn thương, đổi ý không phạt", "Nghiêm khắc", "Công bình", "Phán xét"]',
'[0]', 'Giona trích Xuất 34:6 - bản tính của Chúa. Điều tốt lành của Chúa lại khiến Giona khó chịu.', '["Cựu Ước","Giona","Tính Chúa"]', 'Jonah 4:2', 'vi', true, NOW(), NOW()),
('q-jon-014', 'Jonah', 1, 9, 9, 'easy', 'multiple_choice_single',
'Giona nói với thủy thủ: "Tôi kính sợ Đức Giê-hô-va là Đức Chúa Trời trên ___"',
'["Trời, Đấng đã làm biển và đất khô", "Núi", "Các thần", "Mọi vật"]',
'[0]', 'Dù đang trốn Chúa, Giona vẫn tuyên xưng Ngài là Đấng Sáng Tạo.', '["Cựu Ước","Giona","Tuyên xưng"]', 'Jonah 1:9', 'vi', true, NOW(), NOW()),

-- MALACHI
('q-mal-002', 'Malachi', 1, 2, 2, 'easy', 'multiple_choice_single',
'Ma-la-chi bắt đầu bằng lời Chúa nói gì?',
'["Ta yêu các ngươi", "Ta giận các ngươi", "Hãy ăn năn", "Hãy vâng lời"]',
'[0]', 'Ma-la-chi 1:2 - Ngay cả khi dân sự bất trung, Chúa vẫn tuyên bố tình yêu. Dân lại hỏi: Ngài yêu ở chỗ nào?', '["Cựu Ước","Ma-la-chi","Tình yêu"]', 'Malachi 1:2', 'vi', true, NOW(), NOW()),
('q-mal-003', 'Malachi', 1, 6, 6, 'easy', 'multiple_choice_single',
'Chúa trách thầy tế lễ vì điều gì?',
'["Dâng thú vật có tật cho Chúa (khinh danh Ngài)", "Không cầu nguyện", "Không đọc sách", "Ăn cắp"]',
'[0]', 'Ma-la-chi 1:8 - Họ dâng thú vật mù, quẹo, đau cho Chúa. Thú dâng cho quan trấn thì sao?', '["Cựu Ước","Ma-la-chi","Của lễ"]', 'Malachi 1:6-8', 'vi', true, NOW(), NOW()),
('q-mal-004', 'Malachi', 2, 16, 16, 'medium', 'multiple_choice_single',
'Ma-la-chi 2:16 bày tỏ thái độ của Chúa về ly dị như thế nào?',
'["Ta ghét sự ly dị vì nó phủ sự oan ức lên vợ", "Không quan tâm", "Cho phép tự do", "Chỉ cấm người nghèo"]',
'[0]', 'Chúa coi trọng hôn nhân và gìn giữ kết ước. Ly dị không phải ý muốn ban đầu của Ngài.', '["Cựu Ước","Ma-la-chi","Hôn nhân"]', 'Malachi 2:16', 'vi', true, NOW(), NOW()),
('q-mal-005', 'Malachi', 3, 1, 1, 'medium', 'multiple_choice_single',
'Ma-la-chi 3:1 tiên tri ai sẽ đến trước Chúa?',
'["Sứ giả (Giăng Báp-tít) để dọn đường", "Ê-li", "Môi-se", "Thiên sứ"]',
'[0]', 'Mác 1:2 áp dụng câu này cho Giăng Báp-tít, người dọn đường cho Chúa Giê-su.', '["Cựu Ước","Tiên tri","Giăng Báp-tít"]', 'Malachi 3:1', 'vi', true, NOW(), NOW()),
('q-mal-007', 'Malachi', 3, 8, 8, 'easy', 'multiple_choice_single',
'Chúa hỏi dân sự: "Người ta có thể ___ Đức Chúa Trời sao? Mà các ngươi đã cướp ta"',
'["Ăn cắp của", "Nói dối với", "Chống lại", "Làm buồn"]',
'[0]', 'Ma-la-chi 3:8 - Dân sự ăn cắp của Chúa bằng cách không dâng phần mười và của lễ.', '["Cựu Ước","Ma-la-chi","Phần mười"]', 'Malachi 3:8', 'vi', true, NOW(), NOW()),
('q-mal-009', 'Malachi', 3, 16, 17, 'easy', 'multiple_choice_single',
'Ma-la-chi 3:16 nói Chúa có sách gì ghi lại những ai kính sợ Ngài?',
'["Sách kỷ niệm", "Sách luật", "Sách sử", "Sách tiên tri"]',
'[0]', 'Chúa ghi nhớ những ai kính sợ và tôn kính danh Ngài. Họ là báu vật riêng của Ngài.', '["Cựu Ước","Ma-la-chi","Ghi nhớ"]', 'Malachi 3:16-17', 'vi', true, NOW(), NOW()),
('q-mal-010', 'Malachi', 4, 2, 2, 'medium', 'multiple_choice_single',
'Ma-la-chi 4:2 tiên tri "Mặt Trời Công Bình" sẽ mọc lên với gì trong cánh?',
'["Sự chữa lành", "Vinh quang", "Lửa", "Ánh sáng"]',
'[0]', 'Mặt Trời Công Bình = Chúa Giê-su. Ngài mang sự chữa lành cho những ai kính sợ Chúa.', '["Cựu Ước","Tiên tri","Chữa lành"]', 'Malachi 4:2', 'vi', true, NOW(), NOW()),
('q-mal-011', 'Malachi', 4, 5, 6, 'medium', 'multiple_choice_single',
'Câu cuối cùng của Cựu Ước tiên tri ai sẽ đến trước ngày lớn của Chúa?',
'["Tiên tri Ê-li (Giăng Báp-tít)", "Môi-se", "Đa-vít", "Ê-li-sê"]',
'[0]', 'Ma-la-chi 4:5 - Chúa Giê-su xác nhận Giăng Báp-tít làm tròn vai trò Ê-li (Mat 11:14).', '["Cựu Ước","Tiên tri","Ê-li"]', 'Malachi 4:5-6', 'vi', true, NOW(), NOW()),
('q-mal-013', 'Malachi', 3, 2, 3, 'easy', 'multiple_choice_single',
'Chúa đến như thợ luyện bạc và luyện vàng để làm gì?',
'["Thánh tẩy con cái Lê-vi để họ dâng của lễ công bình", "Hủy diệt", "Thử thách", "Phán xét"]',
'[0]', 'Sự thánh tẩy không phải hủy diệt mà là làm cho tinh sạch, như luyện kim.', '["Cựu Ước","Ma-la-chi","Thánh tẩy"]', 'Malachi 3:2-3', 'vi', true, NOW(), NOW()),
('q-mal-014', 'Malachi', 2, 10, 10, 'medium', 'multiple_choice_single',
'Ma-la-chi 2:10 hỏi: "Chúng ta chẳng có chung một ___ sao? Chẳng có một Chúa dựng nên chúng ta sao?"',
'["Cha", "Vua", "Chúa", "Nhà"]',
'[0]', 'Mọi người có chung một Cha (Đấng Sáng Tạo). Nên phải đối xử tốt với nhau.', '["Cựu Ước","Ma-la-chi","Hiệp nhất"]', 'Malachi 2:10', 'vi', true, NOW(), NOW()),
('q-mal-015', 'Malachi', 3, 11, 11, 'easy', 'multiple_choice_single',
'Khi dâng phần mười đầy đủ, Chúa hứa sẽ làm gì?',
'["Vì các ngươi cấm những kẻ phá phá (bảo vệ mùa màng)", "Ban thêm vàng", "Cho thêm đất", "Tăng quân đội"]',
'[0]', 'Ma-la-chi 3:11 - Chúa bảo vệ mùa màng khỏi bị phá hại khi dân sự vâng lời trong việc dâng hiến.', '["Cựu Ước","Ma-la-chi","Bảo vệ"]', 'Malachi 3:11', 'vi', true, NOW(), NOW());
