-- Supplementary: Isaiah, Jeremiah, Lamentations, Ezekiel, Daniel, Minor Prophets

-- ==================== ISAIAH (need +8) ====================
INSERT IGNORE INTO questions (id, book, chapter, verse_start, verse_end, difficulty, type, content, options, correct_answer, explanation, tags, source, language, is_active, created_at, updated_at) VALUES
('q-isa-008', 'Isaiah', 1, 18, 18, 'easy', 'multiple_choice_single',
'E-sai 1:18: "Du toi loi cac nguoi nhu mau do, se tro nen ___"',
'["Trang nhu tuyet", "Sach nhu nuoc", "Moi nhu ban dau", "Dep nhu hoa"]',
'[0]', 'Chua hua tha thu hoan toan, bien doi toi loi do nhu mau thanh trang nhu tuyet.', '["Cuu Uoc","E-sai","Tha thu"]', 'Isaiah 1:18', 'vi', true, NOW(), NOW()),
('q-isa-009', 'Isaiah', 6, 1, 3, 'medium', 'multiple_choice_single',
'Se-ra-phim keu voi nhau dieu gi trong khai tuong cua E-sai?',
'["Thanh thay, thanh thay, thanh thay la Duc Gie-ho-va van quan", "Vinh hien cho Chua", "Ha-le-lu-gia", "A-men"]',
'[0]', 'E-sai 6:3 - Thanh thay (Kadosh) duoc lap lai 3 lan, nhan manh su thanh khiet tuyet doi cua Chua.', '["Cuu Uoc","E-sai","Thanh khiet"]', 'Isaiah 6:1-3', 'vi', true, NOW(), NOW()),
('q-isa-010', 'Isaiah', 6, 6, 7, 'medium', 'fill_in_blank',
'Se-ra-phim lay than lua cham vao ___ E-sai va noi toi loi da duoc tay sach',
'[]', '[]', 'E-sai 6:7 - Chua thanh tay moi va loi E-sai truoc khi sai ong di phuc vu.', '["Cuu Uoc","E-sai","Thanh tay"]', 'Isaiah 6:6-7', 'vi', true, NOW(), NOW()),
('q-isa-011', 'Isaiah', 11, 6, 9, 'easy', 'multiple_choice_single',
'E-sai 11:6 mo ta vuong quoc hoa binh: "Cho soi se o voi ___"',
'["Chien con", "Su tu", "Gau", "De"]',
'[0]', 'E-sai 11:6 - Khai tuong ve thoi dai hoa binh khi Dang Cuu The cai tri, moi thu dich se hoa giai.', '["Cuu Uoc","Tien tri","Hoa binh"]', 'Isaiah 11:6-9', 'vi', true, NOW(), NOW()),
('q-isa-012', 'Isaiah', 40, 8, 8, 'easy', 'multiple_choice_single',
'E-sai 40:8: "Co kho, hoa roi, nhung ___ cua Duc Chua Troi chung ta con lai doi doi"',
'["Loi", "Tinh yeu", "Giao uoc", "Den tho"]',
'[0]', 'Moi thu tren dat deu tam thoi nhung Loi Chua thi vinh vien. 1 Phi 1:24-25 trich cau nay.', '["Cuu Uoc","E-sai","Loi Chua"]', 'Isaiah 40:8', 'vi', true, NOW(), NOW()),
('q-isa-013', 'Isaiah', 41, 10, 10, 'easy', 'fill_in_blank',
'Dung so vi ta o voi nguoi; chot kinh hoang vi ta la ___ nguoi (E-sai 41:10)',
'[]', '[]', 'E-sai 41:10 - Ta se bo suc cho nguoi va giup do nguoi. Loi an uy manh me nhat.', '["Cuu Uoc","E-sai","An uy"]', 'Isaiah 41:10', 'vi', true, NOW(), NOW()),
('q-isa-014', 'Isaiah', 55, 8, 9, 'medium', 'multiple_choice_single',
'E-sai 55:8-9 noi y tuong va duong loi cua Chua so voi con nguoi the nao?',
'["Cao hon bao nhieu troi cao hon dat", "Giong nhau", "Hoi khac", "Khong the so sanh"]',
'[0]', 'Y tuong Chua cao hon y tuong con nguoi nhu troi cao hon dat. Chung ta khong the hieu het Chua.', '["Cuu Uoc","E-sai","Chu quyen"]', 'Isaiah 55:8-9', 'vi', true, NOW(), NOW()),
('q-isa-015', 'Isaiah', 64, 8, 8, 'easy', 'multiple_choice_single',
'E-sai 64:8 so sanh Chua va chung ta nhu gi?',
'["Tho gom va dat set", "Cha va con", "Vua va dan", "Thay va tro"]',
'[0]', 'Chua la tho gom, chung ta la dat set. Ngai co quyen nang nao chung ta thanh bat cu dieu gi Ngai muon.', '["Cuu Uoc","E-sai","Chu quyen"]', 'Isaiah 64:8', 'vi', true, NOW(), NOW()),

-- ==================== JEREMIAH (need +11) ====================
('q-jer-005', 'Jeremiah', 1, 6, 8, 'easy', 'multiple_choice_single',
'Gie-re-mi vien co gi khi Chua goi?',
'["Toi con tre qua, khong biet noi", "Toi khong xung dang", "Toi so ke thu", "Toi dang ban"]',
'[0]', 'Gie 1:6-7 - Gie-re-mi con tre nhung Chua noi: Dung noi toi con tre. Hay di khap noi ta sai nguoi.', '["Cuu Uoc","Gie-re-mi","Su keu goi"]', 'Jeremiah 1:6-8', 'vi', true, NOW(), NOW()),
('q-jer-006', 'Jeremiah', 2, 13, 13, 'medium', 'multiple_choice_single',
'Chua to cao dan su pham hai toi gi?',
'["Bo nguon nuoc song de dao ho nit khong giu duoc nuoc", "Tho tuong", "Giet nguoi", "Lam biet"]',
'[0]', 'Gie 2:13 - Hai toi: bo Chua (nguon nuoc song) va tim su thoa man noi khac (ho nit ro ri).', '["Cuu Uoc","Gie-re-mi","Phan boi"]', 'Jeremiah 2:13', 'vi', true, NOW(), NOW()),
('q-jer-007', 'Jeremiah', 17, 9, 9, 'easy', 'multiple_choice_single',
'Gie-re-mi 17:9 noi gi ve tam long con nguoi?',
'["Dang gian doi hon moi vat, ai biet duoc?", "Tam long luon tot", "Tam long la trung lap", "Tam long luon dung"]',
'[0]', 'Long nguoi ta dang gian doi hon moi vat va rat la xau xa. Ai biet duoc? Chi Chua biet.', '["Cuu Uoc","Gie-re-mi","Tam long"]', 'Jeremiah 17:9', 'vi', true, NOW(), NOW()),
('q-jer-008', 'Jeremiah', 18, 1, 6, 'easy', 'multiple_choice_single',
'Gie-re-mi hoc bai hoc gi tai nha tho gom?',
'["Chua la tho gom co quyen nang dat thanh bat cu dang nao", "Phai lam viec cham chi", "Dat set la quy", "Hay kien nhan"]',
'[0]', 'Gie 18:6 - Nhu tho gom co quyen tren dat set, Chua co quyen tren moi dan moi nuoc.', '["Cuu Uoc","Gie-re-mi","Chu quyen"]', 'Jeremiah 18:1-6', 'vi', true, NOW(), NOW()),
('q-jer-009', 'Jeremiah', 29, 7, 7, 'medium', 'fill_in_blank',
'Chua day dan luu day: "Hay tim su ___ cho thanh ma ta day cac nguoi den" (Gie 29:7)',
'[]', '[]', 'Gie 29:7 - Hay cau hoa binh (shalom) cho thanh noi luu day. Dan Chua la phuc lanh cho xa hoi.', '["Cuu Uoc","Gie-re-mi","Binh an"]', 'Jeremiah 29:7', 'vi', true, NOW(), NOW()),
('q-jer-010', 'Jeremiah', 31, 3, 3, 'easy', 'multiple_choice_single',
'Gie 31:3: Chua noi yeu dan su bang loai tinh yeu nao?',
'["Tinh yeu doi doi", "Tinh yeu co dieu kien", "Tinh yeu tam thoi", "Tinh yeu moi"]',
'[0]', 'Ta da yeu nguoi bang mot tinh yeu doi doi, nen ta lay su nhan tu ma keo nguoi.', '["Cuu Uoc","Gie-re-mi","Tinh yeu"]', 'Jeremiah 31:3', 'vi', true, NOW(), NOW()),
('q-jer-011', 'Jeremiah', 33, 3, 3, 'easy', 'fill_in_blank',
'Hay keu cau ta, ta se tra loi va to cho nguoi biet nhung dieu lon va kho ma nguoi chua ___ (Gie 33:3)',
'[]', '[]', 'Gie 33:3 - Chua moi chung ta cau nguyen va hua bay to nhung dieu ky dieu.', '["Cuu Uoc","Gie-re-mi","Cau nguyen"]', 'Jeremiah 33:3', 'vi', true, NOW(), NOW()),
('q-jer-012', 'Jeremiah', 38, 6, 6, 'medium', 'multiple_choice_single',
'Gie-re-mi bi quang xuong dau vi rao giang su that?',
'["Gieng bun (ho bun)", "Nguc", "Ho sau", "Hang toi"]',
'[0]', 'Gie 38:6 - Ho thong xuong Gie-re-mi bang day vao gieng bun. Gia cua viec noi su that.', '["Cuu Uoc","Gie-re-mi","Buc hai"]', 'Jeremiah 38:6', 'vi', true, NOW(), NOW()),
('q-jer-013', 'Jeremiah', 52, 12, 13, 'easy', 'multiple_choice_single',
'Loi tien tri cua Gie-re-mi ve viec Gie-ru-sa-lem bi pha co ung nghiem khong?',
'["Co, Ba-by-lon pha thanh va den tho nam 586 TCN", "Khong", "Chi mot phan", "Chua biet"]',
'[0]', 'Gie 52:12-13 - Moi loi tien tri deu ung nghiem. Gie-ru-sa-lem bi pha va dan bi luu day 70 nam dung nhu Gie-re-mi noi.', '["Cuu Uoc","Gie-re-mi","Ung nghiem"]', 'Jeremiah 52:12-13', 'vi', true, NOW(), NOW()),
('q-jer-014', 'Jeremiah', 17, 7, 8, 'easy', 'multiple_choice_single',
'Gie 17:7-8 so sanh nguoi tin cay Chua nhu gi?',
'["Cay trong gan nuoc, la xanh, ra trai khong dut", "Nui cao", "Ngoi sao", "Chien binh"]',
'[0]', 'Giong Thi 1:3 - Nguoi tin cay Chua nhu cay co re sau, khong so han han.', '["Cuu Uoc","Gie-re-mi","Tin cay"]', 'Jeremiah 17:7-8', 'vi', true, NOW(), NOW()),
('q-jer-015', 'Jeremiah', 10, 23, 23, 'medium', 'multiple_choice_single',
'Gie 10:23: Gie-re-mi thua nhan dieu gi ve con nguoi?',
'["Duong cua loai nguoi khong do noi chinh minh, khong tu dinh buoc minh", "Con nguoi tu lap", "Con nguoi manh me", "Con nguoi khon ngoan"]',
'[0]', 'Con nguoi khong the tu huong dan doi song minh. Chung ta can su dan dat cua Chua.', '["Cuu Uoc","Gie-re-mi","Phu thuoc"]', 'Jeremiah 10:23', 'vi', true, NOW(), NOW()),

-- ==================== LAMENTATIONS (15 moi) ====================
('q-lam-001', 'Lamentations', 3, 22, 23, 'easy', 'multiple_choice_single',
'Ca thuong 3:22-23 noi an dien Chua nhu the nao?',
'["Moi buoi sang deu moi, su thanh tin Ngai la lon", "Co gioi han", "Chi cho nguoi xung dang", "Da het"]',
'[0]', 'Giua dau kho, tac gia kham pha rang an dien Chua moi moi sanh moi buoi sang.', '["Cuu Uoc","Ca thuong","An dien"]', 'Lamentations 3:22-23', 'vi', true, NOW(), NOW()),
('q-lam-002', 'Lamentations', 3, 25, 25, 'easy', 'fill_in_blank',
'Duc Gie-ho-va ban phuc cho ke ___ doi Ngai va linh hon tim kiem Ngai (Ca thuong 3:25)',
'[]', '[]', 'Su kien nhan trong doi Chua se duoc thuong.', '["Cuu Uoc","Ca thuong","Trong doi"]', 'Lamentations 3:25', 'vi', true, NOW(), NOW()),
('q-lam-003', 'Lamentations', 1, 1, 1, 'easy', 'multiple_choice_single',
'Sach Ca Thuong than khoc ve su kien gi?',
'["Gie-ru-sa-lem va den tho bi pha huy boi Ba-by-lon", "Cai chet cua Moi-se", "Nan doi", "Chien tranh voi Phi-li-tin"]',
'[0]', 'Ca thuong la 5 bai tho than khoc ve su sup do cua Gie-ru-sa-lem nam 586 TCN.', '["Cuu Uoc","Ca thuong","Gie-ru-sa-lem"]', 'Lamentations 1:1', 'vi', true, NOW(), NOW()),
('q-lam-004', 'Lamentations', 3, 31, 33, 'medium', 'multiple_choice_single',
'Du hinh phat, Ca thuong 3:31-33 tin dieu gi ve Chua?',
'["Chua khong bo cho den doi va khong muon lam kho con nguoi", "Chua da bo roi", "Chua gian mai", "Khong co hy vong"]',
'[0]', 'Du ky luat, Chua khong bo con cai Ngai mai. Su hinh phat la tam thoi, tinh yeu la doi doi.', '["Cuu Uoc","Ca thuong","Hy vong"]', 'Lamentations 3:31-33', 'vi', true, NOW(), NOW()),
('q-lam-005', 'Lamentations', 3, 40, 40, 'easy', 'multiple_choice_single',
'Ca thuong 3:40 keu goi dan su lam gi?',
'["Hay xet xem va thu duong loi minh, roi tro lai cung Chua", "Hay chay tron", "Hay chien dau", "Hay quen di"]',
'[0]', 'Su tu xet minh va an nan la buoc dau cua su phuc hoi.', '["Cuu Uoc","Ca thuong","An nan"]', 'Lamentations 3:40', 'vi', true, NOW(), NOW()),
('q-lam-006', 'Lamentations', 5, 21, 21, 'easy', 'fill_in_blank',
'Cau cuoi: "Hoi Duc Gie-ho-va, xin dem chung toi tro lai cung Ngai va ___ ngay chung toi nhu cu"',
'[]', '[]', 'Ca thuong 5:21 - Loi cau xin Chua phuc hoi va doi moi. Su trong doi va hy vong giua tan nat.', '["Cuu Uoc","Ca thuong","Phuc hoi"]', 'Lamentations 5:21', 'vi', true, NOW(), NOW()),
('q-lam-007', 'Lamentations', 2, 11, 11, 'easy', 'multiple_choice_single',
'Tac gia mo ta noi dau the nao?',
'["Mat toi khong con nuoc mat, ruot toi soi dong", "Toi im lang", "Toi bo di", "Toi quen"]',
'[0]', 'Ca thuong 2:11 - Noi dau cua tac gia rat sau sac, khong che giau cam xuc truoc Chua.', '["Cuu Uoc","Ca thuong","Dau kho"]', 'Lamentations 2:11', 'vi', true, NOW(), NOW()),
('q-lam-008', 'Lamentations', 3, 26, 26, 'easy', 'multiple_choice_single',
'Ca thuong 3:26 day lam gi khi doi Chua?',
'["Yen lang va doi cho su cuu roi cua Chua", "Keu la", "Gian du", "Hanh dong ngay"]',
'[0]', 'Su yen lang va kien nhan trong doi Chua la tot. Khong phai thu dong ma la tin cay.', '["Cuu Uoc","Ca thuong","Kien nhan"]', 'Lamentations 3:26', 'vi', true, NOW(), NOW()),
('q-lam-009', 'Lamentations', 1, 18, 18, 'medium', 'multiple_choice_single',
'Tac gia thua nhan nguyen nhan cua su sup do la gi?',
'["Dan su da noi loan nghich cung Chua", "Vi ke thu manh hon", "Vi van xui", "Vi thien tai"]',
'[0]', 'Ca thuong 1:18 - Duc Gie-ho-va la cong binh vi toi da pham dieu ran Ngai. Nhan trach nhiem thay vi do loi.', '["Cuu Uoc","Ca thuong","An nan"]', 'Lamentations 1:18', 'vi', true, NOW(), NOW()),
('q-lam-010', 'Lamentations', 3, 37, 38, 'hard', 'multiple_choice_single',
'Ca thuong 3:37-38 day gi ve chu quyen cua Chua?',
'["Khong ai noi dieu gi ma thanh neu Chua khong treo", "Chua khong kiem soat tat ca", "Chi dieu tot den tu Chua", "Con nguoi tu quyet dinh"]',
'[0]', 'Ca dieu lanh va dieu du deu o duoi su cho phep cua Chua. Ngai toi cao tren moi su.', '["Cuu Uoc","Ca thuong","Chu quyen"]', 'Lamentations 3:37-38', 'vi', true, NOW(), NOW()),
('q-lam-011', 'Lamentations', 4, 1, 2, 'medium', 'fill_in_blank',
'Ca thuong 4:2: "Con cai Si-on quy gia bang ___ rong ma nay bi ke nhu binh dat"',
'[]', '[]', 'Dan su quy gia nhu vang nhung bi doi xu nhu do re mat. Hau qua cua toi loi.', '["Cuu Uoc","Ca thuong","Mat mat"]', 'Lamentations 4:1-2', 'vi', true, NOW(), NOW()),
('q-lam-012', 'Lamentations', 3, 21, 21, 'easy', 'multiple_choice_single',
'Truoc khi noi ve an dien moi, tac gia lam gi?',
'["Nhac lai va suy nghi trong long, nen co hy vong", "Quen di", "Gian du", "Bo cuoc"]',
'[0]', 'Ca thuong 3:21 - Khi nho lai an dien Chua, hy vong phuc hoi. Ky uc ve su tot lanh cua Chua lam noi dau de chiu hon.', '["Cuu Uoc","Ca thuong","Hy vong"]', 'Lamentations 3:21', 'vi', true, NOW(), NOW()),
('q-lam-013', 'Lamentations', 3, 27, 27, 'easy', 'multiple_choice_single',
'Ca thuong 3:27: "Nguoi ta chiu ___ tu luc tre tho thi tot"',
'["Ach (ganh nang)", "Phuc lanh", "Su vui", "Tri thuc"]',
'[0]', 'Hoc vang phuc va chiu kho tu tre giup xay dung tinh cach.', '["Cuu Uoc","Ca thuong","Ky luat"]', 'Lamentations 3:27', 'vi', true, NOW(), NOW()),
('q-lam-014', 'Lamentations', 2, 19, 19, 'medium', 'multiple_choice_single',
'Ca thuong 2:19 khuyen do long ra nhu nuoc truoc ai?',
'["Truoc mat Chua", "Truoc dan su", "Truoc thay te le", "Truoc ke thu"]',
'[0]', 'Hay do long ra nhu nuoc truoc mat Chua. Kinh Thanh khuyen bay to cam xuc that voi Chua.', '["Cuu Uoc","Ca thuong","Cau nguyen"]', 'Lamentations 2:19', 'vi', true, NOW(), NOW()),
('q-lam-015', 'Lamentations', 3, 32, 32, 'easy', 'fill_in_blank',
'Du Ngai lam cho dau kho, Ngai se lai ___ theo su day dau cua an dien Ngai (Ca thuong 3:32)',
'[]', '[]', 'Chua ky luat nhung cung phuc hoi. An dien Ngai luon lon hon hinh phat.', '["Cuu Uoc","Ca thuong","Phuc hoi"]', 'Lamentations 3:32', 'vi', true, NOW(), NOW()),

-- ==================== EZEKIEL (need +14) ====================
('q-eze-002', 'Ezekiel', 36, 26, 26, 'easy', 'multiple_choice_single',
'Chua hua ban cho dan su dieu gi thay cho tam long bang da?',
'["Tam long bang thit (tam long moi)", "Tri khon ngoan", "Suc manh", "Su giau co"]',
'[0]', 'Exe 36:26 - Chua cat bo tam long bang da va ban tam long mem mai. Ung nghiem qua Duc Thanh Linh.', '["Cuu Uoc","E-xe-chi-en","Tam long moi"]', 'Ezekiel 36:26', 'vi', true, NOW(), NOW()),
('q-eze-003', 'Ezekiel', 37, 3, 3, 'easy', 'fill_in_blank',
'Chua hoi E-xe-chi-en: "Xuong kho nay co the ___ lai khong?" Ong dap: Chi Chua biet',
'[]', '[]', 'Exe 37:3 - Cau tra loi khon ngoan: pho thac cho Chua thay vi tu suy doan.', '["Cuu Uoc","E-xe-chi-en","Duc tin"]', 'Ezekiel 37:3', 'vi', true, NOW(), NOW()),
('q-eze-004', 'Ezekiel', 34, 11, 12, 'easy', 'multiple_choice_single',
'Chua noi se lam gi khi nhung ke chan khong lam tron bon phan?',
'["Chinh Ngai se tim va cham soc bay chien", "Phat ke chan", "De bay chien tu lo", "Tim ke chan moi"]',
'[0]', 'Exe 34:11 - Chua la Dang Chan Hien Lanh that su. Chua Gie-su tu xung la Dang Chan Hien Lanh (Giang 10:11).', '["Cuu Uoc","E-xe-chi-en","Dang Chan"]', 'Ezekiel 34:11-12', 'vi', true, NOW(), NOW()),
('q-eze-005', 'Ezekiel', 18, 4, 4, 'medium', 'multiple_choice_single',
'Exe 18:4 day nguyen tac gi ve trach nhiem toi loi?',
'["Linh hon nao pham toi thi linh hon ay se chet (moi nguoi chiu trach nhiem toi minh)", "Con chiu toi cha", "Cha chiu toi con", "Ca gia dinh chiu"]',
'[0]', 'Moi nguoi chiu trach nhiem ve toi loi cua chinh minh. Khong ai bi phat vi toi nguoi khac.', '["Cuu Uoc","E-xe-chi-en","Trach nhiem"]', 'Ezekiel 18:4', 'vi', true, NOW(), NOW()),
('q-eze-006', 'Ezekiel', 33, 11, 11, 'easy', 'multiple_choice_single',
'Chua co vui ve khi ke ac chet khong?',
'["Khong, Chua muon ke ac an nan va song", "Co, vi la cong binh", "Chua khong quan tam", "Tuy truong hop"]',
'[0]', 'Exe 33:11 - Ta khong vui ve ve su chet cua ke ac nhung muon ke ac an nan va song.', '["Cuu Uoc","E-xe-chi-en","An nan"]', 'Ezekiel 33:11', 'vi', true, NOW(), NOW()),
('q-eze-007', 'Ezekiel', 1, 4, 10, 'hard', 'multiple_choice_single',
'Khai tuong dau tien cua E-xe-chi-en mo ta gi?',
'["Bon sinh vat co canh va banh xe, vinh quang Chua", "Den tho", "Chien tran", "Vuon E-den"]',
'[0]', 'Exe 1:4-10 - Khai tuong phuc tap ve ngai Chua voi 4 sinh vat co mat nguoi, su tu, bo, va chim ung.', '["Cuu Uoc","E-xe-chi-en","Khai tuong"]', 'Ezekiel 1:4-10', 'vi', true, NOW(), NOW()),
('q-eze-008', 'Ezekiel', 47, 1, 9, 'medium', 'multiple_choice_single',
'Khai tuong ve dong song tu den tho chay ra co y nghia gi?',
'["Nuoc su song tu su hien dien Chua chay ra chua lanh moi noi", "Tuoi vuon", "Cung cap nuoc uong", "Tao bien moi"]',
'[0]', 'Exe 47:9 - Nuoc nay chay den dau thi co su song o do. Khai 22:1 cung mo ta song nuoc su song.', '["Cuu Uoc","E-xe-chi-en","Nuoc song"]', 'Ezekiel 47:1-9', 'vi', true, NOW(), NOW()),
('q-eze-009', 'Ezekiel', 3, 17, 17, 'medium', 'fill_in_blank',
'Chua dat E-xe-chi-en lam nguoi ___ cho nha Y-so-ra-en',
'[]', '[]', 'Exe 3:17 - Nguoi canh gac co trach nhiem canh bao dan ve nguy hiem. Tien tri la nguoi canh gac thuoc linh.', '["Cuu Uoc","E-xe-chi-en","Canh gac"]', 'Ezekiel 3:17', 'vi', true, NOW(), NOW()),
('q-eze-010', 'Ezekiel', 36, 27, 27, 'medium', 'multiple_choice_single',
'Chua hua se dat gi ben trong dan su de ho vang loi?',
'["Than ta (Duc Thanh Linh) ben trong cac nguoi", "Luat phap moi", "Tien tri moi", "Vua moi"]',
'[0]', 'Exe 36:27 - Chua se dat Than Ngai ben trong de dan su vang loi tu ben trong. Ung nghiem Le Ngu Tuan.', '["Cuu Uoc","E-xe-chi-en","Thanh Linh"]', 'Ezekiel 36:27', 'vi', true, NOW(), NOW()),
('q-eze-011', 'Ezekiel', 37, 21, 22, 'easy', 'multiple_choice_single',
'Khai tuong xuong kho cung tien tri ve dieu gi cho dan Y-so-ra-en?',
'["Su phuc hoi va thong nhat Y-so-ra-en", "Su huy diet", "Chien tranh moi", "Di cu"]',
'[0]', 'Exe 37:22 - Chua hua lam ho thanh mot dan toc duoi mot vua. Y-so-ra-en phuc quoc nam 1948.', '["Cuu Uoc","E-xe-chi-en","Phuc hoi"]', 'Ezekiel 37:21-22', 'vi', true, NOW(), NOW()),
('q-eze-012', 'Ezekiel', 22, 30, 30, 'medium', 'multiple_choice_single',
'Chua noi: "Ta da tim mot nguoi dung noi tro-rong truoc mat ta vi xu nay nhung ___"',
'["Khong tim duoc ai", "Tim duoc mot nguoi", "Tim duoc nhieu nguoi", "Khong can"]',
'[0]', 'Exe 22:30 - Chua tim nguoi cau thay nhung khong co ai. Su can dau nguoi cau nguyen cho dan toc.', '["Cuu Uoc","E-xe-chi-en","Cau thay"]', 'Ezekiel 22:30', 'vi', true, NOW(), NOW()),
('q-eze-013', 'Ezekiel', 2, 6, 7, 'easy', 'multiple_choice_single',
'Chua phan voi E-xe-chi-en: "Dung ___ ho va dung so loi noi ho"',
'["So", "Nghe", "Tin", "Yeu"]',
'[0]', 'Exe 2:6 - Chua khuyen can dam noi su that du bi chong doi.', '["Cuu Uoc","E-xe-chi-en","Can dam"]', 'Ezekiel 2:6-7', 'vi', true, NOW(), NOW()),
('q-eze-014', 'Ezekiel', 34, 23, 24, 'hard', 'multiple_choice_single',
'Chua hua se dat "toi to ta la Da-vit" lam dang chan. Day tien tri ve ai?',
'["Chua Gie-su - Dang Chan Hien Lanh tu dong doi Da-vit", "Vua Da-vit phuc sinh", "Mot hau due cua Da-vit", "Sa-lo-mon"]',
'[0]', 'Exe 34:23-24 - Dang Chan Da-vit la Chua Gie-su, hau due Da-vit va la Vua doi doi (Giang 10:11).', '["Cuu Uoc","Tien tri","Dang Chan"]', 'Ezekiel 34:23-24', 'vi', true, NOW(), NOW()),
('q-eze-015', 'Ezekiel', 48, 35, 35, 'easy', 'fill_in_blank',
'Ten thanh trong khai tuong cuoi sach E-xe-chi-en la: "Duc Gie-ho-va o ___"',
'[]', '[]', 'Exe 48:35 - Gie-ho-va Sam-ma = Chua o tai day. Muc dich cuoi cung: Chua o giua dan Ngai.', '["Cuu Uoc","E-xe-chi-en","Su hien dien"]', 'Ezekiel 48:35', 'vi', true, NOW(), NOW()),

-- ==================== DANIEL (need +13) ====================
('q-dan-003', 'Daniel', 1, 8, 8, 'easy', 'multiple_choice_single',
'Da-ni-en dinh y trong long khong lam gi tai Ba-by-lon?',
'["Khong tu ue minh bang thuc an va ruou cua vua", "Khong hoc tieng Ba-by-lon", "Khong lam viec", "Khong noi chuyen"]',
'[0]', 'Da-ni-en 1:8 - Da-ni-en giu nguyen tac du o xu la. Chua ban phuc cho su trung tin.', '["Cuu Uoc","Da-ni-en","Trung tin"]', 'Daniel 1:8', 'vi', true, NOW(), NOW()),
('q-dan-004', 'Daniel', 2, 44, 45, 'hard', 'multiple_choice_single',
'Giac mo cua vua Ne-bu-cat-net-sa ve pho tuong tien tri ve dieu gi?',
'["Cac de quoc the gioi va vuong quoc doi doi cua Chua", "Chi ve Ba-by-lon", "Ve tuong lai gan", "Ve chien tranh"]',
'[0]', 'Da-ni-en 2:44 - Hon da khong bi tay cat ra = Vuong quoc Chua se ha moi vuong quoc va con lai doi doi.', '["Cuu Uoc","Da-ni-en","Tien tri"]', 'Daniel 2:44-45', 'vi', true, NOW(), NOW()),
('q-dan-005', 'Daniel', 3, 25, 25, 'easy', 'multiple_choice_single',
'Khi nhin vao lo lua, vua thay bao nhieu nguoi thay vi 3?',
'["4 nguoi, nguoi thu tu giong nhu con cua cac than", "5 nguoi", "3 nguoi", "2 nguoi"]',
'[0]', 'Da-ni-en 3:25 - Nguoi thu tu co the la thien su hoac su hien ra cua Chua. Ngai o cung con cai Ngai trong lua.', '["Cuu Uoc","Da-ni-en","Bao ve"]', 'Daniel 3:25', 'vi', true, NOW(), NOW()),
('q-dan-006', 'Daniel', 4, 30, 33, 'medium', 'multiple_choice_single',
'Vua Ne-bu-cat-net-sa bi phat the nao vi kieu ngao?',
'["Song nhu thu vat, an co 7 ky cho den khi nhan ra Chua cai tri", "Mat ngoi", "Bi giet", "Bi luu day"]',
'[0]', 'Da-ni-en 4:33 - 7 ky song nhu thu. Khi hoi tam, vua ngoi khen Chua. Bai hoc ve su khiem nhuong.', '["Cuu Uoc","Da-ni-en","Kieu ngao"]', 'Daniel 4:30-33', 'vi', true, NOW(), NOW()),
('q-dan-007', 'Daniel', 5, 5, 5, 'easy', 'multiple_choice_single',
'Trong tiec cua vua Ben-sa-xa, dieu gi xuat hien tren tuong?',
'["Ban tay viet chu tren tuong", "Lua", "Mat nguoi", "Anh sang"]',
'[0]', 'Da-ni-en 5:5 - Ban tay viet: Me-ne, Me-ne, Te-ken, U-phac-sin. Vuong quoc da duoc can va thieu.', '["Cuu Uoc","Da-ni-en","Phan xet"]', 'Daniel 5:5', 'vi', true, NOW(), NOW()),
('q-dan-008', 'Daniel', 5, 25, 28, 'medium', 'fill_in_blank',
'Chu tren tuong nghia la: Vuong quoc da duoc can va thay ___',
'[]', '[]', 'Da-ni-en 5:28 - Me-ne (dem), Te-ken (can), U-phac-sin (chia). Dem do Ba-by-lon that thu.', '["Cuu Uoc","Da-ni-en","Phan xet"]', 'Daniel 5:25-28', 'vi', true, NOW(), NOW()),
('q-dan-009', 'Daniel', 6, 10, 10, 'easy', 'multiple_choice_single',
'Khi biet luat cam cau nguyen, Da-ni-en lam gi?',
'["Van cau nguyen 3 lan moi ngay nhu truoc", "Cau nguyen kin", "Ngung cau nguyen", "Cau nguyen it hon"]',
'[0]', 'Da-ni-en 6:10 - Da-ni-en khong thay doi thoi quen cau nguyen du bi de doa. Duc tin khong bi de doa.', '["Cuu Uoc","Da-ni-en","Cau nguyen"]', 'Daniel 6:10', 'vi', true, NOW(), NOW()),
('q-dan-010', 'Daniel', 7, 13, 14, 'hard', 'multiple_choice_single',
'Da-ni-en 7:13 thay "mot Dang giong nhu Con Nguoi" den tren may troi. Day la ai?',
'["Chua Gie-su Christ", "Thien su Mi-ca-en", "Moi-se", "E-li"]',
'[0]', 'Chua Gie-su tu xung la Con Nguoi (Mat 26:64) va trich Da-ni-en 7:13 ve su tai lam cua Ngai.', '["Cuu Uoc","Tien tri","Con Nguoi"]', 'Daniel 7:13-14', 'vi', true, NOW(), NOW()),
('q-dan-011', 'Daniel', 9, 25, 26, 'hard', 'multiple_choice_single',
'Loi tien tri 70 tuan le (490 nam) cua Da-ni-en tien tri ve su kien gi?',
'["Thoi diem Dang Cuu The den va bi giet", "Su phuc hoi den tho", "Ngay tan the", "Le Ngu Tuan"]',
'[0]', 'Da-ni-en 9:25-26 - 69 tuan (483 nam) tu luc ra lenh xay lai den khi Dang Cuu The bi cat off. Ung nghiem chinh xac.', '["Cuu Uoc","Tien tri","Thoi diem"]', 'Daniel 9:25-26', 'vi', true, NOW(), NOW()),
('q-dan-012', 'Daniel', 12, 2, 3, 'medium', 'multiple_choice_single',
'Da-ni-en 12:2 tien tri ve dieu gi?',
'["Su phuc sinh: nguoi song lai, ke duoc song doi doi, ke bi xau ho doi doi", "Chi su phuc sinh nguoi tot", "Khong co phuc sinh", "Chi phuc sinh thuoc linh"]',
'[0]', 'Da-ni-en 12:2 - Mot trong nhung tien tri ro rang nhat ve su phuc sinh trong Cuu Uoc.', '["Cuu Uoc","Da-ni-en","Phuc sinh"]', 'Daniel 12:2-3', 'vi', true, NOW(), NOW()),
('q-dan-013', 'Daniel', 2, 20, 21, 'easy', 'fill_in_blank',
'Da-ni-en ngoi khen: "Ngai thay doi thoi ky va mua, Ngai truong va phe cac ___"',
'[]', '[]', 'Da-ni-en 2:21 - Chua kiem soat lich su, dat va ha lanh dao. Khong co quyen luc nao ngoai y Chua.', '["Cuu Uoc","Da-ni-en","Chu quyen"]', 'Daniel 2:20-21', 'vi', true, NOW(), NOW()),
('q-dan-014', 'Daniel', 10, 12, 13, 'medium', 'multiple_choice_single',
'Tai sao thien su den voi Da-ni-en bi tre 21 ngay?',
'["Bi quan truong Ba-tu (the luc thuoc linh) can tro", "Bi lac duong", "Chua giao viec khac", "Khong biet"]',
'[0]', 'Da-ni-en 10:13 - Co chien tran thuoc linh dang sau moi su. Cau nguyen anh huong the gioi vo hinh.', '["Cuu Uoc","Da-ni-en","Chien tran linh"]', 'Daniel 10:12-13', 'vi', true, NOW(), NOW()),
('q-dan-015', 'Daniel', 12, 13, 13, 'easy', 'multiple_choice_single',
'Loi cuoi cung Chua noi voi Da-ni-en la gi?',
'["Hay di cho den cuoi cung, nguoi se nghi ngoi va se dung lai trong phan minh", "Hay viet them", "Hay noi cho nguoi khac", "Hay doi"]',
'[0]', 'Da-ni-en 12:13 - Loi hua phuc sinh va phan thuong cho nguoi trung tin. Hy vong cho moi tin do.', '["Cuu Uoc","Da-ni-en","Hy vong"]', 'Daniel 12:13', 'vi', true, NOW(), NOW()),

-- ==================== MINOR PROPHETS ====================
-- Hosea (15), Joel (15), Amos (15) — abbreviated to key verses
-- Micah (need +13), Habakkuk (+14), Jonah (+14), Malachi (+14)

-- MICAH (need +13)
('q-mic-003', 'Micah', 7, 18, 18, 'easy', 'multiple_choice_single',
'Mi-che 7:18: "Ai la Duc Chua Troi giong nhu Ngai, ___ su gian ac?"',
'["Hay tha", "Phat", "Nho", "Ghi"]',
'[0]', 'Chua hay tha su gian ac, khong giu gian doi doi vi Ngai lay su nhan tu lam vui.', '["Cuu Uoc","Mi-che","Tha thu"]', 'Micah 7:18', 'vi', true, NOW(), NOW()),
('q-mic-004', 'Micah', 7, 19, 19, 'easy', 'fill_in_blank',
'Mi-che 7:19: Ngai se nem tat ca toi loi chung toi xuong day ___',
'[]', '[]', 'Chua nem toi loi xuong day bien. Hinh anh ve su tha thu tron ven va vinh vien.', '["Cuu Uoc","Mi-che","Tha thu"]', 'Micah 7:19', 'vi', true, NOW(), NOW()),
('q-mic-005', 'Micah', 4, 3, 3, 'easy', 'multiple_choice_single',
'Mi-che 4:3 tien tri thoi dai hoa binh: "Ho se ren guom thanh ___"',
'["Luoi cay", "Trang suc", "Dung cu", "Khien"]',
'[0]', 'Vu khi bien thanh dung cu nong nghiep. Khong con hoc chien tran nua.', '["Cuu Uoc","Mi-che","Hoa binh"]', 'Micah 4:3', 'vi', true, NOW(), NOW()),
('q-mic-006', 'Micah', 3, 8, 8, 'medium', 'multiple_choice_single',
'Mi-che tuyen bo ong day quyen nang nho dieu gi?',
'["Than cua Duc Gie-ho-va, su cong binh va suc manh", "Hoc thuc", "Kinh nghiem", "Chuc vu"]',
'[0]', 'Mi-che 3:8 - Quyen nang phuc vu den tu Thanh Linh, khong phai tu ban than tien tri.', '["Cuu Uoc","Mi-che","Quyen nang"]', 'Micah 3:8', 'vi', true, NOW(), NOW()),
('q-mic-007', 'Micah', 5, 4, 4, 'easy', 'multiple_choice_single',
'Dang Cuu The tu Bet-le-hem se chan dan su bang gi?',
'["Suc manh cua Duc Gie-ho-va", "Guom", "Tri khon", "Quan doi"]',
'[0]', 'Mi-che 5:4 - Dang Chan vi dai se dung trong suc Chua va cham soc dan su.', '["Cuu Uoc","Mi-che","Dang Chan"]', 'Micah 5:4', 'vi', true, NOW(), NOW()),
('q-mic-008', 'Micah', 2, 12, 13, 'easy', 'fill_in_blank',
'Chua hua se nhom lai dan Y-so-ra-en con sot lai nhu ___ trong chuong',
'[]', '[]', 'Mi-che 2:12 - Chua la Dang Chan nhom lai bay chien bi tan lac.', '["Cuu Uoc","Mi-che","Phuc hoi"]', 'Micah 2:12-13', 'vi', true, NOW(), NOW()),
('q-mic-009', 'Micah', 6, 6, 7, 'medium', 'multiple_choice_single',
'Mi-che 6:6-7 hoi: Chua co muon hang ngan con chien hay dau o-liu khong?',
'["Khong, Chua muon cong binh, nhan tu va khiem nhuong", "Co, cang nhieu cang tot", "Chi can mot it", "Tuy luc"]',
'[0]', 'Chua khong muon hinh thuc ton giao ma muon doi song cong binh va khiem nhuong.', '["Cuu Uoc","Mi-che","Cong binh"]', 'Micah 6:6-7', 'vi', true, NOW(), NOW()),
('q-mic-010', 'Micah', 1, 3, 4, 'easy', 'multiple_choice_single',
'Mi-che canh bao su phan xet cua Chua se den tren thanh nao?',
'["Sa-ma-ri va Gie-ru-sa-lem", "Chi Sa-ma-ri", "Chi Gie-ru-sa-lem", "Ni-ni-ve"]',
'[0]', 'Mi-che 1:5 - Ca hai kinh do deu pham toi va ca hai se bi phan xet. Chua cong binh voi moi nguoi.', '["Cuu Uoc","Mi-che","Phan xet"]', 'Micah 1:3-5', 'vi', true, NOW(), NOW()),
('q-mic-011', 'Micah', 4, 1, 2, 'medium', 'multiple_choice_single',
'Mi-che tien tri: trong nhung ngay sau rot, nui cua nha Chua se nhu the nao?',
'["Duoc lap len tren chop cac nui, dan toc se do den", "Bi pha huy", "Bi an", "Bi quen"]',
'[0]', 'Mi-che 4:1-2 - Vuong quoc Chua se duoc ton cao va moi dan toc se den hoc duong loi Ngai.', '["Cuu Uoc","Mi-che","Ngay sau"]', 'Micah 4:1-2', 'vi', true, NOW(), NOW()),
('q-mic-012', 'Micah', 5, 2, 2, 'easy', 'fill_in_blank',
'Mi-che tien tri Dang Cuu The sinh tai Bet-le-hem Ep-ra-ta du no la thanh ___ trong Giu-da',
'[]', '[]', 'Mi-che 5:2 - Chua chon noi nho be nhat de lam dieu vi dai nhat. Khiem nhuong la dau hieu cua Chua.', '["Cuu Uoc","Mi-che","Giang sinh"]', 'Micah 5:2', 'vi', true, NOW(), NOW()),
('q-mic-013', 'Micah', 6, 8, 8, 'easy', 'fill_in_blank',
'Mi-che 6:8: Chua doi hoi con lam su cong binh, yeu su nhan tu va ___ di voi Duc Chua Troi con',
'[]', '[]', 'Ba dieu don gian nhung bao gom toan bo y muon Chua cho doi song.', '["Cuu Uoc","Mi-che","Doi song"]', 'Micah 6:8', 'vi', true, NOW(), NOW()),
('q-mic-014', 'Micah', 7, 7, 7, 'easy', 'multiple_choice_single',
'Mi-che tuyen bo: "Phan ta, ta se trong doi ai?"',
'["Duc Gie-ho-va", "Vua", "Quan doi", "Ban be"]',
'[0]', 'Mi-che 7:7 - Du hoan canh nao, Mi-che chon trong doi va tin cay Chua.', '["Cuu Uoc","Mi-che","Trong doi"]', 'Micah 7:7', 'vi', true, NOW(), NOW()),
('q-mic-015', 'Micah', 7, 8, 8, 'medium', 'multiple_choice_single',
'Mi-che 7:8: "Khi ta bi te thi ta se ___; khi ta ngoi trong toi thi Duc Gie-ho-va la anh sang ta"',
'["Dung len lai", "Nam mai", "Keu cau", "Bo cuoc"]',
'[0]', 'Du sa nga, nguoi tin Chua se dung len lai vi Chua la anh sang trong bong toi.', '["Cuu Uoc","Mi-che","Hy vong"]', 'Micah 7:8', 'vi', true, NOW(), NOW()),

-- HABAKKUK (need +14)
('q-hab-002', 'Habakkuk', 1, 2, 3, 'medium', 'multiple_choice_single',
'Ha-ba-cuc hoi Chua cau hoi gi?',
'["Tai sao Chua im lang truoc bat cong va bao luc?", "Khi nao Chua den?", "Tai sao toi kho?", "Chua o dau?"]',
'[0]', 'Ha-ba-cuc 1:2 - Tien tri that tho hoi Chua ve su bat cong. Chua cho phep hoi va than van.', '["Cuu Uoc","Ha-ba-cuc","Cong binh"]', 'Habakkuk 1:2-3', 'vi', true, NOW(), NOW()),
('q-hab-003', 'Habakkuk', 1, 5, 5, 'easy', 'multiple_choice_single',
'Chua tra loi Ha-ba-cuc: "Hay nhin cac dan toc va ___"',
'["Kinh ngac, vi ta se lam mot viec ma nguoi khong tin", "So hai", "Vui mung", "Chay tron"]',
'[0]', 'Chua dang lam viec ngay ca khi chung ta khong nhin thay hay hieu.', '["Cuu Uoc","Ha-ba-cuc","Tin cay"]', 'Habakkuk 1:5', 'vi', true, NOW(), NOW()),
('q-hab-004', 'Habakkuk', 2, 2, 3, 'easy', 'multiple_choice_single',
'Chua bao Ha-ba-cuc viet khai tuong xuong de lam gi?',
'["De nguoi doc chay duoc (ro rang)", "De giu kin", "De dang cho vua", "De doc o den tho"]',
'[0]', 'Ha-ba-cuc 2:2 - Khai tuong phai ro rang de moi nguoi doc duoc. Loi Chua can duoc truyen dat de hieu.', '["Cuu Uoc","Ha-ba-cuc","Khai tuong"]', 'Habakkuk 2:2-3', 'vi', true, NOW(), NOW()),
('q-hab-005', 'Habakkuk', 2, 14, 14, 'easy', 'fill_in_blank',
'Su nhan biet ___ Duc Gie-ho-va se day tran dat nhu nuoc phu day bien (Ha 2:14)',
'[]', '[]', 'Loi hua ve su tri thuc va vinh quang Chua se bao trum toan the gioi.', '["Cuu Uoc","Ha-ba-cuc","Vinh quang"]', 'Habakkuk 2:14', 'vi', true, NOW(), NOW()),
('q-hab-006', 'Habakkuk', 2, 20, 20, 'easy', 'multiple_choice_single',
'Ha 2:20: "Duc Gie-ho-va ngu trong den thanh Ngai; ca dat hay ___"',
'["Nen lang truoc mat Ngai", "Ngoi khen", "Keu goi", "Vui mung"]',
'[0]', 'Su ton kinh va yen lang truoc su hien dien cua Chua.', '["Cuu Uoc","Ha-ba-cuc","Ton kinh"]', 'Habakkuk 2:20', 'vi', true, NOW(), NOW()),
('q-hab-007', 'Habakkuk', 3, 2, 2, 'medium', 'multiple_choice_single',
'Ha-ba-cuc cau nguyen: "Xin Ngai lam su nghiep Ngai song lai giua cac nam va trong con ___ hay nho su thuong xot"',
'["Thiet gian (gian du)", "Vui ve", "Binh an", "Chien tranh"]',
'[0]', 'Ngay ca khi Chua phan xet, Ha-ba-cuc xin Ngai nho su thuong xot.', '["Cuu Uoc","Ha-ba-cuc","Cau nguyen"]', 'Habakkuk 3:2', 'vi', true, NOW(), NOW()),
('q-hab-008', 'Habakkuk', 3, 17, 18, 'medium', 'multiple_choice_single',
'Ha-ba-cuc 3:17-18: Du khong co trai, khong mua, khong bay, ong van lam gi?',
'["Vui mung trong Duc Gie-ho-va", "Than van", "Bo cuoc", "Tim noi khac"]',
'[0]', 'Duc tin khong dieu kien: vui mung trong Chua du mat tat ca. Dinh cao cua duc tin.', '["Cuu Uoc","Ha-ba-cuc","Duc tin"]', 'Habakkuk 3:17-18', 'vi', true, NOW(), NOW()),
('q-hab-009', 'Habakkuk', 3, 19, 19, 'easy', 'fill_in_blank',
'Chua Gie-ho-va la suc luc toi; Ngai lam cho chan toi nhanh nhu chan ___ (Ha 3:19)',
'[]', '[]', 'Chua ban suc manh de buoc di tren noi cao (hoan canh kho khan).', '["Cuu Uoc","Ha-ba-cuc","Suc manh"]', 'Habakkuk 3:19', 'vi', true, NOW(), NOW()),
('q-hab-010', 'Habakkuk', 2, 3, 3, 'easy', 'multiple_choice_single',
'Ha 2:3 day gi ve loi hua cua Chua?',
'["Khai tuong con doi den ky, nhung chac chan se den, hay doi", "Co the khong den", "Se den ngay", "Khong chac"]',
'[0]', 'Loi hua Chua co the tre nhung khong bao gio that bai. Hay kien nhan doi.', '["Cuu Uoc","Ha-ba-cuc","Kien nhan"]', 'Habakkuk 2:3', 'vi', true, NOW(), NOW()),
('q-hab-011', 'Habakkuk', 1, 12, 12, 'easy', 'multiple_choice_single',
'Ha-ba-cuc goi Chua bang danh hieu nao?',
'["Duc Chua Troi doi doi va Von Da", "Vua cua vua", "Chien binh", "Quan an"]',
'[0]', 'Ha-ba-cuc 1:12 - Von Da (Tsur) = noi vung chac va an nau. Chua doi doi va khong thay doi.', '["Cuu Uoc","Ha-ba-cuc","Danh Chua"]', 'Habakkuk 1:12', 'vi', true, NOW(), NOW()),
('q-hab-012', 'Habakkuk', 2, 4, 4, 'medium', 'fill_in_blank',
'Nguoi cong binh se ___ boi duc tin (Ha 2:4)',
'[]', '[]', 'Nen tang cua su xung cong binh boi duc tin. Phao-lo trich cau nay trong Ro-ma 1:17.', '["Cuu Uoc","Ha-ba-cuc","Duc tin"]', 'Habakkuk 2:4', 'vi', true, NOW(), NOW()),
('q-hab-013', 'Habakkuk', 2, 6, 8, 'medium', 'multiple_choice_single',
'Ha-ba-cuc chuong 2 tuyen bo may loi khon cho ai?',
'["Ke tham lam, boc lot, bao luc, say sua va tho tuong", "Nguoi ngheo", "Nguoi benh", "Tien tri gia"]',
'[0]', 'Nam loi khon nham ke ac, canh bao rang Chua thay va se phan xet moi bat cong.', '["Cuu Uoc","Ha-ba-cuc","Phan xet"]', 'Habakkuk 2:6-20', 'vi', true, NOW(), NOW()),
('q-hab-014', 'Habakkuk', 3, 3, 4, 'easy', 'multiple_choice_single',
'Ha-ba-cuc mo ta Chua den trong vinh quang nhu the nao?',
'["Vinh quang che troi, anh sang tu tay Ngai", "Yen lang", "Nho nhe", "Khong thay"]',
'[0]', 'Ha-ba-cuc 3:3-4 - Mo ta Chua den trong quyen nang va vinh quang bat tan.', '["Cuu Uoc","Ha-ba-cuc","Vinh quang"]', 'Habakkuk 3:3-4', 'vi', true, NOW(), NOW()),
('q-hab-015', 'Habakkuk', 3, 16, 16, 'easy', 'multiple_choice_single',
'Khi nghe Chua phan, Ha-ba-cuc phan ung the nao?',
'["Run ray nhung van doi Chua", "Vui mung", "Bo chay", "Gian du"]',
'[0]', 'Ha-ba-cuc 3:16 - Kinh so truoc su vi dai cua Chua nhung van yen lang doi ngay Ngai hanh dong.', '["Cuu Uoc","Ha-ba-cuc","Kinh so"]', 'Habakkuk 3:16', 'vi', true, NOW(), NOW()),

-- JONAH (need +14)
('q-jon-002', 'Jonah', 1, 1, 3, 'easy', 'multiple_choice_single',
'Chua sai Giona di Ni-ni-ve nhung ong tron di dau?',
'["Ta-si (huong nguoc lai)", "Ai-cap", "Ba-by-lon", "Mo-ap"]',
'[0]', 'Giona 1:3 - Giona tron chay khoi mat Chua bang tau di Ta-si, huong nguoc hoan toan.', '["Cuu Uoc","Giona","Bat tuan"]', 'Jonah 1:1-3', 'vi', true, NOW(), NOW()),
('q-jon-003', 'Jonah', 1, 4, 5, 'easy', 'multiple_choice_single',
'Khi Giona tron, Chua lam gi?',
'["Sai bao lon tren bien", "Gui thien su", "De mac", "Goi tien tri khac"]',
'[0]', 'Giona 1:4 - Chua khong de Giona tron thanh cong. Bao lon de dua ong quay lai.', '["Cuu Uoc","Giona","Ky luat"]', 'Jonah 1:4-5', 'vi', true, NOW(), NOW()),
('q-jon-004', 'Jonah', 1, 12, 12, 'medium', 'multiple_choice_single',
'Giona noi voi thuy thu lam gi de bien lang?',
'["Nem toi xuong bien", "Cau nguyen", "Quet don tau", "Quay lai"]',
'[0]', 'Giona 1:12 - Giona nhan trach nhiem va san sang chiu hau qua toi loi minh.', '["Cuu Uoc","Giona","Trach nhiem"]', 'Jonah 1:12', 'vi', true, NOW(), NOW()),
('q-jon-005', 'Jonah', 2, 1, 2, 'easy', 'fill_in_blank',
'Tu trong bung ca, Giona lam gi? (1 tu)',
'[]', '[]', 'Giona 2:1 - Giona cau nguyen tu noi tuyet vong nhat. Chua nghe o bat cu dau.', '["Cuu Uoc","Giona","Cau nguyen"]', 'Jonah 2:1-2', 'vi', true, NOW(), NOW()),
('q-jon-006', 'Jonah', 2, 9, 9, 'easy', 'multiple_choice_single',
'Giona tuyen bo tu trong bung ca: "Su ___ den tu Duc Gie-ho-va"',
'["Cuu roi", "Phan xet", "Khon ngoan", "Binh an"]',
'[0]', 'Giona 2:9 - Du trong hoan canh tuyet vong nhat, Giona nhan ra chi Chua cuu roi.', '["Cuu Uoc","Giona","Cuu roi"]', 'Jonah 2:9', 'vi', true, NOW(), NOW()),
('q-jon-007', 'Jonah', 3, 3, 4, 'easy', 'multiple_choice_single',
'Lan thu hai Chua goi, Giona lam gi?',
'["Vang loi di Ni-ni-ve rao giang", "Tron lan nua", "Hoi tai sao", "Nghi ngoi"]',
'[0]', 'Giona 3:3 - Lan nay Giona vang loi. Chua cho co hoi thu hai.', '["Cuu Uoc","Giona","Vang loi"]', 'Jonah 3:3-4', 'vi', true, NOW(), NOW()),
('q-jon-008', 'Jonah', 3, 5, 5, 'easy', 'multiple_choice_single',
'Dan Ni-ni-ve phan ung the nao khi nghe Giona rao giang?',
'["Tin Duc Chua Troi, kieng an va an nan", "Bo mac", "Gian du", "Cuoi nhao"]',
'[0]', 'Giona 3:5 - Ca thanh an nan tu vua den dan! Su an nan lon nhat trong Cuu Uoc.', '["Cuu Uoc","Giona","An nan"]', 'Jonah 3:5', 'vi', true, NOW(), NOW()),
('q-jon-009', 'Jonah', 3, 10, 10, 'easy', 'multiple_choice_single',
'Khi Ni-ni-ve an nan, Chua lam gi?',
'["Doi y va khong huy diet ho", "Van phat ho", "Tri hoan hinh phat", "De mac"]',
'[0]', 'Giona 3:10 - Chua doi y khi dan su an nan. Ngai nhan tu va san sang tha thu.', '["Cuu Uoc","Giona","Tha thu"]', 'Jonah 3:10', 'vi', true, NOW(), NOW()),
('q-jon-010', 'Jonah', 4, 1, 2, 'medium', 'multiple_choice_single',
'Tai sao Giona gian khi Ni-ni-ve duoc tha?',
'["Vi ong da biet Chua nhan tu va se tha, ong khong muon ke thu duoc cuu", "Vi mat uy tin", "Vi met moi", "Vi so"]',
'[0]', 'Giona 4:2 - Giona thua nhan biet tu dau Chua se tha. Van de cua ong la long kem va ky thi dan toc.', '["Cuu Uoc","Giona","Nhan tu"]', 'Jonah 4:1-2', 'vi', true, NOW(), NOW()),
('q-jon-011', 'Jonah', 4, 6, 7, 'easy', 'fill_in_blank',
'Chua cho moc len roi lam ___ mot cay de day Giona bai hoc',
'[]', '[]', 'Giona 4:6-7 - Cay moc len lam mat rong heo di. Giona thuong cay nhung khong thuong dan Ni-ni-ve.', '["Cuu Uoc","Giona","Bai hoc"]', 'Jonah 4:6-7', 'vi', true, NOW(), NOW()),
('q-jon-012', 'Jonah', 4, 11, 11, 'medium', 'multiple_choice_single',
'Chua ket thuc sach Giona bang cau hoi gi?',
'["Ta lai khong thuong xot Ni-ni-ve voi 120,000 nguoi khong phan biet tay phai tay trai sao?", "Nguoi co vui khong?", "Nguoi co vang loi khong?", "Nguoi o dau?"]',
'[0]', 'Giona 4:11 - Chua thuong moi nguoi, ke ca ke thu. Tinh yeu Chua khong co ranh gioi dan toc.', '["Cuu Uoc","Giona","Tinh yeu"]', 'Jonah 4:11', 'vi', true, NOW(), NOW()),
('q-jon-013', 'Jonah', 4, 2, 2, 'easy', 'multiple_choice_single',
'Giona mo ta Chua la gi khien ong gian?',
'["Hay lam on, thuong xot, cham gian, day on thuong, doi y khong phat", "Nghiem khac", "Cong binh", "Phan xet"]',
'[0]', 'Giona trich Xuat 34:6 - ban tinh cua Chua. Dieu tot lanh cua Chua lai khien Giona kho chiu.', '["Cuu Uoc","Giona","Tinh Chua"]', 'Jonah 4:2', 'vi', true, NOW(), NOW()),
('q-jon-014', 'Jonah', 1, 9, 9, 'easy', 'multiple_choice_single',
'Giona noi voi thuy thu: "Toi kinh so Duc Gie-ho-va la Duc Chua Troi tren ___"',
'["Troi, Dang da lam bien va dat kho", "Nui", "Cac than", "Moi vat"]',
'[0]', 'Du dang tron Chua, Giona van tuyen xung Ngai la Dang Sang Tao.', '["Cuu Uoc","Giona","Tuyen xung"]', 'Jonah 1:9', 'vi', true, NOW(), NOW()),
('q-jon-015', 'Jonah', 2, 7, 7, 'medium', 'fill_in_blank',
'Giona cau nguyen: "Khi linh hon toi met lam thi toi ___ Duc Gie-ho-va"',
'[]', '[]', 'Giona 2:7 - Trong tuyet vong, Giona nho den Chua va loi cau nguyen len den den thanh Ngai.', '["Cuu Uoc","Giona","Cau nguyen"]', 'Jonah 2:7', 'vi', true, NOW(), NOW()),

-- MALACHI (need +14)
('q-mal-002', 'Malachi', 1, 2, 2, 'easy', 'multiple_choice_single',
'Ma-la-chi bat dau bang loi Chua noi gi?',
'["Ta yeu cac nguoi", "Ta gian cac nguoi", "Hay an nan", "Hay vang loi"]',
'[0]', 'Ma-la-chi 1:2 - Ngay ca khi dan su bat trung, Chua van tuyen bo tinh yeu. Dan lai hoi: Ngai yeu o cho nao?', '["Cuu Uoc","Ma-la-chi","Tinh yeu"]', 'Malachi 1:2', 'vi', true, NOW(), NOW()),
('q-mal-003', 'Malachi', 1, 6, 6, 'easy', 'multiple_choice_single',
'Chua trach thay te le vi dieu gi?',
'["Dang thu vat co tat cho Chua (khinh danh Ngai)", "Khong cau nguyen", "Khong doc sach", "An cap"]',
'[0]', 'Ma-la-chi 1:8 - Ho dang thu vat mu, que, dau cho Chua. Thu dang cho quan tran thi sao?', '["Cuu Uoc","Ma-la-chi","Cua le"]', 'Malachi 1:6-8', 'vi', true, NOW(), NOW()),
('q-mal-004', 'Malachi', 2, 16, 16, 'medium', 'multiple_choice_single',
'Ma-la-chi 2:16 bay to thai do cua Chua ve ly di nhu the nao?',
'["Ta ghet su ly di vi no phu su oan uoc len vo", "Khong quan tam", "Cho phep tu do", "Chi cam nguoi ngheo"]',
'[0]', 'Chua coi trong hon nhan va ghim giu ket uoc. Ly di khong phai y muon ban dau cua Ngai.', '["Cuu Uoc","Ma-la-chi","Hon nhan"]', 'Malachi 2:16', 'vi', true, NOW(), NOW()),
('q-mal-005', 'Malachi', 3, 1, 1, 'medium', 'multiple_choice_single',
'Ma-la-chi 3:1 tien tri ai se den truoc Chua?',
'["Su gia (Giang Bap-tit) de don duong", "E-li", "Moi-se", "Thien su"]',
'[0]', 'Mac 1:2 ap dung cau nay cho Giang Bap-tit, nguoi don duong cho Chua Gie-su.', '["Cuu Uoc","Tien tri","Giang Bap-tit"]', 'Malachi 3:1', 'vi', true, NOW(), NOW()),
('q-mal-006', 'Malachi', 3, 6, 6, 'easy', 'fill_in_blank',
'Vi ta la Duc Gie-ho-va, ta khong hay ___; nen cac nguoi chua bi tieu diet (Ma 3:6)',
'[]', '[]', 'Chua khong thay doi. Nho su bat bien cua Ngai ma dan su con ton tai du bat trung.', '["Cuu Uoc","Ma-la-chi","Bat bien"]', 'Malachi 3:6', 'vi', true, NOW(), NOW()),
('q-mal-007', 'Malachi', 3, 8, 8, 'easy', 'multiple_choice_single',
'Chua hoi dan su: "Nguoi ta co the ___ Duc Chua Troi sao? Ma cac nguoi da cuop ta"',
'["An cap cua", "Noi doi voi", "Chong lai", "Lam buon"]',
'[0]', 'Ma-la-chi 3:8 - Dan su an cap cua Chua bang cach khong dang phan muoi va cua le.', '["Cuu Uoc","Ma-la-chi","Phan muoi"]', 'Malachi 3:8', 'vi', true, NOW(), NOW()),
('q-mal-008', 'Malachi', 3, 10, 10, 'easy', 'fill_in_blank',
'Hay dem phan muoi day du vao kho, hay thu ta xem ta co mo cac ___ troi do phuc xuong khong',
'[]', '[]', 'Cau Kinh Thanh duy nhat Chua thach thuc con nguoi thu Ngai.', '["Cuu Uoc","Ma-la-chi","Dang hien"]', 'Malachi 3:10', 'vi', true, NOW(), NOW()),
('q-mal-009', 'Malachi', 3, 16, 17, 'easy', 'multiple_choice_single',
'Ma-la-chi 3:16 noi Chua co sach gi ghi lai nhung ai kinh so Ngai?',
'["Sach ky niem", "Sach luat", "Sach su", "Sach tien tri"]',
'[0]', 'Chua ghi nho nhung ai kinh so va ton kinh danh Ngai. Ho la bau vat rieng cua Ngai.', '["Cuu Uoc","Ma-la-chi","Ghi nho"]', 'Malachi 3:16-17', 'vi', true, NOW(), NOW()),
('q-mal-010', 'Malachi', 4, 2, 2, 'medium', 'multiple_choice_single',
'Ma-la-chi 4:2 tien tri "Mat Troi Cong Binh" se moc len voi gi trong canh?',
'["Su chua lanh", "Vinh quang", "Lua", "Anh sang"]',
'[0]', 'Mat Troi Cong Binh = Chua Gie-su. Ngai mang su chua lanh cho nhung ai kinh so Chua.', '["Cuu Uoc","Tien tri","Chua lanh"]', 'Malachi 4:2', 'vi', true, NOW(), NOW()),
('q-mal-011', 'Malachi', 4, 5, 6, 'medium', 'multiple_choice_single',
'Cau cuoi cung cua Cuu Uoc tien tri ai se den truoc ngay lon cua Chua?',
'["Tien tri E-li (Giang Bap-tit)", "Moi-se", "Da-vit", "E-li-se"]',
'[0]', 'Ma-la-chi 4:5 - Chua Gie-su xac nhan Giang Bap-tit lam tron vai tro E-li (Mat 11:14).', '["Cuu Uoc","Tien tri","E-li"]', 'Malachi 4:5-6', 'vi', true, NOW(), NOW()),
('q-mal-012', 'Malachi', 4, 6, 6, 'easy', 'fill_in_blank',
'E-li se lam cho long ___ quay ve cung con cai, va long con cai quay ve cung cha (Ma 4:6)',
'[]', '[]', 'Cau cuoi Cuu Uoc noi ve phuc hoi moi quan he gia dinh. Giang Bap-tit lam tron su vu nay.', '["Cuu Uoc","Ma-la-chi","Gia dinh"]', 'Malachi 4:6', 'vi', true, NOW(), NOW()),
('q-mal-013', 'Malachi', 3, 2, 3, 'easy', 'multiple_choice_single',
'Chua den nhu tho luyen bac va luyen vang de lam gi?',
'["Thanh tay con cai Le-vi de ho dang cua le cong binh", "Huy diet", "Thu thach", "Phan xet"]',
'[0]', 'Su thanh tay khong phai huy diet ma la lam cho tinh sach, nhu luyen kim.', '["Cuu Uoc","Ma-la-chi","Thanh tay"]', 'Malachi 3:2-3', 'vi', true, NOW(), NOW()),
('q-mal-014', 'Malachi', 2, 10, 10, 'medium', 'multiple_choice_single',
'Ma-la-chi 2:10 hoi: "Chung ta chang co chung mot ___ sao? Chang co mot Chua dung nen chung ta sao?"',
'["Cha", "Vua", "Chua", "Nha"]',
'[0]', 'Moi nguoi co chung mot Cha (Dang Sang Tao). Nen phai doi xu tot voi nhau.', '["Cuu Uoc","Ma-la-chi","Hiep nhat"]', 'Malachi 2:10', 'vi', true, NOW(), NOW()),
('q-mal-015', 'Malachi', 3, 11, 11, 'easy', 'multiple_choice_single',
'Khi dang phan muoi day du, Chua hua se lam gi?',
'["Vi cac nguoi cam nhung ke pha pha (bao ve mua mang)", "Ban them vang", "Cho them dat", "Tang quan doi"]',
'[0]', 'Ma-la-chi 3:11 - Chua bao ve mua mang khoi bi pha hai khi dan su vang loi trong viec dang hien.', '["Cuu Uoc","Ma-la-chi","Bao ve"]', 'Malachi 3:11', 'vi', true, NOW(), NOW());
