-- Supplementary: Matthew, Mark, Luke, John, Acts

-- ==================== MATTHEW ====================
INSERT IGNORE INTO questions (id, book, chapter, verse_start, verse_end, difficulty, type, content, options, correct_answer, explanation, tags, source, language, is_active, created_at, updated_at) VALUES
('q-mat-013', 'Matthew', 11, 28, 28, 'easy', 'multiple_choice_single',
'Chúa Giê-su mời: "Hỡi kẻ mệt mỏi và gánh nặng, hãy đến cùng ta, ta sẽ cho các ngươi được ___"',
'["Nghỉ ngơi", "Sức mạnh", "Khôn ngoan", "Giàu có"]',
'[0]', 'Mat 11:28 - Chúa mời tất cả người đang gánh nặng đến với Ngài để được nghỉ ngơi thật sự.', '["Tân Ước","Lời mời","Nghỉ ngơi"]', 'Matthew 11:28', 'vi', true, NOW(), NOW()),
('q-mat-014', 'Matthew', 18, 21, 22, 'medium', 'multiple_choice_single',
'Phi-e-rô hỏi tha thứ bao nhiêu lần. Chúa Giê-su đáp bao nhiêu?',
'["70 lần 7 (không giới hạn)", "7 lần", "3 lần", "100 lần"]',
'[0]', 'Mat 18:22 - Tha thứ không có giới hạn. 70 lần 7 nghĩa là luôn luôn tha thứ.', '["Tân Ước","Tha thứ","Môn đồ"]', 'Matthew 18:21-22', 'vi', true, NOW(), NOW()),

-- ==================== MARK ====================
('q-mar-004', 'Mark', 1, 15, 15, 'easy', 'multiple_choice_single',
'Sứ điệp đầu tiên của Chúa Giê-su khi bắt đầu sứ vụ là gì?',
'["Kỳ đã trọn, nước Chúa đã đến gần, hãy ăn năn và tin Phúc Âm", "Hãy giữ luật pháp", "Hãy theo ta", "Hãy xây đền thờ"]',
'[0]', 'Mac 1:15 - Tóm tắt toàn bộ sứ điệp của Chúa Giê-su trong một câu.', '["Tân Ước","Phúc Âm","Ăn năn"]', 'Mark 1:15', 'vi', true, NOW(), NOW()),
('q-mar-005', 'Mark', 4, 39, 39, 'easy', 'multiple_choice_single',
'Chúa Giê-su nói gì để biển lặng?',
'["Im đi, lặng đi!", "Hãy bình an", "Hãy yên tĩnh", "Đừng sợ"]',
'[0]', 'Mac 4:39 - Chúa có quyền trên thiên nhiên. Gió và biển đều vâng lời Ngài.', '["Tân Ước","Phép lạ","Quyền năng"]', 'Mark 4:39', 'vi', true, NOW(), NOW()),
('q-mar-007', 'Mark', 6, 41, 44, 'easy', 'multiple_choice_single',
'Chúa Giê-su cho 5000 người ăn với bao nhiêu bánh và cá?',
'["5 cái bánh và 2 con cá", "7 bánh và 3 cá", "3 bánh và 5 cá", "10 bánh"]',
'[0]', 'Mac 6:41 - Từ 5 bánh 2 cá, 5000 người ăn no và còn dư 12 giỏ đầy.', '["Tân Ước","Phép lạ","Cung ứng"]', 'Mark 6:41-44', 'vi', true, NOW(), NOW()),
('q-mar-008', 'Mark', 8, 34, 34, 'medium', 'multiple_choice_single',
'Chúa Giê-su nói điều kiện theo Ngài là gì?',
'["Từ bỏ mình, vác thập tự giá và theo ta", "Học thức", "Giàu có", "Tài năng"]',
'[0]', 'Mac 8:34 - Theo Chúa đòi hỏi từ bỏ ý riêng và sẵn sàng chịu khổ vì Ngài.', '["Tân Ước","Môn đồ","Thập tự"]', 'Mark 8:34', 'vi', true, NOW(), NOW()),
('q-mar-009', 'Mark', 9, 23, 24, 'easy', 'multiple_choice_single',
'Người cha xin Chúa chữa con bị quỷ ám nói: "Tôi tin, xin Chúa giúp sự ___"',
'["Ít đức tin của tôi", "Yếu đuối của tôi", "Sợ hãi của tôi", "Ngu dốt của tôi"]',
'[0]', 'Mac 9:24 - Lời cầu nguyện thật thà nhất: thừa nhận đức tin yếu và xin Chúa giúp.', '["Tân Ước","Đức tin","Thật thà"]', 'Mark 9:23-24', 'vi', true, NOW(), NOW()),
('q-mar-010', 'Mark', 10, 14, 15, 'easy', 'multiple_choice_single',
'Chúa Giê-su nói phải nhận nước Chúa như ai?',
'["Như con trẻ", "Như học giả", "Như chiến binh", "Như vua"]',
'[0]', 'Mac 10:15 - Con trẻ tin đơn giản, không nghi ngờ. Đức tin cần sự đơn sơ và tin cậy.', '["Tân Ước","Nước Chúa","Khiêm nhường"]', 'Mark 10:14-15', 'vi', true, NOW(), NOW()),
('q-mar-012', 'Mark', 11, 24, 24, 'easy', 'multiple_choice_single',
'Mac 11:24: Khi cầu nguyện, hãy tin rằng mình đã ___ thì sẽ được',
'["Nhận được", "Nghe", "Thấy", "Hiểu"]',
'[0]', 'Cầu nguyện với đức tin là tin rằng Chúa đã nghe và đáp lời trước khi thấy kết quả.', '["Tân Ước","Cầu nguyện","Đức tin"]', 'Mark 11:24', 'vi', true, NOW(), NOW()),
('q-mar-013', 'Mark', 14, 36, 36, 'medium', 'multiple_choice_single',
'Tại Ghết-sê-ma-nê, Chúa Giê-su cầu nguyện: "Áp-ba, Cha ơi, xin cất chén này, nhưng không theo ___"',
'["Ý con nhưng theo ý Cha", "Ý thế gian", "Ý môn đồ", "Ý thầy tế lễ"]',
'[0]', 'Mac 14:36 - Chúa Giê-su phục tùng ý Cha dù biết sự đau khổ phía trước. Khuôn mẫu cầu nguyện.', '["Tân Ước","Ghết-sê-ma-nê","Vâng phục"]', 'Mark 14:36', 'vi', true, NOW(), NOW()),
('q-mar-014', 'Mark', 15, 34, 34, 'hard', 'multiple_choice_single',
'Chúa Giê-su kêu trên thập tự: "Ê-loi, Ê-loi, la-ma sa-bác-ta-ni?" Đây là tiếng gì?',
'["A-ram, nghĩa là: Đức Chúa Trời tôi, sao Ngài bỏ tôi?", "Hê-bơ-rơ", "Hy Lạp", "La-tinh"]',
'[0]', 'Mac 15:34 - Trích Thi 22:1. Chúa Giê-su gánh tội lỗi nhân loại và bị Cha quay mặt.', '["Tân Ước","Thập tự","Cứu chuộc"]', 'Mark 15:34', 'vi', true, NOW(), NOW()),
('q-mar-015', 'Mark', 16, 15, 15, 'easy', 'multiple_choice_single',
'Chúa Giê-su sai môn đồ: "Hãy đi khắp ___ giảng Phúc Âm cho mọi loài người"',
'["Thế gian", "Giu-đê", "Giê-ru-sa-lem", "Y-sơ-ra-ên"]',
'[0]', 'Mac 16:15 - Phúc Âm không chỉ cho người Do-thái mà cho mọi người, mọi nơi, mọi dân tộc.', '["Tân Ước","Đại mạng lệnh","Truyền giáo"]', 'Mark 16:15', 'vi', true, NOW(), NOW()),

-- ==================== LUKE ====================
('q-luk-008', 'Luke', 4, 18, 19, 'medium', 'multiple_choice_single',
'Chúa Giê-su đọc Ê-sai 61 tại Na-xa-rét và tuyên bố Ngài đến để làm gì?',
'["Giảng Phúc Âm cho kẻ nghèo, chữa lành kẻ đau khổ, phóng thích kẻ bị giam", "Làm vua", "Xây đền thờ", "Lập quân đội"]',
'[0]', 'Lu-ca 4:18-19 - Chúa tuyên bố sứ vụ của Ngài dùng lời Ê-sai: giải phóng và chữa lành toàn diện.', '["Tân Ước","Sứ vụ","Giải phóng"]', 'Luke 4:18-19', 'vi', true, NOW(), NOW()),
('q-luk-009', 'Luke', 6, 38, 38, 'easy', 'multiple_choice_single',
'Lu-ca 6:38: "Hãy ___ thì sẽ được; đo đầy, dằn chặt, lắc tràn trao vào lòng các ngươi"',
'["Cho", "Xin", "Tìm", "Gõ"]',
'[0]', 'Nguyên tắc rộng rãi: cho đi sẽ nhận lại gấp bội. Chúa thương người rộng rãi.', '["Tân Ước","Rộng rãi","Cho đi"]', 'Luke 6:38', 'vi', true, NOW(), NOW()),
('q-luk-011', 'Luke', 10, 41, 42, 'easy', 'multiple_choice_single',
'Giữa Ma-thê bối rối phục vụ và Ma-ri ngồi nghe, Chúa khen ai?',
'["Ma-ri, vì chọn phần tốt nhất", "Ma-thê, vì chăm chỉ", "Cả hai", "Không ai"]',
'[0]', 'Lu-ca 10:42 - Ma-ri chọn phần tốt nhất: ngồi dưới chân Chúa nghe Lời Ngài. Mối quan hệ hơn phục vụ.', '["Tân Ước","Ma-ri","Ưu tiên"]', 'Luke 10:41-42', 'vi', true, NOW(), NOW()),
('q-luk-012', 'Luke', 12, 15, 15, 'easy', 'multiple_choice_single',
'Chúa Giê-su cảnh báo: "Hãy giữ mình về mọi thứ ___"',
'["Tham lam, vì sự sống không ở tại sự dư dật", "Sợ hãi", "Kiêu ngạo", "Ghen tị"]',
'[0]', 'Lu-ca 12:15 - Sự sống thật không phụ thuộc tài sản. Bài học trong dụ ngôn người giàu ngu dại.', '["Tân Ước","Tham lam","Giá trị"]', 'Luke 12:15', 'vi', true, NOW(), NOW()),
('q-luk-013', 'Luke', 17, 15, 16, 'easy', 'multiple_choice_single',
'Trong 10 người phung được chữa lành, bao nhiêu người quay lại cảm ơn?',
'["Chỉ 1 người (và là người Sa-ma-ri)", "5 người", "Tất cả 10", "Không ai"]',
'[0]', 'Lu-ca 17:15-16 - Chỉ 1/10 biết ơn. Chúa Giê-su hỏi: 9 người kia đâu? Bài học về lòng biết ơn.', '["Tân Ước","Biết ơn","Phép lạ"]', 'Luke 17:15-16', 'vi', true, NOW(), NOW()),
('q-luk-014', 'Luke', 18, 13, 14, 'medium', 'multiple_choice_single',
'Trong dụ ngôn người thu thuế và Pha-ri-si, ai được xưng công bình?',
'["Người thu thuế, vì khiêm nhường ăn năn", "Người Pha-ri-si, vì làm nhiều việc tốt", "Cả hai", "Không ai"]',
'[0]', 'Lu-ca 18:14 - Người thu thuế chỉ biết kêu: Chúa ơi, xin thương xót kẻ có tội. Và được xưng công bình.', '["Tân Ước","Khiêm nhường","Công bình"]', 'Luke 18:13-14', 'vi', true, NOW(), NOW()),

-- ==================== JOHN ====================
('q-joh-012', 'John', 4, 13, 14, 'medium', 'multiple_choice_single',
'Chúa Giê-su nói với người đàn bà Sa-ma-ri về nước gì?',
'["Nước sống, uống rồi sẽ không bao giờ khát nữa", "Nước giếng Gia-cốp", "Nước biển", "Nước mưa"]',
'[0]', 'Giăng 4:14 - Nước sống = Đức Thánh Linh và sự sống đời đời. Thỏa mãn nỗi khát sự thật.', '["Tân Ước","Nước sống","Thánh Linh"]', 'John 4:13-14', 'vi', true, NOW(), NOW()),
('q-joh-013', 'John', 6, 35, 35, 'easy', 'multiple_choice_single',
'Chúa Giê-su tuyên bố: "Ta là ___ sự sống"',
'["Bánh", "Nước", "Ánh sáng", "Cửa"]',
'[0]', 'Giăng 6:35 - Ai đến cùng ta sẽ không đói, ai tin ta sẽ không khát. Chúa là nguồn nuôi dưỡng thuộc linh.', '["Tân Ước","Ta là","Bánh sống"]', 'John 6:35', 'vi', true, NOW(), NOW()),
('q-joh-015', 'John', 10, 11, 11, 'easy', 'multiple_choice_single',
'Chúa Giê-su nói: "Ta là Đấng chăn hiền lành; đấng chăn hiền lành vì chiên mà ___"',
'["Phó mạng sống mình", "Chiến đấu", "Tìm cỏ xanh", "Xây chuồng"]',
'[0]', 'Giăng 10:11 - Đấng Chăn Tốt Lành hy sinh mạng sống vì bầy chiên. Hình ảnh đẹp về Chúa Giê-su.', '["Tân Ước","Đấng Chăn","Hy sinh"]', 'John 10:11', 'vi', true, NOW(), NOW()),

-- ==================== ACTS ====================
('q-act-006', 'Acts', 2, 42, 42, 'easy', 'multiple_choice_single',
'Hội thánh đầu tiên bền đỗ trong 4 điều gì?',
'["Sự dạy của sứ đồ, sự thông công, lễ bẻ bánh, sự cầu nguyện", "Chỉ cầu nguyện", "Chỉ nghe giảng", "Chỉ ăn uống"]',
'[0]', 'Công vụ 2:42 - Bốn cột trụ của Hội thánh: dạy dỗ, thông công, bẻ bánh, cầu nguyện.', '["Tân Ước","Hội thánh","Nền tảng"]', 'Acts 2:42', 'vi', true, NOW(), NOW()),
('q-act-007', 'Acts', 3, 6, 6, 'easy', 'multiple_choice_single',
'Phi-e-rô nói với người quẹ trước đền thờ: "Vàng bạc ta không có, nhưng ta cho ngươi điều ta có: nhân danh ___ hãy đứng dậy và bước đi"',
'["Chúa Giê-su Christ", "Đức Chúa Trời", "Môi-se", "Ê-li"]',
'[0]', 'Công vụ 3:6 - Quyền năng chữa lành đến từ danh Chúa Giê-su, không phải tiền bạc.', '["Tân Ước","Phép lạ","Danh Chúa"]', 'Acts 3:6', 'vi', true, NOW(), NOW()),
('q-act-010', 'Acts', 5, 29, 29, 'easy', 'multiple_choice_single',
'Khi bị cấm giảng đạo, các sứ đồ đáp: "Phải vâng lời ___ hơn là vâng lời người ta"',
'["Đức Chúa Trời", "Lương tâm", "Luật pháp", "Truyền thống"]',
'[0]', 'Công vụ 5:29 - Khi luật người chống lại luật Chúa, phải chọn vâng lời Chúa.', '["Tân Ước","Can đảm","Vâng lời"]', 'Acts 5:29', 'vi', true, NOW(), NOW()),
('q-act-011', 'Acts', 7, 59, 60, 'medium', 'multiple_choice_single',
'Ê-tiên, vị tử đạo đầu tiên, cầu nguyện điều gì khi bị ném đá?',
'["Lạy Chúa, xin đừng kể tội này cho họ", "Xin báo thù", "Xin cứu con", "Xin phạt họ"]',
'[0]', 'Công vụ 7:60 - Giống Chúa Giê-su, Ê-tiên tha thứ cho kẻ giết mình. Tiêu chuẩn tha thứ cao nhất.', '["Tân Ước","Ê-tiên","Tha thứ"]', 'Acts 7:59-60', 'vi', true, NOW(), NOW()),
('q-act-012', 'Acts', 8, 30, 31, 'easy', 'multiple_choice_single',
'Phi-líp hỏi hoạn quan Ê-thi-ô-pi: "Ông có hiểu điều mình đọc không?" Ông đáp thế nào?',
'["Làm sao hiểu được nếu không ai giải nghĩa?", "Tôi hiểu rồi", "Không cần giúp", "Tôi đang học"]',
'[0]', 'Công vụ 8:31 - Cần người giải thích Kinh Thánh. Vai trò quan trọng của người dạy dỗ.', '["Tân Ước","Phúc Âm","Giải nghĩa"]', 'Acts 8:30-31', 'vi', true, NOW(), NOW()),
('q-act-014', 'Acts', 17, 11, 11, 'easy', 'multiple_choice_single',
'Dân Bê-rê được khen vì làm gì khi nghe Phao-lô giảng?',
'["Hằng ngày xem xét Kinh Thánh để kiểm tra điều Phao-lô nói có đúng không", "Tin ngay", "Từ chối", "Im lặng"]',
'[0]', 'Công vụ 17:11 - Mẫu mực: nghe giảng rồi kiểm tra lại với Kinh Thánh. Không tin mù quáng.', '["Tân Ước","Bê-rê","Kinh Thánh"]', 'Acts 17:11', 'vi', true, NOW(), NOW()),
('q-act-015', 'Acts', 20, 35, 35, 'easy', 'multiple_choice_single',
'Phao-lô trích lời Chúa Giê-su: "Ban cho có phước hơn ___"',
'["Nhận", "Xin", "Giữ", "Đòi"]',
'[0]', 'Công vụ 20:35 - Lời của Chúa Giê-su không có trong Phúc Âm nhưng được Phao-lô truyền lại.', '["Tân Ước","Rộng rãi","Phước"]', 'Acts 20:35', 'vi', true, NOW(), NOW());
