-- Daily missions: 3 per user per day, auto-generated by tier
CREATE TABLE IF NOT EXISTS daily_mission (
    id          VARCHAR(36) PRIMARY KEY,
    user_id     VARCHAR(36) NOT NULL,
    date        DATE NOT NULL,
    mission_slot INT NOT NULL,
    mission_type VARCHAR(50) NOT NULL,
    config      JSON NOT NULL,
    progress    INT NOT NULL DEFAULT 0,
    target      INT NOT NULL,
    completed   BOOLEAN NOT NULL DEFAULT FALSE,
    completed_at DATETIME NULL,
    bonus_claimed BOOLEAN NOT NULL DEFAULT FALSE,
    created_at  DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

    UNIQUE KEY uk_user_date_slot (user_id, date, mission_slot),
    KEY idx_user_date (user_id, date),
    CONSTRAINT fk_daily_mission_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
