/**
 * Custom Playwright fixtures — authenticated page contexts.
 *
 * Provides tier1Page through tier6Page (pre-authenticated via storageState)
 * and adminPage for admin-panel tests. Also exposes a testApi fixture.
 *
 * storageState files are generated by global-setup.ts.
 */

import { test as base, type Page } from '@playwright/test'
import { TestApi } from '../helpers/test-api'
import path from 'path'
import { fileURLToPath } from 'url'

// Resolve storage-state directory relative to this file
const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)
const STORAGE_DIR = path.join(__dirname, 'storage-states')

type AuthFixtures = {
  tier1Page: Page
  tier2Page: Page
  tier3Page: Page
  tier4Page: Page
  tier5Page: Page
  tier6Page: Page
  adminPage: Page
  testApi: TestApi
}

export const test = base.extend<AuthFixtures>({
  tier1Page: async ({ browser }, use) => {
    const ctx = await browser.newContext({
      storageState: path.join(STORAGE_DIR, 'tier1.json'),
    })
    const page = await ctx.newPage()
    await use(page)
    await ctx.close()
  },

  tier2Page: async ({ browser }, use) => {
    const ctx = await browser.newContext({
      storageState: path.join(STORAGE_DIR, 'tier2.json'),
    })
    const page = await ctx.newPage()
    await use(page)
    await ctx.close()
  },

  tier3Page: async ({ browser }, use) => {
    const ctx = await browser.newContext({
      storageState: path.join(STORAGE_DIR, 'tier3.json'),
    })
    const page = await ctx.newPage()
    await use(page)
    await ctx.close()
  },

  tier4Page: async ({ browser }, use) => {
    const ctx = await browser.newContext({
      storageState: path.join(STORAGE_DIR, 'tier4.json'),
    })
    const page = await ctx.newPage()
    await use(page)
    await ctx.close()
  },

  tier5Page: async ({ browser }, use) => {
    const ctx = await browser.newContext({
      storageState: path.join(STORAGE_DIR, 'tier5.json'),
    })
    const page = await ctx.newPage()
    await use(page)
    await ctx.close()
  },

  tier6Page: async ({ browser }, use) => {
    const ctx = await browser.newContext({
      storageState: path.join(STORAGE_DIR, 'tier6.json'),
    })
    const page = await ctx.newPage()
    await use(page)
    await ctx.close()
  },

  adminPage: async ({ browser }, use) => {
    const ctx = await browser.newContext({
      storageState: path.join(STORAGE_DIR, 'admin.json'),
    })
    const page = await ctx.newPage()
    await use(page)
    await ctx.close()
  },

  testApi: async ({}, use) => {
    const api = new TestApi()
    await api.init()
    await use(api)
  },
})

export { expect } from '@playwright/test'
